### ISSUE TITLE
Bare metal install on machine with 2 10G NICs does not come up

### ISSUE THREAD

**Issue by deniseschannon** [rancher/os#1005]
**RancherOS Version: (ros os version)**
Custom Build of v0.5.0 (os3)

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
Baremetal

Tried to install on machine with 2 10G NICs.

No internet came up, no valid NICs present, unable to configure NICs.

**Comment by joshwget** [comment]
Problem was introduced in #971, so it's likely related to Docker 1.11 in some way

**Comment by joshwget** [comment]
Fixed by #1028
