### ISSUE TITLE
Kubernetes fails to create pod on RancherOS

### ISSUE THREAD

**Issue by liyimeng** [rancher/os#1036]
**RancherOS Version: (ros os version)**
0.4.5
**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
KVM

Deploy Kubernetes on RancherOS go well, but after that, you fail to create any pods with kubectl, while the static pod in hyperkube works nicely. 

<pre>
[rancher@rancher ~]$ ./kubectl describe pods 
Name:		test-pod
Namespace:	default
Node:		127.0.0.1/127.0.0.1
Start Time:	Mon, 20 Jun 2016 12:44:13 +0000
Labels:		<none>
Status:		Pending
IP:		127.0.0.1
Controllers:	<none>
Containers:
  test-pod:
    Container ID:	
    Image:		busybox
    Image ID:		
    Port:		
    Command:
      sleep
      3600
    State:			Waiting
      Reason:			ContainerCreating
    Ready:			False
    Restart Count:		0
    Environment Variables:	<none>
Conditions:
  Type		Status
  Initialized 	True 
  Ready 	False 
  PodScheduled 	True 
Volumes:
  run:
    Type:	HostPath (bare host directory volume)
    Path:	/run
  default-token-bik2x:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	default-token-bik2x
QoS Tier:	BestEffort
Events:
  FirstSeen	LastSeen	Count	From			SubobjectPath	Type		Reason		Message
  ---------	--------	-----	----			-------------	--------	------		-------
  6m		6m		1	{default-scheduler }			Normal		Scheduled	Successfully assigned test-pod to 127.0.0.1
  6m		5s		32	{kubelet 127.0.0.1}			Warning		FailedMount	Unable to mount volumes for pod "test-pod_default(b0f63ab7-36e4-11e6-a26b-525400603656)": exit status 1
  6m		5s		32	{kubelet 127.0.0.1}			Warning		FailedSync	Error syncing pod, skipping: exit status 1

</pre>

**Comment by ibuildthecloud** [comment]
@liyimeng Can you give steps to reproduce and then we will look into what is happening.  I'm guessing hyperkube won't work on RancherOS if it does any nsenter tricks.  If we can figure out how to reproduce we can probably help hyperkube fix this.

**Comment by liyimeng** [comment]
Hi @ibuildthecloud, it is pretty easy to re-produce since the problem is almost consistent. Here is the steps to reproduce: 
- 1, Deploy a ROS 
- 2, Deploy K8s  with command: 
<pre>
docker run -d \
    --volume=/:/rootfs:ro \
    --volume=/sys:/sys:ro \
    --volume=/var/lib/docker/:/var/lib/docker:rw \
    --volume=/var/lib/kubelet/:/var/lib/kubelet:rw,shared \
    --volume=/var/run:/var/run:rw \
    --net=host \
    --pid=host \
    --privileged \
    gcr.io/google_containers/hyperkubeamd64:1.2.4 \
    /hyperkube kubelet \
        --containerized \
        --hostname-override=127.0.0.1 \
        --api-servers=http://localhost:8080 \
        --config=/etc/kubernetes/manifests \
        --cluster-dns=10.0.0.10 \
        --cluster-domain=cluster.local \
        --allow-privileged --v=2
</pre>
- 3, Try to run a pod, e.g. "kubectl run nginx"  you will see the problem. 

I also replace step 2 with using rancher to deploy K8s, the same issue as long as I run rancheros in host.  However, I tested it with rancher 1.0.1, not the latest version.

**Comment by liyimeng** [comment]
Hi @ibuildthecloud are you able to reproduce this?

**Comment by ibuildthecloud** [comment]
@liyimeng can you test this on v0.5.0-rc2?  I'm sorry I haven't had time to look at this.

**Comment by liyimeng** [comment]
@ibuildthecloud no help, kubelet logs says.

<pre>
I0630 20:06:56.154271    1150 nsenter_mount.go:185] Failed findmnt command for path /var/lib/kubelet/pods/a5bd2fd353c9b9520d8b83a4977451ae/volumes/kubernetes.io~empty-dir/data: exit status 1
I0630 20:07:10.037514    1150 nsenter_mount.go:185] Failed findmnt command for path /var/lib/kubelet/pods/1df6a8b4d6e129d5ed8840e370203c11/volumes/kubernetes.io~empty-dir/varetcd: exit status 1
I0630 20:08:14.917705    1150 nsenter_mount.go:185] Failed findmnt command for path /var/lib/kubelet/pods/a5bd2fd353c9b9520d8b83a4977451ae/volumes/kubernetes.io~empty-dir/data: exit status 1
I0630 20:08:19.917936    1150 nsenter_mount.go:185] Failed findmnt command for path /var/lib/kubelet/pods/1df6a8b4d6e129d5ed8840e370203c11/volumes/kubernetes.io~empty-dir/varetcd: exit status 1
</pre>

Not sure if this is k8s problem, or rancheros one. However, the same setup works on CentOS 7.

**Comment by liyimeng** [comment]
Just dig a little more. It seems only fail to mount secret volume.

**Comment by liyimeng** [comment]
After investigation, I would like to close since I believe it is more k8s problem that RancherOS ones.

**Comment by shamalco** [comment]
Hi @liyimeng I facing the same issue as you mentioned here. Did you manage to resolve it or figure out what is causing this? For some reason only the secret volumes fail on RancherOS

Thanks.
