### ISSUE TITLE
Docker server version

### ISSUE THREAD

**Issue by prologic** [rancher/os#1044]
**RancherOS Version: (ros os version)**

0.4.5

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**

Proxmox VM

----

This is more of a question around process. What are you doing to keep up-to-date with upstream Docker? Currently RancherOS 0.4.5 (the latest) is 3 versions behind. This makes it hard to upgrade because if you upgrade your client(s) you can't talk to older server api(s).

Is there something we (RancherOS users) can do to keep up-to-date with the Docker server binary more easily/quickly than the RancherOS releases?

**Comment by deniseschannon** [comment]
You can easily change the user docker version to whatever version you want. 

http://docs.rancher.com/os/configuration/custom-docker/
