### ISSUE TITLE
Show current console running in `sudo ros console list`

### ISSUE THREAD

**Issue by datawolf** [rancher/os#1046]
**RancherOS Version: (ros os version)**

v0.4.5-dev-1

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**

baremetal

(1) the current output of the command `sudo ros os list` is 

```
$ sudo ros console list          
default
centos
debian
fedora
ubuntu
```

It is better that `sudo ros console list` should be show the status of the consoles eg

```
$ sudo ros console list
current: default
Disabled: centos
Disabled: debian
Disabled: fedora
Disabled: ubuntu
```

when we switch to ubuntu console, the output of the command should be 

```
$ sudo ros console list
Disabled: default
Disabled: centos
Disabled: debian
Disabled: fedora
current: ubuntu
```

when we enable ubuntu console. and before reboot

```
$ sudo ros console list
current: default
Disabled: centos
Disabled: debian
Disabled: fedora
Enabled: ubuntu
```

(2) `sudo ros console enable` command should ensure only one console can be enabled.

**Comment by joshwget** [comment]
(1) would definitely be a good change. I think matching the appearance of `ros service list` would be best (with the addition of the "current" option).
```
disabled amazon-ecs-agent
enabled  kernel-headers
disabled kernel-headers-system-docker
disabled open-vm-tools
```
(2) is actually done already. `rancher.console` is a string which means only one can be set at a time.

**Comment by datawolf** [comment]
Thanks @joshwget ,(2) has indeed done. I would like to add (1) on the new version v0.5.0.

**Comment by deniseschannon** [comment]
Verified with v0.5.0-rc1
```
$ sudo ros console list
disabled centos
disabled debian
disabled default
enabled  fedora
current  ubuntu
```
