### ISSUE TITLE
Add openstack images to the standard release process

### ISSUE THREAD

**Issue by hh** [rancher/os#1050]
I'm not sure if the openstack image will be built from https://github.com/rancher/os-images (nothing there yet) or https://github.com/rancher/os/tree/master/scripts/images/openstack

Currently the [images/openstack/scripts/build.sh](https://github.com/rancher/os/blob/master/scripts/images/openstack/scripts/build.sh#L18) runs `ros install -d /dev/vda -f --no-reboot` which pulls rancher/os:lastest

Is there a way to use the ISO itself to install to disk?

I took a quick look at what we have available via /dev/sr0 at the time of  `ros install` above:

```
[root@rancher /]# modprobe isofs ; mkdir -p /cdrom ; mount /dev/cdrom /cdrom
[root@rancher /]# ls /cdrom/boot/   
initrd    isolinux  vmlinuz
```

**Comment by hh** [comment]
Looks like we can get at the kernel / initrd pretty easily:

```
[root@rancher /]# mkdir -p /target ; mount /dev/vda1 /target
[root@rancher /]# modprobe isofs ; mkdir -p /cdrom ; mount /dev/cdrom /cdrom
[root@rancher /]# cp /cdrom/boot/vmlinuz /target/boot/vmlinuz-116c147-rancheros
[root@rancher /]# cp /cdrom/boot/initrd /target/boot/initrd-116c147-rancheros
```

**Comment by joshwget** [comment]
The kernel and initrd are produced as artifacts when building an ISO, so there's no need extract them. They should be in `dist/artifacts` after completing a build.

I agree that the OpenStack image builder should probably just use those artifacts rather than going through an installer image. In the meantime, building a custom installer image and modifying the builder to point to it should have the same effect.

**Comment by hh** [comment]
Running dapper results in kvm running within a docker container.
The resulting kvm instance doesn't seem to have networking.
Running the same resulting qemu command outside of docker works fine.

```
RancherOS rancher /dev/tty2
docker-sys: 172.18.42.1 lo: 127.0.0.1
rancher login: time="2016-06-27T21:06:08Z" level=info msg="No install type speci
fied...defaulting to generic"
time="2016-06-27T21:06:08Z" level=warning msg="Cloud-config not provided: you mi
ght need to provide cloud-config on boot with ssh_authorized_keys"
Installing from instant/os
Unable to find image 'instant/os:latest' locally
Pulling repository docker.io/instant/os
system-docker: Error while pulling image: Get https://index.docker.io/v1/reposit
ories/instant/os/images: dial tcp: lookup index.docker.io on [::1]:53: read udp
 [::1]:37763->[::1]:53: read: connection refused.
See 'system-docker run --help'.
time="2016-06-27T21:06:08Z" level=fatal msg="Failed to run install" err="exit st
atus 125"

RancherOS rancher /dev/tty2
docker-sys: 172.18.42.1 lo: 127.0.0.1
rancher login: rancher
Password: 
[rancher@rancher ~]$ ping 8.8.8.8 -c 1
PING 8.8.8.8 (8.8.8.8): 56 data bytes

--- 8.8.8.8 ping statistics ---
1 packets transmitted, 0 packets received, 100% packet loss
[rancher@rancher ~]$ ip a show dev eth0
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP gr
oup default qlen 1000
link/ether 52:54:00:12:34:56 brd ff:ff:ff:ff:ff:ff
inet 10.0.2.15/24 brd 10.0.2.255 scope global eth0
valid_lft forever preferred_lft forever
inet6 fe80::5054:ff:fe12:3456/64 scope link
valid_lft forever preferred_lft forever
[rancher@rancher ~]$ route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         10.0.2.2        0.0.0.0         UG    202    0        0 eth0
10.0.2.0        0.0.0.0         255.255.255.0   U     202    0        0 eth0
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
172.18.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker-sys
```

I looked at how the image is being run to see if I could run qemu from outside of docker:

```
$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
51303c9c4e75        openstack:master    "/source/scripts/buil"   36 minutes ago      Up 36 minutes                           openstack-BsClmfp
$ docker exec -ti openstack-BsClmfp ps auxww | grep qemu
root        42  1.3  0.8 4708136 582768 ?      Sl+  21:05   0:12 qemu-system-x86_64 -enable-kvm -curses -drive if=virtio,file=build/hd.img -cdrom assets/rancheros.iso -m 4096 -fsdev local,id=conf,security_model=none,path=/source/build -device virtio-9p-pci,fsdev=conf,mount_tag=config-2
```

Running ```qemu-system-x86_64 -enable-kvm -curses -drive if=virtio,file=build/hd.img -cdrom assets/rancheros.iso -m 4096 -fsdev local,id=conf,security_model=none,path=/source/build`` with the same iso outside of docker/dapper seems to work fine.

It feels like it might be easier just to partition/mount/format the qemu qcow2 image without launching qemu.

**Comment by hh** [comment]
https://github.com/ii/os/commit/730f38cf8e720143997c4f02c612394a87d0b0e9 has my changes so far in trying to get this to work (using a COPY for the rancheros.iso).

The sleep is there so a can manually jump in and run qemu in another window via docker exec).

I had to increase the memory because my image seems to be a bit larger for some reason.

**Comment by joshwget** [comment]
Not having to run QEMU would also be nice! There's definitely some room for improvement with the builder. I think it's currently built with just our internal use case in mind, which is essentially just making an image after each release.

**Comment by niusmallnan** [comment]
https://github.com/rancher/os-packer/tree/master/openstack
