### ISSUE TITLE
remove hard code

### ISSUE THREAD

**Issue by datawolf** [rancher/os#1052]
**RancherOS Version: (ros os version)**

v0.5.0

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**

berematal

The current  RancherOS have some hard-code in file `cmd/control/selinux.go` and `cmd/control/console.go`, eg

```
 53    fmt.Sprintf("rancher/os-selinuxtools:%s", config.VERSION+config.SUFFIX), "bash"}
 76    Image:      fmt.Sprintf("rancher/os-base:%s", config.VERSION),
```

we should make them configurable, because user may not connect docker hub in company intranet.

**Comment by joshwget** [comment]
The idea for `cmd/control/console.go` was to use the built-in `os-base` image to avoid pulling any image from Docker Hub.

If I understood your issue correctly, I think #1056 will this.

**Comment by datawolf** [comment]
Thanks @joshwget I have verified it

**Comment by joshwget** [comment]
Thanks @datawolf!
