### ISSUE TITLE
[os-images] Unable to install correct kernel headers when using custom kernel

### ISSUE THREAD

**Issue by datawolf** [rancher/os#1053]
**RancherOS Version: (ros os version)**

v0.5.0

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**

barematal

when we build our own custom RancherOS with custom kernel. we can not install correct kernel headers. Currently, the os-header service always download kernel from `https://github.com/rancher/os-kernel/releases/download/${VER}/build.tar.gz`, It should be configurable.

**Comment by deniseschannon** [comment]
@datawolf Would you be able to verify this issue for me using v0.5.0-rc1?

**Comment by datawolf** [comment]
when merged this pr https://github.com/rancher/os-images/pull/93. this issue is verified with the following command

```
$ sudo ros config set rancher.environment.KERNEL_HEADERS_URL http://containeros.huawei.com/code.huawei.com/hulk/hulk-vhulk3.6.1-2/x86_64/build.tar.gz
$ sudo ros config get rancher.environment
KERNEL_HEADERS_URL: http://containeros.huawei.com/code.huawei.com/hulk/hulk-vhulk3.6.1-2/x86_64/build.tar.gz

$ sudo ros service enable kernel-headers
...
...
$ sudo ros service list
disabled amazon-ecs-agent
enabled  kernel-headers
disabled kernel-headers-system-docker
$ sudo reboot
```
