### ISSUE TITLE
Error out or throw warning if invalid console is set

### ISSUE THREAD

**Issue by deniseschannon** [rancher/os#1060]
If possible, we should error out if someone tries to set a rancher console that doesn't exist.

```
$ sudo ros config set rancher.console test1
# ERROR NEEDED
$ sudo ros console switch test2
# ERROR NEEDED
```

This is weird that after I incorrectly set the console using `sudo ros config set`, it shows me the invalid console in my cloud-config.

```
$ sudo ros config export
rancher:
  console: test1
```

When I go to reboot the host, I end up back in the default console.

**Comment by datawolf** [comment]
https://github.com/rancher/os/pull/1074

**Comment by deniseschannon** [comment]
Verified with v0.8.0-rc4

```
$ sudo ros console switch test2
> FATA[0000] test2 is not a valid console
```
