### ISSUE TITLE
Check the validity of the console name

### ISSUE THREAD

**Issue by datawolf** [rancher/os#1073]
**RancherOS Version: (ros os version)**

v0.5.0-rc2

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**

baremetal

If use want to enable or switch to `ubuntu` console and type the wrong service name `ubunut`. there is no any prompt.

It is better to Warn user when the console name is invalid.

**Comment by datawolf** [comment]
https://github.com/rancher/os/pull/1074

**Comment by deniseschannon** [comment]
Duplicate of #1060
