### ISSUE TITLE
console or service? may be we need a proper way to check its name

### ISSUE THREAD

**Issue by datawolf** [rancher/os#1080]
**RancherOS Version: (ros os version)**

v0.5.0-rc2

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**

barematel

when I type the command `sudo ros service enable ubuntu`, It pull `rancher/os-ubuntuconsole` image and the output `sudo ros config get rancher.services_include` is 

```
$ sudo ros c get rancher.services_include 
ubuntu: true

```

`ubuntu` is a **console** not a **service**. so I think we need a proper way to check console and service name when user enable/disable services  or switch consoles.

**Comment by deniseschannon** [comment]
Verified with v0.8.0-rc4. 

Consoles/Services/Engines are checked independently, but still able to create custom services
