### ISSUE TITLE
Automatic resizing for Raspberry Pi

### ISSUE THREAD

**Issue by deniseschannon** [rancher/os#1084]
**RancherOS Version: (ros os version)**
v0.5.0

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
Unable to use resize with raspberry pi 3.

**Comment by joshwget** [comment]
We don't automatically resize to the size of the SD card, but manual resizing should be fine.

**Comment by gjongenelen** [comment]
Is there any documentation on resizing the root partition on the RaspberryPI? When using ** resize2fs** I'm getting the error "Resource busy".

**Comment by s80275** [comment]
How to manual resizing?

**Comment by BrianAdams** [comment]
https://forums.rancher.com/t/resizing-the-primary-partition-on-the-raspberry-pi/3515

Same issue. Anyway I try to expand the partition from within the running SD card fails with resize2fs throwing:
```
resize2fs: Device or resource busy while trying to open /dev/mmcblk0p2
Couldn't find valid filesystem superblock.
```

**Comment by jgato** [comment]
I am also stuck with this issue. I cannot use ros install (I guess it has not sense because I have a full RancherOS installed, right?), and I cannot resize the partition.

What I am trying to do is include a rasbperry pi into my rancher infrastructure running a Rancher Agent.

**Comment by BrianAdams** [comment]
As a work around, I used a linux computer to manually complete the resize of the image simply following the generic SD card expand partitions instructions for Raspi.

I suspect that when running on the device and manually trying to expand the partition we need to run e2fsck before running the resize2fs command.  The only problem is that it is the one utility not built in to the image so I have not had a chance to confirm.

**Comment by alkar** [comment]
Automatic resizing isn't an issue as far as I'm concerned but it should be possible to resize without the use of an external system. Even a set of manual instructions that we can run on the pi itself to resize the disk should be great moving forward.

**Comment by jnovack** [comment]
> Even a set of manual instructions that we can run on the pi itself to resize the disk should be great moving forward.

I updated the docs to perform a work-around using the extra space as a mounted partition for the user-docker.

**Comment by alkar** [comment]
@jnovack thanks for documenting this workaround, it should at least allow people to utilise 100% of their available space.

**Comment by jgato** [comment]
@jnovack  dont you think that step 10 should be previous to step 8? Otherwise you cannot mount the partition without formating. At least it is what I did...

**Comment by jnovack** [comment]
@jgato An admin updated the docs after I posted them, so I assume s/he knows what s/he is doing. :)

**Comment by SvenDowideit** [comment]
@joshwget is this ready for testing?

**Comment by joshwget** [comment]
@SvenDowideit It was part of the buildroot update that was rolled back so I don't think it's ready to test anymore. If you still plan on updating buildroot for v0.8.0 then it can make it in.

**Comment by SvenDowideit** [comment]
so running 

```
[root@rancher rancher]# growpart /dev/mmcblk0 2
....
[root@rancher rancher]#DISABLE_FLAG_EXCLUSIVE=1 resize2fs /dev/mmcblk0p2`
resize2fs 1.43.1 (08-Jun-2016)
Please run 'e2fsck -f /dev/mmcblk0p2' first.

[root@rancher rancher]# e2fsck -f /dev/mmcblk0p2
e2fsck 1.43.1 (08-Jun-2016)
/dev/mmcblk0p2 is in use.
e2fsck: Cannot continue, aborting.
```

on v1.0.2 gets us further - but now I really need to wire it up to the `rancher.state.auto_reize`

**Comment by SvenDowideit** [comment]
for today, I cheated, and did the resize on the same linux box I did the `dd of=/dev/sdb`...

**Comment by SvenDowideit** [comment]
or on the other notebook, while testing ssp fixes:

```
-rw-r--r-- 1 sven sven 500M Jun 22 12:28 rancheros-raspberry-pi64.img
sven@y260:~/releases/v2017.02.3-glibc-ssp-all/build$ sudo dd if=rancheros-raspberry-pi64.img of=/dev/mmcblk0
1024000+0 records in
1024000+0 records out
524288000 bytes (524 MB, 500 MiB) copied, 109.958 s, 4.8 MB/s
sven@y260:~/releases/v2017.02.3-glibc-ssp-all/build$ sudo e2fsck -f /dev/mmcblk0p2
e2fsck 1.43.4 (31-Jan-2017)
Pass 1: Checking inodes, blocks, and sizes
Pass 2: Checking directory structure
Pass 3: Checking directory connectivity
Pass 4: Checking reference counts
Pass 5: Checking group summary information
rootfs: 2000/121344 files (0.1% non-contiguous), 52581/121344 blocks
sven@y260:~/releases/v2017.02.3-glibc-ssp-all/build$ sudo growpart /dev/mmcblk0 2
CHANGED: partition=2 start=53248 old: size=970752 end=1024000 new: size=15470559,end=15523807
sven@y260:~/releases/v2017.02.3-glibc-ssp-all/build$ sudo e2fsck -f /dev/mmcblk0p2
e2fsck 1.43.4 (31-Jan-2017)
Pass 1: Checking inodes, blocks, and sizes
Pass 2: Checking directory structure
Pass 3: Checking directory connectivity
Pass 4: Checking reference counts
Pass 5: Checking group summary information
rootfs: 2000/121344 files (0.1% non-contiguous), 52581/121344 blocks
sven@y260:~/releases/v2017.02.3-glibc-ssp-all/build$ sudo resize
resize      resize2fs   resizecons  resizepart  
sven@y260:~/releases/v2017.02.3-glibc-ssp-all/build$ sudo resize
resize      resize2fs   resizecons  resizepart  
sven@y260:~/releases/v2017.02.3-glibc-ssp-all/build$ sudo resize2fs /dev/mmcblk0p2
resize2fs 1.43.4 (31-Jan-2017)
Resizing the filesystem on /dev/mmcblk0p2 to 1933819 (4k) blocks.
The filesystem on /dev/mmcblk0p2 is now 1933312 (4k) blocks long.
```

**Comment by niusmallnan** [comment]
We have documentation about manual resizing: https://rancher.com/docs/os/v1.x/en/installation/running-rancheros/server/raspberry-pi/

We need to support automatic resizing.

**Comment by Jason-ZW** [comment]
Workaround:
```
$ ln -s /dev/mmcblk0p2 /dev/root
$ growpart /dev/mmcblk0 2
$ partprobe /dev/mmcblk0
$ resize2fs /dev/mmcblk0p2
```
