### ISSUE TITLE
It seems that cloud-config didn't work when creating a instance on openstack using openstack image

### ISSUE THREAD

**Issue by javagg** [rancher/os#1085]
**RancherOS Version: (ros os version)**
0.5.0
**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
openstack

my cloud-config content
```
#cloud-config
ssh_authorized_keys:
  - ssh-rsa AAAAB3... miteke-os-key-1
```

when I try to login as rancher, it says "Server refused our key"

**Comment by deniseschannon** [comment]
How did you pass in your cloud-config? Did you enable the "config drive" option?

**Comment by joshwget** [comment]
Using the config drive should be enabled by default. We use it for all of our testing, so I'm pretty certain there's nothing wrong with that feature in itself. I'm pretty unfamiliar with OpenStack though, so there could be other relevant details here that I'm unaware of.

Were you using RancherOS prior to v0.5? I'm curious if this can be reproduced on older versions.

**Comment by javagg** [comment]
@deniseschannon It worked when I enable this option! Thanks!

**Comment by javagg** [comment]
@joshwget problem solved. my mistake.

**Comment by TravSalesman** [comment]
I know this thread is pretty old, but I wanted to add the information, that the validation tool that is provided with RancherOS helped me identify a similar problem. With the tool I was able to identify the wrong characters in my cloud-config.yml. In my case it was an incorrectly encoded tab character. 

`sudo ros config validate -i cloud-config.yml`

Maybe this will be helpful for anyone in the future
