### ISSUE TITLE
v0.5.0 upgrade, stack service stuck "initializing"

### ISSUE THREAD

**Issue by pulberg** [rancher/os#1091]
**RancherOS Version: (ros os version)** v0.5.0

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)** AWS

After upgrading a RancherOS host to v0.5.0 some services in stacks are stuck in “initializing” state –

![image](https://cloud.githubusercontent.com/assets/11069351/16551388/c638d05c-417d-11e6-95ae-cf1b6b225959.png)

In order to fix this, I have to either stop the stack completely and start it again, or I have to restart the affected service.

**Comment by deniseschannon** [comment]
What version of Rancher are you running? I'd like to try and reproduce.

How many hosts do you have in your environment?

**Comment by pulberg** [comment]
@deniseschannon This is happening on hosts after I upgrade them to v0.5.0, this issue is happening regardless of the number of hosts, and is actually worse in envs with multiple hosts, the LB's are not honoring the scheduling rules, will create a new ticket for that issue.

**Comment by deniseschannon** [comment]
@pulberg The services stuck in `Initializing` are typically in that state when cross host communication fails.

Can you exec into the network agent container on one of the v0.5.0 hosts and ping another ip of another network agent? 

Is this the same setup that has the hosts with the issues filed for #1090, where you can't ssh into these hosts?

**Comment by pulberg** [comment]
@deniseschannon In an env with multiple hosts, I can ping other network agents from within a network agent - 

rancher@P-RHST04 ~]$ docker exec -i -t  5b3 /bin/bash
root@5b370e03e07f:/# ping 10.42.60.39
PING 10.42.60.39 (10.42.60.39) 56(84) bytes of data.
64 bytes from 10.42.60.39: icmp_seq=1 ttl=64 time=0.800 ms
64 bytes from 10.42.60.39: icmp_seq=2 ttl=64 time=0.793 ms
64 bytes from 10.42.60.39: icmp_seq=3 ttl=64 time=0.799 ms
^C
--- 10.42.60.39 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 1999ms
rtt min/avg/max/mdev = 0.793/0.797/0.800/0.023 ms


Yes, these are the same hosts as #1090, but I am able to ssh now after rebooting the hosts through AWS console, the ssh issues only occurred after the Rancher upgrade reboot process.

**Comment by deniseschannon** [comment]
I was able to reproduce this issue temporarily, but when I refreshed the UI, the health checks were satisified. Typically load balancers get stuck in initializing when health checks are failing and this is cause cross host communication is failing. In my case, my cross host communication  (communication between the existing managed network and my newly upgraded host with v0.5.0) took a couple of minutes before getting set up.

Some other notes:
After upgrading from Rancher v1.0.2 -> Rancher v1.1.0, the agent-instance image has changed from v0.8.1 -> v0.8.3. 
Whenever a host is rebooted (in this case from upgrading ros v0.4.5 to v0.5.0), the health check of the load balancer fails, which deletes the existing load balancer (v0.8.1) on the host. When the host comes back up and the network agent syncs back up, Rancher realizes a load balancer should be launched on the host and will spin up a new load balancer using the updated image (v0.8.3). 

If the cross host networking is working, then the health checks should resolve itself and the services will automatically go into active state. 

If this happens again, can you refresh your browser before attempting to restart the services? I think there might be a delay in the UI and when the services are actually active. I believe that once cross host communication has set up, it would resolve by itself.

**Comment by pulberg** [comment]
Then it would appear there is some issue with the health-check mechanism, as I still have running agent-instances v0.8.1, even after several reboots.

`5b370e03e07f        rancher/agent-instance:v0.8.1                                                                            "/etc/init.d/agent-in"   5 weeks ago         Up 2 days           0.0.0.0:500->500/udp, 0.0.0.0:4500->4500/udp   a17c1479-afd1-4211-925f-3626560002a9`

`671ced922aa8        rancher/agent-instance:v0.8.1                                                                            "/etc/init.d/agent-in"   5 weeks ago         Up 2 days           0.0.0.0:500->500/udp, 0.0.0.0:4500->4500/udp   8e51c3b4-c41b-49bf-a60a-8d009f0d3147`

`f9076486dc16        rancher/agent-instance:v0.8.1                                                                            "/etc/init.d/agent-in"   5 weeks ago         Up 2 days           0.0.0.0:8080->8080/tcp                         r-docker-test-pulberg_load-balancer_2`

**Comment by deniseschannon** [comment]
Sorry, I should have clarified. 

When you upgrade to v1.1.0, we will only update to the new tagged agent-instance images if those containers are deleted. It's okay to have a mixed group of agent-instances as we internally update the container for whatever changes are in the new tagged image. We only create new containers with the new tagged version when the network agent or load balancer is destroyed.

For the agent-instance that you show above, it looks like 2 of them are network agents, which is expected to remain on v0.8.1. For the last one, is it on the host that is still on v0.4.5 or on a host that is on v0.5.0?

**Comment by pulberg** [comment]
The last one is in a stack on my Dev env/host, which I upgraded to v0.5.0.

**Comment by deniseschannon** [comment]
How many hosts are in your dev environment? 1 or more?

**Comment by pulberg** [comment]
Just 1

**Comment by deniseschannon** [comment]
As discussed, this should not occur if cross host communication is up. It might take a couple of minutes for it sync up after an OS upgrade, please re-open if you can't get cross host communication working across hosts after upgrade.
