### ISSUE TITLE
Missing v0.5.0 images on Docker Hub

### ISSUE THREAD

**Issue by robbertkl** [rancher/os#1092]
Hi, I have my own system service, which uses `rancher/os-base` as a base image. With v0.5.0 being released, I wanted to create a v0.5.0 tag of my service, based on `rancher/os-base:v0.5.0`. However, the v0.5.0 images for os-base (and other system services) are not available on Docker Hub: https://hub.docker.com/r/rancher/os-base/tags/

Doesn't the installer or the upgrade process pull these images from Docker Hub in order to install the system? Are they being pulled from somewhere else? When can I expect to see the v0.5.0 images on Docker Hub? Or do I have to `sudo system-docker build` my service on each of my machines?

Thanks in advance!

**Comment by joshwget** [comment]
Sorry, we forgot to push the `rancher/os-base` image. It should be available now!

**Comment by deniseschannon** [comment]
@robbertkl If you have further questions, please let us know!
