### ISSUE TITLE
/run shared mount propagation is overpowered 

### ISSUE THREAD

**Issue by liyimeng** [rancher/os#1095]
**RancherOS Version: (ros os version)**
v0.5.0-rc2
**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
baremetal

Shared mount propagation seem take no effect: 

<pre>
sudo mount --make-shared /run
sudo findmnt /run
TARGET SOURCE FSTYPE OPTIONS
/run   none   tmpfs  rw,relatime
/run   none   tmpfs  rw,relatime
</pre>

If run a container with shared propagation mode will result error like: 

Path /run is mounted on /run but it is not a shared mount.

**Comment by liyimeng** [comment]
Hi, 
I find the problem is only happen on /run, it seem /run have got a double mounted
<pre>
findmnt -o TARGET,PROPAGATION /run
TARGET PROPAGATION
/run   private
/run   shared
</pre>

Can anyone explain whe /run is mounted in such way?

**Comment by liyimeng** [comment]
I think /run is mounted with shared propagation.  However. because of the duplicated mount, docker daemon mistake private as the propagation mode and refuse to work.

**Comment by SvenDowideit** [comment]
@liyimeng can you tell me more about what you're trying to achieve?

**Comment by liyimeng** [comment]
A container that would like to make use of shared mount propagation on /run will not possible to work because of this. And shared mount propagation is a very popular need on /run.

**Comment by ibuildthecloud** [comment]
This should have been addressed already.  For user docker I believe mounts are shared.  We did this in 0.6 or maybe right at the end of 0.5

**Comment by liyimeng** [comment]
@ibuildthecloud should I close this one now?

**Comment by deniseschannon** [comment]
@liyimeng If you are able to use shared mounts, then please feel free to close.
