### ISSUE TITLE
Resource Management 

### ISSUE THREAD

**Issue by galindro** [rancher/os#1097]
I want to know how RancherOS manages the host resources to user containers. 
How CPU time and memory are shared between containers?
Is it possible to a process running inside a user container to stuck the entire system or there is a kind of "resource usage protection" like the hypervisors (VMware ESXi, Xen) implements?

**Comment by vincent99** [comment]
RancherOS doesn't do anything specific.  Docker has various options to manage resource limits and priority when there is contention, e.g. https://docs.docker.com/engine/reference/run/#cpu-share-constraint

**Comment by joshwget** [comment]
@galindro I'm going to go ahead and close this. If you have any further questions, please post in the forums or open another issue!
