### ISSUE TITLE
Kernel warning during boot: WARNING: CPU: 3 PID: 551 at crypto/algapi.c:349 crypto_wait_for_test+0x56/0x5f()

### ISSUE THREAD

**Issue by sheng-liang** [rancher/os#1100]
**RancherOS Version: (ros os version)** 0.5.0

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)** VMware workstation
[kernel-log.txt](https://github.com/rancher/os/files/351094/kernel-log.txt)

**Comment by SvenDowideit** [comment]
I'm going to close this, its been a long time, and we're at v1.0 now.
