### ISSUE TITLE
Implement 'runcmd' cloud-config keys

### ISSUE THREAD

**Issue by joshwget** [rancher/os#1102]
`runcmd` should probably just be a simpler alternative to writing to `/opt/rancher/bin/start.sh`. This means that the commands will:

1. Run at the start of the console container
2. Run before User Docker begins
3. Be run on each boot (or each time the console container is restarted, more accurately)

I'm still unsure when `bootcmd` should be applied to maximize its usefulness.

**Comment by drpebcak** [comment]
👍

**Comment by deniseschannon** [comment]
Verified with v0.6.0-rc4
