### ISSUE TITLE
race condition in dhcp with multiple network interfaces

### ISSUE THREAD

**Issue by hongjia** [rancher/os#1105]
**RancherOS Version: (ros os version)**
v0.5.0 / v0.4.5

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
VirtualBox VM for Linux

I created a virtual machine using VirtualBox in Debian.  The VM has two network interfaces connected to a Host-Only network, vboxnet0(The problem also occurs with a host-only NIC and a NIC bridged to host link)。I boot RancherOS from ISO, and use a virtual hard disk for state data.

Usually, the two network interfaces can get IP addresses through DHCP on system start. But sometimes only one NIC can get IP address. I can repeat this more often if I have a container started with some ports published and the option --restart=always specified when starting the container.

If one NIC failed to obtain an IP address, "system-docker logs network" shows the following message:

===========
time="2016-07-08T03:32:04Z" level=info msg="Running network: stop-network-pre=true"
time="2016-07-08T03:32:04Z" level=info msg="Running DHCP on eth1"
time="2016-07-08T03:32:04Z" level=info msg="Running DHCP on eth0"
control_open: control_open: Connection refused
Connection refused
dhcpcd already running on pid 693 (/var/run/dhcpcd.pid)
time="2016-07-08T03:32:05Z" level=error msg="exit status 1"
eth1: rebinding lease of 192.168.56.107
eth1: leased 192.168.56.107 for 1200 seconds
eth1: adding route to 192.168.56.0/24
forked to background, child pid 886
=========== 

The following is the reason I guessed after inspecting some code of the network service and dhcpcd: It seems that the network service will start two instances of dhcpcd. There is a race condition here: The first dhcpcd locks the pidfile. Before it forks to background, the second dhcpcd starts (also in master mode, since -M is specified by default in the command line arguments) and finds that the pidfile is locked by the first process. The second dhcpcd will exit with the above message(dhcpcd already running on pid ...).

I am new to RancherOS and I am not sure how to solve this problem. Maybe starting one dhcpcd process with all interface names appended in the command line arguments? Or running an individual dhcpcd instance for each interface?

**Comment by joshwget** [comment]
Are you sure this issue is present in v0.5.0 and not just v0.4.5? If I remember correctly, this was an issue I resolved between v0.4.5 and v0.5.0.

**Comment by deniseschannon** [comment]
@hongjia Can you try with our latest versions and see if you still have issues? If so, please re-open.
