### ISSUE TITLE
Tag v0.5.0_arm not found in repository

### ISSUE THREAD

**Issue by gjongenelen** [rancher/os#1108]
**RancherOS Version: (ros os version)**
OS: v0.5.0_arm

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
Raspberry PI 3B

When using **ros install -c cloud-config.yml -d /dev/disk** the tag _v0.5.0_arm_ could not be found in the repo _rancher/os_

**Comment by joshwget** [comment]
Is there a use case where you'd use the installer over the SD card image? Our installer doesn't currently support Raspberry Pi, but if that's something needed for some situations then we can look into adding support for it.

**Comment by gjongenelen** [comment]
I wanted to use the installer to take advantage of disk resizing, static ip configuration and ssh-key configuration.

**Comment by joshwget** [comment]
Configuration can be changed after installing RancherOS, so you shouldn't need the installer for this. Check out the docs for [configuration](http://docs.rancher.com/os/configuration/). Be aware of #1084 for resizing though!
