### ISSUE TITLE
Cannot run docker-compose on v0.5.0

### ISSUE THREAD

**Issue by robbertkl** [rancher/os#1109]
**RancherOS Version: (ros os version)**

v0.5.0

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**

Linode & TransIP VPS

On v0.4.5 and before, I have used docker-compose on the machine itself, but on v0.5.0 it won't run:

```
$ wget https://github.com/docker/compose/releases/download/1.7.1/docker-compose-`uname -s`-`uname -m`
$ chmod +x docker-compose-Linux-x86_64
$ ./docker-compose-Linux-x86_64 
-bash: ./docker-compose-Linux-x86_64: No such file or directory
$ ldd docker-compose-Linux-x86_64 
checking sub-depends for 'not found'
checking sub-depends for '/lib64/libz.so.1'
checking sub-depends for 'not found'
checking sub-depends for '/lib64/libc.so.1'
	ld64-uClibc.so.1 => /lib/ld64-uClibc.so.1 (0x7f35d5268000)
	libdl.so.2 => not found (0x00000000)
	libz.so.1 => /lib64/libz.so.1 (0x00000000)
	libc.so.6 => not found (0x00000000)
	libc.so.1 => /lib64/libc.so.1 (0x00000000)
	/lib/ld64-uClibc.so.1 => /lib/ld64-uClibc.so.1 (0x00000000)
```

Did something happen with libraries like libc? Could this be a change in the (default) console? I run the default console.

I know I could run docker-compose within a container, but it would be nice if it could run the public release version directly from my home dir, just like I could do in previous versions of RancherOS.

Thanks!

**Comment by joshwget** [comment]
glibc was removed from the default console in v0.5.0. It was replaced with uClibc, but we'll be switching over to musl in one of the upcoming releases. musl offers better compatibility with glibc, which will fix some issues like these.

As a workaround, I'd suggest using an alternate console (they all use glibc) or running in a container as you'd suggested.

**Comment by robbertkl** [comment]
Thanks, that clears it up. Do you think musl will allow running the compiled release version of docker-compose? Anyway, I've discovered they actually release a run.sh script (https://github.com/docker/compose/releases/download/1.7.1/run.sh) which runs docker-compose in a container, making the experience pretty much identical to downloading the compose binary!

Since you're already planning on switching to musl, I'll close this issue.
