### ISSUE TITLE
Docker 1.12 not compatible with custom Docker docs

### ISSUE THREAD

**Issue by joshwget** [rancher/os#1110]
Docker 1.12 splits the daemon and client into separate binaries. As a result of this, the instructions in [the custom Docker docs](http://docs.rancher.com/os/configuration/custom-docker/) don't work for Docker 1.12.

**Comment by CumpsD** [comment]
Looking forward to try out 1.12 on rancher os myself as well.

**Comment by channeladam** [comment]
What needs to be done in order for Rancher OS to support Docker 1.12 ?
Is there an expected milestone for 1.12 support? 
(really want to use it!)

thx!

**Comment by nhi-vanye** [comment]
Docker 1.12 support - specifically macvlan has put my work using RancherOS on hold.

Some indication - weeks, months would help with planning my time.

**Comment by deniseschannon** [comment]
In the next release, we're changing how to customize Docker. We'll update the docs on how to customize Docker. 

https://github.com/rancher/os/issues/1129

**Comment by joshwget** [comment]
@channeladam @nhi-vanye The most recent RC has support for Docker 1.12 if you'd like to try it out now.

**Comment by channeladam** [comment]
Fyi, the trick to successfully building the RC is to have Docker 1.11.2 installed on the build server - as the build fails if it tries to use Docker 1.12 ... :)

**Comment by deniseschannon** [comment]
http://docs.rancher.com/os/configuration/switching-docker-versions/

**Comment by deniseschannon** [comment]
This is now working for v0.6.0
