### ISSUE TITLE
RancherOS 0.5.0 not compatible with current version of convoy-nfs

### ISSUE THREAD

**Issue by nunofgs** [rancher/os#1111]
**RancherOS Version: (ros os version)**
0.5.0.

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
AWS.

Since RancherOS 0.5.0 includes Docker 1.11, it isn't compatible with the current version of `convoy-nfs` so convoy is a no go with RancherOS at the moment.

**Comment by deniseschannon** [comment]
Convoy-nfs works with Docker 1.11 as we've updated our template for this compatibility so there are no known issues with RancherOS v0.5.0.

Also, this is more of a Rancher bug and not a RancherOS bug. I'm going to close and if you have  an issue with convoy-nfs, it will be better suited for Rancher.
