### ISSUE TITLE
Create an iso that includes installer image so no internet would be required

### ISSUE THREAD

**Issue by deniseschannon** [rancher/os#1112]
Currently, you can point to an installer image (either through DockerHub or a private registry) to be able to run `sudo ros install -i <image_name>` and install to disk. 

RancherOS should create another iso that has the installer image inside the iso so that installation could occur without internet.

**Comment by ibuildthecloud** [comment]
This should be doable once we switch to alpine+syslinux.

**Comment by datawolf** [comment]
+1

**Comment by liyimeng** [comment]
+1

**Comment by darkadan** [comment]
+1

**Comment by chinaares** [comment]
+1

**Comment by SvenDowideit** [comment]
implemented by #1456

**Comment by deniseschannon** [comment]
Verified with v0.8.0-rc4. 

Able to install using the iso without internet.
