### ISSUE TITLE
Kernel Header in v0.5.0 is downloading the incorrect wrong tar ball

### ISSUE THREAD

**Issue by deniseschannon** [rancher/os#1114]
**RancherOS Version: (ros os version)**
v0.5.0
**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**

Kernel Headers do not work in v0.5.0

**Comment by deniseschannon** [comment]
We've updated the kernel headers for v0.5.0. Verified that it's working.

**Comment by ryansch** [comment]
How do I use this with 0.5.0?  Do I have to create my own service?

**Comment by ryansch** [comment]
Looks like https://github.com/rancher/os-services/blob/master/k/kernel-headers.yml hasn't been updated with the new `-4` release (https://hub.docker.com/r/rancher/os-headers/tags/).

**Comment by deniseschannon** [comment]
When you follow these directions on how to use kernel headers, it automatically loads the `-4` release.

http://docs.rancher.com/os/configuration/kernel-modules-kernel-headers/

**Comment by ryansch** [comment]
When I disable/enable the `kernel-headers` service on an existing 0.5.0 machine it still pulls the `-3` version.

**Comment by deniseschannon** [comment]
Can you try disabling the `kernel-headers` service and then removing the images (in user docker) and try enabling again? I enabled on a fresh install of v0.5.0 and it pulled the `v0.5.0-4`.

**Comment by ryansch** [comment]
I see the commit for the 0.5.0 services: https://github.com/rancher/os-services/commit/cede78e967e3068831be0b3d7b38154d5030883e

I've tried what you requested and I've also tried rebooting with and without the service enabled with the image removed.  It seems to have `-3` cached somewhere and is refusing to hit the network to grab the new version.

**Comment by ryansch** [comment]
Figured it out!  I found the cached service file under a hash in `/var/lib/rancher/cache`.  When I removed that and did the disable/enable dance it pulled the `-4` version.

**Comment by ibuildthecloud** [comment]
@ryansch Delete `/var/lib/rancher/cache/*` to clear the cache.

**Comment by ryansch** [comment]
Thanks for the help @deniseschannon and @ibuildthecloud!
