### ISSUE TITLE
Login after Install not possible

### ISSUE THREAD

**Issue by rdissauer** [rancher/os#1117]
**RancherOS Version: v0.5.0**
**Where are you running RancherOS? baremetal**

When I install RancherOS v0.5.0 from ISO on a baremetal machine I cannot login neither on the terminal nor over ssh using user `rancher` password `rancher`.

I install using following command:
`sudo ros install -c config.yml -d /dev/sdx`

config.yml content:
`ssh_authorized_keys: `
`  - ssh-rsa ssh-rsa AAAA... `

With v0.4.5 this procedure worked seamlessly

**Comment by rdissauer** [comment]
When I boot from ISO on the freshly installed machine, change the console to a non-default console and then boot into the baremetal machine again, login works fine from the Console as `rancher`password `rancher`. Correct SSH Key is installed in `/home/rancher/.ssh/authorized keys` but SSH login with `rancher` from my host always requests password.

When I change back console to default I get locked out again. No login neither on Console nor over SSH possible!

**Comment by joshwget** [comment]
Can you login and verify that you have network access? The output of `system-docker logs network-pre` and `system-docker logs console` would also be useful.

**Comment by deniseschannon** [comment]
@rdissauer If you're still having issues, please re-open with some updates on our requests.
