### ISSUE TITLE
Logs and Shell as a Rancher agent only work for the first boot

### ISSUE THREAD

**Issue by hemsleyk** [rancher/os#1124]
**RancherOS Version: (0.5.0)**

**Where are you running RancherOS? (Hyper-V, boot from ISO w/ state disk)**

Similar to boot2docker, this OS is not usable with Rancher.

After the first VM reboot the container terminal and logs features are permanently disabled and stall on connecting.

Steps to reproduce:
Create VM
Boot ISO
Create state disk
Reboot
Lock down SSH(?)
Run rancher agent
Run some containers via rancher
Reboot
Container terminal / logs are now gone as well as host utilization stats

At least it doesn't detect it as a totally new host, I guess.

**Comment by arthurkay** [comment]
Supplementary: If RancherOS is not supported for use with Rancher under Hyper-V ... what IS supported that has a <5 command setup process?

**Comment by deniseschannon** [comment]
I was unable to reproduce using Rancher v1.2.0-pre2 and RancherOS v0.6.0-rc6.  

I used Virtual box and installed to disk and added it to Rancher. I started some containers/a Load balancer and rebooted. The logs/shell still worked for my containers.

**Comment by hemsleyk** [comment]
This was a two-off issue ... somehow. Further VMs do not display. Possible there was actually a problem and it is fixed in master at some point, or a problem with the network being used here (no NAT boundaries save for Docker itself though).
