### ISSUE TITLE
Is it possible to setup a Python Interpreter

### ISSUE THREAD

**Issue by bernardoVale** [rancher/os#1127]
I was wondering if it's possible to setup a python interpreter on RancherOS.

I have several RancherOS installation on my customers, I use then to deploy a simple app and also as a bastion host for remote access. I want Python to be able to put my RancherOS on ansible inventory and ping then as well. 

**RancherOS Version: (ros os version)**
Latest
**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
AWS, VMware, Baremetal

**Comment by joshwget** [comment]
This can be done two ways:

1. [Switch to a different console](http://docs.rancher.com/os/configuration/custom-console/) and install it with a package manager.
2. Run whatever requires Python in a container.

In most cases, number two will be the better solution. Can you describe your use case a little more?

**Comment by bernardoVale** [comment]
Hello @joshwget , thanks for your response.

I need Rancher to communicate with Ansible, and Python is required for that.

**Comment by bernardoVale** [comment]
@joshwget , I've switched to CentOS console and it's working fine. I'll close this issue.

Thanks

**Comment by zot24** [comment]
I'm trying to achieve this but something it's not quite working for me in order to be able to install `python` to be able to use `ansible` on RancherOS 0.7.1 I do:

```
#cloud-config
rancher:
  console: ubuntu
```

Which works fine then I ssh into the instance and install `python` and run my Ansible scripts however when I try to automate this last bit and install `python` from the `cloud-conf.yml` file it doesn't like it and it didn't even activate the ``ubuntu console for me, this is how my final `cloud-config.yml` looks like:

```
#cloud-config
rancher:
  console: ubuntu
runcmd:
  - apt-get update ; apt-get install python
```

How did you @bernardoVale manage to activate CoreOS console and at the same time install python? Do I have something wrong on my `cloud-config` script @joshwget?

Thanks,

**Comment by zot24** [comment]
I think I'm using the wrong version of RancherOS and it's not 0.7.1 as I thought looks like the readme file for the tag version 0.7.1 https://github.com/rancher/os/blob/v0.7.1/README.md#user-content-amazon it's wrong and point to 0.6.1 `ami-934837e0` instead.

Going to double check and try with the 0.7.1 version `ami-c62170b5`

**Comment by joshwget** [comment]
@zot24 The problem is with your `runcmd`. Check out #1284.

**Comment by zot24** [comment]
I see, I though strings where supported on 0.7.1 but it's on 0.8.0-rc1 👍 

I have change it to and try:

```
#cloud-config
rancher:
  console: ubuntu
runcmd:
  - [ sudo apt-get update ]
  - [ sudo apt-get install python ]
```

**Comment by joshwget** [comment]
The parts are comma separated for lists. This should do the trick.

```
runcmd:
  - [ apt-get, update ]
  - [ apt-get, install, python ]
```

**Comment by zot24** [comment]
Thanks that fix it just mention I needed to add the `-y` option to force the installation of `python`

```
#cloud-config
rancher:
  console: ubuntu
runcmd:
  - [ apt-get, update ]
  - [ apt-get, install, -y, python ]
```

**Comment by SvenDowideit** [comment]
you really should make your own console Dockerfile, and a custom service file - but I need to write some docs on this, and then we need to work towards making that process simpler.
