### ISSUE TITLE
Replace custom base image with Alpine

### ISSUE THREAD

**Issue by joshwget** [rancher/os#1130]
Replace our [custom Buildroot base image](https://github.com/rancher/os-base) with Alpine. Buildroot is slow to compile and difficult for new contributors. Having the Alpine image available by default is also convenient for custom system services that use it as a base image.

**Comment by joshwget** [comment]
Unfortunately we've decided not to go this route. Alpine doesn't currently have support for arm64, which is a pretty major blocker for us. We're going to create an Alpine console as an alternative (#1151).

**Comment by ryansch** [comment]
😭
