### ISSUE TITLE
Upgrade Linux kernel for Raspberry Pi

### ISSUE THREAD

**Issue by DieterReuter** [rancher/os#1132]
**RancherOS Version: (ros os version)**
0.5.0

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
baremetal, Raspberry Pi2/Pi3

**TODO**
As there is a new Linux kernel release 4.4.15 for HypriotOS/RPi available soon, we should also consider to upgrade the SD image creation for RancherOS.

**Comment by SvenDowideit** [comment]
yes, we need to work on our automation :)

though I'm going to close this issue, as its out of date (and so is our spi kernel)

**Comment by joshwget** [comment]
@SvenDowideit Why is this being closed? It's an old issue, but we do need to upgrade still.

**Comment by SvenDowideit** [comment]
because we've upgraded since then, and i'm doing another - having an issue for it hasn't made a difference
