### ISSUE TITLE
Severe: upgrading from 0.4.5 to 0.5.0 lost all data ( on /data )

### ISSUE THREAD

**Issue by EugenMayer** [rancher/os#1133]
**RancherOS Version: (ros os version)**
0.4.5

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
baremetal 'kvm'

using this guide http://docs.rancher.com/os/upgrading/ and running 

```
sudo ros os upgrade
```

it went through without issues. After a restart, rancher was reet to factory. All data on /data was lost, thus all my host mounts, my rancher-server db - everything.

I do not expect this to be desired, right? I had to remake the whole rancheros server from the backups

**Comment by EugenMayer** [comment]
after re-reading the docs and all this, i understood that what i ssh into, is the system-container 'console' and this container will be remade during rancheros upgrade. Anything not exposed into volumes is lost of course.

With this informations, that the 'host' hosting my user-docker container is actually not a host but rather a container, i used inspect and saw, which volumes / host mount ( real host mounts ) the console has - /data was not part of them.

After some time i found this http://docs.rancher.com/os/configuration/custom-console/#console-persistence als stating, that only data in those folders will "survive" upgrades.

So wrapping my head arround, i finally found it, why my rancher data was reset, since i put mostly anything under data, including the rancher-database.

While you clearly can state RTFM, maybe its just me, but i find this absolutely critical informations spreaded that far over the whole docs, that i did not even find it until now.

My suggestions:
 - either adjust http://docs.rancher.com/os/quick-start-guide/ or/and http://docs.rancher.com/os/configuration/storage/ or any "first installation guide" to force the user to think about were to put all his files into. If the users, like me, choses stuff like /mnt or /data - he will be screwed
 - explain more briefly, with a big fat "BE AWARE" that the 'host' volumes for user-docker containers are actually mounted in the console-container and its filesystem. I was, until know, not aware of this, of course i knew what the console container is though 
 - update http://docs.rancher.com/os/upgrading/ to state that data can be lost and will be lost on every folder not being /home /var/lib/docker or /var/lib/rancher. Make it a big fat warning with an confirmation and ensure the user gets it. Probably, we even want to use docker-inspect on all user-containers and check there mounts for not being either name-volume or host mounts into not one of those folders. This would be great, but at least the docs and the warning should be there

So in the end, this is a documentation task, but still, if find this very critical, since it is probably a complete data loss resulting in miss-configuration

**Comment by joshwget** [comment]
I definitely agree with your suggestions! This is something that really needs to be highlighted more. Check out [my response in another issue](https://github.com/rancher/os/issues/902#issuecomment-237400974) for some other thoughts on this topic.

**Comment by SvenDowideit** [comment]
I wonder if we can set up some inotify bits to send the user a console message if they write to console fs locations that are ephemeral - with a setting to disable it if they're doing it intentionally.

**Comment by higuita** [comment]
No need for upgrade, a simply restart will do the same, i just lost my /data... luckily i was just testing rancher and rancheros. 

This info is important and should be clearly flagged and they should also clearly show how one can add persistent data to the dockers. All this must be added to the quickstart

why even the other containers can access a folder created in the console and it is volatile is helping people make this mistake. If you block it, it volumes will not work, people will do more research why and will not risk losing data

**Comment by EugenMayer** [comment]
Well for me it became fairly easy after this accident: never upgrade until you migrated away from rancheros

**Comment by JigSawFr** [comment]
Just see this issue too late ... I've upgraded ros and lost all my /data directory ! (2Tera)
Can you confirm these directory are persistent ?
- /home
- /opt
- /var/lib/docker
- /var/lib/rancher

So I can put my data in `home`or `opt` without losing data after restart or upgrade ?
Thank you

**Comment by SvenDowideit** [comment]
I would _only_ use `/home`, `/opt`, or a separate disk/partition that you mount.

**Comment by Vanuan** [comment]
I've just lost my database after rancheros upgrade :angry: 
Using `/data` for persistence looked like an obvious choice.
Rancher os MUST NOT allow me to upgrade if rancheros system image is not clear (docker diff).
At the very list it should warn that new folders created in root (`/`) are to be deleted.
For example:

```
You have a new folder `/data` created in the temporary rancher container filesystem.
This folder will be DELETED. Proceed? (y/n)
```

**Comment by Vanuan** [comment]
Oh, it's not even upgrade, it's a simple restart that leads to data loss :astonished:

**Comment by vincent99** [comment]
The default console is ephemeral and designed for running everything through Docker.  Only /home and docker volumes are persistent.  http://rancher.com/docs/os/v1.1/en/configuration/switching-consoles/#console-persistence

We're not going to patch `mkdir` and `docker -v` and break scripting to show a warning.

**Comment by Vanuan** [comment]
Virtually nobody's using Docker volumes for persistence. Most people use docker bind mounts. Since docker daemon uses temporary root filesystem instead of the real root, it's causing such confusion.

Rancher OS should be either more transparent (read needing manual intervention) about mounted folders. Alternatively, it should use the real filesystem for mounts by default (while optionally using the temporary one).

**Comment by EugenMayer** [comment]
@Vanuan wat? why anybody would ever consider using bind mounts ever. Beside having only downsides, its not even close to cluster-compatible.

Still i agree, that this thing should have been solved a long time ago. Nobody wants a patched mkdir or docker, it could be done so much easier. Even doing a `du -sh /*` picking up the largest 3 and comparing them against the list of "persistent storage" if anything in there is not part of it, just show a hint on upgrade. People can ignore it, if its a false positive, or go with it.

**Comment by Vanuan** [comment]
@EugenMayer what do you use for docker container persistence? Docker volumes aren't cluster-compatible either.

**Comment by EugenMayer** [comment]
@Vanuan this is going off-topic, but you can see and read it here https://docs.docker.com/engine/swarm/services/#give-a-service-access-to-volumes-or-bind-mounts you can use a lot https://portworx.com/, minion, long and sure a lot more i am not aware of.

**Comment by Vanuan** [comment]
@EugenMayer 
Ok. So when I said docker volume I meant default docker volume driver (overlay). And when I said bind mount I meant a non-docker directory with some network synchronization.

According to the swarm docs link:
> You can create two types of mounts for services in a swarm, volume mounts or bind mounts.

Attached volumes are not moved to another machine when a service is moved to another swarm node. So you would have to use some kind of network attached block device (e.g. NFS) or the solutions you've mentioned.

You said that bind mounts are
> not even close to cluster-compatible.

Neither are docker volumes (overlay driver).
I asked what do you use. As I see you've lost data, so you've been using bind mounts too?

Now the solutions you've mentioned. Those aren't docker volumes.

**Portworx** whitepaper confirms that docker volumes aren't cluster compatible:
![screenshot from 2017-10-08 22-50-25](https://user-images.githubusercontent.com/361985/31320325-60e056f2-ac7b-11e7-95b3-9c43b8a7c1ee.png)
So portworx is a [3rd party volume driver](https://docs.portworx.com/scheduler/docker/swarm.html).

What is minion? Do you mean **minio.io**? Well, that's Amazon S3 implementation, not a block storage. Even then it relies on bind mount for persistence. Alternatively you could use volumes but then you have to make sure its services are never scheduled to another swarm node. Not a good solution, right?

What is long? **[Longhorn](https://github.com/rancher/longhorn)**?  Well, that's a volume driver, similar to Portworx.
