### ISSUE TITLE
RancherOS mounts only 15GB.

### ISSUE THREAD

**Issue by zhang8473** [rancher/os#1135]
**RancherOS Version: (ros os version)**
RancherOS (4.4.10-rancher)
AWS images: ami-f0f03190

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
AWS

No matter how large 50GB , only 15GB is mounted to the host. It seems it does not mount the other volumes at boot.

**Comment by joshwget** [comment]
It sounds to me like this is #1099, but I might be misunderstanding you. Can you explain a bit more about what's happening and what you expect to happen? Some command outputs would probably be helpful.

**Comment by zhang8473** [comment]
I think I am having the same problem with #1099. 
In "Add host", I set,
![image](https://cloud.githubusercontent.com/assets/5016962/17390383/7dd96ec8-59c1-11e6-834e-4c91d285fd9f.png)
After launching, I saw,
![image](https://cloud.githubusercontent.com/assets/5016962/17390351/3606ed5a-59c1-11e6-92d4-9d565efc7ee7.png)

**Comment by joshwget** [comment]
Yeah, this looks like a duplicate. Thanks for confirming!
