### ISSUE TITLE
Multiple IP's - 1 IP per container.

### ISSUE THREAD

**Issue by danipolo** [rancher/os#1137]
Panel
**RancherOS Version: v1.1.2** - (isolated in a VPS)

New host:
**Baremetal - OVH Dedicated server, 32GB RAM** (all the machine will be a host for multiple websites)

I'm just installed RancerOS to a dedicated server in OVH and I really don't know how to point multiple IP's to the containers. We have around 40 IP's, and we want to assign them.

We do this in Ubuntu:

```
# The loopback network interface
auto lo
iface lo inet loopback

auto eth0
iface eth0 inet static
        address 51.254.xxx.87
        netmask 255.255.255.255
        post-up /sbin/ip route add 51.254.xxx.1 dev eth0
        post-up /sbin/ip route add default via 51.254.xxx.1
        pre-down /sbin/ip route del default via 51.254.xxx.1
        pre-down /sbin/ip route del 51.254.xxx.1 dev eth0
        dns-nameserver 213.186.33.99
        dns-search ovh.net

auto eth0:1
iface eth0:1 inet static
        address 5.196.xxx.12
        netmask 255.255.xxx.255
        broadcast 5.196.xxx.12
...
```

How we do this with your OS and then point it in each container?

I really apreaciate your help. Currently migrating all our company to your system :)

Thanks!

**Comment by ibuildthecloud** [comment]
This ends up being a fairly general Docker question, meaning you'll have a bit of difficulty doing this in any Docker setup.  So the first question is have you done this setup before without RancherOS?  On a different Docker host.  If so, can you share how you accomplished it.

Typically with Docker people don't bind IP's directly to container but instead map incoming ports to containers.  There are multiple ways you can do that.  The simplest way is if all of your 40's are bound to the host, you then run a container like `docker run -p 1.1.1.1:80:80 nginx` and that will map port 80 on 1.1.1.1 to your containers private IP.

To setup your above config in RancherOS you would use the following cloud-config (/var/lib/rancher/conf/cloud-config.yml):

```yaml
rancher:
  network:
    dns:
      nameservers:
      - 213.186.33.99
      search:
      - ovh.net
    interfaces:
      eth0:
        address: 51.254.xxx.87/32
        addresses:
        - 5.196.xxx.12/32
        - 5.196.xxx.13/32
        post_up:
        - /sbin/ip route add 51.254.xxx.1 dev eth0
        - /sbin/ip route add default via 51.254.xxx.1

**Comment by SvenDowideit** [comment]
@danipolo have you seen https://docs.docker.com/engine/userguide/networking/get-started-macvlan/ ?

I've not used it, but its on my list :)

**Comment by danipolo** [comment]
@SvenDowideit @ibuildthecloud It worked, thanks. I arrived to the point of mount Route 53 and it's awesome. But actually I'm in other trouble:

I configured Route 53 as external DNS for Rancher and it work like a charm but I have a big question for this. I think I won't be the first to handle with this situation.

As Rancher Route 53 External DNS Service works, the host IP is used to balance the stacks externally. It only exposes the services which have public ports exposed. Then if some of the hosts fails, the Rancher External DNS, request AWS to change the IP. Rancher will send by default the host main IP configured.

From here, all it's working but what's the way to do it specifying multiple IP's in a host?

I saw in the documentation you can specify an IP adding the label `io.rancher.host.external_dns_ip`	to the host but... What happens if I want to specify an IP to a website in normal conditions? If the regular IP fails, just use other one. But in normal situation, use an specific one.

Domain **example1.com** -> Normally resolves to **1.1.1.1 (host1)** -> In case of fail, move to **host2** and **host3** (**2.2.2.2** and **3.3.3.3**)

Domain **example2.com** -> Normally resolves to **4.4.4.4 (host1)** -> In case of fail, move to **host2** and **host3** (**5.5.5.5** and **6.6.6.6**)

...

How can we solve this?

Thanks!

**Comment by deniseschannon** [comment]
@danipolo Your issue is more related to Rancher and Route 53, could you open an issue in rancher/rancher?

**Comment by danipolo** [comment]
@deniseschannon sure, thanks.

**Comment by deniseschannon** [comment]
@danipolo Let me know if you have more question, but I think your questions are answered.
