### ISSUE TITLE
Early cloud-init

### ISSUE THREAD

**Issue by joshwget** [rancher/os#1175]
cloud-init is currently run pretty late in the boot process, especially when the source requires network access. There should be an option to run cloud-init very early in the boot process, specifically before state is mounted and before System Docker starts. This should make it much easier to configure System Docker and system services that currently run before cloud-init.

**Comment by deniseschannon** [comment]
Verified with v0.8.0-rc4 by using `write_files` to change `ntp` system service.

Used this cloud config

```
#cloud-config
write_files:
  - container: ntp
    path: /etc/ntp.conf
    permissions: "0644"
    owner: root
    content: |
      server 0.pool.ntp.org iburst
      server 1.pool.ntp.org iburst
      server 2.pool.ntp.org iburst
      server 3.pool.ntp.org iburst

      # Allow only time queries, at a limited rate, sending KoD when in excess.
      # Allow all local queries (IPv4, IPv6)
      restrict default nomodify nopeer noquery limited kod
      restrict 127.0.0.2
      restrict [::1]
```

Logged in and `sudo system-docker exec -it ntp cat /etc/ntp.conf` showed the same file.

**Comment by robbertkl** [comment]
Hi @deniseschannon, does this mean sysctls will also be applied before the network is initialized? Asking because of #908 , which was closed in favor of this one.

**Comment by joshwget** [comment]
@robbertkl I'm sorry, my earlier comment was actually incorrect. The sysctl values are now available before networking but they aren't actually applied until the `cloud-init-execute` service is run. I'm going to open a new issue to track this.

**Comment by robbertkl** [comment]
@joshwget Thanks, can you send me the # so I can subscribe to it?

**Comment by joshwget** [comment]
@robbertkl Created #1539 to track it..
