### ISSUE TITLE
Network hardware not detected during boot

### ISSUE THREAD

**Issue by bachp** [rancher/os#1176]
**RancherOS Version: 0.5.0**

**Where are you running RancherOS? baremetal ([ASUS P9X79 WS](https://www.asus.com/Motherboards/P9X79_WS/))**

While running Rancher OS on a new machine with the mainboard specified above I notived that the onboard network cards are not recognized during startup. Which leads to the case where no network interfaces other than `lo` and `docker0` are initialized.

Further investigation revealed that if I re-run the `udev-cold` container the network interfaces `eth0` and `eth1` appear correctly. Restarting `network` after that restores full network connectivity.

To me it seems like there is a timing issue with the kernel and the point in time when udev-cold is run.
I also tried to do a `udevadm trigger` from the console but it didn't seem to have any effect.

Is there anything I can try in order confirm my timing theory, for example delay the execution of udev-cold during startup?

PS:
I already upgraded to the latest BIOS version and tried to change some BIOS setting that could lead to the issue. Also I don't see the same issue with a CentOS 7 or Debian. Maybe Rancher OS is just starting up to fast :wink:

**Comment by ibuildthecloud** [comment]
@bachp Can you try [v0.6.0-rc3](https://github.com/rancher/os/releases/tag/v0.6.0-rc3)?  We are constantly tweaking the startup to address issues like this and it would be nice to see if the latest build still had this problem.

**Comment by bachp** [comment]
Sure I will give v0.6.0-rc3 a try tomorrow and let you know the results.

**Comment by bachp** [comment]
I tested with v0.6.0-rc4 and I did several reboots. So far the issue has never occured again. Great work.

**Comment by ibuildthecloud** [comment]
@bachp Not so fast 😄  There is a boot issue in rc4 that slows down the boot and will be fixed on rc5.  So I'm concerned your issue might pop back in rc5.  I'll update this issue when rc5 is out.

**Comment by bachp** [comment]
@ibuildthecloud Is the fix you mentioned in rc5? Should I retry?

**Comment by deniseschannon** [comment]
@bachp Can you try with v0.6.0? Please let me know if you still have issues and we can address in the next release.

**Comment by bachp** [comment]
@deniseschannon I testet with v0.6.0 and the network card is detected and configured.
The only thing that is not so nice is that in the banner before the login only the `lo: 127.0.0.1` is displayed.
But this doesn't affect the functionality.

**Comment by joshwget** [comment]
@bachp Your original theory was actually correct. #1195 is the proper fix for this.

Regarding the banner containing only `lo: 127.0.0.1`, the console is being started before the remaining interfaces get IP addresses. The only way to prevent this is to block and wait for these during the boot process, which most people likely wouldn't prefer.

**Comment by bachp** [comment]
@joshwget Thanks

BTW:  CoreOS also shows a banner, and theirs get updated even if the ip changes because of dhcp during runtime. Not sure how they do it.

**Comment by joshwget** [comment]
@bachp Interesting, there must be some trick I'm unaware of. Thanks for the heads up!

**Comment by ibuildthecloud** [comment]
CoreOS uses systemd/systemd-networkd and a series of shell scripts to regenerate the `/etc/issue` file.  It's surprisingly complicated.  I've looked into doing the same for RancherOS.
