### ISSUE TITLE
v0.6.0-rc4 - udevd inotify_add_watch errors when booting: /dev/sda No such file or directory

### ISSUE THREAD

**Issue by lucymhdavies** [rancher/os#1179]
**RancherOS Version: v0.6.0-rc4**

**Where are you running RancherOS? VMWare ESXi (5 ish), and VMWare Fusion (8.1.1)**

As per attached screenshot
![screen shot 2016-08-23 at 15 50 25](https://cloud.githubusercontent.com/assets/1116529/17896823/ddf4498a-6949-11e6-9e70-f48cf4899a64.png)

````
udevd[24]: inotify_add_watch(6, /dev/sda, 10) failed: No such file or directory
udevd[15]: inotify_add_watch(6, /dev/sda1, 10) failed: No such file or directory
````

I do not see this issue in 0.5.0.

I haven't yet seen any side effects of this, other than it taking longer to boot my VM.

This is a fairly clean install, installed with:

```
sudo ros install -d /dev/sda -f -t generic -c ./cloud-config.yml
```

**Comment by joshwget** [comment]
Good catch! Should be fixed in the next RC.

**Comment by joshwget** [comment]
Confirmed with v0.6.0-rc5 that this issue is no longer present.

**Comment by lucymhdavies** [comment]
Yep. No longer an issue 👍
