### ISSUE TITLE
v0.6.0-rc4 - Unable to bind ports in User Docker, with rancher/os-docker:1.12.0

### ISSUE THREAD

**Issue by lucymhdavies** [rancher/os#1181]
**RancherOS Version: v0.6.0-rc4**

Fairly fresh install of RancherOS from the 0.6.0-rc4 iso, 

**Where are you running RancherOS? VMWare ESXi (5 ish), and VMWare Fusion (8.1.1)**

With the user docker version set to 1.12.0 (the default), I am unable to expose ports in docker containers:

{noformat}
[rancher@guealucytest01 ~]$ docker run -it -p 8080:8080 ubuntu bash
docker: Error response from daemon: driver failed programming external connectivity on endpoint romantic_bell (89ad7157ea7fa196cf313ffbdfa0d0e0af232448af7b8ea2cc8d7bcc5aaf04c6): exec: "docker-proxy": executable file not found in $PATH.
{noformat}

However, I do not see the same issue when running the same command with `system-docker` rather than `docker`.

```
[rancher@guealucytest01 ~]$ sudo system-docker run -it -p 8080:8080 ubuntu bash
root@226d035b949c:/#
```

Also, if I downgrade the docker engine to 1.11.2, then I have no issue either:

```
[rancher@guealucytest01 ~]$ sudo ros engine switch docker-1.11.2
INFO[0002] Project [os]: Starting project
INFO[0002] [0/20] [docker]: Starting
Pulling docker (rancher/os-docker:1.11.2)...
1.11.2: Pulling from rancher/os-docker
2a6bbb293656: Pull complete
Digest: sha256:ec57fb24f6d4856d737e14c81a20f303afbeef11fc896d31b4e498829f5d18b2
Status: Downloaded newer image for rancher/os-docker:1.11.2
INFO[0007] Recreating docker
INFO[0008] [1/20] [docker]: Started
INFO[0008] Project [os]: Project started

[rancher@guealucytest01 ~]$ docker run -it -p 8080:8080 ubuntu bash
root@08f29a73fd9f:/#
```

**Comment by joshwget** [comment]
Another good catch. Thanks @lucymhdavies!

**Comment by ibuildthecloud** [comment]
Darn you multiple binaries!

**Comment by deniseschannon** [comment]
Verified with v0.6.0-rc5.

Able ot start a container with exposed ports.

**Comment by lucymhdavies** [comment]
Yep. No longer an issue 👍
