### ISSUE TITLE
can not upgrade RancherOS's console with --upgrade-console

### ISSUE THREAD

**Issue by datawolf** [rancher/os#1197]
**RancherOS Version: (ros os version)**

v0.5.0

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**

qemu(ubuntu console)

when we use `sudo ros os upgrade --upgrade-console -i rancher/os:v0.6.0-rc5` to upgrade RancherOS in ubuntu console.  we can not upgrade console successfully. the console's version is still `v0.5.0`.

**Comment by datawolf** [comment]
we can remove files in /var/lib/rancher/cache/*  before os upgrade. the console will upgrade with `--upgrade-console` successfully.

**Comment by deniseschannon** [comment]
Verified that `--upgrade-console` is working as expected when upgrading from v0.5.0 to v0.6.0-rc6.
