### ISSUE TITLE
Password for rancher user in 0.6.0-rc5?

### ISSUE THREAD

**Issue by progmetalbg** [rancher/os#1198]
**RancherOS Version: (ros os version)**
0.6.0-rc5

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
VirtualBox 4.3.28

I booted 0.6.0-rc5 iso in a VirtualBox VM and tried to login to it via ssh with rancher user.
However the default password from previous releases did not work so I switched to root and changed it.
I noticed that autologin to virtual console with rancher user is enabled but what is the password?

**Comment by lucilecoutouly** [comment]
i have the same issue

**Comment by lucymhdavies** [comment]
I believe this change was made as a security measure for users who need to run the ISO on publicly exposed servers.
If I understand correctly, it's not the case that the password has been changed, it is instead the case that the password is no longer set at all.
https://github.com/rancher/os/issues/787

It is a little inconvenient having to set the password again if you need it, but it's not an insurmountable problem.

Pinging @joshwget who can correct me if I'm wrong :)

**Comment by yozh** [comment]
Hello,

I have this issue on 0.5.0 and I`m not able to login, I`m booting the ISO from grub2 and need to login to install rancherOS, but when I try to login with rancher/rancher from the console, it keeps saying login incorrect. I cant try SSH as I need to manually add the IP first....

**Comment by joshwget** [comment]
@lucymhdavies is completely right here. We've removed the default password for the `rancher` user intentionally.

@yozh I think your issue is something different since you're running v0.5.0. If you're booting the ISO from GRUB, perhaps the default kernel parameters from the ISO aren't being set. Try setting `rancher.password=password` as a kernel parameter and that should fix your issue.

**Comment by yozh** [comment]
@joshwget thank you, that worked !

**Comment by chinaares** [comment]
@joshwget  I use qemu-system-x86_64 to boot rancher vm, how to set rancher.password=password as a kernel parameter.

**Comment by imaia** [comment]
@joshwget is this documented? I had some trouble trying to find out the default password to scp my config yml to a new rancheros vm.

**Comment by peterrus** [comment]
Experiencing the same, can't seem to find any documentation about this. Booting the current iso through isolinux.

**Comment by SvenDowideit** [comment]
@peterrus your description feels like something that we should spell out in the docs - thank you for putting it "just right" :)

**Comment by SvenDowideit** [comment]
and that docs could be added as part of #1563

**Comment by cj-anthony** [comment]
Just pressing enter at the old password prompt in passwd doesn't seem to work anymore (rancheros 0.8.0), it says invalid password. I've booted off the iso and now I need to transfer a cloud-config file to the machine so I can start the install. Am I missing something here? What are my options now for getting a config file to the server so the install can start?

**Comment by kuhnroyal** [comment]
I have the same problem as @cj-anthony trying the latest 0.8.0rc11.
Autologin is successful but just pressing enter for the old password doesn't work anymore.

**Comment by cj-anthony** [comment]
> When booting from iso, it should do an autologin. If that doesnt happen you might have a state partition on your harddisk, I think there is a boot option to ignore that state partition.

Thanks, Peter. The autologin works just fine. It's the next part, connecting to the machine and transferring the cloud-config that was the issue. I suspect that the password for rancher is now no longer blank, but randomized. As such SCP connections won't be possible. I was able to get around this by sudoing passwd but it feels like I'm working against the developers and they intended me to get my cloud-config onto the server via other means, I just can't figure out what they are. As mentioned above I've solved it for now but if there's a more "official" way of doing this I'd be interested in hearing about it.

**Comment by SvenDowideit** [comment]
In v1.1 I added a Syslinux boot menu that allows you to select "autologin" and "debug"

hopefully this will help

**Comment by prudolf620** [comment]
Just came across rancherOS today as I'm looking to setup a simple docker box for learning and playing with some home projects.

I'm able to get rancheros ISO to boot from grub2 (machine is EFI only), however it doesn't seem to use the autologin and I'm at a loss of where to go from here.  I'm not seeing a default login/password documented anywhere and not having any luck with running 'passwd' as I get stuck in a loop.

Any help's appreciated.

**Comment by ryansch** [comment]
@prudolf620 Any reason why you're not just booting the ISO with the included syslinux?  I might not understand your EFI only comment.

Since you're using grub2, it might not have the normal kernel parameters set.  These might be useful:

`rancher.autologin=<tty>` will enable autologin on the specified tty
`rancher.password=<password>` will set the password for the `rancher` user

**Comment by prudolf620** [comment]
@ryansch Thanks for the reply.  FYI, the boot USB created from the ISO works fine on my desktop, but legacy mode and not UEFI.  The box I'm trying to install this on is a baytrail mini-pc that is 'windows mode' (EFI) only, and does not support bios.  If syslinux is supposed to be able to boot using EFI, I'll have to dig around for some guides for creating the bootable USB drive correctly.  Currently creating bootable drives using rufus in Windows.

I'll play with the kernel parameters with grub in the meantime.
