### ISSUE TITLE
Vagrant Host Permission

### ISSUE THREAD

**Issue by ricardson** [rancher/os#120]
Hi All,

When I try to build(docker build -t saltmaster .) my Dockerfile(CentOS)  that uses CentOS I get the below error:

     Rpmdb checksum is invalid: dCDPT(pkg checksums): bind-libs.x86_64 32:9.9.4-14.el7_0.1 - u

  If I use CentOS as HOST it's just work fine. Looks like it's related to the permission.

The "issue" I did open to CentOS Team
https://github.com/CentOS/sig-cloud-instance-images/issues/15   

My Dockerfile

     MAINTAINER Ricardson 'rwcs' Williams <ricardsonwilliams@gmail.com>
     RUN curl -s -L https://bootstrap.saltstack.com -o - | sh -s -- -M -X -D
     RUN yum -y install bind-utils dmidecode supervisor
     #Allow Salt-master access ANY minion (for test only)
     RUN sed -i "s/#auto_accept: False/auto_accept: True/g" /etc/salt/master
     #Setting minion configuration
     RUN sed -i "s/#master:.*/master: localhost/g" /etc/salt/minion
     COPY supervisord.ini /etc/supervisord.d/
     EXPOSE 4505 4506
     CMD ["/usr/bin/supervisord"]

**Comment by cloudnautique** [comment]
It looks like this might be related to what they are seeing in this issue docker/docker#10180. We are also using OverlayFS inside RancherOS. Will need to keep digging into this one.

**Comment by deniseschannon** [comment]
@ricardson We've moved away from using a vagrantfile and only support docker-machine. Due to this, I'll be closing this issue.
