### ISSUE TITLE
RancherOS docker ipvlan / macvlan support?

### ISSUE THREAD

**Issue by pwFoo** [rancher/os#1202]
Tested with latest pre-release of RancherOS, but it looks like docker 
1.12.1 doesn't support ipvlan / macvlan?

**Comment by pwFoo** [comment]
Looks like it works...

1. Manually create vlan interface @ primary interface + create macvlan docker network
2. automatically create a docker network macvlan with a unused interface 

So I close the issue...

**Comment by MayankTahil** [comment]
@pwFoo care to share your rancherOS cloud init file? I'm looking into MacVlan with Rancher OS as well.
