### ISSUE TITLE
Zpool persistence not working anymore with v0.6.0-rc6

### ISSUE THREAD

**Issue by tlvenn** [rancher/os#1203]
RancherOS: v0.6.0-rc6
Baremetal HD install

As described in this topic : https://forums.rancher.com/t/persistent-zpool-across-restart/3855
Following the ZFS guide with latest pre release version, things work however, once the server is rebooted, the zpool is gone.

Somehow it seems something is not working anymore around the invocation of the script `/opt/rancher/bin/start.sh`

I have tested this with v0.5 and it works fine and survive reboot as expected and documented.

**Comment by joshwget** [comment]
Confirmed that this is fixed in v0.6.0. Thanks for reporting this @tlvenn!
