### ISSUE TITLE
kernel-headers service redownloads on each boot

### ISSUE THREAD

**Issue by ryansch** [rancher/os#1204]
**RancherOS Version: (ros os version)**
v0.5.0

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
docker-machine

I've noticed this while using RancherOS as my local development VM.  If I'm in a coffee shop with limited bandwidth I notice the VM downloading the headers every time I run `docker-machine start`.

**Comment by joshwget** [comment]
You're right. I was able to confirm they're downloaded on each boot, which shouldn't be the case. Thanks for the heads up!

**Comment by SvenDowideit** [comment]
I'm contemplating building these files into the images directly to simplify the build&test pipeline I'm working on atm.

**Comment by ibuildthecloud** [comment]
@joshwget They download everytime there is a new console, so for default that is each boot.  For ubuntu and others it's cache.  But what @SvenDowideit is saying is really the right way to go here.

**Comment by SvenDowideit** [comment]
this should be resolved in https://github.com/rancher/os-kernel/pull/36 - the headers and extras images contain the files, and copy them to the base fs when installed (or the non-persistent console is booted)

**Comment by deniseschannon** [comment]
Verified with v0.8.0-rc4.

Headers remained in `/lib/modules` and no longer installed in `/usr/lib`.
