### ISSUE TITLE
rancheros-openstack.img

### ISSUE THREAD

**Issue by chinaares** [rancher/os#1210]
**RancherOS Version: (V0.6.0 rc1-rc9)**
Please release rancheros-openstack.img and rancheros-raspberry-pi.zip together,cause of my poor network so slowly。

Thanks a lot!!

**Comment by deniseschannon** [comment]
What do you mean by together?

**Comment by chinaares** [comment]
Thank you for your reply! 
I means if you release a rc version(like V0.6.0 rc1-rc9), at the same time build and release rancheros-openstack.img together!  convenient for us using rancheros on openstack!

**Comment by chinaares** [comment]
I found at https://releases.rancher.com/os/latest/,already supplied!
