### ISSUE TITLE
Docker 1.12.1 not available on arm

### ISSUE THREAD

**Issue by djmaze** [rancher/os#1213]
**RancherOS Version: (ros os version)**
0.6.0

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
Odroid XU-4 (custom-built, with armhf root from 0.6.0 release).

Currently, it is not possible to switch to the newest Docker version on armhf (with the new version switcher):

`Tag 1.12.1_arm not found in repository docker.io/rancher/os-docker`

Any plans to make this version available on arm?

**Comment by ibuildthecloud** [comment]
@djmaze We ran into a last minute (non-technical) issue with Docker 1.12 on arm64.  As a result we didn't release 1.12 on either armv7 or arm64.  We hope to address this shortly.

**Comment by alkar** [comment]
Hi, I'm still not able to switch to 1.12. Any updates on this / plans?

**Comment by SvenDowideit** [comment]
closing - I built 1.12.6 and 17.03 etc on arm a while back - though 17.06 will be a problem on arm64 for a little while.
