### ISSUE TITLE
Kernel panic with 0.6.0

### ISSUE THREAD

**Issue by pwFoo** [rancher/os#1216]
**RancherOS Version: (ros os version)**
0.6.0

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
vmware, kvm

Kernel panic with RancherOS during container action. First with vmware RancherOS, reproduced with kvm RancherOS. Both 0.6.0.

```
docker run --rm -ti alpine sh
/ # 
/ # 
/ # 
/ # 
/ # 
/ # 
/ # apk -U add sudo
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/community/x86_64/APKINDEX.tar.gz
(1/1) Installing sudo (1.8.16-r0)
 23% [##################################################### 
```

Each time I installed sudo inside a simple alpine container the RancherOS gets a kernel panic.

No problem with wget, tar, libcap install. 

But also apache2 cause a kernel panic...

```
/ # apk add apache2
(1/6) Installing libuuid (2.28-r3)
(2/6) Installing apr (1.5.2-r0)
(3/6) Installing expat (2.1.1-r1)
(4/6) Installing apr-util (1.5.4-r1)
(5/6) Installing pcre (8.38-r1)
(6/6) Installing apache2 (2.4.23-r1)
Executing apache2-2.4.23-r1.pre-install
 46% [########################################################################################################## 
```

Any idea? RancherOS 0.6 related? Also tested and reproduced with 0.6.0-rc7 (maybe it was rc8 instead of rc7...)

**Comment by pwFoo** [comment]
Downgraded to 0.5.0 and the kernel panic is gone!

```
docker run --rm -ti alpine sh
/ # apk -U add sudo
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/community/x86_64/APKINDEX.tar.gz
(1/1) Installing sudo (1.8.16-r0)
Executing busybox-1.24.2-r9.trigger
OK: 5 MiB in 12 packages
```

**Comment by ibuildthecloud** [comment]
Wow, crazy!  Investigating.

**Comment by ibuildthecloud** [comment]
@pwFoo Extra internet points to you!  This is a kernel upstream issue in Linux 4.4 in overlayfs.  The same bug exists in Ubuntu 16.04.1 (from which our kernel is based).  It appears this issue is fixed in 4.6.5 but I believe a backport already exists.  Ubuntu 16.04 primarily uses ZFS or aufs so this isn't as urgent of an issue for them, but it is for us.  We will fix this shortly.

Thanks for the concise bug report!

**Comment by pwFoo** [comment]
Yes, crazy issue. I killed two different VMs some times because I can't believe what happened here *g*

Thanks for explaination!

**Comment by ryansch** [comment]
@ibuildthecloud Will the fix come as a new release (ex: 0.6.1)?

**Comment by joshwget** [comment]
@ryansch Yes, this will be fixed as a new release.

**Comment by deniseschannon** [comment]
Verified with v0.6.1-rc1
