### ISSUE TITLE
EC2 machine very slow to stop and reboot

### ISSUE THREAD

**Issue by ebuildy** [rancher/os#1222]
**RancherOS Version: (ros os version)**

Rancher 0.5.0

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**

AWS

From AWS UI, I want to stop the machine, usually this takes some secondes, here with RancherOS some minutes, why?

Many thanks.

**Comment by whiteadam** [comment]
Just a thought, but it might be a long shutdown process because of the use of user-docker, system-docker, mounted volumes, and etc. I bet the graceful shutdown of so many services takes time.

**Comment by ebuildy** [comment]
Good to know!

It takes time but it stops well. Thanks you

**Comment by joshwget** [comment]
RancherOS shuts down as quickly as most other distros I've tried, so I'm thinking this is something specific to AWS.

**Comment by SvenDowideit** [comment]
closing as anwsered
