### ISSUE TITLE
rancher.state.autoformat doesn't work anymore in 0.6.0

### ISSUE THREAD

**Issue by segator** [rancher/os#1224]
**RancherOS Version: (ros os version)**
0.6.0
**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
Vmware vshpere 5.5 + ipxe cloud config

I was a happy cloud config deploy-man using rancher cloud config with 0.5.0, but  I upgraded my ipxe to 0.6.0 and it's seems all servers are not able to mount hard drive /dev/sda anymore, if I try to put empty HDD, rancher doesn't try to format the HDD, I didn't modify anything from the cloud config and ipxe and before was working, so I supose is a bug on this new version

I have this in the IPXE
`kernel ${base-url}/vmlinuz rancher.state.autoformat=[/dev/sda] rancher.state.formatzero=true rancher.cloud_init.datasources=['${config-file}']`

and the cloud config file
`#cloud-config
rancher:
  state:
    fstype: auto
    dev: LABEL=RANCHER_STATE
    autoformat:
    - /dev/sda
  ..........`

**Comment by joshwget** [comment]
Prior to v0.6.0, `LABEL=RANCHER_STATE` was the default value for `rancher.state.dev`. We decided to make this opt-in as most people expect an ISO to boot from memory and be stateless.

I think you just need to add `rancher.state.dev=LABEL=RANCHER_STATE` as a kernel parameter. You have it in your cloud-config, but this file won't be fetched until after state would have been mounted.

**Comment by segator** [comment]
thank you, now works again!
