### ISSUE TITLE
RFE ROS to look for cloud-config at a generic domain/url

### ISSUE THREAD

**Issue by aemneina** [rancher/os#1230]
This would simplify automated provisioning of ROS in bare metal environments where control of DHCP/PXE is limited.

**Comment by joshwget** [comment]
This is possible with the `url` datasource. Tagging this as docs instead of a feature request.

**Comment by SvenDowideit** [comment]
it would, but we can't set it to a static hostname, as that just makes it trivial for someone to hijack a RancherOS on a network that doesn't already have that.

**Comment by SvenDowideit** [comment]
I'm going to close this as having too many risks
