### ISSUE TITLE
Published 0.6.1 AMIs are ECS optimized

### ISSUE THREAD

**Issue by ryansch** [rancher/os#1231]
**RancherOS Version: (ros os version)**
0.6.1

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
AWS

I had to search for what appears to the the correct AMI on the AMI marketplace.

Edit: I've only tested the AMI for us-east-1: `ami-af7d0bb8`  It appears the correct AMI for us-east-1 is `ami-a8d2a4bf`.

**Comment by deniseschannon** [comment]
@ryansch Thanks! I had mixed up the tables between our Amazon ECS ones and regular ones. I've updated it now.
