### ISSUE TITLE
ros install stalls (agetty issue)

### ISSUE THREAD

**Issue by rvlander** [rancher/os#1234]
**RancherOS Version: (ros os version)**
0.6.0

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
pcengine apu via serial port (there is no graphic output on this board).

After typing :
`sudo ros install -d /dev/sda`

I am prompted :
`Continue [y/N]`

I type y + Enter and then nothing happens and `ros` seem stalled. When I quit the process and mount the partition on sda, there is nothing on it.

Note: I can boot via serial port changing boot options. However, I can't see the boot sequence.

**Comment by joshwget** [comment]
Can this be consistently reproduced, or does this only happen some of the time? Does the same thing happen when installing via SSH?

Regarding seeing the boot sequence, you might need to add the appropriate TTY as a kernel parameter, e.g. `console=ttyS0`.

**Comment by rvlander** [comment]
@joshwget I made a usb boot key using unetbootin which generate two grub entries, I already modified its 2 entries using `console=ttyS0, 1152000`.

The fact that there is no boot sequence is due to the fact that the first entry is generated by unetbootin doing some manipulation on the kernel he finds in the iso. I can boot using this entry (but then `ros install ` stalls). I will try to connect via ssh once booted and come back to you.

Using the second entry (which boots the rancheros kernel as is), the boot sequence is displayed but there is a kernel panic as reported in #984

Trying to use IPXE, I have an error during boot sequence saying that rootfs can't be uncompressed because it appears to be a initrd...

**Comment by joshwget** [comment]
I've actually been running into a similar issue when trying to switch consoles in a serial console with QEMU. Pretty sure these two are related.

**Comment by SvenDowideit** [comment]
very interesting. I started kicking this, and it looks like the qemu problem only happens for some consoles, and only on ttyS0 _IF_ you havn't `ros console switch`ed in another shell (ssh for eg) previously.

doing a fresh boot with a debian console previously enabled doesn't seem to have a problem (ok, I'm going to try a fresh install with debian just in case)

its not just `ros`, `read -p type something yn` doesn't work.

**Comment by SvenDowideit** [comment]
@rvlander, if you remove that from your setup, and add `rancher.password=rancher` after you login, does the install prompt work again?

or alternatively, if you `ros console enable debian` and reboot, that works for me.

**Comment by SvenDowideit** [comment]
and to add insult to injury, using `/sbin/getty -n -l /bin/sh 115200 ttyS0` works (you're logged in as root tho), while `/sbin/agetty --autologin rancher 11520 ttyS0` doesn't.

**Comment by SvenDowideit** [comment]
it'd be nice if respawn supported SIGHUP for re-reading the cfg.

**Comment by SvenDowideit** [comment]
Next TODO is to compare the code for the busybox / alpine getty and agetty as switching between them makes a difference. I fear the centos/fedora pair might have more todo with an assumption of systemd magics, but hopefully that's just my ignorance talking.

**Comment by SvenDowideit** [comment]
I've just experienced this on a normal hardware console while testing 0.8.0-rc3 - so it looks like this will get more attention very soon.

**Comment by SvenDowideit** [comment]
it looks to me like the qemu issue can be solved by running `reset` after the autologin - so obviously the default console's autologin isn't initializing the console fully.

**Comment by SvenDowideit** [comment]
#1931 fixes this  - calling `login -f rancher` on most consoles, and just running `bash --login` on centos and fedora
