### ISSUE TITLE
Rancher OS: ISO corrupting USB disk

### ISSUE THREAD

**Issue by rvlander** [rancher/os#1235]
**RancherOS Version: (ros os version)**
0.6.0

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
baremetal

Burning latest ISO to USB disk using dd result in corrupted partition table: Invalid partition table - recursive partition on /dev/sdc

**Comment by SvenDowideit** [comment]
@rvlander I just tested with the iso at https://github.com/rancher/os/releases/tag/v0.6.0

```
root@t440s:~/src/rancher# dd if=rancheros-v0.6.0.iso of=/dev/sdb
83968+0 records in
83968+0 records out
42991616 bytes (43 MB, 41 MiB) copied, 12.7779 s, 3.4 MB/s
root@t440s:~/src/rancher# 
root@t440s:~/src/rancher# 
root@t440s:~/src/rancher# sync
root@t440s:~/src/rancher# fdisk -l /dev/sdb
Disk /dev/sdb: 1.9 GiB, 2063597568 bytes, 4030464 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x4b61a409

Device     Boot Start   End Sectors Size Id Type
/dev/sdb1  *        0 83967   83968  41M 17 Hidden HPFS/NTFS
```

and it booted ok

its possible that the download was incomplete, or that the `dd` copy was still cached in memory - I've been running `sync` after a `dd` for way too many years, but perhaps its still useful :)

**Comment by SvenDowideit** [comment]
closing - I presume you've found a solution :)
