### ISSUE TITLE
FS Resize Unreliable

### ISSUE THREAD

**Issue by ryansch** [rancher/os#1237]
**RancherOS Version: (ros os version)**
0.6.1
**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
AWS

I started 9 instances and only 5 of them did the resize.  I manually ran the 0.4.5 resize container on the other 4 and it did the right thing.

These instances are started through two different ASGs so they should be identical within those two groups.  Both groups were affected.

**Comment by joshwget** [comment]
Can you post the output of `system-docker logs cloud-init-execute` for one of the instances where resize failed?

**Comment by ryansch** [comment]
```
time="2016-09-14T17:45:29Z" level=info msg="Running cloud-init-execute: pre-console=true, console=false"
time="2016-09-14T17:46:04Z" level=error msg="Failed to resize /dev/xvda: exit status 1"
```

**Comment by ryansch** [comment]
I have `RESIZE_DEV: /dev/xvda` set in the cloud config environment.

**Comment by joshwget** [comment]
Looks like we don't capture the output from the resize commands, so the logs don't reveal too much. I'll spin up some instances until I can reproduce this and then debug from there. Thanks @ryansch!

**Comment by ryansch** [comment]
Thanks!

**Comment by schuylr** [comment]
Seeing this issue with v0.6.0 as well.

**Comment by fifthecho** [comment]
I'm having this issue with ami-a8d2a4bf which is also preventing any further services or cloud-init data from executing.

**Comment by joshwget** [comment]
The following can be used as a workaround.

```
rancher:
  environment:
    RESIZE_DEV: /dev/xvda
  services_include:
    https://raw.githubusercontent.com/rancher/os-services/v0.4.5/r/resize-fs.yml: true
```

**Comment by schuylr** [comment]
Yep that hack works for me, I can also confirm that `docker run -it --rm --privileged slamper/disk_resizer xvda` (stolen from @CumpsD in #1099) will resize already-initialized instances.

**Comment by deniseschannon** [comment]
Verified with v0.7.0-rc3. 

Ran 30 instances in AWS and all re-sized as expected.
