### ISSUE TITLE
Proposal: moving os-release from /etc to /usr/lib

### ISSUE THREAD

**Issue by kascador** [rancher/os#1241]
**RancherOS Version: (ros os version)**
0.6.1
**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
barmetal

From https://www.freedesktop.org/software/systemd/man/os-release.html, it seems that the file "os-release" should be at /usr/lib.

Could it be possible in the next release to move the file "os-release" from /etc to /usr/lib, and create a symlink in the /etc folder for backwark compatibility?

I've found this because currently I've got a warning in my system-docker.log complaining about this:
level=warning msg="Could not get operating system name: Error opening /usr/lib/os-release: open /usr/lib/os-release: no such file or directory"

**Comment by joshwget** [comment]
Sure, sounds reasonable. It's interesting that Docker gives this error since it sounds like it should be reading from `/etc/os-release` first.

**Comment by SvenDowideit** [comment]
fix in #1308

this issue shows up when you start rancheros with `rancher.debug`

**Comment by deniseschannon** [comment]
The `os-release` file is missing in v0.8.0-rc4. 

```
$ cat /etc/os-release 
cat: can't open '/etc/os-release': No such file or directory
$ cat /usr/lib/os-release 
cat: can't open '/usr/lib/os-release': No such file or directory
```

**Comment by SvenDowideit** [comment]
#1532 merged - it should fix this.

**Comment by deniseschannon** [comment]
Verified using v0.8.0-rc6 that it's located in both places.

**Comment by kuhnroyal** [comment]
Getting a lot of this on 0.8.0:

```
> time="2017-02-15T12:19:49.309654198Z" level=warning msg="Could not get operating system name: Error opening /usr/lib/os-release: open /usr/lib/os-release: no such file or directory"
time="2017-02-15T12:19:49.309654198Z" level=warning msg="Could not get operating system name: Error opening /usr/lib/os-release: open /usr/lib/os-release: no such file or directory"
```
