### ISSUE TITLE
Removal of user password from ISO breaks packer image creation

### ISSUE THREAD

**Issue by OldCrowEW** [rancher/os#1242]
**RancherOS Version: (ros os version)**
v0.6.1

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
Archlinux build host. Packer version: 0.9.0

It seems as though the default rancher/rancher username/password has been removed for [security reasons](https://github.com/rancher/os/issues/1198).

This breaks packer's ability to create images in an automated way. I have tested my repo, and the official https://github.com/rancher/os-packer Both appear to have issues. I have a hack to get around the issue but feel this needs further discussion. Here is the [commit](https://github.com/OldCrowEW/rancheros-openstack/commit/dbc2498e6db72986021f4fad2de3c86c61e313dd) with my workaround.

**Comment by SvenDowideit** [comment]
it looks like they solved it in os-packer using 

```
     "boot_command":
     [
        "sudo -i<enter>",
        "echo rancher:rancher | chpasswd<enter>"
     ],
```

I'm going to close this - as there seem to me more than one ways to skin this cat
