### ISSUE TITLE
GCE installation failed

### ISSUE THREAD

**Issue by xinity** [rancher/os#1246]
**RancherOS Version: 0.6.1**

**Where are you running RancherOS? GCE**

I'm trying to deploy RancherOS instances on GCE but it failed

while i've been successful installing Rancher on a CoreOS instance, i've tried to deployed from Rancher , 3 node based on latest RancherOS release (system image pushed in a bitbucket as it doesn't exist by default on google GCE)

Here is the ouput log on the rancher instance:
```
2016-09-20 07:24:55,141 ERROR [394479a3-07d3-4628-a13c-80c7f71836c0:16083] [instance:378] [instance.start->(InstanceStart)] [] [utorService-259] [i.c.p.process.instance.InstanceStart] Failed to Scheduling for instance [378] 
time="2016-09-20T07:25:33Z" level=info msg="stdout: The default lines below are for a sh/bash shell, you can specify the shell you're using, with the --shell flag." resourceId: =1ph21 
time="2016-09-20T07:25:33Z" level=info msg="stdout: " resourceId: =1ph21 
time="2016-09-20T07:25:34Z" level=info msg="stderr: Error creating machine: Error detecting OS: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded" resourceId=1ph21 
time="2016-09-20T07:25:34Z" level=info msg="starting cleanup..." machine name=app-node1 
time="2016-09-20T07:25:35Z" level=info msg="stdout: The default lines below are for a sh/bash shell, you can specify the shell you're using, with the --shell flag." resourceId: =1ph22 
time="2016-09-20T07:25:35Z" level=info msg="stdout: " resourceId: =1ph22 
time="2016-09-20T07:25:35Z" level=info msg="stderr: Error creating machine: Error detecting OS: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded" resourceId=1ph22 
time="2016-09-20T07:25:35Z" level=info msg="starting cleanup..." machine name=app-node2 
```
in the serial port on GCE i have : 
```
SeaBIOS (version 1.8.2-20160811_132127-google)
Total RAM Size = 0x00000000f0000000 = 3840 MiB
CPU Mhz=2601
CPUs found: 1     Max CPUs supported: 1
found virtio-scsi at 0:3
virtio-scsi vendor='Google' product='PersistentDisk' rev='1' type=0 removable=0
virtio-scsi blksize=512 sectors=20971520 = 10240 MiB
drive 0x000f4750: PCHS=0/0/0 translation=lba LCHS=1024/255/63 s=20971520
Booting from Hard Disk 0...
```
**UPDATE**
tried with gcloud:
gcloud compute instances create --project myproject --zone europe-west1-c rancher-server2 --image https://www.googleapis.com/compute/v1/projects/myproject/global/images/rancheros

same error :(

Any chances you can help fixing this ? :)

**Comment by deniseschannon** [comment]
1. Are you trying to deploy to RancherOS through Rancher using docker-machine? 

2. When using `glcoud` How are you adding in your ssh keys to the instance? Is your SSH key part of your metadata in your GCE project?  I don't see you passing in user data with a cloud config: http://docs.rancher.com/os/running-rancheros/cloud/gce/#using-a-cloud-config-file-with-gce

We've noticed that the serial output doesn't get updated properly in GCE.

**Comment by xinity** [comment]
1. indeed !
2. i think right as i can ssh to my GCE instances (coreos ones) using gcloud

i've just made several tests but still failing using RancherOS latest (coreos or any other distro from GCE library works)

**Comment by xinity** [comment]
same behavior with 0.6.0

**Comment by deniseschannon** [comment]
And just to confirm, you are trying ssh-ing in as the rancher user?

**Comment by xinity** [comment]
Hum.....  I think rancher uses default username, I think it is :docker-user correct?

**Comment by xinity** [comment]
@deniseschannon it seems to be working .

2 things:
- rancher by default using docker-user instead of rancher
- you were right about the serial console port

i'll dig in a bit more and let you know how it goes.

**Comment by deniseschannon** [comment]
@xinity Yes, I forgot we also have support for the `docker` user, so using `docker-machine` doesn't require the rancher user. 

It sounds like you're able to ssh in and user RancherOS on GCE. Let me know if you have issues, otherwise I'll close this issue.

**Comment by xinity** [comment]
@deniseschannon out of the box rancher uses docker-user instead of docker or rancher 
maybe that's what made me think that rancherOS doesn't work

**Comment by deniseschannon** [comment]
This is the default that the docker-machine driver uses, not Rancher. We populate with the defaults that Docker provides as we don't know what OS type you are going to select.

https://docs.docker.com/machine/drivers/gce/

If you are launching a GCE instance that is running RancherOS, you would need to update the `username` (i.e google-username) to `rancher`

**Comment by xinity** [comment]
@deniseschannon thanks a lot for your help!

everything is fine with latest rancheros on GCE (nice nice nice !!)

i'll close this issue which was at first a misunderstanding on my side :)
