### ISSUE TITLE
Bare metal install fails

### ISSUE THREAD

**Issue by xinity** [rancher/os#1248]
**RancherOS Version: 0.6.1**

*_Where are you running RancherOS? baremetal *_

trying to install latest rancherOS in bare metal mode, i have a strange issue.

i creating a cloud-config.yml containing something like:
- #cloud-config
  ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADABKPOJBBDOZPQCnTiL9JpUJXgixt501m/MMKJDBZJPP3OCBBPPLB2IOJND/6AY4BF9mGNRfk70Cp4cvZQ0bj6S2M62WwzpRfloNf4kA+UWeO+qsdqksjdqlksjdlk+KA1fOeguIPbSveCXx1uNngiWzhT/McdR1ipmrdqHmuMw6Z3biYjxXUXl3l5tj15syBeqrVqAetiJvgu+doxn5t6eokLtygGJOehcFcIMSx1eoS4CR0PzZLYpAYhz4KaMROP8w0My+qeT/KETdhxdi/FLK33L5K23KRFJH235H230R9 

while trying to install rancherOS using:
sudo ros install -c cloud-config.yml -d /dev/sda

it fails with a message saying:
![rancheros_install_ko](https://cloud.githubusercontent.com/assets/1799009/18778559/2676af70-8175-11e6-8adc-67f01e76e622.png)

any cluses on fixing this ?

Thanks a lot guys!

**Comment by joshwget** [comment]
Do you perform any other actions before the install? I haven't been able to reproduce this yet.

**Comment by xinity** [comment]
Aside deleting disk partitions before launching the install nothing @joshwget

**Comment by joshwget** [comment]
Does this issue occur only on this bare metal host, or do you also see this issue elsewhere?

**Comment by xinity** [comment]
@joshwget bare metal only doing remote installation via KVM

**Comment by SvenDowideit** [comment]
closing as old - the install code is very different now, so likely has a different set of problems.
