### ISSUE TITLE
build to run without docker

### ISSUE THREAD

**Issue by ranmacar** [rancher/os#1253]
**RancherOS Version: (ros os version)**
none
**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
none

Hi, 

Just stumbled upon the project, and it looks awesome as a base for my docker adventures. In the end, I'd like to have a fully dockerized personal os. What I am wondering is, is there a simple way to build an image that does not contain docker at the end? Just all the containers baked into place.

Cheers,

**Comment by joshwget** [comment]
User Docker is optional, but System Docker is definitely required. Without a container engine around you wouldn't be able to start any containers.

**Comment by ranmacar** [comment]
I understand that you probably lose container  security and networking setup when de-containing, but thought you could do it somehow. Maybe just systemd would be a way.

**Comment by joshwget** [comment]
Docker is the only process supervisor in RancherOS. We intentionally don't include others such as systemd. This is one of the fundamental ideas of RancherOS, so I don't think what you're looking for will be possible.
