### ISSUE TITLE
preload-system-images does not actually do anything and can be removed

### ISSUE THREAD

**Issue by sols1** [rancher/os#1257]
**RancherOS Version: (ros os version)** 0.6.1 (doesn't matter)

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)** bare metal (doesn't matter)

**Comment by joshwget** [comment]
Can you explain why you think it doesn't do anything? Is there an issue with it that you've run into?

**Comment by sols1** [comment]
There is no functional issue - it's just a waste of time and resources.

System docker images are actually loaded by:

```
grep -rn --color -A 5 "Loading images" *
init/sysinit.go:80:		log.Infof("Loading images from %s", inputFileName)
init/sysinit.go-81-		if _, err = client.ImageLoad(context.Background(), input, true); err != nil {
init/sysinit.go-82-			return cfg, err
init/sysinit.go-83-		}
init/sysinit.go-84-
init/sysinit.go-85-		log.Infof("Done loading images from %s", inputFileName)
```

If you look inside preload-system-images, you won't find images.tar file.

And from common sense point of view preload-system-images cannot possibly preload images into system docker b/c it is itself must be preloaded before it can do anything - i.e. it is a chicken and egg problem.

**Comment by joshwget** [comment]
The use cases for the feature are a bit more advanced, but it does have value. Imagine you're creating a custom AMI and want to include an image without having to download it for each new instance. You could add the image to disk with Packer and then preload-system-images would load it on first boot.

**Comment by joshwget** [comment]
I think our goal is to always keep preloading around for System Docker, so I'm going to close this issue. Once #1278 is fixed it should have basically no effect on boot time if you're not making use of the feature.

**Comment by sols1** [comment]
My 2 cents: even if somebody wanted to load images into system docker it would likely to fail b/c system docker is quite screwed up at this point, e.g.: #https://github.com/rancher/docker/commit/1fb6ae53577893d1453e915ce10ba0af30520342 and #https://github.com/rancher/docker/commit/ac28f413b28d3f8b0ff6907a680498218f5d3c8f

```
func (daemon *Daemon) updateContainerNetworkSettings(container *container.Container, endpointsConfig map[string]*networktypes.EndpointSettings) error {
	return nil
}

func (daemon *Daemon) updateNetwork(container *container.Container) error {
	return nil
}

func (daemon *Daemon) allocateNetwork(container *container.Container) error {
	return nil
}
```
