### ISSUE TITLE
@joshwget doesn't like the `ros os` command.

### ISSUE THREAD

**Issue by SvenDowideit** [rancher/os#1274]
> On a somewhat related topic, I don't really like the ros os subcommand in general. It seems like both
> words basically mean the same thing and it's only used for ros os upgrade and ros os list. I think this
> made more sense when it was rancherctl os ... and then when we moved to ros it was never 
> updated.
> 
> Instead, maybe we could just move ros os upgrade to ros upgrade and include ros os list
> functionality in ros version. It's not a perfect fit for ros version, but I think it might be preferable to
> what we currently have.

I (Sven) have no opinion - so long as `ros -v` works without doing an internet request, `ros version` can be verbose - and a synonym for `ros versions` :)

**Comment by ibuildthecloud** [comment]
Can't say I like `ros os ...` either.
