### ISSUE TITLE
rancher.cloud_init.datasources failing to parse

### ISSUE THREAD

**Issue by ChromoX** [rancher/os#1283]
**RancherOS Version: (ros os version)**
Latest directly from the RancherOS HTTP

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
Baremetal

When trying to boot RancherOS starts up and attempts to download my cloud-config from a local server.

The following is in my ipxe file:
```
rancher.cloud_init.datasources='["url:http://192.168.12.10:8999/cloud-config"]'
```

The error that prints in the console is the following:
```
Failed to parse configuration: Cannot resolve [“url:http://192.168.12.10:8999/cloud-config“] into <[]string Value> at line 74, column 17
```

Any suggestions?

**Comment by joshwget** [comment]
Can you try taking off the outer single quotes?

**Comment by ChromoX** [comment]
Thanks @joshwget that fixed the issue. Now there is a kernel panic...

Just as a note I followed the syntax on this documentation page: http://docs.rancher.com/os/running-rancheros/server/pxe/

**Comment by joshwget** [comment]
Thanks @ChromoX. In v0.7.0 the inner quotes won't be necessary so this issue is avoided.
