### ISSUE TITLE
Service commands shouldn't be direct copies from libcompose

### ISSUE THREAD

**Issue by joshwget** [rancher/os#1287]
Other than `enable`, `disable`, `list`, and `delete`, all `ros service` commands are directly imported from the libcompose `cli` package. It would be better to have our own versions of these commands so we can tailor them to RancherOS use cases.

There are likely others, but these changes would be a good start.
- `-d` should be the default
- `-f` and `-p` should be disabled
- If no service is specified for an operation, we should throw an error rather than applying that operation to all services

**Comment by deniseschannon** [comment]
Verified that the help looks fixed so that irrelevant commands are hidden in v0.8.0-rc4
