### ISSUE TITLE
Warning: '--restart' is deprecated, it will be removed soon. See usage.

### ISSUE THREAD

**Issue by SvenDowideit** [rancher/os#1297]
**RancherOS Version: 0.7.0-dev)**

in system-docker.log

**Comment by joshwget** [comment]
I'm not really sure what this is being deprecated in favor of (https://forums.docker.com/t/alternative-to-restart-no-to-docker-daemon/3214/5). We'll have to keep an eye on this since we need this feature for System Docker.

**Comment by ibuildthecloud** [comment]
I've commented many times in dockerland that we need this feature.
