### ISSUE TITLE
catalog cache too agressive

### ISSUE THREAD

**Issue by SvenDowideit** [rancher/os#1300]
**RancherOS Version: 0.7-dev**

we probably need to add a `ros <service|console|os> --refresh <list|enable>` to force a cache flush, and to not cache the file on errors (both network and parse)

```
[rancher@rancher-dev ~]$ sudo ros console list
ERRO[0000] Failed to unmarshal https://raw.githubusercontent.com/SvenDowideit/os-services/test/index.yml: Cannot resolve  into <[]string Value> at line 14, column 8 
disabled centos
disabled debian
current  default
disabled fedora
disabled ubuntu
disabled xfce
[rancher@rancher-dev ~]$ sudo rm /var/lib/rancher/cache/*
[rancher@rancher-dev ~]$ sudo ros console list
disabled alpine
disabled centos
disabled debian
current  default
disabled fedora
disabled ubuntu
disabled xfce
```

**Comment by joshwget** [comment]
Do you think caching has value for anything other than service definitions? I'm thinking that's the only use case where we should be doing this.

Refreshing a cached service definition opens up a few other questions too. If the service is already running and a refresh changes the service definition then there will be a mismatch between the running service and the definition. We'd probably have to store the existing service definition and have a thorough story for upgrading a service.

**Comment by ibuildthecloud** [comment]
@joshwget We should really rethink the whole os-services thing.  The caching was added for one reason.  Once something is installed we shouldn't go to the internet anymore.  Like once you do `apt-get install foo` it just installs what was current and never checks again.  The approach we took was probably wrong.  Before if you did `ros service enable` on every boot it would redownload the yml file for the service.

So the only real requirement is that when we do `ros service enable` we make a local copy of the service file.  Instead we are caching a lot more and causing more of a headache....

**Comment by SvenDowideit** [comment]
cool - I think we'll park it til next week when I'm in town - I have some very un-finished thoughts that might simplify things - or i might be so wrong its not funny :)

**Comment by joshwget** [comment]
Yeah, I think we all agree we should only be doing this for service definitions. I think the other part of what you're saying is to have `--refresh` be the default. I like that idea.

**Comment by joshwget** [comment]
Okay, let's hold off to discuss this in person then!

**Comment by ibuildthecloud** [comment]
@joshwget how dare you speak of speaking offline online :)
