### ISSUE TITLE
Untar re-exec error, no space left on device

### ISSUE THREAD

**Issue by dvorakluk** [rancher/os#1310]
Hi, I've just rebooted our ec2 server with rancheros and it didn't came back. What should I try to recover it? It was running smoothly about two weeks till today.

**RancherOS Version: 0.6.1**
**Where are you running RancherOS? AWS** (t2.medium - 4GB of RAM)

![rancheros](https://cloud.githubusercontent.com/assets/4776553/19272389/ae13407c-8fc8-11e6-98af-f18b14f3b6fd.jpeg)

**Comment by SvenDowideit** [comment]
I'm going to guess that atm, the easiest thing to do is to detach the volume from your current ec2 instance, then attach it as a non-root volume to another instance, boot, mount it, and decide what to move away.

IDK the boot params well enough yet, there might be a way to change the sysinit

this is another reason why we'll be working on a recovery console very soon.

**Comment by dvorakluk** [comment]
Sure, thank you for response. I just thought (based on other issues reported here at github), that the images are being unpacked into ram.

**Comment by SvenDowideit** [comment]
@dvorakluk the re-exec error comes from the Docker daemon :/
