### ISSUE TITLE
hang on boot: unregister_netdevice: waiting for veth87a8c6d to become free. Usage count = 1

### ISSUE THREAD

**Issue by sols1** [rancher/os#1319]
**RancherOS Version: (ros os version)** 0.6.1

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)** bare metal

Error message repeated multiple times:

`unregister_netdevice: waiting for veth87a8c6d to become free. Usage count = 1
`

This does not happen on every boot, however, when it does happen it's impossible to login into the machine either through ssh or through BMC console.

It looks like a well known kernel bug affecting docker #https://github.com/docker/docker/issues/5618 which is claimed to be fixed in 4.4.22 kernel #https://github.com/docker/docker/issues/5618#issuecomment-252420204

Can RancherOS kernel be upgraded to 4.4.22?

**Comment by ibuildthecloud** [comment]
@sols1 Yep, we are looking to bump to 4.4.24.  Been waiting for this fix for a long time.

**Comment by deniseschannon** [comment]
We are still using 4.4.21, but we backported the patch for this issue. 

As this issue is hard to reproduce. If you see this issue after v0.7.0 is released, can you please re-open? @sols1

**Comment by sols1** [comment]
When is v0.7.0 supposed to arrive?

**Comment by deniseschannon** [comment]
@sols1 Should be the next day or two? You could try using v0.7.0-rc7 if you want. It has the patch in it.

**Comment by sols1** [comment]
When are you going to upgrade to 4.4.22 proper or later? Is it after the buildroot upgrade?

**Comment by joshwget** [comment]
@sols1 Next release, very likely. The Ubuntu kernel isn't actually on that version yet. Buildroot upgrades are independent of kernel upgrades, AFAIK.
