### ISSUE TITLE
containers with `--restart=always` do not get restarted after switching consoles

### ISSUE THREAD

**Issue by deniseschannon** [rancher/os#1323]
**RancherOS Version: (ros os version)**
v0.6.1 and v0.7.0-rc5

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
AWS

I have containers with a restart policy of always and they don't get restarted after switching consoles. 

Steps to Reproduce:
1. Create a container `sudo ros -d --restart=always nginx`
2. Switch consoles `sudo ros console switch ubuntu`

Result:
Console switches, but nginx container never starts.
Docker is running because I can find the container when doing `docker ps -a`

Note: They do restart after upgrade and doing `sudo system-docker restart docker`.

**Comment by joshwget** [comment]
This appears to be magically fixed in v0.8.0-rc1 :tada:

**Comment by joshwget** [comment]
Tested with v0.8.0-rc1 and added integration tests in #1436
