### ISSUE TITLE
Cannot SSH into RancherOS Azure

### ISSUE THREAD

**Issue by munjalpatel** [rancher/os#1344]
Hello,

I just provisioned RancherOS through new Azure Portal.
But regardless wether I select SSH or Password as a security mode, I am not able to SSH into the RancherOS server. I keep getting prompted for the password and after a few prompts, I get the following error (even though the security mode is private key or password):

`Permission denied (publickey,password).`

**Comment by joshwget** [comment]
RancherOS isn't supported on Azure yet so unfortunately we can't provide any support for it. The version that's up there is quite old. You can track Azure support in #84.
