### ISSUE TITLE
Bash completion for Docker in other consoles

### ISSUE THREAD

**Issue by joshwget** [rancher/os#1345]

**Comment by homme** [comment]
The following worked for me in the interim in terms of getting docker command completion:

    sudo curl -L -o /etc/bash_completion.d/docker https://github.com/docker/cli/raw/master/contrib/completion/bash/docker

Then log out and back in again, or just `source  /etc/bash_completion.d/docker`.

**Comment by TBK** [comment]
Depending on your console the distro might prodive docker completion packages.

Here are the packages for Alpine:
https://pkgs.alpinelinux.org/packages?name=docker-*-completion&branch=v3.8

**Comment by niusmallnan** [comment]
Add it to milestone v1.5.1.
We don't want the default console to be too complicated.
For other consoles, I think we can add it.

**Comment by niusmallnan** [comment]
It seems that integrating bash completion for Docker is very complicated for ROS, because ROS can switch user-docker and each docker has its own completion files.

Maybe we can only tell the user how to do it in the documentation.

Do you have any ideas? @olljanat

**Comment by niusmallnan** [comment]
Supported consoles:
- alpine
- centos
- debian
- fedora
- ubuntu

Supported engines:
- docker-18.06.0
- docker-18.06.0_arm
- docker-18.06.1
- docker-18.06.1_arm

For the default console, it's a bit complicated to enable `bash-completion`. We want the default console to keep simple, therefore, the default console is not currently supported.

**Comment by kingsd041** [comment]
@olljanat We have supported Docker Bash completion in other consoles in the rancheros v1.5.1-rc1 version.
