### ISSUE TITLE
No zfs in 0.7.0

### ISSUE THREAD

**Issue by stefanfritsch** [rancher/os#1346]
Hi,

I just installed v0.7.0 on a baremetal machine and it doesn't seem like the zfs module still exists.

/lib/modules/4.4.21-rancher/build contains a zfs directory but there's nothing in there but a bunch of Makefiles. In build/fs/ there is nothing.

Is that a known issue? Is it mentioned somewhere because I can't find anything in the docs.

Regards,
Stefan

**Comment by deniseschannon** [comment]
Did you follow the docs about ZFS?

**Comment by stefanfritsch** [comment]
Yes (or more accurately: I think so :)

At least /lib/modules/$(uname -r)/build exists as mentioned here:
http://docs.rancher.com/os/configuration/kernel-modules-kernel-headers/

There is a whole lot of modules in there just no zfs.

**Comment by joshwget** [comment]
I'm unable to reproduce this with v0.7.0 using these steps.

1. Switch to Ubuntu console
2. Install kernel-headers
3. Install zfs package

@stefanfritsch Is it possible that you accidentally performed steps 2 and 3 in reverse order?

**Comment by stefanfritsch** [comment]
Hi,

sorry this took so long, I hadn't the opportunity to try rancheros again since the last time and now it works.

joshwget you're most likely right, so I'll close the issue. 

Thanks for your help
Stefan
