### ISSUE TITLE
OS unable to contact registry, DNS issue?

### ISSUE THREAD

**Issue by wyaeld** [rancher/os#1354]
**RancherOS Version: (ros os version)**
0.7.0
**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
AWS, ap-southeast-2 using official AMI `ami-cd5568ae`

```
[rancher@ip-172-16-1-249 ~]$ sudo docker run -d --restart=always -p 8080:8080 rancher/server
Unable to find image 'rancher/server:latest' locally
Pulling repository docker.io/rancher/server
docker: Get https://registry-1.docker.io/v1/repositories/rancher/server/tags/latest: dial tcp: lookup registry-1.docker.io on 172.16.0.2:53: no such host.
See 'docker run --help'.
```

Have tried on 2 different VPCs, its not an issue with AWS networking, ping and wget are working fine

**Comment by deniseschannon** [comment]
Are you able to pull other docker images?

**Comment by wyaeld** [comment]
apparently I can now pull everything, 30 mins later.

Maybe close as a temp issue, I didn't change anything, and the issue was
happening for over an hour, but its not any more.

**Comment by deniseschannon** [comment]
Ok. let me know if you face other issues. I'll close for now.
