### ISSUE TITLE
docker engine v1.12.3?

### ISSUE THREAD

**Issue by adaphi** [rancher/os#1359]
**RancherOS Version: (ros os version)**
v0.7.0

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
AWS

Hello,
Would it be possible/is there a plan to make docker v1.12.3 available as an engine option? It has several fixes over 1.12.1 that we'd like to make use of.

**Comment by joshwget** [comment]
It'll be the default in v0.8.0 unless another version comes out before then. We can probably add to v0.7.0 as well.

**Comment by stuart-c** [comment]
Now there is the capability to choose & change engine versions easily via the ros engine command & cloud config file it would be great if the available list can track whatever is released upstream (for both x64 & arm) rather than having to wait for specific full rancher releases.

**Comment by joshwget** [comment]
There's still a bit of process between the Docker binaries being released and packaging them as RancherOS services. I'm pretty sure this process could be fully automated, however.

It's also a pretty straightforward process for users to package their own binaries, although we don't have any documentation for this feature yet unfortunately.

The bigger issue with ARM is that there aren't official Docker releases for it yet.

**Comment by stuart-c** [comment]
If there are any clues on how to do it ourselves in the meantime that would be good :-)

Looks like the dev version of 1.13 is available for arm (https://master.dockerproject.org/linux/arm/docker) so fingers crossed that will continue for newer versions too...

**Comment by joshwget** [comment]
Engines images are just a `FROM scratch` image with the binaries in a folder called `/engine`. Once the image is built you can use one of the existing service templates (https://github.com/rancher/os-services/blob/master/d/docker-1.12.1.yml) as a reference and just change the image.

**Comment by stuart-c** [comment]
That's great thanks!

How would you then choose which engine to use? Would you just include the service template in your cloud-init and if so what would you put in the engine: section?

**Comment by SvenDowideit** [comment]
working on it
- https://github.com/rancher/os-engines/pull/3
- https://github.com/rancher/os-services/pull/52

**Comment by SvenDowideit** [comment]
@stuart-c the way I'd do it, is to make my own os-services repo and add that to my RancherOS - see https://roastlink.github.io/

I'll work on some docs later today too

**Comment by SvenDowideit** [comment]
Ok, I've merged @alex-berger's PRs, so docker 1.12.3 should be available on `amd64`. I'm going to try to get my ARM infrastructure set up over the weekend, and then we should start getting that up to date too.

I still need to write some docs before i can close this issue :)

**Comment by joshwget** [comment]
Docker v1.12.3 is the default for v0.7.1.

**Comment by joshwget** [comment]
@stuart-c Added some docs in #1497. This should hopefully be clearer if you haven't already figured out the process.
