### ISSUE TITLE
system-docker network container: add iptables

### ISSUE THREAD

**Issue by camrossi** [rancher/os#1362]
**RancherOS Version: 0.7.0**

**Where are you running RancherOS? BareMetal

As per https://github.com/rancher/os/issues/446 it should be possible to configure iptables at start up trough the network container. 
However it seems only the console contains the iptables executable.

iptables should be added to the network container. 

Thanks

**Comment by joshwget** [comment]
@SvenDowideit I think we need to add `iptables` to the base image. We currently [bind mount it into the console from the host](https://github.com/rancher/os/blob/master/os-config.tpl.yml#L158). I'm assuming it's done this way to save space, but I don't think it's a good idea to have a special case for just this one binary. It's not that big anyways.

**Comment by SvenDowideit** [comment]
I'd rather go the other way - but we'll see

**Comment by joshwget** [comment]
What other way? I'm not sure what you mean.

**Comment by SvenDowideit** [comment]
have less in the base image, and compose things together.

**Comment by joshwget** [comment]
I'd mostly prefer that too, but it's not possible with buildroot. We can revisit it in more depth after #1478 is merged.

**Comment by SvenDowideit** [comment]
this was added in v0.9.0 by #1669
