### ISSUE TITLE
Switch engine to docker-1.10.3  report error

### ISSUE THREAD

**Issue by niusmallnan** [rancher/os#1375]
**RancherOS Version: v0.7.0**

**I am running RancherOS on raspberrypi**

I want to switch docker engine verison to 1.10.3.

```
[rancher@rancher ~]$ sudo ros engine list
disabled docker-1.10.3
current  docker-1.11.2
disabled docker-1.12.1

[rancher@rancher ~]$ sudo ros engine enable docker-1.10.3
Pulling docker (rancher/os-docker:1.10.3_arm)...
Pulling repository docker.io/rancher/os-docker
&{%!s(*os.file=&{2 /dev/stderr <nil>})}ERRO[0009] Failed Pulling docker : Status: Tag 1.10.3_arm not found in repository docker.io/rancher/os-docker, Code: 1
ERRO[0009] Failed to start: docker : Status: Tag 1.10.3_arm not found in repository docker.io/rancher/os-docker, Code: 1
```

Check this url [os-docker-tags](https://hub.docker.com/r/rancher/os-docker/tags/). I can not see rancher/os-docker:1.10.3_arm 

Please add it.

**Comment by niusmallnan** [comment]
I use https://github.com/rancher/os-engines , make the docker-1.10.3_arm image.

Then run:
```
$ sudo system-docker load -i docker-1.10.3_arm.tar
$ sudo ros config set rancher.docker.engine docker-1.10.3
$ sudo reboot
```

**Comment by djmaze** [comment]
@niusmallnan This doesn't work for me. RancherOS falls back to the previous version (ie. the last version which can be seen via `ros engine list`).

This is a pity. It would be really useful to be able to use Docker versions other than those available from the official os/services repository. (E.g. for testing new versions.)

**Comment by joshwget** [comment]
@djmaze There's a bit of info [here](https://github.com/rancher/os/issues/1359#issuecomment-257962986) on how to do this yourself. The process is pretty straightforward, but unfortunately we don't have any documentation on this yet.
