### ISSUE TITLE
ros config export doesn't show Public SSH key from metadata

### ISSUE THREAD

**Issue by cloudnautique** [rancher/os#1378]
**RancherOS Version: (ros os version)**
v0.7.0
**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
AWS

When running `ros config export --full` or `ros config export --private` the SSHPublicKeys are not displayed. These appear to come from the AWS metadata and are written to /var/lib/rancher/conf/metadata. It would be expected that the key is returned with one of the export commands.

**Comment by deniseschannon** [comment]
Verified with v0.8.0-rc4 that running `ros config export --private` shows the AWS key from metadata.
