### ISSUE TITLE
How to turn off hibernate function in rancher OS?

### ISSUE THREAD

**Issue by transifex3** [rancher/os#1388]
**RancherOS Version: (ros os version)**
0.7.1
**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
Laptop

Hi. I am using laptop to run rancher os, and it's pretty good server for me :)
But, i got a problem little bit about hibernate/sleep problem.
If i close my laptop just like this, to turn off just monitor
![studio-shot-of-hand-closing-laptop-136596098-57be06603df78cc16e3cc737](https://cloud.githubusercontent.com/assets/16120391/20246659/d34bf370-a9fe-11e6-91a2-ce4bda210923.jpg)
rancher os is going to be hibernated. and what i want is to turn off this function.
All i need is to turn off mornitor, which is not nessessary for server!
Is there any way to do it? thanks :D

**Comment by ibuildthecloud** [comment]
It's built into the acpid container.  Lid close event will trigger a hibernate.  You can see how this works here https://github.com/rancher/os/blob/master/images/02-acpid/Dockerfile

I would recommend using `write_files` to overwrite suspend.sh with `exit 0` http://docs.rancher.com/os/configuration/write-files/

**Comment by xpressengine3** [comment]
I'll check it out :D
Thank you ibuildthecloud.

**Comment by Albus** [comment]
```sh
sudo ros s stop acpid
sudo ros s rm acpid
```

**Comment by PrplHaz4** [comment]
@Albus stopping and removing the `acpid` service did not work in my case.  When closing the lid, the system went to sleep.

The method I'm using now is to set `acpi=off` in syslinux.  Unfortunately, this does not persist across a rancherOS upgrade (but does persist across reboots).
```
sudo ros config syslinux
acpi=off
```
