### ISSUE TITLE
Setting up Kubernetes: infinite loop start proxy Starting services (7 of 9)

### ISSUE THREAD

**Issue by jujes** [rancher/os#1390]
**SOLVED** I think kubernetes not support yet docker-1.12.1

sudo ros engine switch docker-1.11.2

**RancherOS Version: (ros os version)**
```
Release v0.7.1
md5sum eb58ac4958cf66bb9c2675cd7e565419
```

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
`docker-machine >> virtualbox`

**Proxy and  don't start... Unhealthy**
![kube_issue](https://cloud.githubusercontent.com/assets/2881017/20260780/70705da6-aa5b-11e6-934f-ac26757a1f9c.png)

**Comment by joshwget** [comment]
Sounds like switching Docker versions resolved the issue - is this safe to close then?

**Comment by joshwget** [comment]
@jujes Please open a new issue if you're still experiencing this.
