### ISSUE TITLE
Can we do full-disk-encryption installation in Rancher OS?

### ISSUE THREAD

**Issue by transifex3** [rancher/os#1392]
**RancherOS Version: (ros os version)**
0.7.1
**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
Laptop

I googled about this and found some guys mentioned full disk encryption, and this would be added in future, but unfortunately no progress on that time.
I guess still there is no option for encrypted installation in this moment.
Any chances to get this feature soon? :)
Thanks.

**Comment by SvenDowideit** [comment]
its not currently on our roadmap - though @tetatetit made https://github.com/rancher/os-base/pull/39 a while ago.
