### ISSUE TITLE
/var/lib/rancher/conf/user-config.yml is world readable

### ISSUE THREAD

**Issue by ibuildthecloud** [rancher/os#1393]
`/var/lib/rancher/conf/user-config.yml ` really only needs to be readable by root.

**Comment by SvenDowideit** [comment]
pushing to 0.9 - I don't want to re-test everything this late into the release cycle.

**Comment by SvenDowideit** [comment]
see #1684

**Comment by deniseschannon** [comment]
Verified in v0.9.0-rc1 that all files in `/var/lib/rancher/conf` are only readable by root.
