### ISSUE TITLE
Rollback system-docker to 1.10.3

### ISSUE THREAD

**Issue by ibuildthecloud** [rancher/os#1394]
For RancherOS 1.0 we should drop the custom system-docker we have now and rollback to Docker 1.10.3 as we develop a new replacement for system-docker that can be lighter weight.

**Comment by faddat** [comment]
Excellent.  My hope for the lighter-weight thing is that it updates itself and the containers it runs by default without the user taking  any action.  Action should be required only to DISABLE the update feature.

**Comment by ibuildthecloud** [comment]
The new thing we allow updates without impacting containers or a reboot.  Look forward to "new thing" :)
