### ISSUE TITLE
Partition resizing not finished

### ISSUE THREAD

**Issue by jdel** [rancher/os#1396]
**RancherOS Version: (ros os version)**
Ros 0.4.5

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
Virtual machines in vCloud

I am trying to resize a partition on one of my ROS machine. First, I followed the documentation and added ```yml
#cloud-config
rancher:
  resize_device: /dev/sdb```
To my cloud-config, rebooted, but nothing happened.

I then followed workaround in #1237 and added
```yml
rancher:
  environment:
    RESIZE_DEV: /dev/sdb
  services_include:
    https://raw.githubusercontent.com/rancher/os-services/v0.4.5/r/resize-fs.yml: true
``` 
To my cloud config instead of `resize_device: /dev/sdb`, and after a reboot it seems to have started doing the job.

```bash
[root@my-server-01 ~]# system-docker logs resizefs
+ RESIZE_DEV=/dev/sdb
+ STAMP=/var/log/resizefs.done
+ '[' -e /var/log/resizefs.done ']'
+ '[' -b /dev/sdb ']'
+ growpart /dev/sdb 1
CHANGED: partition=1 start=63 old: size=41929587 end=41929650 new: size=83875302,end=83875365
+ partprobe /dev/sdb
+ resize2fs /dev/sdb1
resize2fs 1.42.9 (4-Feb-2014)
Please run 'e2fsck -f /dev/sdb1' first.

+ RESIZE_DEV=/dev/sdb
+ STAMP=/var/log/resizefs.done
+ '[' -e /var/log/resizefs.done ']'
+ '[' -b /dev/sdb ']'
+ growpart /dev/sdb 1
NOCHANGE: partition 1 is size 83875302. it cannot be grown
+ :
+ partprobe /dev/sdb
+ resize2fs /dev/sdb1
resize2fs 1.42.9 (4-Feb-2014)
Please run 'e2fsck -f /dev/sdb1' first.
```

So on the first reboot, `growpart` actually grew the partition, but resize2fs failed because it wants fsck first. 

The result is my partition being the right size in `fdisk -l`, but the file system is not extended as `df` still reports the old size.

Is there any way I can trigger that fsck before the resize service kicks in ?

**Comment by SvenDowideit** [comment]
handing this to josh for now - he know way more about this than i atm.

**Comment by jdel** [comment]
I managed to work my way around this by running the resize container like this:

```bash
docker run --privileged=true --rm -ti --entrypoint=/bin/bash rancher/os-resizefs:v0.4.5
```

Then executing the following:

```bash
root@7ec6ac2a49be:/# growpart /dev/sdb 1
CHANGED: partition=1 start=63 old: size=41929587 end=41929650 new: size=83875302,end=83875365
root@7ec6ac2a49be:/# partprobe /dev/sdb
root@7ec6ac2a49be:/# e2fsck -f /dev/sdb1
e2fsck 1.42.9 (4-Feb-2014)
Pass 1: Checking inodes, blocks, and sizes
Pass 2: Checking directory structure
Pass 3: Checking directory connectivity
Pass 4: Checking reference counts
Pass 5: Checking group summary information
/dev/sdb1: 4579/1310720 files (14.0% non-contiguous), 4975044/5241198 blocks
root@7ec6ac2a49be:/# resize2fs /dev/sdb1
resize2fs 1.42.9 (4-Feb-2014)
Resizing the filesystem on /dev/sdb1 to 10484412 (4k) blocks.
The filesystem on /dev/sdb1 is now 10484412 blocks long.
root@7ec6ac2a49be:/# exit
```

The problem was `e2fsck -f /dev/sdb1` missing from the original entrypoint before the `resize2fs`
