### ISSUE TITLE
take a long hard look at file ownerships and permissions in the hostfs

### ISSUE THREAD

**Issue by SvenDowideit** [rancher/os#1403]
and add some auditing of them in the build process.

**Comment by SvenDowideit** [comment]
and @joshwget points out there are likely things in it that we don't need anymore

**Comment by joshwget** [comment]
As far as I can tell, modprobe is the only thing we need from BusyBox. We should build a very minimal BusyBox config to only include this. xz is probably safe to remove as well.

Our current approach is to use the docker-from-scratch image (https://github.com/rancher/docker-from-scratch/tree/master/base-image) and strip off what we don't need. I think it makes sense to move away from this and just build an image specifically for the host filesystem.

**Comment by joshwget** [comment]
Looks like we already have a really minimal config (https://github.com/rancher/docker-from-scratch/blob/master/base-image/config/busybox-ps-modprobe-only.config). We just need to remove ps from it.

After these changes BusyBox and iptables will be the only binaries left on the host. It feels like using buildroot just for these two things might be a little overkill.

**Comment by joshwget** [comment]
Definitely thinking a separate repo for the host filesystem is a good idea. docker-from-scratch releases are currently tied to releases of Docker, which isn't ideal https://github.com/rancher/os/blob/master/Dockerfile.dapper#L73.
