### ISSUE TITLE
[looking for guidance] ROS Remote Installer

### ISSUE THREAD

**Issue by faddat** [rancher/os#1418]
**RancherOS Version: (ros os version)**
All

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
remote bare metal at assorted providers

So, as we all know it can be a little bit of a pain to get rancheros running.  I'd like to build a go app that downloads the latest RancherOS image from the releases on Github into the machine's RAM and then writes it to disk complete with configuration. For example:

**Scenario**
Bob has a machine running Ubuntu 16.04 from Bill's Computation Shack.  Bob wants it to run RancherOS, but Bill's Computation Shack doesn't support it and as a legacy computing provider, they don't invest in software innovation, so aside from not being around much longer, we cannot reasonably expect them to support ROS at some later date.  Bob still wants his machine to run ROS.  

So, Bob downloads goros, the remote RancherOS installer.  Bob is fully aware that he is about to delete /, entirely and irrevocably, because the download page says that if used correctly, goros will delete / entirely and irrevocably, and the application itself warns bob, too, unless the flag -y is used (for automation.)  AFAIK, goros would need to:

1) be run as root
2) Read and parse the configuration specified
2) unmount / -- (!?!?-- I don't know how to do this part.  I'm specifically looking for guidance on this point... or is it better to do this in another way?  I've seen similar done here:

3) Format / as a btrfs filesystem (I think I'd do this by building mkfs.btrfs as a binary into the goros executable)
4) Write the filesystem to disk
5) Apply the configuration specified in the parameter
6) reboot the machine

This app's only parameter should be the cloud-config info, which could be hosted, for example, at gist.github.com.  So this app would work a little bit like this:

goros https://gist.github.com/username/thatcrazyhashcodegistgives

so, usage would be like that, and only like that.  Here are the use-cases I envision:

1) Downloading and configuring RancherOS for environments like these:
- Cheap bare metal compute providers
- small deployments where ipxe "isn't worth it" (think: 5-machine cluster at a startup or even at someone's home) 
- raspberry pi

**Comment by SvenDowideit** [comment]
https://github.com/docker/machine has quite alot of the bits we need to achieve this.

IMO the best thing would be to start working with it - adding what you need to it.

**Comment by faddat** [comment]
Thanks very much for the link.  That was fantastically useful.  

OK, now I know what to do :D.

**Comment by nathanleclaire** [comment]
Well, provisioners aren't really pluggable like drivers are.  So it'd need to be inside Machine source code, although I'm not sure to over-write existing OSes with RancherOS really fits in the existing model.
