### ISSUE TITLE
fix `ros s enable kernel-headers` 

### ISSUE THREAD

**Issue by SvenDowideit** [rancher/os#1419]
I've changed the kernel header and extra services to contain the kernel version, in the hope that it'll eventually allow us to decouple the kernel version  from the release version.

for 0.8.0-rc1, this means the user needs to know the right service to install to match what they have installed - but before we release 0.8.0, this needs to be either aliased, or some other mechanism needs to work so that other services can be built to depend on the headers without needing to upgrade your yml file every time the kernel changes.

**Comment by ibuildthecloud** [comment]
Would it be terrible to just hard code in the the `ros service` command that `kernel-headers` means `kernel-headers-$(uname -r)`

**Comment by SvenDowideit** [comment]
y - that might be enough - but i think I need to try to make a zfs service that depends on a kernel-header service to make sure.

**Comment by joshwget** [comment]
+1 for mapping `kernel-headers` -> `kernel-headers-$(uname -r)`. We need the following cloud-config to work for backwards compatibility.

```
#cloud-config
rancher:
  services_include:
    kernel-headers: true
```

**Comment by SvenDowideit** [comment]
https://github.com/rancher/os-services/pull/66 plus a PR here to set the env var to the `uname -r`
