### ISSUE TITLE
Failed to pull the catalog from git repo https://github.com/rancher/community-catalog.git

### ISSUE THREAD

**Issue by smith64fx** [rancher/os#1423]
**RancherOS Version: (ros os version)**
1.7.1

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
GCE

Hey guys,
I just deployed ROS on GCE using this script: https://github.com/rancher/os-packer

I used
```
make release
gsutil cp ./rancheros-${RANCHEROS_VERSION}.tar.gz gs://ros-images/
```
After that I created the image and finally the instance.
Everything worked fine.

But everytime I try to start the rancher
```

```

I get this error
```
049bcd5945e9-docker-machine-driver-packet => /usr/local/bin/docker-machine-driver-packet"
time="2016-11-25T15:42:05Z" level=info msg="Creating schema machine, roles [admin user readAdmin]" id=1ds14
time="2016-11-25T15:42:05Z" level=info msg="Creating schema machine, roles [readonly]" id=1ds15
time="2016-11-25T15:42:05Z" level=info msg="Creating schema packetConfig, roles [service member owner project admin user readAdmin readonly restricted]" id=1ds16
time="2016-11-25T15:42:06Z" level=info msg="Updating machine jsons for  [packet packet amazonec2 azure digitalocean]"
time="2016-11-25T15:42:07Z" level=info msg="Creating schema machine, roles [service]" id=1ds17
time="2016-11-25T15:42:07Z" level=info msg="Creating schema machine, roles [project member owner]" id=1ds18
time="2016-11-25T15:42:07Z" level=info msg="Creating schema machine, roles [admin user readAdmin]" id=1ds19
time="2016-11-25T15:42:08Z" level=info msg="Creating schema machine, roles [readonly]" id=1ds20
time="2016-11-25T15:42:09Z" level=error msg="Failed to pull the catalog from git repo https://github.com/rancher/community-catalog.git, error: exit status 1"
time="2016-11-25T15:42:09Z" level=error msg="Git pull for Catalog community failing with error: exit status 1 "
```

Anyone got some idea?

**Comment by deniseschannon** [comment]
The logs indicate that you do't have internet access. Can you access the internet from your instance?

**Comment by smith64fx** [comment]
hey,
thanks for your answer.

I have internet access from the docker instance.
I can even do "git clone https://github.com/rancher/community-catalog.git" and it works.

I have no idea what's the reason for this... really frustrating :(

**Comment by vincent99** [comment]
The catalog service literally shells out and executes `git clone $url` (not exactly that, but logically the same) just like you would.  Did you try it from *inside* the server container (`docker exec -it <id of rancher/server container> bash`)?

The catalog wouldn't affect the loading of the UI, what's in the browser dev tools console?

**Comment by smith64fx** [comment]
what the hell!

after i started the engine now (terminate and start) everything works :)

thanks anyway @vincent99 and @deniseschannon 

I love <3 a fast helping community like this :)
