### ISSUE TITLE
Allow login from arbitrary openid connect providers

### ISSUE THREAD

**Issue by fire** [rancher/os#1426]
**RancherOS Version: (ros os version)**
any
**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
local machine
Examples:

* Google Apps
* Keycloak

**Comment by joshwget** [comment]
Can you describe what you're expecting a bit more? I don't think any other operating systems offer functionality like this.

**Comment by SvenDowideit** [comment]
If you're wanting what I think you are, then this is something that should be able to be done using a custom console, configured with the needed PAM modules.

**Comment by fire** [comment]
Well the admin interface allows login from github. I use google apps and fundamentally supporting github is the same as google apps.

**Comment by fire** [comment]
![screenshot-192 168 1 78 8080-2016-11-27-17-08-56](https://cloud.githubusercontent.com/assets/32321/20653564/478ee4a2-b4c4-11e6-993b-f25a7cef95fe.png)

**Comment by fire** [comment]
Both keycloak and google apps are openid connect providers. It would be cool to see support for any openid provider. (I can imagine facebook etc.)

**Comment by deniseschannon** [comment]
So your screenshot has to do with Rancher and not RancherOS. 

Can you open your request under that project? Note: Google sign ins already has an enhancement request. 
https://github.com/rancher/rancher/issues/1411

**Comment by deniseschannon** [comment]
Also, with Rancher 1.2, we've created our authentication service into it's own go-microservice so anyone could implement their own ability to create auth using other providers from what Rancher provides.
