### ISSUE TITLE
Add VirtualBox tools support 

### ISSUE THREAD

**Issue by wlan0** [rancher/os#143]
https://www.virtualbox.org/manual/ch04.html

**Comment by miztiik** [comment]
I second this, I would really like built in support for VirtualBox Tools

**Comment by ibuildthecloud** [comment]
This request has been coming more and more.  Especially since RancherOS works in docker-machine and people expect folder sharing to work like b2d.  We are in the process of releasing v0.4 now and we can't squeeze in this feature.  But it think we can get it in the next release.

**Comment by miztiik** [comment]
Thanks for the update, 

I am seriously considering this platform to host some of my applications, so would like to know what is the expected time frame. I have been researching rancher os only recently so not sure about your release cycles, Can you please tell us about your release cycle, When would be the _next release 'tentatively'_

**Comment by ibuildthecloud** [comment]
We don't have a fixed release cycle yet.  We should create one soon, but releases have been pretty ad hoc right now .  V0.4 should be released by the 26th.  The vbox support I won't expect until 4 weeks after that.  After v0.4 you should expect a monthly release.  We'd like to get that shorter but we've found testing all the permutations of clouds and baremetal to be pretty time consuming.

**Comment by philipz** [comment]
I used docker-machine to create RancherOS on VMware vShpere was timeout. And by docker-machine just create a VM, it didn't run `ros install -d /dev/sda` automatic. So, I couldn't use docker-machine to ssh this VM.
https://gist.github.com/philipz/2eb126f6c68568a1ef57
http://docs.rancher.com/os/running-rancheros/workstation/docker-machine/
http://docs.rancher.com/os/running-rancheros/server/install-to-disk/

**Comment by ivotron** [comment]
Any update on this? It'd be awesome to have shared folders so one can replace b2d with rancher

**Comment by deniseschannon** [comment]
@ivotron We are hoping to get this in the next 1 or 2 releases.

**Comment by deniseschannon** [comment]
Broken in v0.4.4-rc2 due to kernel bump. @joshwget to fix for v0.4.4-rc3

**Comment by flyingbuddha** [comment]
I'm also interested in this. Can someone tell us what the workaround is until the feature is implemented?

I was talking the problem through with a friend who suggested a NFS share from OS X that's mounted from RancherOS. Does that seem the most sensible approach?

**Comment by zot24** [comment]
Have being a while since the last time this thread was update (we are now on RancherOS 0.7.1) I was wondering if there is any news or have anyone manage to make RancherOS works properly with VirtualBox and share local folders?

**Comment by xinity** [comment]
tried with rancherOS LTS, nothing comes up :(
That's a pity as i wished for replacing boot2docker with RancherOS.

Please do something for us rancherOS fans !!!

**Comment by niusmallnan** [comment]
@kingsd041 we need to do something like this: https://github.com/boot2docker/boot2docker/blob/master/Dockerfile#L362-L380
May need to introduce it through os-services.

**Comment by kingsd041** [comment]
We have supported VirtualBox tools in the RancherOS v1.5.1-rc1 version.


## How to use

First, you need to start the `virtualbox-tools` service in rancheros.

```
sudo ros service enable virtualbox-tools
sudo ros service up virtualbox-tools
```
> Note: if you switch consoles, you may need to re-run `ros service restart virtualbox-tools`.

After the `virtualbox-tools` service starts, it will automatically load the vbox module and start the `VBoxService` process.

```
lsmod | grep -i vbox
vboxsf                 49152  0
vboxguest             258048  2 vboxsf

ps -ef | grep VBoxService
root      1898     1  0 09:12 ?        00:00:00 [VBoxService] <defunct>
root      1900     1  0 09:12 ?        00:00:00 /sbin/VBoxService --disable-automount
```
At this point, you can mount the shared folder with `mount.vboxsf test /mnt`. If you want to mount it automatically, you can also do the following:

```
#cloud-config
write_files:
  - path: /etc/rc.local
    permissions: "0755"
    owner: root
    content: |
      #!/bin/bash
      for _ in {1..10}
      do
          if [ -f /sbin/mount.vboxsf ];then
              mount.vboxsf ansible /mnt/ansible
              break
          else
              sleep 1
          fi
      done
```


**Note:**
1. We do not support the auto-mount feature of shared folders.
2. Using `mount.vboxsf` in the alpine console is not yet supported.
