### ISSUE TITLE
redo rancher.environment to globally set shell ENV

### ISSUE THREAD

**Issue by SvenDowideit** [rancher/os#1437]
follow-on for #1435.

- [ ] caching of immutable values like KERNEL_VERSION
- [ ] export rancher.environment values to all engines and services - so we are able to get HTTP_PROXY working globally (think about certs)
- [ ] docs.

**Comment by joshwget** [comment]
Do you mean `rancher.env` in addition to `rancher.environment`? Or were you just shortening it?

**Comment by SvenDowideit** [comment]
yes, just lazy typing, sorry.
