### ISSUE TITLE
RancherOS Kernel and kernel-headers* do not have matching versions

### ISSUE THREAD

**Issue by killerspaz** [rancher/os#1463]
**RancherOS Version: (ros os version)**
Rancher v0.7.1

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
VirtualBox

The environment is telling me that the kernel version is 4.4.24:

```
rancher@spaz_rancher:~$ uname -a
Linux spaz_rancher 4.4.24-rancher #1 SMP Fri Nov 11 03:20:22 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

The source version of `kernel-headers-system-docker` (as well as `kernel-headers`) are 4.4.0-47.68:

```
rancher@spaz_rancher:~$ ls -la /lib/modules/4.4.24-rancher/build
lrwxrwxrwx 1 root root 36 Nov 11 04:35 /lib/modules/4.4.24-rancher/build -> /usr/src/Ubuntu-4.4.0-47.68-rancher1
```

I believe, because of these version mismatches, I'm unable to properly compile any kernel modules needed for our deployment.

Any ideas?

----

Looks like there is a compose file (or something very similar) that constructs the docker tag with `KERNEL_VERSION`, but unsure where that's supplied, as it doesn't exist in my env vars.

https://github.com/rancher/os-services/blob/master/k/kernel-headers-system-docker.yml

**Comment by SvenDowideit** [comment]
The different release names are an artifact of how Ubuntu names their packages - but yes, `4.4.0-47.68` _is_ `4.4.24`

can you post your compile issues?

**Comment by killerspaz** [comment]
That's what I was thinking, but wasn't sure. After a bit of retries I gave up for the day.

Attempting to get `v4l2loopback` dkms module inserted...

As for compile issues, there aren't any errors other than a typical message about being in a chroot env, which should be fine; however when trying to `modprobe v4l2loopback` we get:

```
[ 3513.426268] v4l2loopback: Unknown symbol video_ioctl2 (err 0)
[ 3513.427093] v4l2loopback: Unknown symbol v4l2_ctrl_handler_init_class (err 0)
[ 3513.427950] v4l2loopback: Unknown symbol video_devdata (err 0)
[ 3513.428724] v4l2loopback: Unknown symbol v4l2_ctrl_new_custom (err 0)
[ 3513.429493] v4l2loopback: Unknown symbol video_unregister_device (err 0)
[ 3513.430134] v4l2loopback: Unknown symbol video_device_alloc (err 0)
[ 3513.440749] v4l2loopback: Unknown symbol v4l2_device_register (err 0)
[ 3513.441482] v4l2loopback: Unknown symbol __video_register_device (err 0)
[ 3513.442267] v4l2loopback: Unknown symbol v4l2_ctrl_handler_free (err 0)
[ 3513.442997] v4l2loopback: Unknown symbol v4l2_device_unregister (err 0)
[ 3513.444643] v4l2loopback: Unknown symbol video_device_release (err 0)
[ 3603.744411] v4l2loopback: Unknown symbol video_ioctl2 (err 0)
```

From my findings, these symbols originate from `videodev` kernel module which includes `v4l2-core`; which `/proc/config.gz` indicates IS set as a module, but nowhere on disk.

When my teammate and I started digging in deeper, we started noticing version-label mismatches which threw us down this path of thinking that could be part of the issue.

Do you happen to have any suggestions on where to start looking at this point? We're about to build our own kernel, but not a fan of the idea of having to fork the entire OS just to do so. Ideally we could just insert some modules at boot and be done with it.

**Comment by killerspaz** [comment]
Another quick question:

When I enable and bring up `kernel-headers-system-docker` the logs of the container indicate:
```
rancher@spaz_rancher:~$ sudo ros s enable kernel-headers-system-docker
Pulling kernel-headers-system-docker (rancher/os-headers:v0.7.1)...
v0.7.1: Pulling from rancher/os-headers

aa070c069533: Pull complete
869be5059c14: Pull complete
d0e01177a301: Pull complete
50338d1be6d6: Pull complete
9ef8c45e8975: Pull complete
7b90696d3bc3: Pull complete
370f3dc7e78b: Pull complete
Digest: sha256:2ffb32cc51936ae048eed92f0ecddfba396749d5e8d669fef045df2a2df52690
Status: Downloaded newer image for rancher/os-headers:v0.7.1

rancher@spaz_rancher:~$ sudo ros s up -d kernel-headers-system-docker
INFO[0000] Project [os]: Starting project
INFO[0000] [0/20] [kernel-headers-system-docker]: Starting
INFO[0005] [1/20] [kernel-headers-system-docker]: Started
INFO[0005] Project [os]: Project started

rancher@spaz_rancher:~$ sudo system-docker logs kernel-headers-system-docker
Downloading https://github.com/rancher/os-kernel/releases/download/Ubuntu-4.4.0-47.68-rancher1/build.tar.gz
Connecting to github.com (192.30.253.113:443)
Connecting to github-cloud.s3.amazonaws.com (52.216.64.128:443)
-                      4% |*                              |   628k  0:00:22 ETA
-                     21% |******                         |  3161k  0:00:07 ETA
-                     49% |***************                |  7241k  0:00:03 ETA
-                     88% |***************************    | 12835k  0:00:00 ETA
-                    100% |*******************************| 14521k  0:00:00 ETA

Headers installed at /usr/src/Ubuntu-4.4.0-47.68-rancher1

rancher@spaz_rancher:~$ ls  /usr/src/ -la
total 8
drwxr-xr-x 2 root root 4096 Apr 12  2016 .
drwxr-xr-x 1 root root 4096 Oct  3 18:09 ..
```

But as you can see, `/usr/src` is an empty folder, certainly doesn't contain `Ubuntu-4.4.0-47.68-rancher1`

The output of `kernel-headers` service is nearly identical, but DOES place files.

Why exactly would we utilize one over the other?

The docs indicate
> [...] the only reason for different services is due to the fact that the storage places for System Docker and Docker are different. [...]

This is extremely ambiguous as to what that even means, and more ambiguous as to where these storage places are. I haven't seen any decent documentation indicating proper differences between the two daemons other than "system starts first and stores somewhere else."

**Comment by killerspaz** [comment]
Sorry for spamming, just really trying to get to the bottom of this....

After compiling my module within a container mounting volumes with the following:
`-v /usr/src:/usr/src -v /lib/modules:/lib/modules -v /usr/bin/ros:/usr/bin/ros`

INSIDE the same container, I see:
```
root@765171d62c3b:/# modprobe v4l2loopback
modprobe: ERROR: could not insert 'v4l2loopback': Operation not permitted
```

In the RancherOS host, I see:
```
rancher@spaz_rancher:~$ sudo modprobe v4l2loopback
modprobe: ERROR: could not insert 'v4l2loopback': Unknown symbol in module, or unknown parameter (see dmesg)
```

Which the OP error list of symbols is the same.

The docs only indicate how to compile, but never how to insert; presumably it wouldn't matter where since the modules are mounted, but I could see the kernel being inaccessible from chroot'd environments.

Anyway, still trying to make sense of all of this :S

**Comment by killerspaz** [comment]
Feeling super stupid right now.... Turns out the solution was to enable the `kernel-extras` service.

After reading every piece of documentation twice (literally every line), it finally registered with me in the [Custom Kernel](https://docs.rancher.com/os/configuration/custom-kernels/) section it states:

> `extra.tar.gz` contains extra modules and firmware for your kernel and should be built into a kernel-extras service

Seems better docs are on the horizon? https://github.com/rancher/os/issues/1352

**Comment by SvenDowideit** [comment]
wow, yes, if there's any chance you could make a PR to the docs (in this repo) that would be awesome!

I've got to look at doing the zfs service in the next days - as soon as the installer PR is 'ok'

**Comment by killerspaz** [comment]
I'll take a look at it, hopefully soon-ish.

Would you prefer to see something related to the DKMS docs or more elaboration within the Custom Kernel docs?

**Comment by SvenDowideit** [comment]
I'd prefer something that you might have found useful when you were looking :) at some point, it becomes harder to remember where you'd have looked when you were starting

**Comment by killerspaz** [comment]
Got it. Will do!

Might merge DKMS and modprobe info with some elaboration around all of it.

**Comment by killerspaz** [comment]
PR submitted, let me know if there's any criticisms.
