### ISSUE TITLE
Add AMI in the London AWS region

### ISSUE THREAD

**Issue by dayglo** [rancher/os#1466]
Cor blimey guvnor! The eu-west-2 region is now available.

Please could you add the AMI, me old china?

**Comment by SvenDowideit** [comment]
will do in a few hours old chap.

**Comment by SvenDowideit** [comment]
The new AMI IDs are `ami-7ceae018` and `ami-65e8e201`.

should be public soon

**Comment by dayglo** [comment]
awesome thanks!
