### ISSUE TITLE
Default Password - v0.8.0-rc2

### ISSUE THREAD

**Issue by wahmedswl** [rancher/os#1467]
**RancherOS Version: (ros os version)**
Rancher-v0.8.0-rc2
**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
Hyper-V

Hi,
   I have installed RancherOS to disk and now i cannot login to RancherOS. I have created minimal cloud-config without SSH as i was previously able to login to RancherOS with user = rancher and empty password in v0.7.1. But, now i am not able to, please provider default password. I have tried rancher/rancher.

Thanks

**Comment by rfranke** [comment]
A default password is bad (see #1453). You should add an SSH key to cloud-config.yml. You might create a key pair using PuTTY ... 

Alternatively install DockerToolbox -- start the installer from the command line with

     DockerToolbox-<version>.exe /COMPONENTS="Docker,DockerMachine"

to disable installation of VirtualBox when using Hyper-V. The command

     docker-machine create --driver hyperv --hyperv-boot2docker-url https://releases.rancher.com/os/latest/rancheros.iso <MACHINE-NAME>

will create a key pair for you (`~/.docker/machine/machines/<MACHINE-NAME>/`). The creation hangs after booting the machine, but the machine is up and running. You can insert the public key into your cloud-config.yml and continue on the Hyper-V console.

**Comment by killerspaz** [comment]
For the time being, it appears you can supply `rancher.password` in the cloud-config.

You can find the info tucked away here: https://docs.rancher.com/os/system-services/built-in-system-services/#console

**Comment by SvenDowideit** [comment]
I've gotten into the habit of using `ros install -d /dev/sda --append "rancher.password=mySecret"` on my local VM's - but at some point soon I'd like to see `ros install -d /dev/sda -c https://roast.link/cloud-config.yml` work.

**Comment by wahmedswl** [comment]
@SvenDowideit Thanks, this worked.

**Comment by pwFoo** [comment]
@deniseschannon @SvenDowideit 
Should be added to installation section of documentation.
```
ros install -d /dev/sda --append "rancher.password=mySecret"
```

Will rancher.password work inside of cloud-config.yml too?

**Comment by TheAifam5** [comment]
Actually "rancher.password" you can find here: https://docs.rancher.com/os/system-services/built-in-system-services/

**Comment by SvenDowideit** [comment]
@pwFoo yes, but we're thinking very strongly of removing it in future - #1563

**Comment by Magiccamera** [comment]
It's unruly. There has to be a slight relaxation of the security until end user can make the changes on new install. I followed verbatim and my keys are not accepted. Documentation is poor.
