### ISSUE TITLE
[Q] Difference between kernel-headers and kernel-headers-system-docker?

### ISSUE THREAD

**Issue by killerspaz** [rancher/os#1468]
**RancherOS Version: (ros os version)**
v0.7.1

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
VirtualBox 5.x

Ok, related to my [erroneous evaluation of the kernel eco system](https://github.com/rancher/os/issues/1463) in relation to Rancher, I'm having a hard time distinguishing the difference between these two packages.

Docs indicate ambiguous and obvious:

> [...] the only reason for different services is due to the fact that the storage places for System Docker and Docker are different. [...]

But HOW are they different? Shouldn't the volume mounts take care of any needs since we're practically only dealing with filesystem overlays?

Also, it appears `kernel-headers-system-docker` does not actually supply the headers as it indicates.

More info here: https://github.com/rancher/os/issues/1463#issuecomment-267386384

**Comment by SvenDowideit** [comment]
at this point, we're seeing the 2 as historical, and would remove the system one. I don't know why one works differently to the other - as they both use the same image and yaml, but that's something to investigate (wanna make a PR?)

**Comment by killerspaz** [comment]
I need to investigate more building my own RancherOS image; I'd love to help where I can, but time is limited :D

I am also trying to get my team to document their findings better for contribution.

We're discussing completely customizing our kernel to include everything in it rather than modules; so that might come sooner than later.

Also, I want to take a look at supplying a kernel through config that's post-build; doing a custom build just for a kernel isn't ideal imo.

**Comment by SvenDowideit** [comment]
We should talk before you get too far into it - we're re-doing much of how the kernel and packaging works in the next months

**Comment by killerspaz** [comment]
I'm down to talk; right now we're sufficing with compiling modules against the kernel headers but we will need to swap kernels frequently for testing in the near future.

I looked around quickly but couldn't find the init or grub settings (or /boot partition) to update grub for a new kernel, but I didn't really dig deep.

**Comment by SvenDowideit** [comment]
yeah - 0.8.0 we're ditching grub and using syslinux so that should make that end easier too

**Comment by SvenDowideit** [comment]
turns out there's a really good reason to only use system-docker for these - otherwise its hard to bring back your zfs user-docker ... so https://github.com/rancher/os-services/pull/94

**Comment by SvenDowideit** [comment]
bizzarely, if i may any comment in an issue i'm assigned to, but didn't create, GH unassigns me.
