### ISSUE TITLE
rancherctl os list only shows available versions, should show current version as well

### ISSUE THREAD

**Issue by deniseschannon** [rancher/os#147]
v0.2.1

When running `rancherctl os list`, I only get a list of versions and remote/local.

``` bash
$ sudo rancherctl os list
rancher/os:v0.1.2 remote
rancher/os:v0.2.0-rc1 remote
rancher/os:v0.2.0-rc2 remote
rancher/os:v0.2.0-rc3 remote
rancher/os:v0.2.0 local
rancher/os:v0.2.1 remote
rancher/os:v0.3.0-rc1 remote
```

The external file that it's pulling from shows:

```

---
available:
  - rancher/os:v0.1.2
  - rancher/os:v0.2.0-rc1
  - rancher/os:v0.2.0-rc2
  - rancher/os:v0.2.0-rc3
  - rancher/os:v0.2.0
  - rancher/os:v0.2.1
  - rancher/os:v0.3.0-rc1
current: rancher/os:v0.2.1
```

Let's have the command show the "available:" text as well as the "current: rancher/os:v0.2.1" text.

As a user, it probably makes sense to order it from most recent version to oldest.

**Comment by deniseschannon** [comment]
Comments from Darren on what it should look like: 


Format

image_name local/remote available/latest/- install/-

available = in the available list in the yml
latest = the current field in yml

= neither available or latest
install = if image_name == cfg.Upgrade.Image + ":" + config.VERSION

= if not installed
pretty format the table.

**Comment by joshwget** [comment]
We keep track of the version (such as `v0.4.4` or `v0.4.5`), but not the original image used to perform the installation. This is pretty useful information though, so we should probably track that as well, maybe in `/etc/os-release`.

**Comment by SvenDowideit** [comment]
it should also be able to indicate if the user is running a custom release, or an rc

```
[root@rancher proc]# more /etc/os-release

NAME="RancherOS"
VERSION=v0.7.0-rc1
ID=rancheros
ID_LIKE=busybox
VERSION_ID=v0.7.0-rc1
PRETTY_NAME="RancherOS v0.7.0-rc1"
HOME_URL=
SUPPORT_URL=
BUG_REPORT_URL=
BUILD_ID=
[root@rancher proc]# ros os list
rancher/os:v0.4.0 remote
rancher/os:v0.4.1 remote
rancher/os:v0.4.2 remote
rancher/os:v0.4.3 remote
rancher/os:v0.4.4 remote
rancher/os:v0.4.5 remote
rancher/os:v0.5.0 remote
rancher/os:v0.6.0 remote
rancher/os:v0.6.1 remote
[root@rancher proc]# 
```

**Comment by SvenDowideit** [comment]
see #1272

**Comment by deniseschannon** [comment]
Verified with v0.8.0-rc4

```
rancher/os:v0.7.1 remote latest 
rancher/os:v0.7.0 remote available 
rancher/os:v0.6.1 remote available 
rancher/os:v0.6.0 remote available 
rancher/os:v0.5.0 remote available 
rancher/os:v0.4.5 remote available 
rancher/os:v0.4.4 remote available 
rancher/os:v0.4.3 remote available 
rancher/os:v0.4.2 remote available 
rancher/os:v0.4.1 remote available 
rancher/os:v0.4.0 remote available 
v0.8.0-rc4 running
```
