### ISSUE TITLE
Release RC's as AMIs

### ISSUE THREAD

**Issue by brettneese** [rancher/os#1480]
It would be nice if the RC's were bundled and uploaded to AWS as part of the release cycle. I'm currently working on building on some automation that relies on #1382, but there's no way to test it easily (since the 
docker options changed from 0.6.1 to 0.7.1.) 

I would actually have no idea how to bundle the ISO/zip into an AMI myself, either, so alternatively documentation on how to roll your own AMI would be nice (though I'm probably overthinking that).

**Comment by joshwget** [comment]
I'm assuming the reason this isn't currently done is the overhead of verifying the AMI for each region. @SvenDowideit is doing some work to automate this process. Once that's done I think it'll be fine to start publishing RCs.

**Comment by SvenDowideit** [comment]
yes, mumble, mumble, more stuff

tbh, the main concern I have is that it'll become easier to install the wrong ami - there are already lots of them

**Comment by brettneese** [comment]
I'm using Terraform to search through them like so: 

![image](https://cloud.githubusercontent.com/assets/504279/21445536/35fb48b6-c86f-11e6-86e1-8cf365dbbba8.png)

![image](https://cloud.githubusercontent.com/assets/504279/21445545/44468642-c86f-11e6-9657-d5c388c47324.png)

Which makes things a bit easier (this searches the appropriate region.) When I get done with this module, I'll be releasing it. 

There's gotta be a nicer way to query the AMI database cross-region on the web than just listing them all out, though.  (And if it doesn't exist someone should build that...)

**Comment by brettneese** [comment]
@SvenDowideit can you update to an RC using "ros os upgrade?" (trying this right now but waiting for instance to spin up)

**Comment by deniseschannon** [comment]
@brettneese Yes, you can upgrade using `ros os upgrade` and just put the `-i rancher/os:v0.8.0-rc2`. That should work. I would recommend that over publishing AMIs for the RCs.

**Comment by SvenDowideit** [comment]
added the `-i` cmdline to the latest rc release note - I'm going to close this issue
