### ISSUE TITLE
localization

### ISSUE THREAD

**Issue by ellerbrock** [rancher/os#1481]
hi rancher team,

thanks for your awesome work!
one thing i miss in the docs is how to set my localization settings (keyboard mapping and timezone).
i couldn't find a cloud-config.yml setting for that.
do i have to write some bash scripts or is there a rancheros way of setting things up?
an example would be awesome.

cheers maik

**Comment by SvenDowideit** [comment]
Yeah - we need someone to figure out what needs to be done , and then document :/

**Comment by checksrc** [comment]
+1 - this would be useful

**Comment by ellerbrock** [comment]
i switched to coreos, so i close the ticket ...

**Comment by n3uz** [comment]
##### 7、RancherOS timezone问题解决

登录RancherOS 服务器		
准备其他linux服务器上的Shanghai时区配置文件，[位于 /usr/share/zoneinfo/Asia/Shanghai]			
拷贝Shanghai到RancherOS的目录 /home/rancher/Shanghai			
再次编辑文件			
vi /var/lib/rancher/conf/cloud-config.d/user_config.yml			
增加软链接，完整配置如下

```
rancher:
  console: centos
runcmd:
- ln -sf /home/rancher/Shanghai /etc/localtime
- hwclock
ssh_authorized_keys:
- ssh-rsa 
.......
```

重启RancherOS，查看时区			
sudo -s		
cat /etc/localtime		
date	

至此时区问题解决
