### ISSUE TITLE
Can't share /tmp between system-docker and docker

### ISSUE THREAD

**Issue by akaspin** [rancher/os#1482]
**RancherOS Version: (ros os version): 0.7.1**

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.): AWS**

I'm stuck with running nomad under system-docker. 

```
$ system-docker run -v /tmp:/tmp ...
```

Nomad uses /tmp for plugin registration. But docker uses `/tmp` from console instead host.
I tried to add `/tmp` to volumes in: user-volumes, docker, console ... no luck. How to expose host `/tmp` to `docker`?

How to reproduce:

```
$ system-docker run -v /tmp:/tmp alpine /bin/sh -c 'echo test > /tmp/from-system-docker'
$ docker run -v /tmp:/tmp alpine /bin/ls /tmp
# no from-system-docker
```

**Comment by ryansch** [comment]
Why are you stuck with nomad under system-docker?

**Comment by akaspin** [comment]
@ryansch Interesting question. Of course I can run nomad under user docker. But I am concerned about the "/tmp problem".

**Comment by ryansch** [comment]
@akaspin But if you run nomad under user docker then you're just using `/tmp` from the console container.  Doesn't that solve your problem?

**Comment by akaspin** [comment]
`/tmp` from console is shared between docker containers. Also after spending a lot of time I can run nomad under docker:

1. Only default console.
1. Add /tmp:/tmp volume in both docker and console.
1. `/tmp` is rwxr-xr-x. This is weird.

**Comment by ryansch** [comment]
Why do you need to mount the host tmp?  For all intents and purposes, the console's tmp _is_ tmp with rancherOS.

**Comment by SvenDowideit** [comment]
yeah, I'm pretty confused why you'd want to do what you say - you only need to persist a `/tmp` for nomad - that `/tmp` doesn't need to be shared with anything else - and it also doesn't need to be system-docker based?

**Comment by SvenDowideit** [comment]
closing - please reopen if you have any updates :)
