### ISSUE TITLE
iPXE doublequotes for rancher.cloud_init.datasources

### ISSUE THREAD

**Issue by kirrmann** [rancher/os#1486]
**RancherOS Version: v0.7.1**

I'm using iPXE in qemu/kvm to boot RancherOS with vmlinuz and initrd as provided in the latest version from https://releases.rancher.com/os/latest/

The [documentation](https://docs.rancher.com/os/running-rancheros/server/pxe/) shows that the doublequotes for rancher.cloud_init.datasources are not needed in v0.7.1, but if I remove them an error is thrown.

![screenshot](https://cloud.githubusercontent.com/assets/55881/21607844/1eb067ce-d1b9-11e6-89f2-df0e816dae6c.png)

**Comment by joshwget** [comment]
Thanks @kirrmann. Now that I see your particular URL I have an idea of what the issue might be. There are likely characters in your URL that have special meaning to YAML (maybe `=` or `?`). If this ends up being the problem then there's a pretty quick fix for it.

In the meantime, using quotes to make YAML ignore those special characters should work fine.

**Comment by deniseschannon** [comment]
@kirrmann Would you be willing to test this with v0.8.0-rc4?

**Comment by kirrmann** [comment]
I have just tested v0.8.0-rc4 and the bug I initially reported is fixed.

**Comment by deniseschannon** [comment]
Thanks @kirrmann!
