### ISSUE TITLE
When bootstrapping through cloud-config on 0.8.0-rc2, custom system services refuse to run

### ISSUE THREAD

**Issue by brettneese** [rancher/os#1488]
When I create a system service, per the docs (https://docs.rancher.com/os/system-services/adding-system-services/) using cloud-config when using Amazon EC2 and Rancher ```v8.0.0-rc2``` the service never seems to get added or ran. 

I am using Terraform to define infrastructure, so my user-data.tmpl file looks like this: 

```
#cloud-config
rancher:
  services:
    nginxapp:
      image: nginx
      restart: always
```

This gets passed into the instance through Terraform, by doing this:

```
data "template_file" "user_data" {
  template = "${file("${path.module}/user-data.tmpl")}"

  vars {
    environment = "${var.environment}"
 }
}

```

and 

```
resource "aws_launch_configuration" "rancher" {
  image_id             = "${data.aws_ami.rancher-os.image_id}"
  instance_type        = "${var.instance_type}"
  security_groups      = ["${aws_security_group.instance.id}"]
  user_data            = "${data.template_file.user_data.rendered}"
  key_name             = "${var.key_name}"
  iam_instance_profile = "${var.iam_instance_profile_id}"

  lifecycle {
    create_before_destroy = true
  }
}
```

AWS parses the user-data correctly, so this probably isn't a Terraform issue:

![image](https://cloud.githubusercontent.com/assets/504279/21618261/ad47e048-d1af-11e6-815a-593e0534e605.png)

But Rancher refuses to run the service:

![image](https://cloud.githubusercontent.com/assets/504279/21618281/c9a909b0-d1af-11e6-8607-e59559008eb3.png)

![image](https://cloud.githubusercontent.com/assets/504279/21618308/e9c7bba6-d1af-11e6-8c86-a0ee5c2c79c0.png)

In fact, it doesn't even get added to the config:

![image](https://cloud.githubusercontent.com/assets/504279/21618349/1ed0e020-d1b0-11e6-83ea-f70a39a9f6b7.png)

What am I doing wrong? I have tried this with several different services and tried to get the config several different ways, no dice -- even tried adding the service manually and exporting the config into my user-data file. I have also tried previous versions of RancherOS, which also failed in the same way.

**Comment by joshwget** [comment]
Can you show the output of `ros config export` and `system-docker logs cloud-init`?

**Comment by brettneese** [comment]
```rancher:
  cloud_init:
    datasources:
    - ec2
  resize_device: /dev/xvda
  state:
    dev: LABEL=RANCHER_STATE
    wait: true
ssh_authorized_keys: []```


```sudo system-docker logs cloud-init
+ MOUNT_POINT=/media/config-2
++ ros dev LABEL=config-2
+ CONFIG_DEV=
+ mkdir -p /media/config-2
+ '[' -e '' ']'
+ mount -t 9p -o trans=virtio,version=9p2000.L config-2 /media/config-2
+ true
+ cloud-init-save -network=true
time="2016-12-23T17:50:07Z" level=info msg="Running cloud-init-save: network=true"
time="2016-12-23T17:50:07Z" level=info msg="Checking availability of \"ec2-metadata-service\"\n"
time="2016-12-23T17:50:07Z" level=info msg="Checking availability of \"ec2-metadata-service\"\n"
time="2016-12-23T17:50:07Z" level=info msg="Checking availability of \"ec2-metadata-service\"\n"
time="2016-12-23T17:50:07Z" level=info msg="Checking availability of \"ec2-metadata-service\"\n"
time="2016-12-23T17:50:07Z" level=info msg="Fetching user-data from datasource ec2-metadata-service"
2016/12/23 17:50:07 Fetching data from http://169.254.169.254/2009-04-04/user-data. Attempt #1
time="2016-12-23T17:50:07Z" level=info msg="Fetching meta-data from datasource of type ec2-metadata-service"
2016/12/23 17:50:07 Fetching data from http://169.254.169.254/2009-04-04/meta-data/public-keys. Attempt #1
2016/12/23 17:50:07 Fetching data from http://169.254.169.254/2009-04-04/meta-data/public-keys/0/openssh-key. Attempt #1
2016/12/23 17:50:07 Found SSH key for "rancheros"
2016/12/23 17:50:07 Fetching data from http://169.254.169.254/2009-04-04/meta-data/hostname. Attempt #1
2016/12/23 17:50:07 Fetching data from http://169.254.169.254/2009-04-04/meta-data/local-ipv4. Attempt #1
2016/12/23 17:50:07 Fetching data from http://169.254.169.254/2009-04-04/meta-data/public-ipv4. Attempt #1
time="2016-12-23T17:50:07Z" level=error msg="Unrecognized user-data\n"
time="2016-12-23T17:50:07Z" level=info msg="Written to /var/lib/rancher/conf/metadata:\nPublicIPv4:\n- 0\n- 0\n- 0\n- 0\n- 0\n- 0\n- 0\n- 0\n- 0\n- 0\n- 255\n- 255\n- 52\n- 15\n- 219\n- 120\nPublicIPv6: []\nPrivateIPv4:\n- 0\n- 0\n- 0\n- 0\n- 0\n- 0\n- 0\n- 0\n- 0\n- 0\n- 255\n- 255\n- 172\n- 31\n- 22\n- 189\nPrivateIPv6: []\nHostname: ip-172-31-22-189.us-east-2.compute.internal\nSSHPublicKeys:\n  rancheros: ssh-rsa REDACTED    rancheros\nNetworkConfig: n```

That "unrecognized user-data" is probably what's doing it, curious as to what it can't recognize though.

**Comment by joshwget** [comment]
Are you sure you're running v0.8.0-rc2? Now that I think about it, there shouldn't be a `cloud-init` service in that version.

**Comment by brettneese** [comment]
![image](https://cloud.githubusercontent.com/assets/504279/21621353/36bb39f2-d1be-11e6-8ebd-331e68e66241.png)

If it makes any difference, I actually upgraded from the 0.7 image and created an AMI from that instance which is how this is running.

**Comment by brettneese** [comment]
So yeah, looking at those logs a bit closer - you're right, they were from before I upgrade that instance to 0.8 (December 23, 2016) and then imaged it (bringing the old logs along for the ride.)

Still would like to know why my cloud-config isn't working, though, and I suspect the cause is similar.

**Comment by joshwget** [comment]
Does the same problem happen if you use v0.7.1? Can you also try putting in your userdata directly instead of going through Terraform?

**Comment by joshwget** [comment]
I was able to use userdata in v0.7.0, upgrade to v0.8.0-rc2, and then still see the userdata. I'm thinking the issue might be relating to Terraform then, though I'm not sure why that would matter.

**Comment by brettneese** [comment]
Using userdata on my v0.8.0-rc2 image manually via the AWS Console didn't work, trying v0.7.1 now...

**Comment by brettneese** [comment]
@joshwget can confirm that adding user-data manually via the AWS console on v0.8.0-rc2 is working, so it has to be somewhere in Terraform. so strange...

i'm using a windows box atm, wondering if it has something to do with line endings somewhere (though all the terraform files have unix line endings). 

i will tinker and report back for future Googlers but closing this because it doesn't seem to be a rancher issue (I sorta thought I just had the syntax wrong somewhere.)

**Comment by brettneese** [comment]
Hmm, running it on a OSX box presents the same error. @joshwget are there any cloud-init logs I can look at in RancherOS 0.8.0-rc2?

**Comment by brettneese** [comment]
Re-opening this. I did extensive work testing this today (using launch configurations via the AWS console manually, using Terraform to define launch configurations, using both Windows and OSX hosts to bootstrap the instance [in case it was a file formatting issue], creating an instance manually outside of a launch configuration, etc etc) and can pinpoint that this is actually an issue in `0.8.0-rc2` (I was wrong above, or there's possibly a race condition somewhere). 

At least it is an issue if you take a 0.7.1 image, upgrade it to 0.8.0-rc2, and base new instances with user-data on that image (user-data that wasn't on the original instance). This kind of blocks me, because I need the fix for #1382. (Though not running in production - working on automation.) 

If it helps, I can share my v0.8.0 image created from upgrading the 0.7.1 instance.

**Comment by SvenDowideit** [comment]
@brettneese what machine type are you using? I'm in the process of trying to track down why m4.large doesn't do cloud-init, while t2.micro does - #1533

**Comment by SvenDowideit** [comment]
@brettneese I've made `rancheros-v0.8.0-rc6-hvm-test-1: ami-31ce9157 with snap-f6a5fe06 in eu-west-1` Public for you to have a quick test with

i don't use terraform, so I'm interested in simplifying the process :)

**Comment by brettneese** [comment]
yo @SvenDowideit, apologies: using m4.larges and just saw your message. will give it a test tonight or tomorrow! 👍

**Comment by brettneese** [comment]
@SvenDowideit can confirm that 0.8.0rc6 AMI works. i'm so glad it wasn't jus me going crazy.  🎉

**Comment by SvenDowideit** [comment]
awesome!
