### ISSUE TITLE
(Non-urgent) Persistent dir location and shell session questions

### ISSUE THREAD

**Issue by m247suppport** [rancher/os#1489]
**RancherOS Version: (ros os version)**
ros version v0.7.1

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
On a Xen Hypervisor

I have not been able to find the relevant documentation yet and I have not been able to figure it on my own, so just a few quick questions:

1. Does the persistent directories (/home, /opt, /var/lib/{docker,rancher}) exist within an fs that is mounted to root fs when the system is booted? If so which one? If not, do the persistent dirs exist within docker data container?

2. When you connect to a remote ros vm using ssh, is the created shell session contained within the console container?

Great OS, thanks for all the work so far and I am looking forward to see how it evolves in the future. 👍

**Comment by joshwget** [comment]
1. Persistent directories are the same folders as on the rootfs. Persistent directories are just Docker bind mounts and these work the same on RancherOS as with other distros.
2. Yes, sshd is run in the console container.

Thanks for the kind words!

**Comment by m247suppport** [comment]
Thanks!
