### ISSUE TITLE
add possibility of using a config-drive for the cloud-init

### ISSUE THREAD

**Issue by strowi** [rancher/os#1501]
Hi,

i think it would be very beneficial, if it was possible to use a config-drive (like with coreos), which mounts the cloud-config.yml to a default location.

E.g.: https://coreos.com/os/docs/latest/config-drive.html

regards,
strowi

**Comment by joshwget** [comment]
RancherOS will currently use a config-drive if it detects it. It should work much in the same way as in the CoreOS docs, though we should really have docs of our own for this.

**Comment by strowi** [comment]
Thx for the answer.
Can you elaborate on how the drive will be detected and how/where it will be mounted?
I tried adding a drive with the mount_tag=config-2 but that didn't work..

**Comment by Klowner** [comment]
I'm also curious how this works. I've built an iso with my `cloud-config.yml` in `/openstack/latest/user_data`. The iso is labeled `config-2`, so `blkid -L config-2` returns `/dev/sr1`, but nothing appears to be mounted or utilized.

Running in kvm/qemu via libvirt.

**Comment by strowi** [comment]
@Klowner : i don't know what changed, but i got it working for my docker-kvm images.. take at the rancher-specific options here https://github.com/strowi/docker-kvm/blob/master/src/docker-entrypoint.sh
