### ISSUE TITLE
Problems getting Docker 1.13 to run

### ISSUE THREAD

**Issue by djmaze** [rancher/os#1513]
**RancherOS Version: v0.7.1**

**Where are you running RancherOS? docker-machine**

Did anyone try getting Docker 1.13 to work on RancherOS (for the user-docker)? I tried building 1.13.0-rc7 analogous to the [1.12.5 PR](https://github.com/rancher/os-services/pull/72), using my [own repository](https://github.com/djmaze/roastlink.github.io/blob/master/index.yml). 

It's not quite working, although the container is running:

```bash
$ sudo system-docker ps | grep docker
5e69e98d27b1        mazzolino/rancher-os-docker:1.13.0-rc7   "/usr/bin/user-docker"   12 days ago         Up 7 hours                              docker
$ docker ps
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.25/containers/json: dial unix /var/run/docker.sock: connect: permission denied
$ ls -l /var/run/docker.sock
-rwx------ 1 root root 0 Jan 15 21:51 /var/run/docker.sock
$ sudo system-docker logs docker
time="2017-01-15T21:51:47Z" level=info msg="Starting Docker in context: console"
time="2017-01-15T21:51:47Z" level=info msg="Getting PID for service: console"
time="2017-01-15T21:51:47Z" level=info msg="console PID 738"
time="2017-01-15T21:51:48Z" level=info msg="[PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin HOSTNAME=rancher-with-docker-1.13 HOME=/root]"
time="2017-01-15T21:51:48Z" level=info msg="Running [docker-runc exec -- 7cbbf984b9e20533ad2996b69b4bcf03ee6d1de50780285425517bca82462532 env PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin HOSTNAME=rancher-with-docker-1.13 HOME=/root docker-init daemon --host unix:///var/run/docker.sock --group docker --debug --log-opt max-file=2 --log-opt max-size=25m]"
```

In `/var/log/docker` I see this error:

```
unknown flag: --storage-driver
See 'docker --help'.

Usage:  docker COMMAND
[...]
```

It seems RancherOS is doing some nifty version dependent stuff in getting user docker to work. Can anyone tell what is going on here? Maybe the core team is already working on 1.13 support?

**Comment by SvenDowideit** [comment]
ah :( no, I've been ignoring 1.13rc - I'll prod it this week while i wait for git bisect to tell me when the dhcp hostname support stopped working :)

**Comment by SvenDowideit** [comment]
I'm seeing something different to what you report - @djmaze can you tell me how you built the `mazzolino/rancher-os-docker:1.13.0-rc7` image?

**Comment by djmaze** [comment]
@SvenDowideit I used the builds from `test.docker.com`, see here: https://github.com/rancher/os-services/compare/master...djmaze:docker-1.13?expand=1

**Comment by SvenDowideit** [comment]
ok, that's pretty much what I did too - but you need to change the `command:` yml file line to be `ros user-docker` - but that's where I've had to stop for now, I'll debug further later

**Comment by SvenDowideit** [comment]
After some mucking around, I deleted the new `completion` dir, and now it works :)

you should be able to try it out with https://github.com/rancher/os/releases/tag/v0.8.0-rc5

**Comment by djmaze** [comment]
@SvenDowideit Works good for me, at least in docker machine. Very fine, thanks!

**Comment by joshwget** [comment]
Ah, I didn't think about the `completion` directory. It might be a good idea for us to make use of it rather than just deleting it in the image.

**Comment by SvenDowideit** [comment]
yup, we will - but I'm not doing to deal with it until 0.8.0 is more sorted. related to #1345
