### ISSUE TITLE
fix log output (to console & installer)

### ISSUE THREAD

**Issue by SvenDowideit** [rancher/os#1522]
this is a cleanup task for 0.8.0

**Comment by SvenDowideit** [comment]
I added 

```
+runcmd:
 +- [ sudo, dmesg, --console-off ]
```
in https://github.com/rancher/os/pull/1524

so once we have a successful boot, we stop spamming the console.

**Comment by joshwget** [comment]
This isn't going to work consistently. The default behavior for arrays to to override the existing value, so if someone specifies their own `runcmd` then it will override this.

**Comment by SvenDowideit** [comment]
moved into respawn in #1545

**Comment by SvenDowideit** [comment]
closing - its better, but there are ugly inconsistencies we will fix before 1.0

please report specific ugly log issues as you see them :)
