### ISSUE TITLE
docker-machine boot fails to provision ssh keys (v0.8.0-rc4)

### ISSUE THREAD

**Issue by ryansch** [rancher/os#1530]
**RancherOS Version: (ros os version)**
v0.8.0-rc4

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
docker-machine

I'm running the following create command:
```
docker-machine create --driver=parallels --parallels-no-share=true --parallels-boot2docker-url=https://github.com/rancher/os/releases/download/v0.8.0-rc4/rancheros.iso test
```

With the following output:
```
Running pre-create checks...
Creating machine...
(test) Downloading /Users/ryansch/.docker/machine/cache/boot2docker.iso from https://github.com/rancher/os/releases/download/v0.8.0-rc4/rancheros.iso...
(test) 0%....10%....20%....30%....40%....50%....60%....70%....80%....90%....100%
(test) Creating SSH key...
(test) Creating Parallels Desktop VM...
(test) Starting Parallels Desktop VM...
(test) Waiting for VM to come online...
Error creating machine: Error in driver during machine creation: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded
```

I can use the Parallels console to gain access to the machine and there aren't ssh keys for the `docker` user (or any user for that matter).

Is there some other place to view the boot log than using the console scrollback buffer?  It's hard to read:
<img width="752" alt="screen shot 2017-01-18 at 3 42 58 pm" src="https://cloud.githubusercontent.com/assets/146013/22087783/d224207a-dd94-11e6-8c5a-bd960a5d9dcb.png">

**Comment by SvenDowideit** [comment]
@ryansch can you try running `dmesg` ? I added some code to spew startup logging to kmsg.

I saw this happen when I made an AWS box with too little memory (but that's an issue I have to leave for later)

**Comment by ryansch** [comment]
`dmesg` is better

Here's the end of the boot log:
<img width="752" alt="screen shot 2017-01-18 at 3 48 42 pm" src="https://cloud.githubusercontent.com/assets/146013/22087917/a3cd58ee-dd95-11e6-8bd2-a0ea765f30ac.png">
<img width="752" alt="screen shot 2017-01-18 at 3 49 28 pm" src="https://cloud.githubusercontent.com/assets/146013/22087928/b551c47e-dd95-11e6-9785-710e019056ec.png">

**Comment by SvenDowideit** [comment]
@joshwget ! there's SELinux in here?!?

**Comment by ryansch** [comment]
@SvenDowideit Managed to get the boot log off of the VM: https://gist.github.com/ryansch/d6069afeb483df84b2bca567529baa03

**Comment by SvenDowideit** [comment]
@ryansch nothing stands out :/ and I don't have paralells atm - can you try again, but with docker-machine debugging turned on? (just want to get as many logs as possible)

**Comment by SvenDowideit** [comment]
Hopfully its not just that RancherOS takes too long to start :/

**Comment by ryansch** [comment]
@SvenDowideit docker-machine create debug log: https://gist.github.com/ryansch/57fae42f389ee3af37a3ad84ed95d70c

**Comment by ryansch** [comment]
In the VM, I get two different ssh errors in `/var/log/messages`:
- `Did not receive identification string from 10.211.55.2 port 59520`
- `Connection closed by 10.211.55.2 port 59521`

The second message repeats with incrementing port numbers.

Comparing this with a working version of RancherOS shows that `/home/docker/.ssh/authorized_keys` is missing in 0.8.0.

**Comment by ryansch** [comment]
The issue must be with `Writing SSH key tar header`.  I'm not sure if it's a RancherOS issue or a docker-machine-parallels issue.

**Comment by ryansch** [comment]
This appears to be where docker-machine is trying to give RancherOS the ssh key: https://github.com/docker/machine/blob/master/libmachine/mcnutils/b2d.go#L487

**Comment by ryansch** [comment]
@SvenDowideit This appears to be where RancherOS tries to deal with the ssh key: https://github.com/rancher/os/blob/master/images/02-bootstrap/auto-format.sh#L31

`/var/lib/rancher/conf/cloud-config.d/machine.yml` does not exist on the 0.8.0 VM but _does_ exist with the ssh keys in my older working VM.

**Comment by SvenDowideit** [comment]
and to confirm - I get the same symptoms using virtualbox:


```
mini:~ sven$ docker-machine create --driver=virtualbox --virtualbox-no-share=true --virtualbox-boot2docker-url=https://github.com/rancher/os/releases/download/v0.8.0-rc4/rancheros.iso test
Running pre-create checks...
(test) Boot2Docker URL was explicitly set to "https://github.com/rancher/os/releases/download/v0.8.0-rc4/rancheros.iso" at create time, so Docker Machine cannot upgrade this machine to the latest version.
Creating machine...
(test) Boot2Docker URL was explicitly set to "https://github.com/rancher/os/releases/download/v0.8.0-rc4/rancheros.iso" at create time, so Docker Machine cannot upgrade this machine to the latest version.
(test) Downloading /Users/sven/.docker/machine/cache/boot2docker.iso from https://github.com/rancher/os/releases/download/v0.8.0-rc4/rancheros.iso...
(test) 0%....10%....20%....30%....40%....50%....60%....70%....80%....90%....100%
(test) Creating VirtualBox VM...
(test) Creating SSH key...
(test) Starting the VM...
(test) Check network to re-create if needed...
(test) Waiting for an IP...
Error creating machine: Error in driver during machine creation: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded
```

**Comment by joshwget** [comment]
@SvenDowideit That could be a different issue (#1475).

**Comment by SvenDowideit** [comment]
your conclusion sounds good - `/dev/sda` hasn't been auto-formated, and still contains the tar payload containing the keys.

**Comment by ryansch** [comment]
I wasn't sure if #1475 was the same issue or not.  It was clear that I was missing the ssh keys whereas that issue just hung after "Waiting for an IP" with no mention of the "Too many retries waiting for SSH" error.

**Comment by SvenDowideit** [comment]
#1535 should go some way to fixing this (It'll be in 0.8.0-rc5 which I'll make this weekend)

turns out there were a number of things that came together to cause it.

**Comment by ryansch** [comment]
Excellent!  I'll give it a whirl after it drops.

**Comment by SvenDowideit** [comment]
https://github.com/rancher/os/releases/tag/v0.8.0-rc5 should resolve this.

**Comment by ryansch** [comment]
I can confirm that rc5 fixes this issue!
