### ISSUE TITLE
Apply sysctl options in ApplyNetworkConfig

### ISSUE THREAD

**Issue by joshwget** [rancher/os#1539]
sysctl settings are applied in the cloud-init-execute service which currently runs after the networking service. Since some sysctl settings are related to networking (https://github.com/rancher/os/issues/908#issuecomment-229939920) we should run cloud-init-execute before network.

**Comment by SvenDowideit** [comment]
This is going to need to be done differently - it should be possible to have these settings in a url / network based cloud-config, and to have them applied - so that also means it needs to be able to be done after the network is up.

In v0.9.0 I changed the cloud-init to always happen after the network is started...

**Comment by SvenDowideit** [comment]
I _think_ that any sysclt options set in the kernel cmdline should be able to be passed to the pre-cloud-config-save ApplyNetworkConfig, and so it should be possible to set them initially, and then refine afterwards from the cloud-init data.

**Comment by robbertkl** [comment]
Can I get those kernel parameters in the bootloader during install somehow? My only concern is turning off `net.ipv6.conf.eth0.autoconf` and `net.ipv6.conf.eth0.accept_ra`, which must be done before the network is initialized.

**Comment by SvenDowideit** [comment]
@robbertkl I _think_ you should be able to do `ros install ... --append "net.ipv6.conf.eth0.autoconf=false net.ipv6.conf.eth0.accept_ra=false"`, but I'm not 100% sure what happens later in the boot process - you might need to duplicate those in the append line with `rancher.network.interfaces.eth0...`

**Comment by robbertkl** [comment]
Just been playing around with this. While it isn't possible to apply sysctls as kernel boot parameters like described, there is a `ipv6.autconf` parameter, which seems to set `net.ipv6.conf.default.autoconf` and then ends up in eth0 as well.

So this does solve my problem! It can be done:
* at install time: `ros install ... --append ipv6.autoconf=0`
* or in an existing system (see http://rancher.com/docs/os/configuration/adding-kernel-parameters/)

@SvenDowideit Is there anything you still want to do for this issue, or shall we just close it?

**Comment by SvenDowideit** [comment]
nice! - yeah, It'd be good to get what you worked out into the docs - adding it to the fire.

**Comment by robbertkl** [comment]
It's pretty much what you told me, which is already nicely documented in http://rancher.com/docs/os/configuration/adding-kernel-parameters/.

Setting _any_ sysctl before the network is initialised (like for example `accept_ra`), however, is not possible.
