### ISSUE TITLE
ros upgrade has messy failure modes

### ISSUE THREAD

**Issue by SvenDowideit** [rancher/os#1552]
the example is from running upgrade on a docker-machine - where the OS is read-only.

it should really detect that, and tell the user that they can't - or tell them how to make it work

```
[root@test docker]# ros os upgrade -f -i rancher/os:v0.8.0-rc6
Upgrading to rancher/os:v0.8.0-rc6
Pulling os-upgrade (rancher/os:v0.8.0-rc6)...
v0.8.0-rc6: Pulling from rancher/os
0a8490d0dfd3: Pull complete
0690e52389de: Pull complete
9d941214f486: Pull complete
2643593d92dc: Pull complete
5ebef577beda: Pull complete
39e6e88df41d: Pull complete
79902cb25aea: Pull complete
a38f53a2be24: Pull complete
0061afe50916: Pull complete
Digest: sha256:70ad3b9cec1594691118364f8896a8ab53fb311b58d06bcb6b39e05ee15751b2
Status: Downloaded newer image for rancher/os:v0.8.0-rc6
os-upgrade_1 | > time="2017-01-26T10:48:31Z" level=warning msg="Cloud-config not provided: you might need to provide cloud-config on bootDir with ssh_authorized_keys"
os-upgrade_1 | Installing from :v0.8.0-rc6
os-upgrade_1 | lsblk: 1: not a block device
os-upgrade_1 | > time="2017-01-26T10:48:31Z" level=error msg="error layDownOS exit status 32"
os-upgrade_1 | > time="2017-01-26T10:48:31Z" level=fatal msg="Failed to run install" err="exit status 32"
> INFO[0086] Rebooting
Connection to 127.0.0.1 closed by remote host.
exit status 255
```

**Comment by joshwget** [comment]
This is definitely a good idea. Causes a lot of confusion for users. Related to #194.

**Comment by prologic** [comment]
I get the same problem as described in this issue too:

```
lk: 1: not a block device
os-upgrade_1 | > time="2017-01-26T10:48:31Z" level=error msg="error layDownOS exit status 32"
os-upgrade_1 | > time="2017-01-26T10:48:31Z" level=fatal msg="Failed to run install" err="exit status 32"
```

I did the stupid thing of not taking a snapshot of the VM **before** upgrading so now I have a broken node :/ I have a backup of the node when it was at v0.4.5 but the upgrade path from **that** version is just as broken with the above failure mode.

**Comment by SvenDowideit** [comment]
@prologic maaaaate :) so you too upgraded a (non-cloud) docker-machine node?

**Comment by prologic** [comment]
By non-cloud you mean it's a VM running on a Proxmox VE Host? Yes :D


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by SvenDowideit** [comment]
I guess the part I wanted to confirm is - did you use docker-machine and its iso way of not-installing?

**Comment by prologic** [comment]
No originally installed from rancheros iso images


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au
