### ISSUE TITLE
dpkg: error processing package docker.io (--configure

### ISSUE THREAD

**Issue by joshuacox** [rancher/os#1561]
**RancherOS Version: (ros os version)** 1.2.2

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)** KVM

docker.io seems to encountering errors with docker.io when I use the 'ubuntu' console and install software using apt-get, perhaps `docker.io` needs to be pinned?

```
Setting up docker.io (1.12.1-0ubuntu13~16.04.1) ...
addgroup: The group `docker' already exists and is not a system group. Exiting.
dpkg: error processing package docker.io (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 docker.io
```

Everything seems fine for now, but it seems like a situation which could break in the future.  Feel free to close if this has been dismissed already.

**Comment by joshwget** [comment]
RancherOS has a [specific method](https://docs.rancher.com/os/configuration/switching-docker-versions/) for running different versions of Docker. They aren't installed via a package manager like other distros.

I'm going to close since I think this is the only use case where this warning/error would appear. If the docs don't solve your particular use case or I'm missing something else please reopen!

**Comment by SvenDowideit** [comment]
hehehe - I'm going to reopen this - it would be nice to investigate if we can do something to tell the user if they run `apt-get install docker.io`, that it won't work

we could, for example, make a dummy docker package with a large version number, and pre-install it.

**Comment by SvenDowideit** [comment]
(if anyone wants to take this on :) I used to use https://www.msweet.org/projects.php?Z2 , but its not been updated in a few years :/

**Comment by joshuacox** [comment]
I'd like to note that I never installed docker.io, I merely installed did an `apt-get update && apt-get upgrade` before installing git and a few other things.  perhaps it got dragged in from something else I installed.

**Comment by SvenDowideit** [comment]
@joshuacox ooo, it'd be great if you could work out what it was that added docker.io to the list (docker-compose perhaps?)

**Comment by joshuacox** [comment]
I think it was the `apt-get upgrade` that did it, I installed rancherOS from iso into KVM as if it was bare-metal (from the iso's perspective).  I created another and duplicated without an `apt-get upgrade`.  All looks good enough.

```
rancher@rancher:~$ history|grep apt
  190  sudo apt-get update && sudo apt-get install -y git make
```

I think it's as simple as don't ever `apt-get upgrade`, only `apt-get update` to refresh repos and install the few things you need, and upgrade using ros only.   This actually makes sense now that I think about it, if this is the case should a note be added to:

http://docs.rancher.com/os/configuration/switching-consoles/#console-persistence

or is this documented elsewhere?

**Comment by joshuacox** [comment]
I finally dug up the node the original issue happened on, and indeed docker-compose may be the culprit, here's a `grep apt` of the history on that node:

```
rancher@rancher:~$ history|grep apt
   27  apt-cache search docker-compose
   28  sudo apt-get install -y docker-compose
   46  sudo apt-get install byobu -
   85  sudo apt-get install time
  100  sudo apt-get install debootstrap
  415  sudo apt-get update && sudo apt-get install -y git make
```
