### ISSUE TITLE
should be able to use the output of `ros config export` for `ros install`

### ISSUE THREAD

**Issue by SvenDowideit** [rancher/os#1565]
i just did it, and i get a kernel panic on boot

**Comment by jdel** [comment]
What's the status on this ? i'm running v1.0.4 and `ros c export` still generates a non-valid file starting with `EXTRA_CMDLINE: /init` instead of `#cloud-config`.

**Comment by SvenDowideit** [comment]
its down for the v1.2 milestone - it might be something for a new contributor to learn a little about the RancherOS codebase :)

**Comment by jdel** [comment]
I see what you're doing there 😆, I'll see what I can do. Any chance you'd be available on slack to help me setting up a dev environment if needed ?

**Comment by SvenDowideit** [comment]
yes to a chance - I'm in Brisbane, Australia, so a mildly painful TZ - but you can also ping @joshwget :D
