### ISSUE TITLE
v0.8.0-rc9 vmlinuz-4.9.7-rancher PXE boot with rancher.state.dev=none

### ISSUE THREAD

**Issue by mscribe** [rancher/os#1578]
**RancherOS Version: (ros os version)**
v0.8.0-rc9

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
baremetal

It might just be that one can't mix and match rc6 initrd with rc9 vmlinuz, but PXE booting with these works:
```
v0.8.0-rc6/initrd
v0.8.0-rc6/vmlinuz-4.9.5-rancher
kernel params: rancher.state.dev=none rancher.cloud_init.datasources=["url:http://example/cloud-config.yaml"]
```
PXE booting with these:
```
v0.8.0-rc6/initrd
v0.8.0-rc9/vmlinuz-4.9.7-rancher
kernel params: rancher.state.dev=none rancher.cloud_init.datasources=["url:http://example/cloud-config.yaml"]
```
Causes it to keep rechecking the availability of the url:
```
level=info msg="Checking availability of \"url\"\n"
```

**Comment by SvenDowideit** [comment]
what about PXE booting rc9 initrd and kernel?

**Comment by mscribe** [comment]
[https://github.com/rancher/os/releases/download/v0.8.0-rc9/initrd](https://github.com/rancher/os/releases/download/v0.8.0-rc9/initrd) doesn't exist, so I was using the latest available initrd.  Does it go by a different name?

**Comment by SvenDowideit** [comment]
ah doh!

**Comment by SvenDowideit** [comment]
I need to figure out what's up with https://github.com/rancher/os/pull/1577

**Comment by SvenDowideit** [comment]
@mscribe I've make https://github.com/rancher/os/releases/tag/v0.8.0-rc9.1 with a matched pair of kernel and initrd

yes, you can't mix and match yet (without luck) I plan on separating the loadable kernel modules into a separate initrd (so you need 2) in 0.9 to allow this though.

can you please test to make sure we're ok?

**Comment by mscribe** [comment]
Thanks, PXE booting with the v0.8.0-rc9.1 files works!
```
$ sudo ros os version
v0.8.0-rc9
```
