### ISSUE TITLE
Enforce a policy of only merging signed commits

### ISSUE THREAD

**Issue by janeczku** [rancher/os#1585]
Proposal:
a) Any commit being merged needs to be signed with a verified GPG signature.
b) Additionally commits contributed by a third-party need to have the `Signed-off-by` line in the commit message, certifying that they wrote it or otherwise have the right to pass it on as a open-source patch.
     
a) is the customer requirement, b) is up for discussion.

**Comment by SvenDowideit** [comment]
closing - we use GitHub, and are an open project - we don't currently think its worth making it harder for anyone to contribute by making everyone require a gpg sig
