### ISSUE TITLE
ZFS as storage shows error in docker info

### ISSUE THREAD

**Issue by tfiduccia** [rancher/os#1592]
**RancherOS Version: (ros os version)** 0.8.0-rc10

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)** AWS

Steps:
1.  Setup and run ZFS
2.  Switch docker storage to zfs
3.  Do a docker info

Results:  Under the storage driver section... Zpool is giving an error instead of returning zpool1
```
Storage Driver: zfs
 Zpool: error while getting pool information strconv.ParseUint: parsing "": invalid syntax
 Zpool Health: not available
 Parent Dataset: zpool1/docker
 Space Used By Parent: 23552
 Space Available: 1895635456
 Parent Quota: no
 Compression: off
```

**Comment by SvenDowideit** [comment]
yup, this is (as far as i know) not a functional issue - and probably has to do with docker needing an update to handle mainline zfs

putting it as post 0.8

**Comment by SvenDowideit** [comment]
@tfiduccia this might be fixed now that we're using an actual release of zfs?

**Comment by SvenDowideit** [comment]
yeah, this looks to have been resolved when I switched to a non-development version of zfs

**Comment by armouredking** [comment]
Is this supposed to be corrected in 1.1.x then? Or is the tagged milestone correct? Confused since it's closed, the help documents and my current install both show this to be the state of ZFS on RancherOS.

Google links to here and docs, but not anywhere else of import for this search query.

Or did something else break from earlier this year to now?

**Comment by jodumont** [comment]
I have the message on Debian9 with 
Server Version: 17.12.0-ce
Storage Driver: zfs
 Zpool: error while getting pool information strconv.ParseUint: parsing "": invalid syntax
 Zpool Health: not available

**Comment by niusmallnan** [comment]
Hey @jodumont 

> yup, this is (as far as i know) not a functional issue - and probably has to do with docker needing an update to handle mainline zfs

Maybe this is an answer.

But if not, please file another issue and give me more details.

**Comment by jodumont** [comment]
Hi @niusmallnan ;
I hope it make sense and please tell me if I might wrong but

by creating a zfs for docker
`zfs create -o mountpoint=/var/lib/docker sys/docker`

and restarting docker everything seems fine now :)
 
> Server Version: 17.12.0-ce
> Storage Driver: zfs
>  Zpool: sys
>  Zpool Health: ONLINE
>  Parent Dataset: sys/docker

thanks for you're reply and sorry to use a old issue for my own mistake
