### ISSUE TITLE
how to add a new host with custom hostname

### ISSUE THREAD

**Issue by godcong** [rancher/os#1595]
**RancherOS Version: (ros os version)**
v0.7.1
**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
docker-machine

in add host like:
http://192.168.1.201:8080/env/1a475/infra/hosts/add?driver=custom
i added a new host named localhost x3
can i rename the hostname on create?

**Comment by janeczku** [comment]
@godcong It might depend on which provider you are deploying. What's the custom driver you are using there?

**Comment by vincent99** [comment]
He says custom ask actual docker-machine is not involved.  There is a custom name but not a way to set it on registration, so the only immediate fix is changing the hosts so that they have a hostname that isn't localhost.

**Comment by godcong** [comment]
i changed the hosts [/etc/hostname] file.
then restart the network.
readd the hosts.
