### ISSUE TITLE
Docker for Windows - Hyper-v - Waiting for host to start - IP not found

### ISSUE THREAD

**Issue by dtodt** [rancher/os#1596]
**RancherOS Version: (ros os version)**
v0.7.1 - Docker for Windows

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
docker-machine @ Windows 10 - hyper-v

Docker version 1.13.1, build 092cba3
docker-machine version 0.9.0, build 15fd4c7

I'm trying to create a rancher-os on hyper-v, but the VM cant find the network adapter.

Here's my command:
`docker-machine --debug create --driver hyperv --hyperv-virtual-switch "hvEthernet" --hyperv-boot2docker-url https://releases.rancher.com/os/latest/rancheros.iso --hyperv-disk-size 30000 --hyperv-memory 4096 rancheros1`

The second command:
`docker-machine --debug create --driver hyperv --hyperv-virtual-switch "hvEthernet" --hyperv-boot2docker-url https://releases.rancher.com/os/v0.7.1/rancheros.iso --hyperv-disk-size 30000 --hyperv-memory 4096 rancheros2`

The third command (not rancher just test):
`docker-machine --debug create --driver hyperv --hyperv-virtual-switch "hvEthernet" test`

So, the test machine is working fine, but the rancher machines not.

On debug log, there's an endless attempt to find the network, known as "Waiting for host to start..."

`docker-machine ls`

| NAME | ACTIVE | DRIVER | STATE | URL | SWARM | DOCKER | ERRORS |
| --- | --- | --- | --- | --- | --- | --- | --- |
| rancheros1 | * | hyperv | Running | | | Unknown | IP not found |
| rancheros2 | - | hyperv | | | | Unknown | |
| test1 | - | hyperv | Running | tcp://10.0.0.8:2376 | | v1.13.1 | |

I think maybe is a version problem, but not sure.
Can someone help with?
Thanks in advance.

**Comment by SvenDowideit** [comment]
I don't currently use Hyper-v - but iirc, the OS needs some hyper-v specific parts (which should be able to be ported from boot2docker as a RancherOS service) to work.

**Comment by dtodt** [comment]
I think maybe something is missing in rancheros boot2docker, because the default boot2docker is working, as can be noted on test1 image.

**Comment by dtodt** [comment]
I've managed to run the RancherOS directly inside hyper-v manager, now it's running ok.

My problem is solved for now.

**Comment by SvenDowideit** [comment]
ah, and the long term issue is #442

**Comment by MichelDiz** [comment]
For the record @dtodt  just Saved me. I was able to make a Hyper-V virtual machine through the PowerShell terminal without problems. I just pasted his command.

I am using Windows 10 Pro 1709

Cheers.

**Comment by yongqiangyue** [comment]
me too.
result:
![image](https://user-images.githubusercontent.com/1995136/51022548-807b1e80-15bf-11e9-8e7a-b0a2bc2c92bf.png)
command: 
docker-machine.exe create --driver hyperv --hyperv-boot2docker-url=file://d:/test/rancheros.iso --hyperv-virtual-switch=Hyper-V-Use rancheros

**Comment by Jason-ZW** [comment]
@yongqiangyue
https://github.com/rancher/os/blob/master/README.md
try this iso.

**Comment by Jason-ZW** [comment]
@yongqiangyue
try this iso
https://releases.rancher.com/os/v1.5.0/hyperv/rancheros.iso

**Comment by yongqiangyue** [comment]
> @yongqiangyue
> try this iso
> https://releases.rancher.com/os/v1.5.0/hyperv/rancheros.iso

thx, Jason-ZW. it fixed

**Comment by yongqiangyue** [comment]
> me too.
> result:
> ![image](https://user-images.githubusercontent.com/1995136/51022548-807b1e80-15bf-11e9-8e7a-b0a2bc2c92bf.png)
> command:
> docker-machine.exe create --driver hyperv --hyperv-boot2docker-url=file://d:/test/rancheros.iso --hyperv-virtual-switch=Hyper-V-Use rancheros
[fixed issue]
using this iso: https://releases.rancher.com/os/v1.5.0/hyperv/rancheros.iso

**Comment by vardhmanandroid2015** [comment]
Make sure to use external network in creating virtual switch with enable ethernet otherwise it will remain in Waiting for host to start..... Once that works then you need to open firewall to connect through.....
