### ISSUE TITLE
Boot Loader not written to disk with v0.2.1 and VMware VCenter

### ISSUE THREAD

**Issue by kentoj** [rancher/os#160]
After doing a new install from ISO I could not boot into my machine. I don't have the exact log output from during the installation today though I'll get it tomorrow.

Here are the steps I did:
1. Create new VM in VCenter with 2 NICs, 8GB RAM, and 100GB HDD
2. Power On machine and connect rancheros.iso
3. login with rancher/rancher
4. $ docker run --privileged -it debian mkfs.ext4 -L RANCHER_STATE /dev/sda
4.1 answer yes to all prompts
5. $ scp myuser@mylaptop:~/cloud-data.yml .
6. $ sudo rancheros-install -d /dev/sda -c ./cloud_data.yml -v v0.2.1 -t generic
7. reboot VM after installation finishes
8. Machine resorts to booting from network interface. After using a boot menu and selecting the hard drive as a boot option it still resorts to the NIC. Is this a result of GRUB not being written to disk?

When I saw the error during install it was some complaint about the partitioning and said something like that GRUB was not written due to the partitioning issue. I'll post the full installation log output tomorrow. Is there anything else needed to help get to the root of this issue?

**Comment by ibuildthecloud** [comment]
We honestly have never tried vCenter, only Fusion and Workstation.  We will try to get a vCenter env working to try to reproduce.  Off the top of my head I can't think of what could be different.

What adapter are you using for the hard disk?

**Comment by ibuildthecloud** [comment]
@sheng-liang  do you think you could get vCenter running to test this?

**Comment by cloudnautique** [comment]
@kentoj You don't need to do step 4. As part of the rancheros-install script installation the disk is partitioned and formatted. I'm guessing that grub is failing to install because of its confused about the labels/partitions. 

If you start with a fresh disk and skip step 4 I think you'll have better luck. If not please let me know.

**Comment by kentoj** [comment]
Great, thanks for the pointer @cloudnautique, I'll try that. @ibuildthecloud as far as which adapter, I don't know. I'll check on that. How would I go about checking my hard drive adapter? Will I have to get information from the physical host?

I'll try starting from a fresh host and see what happens.

**Comment by deniseschannon** [comment]
@kentoj Please let us know if you are still running into this issue on v0.3.3. We've made significant improvements over the last couple of releases and the rancheros-install is much more stable. If you are still having issues, please re-open.
