### ISSUE TITLE
Disks missing in 0.8.0

### ISSUE THREAD

**Issue by zimme** [rancher/os#1609]
**RancherOS Version: v0.8.0**

**Where are you running RancherOS? baremetal**

I have missing disks since the upgrade, they're on a controller card which have the silicon image SIL3112 chipset, which means I probably need the sata_sil module to get that working.

Is there anything I can do on my own?

**Comment by SvenDowideit** [comment]
ah, its build as a kernel module - so you should be able to `ros service enable kernel-extras` and either use `ros service up kernel-extras` and then modprobe to get the module, or reboot.

sorry - I'll need to investigate to see what changed there.

**Comment by zimme** [comment]
aah, maybe kernel-extras has just been disabled during the upgrade. I'll
check that in a bit and get back with an update.

**Comment by SvenDowideit** [comment]
oooo. it might have changed, yes.

**Comment by zimme** [comment]
I'm having trouble running `sudo ros s enable/up kernel-extras`.

In version `v0.7.1` I had `kernel-extras` enabled and I was using `debian-console` in which I installed `zfs` through the backports and I had setup user-docker to use `zfs` as a backend storage.

Now when I've upgraded to `v0.8.0`, `kernel-extras` was still enabled but I guess I'd need to do `sudo ros s up kernel-extras` to rebuild modules for the current kernel.

But as my user-docker daemon can't start because of my zfs pool not being available I can't get the kernel module that I need to bring my zfs pool up.

**Comment by zimme** [comment]
Should the `kernel-extras` really be relying on the user-docker daemon and not on the system-docker daemon?

**Comment by zimme** [comment]
I tried cloning the `os-kernel` repo, I thought I could build and run the `kernel-extras` image on system-docker instead.

But I couldn't get through the build script because It couldn't find the docker daemon, I even tried adding `DAPPER_DOCKER_SOCKET` and point it to the `system-docker.sock` file. still no luck.

**Comment by zimme** [comment]
I solved this by removing the `rancher.docker.storage_driver` which I had set to `zfs` which allowed user-docker to be ran on `/var/lib/docker` without my zfs mountpoint.

So I got `kernel-extras` enabled and started to get the module I was looking for and I got the `zfs` service to run and find my pool properly.

I'd say this issue is resolved.
