### ISSUE TITLE
cloud-init from config drive not working in v0.8.0 (regression)

### ISSUE THREAD

**Issue by huggla** [rancher/os#1614]
**RancherOS Version: v0.8.0**

**Where are you running RancherOS?: rancheros.iso **

Openstack config drives must be formatted as either ISO9660 or VFAT. In v0.7.1 Openstack config drives were detected during boot but only those formatted as ISO9660 were read. In v0.8.0 no config drives are detected or read.

Useful links with information on how to create a config drive:
[https://coreos.com/os/docs/1284.2.0/config-drive.html](https://coreos.com/os/docs/1284.2.0/config-drive.html)
[https://gist.github.com/itzg/608cad532cb61d6b6c10](https://gist.github.com/itzg/608cad532cb61d6b6c10)

**Comment by SvenDowideit** [comment]
ah darn - we only use the qemu virtfs in our testing - I'll add the full iso way to the tests, and fix it for 0.8.1

(unless someone else gets there first :))

**Comment by SvenDowideit** [comment]
I've pulled out VFAT to #1643

**Comment by SvenDowideit** [comment]
iso cloud config drive support should be fixed in v0.8.1
