### ISSUE TITLE
Shared /mnt not available in console containers

### ISSUE THREAD

**Issue by zimme** [rancher/os#1615]
**RancherOS Version: v0.8.0**

**Where are you running RancherOS? Baremetal**

I've setup the `zfs` service, it finds my zpool(`storage`) and I can list it all fine, I've mounted it
under `/mnt/storage` as pointed out in the docs, missed this at first.

However, now that it's mounted under `/mnt/storage` I can't access it from my console.

It seems that at least the debian console and apline console isn't getting the shared `/mnt` properly mounted or something like that.

**Comment by joshwget** [comment]
@SvenDowideit Looks like the alternate console services are missing `/media` and `/mnt` bind mounts https://github.com/rancher/os/blob/master/os-config.tpl.yml#L151.

**Comment by SvenDowideit** [comment]
@zimme this should now be fixed in v0.8.0 - https://github.com/rancher/os-services/pull/95

its likely you need to disable and reenable the console service to get the new debian.yml file tho

**Comment by SvenDowideit** [comment]
argh - wrong button - please close if it works for you :)

**Comment by zimme** [comment]
I've switched to the `default` console, removed the system-docker images for debian and alpine console and removed old containers for said consoles.

I enable the `debian` with `sudo ros console enable debian`, I can see it pulling the image and I reboot the machine. Still no joy.

No `/mnt/storage` so I'm guessing I'm not getting the image with the latest chages?

Have the images been rebuilt with the latest changes or something like that?

**Comment by zimme** [comment]
So I've tried to play around with this in the `default` console and tried to get user-docker running with `rancher.docker.graph=/mnt/storage/docker` and looking at [these ](https://github.com/rancher/os-services/tree/master/d) I can't see that they have have the `/mnt` and `/media` volume.

**Comment by SvenDowideit** [comment]
ok, so the change I made was not to the image, but to the yml service definition. at the moment, those are overly aggressively cached in `/var/lib/rancher/cache` - I mistakenly thought it might be flushed on enable, but clearly not.

The PR you made is the right one longer term, but won't work until v0.8.1 gets released

**Comment by zimme** [comment]
I cleared `/var/lib/rancher/cache` and enabled `debian` console and rebooted the server.

I'm up and running :+1:

**Comment by SvenDowideit** [comment]
ok, so we have a workaround for 0.8.0 and a proper fix coming in 0.8.1
