### ISSUE TITLE
Kernel Commandline edit

### ISSUE THREAD

**Issue by RaymondSchnyder** [rancher/os#1633]
**RancherOS Version: (ros os version)**
v0.8.0
**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
baremetal

I set for the installation the flag "rancher.password=hello" now i added SSL Keys for Public Authentication, but i dont get rid of the flag state above, where can i edit the kernel command line?

**Comment by SvenDowideit** [comment]
these params can be edited using

```
sudo system-docker run --rm -it -v /:/host alpine vi /host/boot/global.cfg
```

**Comment by RaymondSchnyder** [comment]
If i delete this, will i still be able to login with pub auth?

**Comment by RaymondSchnyder** [comment]
Is there any default pass i can use? Because when i used your solution, it changed to a random password and i cant login anymore... Thats not nice...

**Comment by SvenDowideit** [comment]
oh, I thought you set up the ssh key for the user!

the `rancher.password=asfd` option is a kernel boot param, so you can also set it from the Syslinux boot prompt - which is on your console for the first second or so - type any letter to stop it from booting, then type `rancheros-v0.8.0 rancher.password=something` to set the password to `something`

**Comment by RaymondSchnyder** [comment]
I set up the ssh key, but i cant login with it, it just shows after the passphrase input the password input...

**Comment by SvenDowideit** [comment]
odd. perhaps using `ssh -vv rancher@yourserver` may tell you more

**Comment by RaymondSchnyder** [comment]
Are you sure you want to continue connecting (yes/no)? yes
debug2: kex_derive_keys
debug2: set_newkeys: mode 1
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug2: set_newkeys: mode 0
debug1: SSH2_MSG_NEWKEYS received
debug1: SSH2_MSG_SERVICE_REQUEST sent
debug2: service_accept: ssh-userauth
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug2: key: Videos/ssh keys/private.key ((nil)), explicit
debug1: Authentications that can continue: publickey,password,keyboard-interactive
debug1: Next authentication method: publickey
debug1: Trying private key: Videos/ssh keys/private.key
debug1: key_load_private_type: incorrect passphrase supplied to decrypt private key
Enter passphrase for key 'Videos/ssh keys/private.key': 
debug2: we sent a publickey packet, wait for reply
debug1: Authentications that can continue: publickey,password,keyboard-interactive
debug2: we did not send a packet, disable method
debug1: Next authentication method: keyboard-interactive
debug2: userauth_kbdint
debug2: we sent a keyboard-interactive packet, wait for reply
debug1: Authentications that can continue: publickey,password,keyboard-interactive
debug2: we did not send a packet, disable method
debug1: Next authentication method: password



Thats the output i get. really weird, btw your fix above didnt work, the password is still not correct

**Comment by SvenDowideit** [comment]
I use `rancheros-v0.8.0 rancher.password=something` in Syslinux pretty much all the time during development - so that is known to work.

you can also get it to autologin with `rancheros-v0.8.0 rancher.autologin=tty1`..

**Comment by RaymondSchnyder** [comment]
So the password line doesnt work at all for me, i try the autologin line now

**Comment by RaymondSchnyder** [comment]
Okay AutoLogin doesnt work for me either, this becomes really annoying, this is the third time i locked myself out of this OS because of this Public Key SSH Decision.
Is there a real good, dummy safe manual for setup the public key authentication with rancheros? (With adding the key into the cloud config...)?

**Comment by SvenDowideit** [comment]
I think you need to tell us more about what you're actually typing, where, and what type of system you're working with, and how - you're getting failures with things that otherwise seem to work.

my "fastest" way to success is to `sudo ros install -d /dev/sda -f --append "rancheros.autologin=tty1"

but this assumes that you're on a system where your console is tty1.

I am wondering what kind of ssh key you're using - while debugging, I'd go for something simple and common...

**Comment by RaymondSchnyder** [comment]
Okay, also for installing, i used the "--append rancher.password=hallo" parameter.
Then i created a public and private key for the user rancher and i moved the keys to the correct location.
After that, when i logged in, i had the pub key auth AND the password auth. Then i disabled the password auth. But the password auth parameter in sshd_config gets resetet at every boot.
And now the password for rancher is random and i cant log in, if i use the kernel parameters, the system boots normal and the passwords dont work, what is really weird actually.
Im working on a baremetal server over a iLO Java Console to use the server.
The Server is DL160 G6, has a Harddrive and i installed rancher from an usb Stick.
so when i use the parameters, i press enter, and then the system boots, but the parameters i used, are getting ignored, i can make a gif when that would be helpfull (maybe i press the wrong buttons).
I used the password parameter for installation to access the os, because when i used pub key with the cloud config, nothing worked and i couldnt log in.

At the moment, im thinking about an complete reinstall with the docs.
My steps would be:
1. boot the os from USB
2. Create internet connection because there is no DHCP
3. Create SSH Keys
4. Upload SSH keys to a temporary host.
5. Create cloud-config.yml on my laptop with the public key
6. upload the cloud-config.yml and download it with the server
7. on the server, install it with the config
8. after that, everything should work am i right?

**Comment by RaymondSchnyder** [comment]
With my manual above and this post: 
https://forums.rancher.com/t/problems-with-bare-metal-install-in-data-center-specifically-cloud-config-yml/2380/5

i managed to install my server a few minutes ago. Im so happy right now and im thinking about to write an "RancherOS Install for dummies" Guide.

Thank you for your help.

**Comment by SvenDowideit** [comment]
@RaymondSchnyder wrt a guide - do it! I'd be very happy to help you get that done - its incredibility hard for those of us working on the code to know what problems you're having, or why 

wanna try out https://gitbooks.com?
