### ISSUE TITLE
Mounts with ext4 doesnt work / Additional Mounts doesnt work

### ISSUE THREAD

**Issue by RaymondSchnyder** [rancher/os#1639]
**RancherOS Version: (ros os version)**
0.8.0
**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
baremetal

Hi,

My problem is that i wanted to add a mount to my 12TB Harddrive into rancher to store data, but when i insert the Mount details into the cloud-config, it gets ignored, but when i do "ros config get mounts" it shows the mounts, but it wont apply them.
And another thing,
when i try to mount them manually, it doesnt work. DMESG says, that "EXT4" exists not...

Is there something i did wrong?

**Comment by RaymondSchnyder** [comment]
Another Question: Is is possible to create an BTRFS Filesystem on rancheros?

**Comment by SvenDowideit** [comment]
that sounds very odd - can you paste the output when you try to mount manually, and the output of `blkid`

I just did it on a v0.8.0 vm I have, with a fresh disk - and first I made the partition with fdisk, then formated it using mkfs.ext4, and then was able to mount it. (when you do an install, we format the RANCHER_STATE partition using ext4, so its kinda normal)

It'd also be interesting to see the cloud-config you have :)

**Comment by RaymondSchnyder** [comment]
After 3 reinstalls with the same guide, it worked. It just worked.
First i wanted to use BTRFS, didnt work, then i tried two times with ext4 and suddenly it worked.
There is no error log or such i found with information to this, its just strange

**Comment by superseb** [comment]
Don't think there is much to investigate here anymore, anyone finding this, please file a new issue with details to reproduce.
