### ISSUE TITLE
Move curl.me/validator to docs site

### ISSUE THREAD

**Issue by joshwget** [rancher/os#1648]

**Comment by killerspaz** [comment]
Just a heads up, we were testing this out today and noticed an issue.

The examples given in [the docs](https://github.com/rancher/os/blob/master/docs/os/configuration/write-files/index.md) result in an error:

`write_files: Additional property write_files is not allowed`

Surely this is wrong!?

Anyway, we're trying to find out why our cloud-config isn't resulting in a running OS, and the built-in validation isn't returning errors, and your version is returning false errors.
