### ISSUE TITLE
When error thrown in upgrading, it should not prompt or force reboot. 

### ISSUE THREAD

**Issue by deniseschannon** [rancher/os#165]
v0.3.0-rc2

In #164, I am prompted for a reboot or forced a reboot (when using -f in rancherctl os upgrade), but it appears that there is an error with the upgrade.

In reality, it looks like the upgrade was successful, but there are mixed messages. 

We need to make sure there is no reboot attempt if there is an error message thrown.

**Comment by SvenDowideit** [comment]
see #1682
