### ISSUE TITLE
Kernel panic when switching consoles on Raspberry Pi

### ISSUE THREAD

**Issue by hashdang** [rancher/os#1658]
I've tried Debian and Ubuntu, still testing the others.
Console switched by executing `sudo ros console switch [console]`

Edit: I should add that rebooting RancherOS will still cause a kernel panic.

**RancherOS Version: 0.8.0**

**Where are you running RancherOS? Raspberry Pi**

**Comment by SvenDowideit** [comment]
argh. I have a suspicion I know what's up - I'll look into it over the weekend.

**Comment by SvenDowideit** [comment]
woah, even just running `sudo ros console enable debian` causes the kernel panic. I wonder if this is more related to disk/memory usage.

**Comment by melozh** [comment]
Possibly, but I'm not sure. I've expanded my disk after imaging to the full capacity of my SD card (32GB) and I still get the kernel panic.

**Comment by SvenDowideit** [comment]
bizzarely, if i may any comment in an issue i'm assigned to, but didn't create, GH unassigns me.

**Comment by mortenlj** [comment]
This does not seem to happen any more (worked fine in 1.5.0 at least).
