### ISSUE TITLE
ros config get:  Show default values or "No key exists"

### ISSUE THREAD

**Issue by deniseschannon** [rancher/os#166]
v0.3.0-rc2

The get command only prints out "true" foe this boolean but not "false". If I was to get the value, I'd want to see a false printed out so that I know what the value is. Blank line doesn't help me.

```bash
[root@rancher rancher]# rancherctl config get user_docker.tls      

[root@rancher rancher]# rancherctl config set user_docker.tls true 
[root@rancher rancher]# rancherctl config get user_docker.tls     
true
[root@rancher rancher]# rancherctl config set user_docker.tls false
[root@rancher rancher]# rancherctl config get user_docker.tls      

[root@rancher rancher]# 
```

**Comment by deniseschannon** [comment]
Actually, it appears that the get function is showing a blank space for any default value. It's only showing the value if it has been changed.

**Comment by deniseschannon** [comment]
Still an issue in v0.3.0-rc3.

**Comment by deniseschannon** [comment]
I noticed that we no longer have the docker_user.tls in the default rancher.yml. is that why it's showing up blank? 

even doing `rancherctl config get dns` gives me nothing, even though there is a dns in the rancher.yml file.

**Comment by deniseschannon** [comment]
Never mind, I've figured out that if the syntax is in correct like in the example of 'rancherctl config get dns', then it will display nothing.

You need to put the correct key path. In the DNS example, it needs to be 'rancherctl config get network.dns.nameservers'

We should have a better message if there is no valid key in rancher.yml

**Comment by wlan0** [comment]
@deniseschannon what's needed here? Better message if key doesn't exist, and a way to distinguish between `false` value and invalid key?

**Comment by ibuildthecloud** [comment]
@deniseschannon I think we had said that the issue here is that no default values are printed.  Only values put in rancher.yml are read.  So we need to read from the full config and not just rancher.yml

**Comment by deniseschannon** [comment]
@wlan0 yes, problem is that no default values are printed. so if you did a `sudo rancherctl get dns` nothing would be printed out. it only prints things from the rancher.yml

**Comment by wlan0** [comment]
@deniseschannon @ibuildthecloud  -- Currently we do read from default config. I understand the need for better error messages when the key specified is wrong. 

Similarly, the need for displaying the value 'false' instead of blank line is also clear to me. But, there is no evidence to prove that default values are not printed.  

This command works just fine

`sudo rancherctl config get network.dns`

**Comment by ibuildthecloud** [comment]
If default values are printed I'm not sure if there is anything to do.  If somebody does a get on a non existent key, I think I'm fine with it printing nothing,

**Comment by deniseschannon** [comment]
I had previously filed this when in an earlier release, the userdocker.tls was showing a false when it wasn't set. But it could also have been when I was playing around with trying to get tls to work so the key was set in rancher.yml. I agree that if no key exists, it could print nothing. It would be nice to have a message that says "No key exists" but not sure if it's necessary.

**Comment by deniseschannon** [comment]
Verified with v0.4.4-rc2. 

If a boolean is false, we print out false instead of blank.
If an array is empty, it prints out the empty array.
