### ISSUE TITLE
How to modify /sys/kernel?

### ISSUE THREAD

**Issue by felixsanz** [rancher/os#1664]
I have this parameters in my cloud-config file.

```
runcmd/bootcmd:
  - printf "never" > /sys/kernel/mm/transparent_hugepage/enabled
  - printf "never" > /sys/kernel/mm/transparent_hugepage/defrag
```

If i use `runcmd`, my cloud-config file is not parsed and i can't even login since the ssh-key is not added.

If i use `bootcmd`, the parsing is done but the option is still `[always]`, when it should be `[never]`.

If i to manually print that values after login, i get:

```
[rancher@server1 ~]$ sudo printf "never" > /sys/kernel/mm/transparent_hugepage/enabled
-bash: /sys/kernel/mm/transparent_hugepage/enabled: Permission denied
```

So... How can I do it?

**RancherOS Version: (ros os version)**

0.7.1

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**

baremetal

**Comment by narcoticfresh** [comment]
@felixsanz did you find a solution for this? i'm having the same issue, on rancherOS v1.1.0

**Comment by felixsanz** [comment]
@narcoticfresh I didn't find one sorry

**Comment by narcoticfresh** [comment]
@felixsanz 
just as a reference or if anyone finds this.. i've seen in the documentation of rancherOS 1.1.0, that the `console` system docker service now actually executes `/etc/rc.local` if found..

And it seems to work.. I created `/etc/rc.local` through my config:

```yml
write_files:
  - path: /etc/rc.local
    permissions: "0644"
    owner: root
    content: |
      echo never > /sys/kernel/mm/transparent_hugepage/enabled
```
if i boot after that, it seems to be correct:

```
rancher@swarm-manager ~ $ cat /sys/kernel/mm/transparent_hugepage/enabled
always madvise [never]
```

so this looks like a very easy way :+1:
