### ISSUE TITLE
rancheros v0.8.1 can't install to qemu image file

### ISSUE THREAD

**Issue by cynici** [rancher/os#1667]
**RancherOS Version: v0.8.1**

**Where are you running RancherOS? docker container**

Up till version v0.8.0-rc1 (haven't tested with any later rc releases), I have been able to install RancherOS on a KVM raw image file via loop device mapper, as described in this article, https://forums.rancher.com/t/proposal-to-install-on-qemu/1236

But in version 0.8.1, `ros install` no longer accepts `-d` and `-p` option in the same manner. When I specified `-d /dev/mapper/loop0p1`, `setDiskpartitions()` would exit with "bad device name /dev/mapper/loop0p1"

**Comment by SvenDowideit** [comment]
ah, wow, yup - the installer was re-written in go, and while i tried to cover all the bases, this one wasn't.

**Comment by cynici** [comment]
Hi Sven,
Sorry to be a pain the ass. This issue has not been fixed in RancherOS v0.9.0.
Do you still intend to fix it, or is there a workaround for my use-case?

Thank you very much.

**Comment by SvenDowideit** [comment]
yes, I need to make time to fix this :/

**Comment by SvenDowideit** [comment]
I've started work on this, and its a nice example of what you can do

but for the sake of completness, https://github.com/rancher/os/tree/master/scripts/images/openstack is the way we've been doing it for releases
