### ISSUE TITLE
Rename `user-docker` command to `user-dockerd`

### ISSUE THREAD

**Issue by janeczku** [rancher/os#1673]
Since this command is available on the console, users need to understand that this is the daemon not the client

**Comment by joshwget** [comment]
There isn't really any use case to call this command directly. I think a better solution would be to prompt for confirmation if a user accidentally types it somehow. Internally we can call it with a `-f` flag.

**Comment by SvenDowideit** [comment]
(0.9 maybe - renaming should be pretty trivial, and would mean its called what it is)

**Comment by SvenDowideit** [comment]
this is in 1.0.2
