### ISSUE TITLE
Can't upgrade using custom state partition settings

### ISSUE THREAD

**Issue by ibuildthecloud** [rancher/os#1674]
Running with `rancher.state.dev=LABEL=CUSTOM rancher.state.directory=ros` the upgrade does not find the right device to mount.  Also if it mounts the correct device it probably won't know to touch the files in `/ros/boot` and not `/boot`.

**Comment by SvenDowideit** [comment]
I've added some logic for upgrade to try `rancher.state.dev` - but we need to write some code and tests for install to do `rancher.state.directory` and then some tests showing it upgrades.

turns out we also need to add support for gpt booting for this use case.

(probably defering to 0.9.1)

**Comment by SvenDowideit** [comment]
this has become less of a priority, as we've solved the problem differently.
