### ISSUE TITLE
ros openstack image 0.8.1 cannot boot due filesystem error

### ISSUE THREAD

**Issue by curx** [rancher/os#1676]
**RancherOS Version: (ros os version)**
0.8.1

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
baremetal, openstack

I've tried running the image from the release url 

https://github.com/rancher/os/releases/download/v0.8.1/rancheros-openstack.img

but the image won't boot:

![ros-os-error](https://cloud.githubusercontent.com/assets/875914/23782357/0bc90f8e-0554-11e7-8ff9-d9e613b8a95e.png)

Digging a bit deeper and try mount the qcow2 on my workstation, ext4 complains about a broken journal

```bash
$ qemu-nbd -c /dev/nbd1 rancheros-openstack.img 
$ kpartx -av /dev/nbd1 
$ mount /dev/mapper/nbd1p1 /mnt/
$ dmesg | tail -1
[254115.168263] EXT4-fs (dm-4): error loading journal
```

**Comment by SvenDowideit** [comment]
@curx can you please try the v0.9.0 openstack image?

**Comment by curx** [comment]
tested and works like a charm
