### ISSUE TITLE
RancherOS as a workstation

### ISSUE THREAD

**Issue by mytototo** [rancher/os#1677]
Hi!

Is it possible to start rancherOS side by side with Gnome desktop environment? Or the only way is to install another Linux distro with Rancher inside a Docker?

The goal is to have a workstation dedicated to Docker / Rancher with the ability to leverage Gnome.

Thanks for your time.

**Comment by xlCHINCHlx** [comment]
I was messing around with this awhile back, it runs amazingly smooth/snappy.  I just don't have enough free time right now so it sits as is but works great.  its based off the work by a guy from redhat I just wrote a few scripts and othee bits to fully automate the whole proccess.  I need to track down a few scripts from my old box and add them to my repo for it to be a one click set up, if your interested let my know and ill dig them up.   Until then clone my rancher-workstation repo and pull the squid image from my dockerhub repo. Run the squid image then the rancher-workstation image.  This will take an install of rancherOS on bare metal with no gui only terminal console and build a full gnome dte with hardware excelleration and working audio. The base OS image is fedora dnf works nicely.  

This Is the pdf I mentioned it will explain everything in great detail: https://lists.projectatomic.io/projectatomic-archives/atomic-devel/2015-June/pdfTIh2rTGNDA.pdf

When I just downloaded google kicked a warning about the https being insecure. Idk, ymmv

if you have any questions let me know.

Cheers. . .

**Comment by mytototo** [comment]
Thanks for your answer @xlCHINCHlx. I'll take a look at it. :-)

**Comment by mostafahussein** [comment]
@mytototo have you tried it ? did it work ?

**Comment by pwFoo** [comment]
RancherOS with kernel-extras (kernel modules) and some custom containers (xorg, fluxbox, chrome,...) works fine, but latest RancherOS booting really slow with my dell notebook from ssd. Boot time is over 30 seconds.

So it would be fine If startup could be optimized to few seconds as possible with older RancherOS versions...

**Comment by mostafahussein** [comment]
@pwFoo Could you guide me how to add the video driver ? and which kernel modules did you used or needed to be installed ?

**Comment by pwFoo** [comment]
I tested it with an older version of RancherOS. There was and maybe is a kernel-extras to enable / install with `ros service`?
But RancherOS changed since I tested it and instead of ~10 seconds boot time it now needs 30-60 seconds from SSD... So it isn't usable as desktop because it's to slow...

**Comment by duhruh** [comment]
@xlCHINCHlx hey i'm trying to adapt what you did but for an arm machine. Running into issues with the squid container. Wondering if you could post the dockerfile for that too. :)
