### ISSUE TITLE
service & console list commands displaying debug info

### ISSUE THREAD

**Issue by tfiduccia** [rancher/os#1687]
**RancherOS Version: (ros os version)** v0.9.0-rc1

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)** AWS

Steps:
1.  Run sudo ros service list
2.  Run sudo ros console list

Results: The list does come out but before that there is a bunch of debug info.
> DEBU[0000] Reading config cmdline                       
> DEBU[0000] Input obj map[rancher:map[state:map[dev:LABEL=RANCHER_STATE wait:true]]] 
> DEBU[0000] writing /var/lib/rancher/cache/https:/raw.githubusercontent.com/rancher/os-services/v0.9.0-rc1/index.yml to /var/lib/rancher/cache/https:/raw.githubusercontent.com/rancher/os-services/v0.9.0-rc1

**Comment by SvenDowideit** [comment]
this should be resolved in 0.9.0-rc2 - I've reverted the new cli changes that cause the `ros` cmds to fail.

**Comment by tfiduccia** [comment]
Version - v0.9.0-rc2
Verified fixed
