### ISSUE TITLE
Can't enable service

### ISSUE THREAD

**Issue by tfiduccia** [rancher/os#1688]
**RancherOS Version: (ros os version)** v0.9.0-rc1

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**AWS

Steps:
1.  Run sudo ros service enable kernel-headers

Results:
> DEBU[0000] Cached file not found: /var/lib/rancher/cache/core/kernel-headers.yml 
> ERRO[0000] Failed to load kernel-headers: Failed to load core/kernel-headers.yml: open /var/lib/rancher/cache/core/kernel-headers.yml: no such file or directory 
> FATA[0000] No valid Services found

**Comment by SvenDowideit** [comment]
this should be fixed in 0.9.0-rc2 - I've reverted the new cli changes that cause the `ros` cmds to fail.

**Comment by tfiduccia** [comment]
Version - v0.9.0-rc2
Verified fixed
