### ISSUE TITLE
rancheros does not recognize config file

### ISSUE THREAD

**Issue by tfiduccia** [rancher/os#1689]
**RancherOS Version: (ros os version)** v0.9.0-rc1

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**  AWS

Steps:
1.  Setup a AWS machine where you add a bunch of ssh keys in Advanced Details
2.  Try to 'ssh rancheros@<ip>' into your machine from terminal

Results:  Asks for a password.  

Comments:
If I use a file to ssh in, and then do a sudo ros config export.  The config info from AWS is not there only the file info.  So it looks like config is being ignored.

**Comment by SvenDowideit** [comment]
mmm, I seem to have this happening on v0.7.1 too - perhaps we have a bad format, or perhaps something else is up

I also note you write `ssh rancheros@` - I'm going to assume that was a writeup typo :)

(still investigating)

**Comment by SvenDowideit** [comment]
looks like its in `/var/lib/rancher/conf/cloud-config.d/boot.yml` as it should be, but then there was a change to the merging of the info

**Comment by SvenDowideit** [comment]
ok, this too should be fixed in 0.9.0-rc2

**Comment by tfiduccia** [comment]
Version - 0.9.0-rc2
Verified fixed
