### ISSUE TITLE
Question: How to add drivers to machine-rancheros.iso?

### ISSUE THREAD

**Issue by JemiloII** [rancher/os#170]
Wondering how I could add drivers to the rancheros machine iso install process. I'd like to add bluetooth and internet drivers.

**Comment by ibuildthecloud** [comment]
0.3.0-rc2 includes a lot more drivers, but I'm sure some are missing.  We don't exactly make it easy to add drivers.  You can create a fully custom build of RancherOS if you want.  You will need to change the kernel config in os-base and then follow the instructions at https://github.com/rancherio/os-base/blob/master/README.md to build RancherOS with a custom os-base.

0.4.0 will focus on making it easier to swap out the kernel.

**Comment by JemiloII** [comment]
Would you mind making a guide on how to add a device driver?

**Comment by ibuildthecloud** [comment]
Yes I can.  Are you trying to add a device driver that is in the upstream Linux kernel tree or is this a driver from a different source?  The procedure is a bit different.

**Comment by JemiloII** [comment]
its a linux driver for the motherboard, sata drives, samsung evo, amd opteron 6272

**Comment by deniseschannon** [comment]
With #258, this will help with this issue.

**Comment by haswalt** [comment]
Any progress on this guide? I want to add the RAID drivers for my HP raid controller into the build

**Comment by deniseschannon** [comment]
This will be included in v0.4.0. Thanks for all your patience!

**Comment by ibuildthecloud** [comment]
In 0.4 you can easily now build an ISO with a custom kernel.  Additionally we provide the kernel headers so you can build additional kernel modules without building a whole new kernel.  For example DKMS works.

**Comment by JemiloII** [comment]
awesome I'll have to go and give this a try, thanks
