### ISSUE TITLE
Unable to set console via cloudconfig

### ISSUE THREAD

**Issue by thiagonache** [rancher/os#1708]
**RancherOS Version: (ros os version)**
0.9.0

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
AWS

Hi there,

I've been using same cloud-config to set console version on AWS, but it seems not working on rancher 0.9.0. I've looked at documentation and I was not able to found any change.

```
#cloud-config
rancher:
  console: ubuntu
```

Can you check it, please?

Best regards.

**Comment by SvenDowideit** [comment]
mmm, I just added both to the Advanced settings section of the AWS creation site,

```
#cloud-config
rancher:
  console: debian
```

and 

```
#cloud-config
rancher:
  console: ubuntu
```

and they worked.

can you be more specific about what you did?

**Comment by thiagonache** [comment]
yes... you're right. Something happened on that deployment. Sorry for not double checking before open issue.

thank you.

**Comment by tfiduccia** [comment]
Version - 0.9.0
@thiagonache - I just created a AWS machine and copied your cloud config into Advanced.  When I ssh'ed into the completed machine and ran 'sudo ros console list', it showed ubuntu as my current console.  So it is currently working and I cannot reproduce your issue.
