### ISSUE TITLE
ZFS troubles on v0.8.1 hosts

### ISSUE THREAD

**Issue by janeczku** [rancher/os#1711]
**RancherOS Version: (ros os version)**
v0.8.1

![lockup](https://cloud.githubusercontent.com/assets/3813921/24158079/a89b5458-0e31-11e7-8ba0-a4b82bd5fe73.png)

Steps:
1. Setup ZFS service and enable Docker ZFS storage as per documentation: https://docs.rancher.com/os/storage/using-zfs/
2. Reboot host
3. Reboot host

Result:
1. Sometimes the host would lock up immediately after reboot and not able to login on the VM console or connect via SSH (`acpid: exiting` is printed to the console)
2. While Docker would use ZFS on first reboot, it would revert to `Storage Driver: overlay` on subsequent boots

Docker not using ZFS example:

```Shell
host-001:~$ sudo zfs list -o name,mountpoint,mounted | grep mnt
zpool1 /mnt/zpool1 no
zpool1/docker /mnt/zpool1/docker no
host-001:~$ sudo ros config get rancher.docker.storage_driver
host-001:~$ sudo ros config get rancher.docker.graph
/mnt/zpool1/docker
host-001:~$ docker info
Containers: 13
Running: 12
Paused: 0
Stopped: 1
Images: 11
Server Version: 1.12.6
Storage Driver: overlay
Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: Volume: local
Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.9.12-rancher
Operating System: RancherOS v0.8.1
OSType: linux
Architecture: x86_64
CPUs: 6
Total Memory: 9.766 GiB
Name: host-001
ID: HLVK:RT36:G4WP:MVVC:S6ML:BOOE:7CMD:46RG:KSGU:WKFR:3RXJ:I6E2
Docker Root Dir: /mnt/zpool1/docker
```

**Comment by SvenDowideit** [comment]
do you enable, then up the zfs service and watch the logs to see that its finished before rebooting?

(basically, I'm wondering if "locks up" on boot is it rebuilding, and if you wait long enough, it completes.)

the other - I'll have to look into it

**Comment by tfiduccia** [comment]
Version v0.9.1 - able to reproduce

**Comment by SvenDowideit** [comment]
on the AWS vm I just tested on, I too can reproduce this \o/

but by setting the storage_driver explicitly, the user docker is using zfs every time.

I've asked for more info from @janeczku - just in case the real hardware on site has different characteristics.


debug dmesg and `system-docker logs docker` from the failed run might be interesting.

**Comment by janeczku** [comment]
@SvenDowideit 

we noticed that after reboot the zfs pool shows with a status of mounted=no. Might this be the reason why docker falls back to Overlay?

```
$ sudo zfs list -o name,mountpoint,mounted | grep mnt
zpool1 /mnt/zpool1 no
zpool1/docker /mnt/zpool1/docker no
```

**Comment by SvenDowideit** [comment]
@janeczku then I need the more detailed logs and info from the system

I also see mount == no if i don't set `zfs`

**Comment by SvenDowideit** [comment]
@janeczku we think explicitly setting `zfs` triggers the pools to be mounted, and then the docker daemon pauses a little - it does seem slower to start

if you have further details, please reopen

**Comment by tfiduccia** [comment]
Version - v0.9.2-rc1
Checked that ZFS storage is still set after reboot if you explicitly set zfs to be mounted.  Also checked after rebooting a couple of times.  zfs pool have the property mounted set to "yes"
