### ISSUE TITLE
Long two and a half hour timeout when we can't set console

### ISSUE THREAD

**Issue by andyshinn** [rancher/os#1720]
**RancherOS Version: (ros os version)** 0.9.0

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)** AWS (ami-2a38b14a)

This seems related to #1655 and #1538. Loading the console configuration seems to take an unnecessarily long time if there is no Internet connection.
 
```
[Tue Mar 21 16:26:00 2017] time="2017-03-21T16:26:00Z" level=info msg="Applying 127.0.0.1/8 to lo" 
[Tue Mar 21 16:26:00 2017] time="2017-03-21T16:26:00Z" level=info msg="Applying ::1/128 to lo" 
[Tue Mar 21 16:26:00 2017] time="2017-03-21T16:26:00Z" level=info msg="Running DHCP on eth0" 
[Tue Mar 21 18:56:30 2017] ERRO[9037] Failed to load console: Get https://raw.githubusercontent.com/rancher/os-services/v0.9.0/u/ubuntu.yml: dial tcp 151.101.40.133:443: i/o timeout 
[Tue Mar 21 18:56:30 2017] DEBU[9037] Using /proc/version to set rancher.environment.KERNEL_VERSION = 4.9.15-rancher               
```

This should probably be a lot less.

**Comment by SvenDowideit** [comment]
@andyshinn is this a fresh install of 0.9.0, or an upgraded vm?

I agree, that doesn't make sense - was this vm intended to have no network?

**Comment by andyshinn** [comment]
It is a fresh creation of the 0.9.0 AMI. No, it isn't intended. The network just happens to have DNS access but not regular Internet and I noticed this while trying to debug the instance never coming up.

**Comment by SvenDowideit** [comment]
fresh 0.9.0 with a default network setup? or a custom vpc?

if its all standard then :(

**Comment by andyshinn** [comment]
It is a custom VPC. Networking routing goes over an external firewall. The networking I can fix and understand the issue. I'm just noting the RancherOS behavior during the network issue.

**Comment by SvenDowideit** [comment]
ok, excellent - then i know what to poke! merci for the details!!

**Comment by SvenDowideit** [comment]
yeah, I've been playing with this a little, and its not something we can resolve in a patch release :/

**Comment by SvenDowideit** [comment]
this may be significantly improved in v1.1.0
