### ISSUE TITLE
cloud-init userdata doesnt work with config drive iso

### ISSUE THREAD

**Issue by cjellick** [rancher/os#1721]
**RancherOS Version: (ros os version)**
v0.9.0

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
Local KVM (via ranher-vm)

An iso that work's with ros v0.6.0 for cloud-init+config drive does not work with v0.9.0

ISO is attached.

Here are the qemu command used to launch the VM.

Successful v0.6.0 launch:
```
qemu-system-x86_64 -vnc unix:/vm/6dee05d1ee25633cb84d42d7098dd285533ada65eac238c4339e4a66f4a63e2b/vnc \
-drive file=/image/sda.qcow2,if=none,id=drive-disk0,format=qcow2 \
-device virtio-blk-pci,scsi=off,drive=drive-disk0,id=virtio-disk0,bootindex=1 \
-cdrom cloud-drive.iso \
-realtime mlock=off \
-serial stdio -usbdevice tablet \
-enable-kvm -machine accel=kvm \
-m 512 -smp cpus=2 \
-device virtio-net-pci,netdev=net0,mac=02:87:4d:1d:04:bc \
-netdev tap,id=net0,vhost=on,fd=3
```
Unsuccessful v0.9.0 launch:
```
exec qemu-system-x86_64 -vnc unix:/vm/11ffd1e154418008ddd7d012cd9d776d965fb24ee75aec28fa1c13fe44c5aa59/vnc -drive file=/image/sda.qcow2,if=none,id=drive-disk0,format=qcow2 -device virtio-blk-pci,scsi=off,drive=drive-disk0,id=virtio-disk0,bootindex=1 -cdrom cloud-drive.iso -realtime mlock=off -serial stdio -usbdevice tablet -enable-kvm -machine accel=kvm -m 512 -smp cpus=2 -device virtio-net-pci,netdev=net0,mac=02:87:4d:e7:ae:cb -netdev tap,id=net0,vhost=on,fd=3

```
(Commands are the same)

Here's the command used to generate the iso:
```
genisoimage -allow-lowercase -allow-multidot -J -l -ldots -o cloud-drive.iso -publisher Rancher -quiet -r -V config-2 /tmp/ranchervm.kUjGJ0
```
I saw issues/PRs/release notes stating that it should work in v0.8.1, but that _completely_ failed with the message:
> Boot failed: Please change disks and press any key to continue

**Comment by cjellick** [comment]
Here's the ISO

[cloud-drive.zip](https://github.com/rancher/os/files/866192/cloud-drive.zip)

**Comment by SvenDowideit** [comment]
one interesting thing is that the `scripts/run` doesn't use `-cdrom` - it uses 
```            CLOUD_CONFIG_DISK="-fsdev local,security_model=passthrough,readonly,id=fsdev0,path=${CCROOT} \
                -device virtio-9p-pci,id=fs0,fsdev=fsdev0,mount_tag=config-2"
```

**Comment by SvenDowideit** [comment]
(and the cloud-init code definitly uses the `config-2` to identify that there's something to use.

**Comment by SvenDowideit** [comment]
ok, I've made #1734 - with which we can then use an existing iso file for testing.

`./scripts/run --fresh --cloud-config cloud-drive.iso`

**Comment by SvenDowideit** [comment]
using the above ISO, and `scrips/run --fresh --cloud-config cloud-config.iso` starts it as

```
+ exec qemu-system-x86_64 -nographic -serial stdio -display none -rtc base=utc,clock=host -kernel /home/sven/src/rancher/os/build/kernel/vmlinuz -initrd /home/sven/src/rancher/os/build/initrd.tmp -append 'printk.devkmsg=on rancher.debug=true rancher.password=rancher console=ttyS0 rancher.autologin=ttyS0  rancher.state.dev=LABEL=RANCHER_STATE rancher.state.autoformat=[/dev/sda,/dev/vda] rancher.rm_usr' -m 2048 -net nic,vlan=0,model=virtio -net user,vlan=0,hostfwd=tcp::2222-:22,hostname=rancher-dev -drive if=virtio,file=/home/sven/src/rancher/os/state/hd.img -smp 1 -cdrom cloud-drive.iso -fsdev local,security_model=none,id=fsdev1,path=/home/sven -device virtio-9p-pci,id=fs1,fsdev=fsdev1,mount_tag=home
```

and works. so there's some other wrinkle.

**Comment by SvenDowideit** [comment]
ok, so there's hope - `./scripts/run --fresh --boothd --openstack --console --cloud-config cloud-drive.iso` leaves me with a vm i can't log into, but it also (unlike the other runs) doesn't have the hostname set to what's in the metadata.

**Comment by SvenDowideit** [comment]
I'm going to close this. I can __ONLY__ reproduce it if i change my qemu to use `-m 512` - which we already found in other places to cause instability and errors. 

Until we have time to reduce the memory footprint, we can't support that little memory.
