### ISSUE TITLE
add ctop to the consoles

### ISSUE THREAD

**Issue by SvenDowideit** [rancher/os#1722]
https://bcicen.github.io/ctop/

presumably via magic

**Comment by ibuildthecloud** [comment]
You can just run ctop with `docker run -ti --name ctop --rm -v /var/run/docker.sock:/var/run/docker.sock quay.io/vektorlab/ctop:latest`

to me this is a good example of magic wonka style apps.  Like you put a symlink in /usr/bin/ctop -> /usr/bin/magic-appifier that just then downlaods and runs a container on demand if you call it

**Comment by SvenDowideit** [comment]
I wonder if that means we should mirror images in our own namespace, or risk someone er, switching what their image means.
