### ISSUE TITLE
Reapply services configuration that are in cloud-config

### ISSUE THREAD

**Issue by ket4yii** [rancher/os#1730]
Is there any way to do it without reboot? Because it's not convenient when service configuration was changed and you have to reboot your nodes to apply it.

**Comment by SvenDowideit** [comment]
it depends which services config was changed. There's always the `ros service restart <servicename>` command..

**Comment by ket4yii** [comment]
@SvenDowideit Just restarting hasn't helped me, but ```ros service rm``` and ```ros service create``` worked my problem out. Thank you.
