### ISSUE TITLE
open-vm-tools: ip or hostname not set

### ISSUE THREAD

**Issue by harmjanblok** [rancher/os#1740]
**RancherOS Version: (ros os version)** v0.8.1, v0.9.0, v0.9.1

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)** vCloud 8.x (VMware based)

I'm using terraform to provision a VM in vCloud with RancherOS. Afaik, terraform uses VMware Guest Customizations to be able to set IP and hostname.

This setup works fine on `CentOS` however, on `RancherOS` both ip and hostname cannot be set. 

How can I further debug this issue?

**Comment by SvenDowideit** [comment]
I _think_ this can be solved with a clever os-service.

**Comment by harmjanblok** [comment]
We've switched to another setup for our production environment, hence I cannot debug this issue any further.
