### ISSUE TITLE
Can't get into AWS M4 machines

### ISSUE THREAD

**Issue by tfiduccia** [rancher/os#1751]
**RancherOS Version: (ros os version)** v0.9.2-rc1

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
AWS - Type m4.large

**Steps:**
1.  Log into AWS
2.  Create a M4.large type machine with rancheros v0.9.2-rc1
3.  After it's fully created, try to ssh into machine

**Results:**
Can't log in, keeps asking me for a password.

**Comment by deniseschannon** [comment]
Note: neither cloud config or metadata is working for ssh.

**Comment by robmadole** [comment]
I'm having this same problem with R types as well.

**Comment by robmadole** [comment]
And just confirmed that this is not a problem with v0.9.0.

**Comment by robmadole** [comment]
No worries. If I can help let me know. Thank you and the whole team for RancherOS and the Rancher product. We've moved from Docker Cloud and couldn't be happier.

**Comment by SvenDowideit** [comment]
@robmadole can you please try https://github.com/rancher/os/releases/tag/v0.9.2-rc2 ?

can we quote you? :D

**Comment by robmadole** [comment]
@SvenDowideit yep, I'll try it this morning.

And yes feel free to quote me. I'm a lead dev on the [Font Awesome](https://github.com/FortAwesome/Font-Awesome) team.

**Comment by robmadole** [comment]
@SvenDowideit do you have the tooling to create the AMI for this RC?

**Comment by SvenDowideit** [comment]
yeah - we normally don't make them public though - I'll be making the release today (sorry, was away on holidays last week :) )

**Comment by SvenDowideit** [comment]
resolved in v0.9.2
