### ISSUE TITLE
/etc/rc.local not created or execute by os-ubuntuconsole:v0.9.0

### ISSUE THREAD

**Issue by craig-mld** [rancher/os#1754]
After switching to the ubuntu console (os-ubuntuconsole:v0.9.0), there is no /etc/rc.local file. If I create this file manually then it is not executed on boot.

This issues is *not* seen on Rancher OS OpenStack 0.7.1 or 0.8.0, only 0.9.1.  Both of these create the /etc/rc.local file as expected and execute it on reboot.

It is also not seen on the debian console with Rancher 0.9.1 - the debian console creates the /etc/rc.local file as expected and executes it on start up.

**RancherOS Version: (ros os version)**
RancherOS OpenStack 0.9.1 

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
OpenStack

**Comment by SvenDowideit** [comment]
not nice :/

**Comment by SvenDowideit** [comment]
I'm not 100% sure, but this is probably caused by changes to the official ubuntu base image.

**Comment by niusmallnan** [comment]
Now we use ubuntu:17.04 image to build the ubuntu console on v1.1.2-rc2.
Confirm that it does not really contain `rc.local`.
```
docker run -it --rm ubuntu:17.04 bash
root@2350be558d4a:/# cat /etc/rc
rc0.d/ rc1.d/ rc2.d/ rc3.d/ rc4.d/ rc5.d/ rc6.d/ rcS.d/
```

@craig-mld  Do not know why ubuntu to get rid of it, you really need `rc.local` ?

**Comment by craig-mld** [comment]
I found out that the reason the rc.local is absent is because Ubuntu moved to systemd in 15.  Therefore as the Rancher consol has moved on to the new Ubuntu version, the rc.local has disappeared.
Fortunately the improved cloudinit support in v1.6 of Rancher has allowed us to do what we were doing in rc.local using cloudinit, so this is no longer an issue for us.
