### ISSUE TITLE
BBR congestion control

### ISSUE THREAD

**Issue by karlsoon** [rancher/os#1756]
**RancherOS Version: latest**

**Where are you running RancherOS? not depend**

Please, add Google BBR support to kernel.
Currently CONFIG_TCP_CONG_BBR is not set

**Comment by SvenDowideit** [comment]
are there any userspace tools needed?

**Comment by karlsoon** [comment]
No, It is controlled by net.ipv4.tcp_congestion_control

**Comment by SvenDowideit** [comment]
sweet - I'll tee that up for the next time I build a kernel

**Comment by SvenDowideit** [comment]
its likely to be in 0.9.3 very early next week - when 4.9.21 is released.

**Comment by SvenDowideit** [comment]
this went into the 4.9.21 kernel build in v0.9.2
