### ISSUE TITLE
[os-images] Add AWS metadata autoload and AWS EFS support

### ISSUE THREAD

**Issue by efim-a-efim** [rancher/os#1775]
**RancherOS Version: (ros os version)**
latest

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
AWS

Currently AWS EFS is not supported in RancherOS, but it's widely used and highly recommended for shared storage in AWS.
To implement correct EFS support, AWS metadata need to be loaded into the environment to be used by AWS services (ECS agent, EFS, maybe others).

**Comment by SvenDowideit** [comment]
we recently imported the cloud-init metadata library we were using into the RancherOS codebase - see https://github.com/rancher/os/blob/master/config/cloudinit/datasource/metadata/ec2/metadata.go

so we're now in a better place to make this happen.

**Comment by efim-a-efim** [comment]
@SvenDowideit as I can see, some very useful data is not imported. Particularly, AWS access/secret keys for IAM role attached to instance. Also, AWS region parameters are not imported.

The main goal here is to load AWS metadata the way that, at least, AWS tools will work correctly (handling parameters through environment variables).

**Comment by SvenDowideit** [comment]
yeah - that approach (and what you did in https://github.com/rancher/os-services/pull/106 makes alot of sense
