### ISSUE TITLE
Reboot command sometimes hangs on vmware (updated)

### ISSUE THREAD

**Issue by nheinemans** [rancher/os#1778]
Rancheros version 1.0.0 on vmware

When I execute the "sudo reboot" command, the node doesn't reboot. I still worked fine on rancheros 0.9.1.

> This was "fixed" in 1.0.1 with the kernel update, but it seems to not be as reliable on VMWare as it was
> in 0.9.
>

**Comment by SvenDowideit** [comment]
wow - pretty much the only thing in that area (that i can think of) that changed was the kernel.

**Comment by nheinemans** [comment]
The same problem on 0.9.2. It's working fine with the same versions on openstack, so it seems to be vmware specific.

**Comment by markych96** [comment]
not only vmware
same error on Asus P5W motheboard

**Comment by SvenDowideit** [comment]
yeah, i've seen it happen in a number of places, and so var, 4.9.22 fixed it - hopefully 4.9.23 will be just as good.

**Comment by nheinemans** [comment]
This issue is resolved in 1.0.1-rc3 (on vmware).

**Comment by nheinemans** [comment]
It looks like I should have tested this more thoroughly. In version 1.0.1, the reboot command leads to a locked up VM in about 50% of the cases. @SvenDowideit can you please reopen this issue?

**Comment by nheinemans** [comment]
Here's a screenshot of a VM which shows this behaviour. The VM boots fine, however after "sudo reboot", the last line in the screenshot appears and the machine hangs. After a powercycle, the machine boots up again.

![screenshot from 2017-05-19 12-36-26](https://cloud.githubusercontent.com/assets/5070895/26244505/2de7c9fc-3c90-11e7-9a74-5cd69e547405.png)

**Comment by nheinemans** [comment]
This issue seems to be resolved in 1.0.2-rc2.

**Comment by SvenDowideit** [comment]
I trust nothing anymore :/

**Comment by janeczku** [comment]
@SvenDowideit they are blocked on upgrading beyond v1.0.0. While they don't experience that issue with v1.0.0, they saw a host lockup with v1.0.1 where "acpid: exiting" was printed to the screen and host was not reachable via SSH. According to the user this did not occur after executing the reboot command but rather during normal operation.
![image](https://user-images.githubusercontent.com/3813921/28384179-070a634e-6cc4-11e7-8e1b-39eb6ad5d4b6.png)

**Comment by SvenDowideit** [comment]
v1.1.0 will add a shutdown command timeout - an amount of time (default 60 seconds) that it will wait for containers to exit.

**Comment by SvenDowideit** [comment]
we've found the cause via ESXi 5.5 and RancherOS 0.8.1 - the existing code stops the system containers in random order - and if the console is asked to stop before open-vm-tools, it sometimes will not exit, and then the shutdown code waits forever.

I've re-written the shutdown code in v1.1.0 and v1.0.4 to stop the console container last, and to add a configurable timeout (default 60s) after which we ignore the wait and shut down.
