### ISSUE TITLE
shutdown now does not work

### ISSUE THREAD

**Issue by sheng-liang** [rancher/os#178]
On RancherOS "shutdown now" does not shutdown the machine.

RancherOS shutdown should behave the same as the standard shutdown command.

**Comment by iDiogenes** [comment]
Typing reboot also does not reboot the box. The only way I have been able to reboot from the shell is to kill PID 1.

**Comment by deniseschannon** [comment]
@iDiogenes I am starting to test out v0.4.4-rc1 and I haven't had any issues with rebooting. What version of RancherOS are you using and do you have reproducible steps of how to make it so that you can't reboot?

**Comment by iDiogenes** [comment]
Hello @deniseschannon I am using v0.4.3 and I also saw the issue on v0.4.2. I don't see the issue when running in a VM, just on the bare-metal install. To reproduce I have racherOS up and running with a couple container and from the CLI I type `reboot` or `shutdown -r now` or even `halt`. The all result in my SSH session being terminated, but the system never fully rebooting. If I have a ping running during the process, it doesn't drop any packets, so I believe the reboot process is being hung on shutting down one of the system containers. If you could provide 4.4-rc1 in iso form I would be happy to test and let you know if I am seeing the same thing.

Also, this system does not have a video card, just a serial console, so at the moment, I am not able to see the output once I type reboot.

**Comment by deniseschannon** [comment]
@iDiogenes We now have a v0.4.5 that is released. By any chance would you be able to test it out to see if you are still having issues?

**Comment by iDiogenes** [comment]
I will test this week and get back to you.

Thanks!



On May 22, 2016 at 2:24:18 PM, Denise (notifications@github.com) wrote:

@iDiogenes We now have a v0.4.5 that is released. By any chance would you be able to test it out to see if you are still having issues?

**Comment by iDiogenes** [comment]
I can confirm that `reboot` and `shutdown now` work on 0.4.5. Thanks! 

Also, I notice something else curious, my host is obtaining two DHCP address. For example, it responds to 192.168.122.3 and 192.168.127.9. However, the `ifconfig` output only show only the .3 address. I even did a LAN scan to confirm the MAC address were identical and they were. Not a huge issue, but figured I would mention it. Let me know if you want me to open a issue about this.

**Comment by deniseschannon** [comment]
@iDiogenes Can you open up a new issue for that one? Best to keep the issues separate.

**Comment by deniseschannon** [comment]
Per @joshwget, this isn't working in with our current master.

**Comment by joshwget** [comment]
I was using it incorrectly. Some of the flags are fairly non-standard, so I filed a separate issue about make it behave more as expected #1048.

**Comment by ramalg** [comment]
I am able to shutdown using 
sudo shutdown

- It doew not prompt for any password and I never set one during installation
