### ISSUE TITLE
[os-images] `ros service list` not working on stable due to branch deletion

### ISSUE THREAD

**Issue by Udyrfrykte** [rancher/os#1783]
**RancherOS Version: (ros os version)**
1.0.0

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
AWS

Hello,

the `ros service list` command on RancherOS seems to fetch the following URL :
https://raw.githubusercontent.com/rancher/os-services/<RancherOS version\>/index.yml

Since the v1.0.0 branch has just been deleted from the rancher/os-services repository, RancherOS v1.0.0 (the current stable) is now unable to execute this command.

Could you put this branch back, please ?

Thanks,

**Comment by Drakulix** [comment]
Same here.

**Comment by tfiduccia** [comment]
Version v1.0.0
The repository is indeed gone.  I can't even upgrade to it.

**Comment by tfiduccia** [comment]
@Udyrfrykte & @Drakulix  - We got it back there.  Try again, should work now.

**Comment by SvenDowideit** [comment]
argh. sorry. fat midnight fingers
