### ISSUE TITLE
Rancher server changes its IP address to the Docker bridge one after some period of time

### ISSUE THREAD

**Issue by AleksandrNull** [rancher/os#1784]
I have some strange issues with RancherOS and Rancher.

Right now I'm booting up one master and 3 workers in VMs via EFI with vmlinuz and initrd of 0.9.1 version of RancherOS.
After some period of time (less than a day) cluster is fall apart because (my suggestion) Rancher server report incorrect IP address (please take a look on screenshot in attachments). If I just reboot master node everything returns back to normal but for less than a day again.

**RancherOS Version: (ros os version)**
0.9.1

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
VMs on baremetal servers.

<img width="1143" alt="screen shot 2017-04-13 at 09 27 02" src="https://cloud.githubusercontent.com/assets/2253348/25014146/67cc603c-202b-11e7-906d-14e940ff889b.png">

**Comment by aemneina** [comment]
@AleksandrNull do you register your hosts with the environmental variable CATTLE_AGENT_IP. That should prevent the host from detecting the wrong IP.

**Comment by SvenDowideit** [comment]
After the problem happens again, can you please give us the output of `sudo ros service logs network` and the output of `ip a` and `route -n` - from the Rancher server box?

**Comment by AleksandrNull** [comment]
Hi Ahmad!

Didn't know that it's a requirement and it's going little bit below main instruction so I missed it. Shame on me! Will check that again and update this topic with results! 
I really appreciate that you pointed on that thing!

Thanks,
Aleksandr.

**Comment by AleksandrNull** [comment]
> After the problem happens again, can you please give us the output of sudo ros service logs network and the output of ip a and route -n - from the Rancher server box?

Here it is:

`[rancher@rancher ~]$ sudo ros service logs network
network_1 | time="2017-04-10T19:31:35Z" level=info msg="Running network: stop-network-pre=true" 
network_1 | time="2017-04-10T19:31:35Z" level=info msg="Running DHCP on eth0" 
network_1 | control_open: Connection refused
network_1 | time="2017-04-11T17:00:02Z" level=info msg="Running network: stop-network-pre=true" 
network_1 | time="2017-04-11T17:00:02Z" level=info msg="Running DHCP on eth0" 
network_1 | control_open: Connection refused
network_1 | time="2017-04-12T00:22:37Z" level=info msg="Running network: stop-network-pre=true" 
network_1 | time="2017-04-12T00:22:38Z" level=info msg="Running DHCP on eth0" 
network_1 | control_open: Connection refused
[rancher@rancher ~]$ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 52:54:00:9c:c4:8c brd ff:ff:ff:ff:ff:ff
    inet 172.16.96.161/24 brd 172.16.96.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::5054:ff:fe9c:c48c/64 scope link 
       valid_lft forever preferred_lft forever
3: docker0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 02:42:fe:90:d8:a7 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 scope global docker0
       valid_lft forever preferred_lft forever
    inet 10.42.0.1/16 scope global docker0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:feff:fe90:d8a7/64 scope link 
       valid_lft forever preferred_lft forever
5: veth865178a@if4: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master docker0 state UP group default 
    link/ether ba:a2:e4:47:29:4a brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet6 fe80::b8a2:e4ff:fe47:294a/64 scope link 
       valid_lft forever preferred_lft forever
13: veth7bf91ca@if12: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master docker0 state UP group default 
    link/ether f2:6b:e4:bb:31:03 brd ff:ff:ff:ff:ff:ff link-netnsid 1
    inet6 fe80::f06b:e4ff:febb:3103/64 scope link 
       valid_lft forever preferred_lft forever
14: veth52ed6619@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master docker0 state UP group default 
    link/ether 0a:0f:78:56:e9:c0 brd ff:ff:ff:ff:ff:ff link-netnsid 2
    inet6 fe80::80f:78ff:fe56:e9c0/64 scope link 
       valid_lft forever preferred_lft forever
20: veth9f98ee5c@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master docker0 state UP group default 
    link/ether 7e:d8:aa:e3:6a:de brd ff:ff:ff:ff:ff:ff link-netnsid 4
    inet6 fe80::7cd8:aaff:fee3:6ade/64 scope link 
       valid_lft forever preferred_lft forever
128: vethddf86ed7@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master docker0 state UP group default 
    link/ether ee:06:ed:51:9f:d7 brd ff:ff:ff:ff:ff:ff link-netnsid 3
    inet6 fe80::ec06:edff:fe51:9fd7/64 scope link 
       valid_lft forever preferred_lft forever
[rancher@rancher ~]$ route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         172.16.96.1     0.0.0.0         UG    202    0        0 eth0
10.42.0.0       0.0.0.0         255.255.0.0     U     0      0        0 docker0
169.254.169.250 0.0.0.0         255.255.255.255 UH    0      0        0 docker0
172.16.96.0     0.0.0.0         255.255.255.0   U     202    0        0 eth0
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
`

**Comment by AleksandrNull** [comment]
Worked like a charm with CATTLE_AGENT_IP parameter. Thanks a lot guys!
