### ISSUE TITLE
Issues with v1.0.0 AMI and NFS

### ISSUE THREAD

**Issue by jrhjr07** [rancher/os#1787]
**RancherOS Version: (ros os version)**
v1.0.0 (ami-03fc6f63) and v0.9.0 (ami-2a38b14a)

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**

AWS Running the v1.0.0 AMI and the v0.9.0 AMI

We are seeing issue with mounting NFS (using rancher/storage-nfs:v0.6.5) volumes in our environment with a newly provisioned v1.0.0 AMI.  When we provision the v.0.9.0 AMI with the same NFS container the volumes mount correctly.  We were also able to upgrade the v0.9.0 rancher OS hosts to v1.0.0 and continue to mount NFS correctly.  It seems like the AWS AMI for v1.0.0 (ami-03fc6f63) is having trouble mounting NFS using the NFS container.

## Logs

*Logs from cattle started with v1.0.0 AMI*

```
4/14/2017 2:08:54 PMtime="2017-04-14T19:08:54Z" level=info msg=Starting
4/14/2017 2:08:54 PMtime="2017-04-14T19:08:54Z" level=info msg="Running on host $host#(1h53) with driver rancher-nfs(1sd11)"
4/14/2017 2:08:54 PMtime="2017-04-14T19:08:54Z" level=info msg="Starting plugin for rancher-nfs"
4/14/2017 2:16:01 PMtime="2017-04-14T19:16:01Z" level=info msg="container $containerID destroyed"
4/14/2017 2:16:01 PMtime="2017-04-14T19:16:01Z" level=info msg="container $containerID destroyed"
4/14/2017 2:16:10 PMtime="2017-04-14T19:16:10Z" level=info msg="container $containerID destroyed"
4/14/2017 2:16:10 PMtime="2017-04-14T19:16:10Z" level=info msg="container $containerID destroyed"
4/14/2017 2:16:17 PMtime="2017-04-14T19:16:17Z" level=info msg=attach.request name=$volumeName
4/14/2017 2:16:17 PMtime="2017-04-14T19:16:17Z" level=error msg=attach.response error="No such volume"
4/14/2017 2:16:17 PMtime="2017-04-14T19:16:17Z" level=info msg=attach.request name=$volumeName
4/14/2017 2:16:17 PMtime="2017-04-14T19:16:17Z" level=error msg=attach.response error="No such volume"
4/14/2017 2:16:17 PMtime="2017-04-14T19:16:17Z" level=info msg=attach.request name=$volumeName
4/14/2017 2:16:17 PMtime="2017-04-14T19:16:17Z" level=error msg=attach.response error="No such volume"
4/14/2017 2:16:17 PMtime="2017-04-14T19:16:17Z" level=info msg=attach.request name=$volumeName
4/14/2017 2:16:17 PMtime="2017-04-14T19:16:17Z" level=error msg=attach.response error="No such volume"
4/14/2017 2:16:17 PMtime="2017-04-14T19:16:17Z" level=info msg=attach.request name=$volumeName
4/14/2017 2:16:17 PMtime="2017-04-14T19:16:17Z" level=error msg=attach.response error="No such volume"
4/14/2017 2:16:41 PMtime="2017-04-14T19:16:41Z" level=info msg=attach.request name=$volumeName
4/14/2017 2:16:41 PMtime="2017-04-14T19:16:41Z" level=error msg=attach.response error="No such volume"
4/14/2017 2:16:41 PMtime="2017-04-14T19:16:41Z" level=info msg=attach.request name=$volumeName
4/14/2017 2:16:41 PMtime="2017-04-14T19:16:41Z" level=error msg=attach.response error="No such volume"
4/14/2017 2:16:42 PMtime="2017-04-14T19:16:42Z" level=info msg=attach.request name=$volumeName
4/14/2017 2:16:42 PMtime="2017-04-14T19:16:42Z" level=error msg=attach.response error="No such volume"
4/14/2017 2:16:42 PMtime="2017-04-14T19:16:42Z" level=info msg=attach.request name=$volumeName
4/14/2017 2:16:42 PMtime="2017-04-14T19:16:42Z" level=error msg=attach.response error="No such volume"
4/14/2017 2:16:42 PMtime="2017-04-14T19:16:42Z" level=info msg=attach.request name=$volumeName
4/14/2017 2:16:42 PMtime="2017-04-14T19:16:42Z" level=error msg=attach.response error="No such volume"
4/14/2017 2:17:11 PMtime="2017-04-14T19:17:11Z" level=info msg=attach.request name=$volumeName
4/14/2017 2:17:11 PMtime="2017-04-14T19:17:11Z" level=error msg=attach.response error="No such volume"
4/14/2017 2:17:11 PMtime="2017-04-14T19:17:11Z" level=info msg=attach.request name=$volumeName
4/14/2017 2:17:11 PMtime="2017-04-14T19:17:11Z" level=error msg=attach.response error="No such volume"
4/14/2017 2:17:11 PMtime="2017-04-14T19:17:11Z" level=info msg=attach.request name=$volumeName
4/14/2017 2:17:11 PMtime="2017-04-14T19:17:11Z" level=error msg=attach.response error="No such volume"
4/14/2017 2:17:11 PMtime="2017-04-14T19:17:11Z" level=info msg=attach.request name=$volumeName
4/14/2017 2:17:11 PMtime="2017-04-14T19:17:11Z" level=error msg=attach.response error="No such volume"
4/14/2017 2:17:11 PMtime="2017-04-14T19:17:11Z" level=info msg=attach.request name=$volumeName
4/14/2017 2:17:11 PMtime="2017-04-14T19:17:11Z" level=error msg=attach.response error="No such volume"
4/14/2017 2:17:41 PMtime="2017-04-14T19:17:41Z" level=info msg=attach.request name=$volumeName
4/14/2017 2:17:41 PMtime="2017-04-14T19:17:41Z" level=error msg=attach.response error="No such volume"
4/14/2017 2:17:41 PMtime="2017-04-14T19:17:41Z" level=info msg=attach.request name=$volumeName
4/14/2017 2:17:41 PMtime="2017-04-14T19:17:41Z" level=error msg=attach.response error="No such volume"
4/14/2017 2:17:42 PMtime="2017-04-14T19:17:42Z" level=info msg=attach.request name=$volumeName
4/14/2017 2:17:42 PMtime="2017-04-14T19:17:42Z" level=error msg=attach.response error="No such volume"
4/14/2017 2:17:42 PMtime="2017-04-14T19:17:42Z" level=info msg=attach.request name=$volumeName
4/14/2017 2:17:42 PMtime="2017-04-14T19:17:42Z" level=error msg=attach.response error="No such volume"
4/14/2017 2:17:42 PMtime="2017-04-14T19:17:42Z" level=info msg=attach.request name=$volumeName
4/14/2017 2:17:42 PMtime="2017-04-14T19:17:42Z" level=error msg=attach.response error="No such volume"
4/14/2017 2:18:26 PMtime="2017-04-14T19:18:26Z" level=info msg=attach.request name=$volumeName
4/14/2017 2:18:26 PMtime="2017-04-14T19:18:26Z" level=error msg=attach.response error="No such volume"
4/14/2017 2:18:26 PMtime="2017-04-14T19:18:26Z" level=info msg=attach.request name=$volumeName
4/14/2017 2:18:26 PMtime="2017-04-14T19:18:26Z" level=error msg=attach.response error="No such volume"
4/14/2017 2:18:26 PMtime="2017-04-14T19:18:26Z" level=info msg=attach.request name=$volumeName
4/14/2017 2:18:26 PMtime="2017-04-14T19:18:26Z" level=error msg=attach.response error="No such volume"
4/14/2017 2:18:26 PMtime="2017-04-14T19:18:26Z" level=info msg=attach.request name=$volumeName
4/14/2017 2:18:26 PMtime="2017-04-14T19:18:26Z" level=error msg=attach.response error="No such volume"
4/14/2017 2:18:26 PMtime="2017-04-14T19:18:26Z" level=info msg=attach.request name=$volumeName
4/14/2017 2:18:26 PMtime="2017-04-14T19:18:26Z" level=error msg=attach.response error="No such volume"
4/14/2017 2:19:33 PMtime="2017-04-14T19:19:33Z" level=info msg="container $containerID destroyed"
4/14/2017 2:19:44 PMtime="2017-04-14T19:19:44Z" level=info msg="container $containerID destroyed"
4/14/2017 2:19:56 PMtime="2017-04-14T19:19:56Z" level=info msg=attach.request name=$volumeName
4/14/2017 2:19:56 PMtime="2017-04-14T19:19:56Z" level=error msg=attach.response error="No such volume"
4/14/2017 2:19:56 PMtime="2017-04-14T19:19:56Z" level=info msg=attach.request name=$volumeName
4/14/2017 2:19:56 PMtime="2017-04-14T19:19:56Z" level=error msg=attach.response error="No such volume"
4/14/2017 2:19:56 PMtime="2017-04-14T19:19:56Z" level=info msg=attach.request name=$volumeName
4/14/2017 2:19:56 PMtime="2017-04-14T19:19:56Z" level=error msg=attach.response error="No such volume"
4/14/2017 2:19:56 PMtime="2017-04-14T19:19:56Z" level=info msg=attach.request name=$volumeName
4/14/2017 2:19:56 PMtime="2017-04-14T19:19:56Z" level=error msg=attach.response error="No such volume"
4/14/2017 2:19:56 PMtime="2017-04-14T19:19:56Z" level=info msg=attach.request name=$volumeName
4/14/2017 2:19:56 PMtime="2017-04-14T19:19:56Z" level=error msg=attach.response error="No such volume"
4/14/2017 2:19:59 PMtime="2017-04-14T19:19:59Z" level=info msg="container $containerID destroyed"
4/14/2017 2:20:55 PMtime="2017-04-14T19:20:55Z" level=info msg="container $containerID destroyed"
4/14/2017 2:23:57 PMtime="2017-04-14T19:23:57Z" level=info msg=attach.request name=$volumeName
4/14/2017 2:23:57 PMtime="2017-04-14T19:23:57Z" level=error msg=attach.response error="No such volume"
4/14/2017 2:23:57 PMtime="2017-04-14T19:23:57Z" level=info msg=attach.request name=$volumeName
4/14/2017 2:23:57 PMtime="2017-04-14T19:23:57Z" level=error msg=attach.response error="No such volume"
4/14/2017 2:23:57 PMtime="2017-04-14T19:23:57Z" level=info msg=attach.request name=$volumeName
4/14/2017 2:23:57 PMtime="2017-04-14T19:23:57Z" level=error msg=attach.response error="No such volume"
4/14/2017 2:23:57 PMtime="2017-04-14T19:23:57Z" level=info msg=attach.request name=$volumeName
4/14/2017 2:23:57 PMtime="2017-04-14T19:23:57Z" level=error msg=attach.response error="No such volume"
4/14/2017 2:23:57 PMtime="2017-04-14T19:23:57Z" level=info msg=attach.request name=$volumeName
4/14/2017 2:23:57 PMtime="2017-04-14T19:23:57Z" level=error msg=attach.response error="No such volume"
4/14/2017 2:28:26 PMtime="2017-04-14T19:28:26Z" level=info msg=attach.request name=$volumeName
4/14/2017 2:28:26 PMtime="2017-04-14T19:28:26Z" level=error msg=attach.response error="No such volume"
4/14/2017 2:28:26 PMtime="2017-04-14T19:28:26Z" level=info msg=attach.request name=$volumeName
4/14/2017 2:28:26 PMtime="2017-04-14T19:28:26Z" level=error msg=attach.response error="No such volume"
4/14/2017 2:28:26 PMtime="2017-04-14T19:28:26Z" level=info msg=attach.request name=$volumeName
4/14/2017 2:28:26 PMtime="2017-04-14T19:28:26Z" level=error msg=attach.response error="No such volume"
4/14/2017 2:28:26 PMtime="2017-04-14T19:28:26Z" level=info msg=attach.request name=$volumeName
4/14/2017 2:28:26 PMtime="2017-04-14T19:28:26Z" level=error msg=attach.response error="No such volume"
4/14/2017 2:28:26 PMtime="2017-04-14T19:28:26Z" level=info msg=attach.request name=$volumeName
4/14/2017 2:28:26 PMtime="2017-04-14T19:28:26Z" level=error msg=attach.response error="No such volume"
4/14/2017 2:33:41 PMtime="2017-04-14T19:33:41Z" level=info msg=attach.request name=$volumeName
4/14/2017 2:33:42 PMtime="2017-04-14T19:33:42Z" level=info msg=attach.response
4/14/2017 2:36:08 PMtime="2017-04-14T19:36:08Z" level=info msg="container $containerID destroyed"
4/14/2017 2:36:09 PMtime="2017-04-14T19:36:09Z" level=info msg="container $containerID destroyed"
4/14/2017 2:36:11 PMtime="2017-04-14T19:36:11Z" level=info msg="container $containerID destroyed"
4/14/2017 2:36:18 PMtime="2017-04-14T19:36:18Z" level=info msg="container $containerID destroyed"
4/14/2017 2:36:19 PMtime="2017-04-14T19:36:19Z" level=info msg="container $containerID destroyed"
4/14/2017 2:36:38 PMtime="2017-04-14T19:36:38Z" level=info msg=attach.request name=$volumeName
4/14/2017 2:36:38 PMtime="2017-04-14T19:36:38Z" level=info msg=attach.response
```

*Logs from v0.9.0 AMI cattle upgraded to v1.0.0*

```
4/14/2017 2:36:05 PMtime="2017-04-14T19:36:05Z" level=info msg=Running
4/14/2017 2:36:05 PMtime="2017-04-14T19:36:05Z" level=info msg=Starting
4/14/2017 2:36:06 PMtime="2017-04-14T19:36:06Z" level=info msg="Running on host $cattle#N+1(1h56) with driver rancher-nfs(1sd11)"
4/14/2017 2:36:06 PMtime="2017-04-14T19:36:06Z" level=info msg="Starting plugin for rancher-nfs"
4/14/2017 2:36:08 PMtime="2017-04-14T19:36:08Z" level=info msg="container $container destroyed"
4/14/2017 2:36:09 PMtime="2017-04-14T19:36:09Z" level=info msg="container $container destroyed"
4/14/2017 2:36:11 PMtime="2017-04-14T19:36:11Z" level=info msg="container $container destroyed"
4/14/2017 2:36:12 PMtime="2017-04-14T19:36:12Z" level=info msg="container $container destroyed"
4/14/2017 2:36:12 PMtime="2017-04-14T19:36:12Z" level=info msg="container $container destroyed"
4/14/2017 2:36:19 PMtime="2017-04-14T19:36:19Z" level=info msg="container $container destroyed"
4/14/2017 2:36:26 PMtime="2017-04-14T19:36:26Z" level=info msg="container $container destroyed"
4/14/2017 2:36:26 PMtime="2017-04-14T19:36:26Z" level=info msg="container $container destroyed"
4/14/2017 2:36:26 PMtime="2017-04-14T19:36:26Z" level=info msg="container $container destroyed"
4/14/2017 2:36:38 PMtime="2017-04-14T19:36:38Z" level=info msg=attach.request name=$volumeName
4/14/2017 2:36:38 PMtime="2017-04-14T19:36:38Z" level=info msg=attach.response
4/14/2017 2:36:38 PMtime="2017-04-14T19:36:38Z" level=info msg=mount.request name=$volumeName
4/14/2017 2:36:39 PMtime="2017-04-14T19:36:39Z" level=info msg=mount.response mountpoint="/var/lib/rancher/volumes/rancher-nfs/$volumeName"
```

**Comment by jrhjr07** [comment]
# Logs from cattle started with v1.0.0 AMI 
4/14/2017 2:08:54 PMtime="2017-04-14T19:08:54Z" level=info msg=Starting
4/14/2017 2:08:54 PMtime="2017-04-14T19:08:54Z" level=info msg="Running on host $host#(1h53) with driver rancher-nfs(1sd11)"
4/14/2017 2:08:54 PMtime="2017-04-14T19:08:54Z" level=info msg="Starting plugin for rancher-nfs"
4/14/2017 2:16:01 PMtime="2017-04-14T19:16:01Z" level=info msg="container $containerID destroyed"
4/14/2017 2:16:01 PMtime="2017-04-14T19:16:01Z" level=info msg="container $containerID destroyed"
4/14/2017 2:16:10 PMtime="2017-04-14T19:16:10Z" level=info msg="container $containerID destroyed"
4/14/2017 2:16:10 PMtime="2017-04-14T19:16:10Z" level=info msg="container $containerID destroyed"
4/14/2017 2:16:17 PMtime="2017-04-14T19:16:17Z" level=info msg=attach.request name=$volumeName
4/14/2017 2:16:17 PMtime="2017-04-14T19:16:17Z" level=error msg=attach.response error="No such volume"
4/14/2017 2:16:17 PMtime="2017-04-14T19:16:17Z" level=info msg=attach.request name=$volumeName
4/14/2017 2:16:17 PMtime="2017-04-14T19:16:17Z" level=error msg=attach.response error="No such volume"
4/14/2017 2:16:17 PMtime="2017-04-14T19:16:17Z" level=info msg=attach.request name=$volumeName
4/14/2017 2:16:17 PMtime="2017-04-14T19:16:17Z" level=error msg=attach.response error="No such volume"
4/14/2017 2:16:17 PMtime="2017-04-14T19:16:17Z" level=info msg=attach.request name=$volumeName
4/14/2017 2:16:17 PMtime="2017-04-14T19:16:17Z" level=error msg=attach.response error="No such volume"
4/14/2017 2:16:17 PMtime="2017-04-14T19:16:17Z" level=info msg=attach.request name=$volumeName
4/14/2017 2:16:17 PMtime="2017-04-14T19:16:17Z" level=error msg=attach.response error="No such volume"
4/14/2017 2:16:41 PMtime="2017-04-14T19:16:41Z" level=info msg=attach.request name=$volumeName
4/14/2017 2:16:41 PMtime="2017-04-14T19:16:41Z" level=error msg=attach.response error="No such volume"
4/14/2017 2:16:41 PMtime="2017-04-14T19:16:41Z" level=info msg=attach.request name=$volumeName
4/14/2017 2:16:41 PMtime="2017-04-14T19:16:41Z" level=error msg=attach.response error="No such volume"
4/14/2017 2:16:42 PMtime="2017-04-14T19:16:42Z" level=info msg=attach.request name=$volumeName
4/14/2017 2:16:42 PMtime="2017-04-14T19:16:42Z" level=error msg=attach.response error="No such volume"
4/14/2017 2:16:42 PMtime="2017-04-14T19:16:42Z" level=info msg=attach.request name=$volumeName
4/14/2017 2:16:42 PMtime="2017-04-14T19:16:42Z" level=error msg=attach.response error="No such volume"
4/14/2017 2:16:42 PMtime="2017-04-14T19:16:42Z" level=info msg=attach.request name=$volumeName
4/14/2017 2:16:42 PMtime="2017-04-14T19:16:42Z" level=error msg=attach.response error="No such volume"
4/14/2017 2:17:11 PMtime="2017-04-14T19:17:11Z" level=info msg=attach.request name=$volumeName
4/14/2017 2:17:11 PMtime="2017-04-14T19:17:11Z" level=error msg=attach.response error="No such volume"
4/14/2017 2:17:11 PMtime="2017-04-14T19:17:11Z" level=info msg=attach.request name=$volumeName
4/14/2017 2:17:11 PMtime="2017-04-14T19:17:11Z" level=error msg=attach.response error="No such volume"
4/14/2017 2:17:11 PMtime="2017-04-14T19:17:11Z" level=info msg=attach.request name=$volumeName
4/14/2017 2:17:11 PMtime="2017-04-14T19:17:11Z" level=error msg=attach.response error="No such volume"
4/14/2017 2:17:11 PMtime="2017-04-14T19:17:11Z" level=info msg=attach.request name=$volumeName
4/14/2017 2:17:11 PMtime="2017-04-14T19:17:11Z" level=error msg=attach.response error="No such volume"
4/14/2017 2:17:11 PMtime="2017-04-14T19:17:11Z" level=info msg=attach.request name=$volumeName
4/14/2017 2:17:11 PMtime="2017-04-14T19:17:11Z" level=error msg=attach.response error="No such volume"
4/14/2017 2:17:41 PMtime="2017-04-14T19:17:41Z" level=info msg=attach.request name=$volumeName
4/14/2017 2:17:41 PMtime="2017-04-14T19:17:41Z" level=error msg=attach.response error="No such volume"
4/14/2017 2:17:41 PMtime="2017-04-14T19:17:41Z" level=info msg=attach.request name=$volumeName
4/14/2017 2:17:41 PMtime="2017-04-14T19:17:41Z" level=error msg=attach.response error="No such volume"
4/14/2017 2:17:42 PMtime="2017-04-14T19:17:42Z" level=info msg=attach.request name=$volumeName
4/14/2017 2:17:42 PMtime="2017-04-14T19:17:42Z" level=error msg=attach.response error="No such volume"
4/14/2017 2:17:42 PMtime="2017-04-14T19:17:42Z" level=info msg=attach.request name=$volumeName
4/14/2017 2:17:42 PMtime="2017-04-14T19:17:42Z" level=error msg=attach.response error="No such volume"
4/14/2017 2:17:42 PMtime="2017-04-14T19:17:42Z" level=info msg=attach.request name=$volumeName
4/14/2017 2:17:42 PMtime="2017-04-14T19:17:42Z" level=error msg=attach.response error="No such volume"
4/14/2017 2:18:26 PMtime="2017-04-14T19:18:26Z" level=info msg=attach.request name=$volumeName
4/14/2017 2:18:26 PMtime="2017-04-14T19:18:26Z" level=error msg=attach.response error="No such volume"
4/14/2017 2:18:26 PMtime="2017-04-14T19:18:26Z" level=info msg=attach.request name=$volumeName
4/14/2017 2:18:26 PMtime="2017-04-14T19:18:26Z" level=error msg=attach.response error="No such volume"
4/14/2017 2:18:26 PMtime="2017-04-14T19:18:26Z" level=info msg=attach.request name=$volumeName
4/14/2017 2:18:26 PMtime="2017-04-14T19:18:26Z" level=error msg=attach.response error="No such volume"
4/14/2017 2:18:26 PMtime="2017-04-14T19:18:26Z" level=info msg=attach.request name=$volumeName
4/14/2017 2:18:26 PMtime="2017-04-14T19:18:26Z" level=error msg=attach.response error="No such volume"
4/14/2017 2:18:26 PMtime="2017-04-14T19:18:26Z" level=info msg=attach.request name=$volumeName
4/14/2017 2:18:26 PMtime="2017-04-14T19:18:26Z" level=error msg=attach.response error="No such volume"
4/14/2017 2:19:33 PMtime="2017-04-14T19:19:33Z" level=info msg="container $containerID destroyed"
4/14/2017 2:19:44 PMtime="2017-04-14T19:19:44Z" level=info msg="container $containerID destroyed"
4/14/2017 2:19:56 PMtime="2017-04-14T19:19:56Z" level=info msg=attach.request name=$volumeName
4/14/2017 2:19:56 PMtime="2017-04-14T19:19:56Z" level=error msg=attach.response error="No such volume"
4/14/2017 2:19:56 PMtime="2017-04-14T19:19:56Z" level=info msg=attach.request name=$volumeName
4/14/2017 2:19:56 PMtime="2017-04-14T19:19:56Z" level=error msg=attach.response error="No such volume"
4/14/2017 2:19:56 PMtime="2017-04-14T19:19:56Z" level=info msg=attach.request name=$volumeName
4/14/2017 2:19:56 PMtime="2017-04-14T19:19:56Z" level=error msg=attach.response error="No such volume"
4/14/2017 2:19:56 PMtime="2017-04-14T19:19:56Z" level=info msg=attach.request name=$volumeName
4/14/2017 2:19:56 PMtime="2017-04-14T19:19:56Z" level=error msg=attach.response error="No such volume"
4/14/2017 2:19:56 PMtime="2017-04-14T19:19:56Z" level=info msg=attach.request name=$volumeName
4/14/2017 2:19:56 PMtime="2017-04-14T19:19:56Z" level=error msg=attach.response error="No such volume"
4/14/2017 2:19:59 PMtime="2017-04-14T19:19:59Z" level=info msg="container $containerID destroyed"
4/14/2017 2:20:55 PMtime="2017-04-14T19:20:55Z" level=info msg="container $containerID destroyed"
4/14/2017 2:23:57 PMtime="2017-04-14T19:23:57Z" level=info msg=attach.request name=$volumeName
4/14/2017 2:23:57 PMtime="2017-04-14T19:23:57Z" level=error msg=attach.response error="No such volume"
4/14/2017 2:23:57 PMtime="2017-04-14T19:23:57Z" level=info msg=attach.request name=$volumeName
4/14/2017 2:23:57 PMtime="2017-04-14T19:23:57Z" level=error msg=attach.response error="No such volume"
4/14/2017 2:23:57 PMtime="2017-04-14T19:23:57Z" level=info msg=attach.request name=$volumeName
4/14/2017 2:23:57 PMtime="2017-04-14T19:23:57Z" level=error msg=attach.response error="No such volume"
4/14/2017 2:23:57 PMtime="2017-04-14T19:23:57Z" level=info msg=attach.request name=$volumeName
4/14/2017 2:23:57 PMtime="2017-04-14T19:23:57Z" level=error msg=attach.response error="No such volume"
4/14/2017 2:23:57 PMtime="2017-04-14T19:23:57Z" level=info msg=attach.request name=$volumeName
4/14/2017 2:23:57 PMtime="2017-04-14T19:23:57Z" level=error msg=attach.response error="No such volume"
4/14/2017 2:28:26 PMtime="2017-04-14T19:28:26Z" level=info msg=attach.request name=$volumeName
4/14/2017 2:28:26 PMtime="2017-04-14T19:28:26Z" level=error msg=attach.response error="No such volume"
4/14/2017 2:28:26 PMtime="2017-04-14T19:28:26Z" level=info msg=attach.request name=$volumeName
4/14/2017 2:28:26 PMtime="2017-04-14T19:28:26Z" level=error msg=attach.response error="No such volume"
4/14/2017 2:28:26 PMtime="2017-04-14T19:28:26Z" level=info msg=attach.request name=$volumeName
4/14/2017 2:28:26 PMtime="2017-04-14T19:28:26Z" level=error msg=attach.response error="No such volume"
4/14/2017 2:28:26 PMtime="2017-04-14T19:28:26Z" level=info msg=attach.request name=$volumeName
4/14/2017 2:28:26 PMtime="2017-04-14T19:28:26Z" level=error msg=attach.response error="No such volume"
4/14/2017 2:28:26 PMtime="2017-04-14T19:28:26Z" level=info msg=attach.request name=$volumeName
4/14/2017 2:28:26 PMtime="2017-04-14T19:28:26Z" level=error msg=attach.response error="No such volume"
4/14/2017 2:33:41 PMtime="2017-04-14T19:33:41Z" level=info msg=attach.request name=$volumeName
4/14/2017 2:33:42 PMtime="2017-04-14T19:33:42Z" level=info msg=attach.response
4/14/2017 2:36:08 PMtime="2017-04-14T19:36:08Z" level=info msg="container $containerID destroyed"
4/14/2017 2:36:09 PMtime="2017-04-14T19:36:09Z" level=info msg="container $containerID destroyed"
4/14/2017 2:36:11 PMtime="2017-04-14T19:36:11Z" level=info msg="container $containerID destroyed"
4/14/2017 2:36:18 PMtime="2017-04-14T19:36:18Z" level=info msg="container $containerID destroyed"
4/14/2017 2:36:19 PMtime="2017-04-14T19:36:19Z" level=info msg="container $containerID destroyed"
4/14/2017 2:36:38 PMtime="2017-04-14T19:36:38Z" level=info msg=attach.request name=$volumeName
4/14/2017 2:36:38 PMtime="2017-04-14T19:36:38Z" level=info msg=attach.response

**Comment by SvenDowideit** [comment]
ouch - the fact that it works when upgrading is pretty suspicious :/

**Comment by jrhjr07** [comment]
😭

**Comment by SvenDowideit** [comment]
@jrhjr07 I've been told by @deniseschannon and @aemneina that they've used and tested RancherOS 1.0.0 with rancher-nfs - so there must be something more we need to know to reproduce your problem :/

**Comment by jrhjr07** [comment]
@SvenDowideit I'm specifically using 1.0.0 with the AWS West2 AMI (ami-03fc6f63).  Maybe that's the source?

**Comment by SvenDowideit** [comment]
I don't think it would be the image - we build the us-west1 AMI, and then copy it to the other regions. I wonder if you could make it happen and then give me and @aemneina access to the vm - I'm expecting its something very specific to your setup

**Comment by jrhjr07** [comment]
I don't think I'll be able to give you access to it due to other considerations.  I've sent you an email to your email in your profile.  I'm available to Webex at any time and work to get it fixed.

**Comment by jrhjr07** [comment]
Closing this as I couldn't reproduce today.
