### ISSUE TITLE
Links to v1.0.0 OpenStack image are broken

### ISSUE THREAD

**Issue by stieler-it** [rancher/os#1791]
I am trying to download RancherOS 1.0.0 for OpenStack from the [download page](https://github.com/rancher/os) but I can't.

The "latest" link seems to provide a dated version:
```
[rancher@ranchertest ~]$ sudo ros --version
ros version v0.9.2
```

The direct link to version v1.0.0 returns:
```
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
</Error>
```

**Comment by SvenDowideit** [comment]
oh argh. ok, uploading - the GH release seems to be correct, but we don't point to that.

**Comment by SvenDowideit** [comment]
@stieler-it please reopen if I got it wrong, but the versions listed on the readme should now be the same as those in the github release page - and all 3 should be 1.0.0

**Comment by stieler-it** [comment]
I was able to find the images because of your hint. They are indeed 1.0.0 so I assume fixing the links in the readme already closed this, yes. Thanks!
