### ISSUE TITLE
Additional filesystems in cloud-config do not mount if the target doesn't exist

### ISSUE THREAD

**Issue by gizmotronic** [rancher/os#1792]
**RancherOS Version: (ros os version)**
v1.0.0

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
vSphere Hypervisor 6.5.0 (ESXi) virtual machine, iPXE

[Additional mounts](https://docs.rancher.com/os/storage/additional-mounts/) work only when the target mount point already exists. For example, this works:
```
mounts:
- ["/dev/sdb1", "/mnt", "ext4", ""]
```
However, it doesn't work when you try to use a subdirectory as shown in the example:
```
mounts:
- ["/dev/sdb1", "/mnt/s", "ext4", ""]
```

I'd like to propose that, barring some other mechanism that we can use to create the mount points manually, any mount points specified should be created if they don't already exist.

**Comment by SvenDowideit** [comment]
agreed

**Comment by stieler-it** [comment]
Duplicate of #1506 ?

**Comment by gizmotronic** [comment]
It is, thanks.
