### ISSUE TITLE
1.0.0 image for Raspberry Pi is missing

### ISSUE THREAD

**Issue by Novanic** [rancher/os#1794]
A 1.0.0 image for Raspberry Pi is missing, the latest is 0.9.0. It seems also not to be possible to build it manually like described here: https://gist.github.com/rgaidot/bc2efc014cccabb926392e353708122a. Error message: "repository rancher/os-debianconsole-base not found: does not exist or no pull access".

**Comment by SvenDowideit** [comment]
@Novanic does https://github.com/rancher/os/releases/download/v1.0.0/rancheros-raspberry-pi.zip not work? (Sorry, I'm at DockerCon atm, so things are hectic)

**Comment by Novanic** [comment]
Oh, it's available, thank you for the link. The link is missing within the release links of https://github.com/rancher/os, that's why I thought it is not available.

**Comment by SvenDowideit** [comment]
I've updated the README, so closing.
