### ISSUE TITLE
setup RanchOS with rootfs_arm64.tar.gz

### ISSUE THREAD

**Issue by ChinaFengliang** [rancher/os#1802]
We intend to setup RancherOS on D05 board (a ARM64 server). 

 I use [RancherOS rootfs](https://github.com/rancher/os/releases/download/v1.0.0/rootfs_arm64.tar.gz) as the rootfs, and make kernel Image & modules from  [open-stuary linux](https://github.com/open-estuary/kernel), install firmware & modules into /usr/lib of rootfs.

Boot the arm64-server, 
<pre><code>
INFO[0001] Apply Network Config
INFO[0001] Applying 127.0.0.1/8 to lo
INFO[0001] Applying ::1/128 to lo
INFO[0001] Apply Network Config RunDhcp
INFO[0001] Running DHCP on eth0: dhcpcd -MA4 -e force_hostname=true eth0
ERRO[0001] exec: "dhcpcd": executable file not found in $PATH
INFO[0001] Running DHCP on eth1: dhcpcd -MA4 -e force_hostname=true eth1
ERRO[0001] exec: "dhcpcd": executable file not found in $PATH
INFO[0001] Running DHCP on eth3: dhcpcd -MA4 -e force_hostname=true eth3
ERRO[0001] exec: "dhcpcd": executable file not found in $PATH
INFO[0001] Running DHCP on eth2: dhcpcd -MA4 -e force_hostname=true eth2
ERRO[0001] exec: "dhcpcd": executable file not found in $PATH
INFO[0001] Apply Network Config SyncHostname
INFO[0001] Waiting for Docker at unix:///var/run/system-docker.sock
INFO[0002] Connected to Docker at unix:///var/run/system-docker.sock
INFO[0002] Loading images from /usr/share/ros/images.tar
INFO[0003] Done loading images from /usr/share/ros/images.tar
INFO[0003] Running cloud-init services
INFO[0003] Project [cloudinit]: Starting project
INFO[0003] [0/1] [cloud-init]: Starting
INFO[0038] [1/1] [cloud-init]: Started
INFO[0038] Project [cloudinit]: Project started
INFO[0038] Apply Network Config
INFO[0038] Applying 127.0.0.1/8 to lo
INFO[0038] Applying ::1/128 to lo
INFO[0038] Apply Network Config RunDhcp
INFO[0038] Running DHCP on eth3: dhcpcd -MA4 -e force_hostname=true eth3
ERRO[0038] exec: "dhcpcd": executable file not found in $PATH
INFO[0038] Running DHCP on eth0: dhcpcd -MA4 -e force_hostname=true eth0
INFO[0038] Running DHCP on eth1: dhcpcd -MA4 -e force_hostname=true eth1
INFO[0038] Running DHCP on eth2: dhcpcd -MA4 -e force_hostname=true eth2
ERRO[0038] exec: "dhcpcd": executable file not found in $PATH
ERRO[0038] exec: "dhcpcd": executable file not found in $PATH
ERRO[0038] exec: "dhcpcd": executable file not found in $PATH
INFO[0038] Apply Network Config SyncHostname
ERRO[0038] open /var/lib/rancher/conf/cloud-config.d/boot.yml: no such file or directory
ERRO[0038] open /var/lib/rancher/conf/cloud-config.d/network.yml: no such file or directory
ERRO[0038] open /var/lib/rancher/conf/metadata: no such file or directory
INFO[0039] Launching System Docker
> INFO[0000] Loading images from /usr/share/ros/images.tar
> INFO[0000] Done loading images from /usr/share/ros/images.tar
> INFO[0000] Project [os]: Starting project
> INFO[0000] [0/15] [command-volumes]: Starting
> INFO[0000] [0/15] [system-volumes]: Starting
> INFO[0000] [0/15] [container-data-volumes]: Starting
> INFO[0000] [0/15] [media-volumes]: Starting
> INFO[0000] [0/15] [user-volumes]: Starting
> INFO[0000] [1/15] [command-volumes]: Started
> INFO[0000] [2/15] [container-data-volumes]: Started
> INFO[0000] [3/15] [user-volumes]: Started
> INFO[0000] [4/15] [system-volumes]: Started
> INFO[0000] [4/15] [syslog]: Starting
> INFO[0000] [4/15] [udev-cold]: Starting
> INFO[0000] [5/15] [media-volumes]: Started
> INFO[0000] [5/15] [all-volumes]: Starting
> INFO[0000] [6/15] [all-volumes]: Started
> INFO[0001] [7/15] [syslog]: Started
> INFO[0002] [8/15] [udev-cold]: Started
> INFO[0002] [8/15] [udev]: Starting
> INFO[0002] [9/15] [udev]: Started
> INFO[0002] [9/15] [network]: Starting
> INFO[0002] [10/15] [network]: Started
> INFO[0002] [10/15] [ntp]: Starting
> INFO[0003] [11/15] [ntp]: Started
> INFO[0003] [11/15] [cloud-init-execute]: Starting
> INFO[0003] [12/15] [cloud-init-execute]: Started
> INFO[0003] [12/15] [console]: Starting
> INFO[0003] Rebuilding console
> INFO[0004] [13/15] [console]: Started
> INFO[0004] [13/15] [docker]: Starting
> INFO[0004] [13/15] [preload-user-images]: Starting
> INFO[0004] [14/15] [docker]: Started
> INFO[0007] [15/15] [preload-user-images]: Started
> INFO[0007] Project [os]: Project started
> INFO[0007] RancherOS v1.0.0 started
</code></pre>

There is no login prompt.

**Comment by SvenDowideit** [comment]
I presume you're using a serial connection? I'm guessing that you need to add `console=tty<something> rancher.autologin=tty<somthing>` to the kernel boot cmdline so that we start the shell on there.

**Comment by ChinaFengliang** [comment]
THANKS! This issue has been resolved. Could you tell me the password of the root?

**Comment by SvenDowideit** [comment]
if i remember correctly, there is no root password - you log in as `rancher` with the password `rancher`


personally, I add `rancher.autologin=ttyS0` - or whatever the serial console is

**Comment by SvenDowideit** [comment]
closing :)
