### ISSUE TITLE
changing sysctl settings fails with ros config

### ISSUE THREAD

**Issue by jaknoll** [rancher/os#1806]
**RancherOS Version: v1.0.1-rc1**

**Where are you running RancherOS? baremetal**

Attempting to change the max inotify watches so I can get live replication between systems the command fails:

```
sudo ros config set rancher.sysctl.fs.inotify.max_user_watches 524288
> FATA[0000] Expected a struct or map but was a  at line 74, column 6
```

Tried using other values as well, for example:

```
sudo ros config set rancher.sysctl.fs.inotify.max_user_watches '524288'
sudo ros config set rancher.sysctl.fs.inotify.max_user_watches '['524288']'
```

All fail with the same value.

**Comment by SvenDowideit** [comment]
mmm, looking at https://docs.rancher.com/os/configuration/sysctl/, i wonder if its the dots in the name that causes the problem.

**Comment by SvenDowideit** [comment]
@jaknoll for now, you can use `ros config merge -i your.yml` to merge the sysctl settings in the https://docs.rancher.com/os/configuration/sysctl/ form
