### ISSUE TITLE
Can't ssh into AWS "nano" instances

### ISSUE THREAD

**Issue by a-h** [rancher/os#1810]
**RancherOS Version: (ros os version)**

ami-05d4ee63

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**

AWS

**Description**

I thought I'd run RancherOS to run a single Web server container behind an auto-scaling group (very low traffic).

Given that RancherOS is a 50MB ISO, and the container I was planning to run is just a Go program taking up 5MB, I thought I'd be OK to run Nano instances and I could scale horizontally at peak times if required (probably not). Nano instances only cost $5 a month too.

I put together cloud-config to run the container, but the container never started up and my AWS SSH keys were rejected, asking for a password instead. When I upped the size to micro, no problems, the container started and I could SSH in.

So I guess it doesn't work at nano-scale which surprised me.

I'm not using Rancher at all for this so it's probably not related to https://github.com/rancher/os/issues/872

The docs in the AWS Marketplace "recommend" micro, but how about making it impossible to start the ami or getting the machines to shut themselves down since it doesn't work at nano?

**Comment by SvenDowideit** [comment]
I was looking into this the other day, and it turns out that the `docker load` of the system images we do at initial boot seems to fail when you use this size vm. I've got a change coming that will cause it to panic when that happens (as you get an undefined result), and then for 1.1 I might have a cunning plan - maybe :)

**Comment by SvenDowideit** [comment]
VM's that don't have enough memory should fail in obvious ways from 1.0.1-rc3 onwards due to #1788

**Comment by SvenDowideit** [comment]
and to show the log from a t3.nano with the logging change I made for v1.0.1-rc3 - docker load isn't made for saving memory, so in future we'll work to remove it (long term the plan is containerd)


```
[    7.526698] Freeing unused kernel memory: 1108K (ffff89495c6eb000 - ffff89495c800000)
[    7.531135] Freeing unused kernel memory: 384K (ffff89495cba0000 - ffff89495cc00000)
[34mINFO[0m[0000] Mounting state device /dev/xvda1 to /state   
[    7.695447] EXT4-fs (xvda1): recovery complete
[    7.697361] EXT4-fs (xvda1): mounted filesystem with ordered data mode. Opts: (null)
[34mINFO[0m[0000] Waiting for Docker at unix:///var/run/system-docker.sock 
[    7.740332] time="2017-04-25T04:06:43Z" level=debug msg="START: [/usr/bin/system-docker daemon --graph /var/lib/system-docker --userland-proxy=false --bridge none --group root --restart=false --storage-driver overlay --host unix:///var/run/system-docker.sock] in /" 
[34mINFO[0m[0000] Connected to Docker at unix:///var/run/system-docker.sock 
[    8.000098] tsc: Refined TSC clocksource calibration: 2399.998 MHz
[    8.002947] clocksource: tsc: mask: 0xffffffffffffffff max_cycles: 0x229835b7123, max_idle_ns: 440795242976 ns
[34mINFO[0m[0000] Loading images from /usr/share/ros/images.tar 
[31mFATA[0m[0000] FATAL: failed loading images from /usr/share/ros/images.tar: Error response from daemon: Untar re-exec error: Non-zero exit code: 1: output: write /c5abd9d47d1220c3ccba42f9f7ad4c6fbb66b1dd3e87b2dd11be2549c56a1b3a/layer.tar: no space left on device 
[    8.209427] Kernel panic - not syncing: Attempted to kill init! exitcode=0x00000100
[    8.209427] 
[    8.212273] CPU: 0 PID: 1 Comm: init Not tainted 4.9.24-rancher #1
[    8.212273] Hardware name: Xen HVM domU, BIOS 4.2.amazon 02/16/2017
[    8.212273]  ffff9ca7c000be20 ffffffff9a327906 ffff89495b280000 ffffffff9aa8d088
[    8.212273]  ffff9ca7c000bea0 ffffffff9a146207 ffff9ca700000010 ffff9ca7c000beb0
[    8.212273]  ffff9ca7c000be48 ffffffff9ac5eae8 0000000000000100 ffff89495b298010
[    8.212273] Call Trace:
[    8.212273]  [<ffffffff9a327906>] dump_stack+0x61/0x7d
[    8.212273]  [<ffffffff9a146207>] panic+0xd8/0x221
[    8.212273]  [<ffffffff9a06c67a>] do_exit+0x4d4/0x92c
[    8.212273]  [<ffffffff9a08b8f2>] ? wake_up_state+0x10/0x12
[    8.212273]  [<ffffffff9a074485>] ? signal_wake_up_state+0x2a/0x3b
[    8.212273]  [<ffffffff9a06cb49>] do_group_exit+0x41/0xa2
[    8.212273]  [<ffffffff9a06cbbe>] SyS_exit_group+0x14/0x14
[    8.212273]  [<ffffffff9a6e2e7b>] entry_SYSCALL_64_fastpath+0x1e/0xad
[    8.212273] Kernel Offset: 0x19000000 from 0xffffffff81000000 (relocation range: 0xffffffff80000000-0xffffffffbfffffff)
```
