### ISSUE TITLE
poweroff no longer working in r/OS

### ISSUE THREAD

**Issue by aemneina** [rancher/os#1822]
**RancherOS Version: (ros os version)**
1.0.0

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
VM's

on my r/OS 0.6.1 this works as expected.

**Comment by SvenDowideit** [comment]
@aemneina yup - this was a kernel issue, and is fixed in v1.0.1

**Comment by aemneina** [comment]
yippie!
