### ISSUE TITLE
Feature Request/Discussion

### ISSUE THREAD

**Issue by Rucknar** [rancher/os#1847]
**RancherOS Version: (ros os version)**
10.0.1

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
AWS

**Summary** 

More discussion than a request....

Are there ways in which prometheus host metrics could be integrated into the OS? 
Currently users are scheduling out tools like node_exporter to run inside containers on the host. In reality, these containers often need quite deep level access to the system to obtain these stats.

Is there an angle/possibility that the metrics could be either baked in directly, or perhaps a deep integration with something like the node_exporter?

**Comment by SvenDowideit** [comment]
In RancherOS, everything runs in a container - so really, what you could do, is create a system-docker service for it - and even better, make a PR for that to https://github.com/rancher/os-services
