### ISSUE TITLE
Doc:  building your own custom RancherOS ISO

### ISSUE THREAD

**Issue by yankunsam** [rancher/os#1853]
**RancherOS Version: (ros os version)**

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**

This URL has been deleted, Can I get the newest document to build a custom kernel?

Thanks.

**Comment by superseb** [comment]
What URL did you try?

These are from docs.rancher.com:

* http://docs.rancher.com/os/custom-builds/custom-kernels/
* http://docs.rancher.com/os/custom-builds/custom-rancheros-iso/

**Comment by yankunsam** [comment]
Thanks.  Maybe it is because my network error. Now it works.
