### ISSUE TITLE
add a `reboot --kexec`

### ISSUE THREAD

**Issue by SvenDowideit** [rancher/os#1855]
and clean up `reboot` command so that `reboot --help` doesn't just reboot with no prompt.

**Comment by SvenDowideit** [comment]
if we can clean up https://github.com/rancher/os/issues/1285 at the same time, that would be good.

**Comment by SvenDowideit** [comment]
done in #1965

**Comment by ahnurmi** [comment]
I noticed that `sudo reboot --kexec`, when running in memory from iPXE boot without an installation hard disk attached, results in an error.

[Screenshot](https://i.imgur.com/B10hNbY.png)
