### ISSUE TITLE
missing repository (console switch to ubuntu)

### ISSUE THREAD

**Issue by john-dev** [rancher/os#1860]
** version: v1.0.2-rc1 running **
** hardware: bare-metal (intel nuc) **

[root@rancher docker]# ros console switch ubuntu
Switching consoles will
1. destroy the current console container
2. log you out
3. restart Docker
Continue [y/N]: y
Pulling console (rancher/os-ubuntuconsole:v1.0.2)...
Pulling repository docker.io/rancher/os-ubuntuconsole
&{%!s(*os.file=&{2 /dev/stderr <nil>})}> ERRO[0003] Failed Pulling console : Status: Tag v1.0.2 not found in repository docker.io/rancher/os-ubuntuconsole, Code: 1 
> ERRO[0003] Failed to start: console : Status: Tag v1.0.2 not found in repository docker.io/rancher/os-ubuntuconsole, Code: 1 
[root@rancher docker]#

**Comment by SvenDowideit** [comment]
@john-dev sorry, finger slip - does it work now?

**Comment by john-dev** [comment]
Like a charm, thanks..
