### ISSUE TITLE
Docker 17.03.1 unavailable for RPi3

### ISSUE THREAD

**Issue by klud1** [rancher/os#1862]
**RancherOS Version: (ros os version)**
`ros version v1.0.0`

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
Raspberry Pi 3 Model B

I'm giving a try to RancherOS, and now I want to update the default Docker version, which is `1.11.2` to `17.03.1` in order to join a swarm cluster of RPis (most of them running HypriotOS), but this version is not available for arm, being `1.12.6` the latest available.

```bash
[rancher@TIE-Fighter ~]$ sudo ros engine list
disabled docker-1.10.3
current  docker-1.11.2
disabled docker-1.12.6
disabled docker-1.13.1
disabled docker-17.03.1-ce
disabled docker-17.04.0-ce

[rancher@TIE-Fighter ~]$ sudo ros engine switch docker-17.03.1-ce
> INFO[0004] Project [os]: Starting project               
> INFO[0004] [0/15] [docker]: Starting                    
Pulling docker (rancher/os-docker:17.03.1_arm)...
Pulling repository docker.io/rancher/os-docker
&{%!s(*os.file=&{2 /dev/stderr <nil>})}> ERRO[0009] Failed Starting docker : Status: Tag 17.03.1_arm not found in repository docker.io/rancher/os-docker, Code: 1 
> ERRO[0009] Failed to start: docker : Status: Tag 17.03.1_arm not found in repository docker.io/rancher/os-docker, Code: 1 
> FATA[0009] Status: Tag 17.03.1_arm not found in repository docker.io/rancher/os-docker, Code: 1
```

https://hub.docker.com/r/rancher/os-docker/tags/

![screenshot from 2017-05-17 16-57-51](https://cloud.githubusercontent.com/assets/13160093/26175839/067b9f48-3b22-11e7-9abe-2463c8728ed3.png)

**Comment by SvenDowideit** [comment]
@klud1 I've just made some changes to the engine image building code, and have pushed the missing arm32 images, and some of the arm64 images.

can you please try them out and tell me if they work for you?

**Comment by klud1** [comment]
@SvenDowideit Thanks for the response, i'm off home for some days, going to test as soon as i get home. 

I have a couple of questions, which should probably be part of another issue, but...
- Is it possible to add some swap (swap partition, swap file)? I have 2 RPi3  running raspbian and each of them has an external drive as swap partition.
- Could it be possible to use an external drive as root filesystem (`/`)? I'm asking this since it can be done on raspbian (https://github.com/adafruit/Adafruit-Pi-ExternalRoot-Helper.git).

**Comment by SvenDowideit** [comment]
yes, swap file and external drive should work fine - http://docs.rancher.com/os/storage/state-partition/ should work on RPi too.
