### ISSUE TITLE
/use/bin/docker:exec format error

### ISSUE THREAD

**Issue by yankunsam** [rancher/os#1864]
**RancherOS Version: (ros os version)**

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**

When I build the os as "make ". After downloading dapper. It reportes this errors.

**Comment by SvenDowideit** [comment]
on what hardware & OS are you building? and does docker work?

can you paste the entire console output including the command you're running?

**Comment by yankunsam** [comment]
[sam@sam_dev os-kernel]$ cat /etc/redhat-release
Fedora release 25 (Twenty Five)
[sam@sam_dev os-kernel]$ systemctl status docker
● docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; disabled; vendor preset: disabled)
   Active: active (running) since Thu 2017-05-18 10:55:53 CST; 4h 40min ago
     Docs: https://docs.docker.com
 Main PID: 6852 (dockerd)
    Tasks: 27 (limit: 4915)
   Memory: 32.5M
      CPU: 22.291s
   CGroup: /system.slice/docker.service
           ├─6852 /usr/bin/dockerd
           └─6874 docker-containerd -l unix:///var/run/docker/libcontainerd/docker-containerd.sock --metrics-interval=0 --start-timeout 2m --

May 18 10:55:46 sam_dev dockerd[6852]: time="2017-05-18T10:55:46.308326439+08:00" level=info msg="Graph migration to content-addressability t
May 18 10:55:46 sam_dev dockerd[6852]: time="2017-05-18T10:55:46.308903358+08:00" level=warning msg="Your kernel does not support cgroup rt p
May 18 10:55:46 sam_dev dockerd[6852]: time="2017-05-18T10:55:46.308943824+08:00" level=warning msg="Your kernel does not support cgroup rt r
May 18 10:55:46 sam_dev dockerd[6852]: time="2017-05-18T10:55:46.309792338+08:00" level=info msg="Loading containers: start."
May 18 10:55:50 sam_dev dockerd[6852]: time="2017-05-18T10:55:50.426240050+08:00" level=info msg="Default bridge (docker0) is assigned with a
May 18 10:55:52 sam_dev dockerd[6852]: time="2017-05-18T10:55:52.764828625+08:00" level=info msg="Loading containers: done."
May 18 10:55:53 sam_dev dockerd[6852]: time="2017-05-18T10:55:53.334391219+08:00" level=info msg="Daemon has completed initialization"
May 18 10:55:53 sam_dev dockerd[6852]: time="2017-05-18T10:55:53.334489945+08:00" level=info msg="Docker daemon" commit=89658be graphdriver=o
May 18 10:55:53 sam_dev dockerd[6852]: time="2017-05-18T10:55:53.355854900+08:00" level=info msg="API listen on /var/run/docker.sock"
May 18 10:55:53 sam_dev systemd[1]: Started Docker Application Container Engine.

[sam@sam_dev os-kernel]$ make
./.dapper ci 2>&1 | tee ci.log
time="2017-05-18T15:36:32+08:00" level=fatal msg="fork/exec /usr/bin/docker: exec format error"
[sam@sam_dev os-kernel]$

**Comment by yankunsam** [comment]
I am sorry. Here is under "os" directory

[sam@sam_dev os]$ make
./.dapper default
FATA[0000] fork/exec /usr/bin/docker: exec format error
Makefile:11: recipe for target 'default' failed
make: *** [default] Error 1
