### ISSUE TITLE
how to use the local kernel package

### ISSUE THREAD

**Issue by yankunsam** [rancher/os#1875]
**RancherOS Version: (ros os version)**

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**

Is it possible to use the local kernel package, not by "url" ?

Thanks.

**Comment by yankunsam** [comment]
As the README("packaging your own kernel builds") of os-kernel, here is some questions:

1 create_firmware_tar: tar xf linux*.tar -C $temp: So what linux*.tar is ?
2 package-kernel: FILE="linux-$KVER-x86.tar": And this. 

Thanks.

**Comment by SvenDowideit** [comment]
the tar files are built from the https://github.com/rancher/os-kernel/ repo.

**Comment by yankunsam** [comment]
Ok. I will try.

**Comment by yankunsam** [comment]
Another question about "<>/scripts/download"
+18 --recv-keys 6092693E

Is there some way to get the key id automatic?  Sorry I try, but failed.

**Comment by SvenDowideit** [comment]
that line should do exactly that - automatically get gregkh's current signing key.
