### ISSUE TITLE
building custom rancher iso with brtfs support built-in

### ISSUE THREAD

**Issue by xinity** [rancher/os#1878]
**RancherOS Version: 1. 0.1**

**Where are you running RancherOS? docker-machine**

I'm trying to built a custom rancheros which will boot on btrfs instead of overlay, but i'm failing.

I've simply updated the file : `os-config.tpl.yml` and changed `overlay` with `btrfs`
i've also added the section below:
```
  modules: [btrfs]
```

but still failing :(

Am I missing something ?

Let me know :)

Regards,

**Comment by SvenDowideit** [comment]
```
sven@rosbuild:~/os$ cat cloud-config.yml 
#cloud-config
rancher:
  modules: [btrfs]
```

works for me.

adding the same to my `os-config.yml` and rebuilding _also_ works (tested with 1.0.1/2

but this only means the btrfs kernel module is loaded - and so assumes that you then format a partition using btrfs, and tell Docker to use it.

**Comment by xinity** [comment]
thanks a lot @SvenDowideit 

last question:
"how can i built a rancher iso that uses then btrfs as filesystem for the docker service ? (not system-docker) "

any tips/clues about that ?

**Comment by SvenDowideit** [comment]
depends - do you want to do a `ros install`, or just use a btrfs state partition

the short answer is - do something similar to what we document for zfs - but use btrfs.

the long answer will take some time, as i'm fixing other things atm.

**Comment by xinity** [comment]
hi @SvenDowideit ,

will try the short answer and let you know how it goes :)

**Comment by 20design** [comment]
Hey @xinity! Did you manage to build the ISO? Can you post you script?
