### ISSUE TITLE
Rotate docker/system-docker daemon log

### ISSUE THREAD

**Issue by ketchoop** [rancher/os#1879]
I think it would be great if it is rotated by logratate out of the box.

**Comment by SvenDowideit** [comment]
I agree :/

**Comment by SvenDowideit** [comment]
see also #1886 and #1885

**Comment by SvenDowideit** [comment]
v1.1.0 __maybe__

**Comment by SvenDowideit** [comment]
implemented by @drakenator in v1.1.0 see #1966
