### ISSUE TITLE
Failed to resize /dev/sda: exec: "partprobe": executable file not found in $PATH

### ISSUE THREAD

**Issue by ket4yii** [rancher/os#1884]
**RancherOS Version: (ros os version)**

Linux 4.9.24-rancher #1 x86_64. Debian console.

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
Parallels VM

Happens after ```cloud-init-execute -pre-console -console```. It seems that it's really not in PATH, ```which``` doesn't show anything.

**Comment by SvenDowideit** [comment]
OH. mmm

**Comment by SvenDowideit** [comment]
the resize is run before the console is started - its not using the console container's filesystem, but that from os-base - which from what i've seem so far, does have it.

I'm still looking into it...

**Comment by ket4yii** [comment]
> the resize is run before the console is started - its not using the console container's filesystem
Yeah and resize works fine, when machine was rebooted, that is, it works out of console environment . But it's strange to see this kind of error in console environment.

**Comment by SvenDowideit** [comment]
oh mumble - so the bug is only a spurious log message. cool. I discovered a pile of other things under that log, I guess I'll clean them off too.

**Comment by SvenDowideit** [comment]
@ket4yii I can't manage to get my setup to throw that error message.

if you see it happening again, can you paste ~30 lines before and after it?

**Comment by ket4yii** [comment]
@SvenDowideit huh, I think I found out what happened. I have cloud-config that can be dynamically changed by ansible. And lately, I've added resize section in it. So this is the reason why I had this error. It doesn't show me this message after reboot. I think we can close this issue:)
