### ISSUE TITLE
Logrotate doesn't rotate logs(err with post script)

### ISSUE THREAD

**Issue by ketchoop** [rancher/os#1885]
**RancherOS Version: (ros os version)**

Linux 4.9.24-rancher #1 x86_64. Debian console.

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
Parallels VM

My syslog file has logs from 18th of March and there are no rotated log files.I tried to rotate it manually, but it didn't work. Running in *verbose* mode show me this message.

```
running postrotate script
killall: syslogd: no process killed
error: error running shared postrotate script for '/var/log/messages /var/log/auth.log /var/log/user.log /var/log/docker.log /var/log/syslog '
```

And it's really awful, because logrotate save itself state and tells you that logs were rotated, but it hasn't done anything.

**Comment by ket4yii** [comment]
@SvenDowideit It seems that you changed syslog to rsyslog, but forgot change postrotate script

**Comment by ket4yii** [comment]
I'm not going to create new issue about it, but it seems that crond in syslog container isn't running. So, logrotate won't work, anyway.

**Comment by SvenDowideit** [comment]
I don't think we ever ran crond - but I could be wrong - @joshwget ?

**Comment by ket4yii** [comment]
> I don't think we ever ran crond

@SvenDowideit So, logrotate in syslog container useless, because it doesn't run :) Except, of course, manual running.

**Comment by ketchoop** [comment]
@SvenDowideit I think this issue is resolved by @drakenator. Thank you guys for your work.
