### ISSUE TITLE
Windows 10 Hyper-V kernel panic

### ISSUE THREAD

**Issue by nponeccop** [rancher/os#1888]
**RancherOS Version: (ros os version)** 

v1.0.1 - Docker 17.03.1-ce - Linux 4.9.24

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**

Hyper-V from Windows 10. Gen 1 VM (as Gen 2 requires EFI), boot from CD

I get a kernel panic during the boot, but it seems an upstream bug in Linux kernel as other OSes crash too.

**Comment by SvenDowideit** [comment]
@nponeccop is there any chance you can try the v1.0.2-rc3 release? it uses linux 4.9.30. I'm working on improving VMware support atm, but I have a plan to free up my Windows box so I can get to Hyper-V too.

**Comment by nponeccop** [comment]
It's the same crash with v1.0.2-rc3 / 4.9.30

**Comment by SvenDowideit** [comment]
bummer.

**Comment by nponeccop** [comment]
I tested few random kernel versions. Unfortunately I only have a 32-bit virtual system to check. So far only 3.14.2 and 3.18.34 worked. I confirmed with my friend that it's not only me.

4.0.7 which worked in the past doesn't work now. So it seems to be a regression in Hyper-V caused by windows updates. It's not even clear where to submit upstream bug reports.

**Comment by nponeccop** [comment]
FYI 4.11.6 kernel works with Hyper-V now.

**Comment by SvenDowideit** [comment]
@nponeccop that's useful info - I don't plan to move off LTS for 1.1 (or 1.2), but I do want to change the way we build rootfs's to make the kernels swappable independently of the OS release.

I wonder if we can pinch a patchset from one of the distros.

**Comment by nponeccop** [comment]
Good news. 4.9.44 kernel (current latest LTS) works under Hyper-V as a Generation 2 guest, which is EFI-only.

So closing #844 will work as a workaround for this bug.

**Comment by nponeccop** [comment]
More good news: current Debian kernel `4.9.30-2+deb9u3` works as a Generation 1 guest in BIOS mode. So we can try building a kernel with Debian config/patches to test if RancherOS works on Hyper-V.

**Comment by SvenDowideit** [comment]
excellent :) now what i really need is a spare machine i don't use for other work to run Windows and Hyper-v :/

**Comment by beatcracker** [comment]
So currently, there is no way to boot `v1.1.0` in latest Hyper-V at all? You either get a kernel panic in Gen1 or EFI boot error in Gen2.

Hope this will get fixed soon :hurtrealbad:.

**Comment by nponeccop** [comment]
BTW the Microsoft contributors to Linux Hyper-V support are very friendly. But they use Debian and build the kernel with default config from Debian to see if it is broken or not. So far I haven't had any time to build their suggested kernel as I couldn't have some 10GBs of disk space lol (not TBs).

So if anybody is willing to build the test kernel the way Hyper-V guys want it - I can send their instructions. You only need to be able to clean-install Debian somewhere, then I can use your kernel to test on Hyper-V.

**Comment by nponeccop** [comment]
Note that even with 1GB it doesn't kernel panic anymore, but displays another error.

It boots to shell prompt with 1280 MB of ram and displays an error with 1024. 

Also, it attempts to start hyperv-vm-tools but fails with error 404. Can I load it manually?

Finally, hyperv_fb module by default makes console resolution high enough to be unusable with 1366x768 screen resolution because of constant need to scroll. This can be changed by supplying `video=hyperv_fb:1024x576` kernel command line option. I wonder if there's a way to make it permanent without affecting other users.

So at least we should document the RAM and resolution issues to make experimentation easier.

**Comment by olljanat** [comment]
You can make kernel parameters as permanent by using --append parameter on install command like this:
```
sudo ros install -d /dev/sda --append "video=hyperv_fb:1024x576"
```
Look: https://rancher.com/docs/os/v1.0/en/configuration/adding-kernel-parameters/

But probably it is better idea to use SSH than console.

What comes to that 404 on start of hyperv-vm-tools I did not see that after install to disk but I'm also not sure how to check if it has started correctly?

**Comment by nponeccop** [comment]
It is probably my particular setup - the DNS given by DHCP was invalid. So it's rather an ask for help on how to retry a failed service than a new bug report.

It's rather impossible to work and fix things in console. And SSH is up only late in the boot process, and you need to know the IP. So a console is indispensable in this case. And I get really mad with having to scroll after every command or not seeing top and bottom of `vi` at the same time. And just few lines of documentation will make life much easier.

Note that in case of Hyper-V it's possible to connect to a serial port using PuTTY, and you get a decent terminal (up to xterm if your getty is capable to provide it). It's a way better console than console, but again it doesn't always work so the setup is not worth it (you either get console or ssh).

**Comment by Andy2244** [comment]
I also hit this problem on hyper-v, with the latest `v1.1.1-rc1` iso, rancheros wont boot in Gen2 and Gen1 still throws a kernel panic if you use memory lower than 1100 MB, so 1024 MB will still get you a kernel panic.

PS: Should the rc1 not also have docker 17.09.0-ce/17.09.1-ce in the engine list, since it was build after those versions made it to stable?

**Comment by niusmallnan** [comment]
We have supported hyper-v after 1.5.0.
https://rancher.com/docs/os/v1.x/en/installation/running-rancheros/workstation/docker-machine/
