### ISSUE TITLE
rancheros is supposed to be 20MB, how come when i upgrade, the image is so large?

### ISSUE THREAD

**Issue by deniseschannon** [rancher/os#189]
Whenever I upgrade, the image is definitely more than 20 MB.

**Comment by JemiloII** [comment]
if you look at the releases it shows 22 mb, I wouldn't be surprised. It's still small.

**Comment by deniseschannon** [comment]
Closing in favor of https://github.com/rancher/os/issues/658. Essentially the image is larger than expected.
