### ISSUE TITLE
When installing RancherOS to disk, kernel can't see the disk

### ISSUE THREAD

**Issue by nega0** [rancher/os#1902]
**RancherOS Version: (v1.0.2 / latest)**

**Where are you running RancherOS? (baremetal)**

After booting RancherOS via iPXE (latest) or from ISO installed to USB drive (v1.0.2) the hard disk isn't detected. In fact, `dmesg | grep scsi` shows nothing, when I would expect to see info related to the installed SATA disk. 

This obviously precludes installing RancherOS to disk.

**Comment by zimme** [comment]
Maybe you need to use the kernel-extras service to get the extra modules.

**Comment by SvenDowideit** [comment]
@nega0 I'm going to close this - feel free to reopen with more detailed information about your hardware
