### ISSUE TITLE
ros os upgrade from 1.0.0 to 1.0.1 or 1.0.2 not working

### ISSUE THREAD

**Issue by ellerbrock** [rancher/os#1906]
Hi there,

i have on a bunch of servers running rancher os version 1.0.0.
When i execute as root user `ros os upgrade` and make a restart it still hangs in version 1.0.0 but won't start to the latest upgrade. Is this a known problem and is there a way how i can fix that?

```
ros os upgrade
Upgrading to rancher/os:v1.0.2
Continue [y/N]: y
Pulling os-upgrade (rancher/os:v1.0.2)...
v1.0.2: Pulling from rancher/os
2aecc7e1714b: Pull complete
a305583ff6c0: Pull complete
930b09681b7b: Pull complete
ae10088f10a1: Pull complete
afb8c1df0a08: Pull complete
ddffc59ed144: Pull complete
0f69bcff4eb0: Pull complete
9493ebcec78d: Pull complete
0c9dba8fba8a: Pull complete
69453c56433f: Pull complete
Digest: sha256:f6befeb23d7240eb65150fe7472e6ac050cc66baa382b1d2e764f7523ddcf52a
Status: Downloaded newer image for rancher/os:v1.0.2
os-upgrade_1 | Installing from :v1.0.2
Continue with reboot [y/N]: y
> INFO[0083] Rebooting
```

```
ros os list
rancher/os:v1.0.2 local latest
rancher/os:v1.0.1 local available
rancher/os:v1.0.0 remote available running
rancher/os:v0.9.2 remote available
rancher/os:v0.9.1 remote available
rancher/os:v0.9.0 remote available
rancher/os:v0.8.1 remote available
rancher/os:v0.8.0 remote available
rancher/os:v0.7.1 remote available
rancher/os:v0.7.0 remote available
rancher/os:v0.6.1 remote available
rancher/os:v0.6.0 remote available
rancher/os:v0.5.0 remote available
rancher/os:v0.4.5 remote available
rancher/os:v0.4.4 remote available
rancher/os:v0.4.3 remote available
rancher/os:v0.4.2 remote available
rancher/os:v0.4.1 remote available
rancher/os:v0.4.0 remote available
```

```
ros os version
v1.0.0
```

And thanks so much for rancher and rancheros, really good stuff you guys are doing there!

Cheers Maik

**Comment by SvenDowideit** [comment]
mmm, no, that's not normal.

do you mean that you run the upgrade as above, and then the reboot doesn't really happen? (there is a problem with vmware acpi not actually rebooting)

What happens when you use an external power cycle on an "upgraded" system?

**Comment by ellerbrock** [comment]
moved to coreos

**Comment by bassrock** [comment]
@ellerbrock Where was this moved to coreos. I am having the same issue.

**Comment by vincent99** [comment]
@bassrock He means that **he** switched to coreos, and therefore doesn't care about this issue anymore.

**Comment by ellerbrock** [comment]
@vincent99 thanks for clarifying and sorry if i did't wrote that clear enought.
anyway i still like rancheros a lot and hope later on when it gets more stable come somehow back to it in the future. for that all the best with your project!

cheers maik

**Comment by bassrock** [comment]
Ok I am still experiencing this issue however. I have it running on iohyve on top of FreeNAS 11.

**Comment by SvenDowideit** [comment]
@bassrock if you can start a new issue with detailed information - including a copy of the cmdline you're running and the resulting output - after setting `sudo ros config set rancher.debug true` that may help us track this down.
