### ISSUE TITLE
Support for USB V/FAT/16/32 for Live CD Baremetal Installs

### ISSUE THREAD

**Issue by k00p** [rancher/os#1910]
In order to run a baremetal install, it would be useful to have the ability to mount USB flash storage easily in order to grab cloud-configs and other necessary installation bits and pieces. It may currently be possible to mount ext2/3/4 formatted drives (still working on verifying that it is possible), but around our shop at least, most people keep their drives in a FAT-esque format for the widest cross-platform useability.

**RancherOS Version: (ros os version)**

0.8

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**

baremetal

**Comment by SvenDowideit** [comment]
@k00p do you mean like https://github.com/rancher/os/pull/1898 ?

**Comment by k00p** [comment]
Yes. Closing this in favor of that. Thank you.
