### ISSUE TITLE
ssh-dss not in PubkeyAcceptedKeyTypes [preauth]

### ISSUE THREAD

**Issue by hdep** [rancher/os#1936]
**RancherOS Version: (ros os version)**
v1.0.2
**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
on a vm vmware.

I installed rancheros with cloud-config.yml file setting up public key like this : 

```
ssh_authorized_keys:
- ssh-dss AAAAB3NzaC1kc3MAAACBAOk1LYhSfTktkulFBxTKjzjMA4VogybtmCJTRu157Htcjtk+15xvOaLONEkkwG5k/mqgWzM7e/h2c+cv1tR5cwGTYMRI0c79ziIm9SDAMGrsUYtbknrn+f7xYwZuospPIvqISaF0NunkClTmOsmyuIj28AzSEOJn7qLA7wEcYM/FAAAAFQCNcGCzxSRyrrpg5umHc+UxYFxzjwAAAIB7ejLKb00IvrA5nuVYJKIhsIUVX/WV83CT9zgUJJvi+iLl3CmepFy51p+SKmdzRE3Yc5o6NZXv7/60V526eR5pE3mYUN3zaam7os0weLybS0UqV6xsQSgab60zlUnJQiiHfjZHMeoNIYZJ7dVwQ7JXgqHPOrzKUf65Q2zsXG9XzgAAAIB3FGgqYqrPGq1b1NyFBbCMM8x9G/goPsOndtA4KDVrBqXaogopkEHqPdeyaiEd4IBaTUeKPYLS+i4g5IvCFHqpCMcKiOtWzUEnrd3L5FkYpTPPX8yYJ+cwEQ44mdSM3/B8C98X13GFsR6seR0zS7gE8bUTH7kcAQCHbBmwF4riQA== root@admin

```

after reboot I wasn't able to log on in the system.

Seems that ssh-dss key is not allowed : according to the logs : 

`Jun 22 14:40:41 SERVER_NAME sshd[1097]: userauth_pubkey: key type ssh-dss not in PubkeyAcceptedKeyTypes [preauth]`

RSA keys are allowed. 
Allowing dss key would be great or at least updating the documentation (I didn't found this information)

**Comment by niusmallnan** [comment]
OpenSSH 7.0 and greater similarly disable the ssh-dss (DSA) public key algorithm. It too is weak and we recommend against its use.
check here: 
1. https://security.stackexchange.com/questions/5096/rsa-vs-dsa-for-ssh-authentication-keys
2. http://www.openssh.com/legacy.html

I will update the doc.
