### ISSUE TITLE
Failed to import image: Error response from daemon: exec: "xz": executable file not found in $PATH

### ISSUE THREAD

**Issue by nhi-vanye** [rancher/os#1939]
**RancherOS Version: (ros os version)**

1.0.1

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**

bare metal

I have a bare-metal build farm (cattle cluster) that is using gitlab-ci runners.

The runner is failing to load the initial helper image because xz isn't available to build the image

When I pulled the image explicitly it worked okay

I opened an issue with gitlab because it took me a while to work out what image was needed to be pulled.

https://gitlab.com/gitlab-org/gitlab-ci-multi-runner/issues/2533

Can we get xz command made available ?

**Comment by albertdb** [comment]
Would be nice to have.

**Comment by SvenDowideit** [comment]
it feels a little wrong to need to add things to a base micro distro to allow something that runs in containers to work - When the stack clash work and post 1.0.3 release catchup calms down, I'll look into it - I need to do some serious playing with GitLab anyway :)

**Comment by andruwa13** [comment]
https://gitlab.com/gitlab-org/gitlab-runner/issues/2533

**Comment by niusmallnan** [comment]
To switch to ubuntu console is a good way.

Can we close this issue, or what I need to do?

**Comment by niusmallnan** [comment]
We have `xz` command.
```
[root@ros-v1-1-2 docker]# ros -v
ros version v1.1.2

[root@ros-v1-1-2 docker]# xz -h
Usage: xz [OPTION]... [FILE]...
Compress or decompress FILEs in the .xz format.

  -z, --compress      force compression
  -d, --decompress    force decompression
....
....
```

Close this issue, if you still have any questions, please let me know.
