### ISSUE TITLE
rancherctl os upgrade: If booted on ISO, better message for failure.

### ISSUE THREAD

**Issue by deniseschannon** [rancher/os#194]
v0.3.0-rc3

Currently, if you attempted to downgrade from v0.3.0-rc3 when booted from an iso, an error is thrown as we haven't installed to disk. It'd be better if:

1. We checked to see that we have installed to disk before attempting to download image, so we could display a message immediately. 

2.  Provide a better error message than this:
```
+ mount -L RANCHER_STATE /mnt/new_img
mount: can't find LABEL = "RANCHER_STATE"
ERRO[0078] Upgrade failed
```

**Comment by deniseschannon** [comment]
stop echoing. remove `set - x` from scrips. @cloudnautique

**Comment by miztiik** [comment]
Isn't this somewhat related to this issue https://github.com/rancher/os/issues/190 ?
