### ISSUE TITLE
Raspberry Pi image created on SD is too small for reboot

### ISSUE THREAD

**Issue by mitchese** [rancher/os#1942]
**RancherOS Version: (ros os version)**
1.0.2

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
baremetal Raspberry Pi 3

Steps to re-produce: 
1. Download https://releases.rancher.com/os/v1.0.2/rancheros-raspberry-pi64.zip and write to SD Card
2. Boot from SD, wait until ROS is started (success)
3. Reboot
4. During bootup, it will stall at unpacking and stall at "Loading images from /usr/share/ros/images.tar" -with an error "FATAL: failed loading images from /usr/share/ros/images.tar: Error response from daemon: untar re-exec error: Non-zero exit code: 1: output: write /<hash>/layer.tar: no space left on device" 

Creating a second partition for the docker images (as described on http://rancher.com/docs/os/running-rancheros/server/raspberry-pi/) also does not change the outcome. At step 5 (reboot to reload partition table), the same issue happens. 

Workaround (only tested on Linux): 
1. Download the image and write to SD Card; do not eject the SD Card
2. use fdisk to remove the second (500Mb) partition
3. Create a new partition, ensure it starts on the same starting block, and ends at the last block
4. *do NOT erase the ext4 headers* 
5. Run e2fsck & resize2fs

This will create a single huge partition the size of the SD card. A complete example is available [here](https://gist.github.com/mitchese/7a3373132f94fc946b1cbeb2b04e7818) - important is that the original partition started at block 53248, and the newly created partition starts on the same block

**Comment by klud1** [comment]
Only way to troubleshoot fow now, afaik, is to resize rootfs partition to its fullest with parted/gparted. that's what i did, have 3 rpis running ros, 2 on arm and 1 on arm64, resized and no problems!

**Comment by mitchese** [comment]
That's exactly what I'm doing in the workaround. See my PR https://github.com/rancher/os/pull/1943 which I'm now using

**Comment by klud1** [comment]
Ya, I found the PR right after commenting this issue, nice job! Although on first tests (before doing the full rootfs resizing stuff) I rezised the rootfs to 1 and then 1.5 GBs and been able to (re)boot without problems.

**Comment by mitchese** [comment]
Yes, I think it only needs to be slightly larger than it is. Version 0.8.0 works just fine, and some slight growth between 0.8.0 and 1.0.2 has caused this issue. I took a guess at 2G just to give room for the future; I don't think there are many using cards <2G

**Comment by SvenDowideit** [comment]
yup - thank you! I only tried increasing it to ~800M, and that wasn't enough, so I punted on trying other sizes :/
