### ISSUE TITLE
console list command isn't showing status properly in Virtual box setup

### ISSUE THREAD

**Issue by tfiduccia** [rancher/os#1947]
**RancherOS Version: (ros os version)** v1.0.3-rc1

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)** VirtualBox

**Steps:**
1.  Setup v1.0.3-rc1 in VirtualBox
2.  Run sudo ros console list
3.  Run sudo ros console enable ubuntu
4.  Run sudo ros console list

**Results:**  All console show disabled.  Default should be 'current' and ubuntu should be 'enabled'.  This is only happening with my VirtualBox install.  It's working fine in my EC2 install.
```
[docker@tanivbtest1 ~]$ sudo ros console list         
disabled alpine
disabled centos
disabled debian
disabled default
disabled fedora
disabled ubuntu
```

**Comment by SvenDowideit** [comment]
did this happen a second time? it doesn't sound like something that could be due to virtualbox.

looks like the code detects "enabled" by looking for at the contents of a file `run/console` - can you check if that's there (I'm guessing not)

and Can you post your `docker ps -a` output please?

**Comment by SvenDowideit** [comment]
I've reproduced it - very odd.

I'm going to release 1.0.3 anyway, as the stack clash cvs much more important, and the I'll go figure out what is going on later.

**Comment by tfiduccia** [comment]
@SvenDowideit - this happens every time.  I've reproduce it and it's not inconsistent at all.

**Comment by SvenDowideit** [comment]
looks like I'll be fixing this as part of #1931
