### ISSUE TITLE
and yet, the password persists?

### ISSUE THREAD

**Issue by bortels** [rancher/os#1955]
**RancherOS Version: (ros os version)**
v1.0.3

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**

running under vmware fusion 8.5.8, installed to disk. 

As you may know, vmware fusion support for cloud-init is ugly, and cut-and-paste to the console fails; to save time, I generally set a password with a new OS install (in this case using --append when I install the OS), then using it go in via SSH and reconfigure things. I do so, and all is good, except:

[root@rancher ~]# ros config export
EXTRA_CMDLINE: /init
rancher:
  environment:
    EXTRA_CMDLINE: /init
  password: password-changed-for-this-report

I cannot for the life of me figure out where that "password:" entry - in plaintext! - is saved. It is *not* in the cloud-config files, so far as I can tell. I can do "ros config set rancher.password something_else" - and that shows up in the cloud-config - but after a reboot, the original password is still there. And yes - you can log in with it.

I know, "don't do that" - which means I need to work out how to build a floppy image (ugh). But - there's got to be a way to erase that password, right?

**Comment by SvenDowideit** [comment]
its stored in the host filesystem, in /boot/global.cfg. In https://github.com/rancher/os/pull/1957/files#diff-098bcdb6b21f32c1ebe688ce2a8600c1R156 I'm adding `ros config syslinux` to launch `vi` to make it easier to edit it - but for now, I use `sudo system-docker run --rm -it -v /:/host alpine vi /host/boot/global.cfg
