### ISSUE TITLE
reboot doesn't work with read-only filesystem

### ISSUE THREAD

**Issue by themotu** [rancher/os#1959]
**RancherOS Version: (ros os version)**
1.0.2 and 1.0.3 (older ones also)

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
cloud machine

When my cloud instances have disk issues they go into read-only mode. When the disk is in read-only mode you cannot restart from session.

```
sudo reboot
FATA[0000] Error response from daemon: chown /var/lib/system-docker/overlay: read-only file system
```

**Comment by SvenDowideit** [comment]
I'm adding a `sudo reboot --force` that should allow you to work around this initially.
