### ISSUE TITLE
Error launching AWS AMI on Dedicated instance

### ISSUE THREAD

**Issue by aschrijver** [rancher/os#1964]
**RancherOS Version:**

RancherOS v1.0.3

**AWS instance launch fails**

When I try to launch a `t2.micro` on AWS Frankfurt region (eu-central-1) with the AMI provided for that region ([ami-8c52f4e3](https://eu-central-1.console.aws.amazon.com/ec2/home?region=eu-central-1#launchInstanceWizard:ami=ami-8c52f4e3) link in the README), and I only set Tenancy to 'Dedicated', then launch will fail with following error in the 'Initializing launches' step:

```
The requested configuration is currently not supported. Please check the documentation for supported configurations.
```

Is this a bug or is this not the supposed method for creating a dedicated instance?

**Comment by superseb** [comment]
You can create dedicated instances, but there are special requirements (only certain instances for instance). See here https://aws.amazon.com/ec2/purchasing-options/dedicated-instances/. Cheapest instance would be `c4.large` I think. Let me know if this doesn't work for you.

**Comment by aschrijver** [comment]
Thanks. That is strange! I just bought 2 dedicated instances from Frankfurt region, a micro and a medium one for $400+ bucks.
In the control panel it says Scope = Region and Zone = (empty). There were not any warning texts or anything when I bought them.

**Comment by vincent99** [comment]
Sounds like you're confusing *reserved* (pre-paying for a regular shared instance type to get a discount) with *dedicated* (physical hardware not shared with any other customer).  You can only get dedicated on larger instance routes because they don't have physical 1GB machines, they're many smaller VMs on a larger server.

**Comment by aschrijver** [comment]
Ah, oops, Yes, this is what I meant. Thanks! I will edit the post.

**Comment by aschrijver** [comment]
So the Reserved instance needs not be set anywhere. This is just automatically matched with a running instance of similar size to get the low tariffs?
