### ISSUE TITLE
"ros install" hanging when using virtual serial port?

### ISSUE THREAD

**Issue by candlerb** [rancher/os#1972]
**RancherOS Version: (ros os version)** v1.0.2

**Where are you running RancherOS?** kvm, controlled by ganeti

Created the instance and started it with ISO attached:

~~~
gnt-instance add -t drbd -n nuc1:nuc2 -s 16G -B minmem=1G,maxmem=2G,vcpus=2 \
  -o noop --no-start --no-wait-for-sync docker1.home.example.net
gnt-instance start -H boot_order=cdrom,cdrom_image_path=/iso/rancheros.iso docker1.home.example.net
~~~

Decided to connect to it using virtual serial port, since this was easier than using VNC console:

~~~
gnt-instance console docker1
~~~

This is fine.  I immediately get a logged-in session for the rancher user.

I use vi to create a cloud-config file:

~~~
[rancher@rancher ~]$ cat cloud-config.yml
#cloud-config
hostname: docker1.home.example.net
ssh_authorized_keys:
  - ssh-rsa <snip> brian@Brians-MacBook-Air.local
rancher:
  network:
    interfaces:
      eth0:
        address: 10.12.255.91/24
        gateway: 10.12.255.1
        mtu: 1500
        dhcp: false
~~~

And I try to do `ros install`:

~~~
[rancher@rancher ~]$ ls /dev/vda
/dev/vda
[rancher@rancher ~]$ sudo ros install -c cloud-config.yml -d /dev/vda
> INFO[0000] No install type specified...defaulting to generic
Installing from rancher/os:v1.0.2
Continue [y/N]: y
~~~

But after typing "y" and hitting enter, it simply hangs. Nothing else happens.  I can ctrl-C out.  Tried several times.

BUT: if I connect to the VNC console, and issue the exact same command there, the installation runs successfully.

**Comment by SvenDowideit** [comment]
#1931 has some changes that will help with this for v1.1.0

**Comment by candlerb** [comment]
Thanks. Now I see this PR is a dupe of #1234 (except the OP was using a real physical serial port rather than a qemu serial port)
