### ISSUE TITLE
ZFS service should make arcstat.py available in console

### ISSUE THREAD

**Issue by janeczku** [rancher/os#1976]
**RancherOS Version: (ros os version)**
v1.0.2

Currently it is required to perform this steps in order to run [arcstat.py command](https://github.com/zfsonlinux/zfs/tree/master/cmd/arcstat):

```
$ exec system-docker run -it --rm --privileged --pid host --net host --ipc host -v /mnt:/mnt:shared -v /media:/media:shared -v /dev:/host/dev -v /run:/run zfs-tools
$ apk --update add python
$ /usr/local/bin/arcstat.py -f read,l2read,hit%,l2hit%,mh%,c,arcsz,l2size
```

**Comment by SvenDowideit** [comment]
see https://github.com/rancher/os-services/compare/master...SvenDowideit:add-python-to-zfs-tools-image?expand=1
