### ISSUE TITLE
zdb command returns error: cannot open '/etc/zfs/zpool.cache'

### ISSUE THREAD

**Issue by janeczku** [rancher/os#1977]
**RancherOS Version: (ros os version)**
v1.0.2

1. Setup ZFS according to http://rancher.com/docs/os/storage/using-zfs/
2. Run `sudo zdb`

Result:
> cannot open '/etc/zfs/zpool.cache': No such file or directory

**Comment by janeczku** [comment]
Works when you specify the `-e (pool is exported/destroyed/has altroot/not in a cachefile)` option though:

```
storage-benchmark-006:$ sudo zdb -e -d tank
Dataset mos [META], ID 0, cr_txg 4, 216K, 40 objects
Dataset tank [ZPL], ID 21, cr_txg 1, 96.0K, 6 objects
Verified large_blocks feature refcount is correct (0)
```

See https://github.com/zfsonlinux/zfs/issues/4598

**Comment by janeczku** [comment]
https://github.com/rancher/rancher.github.io/pull/835

**Comment by janeczku** [comment]
https://github.com/rancher/rancher.github.io/pull/835

**Comment by SvenDowideit** [comment]
and merged back into this repo too in #1983

awesome, merci :)

**Comment by tfiduccia** [comment]
**Version:** v1.1.0-rc1 AMI - ami-9e9eb0fe

**Comments:** ran through all the steps and got zfs to setup properly.  But when I ran the ```sudo zdb``` command it still returned:
```
[rancher@ip-172-31-31-83 ~]$ sudo zdb
cannot open '/etc/zfs/zpool.cache': No such file or directory
```

So failed?

**Comment by superseb** [comment]
http://rancher.com/docs/os/storage/using-zfs/#using-the-zfs-debugger-utility

```
The zdb command may be used to display information about ZFS pools useful to diagnose failures and gather statistics. By default the utility tries to load pool configurations from /etc/zfs/zpool.cache. Since the RancherOS ZFS service does not make use of the ZFS cache file and instead detects pools by inspecting devices, the zdb utility has to be invoked with the -e flag.

E.g. to show the configuration for the pool zpool_1 you may run the following command:

$ sudo zdb -e -C zpool_1
```

**Comment by tfiduccia** [comment]
So basically this was a document change.  I checked the link and the docs are changed so I'm closing this issue.

Version - v1.1.0
Verified fixed
