### ISSUE TITLE
[SEC] Implement Checksums

### ISSUE THREAD

**Issue by guusverbeek** [rancher/os#1982]
Hi All,

For example on https://github.com/rancher/os-services/blob/master/images/20-iscsi/build.sh

You download open-iscsi using 

`VERSION="0.97"`
  | curl -sL https://github.com/open-iscsi/open-isns/archive/v${VERSION}.tar.gz > open-isns${VERSION}.tar.gz
  | tar zxvf open-isns${VERSION}.tar.gz
  | rm -rf /dist/isns
  | mv open-isns-${VERSION}/ `/dist/isns/`
 
This poses a risk as everyone could potentially pose as https://github.com/*

By implementing a checksum we can be more certain that the binary that will compile is actually the binary that we want to compile.

Best Regards,

Guus Verbeek

**Comment by vincent99** [comment]
Checksums are fine but solve the problem of open-iscsi being compromised and having the `${VERSION}.tar.gz`artifact be replaced.

If github.com is being man-in-the-middled on your build server with a valid SSL cert you have far bigger problems, and no reason to think the checksum in the copy of this repo you downloaded from github too is legitimate.

**Comment by guusverbeek** [comment]
Wouldn't it be better to implement a checksum check (ideally verified with multiple hashes to check to prevent a hash collision attack)?

It's true that if github.com is being man-in-the-middled on your build server with a valid SSL cert that you have far bigger problems. But this shouldn't be an excuse not to implement such checks. It might be even another way of figuring out as an administrator that you are currently being MitM'ed.

As the build server is a very critical component in the rancher process I believe it would be wise to add some extra checks to ensure security (besides, the version numbers seem to be hardcoded, so there wouldn't be a lot of hashes to be verified).

**Comment by vincent99** [comment]
I'm not saying they shouldn't be added, but that they do not address the problem you describe.  This source is in github too, so if github (or communication with it) is compromised you would just have it return an altered build script that expects the hash of your altered tarball.

**Comment by guusverbeek** [comment]
I agree, at least on the server level it depends on your trust for the certificates that are being included on Rancher OS.
