### ISSUE TITLE
[os-images] 17.06 ?

### ISSUE THREAD

**Issue by prologic** [rancher/os#1985]
I can see the 17.06 tag upstream in the hub and I see and the most recent commit from @SvenDowideit (https://github.com/rancher/os-services/commit/9c37e955a688de5adeaac31de1d9598e6d174ba7) seems to pull in some stuff for 17.06

However I cannot see 17.06 to upgrade to

```#!bash
[rancher@dm1 ~]$ sudo ros engine list | tail -n 3
disabled docker-17.03.1-ce
disabled docker-17.04.0-ce
current  docker-17.05.0-ce
[rancher@dm1 ~]$
```

Is this because of a missing 17.06 config like https://github.com/rancher/os-services/blob/master/d/docker-17.05.0-ce.yml ?

**Comment by SvenDowideit** [comment]
turns out there's a bug in the find docker/dockerd path finding code, which falls over. I'll be fixing that for 1.1.0 and 1.0.4

**Comment by prologic** [comment]
Perfect 👍

**Comment by SvenDowideit** [comment]
fixed for 1.1.0 in #2022, and backported to v1.0.4

**Comment by prologic** [comment]
Sweeet! Thank you!!!!!!!!


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by prologic** [comment]
Will this become available to upgrade to on existing nodes btw?

```#!bash
[rancher@dm5 ~]$ sudo ros os list | head
rancher/os:v1.0.3 local latest running
rancher/os:v1.0.2 remote available
rancher/os:v1.0.1 remote available
```

**Comment by SvenDowideit** [comment]
er, yes - `ros os list` will only list full release - right now, you can `ros os upgrade -i rancher/os:v1.0.4-rc1` ... I'm still putting it through validation atm - assuming it continues to go well, the full v1.0.4 will be this week. v1.1.0 hasn't been quite as nice to me.

**Comment by prologic** [comment]
TIL: Didn't know ros os update could install non-full-releases :D Thanks!


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au
