### ISSUE TITLE
RancherOS RAW image incompatible with GCE

### ISSUE THREAD

**Issue by stevenmunro** [rancher/os#1998]
I'm trying to add RancherOS to GCE (http://rancher.com/docs/os/running-rancheros/cloud/gce/) but the RAW image file inside rancheros-v1.0.3.tar.gz is 10.49GB.  According to Google (https://cloud.google.com/compute/docs/images/import-existing-image#publishingimage) it must have a size in an increment of 1GB.

I waited for more than half hour waiting for Google to make the image available, then it gave up and removed it from the list.

**Comment by SvenDowideit** [comment]
@cloudnautique ? this sounds surprising, as we've been using RancherOS on gce for quite a lot of releases.

**Comment by stevenmunro** [comment]
I have tried this over and over again. I have even tried using your v1.0.0 release.

- I am uploading the tar.gz to a 'bucket'
- Then Compute Engine -> Images -> Create Image
- I give it a name, select Source as cloud storage file, and select the file from the bucket
- Create.

Go back to Images, I can see the image at the top of the list, with the rotating blue circle progress indicator. In the 'Size' column it just says 'GB'

It will stay like that for ages, until it gives up and removes itself from the list.

**Comment by SvenDowideit** [comment]
I've just used the gcloud command to make an image. I presume you don't get to make one from our bucket, but idk.

```
sven@y260:~/releases$ export VERSION=v1.0.3
sven@y260:~/releases$ export SHORTVERSION=$(echo $VERSION | sed 's/[.]//g')sven@y260:~/releases$ gcloud compute images create rancheros-$SHORTVERSION --source-uri gs://releases.rancher.com/os/$VERSION/rancheros-$VERSION.tar.gz
```

**Comment by SvenDowideit** [comment]
In building and testing v1.0.4, I just did the following:

```
sven@y260:~/releases$ gcloud compute images create rancheros-sven-delete-v104 --source-uri gs://releases.rancher.com/os/v1.0.4/rancheros-v1.0.4.tar.gz
Created [https://www.googleapis.com/compute/v1/projects/test/global/images/rancheros-sven-delete-v104].
NAME                        PROJECT          FAMILY  DEPRECATED  STATUS
rancheros-sven-delete-v104  test                      READY
sven@y260:~/releases$ gcloud compute images create rancheros-sven-delete-v103 --source-uri gs://releases.rancher.com/os/v1.0.3/rancheros-v1.0.3.tar.gz
Created [https://www.googleapis.com/compute/v1/projects/test/global/images/rancheros-sven-delete-v103].
NAME                        PROJECT          FAMILY  DEPRECATED  STATUS
rancheros-sven-delete-v103  test                      READY
```

and then I use docker-machine to create the vm.

@stevenmunro can you please confirm that this helps / not?

**Comment by niusmallnan** [comment]
any update？

Close it.
If you still have this problem, please reopen it and let me know.
