### ISSUE TITLE
Containers created via "system-docker run" are not restarted on boot

### ISSUE THREAD

**Issue by janeczku** [rancher/os#2010]
**RancherOS Version: (ros os version)**
v1.0.1

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**

Steps to reproduce:

1. sudo system-docker run -d --restart=always redis
2. sudo reboot
3. sudo system-docker ps

Result:

Container has not been restarted on boot

**Comment by SvenDowideit** [comment]
Generally, you should run all non-operating system containers in user-docker - system-docker is the OS container engine, and is likely to be replaced containerd.

IF it needs to run as an OS service, it _should_ be started using a service yml file.

As I was hunting some other issue, I also tried this in v0.7.1 - and it doesn't really look to me like the simplified, customised system-docker supported this then either, so its probably not a regression.
