### ISSUE TITLE
Can't start zfs

### ISSUE THREAD

**Issue by tfiduccia** [rancher/os#2028]
**RancherOS Version: (ros os version)** v1.0.4-rc1

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)** AWS

**Steps:**
1.  Try to start up zfs

**Results:**  zfs doesn't start up.  Getting an error in logs
zfs_1 | checking kernel source directory... /lib/modules/4.9.40-rancher/build
zfs_1 | checking kernel build directory... /lib/modules/4.9.40-rancher/build
zfs_1 | checking kernel source version... Not found
zfs_1 | configure: error: *** Cannot find UTS_RELEASE definition.

**Comment by SvenDowideit** [comment]
oh, interesting.

my working host == default ami, then run 
1. `ros s enable zfs`
1. `ros s up zfs`

testing again with ubuntuconsole - I hope that's the problem.

**Comment by SvenDowideit** [comment]
bizzarely, if i may any comment in an issue i'm assigned to, but didn't create, GH unassigns me.

**Comment by niusmallnan** [comment]
Fixed by https://github.com/rancher/os/issues/2240
