### ISSUE TITLE
Rancheros ISO startup error  （level=error  msg=symlink /usr/bin/ros/  .... ）

### ISSUE THREAD

**Issue by hongxiaolu** [rancher/os#2029]
**RancherOS Version: (ros os version)**
v1.0.3
**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
baremetal, VMware esxi  platform and VMware Fusion or virtualbox

I install rancherOS system on the VMware esxi  platform and VMware Fusion or virtualbox,  The terminal is always jammed When the rancheros ISO  startup  ，       The error is as follows：
<img width="637" alt="11" src="https://user-images.githubusercontent.com/20707603/28903330-dbb4f53c-7836-11e7-9614-d31e4c990085.png">

**Comment by SvenDowideit** [comment]
mmm, those errors are known, and have (now) been determined to be harmless (I've removed them in v1.0.4).

**Comment by hongxiaolu** [comment]
thanks!
