### ISSUE TITLE
docker-machine with VMWare ESXi and v1.0.x fails to untar userdata.tar

### ISSUE THREAD

**Issue by SvenDowideit** [rancher/os#2035]
i thought this worked - atm, on my vmware esxi 6.5, i need to use the web UI to manually untar `/home/docker/userdata.tar and then `chmod -R docker:docker .ssh`

v1.1.0  currently works - so this might be something to fix in 1.0.5

**Comment by ryansch** [comment]
Would I see this in any docker-machine usage?  I ask because 1.0.3 is working just fine for me with docker-machine.  Anything I can do to help test?

**Comment by ryansch** [comment]
I was able to provision a 1.0.4-rc1 VM with `docker-machine create` and everything worked ok.

**Comment by SvenDowideit** [comment]
@ryansch what backend are you using - this (i think) is specific to vmware - and possible esxi

**Comment by ryansch** [comment]
@SvenDowideit I'm using the parallels backend.

**Comment by SvenDowideit** [comment]
and confirmed - this is also now not working on ESXi 5.5 with RancherOS 1.1.0-rc3 - IDK what changed

**Comment by SvenDowideit** [comment]
so the userdata.tar file is put in `/home/docker`, I wonder if machine is then trying to untar `/home/rancher/userdata.tar`

**Comment by SvenDowideit** [comment]
ah, and it looks like its fixed in both v1.0.4 and v1.1.0-rc3 now - the new open-vm-tools service I built doesn't work the way docker-machine expects, so I rolled back to the previous one.
