### ISSUE TITLE
"ros os list" shows two entries for version 1.0.3

### ISSUE THREAD

**Issue by cybe** [rancher/os#2040]
**RancherOS Version:** v1.0.2
**Where are you running RancherOS?**: baremetal

```bash
$ sudo ros os list
rancher/os:v1.0.3 remote available
rancher/os:v1.0.3 remote available
rancher/os:v1.0.2 local available running
```
I guess the topmost entry is the recently released version 1.0.4?

**Comment by SvenDowideit** [comment]
very odd. is it still happening?

**Comment by cybe** [comment]
Not anymore, the entries in https://releases.rancher.com/os/releases.yml are now correct.

**Comment by SvenDowideit** [comment]
cool - fat finger issue on my side
