### ISSUE TITLE
Version specification and reporting consistency

### ISSUE THREAD

**Issue by allingeek** [rancher/os#2049]
There is a disconnect between ROS CLI upgrade specifications and version reporting. Where `ros os version` reports the version of the `ros` binary or logical ROS version the upgrade subcommand takes a full image qualifier. 

While the ros binary version is surely relevant it is no better an indicator of the "OS" version than specifying the kernel version. The best version qualifier for the distribution is the full image qualifier that was used to install the current running image (ideally the content addressable form).

Currently the best way to acquire the current effective running version (with full image qualification) is to run something like, `sudo ros os list | awk '$4 ~ /running/ {print $1}'` and while this works it is far from ideal.

The best way to reconcile this difference without breaking backwards interface compatibility is to add a flag to the version subcommand. Something like `-i` which will cause the subcommand to report the current image in use.

**RancherOS Version: (ros os version)**
rancher/os:v1.0.4

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
baremetal, AWS

**Comment by SvenDowideit** [comment]
```
[rancher@sven-long-term-test ~]$ cat /etc/os-release 
NAME="RancherOS"
VERSION=v1.0.3
ID=rancheros
ID_LIKE=
VERSION_ID=v1.0.3
PRETTY_NAME="RancherOS v1.0.3"
HOME_URL="http://rancher.com/rancher-os/"
SUPPORT_URL="https://forums.rancher.com/c/rancher-os"
BUG_REPORT_URL="https://github.com/rancher/os/issues"
BUILD_ID=
[rancher@sven-long-term-test ~]$ ros -v
ros version v1.0.3
```

**Comment by SvenDowideit** [comment]
ok, agreed - it would be very useful to know that a system was created from `svendowideit/myhackedos:v12.32` and not `rancher/os:v1.0.4`.

agreed.

**Comment by allingeek** [comment]
Can we get this in 1.2?

**Comment by kingsd041** [comment]
@allingeek 
We made some changes and now we use `ros -v` to get the current image in use
```
# ros -v
version v1.2.0-rc2 from os image rancher/os:v1.2.0-rc2
```
This change to meet your needs?

**Comment by kingsd041** [comment]
Close it.
If you still have doubts, please reopen it and let me know.
