### ISSUE TITLE
Hyper-V tools

### ISSUE THREAD

**Issue by nponeccop** [rancher/os#2058]
This is a low-priority issue to solve when #1888 does not prevent RancherOS from running on Hyper-V anymore.

There are few daemons in Linux Kernel Tools which provide usermode part of guest integration services analogous to VMWare `open-vm-tools`.

https://github.com/torvalds/linux/tree/master/tools/hv

To me the most important is `hv_kvp_daemon` which reports guest IP addresses to the host management console (among other things).

In Ubunty, this component is packaged in rather strangely named `linux-cloud-tools-common` package. So RancherOS needs something like that. See distribution-specific bash and systemd scripts which are not in the kernel source.

https://packages.ubuntu.com/trusty/all/linux-cloud-tools-common/filelist

**Comment by doxxx** [comment]
IMO, the lack of `hv_kvp_daemon` makes RancherOS nigh useless on Hyper-V for any kind of automation, since a lot of automation tools need to know the VM's IP address.

**Comment by niusmallnan** [comment]
try v1.5.0
