### ISSUE TITLE
Switching Consoles fails (net/http: TLS handshake timeout)

### ISSUE THREAD

**Issue by fransvanberckel** [rancher/os#2071]
**RancherOS Version: (ros os version)**
RancherOS v1.1.0-rc3

**Where are you running RancherOS?**
On a HP baremetal server

**oem-config.yml**
#cloud-config
rancher:
console: ubuntu
ssh_authorized_keys:
ssh-rsa AAAAB3N...

While installing a fresh server system, and setting with oem-config.yml a other default console, i have got this error. So why doesn't it surprise me, the os-ubuntuconsole isn't installed ;-) 

**ros-sysinit.log**
time="2017-09-04T07:49:49Z" level=debug msg="[13/18] [console]: Reloading project " 
time="2017-09-04T07:49:49Z" level=debug msg="LoadFromNetwork( https://raw.githubusercontent.com/rancher/os-services/v1.1.0-rc3/u/ubuntu.yml)" 
time="2017-09-04T07:49:59Z" level=debug msg="LoadFromNetwork( https://raw.githubusercontent.com/rancher/os-services/v1.1.0-rc3/u/ubuntu.yml) returned <nil>" 
time="2017-09-04T07:49:59Z" level=debug msg="LoadFromNetwork( https://raw.githubusercontent.com/rancher/os-services/v1.1.0-rc3/u/ubuntu.yml) error Get https://raw.githubusercontent.com/rancher/os-services/v1.1.0-rc3/u/ubuntu.yml: net/http: TLS handshake timeout" 
time="2017-09-04T07:49:59Z" level=error msg="Get https://raw.githubusercontent.com/rancher/os-services/v1.1.0-rc3/u/ubuntu.yml: net/http: TLS handshake timeout" 
time="2017-09-04T07:49:59Z" level=error msg="Failed to load gancher.console=(ubuntu): Get https://raw.githubusercontent.com/rancher/os-services/v1.1.0-rc3/u/ubuntu.yml: net/http: TLS handshake timeout"

Installing os-ubuntuconsole afterward, looks okay to me.

**# sudo ros console switch ubuntu**
Status: Downloaded newer image for rancher/os-ubuntuconsole:v1.1.0-rc3
switch-console_1 | time="2017-09-04T08:52:16Z" level=info msg="Project [os]: Starting project " 
switch-console_1 | time="2017-09-04T08:52:16Z" level=info msg="[0/18] [console]: Starting " 
switch-console_1 | time="2017-09-04T08:52:16Z" level=info msg="Recreating console"

**Comment by SvenDowideit** [comment]
mmm, that `net/http: TLS handshake timeout` in your logs sounds very un-good.

**Comment by niusmallnan** [comment]
Close it.
If you still have any problem, please reopen it and let me know.
