### ISSUE TITLE
Unable to load system services

### ISSUE THREAD

**Issue by gizmotronic** [rancher/os#2075]
**RancherOS Version: (ros os version)**
v1.1.0

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
vSphere Hypervisor 6.5.0 (ESXi) virtual machine, iPXE, diskless

I noticed that open-vm-tools wasn't running. When confirming that it was enabled:

```
[rancher@myhost ~]$ sudo ros service list
ERRO[0000] Failed to load https://raw.githubusercontent.com/rancher/os-services/v1.1.0/index.yml: Get https://raw.githubusercontent.com/rancher/os-services/v1.1.0/index.yml: x509: certificate signed by unknown authority 
enabled  open-vm-tools
```

Attempting to start it manually shows the same error:

```
[rancher@myhost ~]$ sudo ros service start open-vm-tools
ERRO[0000] Get https://raw.githubusercontent.com/rancher/os-services/v1.1.0/o/open-vm-tools.yml: x509: certificate signed by unknown authority 
ERRO[0000] Failed to load service(open-vm-tools): Get https://raw.githubusercontent.com/rancher/os-services/v1.1.0/o/open-vm-tools.yml: x509: certificate signed by unknown authority 
No such service: open-vm-tools
```

It seems there's a missing CA certificate bundle somewhere.

**Comment by SvenDowideit** [comment]
mmm, is this a cd/iso/pxe booted system, an installed system, or ?

I'm hoping there's something specific in your system setup that we can narrow the problem down to.

**Comment by gizmotronic** [comment]
Booted via iPXE with state stored on /dev/sda.

```
#!ipxe
# Boot a persistent RancherOS to RAM

# Location of Kernel/Initrd images
set base-url http://releases.rancher.com/os/v1.1.0

kernel ${base-url}/vmlinuz rancher.state.dev=LABEL=RANCHER_STATE rancher.state.autoformat=[/dev/sda]
initrd ${base-url}/initrd
boot
```

Incidentally, since this is on VMware, I'm using guestinfo to configure the cloud-init datasource URL. Works well. :+1:

**Comment by gizmotronic** [comment]
Curiously, a couple of findings:

- I can use wget from the standard/default console container to fetch the URL in the error message without any certificate validation trouble.
- Both open-vm-tools and ```ros service list``` work fine on a similar machine I configured at home.

There are two differences that I am aware of:

1. On the machine having problems I have an iPXE boot ROM configured. At home I use PXE to load an iPXE booter with an embedded script, which then chain loads the OS.
2. There's an application aware firewall in front of the machine having problems. Having said that, though, HTTPS traffic is passed through unmolested (except for IP blocks to known risky sites). I think that being able to use wget eliminates the firewall as a potential problem.

I can probably set up a chain loader like I did at home and will report back if/when I'm able to do that, just to eliminate the boot ROM as a potential problem.

**Comment by gizmotronic** [comment]
Using PXE to load iPXE and then chain load the OS didn't change anything.

One thing I've noticed is that where v1.1.0 immediately returns a certificate validation error, v1.0.1 and v1.0.4 take considerably longer to return a result but end up with the same error (with the URL adjusted according to the OS version, of course). This suggests an environmental problem, in spite of the fact that I can also get the index.yml file from the console container on these versions.

Is there some way to peek under the hood, and perhaps be able to run commands from the same context that the error is being triggered? The logs in /var/log/boot tell me nothing other than what I already know.

**Comment by SvenDowideit** [comment]
yeah, thinking music :/

**Comment by SvenDowideit** [comment]
and in an annoying turn, I'm failing to reproduce this - I'll keep kicking, because I've seen something similar intermittently over the week.

**Comment by gizmotronic** [comment]
I have collected definitive evidence of a recent, unannounced change to the application aware firewall. This is a local problem. Sorry to waste your time.

**Comment by SvenDowideit** [comment]
I don't believe you :banana: 

but in really good news, your issue, and a blog post I started writing yesterday, caused me to find a different dhcp&resolv.conf related issue in 1.1.0 - so 1.1.1 will be even better-er-er

**Comment by gizmotronic** [comment]
The firewall intercepts HTTPS requests and synthesizes a private-CA-signed cert to present to the client. If the client doesn't trust the private CA, certificate validation fails. The cert I snagged using ```openssl s_client``` clearly shows that's what is going on here. :(

**Comment by gizmotronic** [comment]
I've confirmed with the people who would know that this was in fact the root cause. They were able to add an exception for my machines. All is well again.

Unless you have an objection, I'll open a new issue to suggest that it would be useful to have a way to add private CA certificates to the OS. (I am already doing this for the user Docker instance.)
