### ISSUE TITLE
Nasty ERR msg for sudo ros service subcommands due to missing <hypervisor>-vm-tools

### ISSUE THREAD

**Issue by ryansch** [rancher/os#2076]
**RancherOS Version: (ros os version)**
v1.1.0

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
linode, docker-machine

I tried to create a service via `sudo ros service create <servicename>` and got the following error:
```
ERRO[0000] non-200 http response: 404
ERRO[0000] Failed to load service(kvm-vm-tools): non-200 http response: 404
```

I noticed the service enabled in the list from `sudo ros service list` so I tried to disable it:

```
$ sudo ros service disable kvm-vm-tools
FATA[0000] kvm-vm-tools is not a valid service
```

**Comment by SvenDowideit** [comment]
Does this error message prevent your command from working? or is it just extra noise? (When I tested, it seemed like noise that I didn't have time to squash)

**Comment by ryansch** [comment]
You're right!  It did create the service.  I figured after the big scary red ERRO that it didn't work.

**Comment by dmnc-net** [comment]
I'm running ROS as a kvm guest (Proxmox VE), trying v. 1.1.0 for a first time. I found nothing is running on port 8080 so I've tried to install service `rancher-server` or `rancher-server-stable` ... both somehow depends on `kvm-vm-tools` which is enabled but I can't stop/disable/delete that service ... I'm getting the same result ... HTTP 404.

**Comment by niusmallnan** [comment]
Same with https://github.com/rancher/os/issues/2168

**Comment by dmnc-net** [comment]
@niusmallnan thanks for solving the isuue.

side note: marking the older (#2076) issue as a "same with" (aka "duplicate of") the your younger (#2168) issue is very funny. :)
