### ISSUE TITLE
bootcmd doesn't work like the docs say

### ISSUE THREAD

**Issue by SvenDowideit** [rancher/os#2081]
the docs suggest you can configure bootcmd like runcmd, in the cloud-init / config

but its run before the OS has access to either the on disk config, or the cloud-init.

it _could possibly_ be used from the kernel params, but needs some testing, and some cleverness

(I'm wondering if my bootcmd can install from a PXE boot, and then if we'd use the installed version without rebooting.)

**Comment by SvenDowideit** [comment]
__AND__ explain in the docs what containers and images the `bootcmd`, `runcmd` and shell based `userdata` run in.

**Comment by SvenDowideit** [comment]
anyone that's interested in looking into this - there's an interesting `rancher.state.script` that could also be useful - we could provide pre-made scripts like `reset.sh` and `reset_if_missing.sh`

**Comment by SvenDowideit** [comment]
which some hacking, I was able to get `bootcmd=dd,if=/dev/zero,of=/dev/sda,bs=1024,count=1024` to run, and in doing so, this ensured that the state parition is re-created at every pxe boot.

needs work, and needs some tests - I think there are a number of bugs, including that non `rancher.*` boot params are ignored by default.

**Comment by strowi** [comment]
Hi,

i am just in the process of setting up a couple of ci-vms and would like them to be cleaned on every boot.
So i tried modifying the iso:

```
+bootcmd:
+  - [ dd, if=/dev/zero, of=/dev/vda, bs=2M, count=2 ]
+  - [mkfs.ext4, -L, RANCHER_STATE, /dev/vda ]
```
But after a reboot a file i created is still present on /dev/vda...?

Bootstrap-Log shows no apparent error:
```
[root@rancher boot]# cat ros-bootstrap.log 
time="2018-07-24T14:06:41Z" level=debug msg="START: [ros-bootstrap] in /" 
time="2018-07-24T14:06:41Z" level=debug msg=bootstrapAction 
time="2018-07-24T14:06:42Z" level=debug msg="bootstrapAction: loadingConfig" 
time="2018-07-24T14:06:42Z" level=debug msg="bootstrapAction: MdadmScan(false)" 
time="2018-07-24T14:06:42Z" level=debug msg="bootstrapAction: stateScript()" 
time="2018-07-24T14:06:42Z" level=debug msg="bootstrapAction: RunCommandSequence([{ [dd if=/dev/zero of=/dev/vda bs=2M count=2]} { [mkfs.ext4 -L RANCHER_STATE /dev/vda]}])" 
time="2018-07-24T14:06:43Z" level=debug msg="bootstrapAction: udev settle2" 
```

regards,
Roman

**Comment by niusmallnan** [comment]
As you can see, `bootcmd` runs during the `bootstrap` process.

In order to boot speed, in fact, now `bootstrap` does not run every boot. It just runs when you first boot via docker-machine or iPXE.

So this part of the document is really unclear. I need to update it.

About your case, if you want to clean on every boot.
A crazy idea is that you can let RancherOS run in memory without using a physical disk. After rebooting, all data is automatically cleared.

**Comment by strowi** [comment]
Ah so there is no way to use a clean RANCHER_STATE on every boot?

Running in RAM would be feasible, but we don't have enough RAM for all the runners... ;)

**Comment by niusmallnan** [comment]
Which data needs to be cleaned up?
The default console can clean up the data every boot, except for those persistent directories.
If you want to clean up user-docker, you can try `runcmd`:
```
#cloud-config
runcmd:
- rm -rf /var/lib/docker/*
```
`runcmd` runs in the console and is executed before user-docker.
