### ISSUE TITLE
[doc?] make the readme for AMI's more clear as to whats RoR and whats regular ROS

### ISSUE THREAD

**Issue by aemneina** [rancher/os#2101]
This is just a doc issue where its not clear from the readme what is a rancher on rancher AMI vs a 'vanilla' ROS ami.

**Comment by SvenDowideit** [comment]
Do we mention the Rancher on RancherOS AMI anywhere in the docs at all? I thought it was just a aws marketplace thing, and not really an AMI you use directly.

**Comment by aemneina** [comment]
The rancher UI has a url that directs to [here](https://github.com/rancher/os/blob/master/README.md/#user-content-amazon). Its not clear if i'm installing ROS or ROR from the ami list there.
