### ISSUE TITLE
default console wget fails when using a http_proxy with a redirect

### ISSUE THREAD

**Issue by SvenDowideit** [rancher/os#2109]
```
wget http://home.org.au
Connecting to 10.11.11.1:3128 (10.11.11.1:3128)
wget: error getting response
```

`wget http://www.home.org.au/` works.

same command with the same env (http_proxy and HTTP_PROXY set to `htto://10.11.11.1:3128` works in the alpine/debian console.

**Comment by Jason-ZW** [comment]
@SvenDowideit @niusmallnan  Hi all, i have built an iso base on revision number `19a8103` and this issue can not be reproduce.
