### ISSUE TITLE
Build the ROS image in Aliyun

### ISSUE THREAD

**Issue by niusmallnan** [rancher/os#2111]
Aliyun support KVM virtualization, support two image formats: raw and vhd.

Import Customized Linux: https://help.aliyun.com/document_detail/48226.html

To do list:
1. Build an image by os-packer(type: qemu), test whether this image will work.
2. Support `Aliyun Datasource` in RancherOS cloud-init.
3. ~~Maybe need to modify the file system (from overlay to ext)~~

**Comment by kingsd041** [comment]
I can import the image on Aliyun and use it to start the instance. Checked the cpu, memory, disk, hostname and other information, and some manual tests on the ros command.
I think rancheros v1.1.2-rc2 works fine on Aliyun.

I found an issue about disk resize.
link：https://github.com/rancher/os/issues/2186
