### ISSUE TITLE
Slow user docker start

### ISSUE THREAD

**Issue by kirrmann** [rancher/os#2126]
**RancherOS Version: v1.1.0**

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**

PXEboot in KVM. Fresh install, ubuntu Console. rancher-nfs

If I restart the server it takes up to 20 minutes for `docker ps` to show output and container to start. system-docker is up and running and I can' find any logs, which points me to any error.

**Comment by superseb** [comment]
Can you please share output of `/var/log/docker.log`, especially for

```
time="2017-11-02T11:24:47.934218978Z" level=warning msg="Unable to locate plugin: rancher-nfs, retrying in 1s" 
time="2017-11-02T11:24:48.934417346Z" level=warning msg="Unable to locate plugin: rancher-nfs, retrying in 2s" 
time="2017-11-02T11:24:50.935378723Z" level=warning msg="Unable to locate plugin: rancher-nfs, retrying in 4s" 
time="2017-11-02T11:24:54.936251447Z" level=warning msg="Unable to locate plugin: rancher-nfs, retrying in 8s" 
```

**Comment by niusmallnan** [comment]
Close it.
If you still have this problem, please reopen it and let me know.

**Comment by pioto** [comment]
I've also observed this.

```
time="2017-12-28T12:56:09.511565774Z" level=error msg="get graphite-statsd_graphite_conf_b25c6: Error looking up volume plugin rancher-nfs: legacy plugin: plugin not found"
time="2017-12-28T12:56:09.511760384Z" level=warning msg="Unable to locate plugin: rancher-nfs, retrying in 1s"
```

I'm currently on v1.1.1... I'll attempt an upgrade to v1.1.2 and see if that helps...

**Comment by pioto** [comment]
Nope, I'm still observing this issue on v1.1.2...

**Comment by niusmallnan** [comment]
Oh, I know. 
I see the logs include `rancher-nfs`,  I think it's a bug for Rancher, not RancherOS.
I can do nothing, our team is trying to fix it in Rancher.
You can watch https://github.com/rancher/rancher/issues/8433
