### ISSUE TITLE
rachner/os-debianconsole-base repository not found

### ISSUE THREAD

**Issue by FXRer** [rancher/os#2128]
Hello all,

I'm trying to build rancherOS  for Raspberry Pi (from master branch) by using the script at [(https://gist.github.com/rgaidot/bc2efc014cccabb926392e353708122a](https://gist.github.com/rgaidot/bc2efc014cccabb926392e353708122a) but it seems that I have problem with **Dockerfile.dapper** file under **os/ scripts/images/raspberry-pi-hypriot(64)** because the **rancher/os-debianconsole-base** does not exist.

I think it would be ok with branches/tags prior v0.8.x because **debian:jessie** repository is required instead of **rancher/os-debianconsole-base**.

I'd like to know which is the propper approche for Raspberry Pi target btw switching back to a version < v0.8.x or modifying the Dockerfile.dapper ?

Best regards,
Pascal

**Comment by niusmallnan** [comment]
@FXRer 
You can build rpi64 image, try this on the ARM platform:
```
git clone https://github.com/rancher/os
cd os
make
make rpi64
```

Close it.
If you still have this problem, please reopen it and let me know.
