### ISSUE TITLE
How to set registry-mirror params for system-docker ?

### ISSUE THREAD

**Issue by JermineHu** [rancher/os#2130]
**First of all, thank you very much for RancherOS provided by Rancher**

**RancherOS Version: V1.1.0**
**Where are you running RancherOS? (virtualBox)**

**Visiting docker official images repo from China is very slow， when to pull a image in system-docker will take a long time！So in order to speed up, I want to set the system-docker registry-mirror**

**Comment by JermineHu** [comment]
This is a very retarded question! It's settled. Share it! 

```
1. vi /etc/docker/system-docker.json

{
    "registry-mirrors": [
        "http://a2efa943.m.daocloud.io"
    ],
    "insecure-registries": []
}
  2. sudo reboot
```

This question can be closed！

**Comment by zjzh** [comment]
vff
