### ISSUE TITLE
[os-images] Cannot enable ros service volume-netshare

### ISSUE THREAD

**Issue by pcassimans** [rancher/os#2142]
**RancherOS Version: (ros os version)**
Version 1.1.0

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
iohyve

When i ask the list of available services, get "volume-netshare" as one of them.
If I try to enable it by:
```
sudo ros service enable volume-netshare
```
I get the following error:
```
FATA[0001] Failed to load volume-netshare : non-200 http response: 404
```

**Comment by cnf** [comment]
I have the same problem, any update on this?

RancherOS v1.1.0 running bare metal.

**Comment by niusmallnan** [comment]
Anyone with this problem can try this:
```
rm -f /var/lib/rancher/cache/*
ros service list
disabled amazon-ecs-agent
disabled crontab
disabled open-iscsi
disabled kernel-extras
disabled kernel-headers
disabled kernel-headers-system-docker
disabled open-vm-tools
disabled rancher-server
disabled rancher-server-stable
disabled zfs
disabled amazon-metadata
disabled volume-cifs
disabled volume-efs
disabled volume-nfs
```
In fact, `volume-netshare` contains three services `volume-cifs` `volume-efs` `volume-nfs`.

**Comment by kingsd041** [comment]
Tested with RancherOS version- v1.1.2-rc2
`volume-cifs` `volume-efs` `volume-nfs` can be enabled.
```
# ros service list | grep volume
enabled  volume-cifs
enabled  volume-efs
enabled  volume-nfs
```
