### ISSUE TITLE
LVM support

### ISSUE THREAD

**Issue by cnf** [rancher/os#2146]
As #356 was closed, and there is no replies to it, i'm opening another issue.

#356 says LVM support is in 0.4.0+, but I can not find any documentation for this, nor can I find the lvm commands.

Was this not added? If it was added, where is the documentation?

Thanks

**Comment by melvyndekort** [comment]
I'm wondering about this too.
I have a server where I use mdadm and LVM to manage my storage configuration.
If LVM actually works, even through an addon Docker, I want to migrate my server to run RancherOS.

**Comment by caryyu** [comment]
weird , nooooo answers

**Comment by niusmallnan** [comment]
I made some attempts, as follows:

```
root@ip-172-31-19-80:# ros -v
ros version v1.1.2-rc2

root@ip-172-31-19-80:# ros console switch ubuntu
root@ip-172-31-19-80:# apt-get install lvm2

# prepare another volume, then check it
root@ip-172-31-19-80:~# fdisk -l
....
....
Disk /dev/xvdf: 10 GiB, 10737418240 bytes, 20971520 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes

# edit /etc/lvm/lvm.conf and change use_lvmetad=1 to use_lvmetad=0
# then reboot
```

Now you can use LVM, I created one pv and one vg.
```
root@ip-172-31-19-80:/home/rancher# pvscan
  PV /dev/xvdf1   VG niusmallnan     lvm2 [10.00 GiB / 10.00 GiB free]
  Total: 1 [10.00 GiB] / in use: 1 [10.00 GiB] / in no VG: 0 [0   ]
root@ip-172-31-19-80:/home/rancher# vgscan
  Reading all physical volumes.  This may take a while...
  Found volume group "niusmallnan" using metadata type lvm2
```

**Comment by kingsd041** [comment]
Tested with rancheros v1.2.0-rc2.
The lvm commands will be added on the default console. Other consoles need to manually install lvm to use.
