### ISSUE TITLE
Network not working at all after installation

### ISSUE THREAD

**Issue by murbanowicz** [rancher/os#2149]
**RancherOS Version: (ros os version)**
1.1
**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
KVM VPS

I am stuck after the installation as RancherOS does not recognize the network therefore I cannot connect to the machine in any way (I am able to do something using VNC).
![rancherconf](https://user-images.githubusercontent.com/9385106/32442305-dbdddaae-c2f2-11e7-9ec1-fd9e46011e55.PNG)

Will appreciate any help

**Comment by liyimeng** [comment]
Try to verify your cloud-config file is correct by running 
ros config validate -i <your config file>

**Comment by niusmallnan** [comment]
@murbanowicz 
The NICs can get ip address?
other suggestion:
1. The `rancher.passwork` is a kernel parameter, It makes no sense to use it in cloud-config.
2. Try `ros config validate -i`.

Close it.
If you still have this problem, please reopen it and let me know.
