### ISSUE TITLE
what's the root password and kernel version？

### ISSUE THREAD

**Issue by 13567436138** [rancher/os#2150]
what's the root password and kernel version？

**Comment by superseb** [comment]
There is none. You can either set a password as a kernel parameter (http://rancher.com/docs/os/v1.1/en/boot-process/built-in-system-services/#console) or add your SSH public key via cloud-config (http://rancher.com/docs/os/v1.1/en/configuration/ssh-keys/).

Latest release is `v1.1.0 - Docker 17.03.2-ce - Linux 4.9.45`
