### ISSUE TITLE
Support for newer (but stable) docker engines

### ISSUE THREAD

**Issue by mikemoate** [rancher/os#2152]
**RancherOS Version: (ros os version)**
v1.1.0
**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
AWS

What are the plans to support newer docker engines (and I guess more generally the plans for future RancherOS releases).

We're using 17.06.1-ce currently on RancherOS v1.1.0, but 17.06.2-ce is the latest release in that series, and 17.09.0-ce is now out as well.

**Comment by djmaze** [comment]
@mikemoate I built newer some versions (17.09.0-ce, 17.10.0-ce) in an an external repository. You can use those while the versions are not yet in the official repo:

```bash
$ sudo ros config set rancher.repositories.strahlungsfrei.url http://www.strahlungsfrei.de/os-services/
$ sudo ros engine list
[...]
current  docker-17.09.0-ce
disabled docker-17.10.0-ce
```

**Comment by develar** [comment]
@niusmallnan Will be cool if upcoming 1.1.1 release will include docker 17.09.1-ce by default.

**Comment by kingsd041** [comment]
RancherOS v1.1.2-rc2 already includes docker-17.06.2-ce and docker-17.09.1-ce. I've switched to docker-17.09.1-ce and simply tested it.

```
root@rancheros-v1:~# ros engine list
disabled docker-1.12.6
disabled docker-1.13.1
disabled docker-17.03.1-ce
disabled docker-17.03.2-ce
disabled docker-17.04.0-ce
disabled docker-17.05.0-ce
disabled docker-17.06.1-ce
disabled docker-17.06.2-ce
current  docker-17.09.1-ce
```
