### ISSUE TITLE
https://releases.rancher.com/dapper/latest/dapper-Darwin-x86_64 throws Segmentation Fault

### ISSUE THREAD

**Issue by bjfr** [rancher/os#2153]
**RancherOS Version: (ros os version)**
Tested with  1.1.0 and 1.0.3

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
The problem is building the ISO, not running it

On the latest recent release of Mac OSX High Sierra v10.13.1, the dapper executable located at 

https://releases.rancher.com/dapper/latest/dapper-Darwin-x86_64

fails with a segmentation fault 11.

If you build dapper yourself using **go version go1.9.2 darwin/amd64** and modify *Makefile* to use the local version the build seems to work OK!

So a rebuild of the executable at *https://releases.rancher.com/dapper/latest/* would be appreciated!

**Comment by bjfr** [comment]
Any progress on this issue? A simple recompile and upload, should take a few minutes max...

**Comment by TunedMidja** [comment]
I'm also having this issue. Any news?

**Comment by MWallenberg** [comment]
I am facing the same issue with rancher-compose after updating to High Sierra. Right now, I'm not able to use Rancher at all :(

**Comment by caryyu** [comment]
the same , no answers at all.

**Comment by ryansch** [comment]
Workaround here: https://github.com/rancher/dapper/issues/47

**Comment by niusmallnan** [comment]
It is a bug for the golang compiler. https://github.com/golang/go/issues/22059
We will release a new dapper.

**Comment by oicheryl** [comment]
@niusmallnan Any update on when you will release?

The last release on https://github.com/rancher/dapper/releases was September 2016.

**Comment by dramich** [comment]
This has been resolved in the [latest release](https://github.com/rancher/dapper/releases/latest)

**Comment by oicheryl** [comment]
Can confirm this release solves my issue. Thank you @dramich!
