### ISSUE TITLE
ros install -c https://link/to/cloud-config.yml -d /dev/sda, no such file or directory

### ISSUE THREAD

**Issue by naisanza** [rancher/os#2155]
**RancherOS Version: (ros os version)**

`v1.1.0`

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
`kvm`

Error:
```syslog
FATA[0000] Failed to copy cloud-config                   cloudConfig="https://link/to/cloud-config.yml" error="open https://link/to/cloud-config.yml: no such file or directory"
```

**Comment by junkiebev** [comment]
Does a URL work? I have always just run wget to get it first.

**Comment by naisanza** [comment]
@junkiebev the URL works

**Comment by niusmallnan** [comment]
Close it.
If you still have this problem, please reopen it and let me know.

**Comment by naisanza** [comment]
@niusmallnan this was never fixed

The URL doesn't work with `ros`

**Comment by niusmallnan** [comment]
@naisanza 
Ok, reopen it.
Will support URL when using `ros install -c https://link/to/cloud-config.ym`.

**Comment by kingsd041** [comment]
@naisanza 
In RancherOS v1.2.0-rc2, the URL is already supported
Close it.

**Comment by naisanza** [comment]
@kingsd041 awesome
