### ISSUE TITLE
Is RancherOS still actively maintained?

### ISSUE THREAD

**Issue by stffabi** [rancher/os#2156]
Hi folks

Basically I have the question if RancherOS is still actively maintained. There has been no work going on in the last couple of months, whereas the project was very active before. Most of the maintenance/development has been done by @SvenDowideit in the past. But it seems to me like he has left "Rancher" during the last couple of months, accordingly to his profile.

I really like the project and I'm actively using it for different productive servers, but the current situation seems a little bit blurry...

Has someone from rancher any information about the future of the project or could clarify the situation?

**Comment by ryansch** [comment]
I came on here to ask exactly this question.  I noticed that Sven's "epic" PR (https://github.com/rancher/os/pull/2079) stalled as well.  Do I need to start evaluating other options?  We're running this in production as well.

**Comment by boistordu** [comment]
why are we talking about actively maintained? Is this not a monetized product for entreprise grade anyway ? and rancherOS is just one part of the project no ?

**Comment by develar** [comment]
@boistordu ...and paid/enterprise users chooses coreos/ubuntu/centos, right?

**Comment by boistordu** [comment]
Well I don't know, since @ryansch have said that they are using it in production ....

**Comment by ryansch** [comment]
@boistordu This is an OS.  Rancher happens to use RancherOS but you don't have to use Rancher.  We're probably going to jump ship for alpine if there's no action here soon.

**Comment by boistordu** [comment]
Okay my mistake then, I though that there has been first rancher then rancherOS as a side project. But then again I don't understand how it could goes to shit like that since they offer consulting service so it has to be an enterprise with monetized product behind it.

**Comment by ibuildthecloud** [comment]
As people noticed, yes @SvenDowideit has moved on to bigger and better things.  This does put us in a pickle as he was the main contributor to RancherOS adding features and doing great work around LinuxKit.  So that has definitely stalled.  From a "maintenance" perspective, that is still going on as needed.  The nature of RancherOS is it is supposed to be small and simple and not need a heck of a lot of maintenance.

So where is RancherOS headed?  It's still alive and we still have plans for it.  And most importantly we have paying customers using it.  Right now the company is super focused on getting Rancher 2.0 (the management product) out the door.  As such we haven't wanted to reallocate resources to RancherOS until 2018 (sorry, we aren't a huge company).  You are going to see a lull in activity until Q1 of 2018. :(

If anyone is looking for a job to maintain RancherOS let me know.

**Comment by mikemoate** [comment]
@ibuildthecloud we'd love some re-assurance that someone is still allocated to RancherOS from a security perspective, tracking and evaluating new CVE's and whether updates/a new release are needed?

**Comment by will-chan** [comment]
@mikemoate we still actively looking for CVE and security issues and will patch accordingly as they come.  We will also ship small releases for our paying customers.  What Darren is talking about is that until Rancher 2.0 shipped, we won't be actively adding new features into OS.  We have done some initial discussions on even RancherOS 2.0, but again, won't be able to act on it until 2018.

**Comment by niusmallnan** [comment]
RancherOS v1.1.1 has been released.
Close this issue.😄

**Comment by eyz** [comment]
I would love to test a LinuxKit-based RancherOS. I think the provisioning pieces of LinuxKit may also be a good fit, instead of using the Docker Machine model.

**Comment by ibuildthecloud** [comment]
@eyz We've done quite a bit of work and analysis to move RancherOS to be LinuxKit based.  In the end I don't think we will go forward with it.  While there could be some advantages to using LinuxKit it doesn't address any of our current issues.  LinuxKit ends up being a nice to have.  So I don't completely rule out using it, the advantages are just very much tangential to what we need.

We have every intention of moving RancherOS to be containerd based.  The current plan is that RancherOS 2.0 will be containerd based.  TBH we aren't in a huge rush though.  RancherOS has always been designed to be very small in scope and do one thing well.  And it does currently accomplish that. Right now we are waiting for cri-containerd to land in containerd proper (not require separate daemon) and for that to stabilize.

**Comment by eyz** [comment]
@ibuildthecloud Thanks for the reply. Yes, it sounds like it's a good idea to wait for the containerd space to settle a bit. LinuxKit is especially under heavy development, and I certainly understand wanting to keep things light, as well. I'm happy to see there is a roadmap of sorts for RancherOS, and I look forward to testing Rancher 2.x in the near future.

**Comment by 2devnull** [comment]
Is the plan to have a regular upgrade (ros os upgrade) from 1.x to 2.0 in moving from Cattle to K8?

**Comment by xinity** [comment]
@2devnull way too soon to ask i think :)
