### ISSUE TITLE
docker not available: permission denied 

### ISSUE THREAD

**Issue by boistordu** [rancher/os#2157]
**RancherOS Version: (ros os version)**
1.1.0
**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
in a VM in KVM-qemu

docker ps doesn't work and give me permission denied. 
I've read that system-docker was only for docker container within the system... So what should I do? Should I provide you with something like logs or anything ? 
I'm a beginner on docker .

**Comment by boistordu** [comment]
So it seems that the container os-docker is restarting every 3 seconds. any idea why it would be in a loophole ?

**Comment by boistordu** [comment]
`time="2017-11-22T17:23:13.591442492Z" level=warning msg="Could not get operating system name: Error opening /usr/lib/os-release: open /usr/lib/os-release: no such file or directory"` 

that's the content of the `system-docker.log` don't know if it's relevant

**Comment by boistordu** [comment]
`Could not load X509 key pair (cert: "/etc/docker/tls/server-cert.pem", key: "/etc/docker/tls/server-key.pem"): open /etc/docker/tls/server-cert.pem: no such file or directory`

that's the content of docker.log

**Comment by boistordu** [comment]
there is indeed no files in /etc/docker/tls ... but why whouldn't no files since I didn't make any change to the file structure ...?

**Comment by boistordu** [comment]
no advice then ?

**Comment by superseb** [comment]
What did you use to start RancherOS? Starting from the ISO doesn't give me a restarting user Docker, what is different in your setup?

**Comment by boistordu** [comment]
it's installed on the disk.  so I just follow the steps which are described  in the forum. What do you need me to show you ?

**Comment by superseb** [comment]
Did you use the ISO to install it? What command did you use to install it? What cloud-config.yml did you use?

**Comment by boistordu** [comment]
yes the iso. 
the install commad that's a good question ^^ ros install something I think ... I should verify but in the meanwhile I have the cloud-config available: 
sudo ros config export
EXTRA_CMDLINE: /init
hostname: rancher-node1
rancher:
  docker:
    tls: true
  environment:
    EXTRA_CMDLINE: /init
  network:
    dns:
      nameservers:
      - 192.168.5.91
      - 192.168.5.4
    interfaces:
      eth*:
        dhcp: false
      eth0:
        address: 192.168.5.23/25
        gateway: 192.168.5.1
        mtu: 1500
  password: 
  services_include:
    kvm-vm-tools: true
  state:
    dev: LABEL=RANCHER_STATE
    wait: true
ssh_authorized_keys:
 - ssh-rsa

**Comment by boistordu** [comment]
the tls key we speak about here, is it the official key of docker ? which are available at the installation to authenficate the docker version ? or is it private key from our domain ?

**Comment by superseb** [comment]
You are configuring the user docker to use TLS, but do you supply certificates somewhere?

**Comment by boistordu** [comment]
Okey sorry about that, since several people were taking that into default config, I assume that it was default key of docker generate automatically at the installation and not some customization to make docker instance communicate with outside world. 
put `sudo ros config set rancher.docker.tls false`
should I do something else? 
thanks anyway
