### ISSUE TITLE
Can't SSH on Google Compute Engine

### ISSUE THREAD

**Issue by kamerk22** [rancher/os#2159]
**RancherOS Version: (v1.1.0)** 

**Where are you running RancherOS? (GEC)**

After following [`Rancher Install`](http://rancher.com/docs/os/v1.1/en/running-rancheros/cloud/gce/ ).
My VM booted successfully but I can't SSH to my VM.

When I connect to VM it's asking for password for SSH.

![screenshot-2017-11-27 compute engine - zroomp-development](https://user-images.githubusercontent.com/11503211/33271896-8b1527e0-d3ae-11e7-8b1c-68543a71eb6f.png)

Trying to SSH from In Browser Windows giving following error and stuck.

![screenshot-2017-11-27 ssh rancher-master zroomp-development](https://user-images.githubusercontent.com/11503211/33271724-105712e8-d3ae-11e7-9b50-5e4c91c4ceea.png)

**Comment by niusmallnan** [comment]
@kamerk22 
Can refer to here:
http://rancher.com/docs/os/v1.1/en/running-rancheros/cloud/gce/

**Comment by niusmallnan** [comment]
@kamerk22 
You should use the `rancher` user, like `ssh rancher@xx.xx.xx.xx`.
I have not tried to SSH from In Browser Windows.
