### ISSUE TITLE
AMI not enable Elastic Network Adapter

### ISSUE THREAD

**Issue by zhouqianli** [rancher/os#2160]
**RancherOS Version: (ros os version)**
v1.1.0
**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
AWS EC2

**Repro**
Using `aws ec2 run-instances --image-id ami-9515feed  --instance-type c5.large` to start new machines.  Got error:

>An error occurred (InvalidParameterCombination) when calling the RunInstances operation: Enhanced networking with the Elastic Network Adapter (ENA) is required for the 'c5.large' instance type. Ensure that you are using an AMI that is enabled for ENA.

**Comment by drpebcak** [comment]
This happens when trying to launch an instance in the `m5`family as well.

**Comment by SimonR** [comment]
I would like to use the new c5 and m5 types to support a number of managed services. Is there a timescale for the upgrade works?

**Comment by kingsd041** [comment]
At eu-west-1, I can start a new machine.
`aws ec2 run-instances --image-id ami-1567e46c --count 1 --instance-type m5.large`
Login instance, we can use the command to check that ena has been enabled
```
# ethtool -i eth0
driver: ena
version: 1.0.2
...

```
```
# modinfo ena
filename:       /lib/modules/4.9.69-rancher/kernel/drivers/net/ethernet/amazon/ena/ena.ko
version:        1.0.2
license:        GPL
description:    Elastic Network Adapter (ENA)
author:         Amazon.com, Inc. or its affiliates
srcversion:     6F645A5E6BD991AF7F7EA34
alias:          pci:v00001D0Fd0000EC21sv*sd*bc*sc*i*
alias:          pci:v00001D0Fd0000EC20sv*sd*bc*sc*i*
alias:          pci:v00001D0Fd00001EC2sv*sd*bc*sc*i*
alias:          pci:v00001D0Fd00000EC2sv*sd*bc*sc*i*
depends:
intree:         Y
vermagic:       4.9.69-rancher SMP mod_unload
parm:           debug:Debug level (0=none,...,16=all) (int)
```

@deniseschannon  Can I close this issue now? Because only am-west-1 and eu-west-1 have this AMI
