### ISSUE TITLE
No need to enable xenhvm-vm-tools/kvm-vm-tools/hyperv-vm-tools/bhyve-vm-tools service

### ISSUE THREAD

**Issue by niusmallnan** [rancher/os#2168]
RancherOS added detetion of Hypervisor, and then will try to download the a service called <hypervisor>-vm-tools. 
When using kvm hypervisor, it will enable `kvm-vm-tools`, but in fact `kvm-vm-tools` does not exist

**Comment by kingsd041** [comment]
Tested with RancherOS version- v1.1.2-rc2.
1. Xenhvm-vm-tools / kvm-vm-tools / hyperv-vm-tools / bhyve-vm-tools service has been removed from RancherOS
2. Only enable open-vm-tools serivce for vmware.

**Comment by kuhnroyal** [comment]
How can I remove the `kvm-vm-tools` service if I already got this enabled somehow with an older version. This causes startup times > 15min for me. I can't disable/delete/rm the service as it is no service valid service.

```
root@foo:/var/lib/rancher# ros s disable kvm-vm-tools
FATA[0000] kvm-vm-tools is not a valid service
```

**Comment by niusmallnan** [comment]
@kuhnroyal You can check the `services_include` in cloud-config, then get rid of `kvm-vm-tools` service.
