### ISSUE TITLE
rc3 is used in tags in os-services repo for v1.1.0

### ISSUE THREAD

**Issue by superseb** [rancher/os#2170]
**RancherOS Version: (ros os version)**
v1.1.0

This commit (https://github.com/rancher/os-services/commit/1be6978142175ae0e7404b3dcdc6ba42f2af87dc) introduces rc3 tags for all console images and zfs image, but was never updated to v1.1.0.

**Comment by niusmallnan** [comment]
For these images, there is no difference between v1.1.0 and v1.1.0-rc3.
But to comply with the norms before, I will update it.

**Comment by niusmallnan** [comment]
Fixed by https://github.com/rancher/os-services/commit/86f3e094005c51ffa7bca6c3ab111ad3a4da29c1

**Comment by superseb** [comment]
Great, thanks
