### ISSUE TITLE
VMware Fusion problem

### ISSUE THREAD

**Issue by tosbaha** [rancher/os#2171]
**RancherOS Version: (ros os version)**
 v1.1.1-rc1 
**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
Docker Machine with VMware Fusion driver
VmWare version 8.5.9
macOS 10.13.1

```
➜  ~ docker-machine create --driver vmwarefusion --vmwarefusion-boot2docker-url https://github.com/rancher/os/releases/download/v1.1.1-rc1/rancheros.iso ranchervm
```
It hangs with following output on VM
![screen shot 2017-12-09 at 5 19 14 pm](https://user-images.githubusercontent.com/971530/33796444-7502cd08-dd05-11e7-91b8-dfa677248c4c.png)

On the terminal I see the following
```
➜  ~ docker-machine create --driver vmwarefusion --vmwarefusion-boot2docker-url https://github.com/rancher/os/releases/download/v1.1.1-rc1/rancheros.iso ranchervm

Running pre-create checks...
(ranchervm) Boot2Docker URL was explicitly set to "https://github.com/rancher/os/releases/download/v1.1.1-rc1/rancheros.iso" at create time, so Docker Machine cannot upgrade this machine to the latest version.
Creating machine...
(ranchervm) Boot2Docker URL was explicitly set to "https://github.com/rancher/os/releases/download/v1.1.1-rc1/rancheros.iso" at create time, so Docker Machine cannot upgrade this machine to the latest version.
(ranchervm) Downloading /Users/mustafa/.docker/machine/cache/boot2docker.iso from https://github.com/rancher/os/releases/download/v1.1.1-rc1/rancheros.iso...
(ranchervm) 0%....10%....20%....30%....40%....50%....60%....70%....80%....90%....100%
(ranchervm) Creating SSH key...
(ranchervm) Creating VM...
(ranchervm) Creating disk '/Users/mustafa/.docker/machine/machines/ranchervm/ranchervm.vmdk'
(ranchervm) Virtual disk creation successful.
(ranchervm) Starting ranchervm...
(ranchervm) Waiting for VM to come online...
```

I also tried https://releases.rancher.com/os/latest/rancheros.iso it gave me the same result.

**Comment by niusmallnan** [comment]
@tosbaha Yes, this is not a good experience, consider improving in later versions.
You can disable this action: http://rancher.com/docs/os/v1.1/en/configuration/adding-kernel-parameters/#enabledisable-hypervisor-service-auto-enable

**Comment by niusmallnan** [comment]
Try this: https://rancher.com/docs/os/v1.x/en/installation/running-rancheros/workstation/docker-machine/#using-docker-machine-with-vmware-fusion
