### ISSUE TITLE
ACPI powerbtn doesn't work

### ISSUE THREAD

**Issue by jollytoad** [rancher/os#2176]
**RancherOS Version: (ros os version)**
1.1.0

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
baremetal (development machine)

Running RancherOS on a development machine under my desk, I'd like to be able to power it off via the power button, and i see the power acpi event is actually handled but it doesn't seem to work.

When I press the power btn I'm seeing this in the system-docker.log:

`time="2017-12-14T23:06:56.209398894Z" level=warning msg="Could not get operating system name: Error opening /usr/lib/os-release: open /usr/lib/os-release: no such file or directory"
time="2017-12-14T23:06:56.309018867Z" level=error msg="Handler for GET /containers/sbin/poweroff/json returned error: No such container: sbin/poweroff"
time="2017-12-14T23:06:56.315361861Z" level=error msg="Handler for POST /containers/create returned error: Invalid container name (/sbin/poweroff), only [a-zA-Z0-9][a-zA-Z0-9_.-] are allowed"`

I can power off by manually running `sudo poweroff` from ssh though!

**Comment by kingsd041** [comment]
Tested with RancherOS version- v1.1.2-rc2
RancherOS shutdown successfully, no error message.
