### ISSUE TITLE
Enhance ROS to create multiple user-docker daemons

### ISSUE THREAD

**Issue by jambajaar** [rancher/os#2177]
We wish to fully launch Rancher and it's agents from Rancher stacks for ease of testing Rancher itself.

E.g. 
* Given Rancher Instance "A" with an Environment "A" with 3 hosts,
* Creating a stack on Environment A with rancher/server and the rancher/agent,
* 1 host in Environment "A" runs the Rancher instance "B", with Environment "B"
* 2 hosts in Environment "A" run rancher/agents that connect to Environment :B:

This allows us to run test automation against Rancher instance B without creating dedicated VMs.

We did a spike to investigate feasibility, but as expected found the rancher/agent for Environment "B" collides with the agent running for Environment "A". 

Our request to Rancher is to provide a solution for our use-case. Two options we saw (in order of preference)
* Enhance ROS to create multiple user-docker daemons
* Enhance the rancher/agent to allow multiple simultaneous instances

**Comment by niusmallnan** [comment]
@jambajaar 
Under the scenario you are talking about, Env A and B will use the system iptable on the same host, which may bring a lot of problems.

**Comment by niusmallnan** [comment]
The users want a `Rancher in Rancher` case.
![image](https://user-images.githubusercontent.com/998984/36184878-4b37fb10-1171-11e8-8073-96783c126261.png)

The user-docker-1 starts root Rancher, and user-docker-2 starts child Rancher.
The user-docker-1 and user-docker-2 are shared host network stacks, so also share the same iptables.

This usage has the following problems:
1. There will be multiple network-managers to handle iptables rules, there is a great chance of conflict.
2. All agents share the `/var/lib/rancher` directory, we know that this directory holds the agent information. There is also a great chance of conflict.

Even if RancherOS can support multiple user-docker, but to fully meet the needs of users also need to modify Rancher itself.

I think that creating dedicated VMs is actually simple enough, we should not make the problem more complicated.

**Comment by niusmallnan** [comment]
Here are my steps about creating another user-docker daemon:
1.  Make a persistent storage directory(`/var/lib/docker2`) for this user-docker daemon.
```
#update /usr/share/ros/os-config.yml

user-volumes:
      ....
      ....
      volumes:
      - /home:/home
      - /opt:/opt
      - /var/lib/kubelet:/var/lib/kubelet
      - /var/lib/docker2:/var/lib/docker2
```

2. Add the startup script in `/etc/rc.local`, it can be done by configuring [cloud-config](http://rancher.com/docs/os/v1.2/en/configuration/running-commands/#running-docker-commands).
```
#cloud-config
write_files:
  - path: /etc/rc.local
     permissions: "0755"
     owner: root
     content: |
       #!/bin/bash
       wait-for-docker
       nohup dockerd --graph /var/lib/docker2 \
          --storage-driver overlay2 --exec-root /var/run/docker2 \
          --host unix:///var/run/docker2.sock --group docker \
          --pidfile /var/run/docker2.pid > /var/log/docker2.log 2>&1 &
```

3. reboot and check this user-docker daemon.
```
# check the docker2
$ DOCKER_HOST=unix:///var/run/docker2.sock docker info
...
...
Docker Root Dir: /var/lib/docker2
...
...
```

**Comment by will-chan** [comment]
dind way is what we prefer

**Comment by jambajaar** [comment]
@will-chan @niusmallnan the tradeoffs of each approach are not clear. 

It appears on the surface, that the RootFS approach is closer to what we were describing (except we’d prefer not to have to reboot). We wanted the ability to run multiple Docker daemons with their own console or just independent engine without a console. This may come down to simply running the console image in the new daemon, but want to make sure we’re not going to run into any limitations with the DinD approach.
 
One possible issue that comes to mind is the process tree.  If using DinD, then the child Docker engines will terminate if the console container terminates, no?  At the very least, they probably will become orphaned processes. Our expectation was that just like the console and system Docker daemon are not affected by each other’s restart/upgrade, we don’t want the additional Docker daemons affected.  All the daemons should be able to be restarted, engine version upgraded, etc. independently.

Could you provide a rundown of the pros/cons between the two approaches, and address the concern above?  That would give us more confidence in the DinD approach.

**Comment by niusmallnan** [comment]
@jambajaar 
> If using DinD, then the child Docker engines will terminate if the console container terminates, no? At the very least, they probably will become orphaned processes.

If you run DinD via user-docker:
If the console container terminates, the current user-docker will terminate.
Since each child docker daemon runs in a container via user-docker, they will terminate too.

If you run Dind via system-docker:
Each child docker engine is 100% independent. 

> All the daemons should be able to be restarted, engine version upgraded, etc. independently.

Each daemon runs in a container, users can use `docker(or system-docker) stop/start <child_docker_name>` to control each daemon.
Each daemon has its own data root, and we can make sure that the data root dir is persistent. If they want to upgrade engine version, they can remove current child docker container and run a new container with this data root.


> Our expectation was that just like the console and system Docker daemon are not affected by each other’s restart/upgrade, we don’t want the additional Docker daemons affected.

As mentioned above, each child docker is independent.

> Could you provide a rundown of the pros/cons between the two approaches?

The key point in the selection is whether each child docker engine needs independent fs and namespance.
DinD mode can, RootFS mode can not.

**Comment by MSandro** [comment]
Thank you very much @niusmallnan for your very detailed informations on how to do that. I need to add a second User-Docker via RootFS Method, but my Docker-Deamon doesn't start.

`time="2018-06-09T10:23:31Z" level=warning msg="The \"-g / --graph\" flag is deprecated. Please use \"--data-root\" instead"
time="2018-06-09T10:23:31.207416294Z" level=info msg="libcontainerd: started new docker-containerd process" pid=1778
time="2018-06-09T10:23:31Z" level=info msg="starting containerd" module=containerd revision=773c489c9c1b21a6d78b5c538cd395416ec50f88 version=v1.0.3 
time="2018-06-09T10:23:31Z" level=info msg="loading plugin "io.containerd.content.v1.content"..." module=containerd type=io.containerd.content.v1 
time="2018-06-09T10:23:31Z" level=info msg="loading plugin "io.containerd.snapshotter.v1.btrfs"..." module=containerd type=io.containerd.snapshotter.v1 
time="2018-06-09T10:23:31Z" level=warning msg="failed to load plugin io.containerd.snapshotter.v1.btrfs" error="path /var/lib/docker2/containerd/daemon/io.containerd.snapshotter.v1.btrfs must be a btrfs filesystem to be used with the btrfs snapshotter" module=containerd 
time="2018-06-09T10:23:31Z" level=info msg="loading plugin "io.containerd.snapshotter.v1.overlayfs"..." module=containerd type=io.containerd.snapshotter.v1 
time="2018-06-09T10:23:31Z" level=info msg="loading plugin "io.containerd.metadata.v1.bolt"..." module=containerd type=io.containerd.metadata.v1 
time="2018-06-09T10:23:31Z" level=warning msg="could not use snapshotter btrfs in metadata plugin" error="path /var/lib/docker2/containerd/daemon/io.containerd.snapshotter.v1.btrfs must be a btrfs filesystem to be used with the btrfs snapshotter" module="containerd/io.containerd.metadata.v1.bolt" 
time="2018-06-09T10:23:31Z" level=info msg="loading plugin "io.containerd.differ.v1.walking"..." module=containerd type=io.containerd.differ.v1 
time="2018-06-09T10:23:31Z" level=info msg="loading plugin "io.containerd.gc.v1.scheduler"..." module=containerd type=io.containerd.gc.v1 
time="2018-06-09T10:23:31Z" level=info msg="loading plugin "io.containerd.grpc.v1.containers"..." module=containerd type=io.containerd.grpc.v1 
time="2018-06-09T10:23:31Z" level=info msg="loading plugin "io.containerd.grpc.v1.content"..." module=containerd type=io.containerd.grpc.v1 
time="2018-06-09T10:23:31Z" level=info msg="loading plugin "io.containerd.grpc.v1.diff"..." module=containerd type=io.containerd.grpc.v1 
time="2018-06-09T10:23:31Z" level=info msg="loading plugin "io.containerd.grpc.v1.events"..." module=containerd type=io.containerd.grpc.v1 
time="2018-06-09T10:23:31Z" level=info msg="loading plugin "io.containerd.grpc.v1.healthcheck"..." module=containerd type=io.containerd.grpc.v1 
time="2018-06-09T10:23:31Z" level=info msg="loading plugin "io.containerd.grpc.v1.images"..." module=containerd type=io.containerd.grpc.v1 
time="2018-06-09T10:23:31Z" level=info msg="loading plugin "io.containerd.grpc.v1.leases"..." module=containerd type=io.containerd.grpc.v1 
time="2018-06-09T10:23:31Z" level=info msg="loading plugin "io.containerd.grpc.v1.namespaces"..." module=containerd type=io.containerd.grpc.v1 
time="2018-06-09T10:23:31Z" level=info msg="loading plugin "io.containerd.grpc.v1.snapshots"..." module=containerd type=io.containerd.grpc.v1 
time="2018-06-09T10:23:31Z" level=info msg="loading plugin "io.containerd.monitor.v1.cgroups"..." module=containerd type=io.containerd.monitor.v1 
time="2018-06-09T10:23:31Z" level=info msg="loading plugin "io.containerd.runtime.v1.linux"..." module=containerd type=io.containerd.runtime.v1 
time="2018-06-09T10:23:31Z" level=info msg="loading plugin "io.containerd.grpc.v1.tasks"..." module=containerd type=io.containerd.grpc.v1 
time="2018-06-09T10:23:31Z" level=info msg="loading plugin "io.containerd.grpc.v1.version"..." module=containerd type=io.containerd.grpc.v1 
time="2018-06-09T10:23:31Z" level=info msg="loading plugin "io.containerd.grpc.v1.introspection"..." module=containerd type=io.containerd.grpc.v1 
time="2018-06-09T10:23:31Z" level=info msg=serving... address="/var/run/docker2/containerd/docker-containerd-debug.sock" module="containerd/debug" 
time="2018-06-09T10:23:31Z" level=info msg=serving... address="/var/run/docker2/containerd/docker-containerd.sock" module="containerd/grpc" 
time="2018-06-09T10:23:31Z" level=info msg="containerd successfully booted in 0.006062s" module=containerd 
time="2018-06-09T10:23:31.232211892Z" level=error msg="'overlay2' is not supported over overlayfs"
Error starting daemon: error initializing graphdriver: backing file system is unsupported for this graph driver`

I am not sure what I've doen wrong? It would be very nice if you could help me.
Thank you very much.

**Comment by niusmallnan** [comment]
@MSandro you probably forgot to make a persistent storage directory(/var/lib/docker2) for another user-docker daemon. Please refer to the `Preparations`.
If you do not do this, the directory is `overlayfs`, then you can get those logs.

Don't forget to reboot, the directory will be generated after reboot.

**Comment by MSandro** [comment]
Okay, I now use DinD mode (Case B) but how can I access the docker2 folder? I've added the persisten volume to the /usr/share/ros/os-config.yml but I have no /var/lib/docker2 in my rancher debian console.

**Comment by niusmallnan** [comment]
Oh, seems to know what happened, you can check the Debian console: `system-docker inspect console`.
I think you cannot see `/var/lib/docker2` in `Mounts`. This is because the debain console is persistent and it will not be rebuilt so the new Mount directory(`/var/lib/docker2`) cannot be obtained.

You have two options to fix it:
1. Switch to default console
2. Change the label `io.docker.compose.rebuild` to `always` for debian console.

**Comment by MSandro** [comment]
Thank you very much, where I have to change the laben? In /usr/share/ros/os-config.yml? And Do I have to restart my system for changing the console? I already defined the console: debian in the cloud_config.yml
And I am not able to change the console with the ros console switch command.

**Comment by kingsd041** [comment]
Multiple user-docker daemons is already supported in rancheros v1.5.0-rc2.
