### ISSUE TITLE
Config ROS image prefix for install and all rancher/os services

### ISSUE THREAD

**Issue by jambajaar** [rancher/os#2178]
We use artifactory for docker.io caching.

A normal `docker pull rancher/os` can be cached as `docker pull dockerhub.mycompanyname.com/docker.io/rancher/os` 

However, we have no way to inject a prefix into Rancher os for installation or service pulls.

We'd like a global prefix we can add to force ROS to always use our mirror.

**Comment by niusmallnan** [comment]
@jambajaar 
Have you tried to custom your upgrade-sources: http://rancher.com/docs/os/v1.1/en/upgrading/#custom-upgrade-sources

**Comment by niusmallnan** [comment]
I will support this feature in v1.3.0, users can config a global image prefix:
```
ros config set rancher.environment.REGISTRY_DOMAIN xxxx.yyy
```

**Comment by kingsd041** [comment]
Tested with rancheros-v1.3.0-rc1.
The use of `ros config set rancher.environment.REGISTRY_DOMAIN xxxx.yyy` to configure the image prefix is now supported.

Like below:
```
# ros console switch ubuntu
Switching consoles will
1. destroy the current console container
2. log you out
3. restart Docker
Continue [y/N]: y
ERRO[0003] Missing the image: Error: No such image: registry.cn-hangzhou.aliyuncs.com/rancher/os-ubuntuconsole:v1.3.0
Pulling console (registry.cn-hangzhou.aliyuncs.com/rancher/os-ubuntuconsole:v1.3.0)...
```
