### ISSUE TITLE
rancher.password doesn't work at all.

### ISSUE THREAD

**Issue by KyleSanderson** [rancher/os#2181]
**RancherOS Version: (ros os version)**
v1.1.1

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
baremetal OVH

Steps to reproduce:
* Have Rancher not startup properly due to a network issue...
* Boot into recovery and have no avenue to change the password from a chroot.
* Set rancher.password in cloud-config.yml
  - ros config set rancher.password motherfucker
* Reboot.
* Be unable to login to RancherOS because rancher.password is ignored, and passwd is overwritten on boot.

**Comment by vincent99** [comment]
`rancher.password` is a kernel parameter, not part of the cloud-config.

**Comment by niusmallnan** [comment]
@KyleSanderson 
Have you tried to add  `rancher.password` to the kernel parameters.
http://rancher.com/docs/os/v1.1/en/configuration/adding-kernel-parameters/

**Comment by niusmallnan** [comment]
Close it.
If you still have doubts, please reopen it and let me know.
