### ISSUE TITLE
rancheros should support azerty keymap

### ISSUE THREAD

**Issue by hdep** [rancher/os#2182]
**RancherOS Version: (ros os version)**
V1.1.1
**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
On vmware esxi 6.0

when you boot rancheros the only keymap available is qwerty. This cause big trouble when you have an azerty keyboard especially for initial configuration.

Some report has been made on the forum.
https://forums.rancher.com/t/change-keyboard-layout-to-german/4510

Has the loadkmap command is already present to the file system you can just drop into the image a  binary keyboard translation table from stdin.

I would specify that the isue only occur in console mode.

**Comment by hdep** [comment]
Any update on this request  ?

**Comment by bd8392** [comment]
+1 more keymaps should be possible for configuration

**Comment by fmichaud** [comment]
+1 to improve i18n keymaps support.

**Comment by hdep** [comment]
since 2017 won't be fixed
