### ISSUE TITLE
No such service: hyperv-vm-tools

### ISSUE THREAD

**Issue by Ankh-** [rancher/os#2187]
**RancherOS Version: (ros os version)**
v1.1.1
**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
Hyper-V on Windows Server 2016 Std

I don't know if it is needed but my cloud-config.yml included:

>   services_include:
>     hyperv-vm-tools: true

Sadly the service is not installed?

> [rancher@rancher boot]$ sudo ros s restart hyperv-vm-tools
> ERRO[0000] non-200 http response: 404
> ERRO[0000] Failed to load service(hyperv-vm-tools): non-200 http response: 404
> INFO[0000] Project [os]: Restarting project
> INFO[0000] Project [os]: Project restarted
> No such service: hyperv-vm-tools

**Comment by niusmallnan** [comment]
@Ankh- 
This has been fixed by  v1.1.2-rc2.
see: https://github.com/rancher/os/issues/2168

Next release v1.1.2 will not have this problem.

**Comment by Ankh-** [comment]
Ah! Search revealed nothing.
