### ISSUE TITLE
Release Notification Channels (Webhooks)

### ISSUE THREAD

**Issue by allingeek** [rancher/os#2192]
Today we're looking at automating reactions to RancherOS releases. Today, a human periodically looks at the README and visually parses the latest stable release AMI. While this has served us well in development, we'd like to take a more event-driven approach. In lieu of an active release notification event published by Rancher we're looking at periodically parsing the GitHub releases atom feed for "newer" releases without an `rc` suffix and searching the AMI marketplace for the official AMI with the relevant tag. This integration takes several "conventions" as interface which makes the whole thing too fragile for production systems. 

We'd ideally prefer lifecycle channel subscriptions. Consider a release hook that pushes various lifecycle events - and relevant references to release artifacts - via release phase specific topics e.g. stable, rc, dev. The notification payload should include the following details:

    {
      "version": "1.1.1",
      "major": "1",
      "minior": "1",
      "patch": "1",
      "engine": "Docker 17.03.2-ce",
      "kernel": "Linux 4.9.67",
      "artifacts": {
        "iso": "https://releases.rancher.com/os/v1.1.1/rancheros.iso",
        "initrd": "https://releases.rancher.com/os/v1.1.1/initrd",
        "openstack": "https://releases.rancher.com/os/v1.1.1/rancheros-openstack.img",
        "digitalocean": "https://releases.rancher.com/os/v1.1.1/rancheros-digitalocean.img",
        "ipxe": "https://releases.rancher.com/os/v1.1.1/rancheros.ipxe",
        "gce": "https://releases.rancher.com/os/v1.1.1/rancheros-gce.tar.gz",
        "rootfs": "https://releases.rancher.com/os/v1.1.1/rootfs.tar.gz",
        "vmlinuz": "https://releases.rancher.com/os/v1.1.1/vmlinuz",
        "ami-hvm": {
          "ap-south-1": ...,
          "eu-west-2": ...,
          "eu-west-1": ...,
          "ap-northeast-2": ...,
          "ap-northeast-1": ...,
          "sa-east-1": ...,
          "ca-central-1": ...,
          "ap-southeast-1": ...,
          "ap-southeast-2": ...,
          "eu-central-1": ...,
          "us-east-1": "ami-4584ec3f",
          "us-east-2": "ami-4695bc23",
          "us-west-1": "ami-d24e4ab2",
          "us-west-2": "ami-99cb6de1",
        }
      }
    }

Such a notification might be publishable via release pipeline, however the sensitive nature of these messages will make authentication "tricky." Where some users will use these notifications as notifications, others will use them to drive deployment automation. The HTTPS webhook path might contain a secret - this is what Slack does - allowing the recipient to make the assertion that the sender is allowed to send the notification and is therefore trustworthy. However, unless the webhook is actually treated like a secret by Rancher then this is bound to become a security risk. I'd alternatively suggest a trust-but-verify model where Rancher pushes these notifications without critical reaction data such as artifact references. Instead include a single reference to the authoritative event hosted on an HTTPS rancher.com URL. That even might look like:

    {
      "version": "1.1.1",
      "major": "1",
      "minior": "1",
      "patch": "1",
      "engine": "Docker 17.03.2-ce",
      "kernel": "Linux 4.9.67",
      "event_url": "https://api.rancher.com/os/release/v1.1.1"
    }

The document returned by the `event_url` would then contain the full document including the `artifacts` map. Publishing events in this way leverages Rancher's existing HTTPS infrastructure. Realistically, Rancher could simply host these documents in an S3 bucket with HTTPS enabled. There is little need for complicated server side logic here.

**Comment by niusmallnan** [comment]
Great idea.
But I think that it might not be too urgent.

**Comment by allingeek** [comment]
The biggest feature gap between RancherOS and CoreOS is the automatic update mechanism. I prefer disposable infrastructure and so we need something to close that gap. If we cannot find some way of reasonably automating reactions to Rancher updates then the management pain might soon outweigh that of dealing with Systemd. I guess, this is me saying that release deployment automation is important. How do your other adopters react to patches or other releases?

**Comment by niusmallnan** [comment]
@allingeek 
We have just discussed it internally.
We will add it to milestone v1.1.3, please be patient.

**Comment by allingeek** [comment]
Hey,

Just realized that, at a minimum this could be addressed by including the release artifacts like AMIs, etc in [https://releases.rancher.com/os/releases.yml](https://releases.rancher.com/os/releases.yml).

**Comment by niusmallnan** [comment]
Hi @allingeek ,
> Just realized that, at a minimum this could be addressed by including the release artifacts like AMIs

I added some files including the release artifacts, you can use like this:
```
curl -sSL https://releases.rancher.com/os/latest/artifact.json | jq .
# or
curl -sSL https://releases.rancher.com/os/v1.2.0/artifact.json | jq .
```

Not sure whether this can mitigate your problem.

For us, it is expensive to maintain a webhook server. 
Do you know which public services can support webhook server? if so, feel free to let me know.
