### ISSUE TITLE
custom os-kernel build issue

### ISSUE THREAD

**Issue by dduquesne** [rancher/os#2212]
Hello,

I have an issue to build a custom kernel for RancherOS.
I am using the os-kernel-4.9.40-rancher version/tag :  https://github.com/rancher/os-kernel/tree/v4.9.40-rancher.
My compilation machine is a clean EC2 Ubuntu instance. I unzipped the project into this instance and I have added a file into the project patches folder. 
This is the RT patch : https://www.kernel.org/pub/linux/kernel/projects/rt/4.9/older/
I am using patch-4.9.40-rt30.patch
It implies to change the Kernel conf a little bit so i changed the os-kernel-master/config/kernel-config file by adding
CONFIG_PREEMPT=y
CONFIG_PREEMPT_RT_BASE=y
CONFIG_PREEMPT_RT_FULL=y
After that, i followed the step bellow :

**// Install build tools**
sudo apt-get update
sudo apt-get install build-essential checkinstall
sudo apt-get install cvs subversion git-core mercurial

**// Install GO**
sudo apt-get install golang-go
mkdir /home/ubuntu/go
export GOPATH=/home/ubuntu/go
export PATH=$PATH:/home/ubuntu/go
export PATH=$PATH:/home/ubuntu/go/bin
go get github.com/aktau/github-release

**// GIT config using a personal GITHUB repo**
cd os-kernel-4.9.40-rancher
git config --global user.name "dduquesne" 
git config --global user.email xxxxxxxxxxxxxxxxxxxxxxxxxx
git init
git add .
git commit <--- "nothing to commit"
git remote add origin https://github.com/dduquesne/os.git
git push -u origin master
git tag 1 && git push --tags

**// Install and configure github-release** 
export GITHUB_TOKEN=xxxxxxxxxxxxxxxxxxxx
github-release info -u dduquesne -r os-kernel

**// Install Docker**
sudo apt-get install \
apt-transport-https \
ca-certificates \
curl \
software-properties-common

curl -fsSLhttps://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo apt-key fingerprint 0EBFCD88
sudo add-apt-repository \
"deb [arch=amd64] https://download.docker.com/linux/ubuntu\
$(lsb_release -cs) \
stable"

sudo apt-get update
sudo apt-get install docker-ce
sudo groupadd docker
sudo usermod -aG docker ubuntu

**// Reboot 
// Try to compile**
cd os-kernel-4.9.40-rancher
GITHUB_TOKEN=xxxxxxxxxxxxxxxxxxxxx KERNEL_TAG=4.9.40 make

The compilation seems to work but there is an issue before the end :

tar: ./boot/vmlinuz-4.9.40-rancher: Not found in archive
tar: ./boot/System.map-4.9.40-rancher: Not found in archive
tar: Exiting with failure status due to previous errors
time="2017-12-22T13:59:16Z" level=fatal msg="exit status 2"  

The full log file is in attachment **ci.log**
I also attach Dockerfile.dapper, kernel-config and my patch file.
If someone could help with some advice or clarification regarding the workflow.
I am not sure to fully understand everything.
It seems that some files are missing in my environment.

Many thanks for your help :)
[DockerKernel.zip](https://github.com/rancher/os/files/1610957/DockerKernel.zip)

**Comment by niusmallnan** [comment]
It seems like your kernel version became `4.9.40-rt30-rancher`, not `4.9.40-rancher`.

I saw these logs:
```
88569   DEPMOD  4.9.40-rt30-rancher^M
88570 './System.map' -> './tar-install/boot/System.map-4.9.40-rt30-rancher'^M
88571 './.config' -> './tar-install/boot/config-4.9.40-rt30-rancher'^M
88572 './vmlinux' -> './tar-install/boot/vmlinux-4.9.40-rt30-rancher'^M
88573 './arch/x86/boot/bzImage' -> './tar-install/boot/vmlinuz-4.9.40-rt30-rancher'
```

Maybe there are some bugs for `os-kernel` repo.

**Comment by dduquesne** [comment]
I did not notice that.
That can explain the issue.
Does it is a side effect from the rt patch ?
I can't rise any bug on the os-kernel repo.
Is there anything wrong in my workflow ?
I understand each step individualy but not the full purpose of the whole think. I am expecting an iso file or a docker image reusable for a later OS build.
Many thanks for your feedback.

**Comment by niusmallnan** [comment]
> Does it is a side effect from the rt patch ?

Yes, the patch makes the kernel version changed to `4.9.40-rt30-*`.

> Is there anything wrong in my workflow ?

Basically correct.

> I can't rise any bug on the os-kernel repo.

If you find the root cause, you can make a PR to `os-kernel`.
Here you can rise any bug.

**Comment by dduquesne** [comment]
I am really not familiar with the diff/patch syntax but maybe i found something line 24481.
Perhaps i could solve this issue by removing the bold line below. It seems that the the patch provide this additional suffix in a dedicated new file. I assume that it should use it somewhere else to rename the resulting files :

diff --git a/localversion-rt b/localversion-rt
new file mode 100644
index 000000000000..b72862e06be4
--- /dev/null
+++ b/localversion-rt
@@ -0,0 +1 @@
**+-rt30**
