### ISSUE TITLE
Upgrade v1.0.4 to v1.1.3 resets console to default

### ISSUE THREAD

**Issue by jdel** [rancher/os#2214]
**RancherOS Version: (ros os version)**
ROS v1.0.4 upgraded to v1.1.3

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
ROS is run on a VMWare infrastructure.

I upgraded my testing environment from ROS v1.0.4 to v1.1.3 and the console is reset to default.
The debian console, originally configured via cloud-config, is still enabled, but not active.
This generates two problems:
  - I cannot use Ansible anymore to manage my servers
  - I have to reboot my servers a second time, manually

There was already a similar issue with v1.1.0 which made me rollback to v1.0.4 https://github.com/rancher/os/issues/2129

I understand the focus is on Rancher 2.0, but this is making each ROS upgrade way more painful than it used to be.

**Comment by niusmallnan** [comment]
Hi, @jdel 
I have tried to upgrade v1.0.4 to v1.1.3 with Debian console enabled.
No problem happened.

Can you share your `/var/log/boot/ros-sysinit.log` logs?

**Comment by jdel** [comment]
Thanks for pointing me to this particular log.... There is something weird there:

```
time="2018-01-08T16:01:21Z" level=debug msg="LoadFromNetwork(https://raw.githubusercontent.com/rancher/os-services/v1.1.3/o/open-vm-tools.yml)"
time="2018-01-08T16:01:21Z" level=debug msg="LoadFromNetwork(https://raw.githubusercontent.com/rancher/os-services/v1.1.3/o/open-vm-tools.yml) returned <nil>, Get https://raw.githubusercontent.com/rancher/os-services/v1.1.3/o/open-vm-tools.yml: dial tcp: lookup raw.githubusercontent.com on 8.8.4.4:53: dial udp 8.8.4.4:53: connect: network is unreachable"
time="2018-01-08T16:01:21Z" level=error msg="Get https://raw.githubusercontent.com/rancher/os-services/v1.1.3/o/open-vm-tools.yml: dial tcp: lookup raw.githubusercontent.com on 8.8.4.4:53: dial udp 8.8.4.4:53: connect: network is unreachable"
time="2018-01-08T16:01:21Z" level=error msg="Failed to load service(open-vm-tools): Get https://raw.githubusercontent.com/rancher/os-services/v1.1.3/o/open-vm-tools.yml: dial tcp: lookup raw.githubusercontent.com on 8.8.4.4:53: dial udp 8.8.4.4:53: connect: network is unreachable"
time="2018-01-08T16:01:21Z" level=debug msg="LoadFromNetwork(https://raw.githubusercontent.com/rancher/os-services/v1.1.3/d/debian.yml)"
time="2018-01-08T16:01:21Z" level=debug msg="LoadFromNetwork(https://raw.githubusercontent.com/rancher/os-services/v1.1.3/d/debian.yml) returned <nil>, Get https://raw.githubusercontent.com/rancher/os-services/v1.1.3/d/debian.yml: dial tcp: lookup raw.githubusercontent.com on 8.8.4.4:53: dial udp 8.8.4.4:53: connect: network is unreachable"
time="2018-01-08T16:01:21Z" level=error msg="Get https://raw.githubusercontent.com/rancher/os-services/v1.1.3/d/debian.yml: dial tcp: lookup raw.githubusercontent.com on 8.8.4.4:53: dial udp 8.8.4.4:53: connect: network is unreachable"
time="2018-01-08T16:01:21Z" level=error msg="Failed to load rancher.console=(debian): Get https://raw.githubusercontent.com/rancher/os-services/v1.1.3/d/debian.yml: dial tcp: lookup raw.githubusercontent.com on 8.8.4.4:53: dial udp 8.8.4.4:53: connect: network is unreachable"
time="2018-01-08T16:01:21Z" level=debug msg="Using /proc/version to set rancher.environment.KERNEL_VERSION = 4.9.75-rancher"
```

**Comment by jdel** [comment]
From the logs above, I don't see `8.8.4.4` anywhere in my configuration.
ROS is set to use my internal DNS, which is set to forward to my cloud provider's DNS.

So I upgraded another ROS VM, on my prod environment this time.

Start from ROS v1.0.4 running happily with debian console.

```
rancher@ops-node-04:~$ sudo ros console list
disabled alpine
disabled centos
current  debian
disabled default
disabled fedora
disabled ubuntu
```

Stage the upgrade then upgrade:

```
rancher@ops-node-04:~$ sudo ros os upgrade -i rancher/os:v1.1.3 -f -s
Upgrading to rancher/os:v1.1.3
Pulling os-upgrade (rancher/os:v1.1.3)...
v1.1.3: Pulling from rancher/os
2fdfe1cd78c2: Pull complete
a22481f54275: Pull complete
8035a739a06f: Pull complete
a03bac5dc2c3: Pull complete
1bd78b5e4957: Pull complete
ade6ec8f65aa: Pull complete
70b5de5c4547: Pull complete
f1130bc287ee: Pull complete
277e65b618e4: Pull complete
f4c01864ecfe: Pull complete
Digest: sha256:3176f260a31fe591d8ba3111a4c1d462fcc8aa86476f8019c95bdc665e1ce021
Status: Downloaded newer image for rancher/os:v1.1.3

rancher@server-name:~$ sudo ros os upgrade -i rancher/os:v1.1.3 -f
Upgrading to rancher/os:v1.1.3
os-upgrade_1 | Installing from :v1.1.3
> INFO[0001] Rebooting
time="2018-01-09T14:14:06Z" level=info msg="Setting reboot timeout to 60 (rancher.shutdown_timeout set to 60)"
time="2018-01-09T14:14:06Z" level=info msg="Stopping /docker : b98e9eff3094"
time="2018-01-09T14:14:09Z" level=info msg="Stopping /ntp : d5a93ab33fe1"
time="2018-01-09T14:14:09Z" level=info msg="Stopping /network : ea318872080d"
time="2018-01-09T14:14:09Z" level=info msg="Stopping /udev : 8655fab360ca"
time="2018-01-09T14:14:09Z" level=info msg="Stopping /syslog : 3b76393154ee"
time="2018-01-09T14:14:09Z" level=info msg="Stopping /acpid : b4058f223faa"
time="2018-01-09T14:14:10Z" level=info msg="Console Stopping [/console] : c1f195c928be"
Connection to server-name.domain.tld closed by remote host.
```

After reboot, the console is back to default, but debian is still enabled, so I tried to reboot to see if it would switch back to debian console:

```
[rancher@server-name ~]$ sudo ros console list
disabled alpine
disabled centos
enabled  debian
current  default
disabled fedora
disabled ubuntu

[rancher@server-name ~]$ sudo reboot
[            ] reboot:info: Setting reboot timeout to 60 (rancher.shutdown_timeout set to 60)
[            ] reboot:info: Setting reboot timeout to 60 (rancher.shutdown_timeout set to 60)
[            ] reboot:info: Stopping /docker : 06594dd8bdc3
[            ] reboot:info: Stopping /ntp : 6db4b3163225
[            ] reboot:info: Stopping /network : 2fc156697640
[            ] reboot:info: Stopping /udev : b80e355e487d
[            ] reboot:info: Stopping /system-cron : 042fa03a769f
[            ] reboot:info: Stopping /acpid : 82c073b97a6d
[            ] reboot:info: Stopping /syslog : ebc1d8a4624a
[            ] reboot:info: Console Stopping [/console] : 67816d413e03

[rancher@server-name ~]$ sudo ros console list
disabled alpine
disabled centos
enabled  debian
current  default
disabled fedora
disabled ubuntu
```

Still the same, console doesn't get upgraded and enabled. 

Even if it shows debian console as enabled, enabling it manually and rebooting restores it to the new debian console.

This is when upgrading without `--upgrade-console` but I have done all my testing nodes yesterday with  `--upgrade-console`  to the same result.

**Comment by jdel** [comment]
Ok, so I have done  a few more tests.

As suggested in https://github.com/rancher/os/issues/1750#issuecomment-325522196, and using `sudo system-docker run --rm -it -v /:/host alpine vi /host/boot/global.cfg ` ([doc](http://rancher.com/docs/os/v1.0/en/configuration/adding-kernel-parameters/)) I added `rancher.network.dns.nameservers="['1.2.3.4','5.6.7.8']"` ([doc](http://rancher.com/docs/os/v1.0/en/configuration/#setting-values)) to global.cfg.

Doing this before the `ros os upgrade` command just discards the options after the reboot and uses the default console.
Doing it after the `ros os upgrade` command, but before the reboot, and rebooting afterwards results in a kernel panic.

What am I doing wrong here ? Is the syntax correct for `rancher.network.dns.nameservers="['1.2.3.4','5.6.7.8']"` ?

**Comment by niusmallnan** [comment]
I used `rancher.network.dns.nameservers=["1.2.3.4","5.6.7.8"]` in boot cmdline, It can work well.

We use `8.8.8.8` and `8.8.4.4` as the default nameservers, I guess you have modified this value in cloud-init config.
But when switching the console during startup, cloud-init is not loaded yet. At that time, the default nameservers are used, but kernel parameters(boot cmdline) can take effect.

**Comment by jdel** [comment]
I've done a few more upgrades. The right syntax to add DNS servers in the kernel line is `her.network.dns.nameservers=["1.2.3.4","5.6.7.8"]`. Double quotes can be substituted for single quotes too.

For some reason I cannot explain, setting my cloud provider's DNS in there doesn't solve the issue. I still get the timeout.

However, setting my internal DNS (that resolves a local zone and forwards unknown names to my cloud provider's DNS) seems to work.

In the logs, I can still see that the vmware tools image times out, but just after, the debian console downloads successfully.

I have no idea why but it looks like some timing issue. Maybe using my local forwarder adds the tiny bit of time the network needs to be up before getting the yml files ?
In the ros-sysinit log I can definitely see that network is starting `[12/19] [network]: Starting`, maybe it takes too long to start ?

All DNS I tried are working fine and I can use any of them to resolve names when ROS is booted up. 

@niusmallnan : If you have a chance to ping me on slack I can send you the ros-sysinit logs.

**Comment by niusmallnan** [comment]
@jdel 
I am on a business trip these days.
My email niusmallnan@gmail.com, feel free to send me anything.
Thanks.

**Comment by jdel** [comment]
It seems that the issue is caused by some network delay introduced by my cloud provider's VM hypervisor or something. Not related to ROS, closing.

**Comment by rbucker** [comment]
I would like to reopen this issue as it is back in RancherOS 1.20. Although it works in ROS 1.10.

```
$ docker-machine --version
docker-machine version 0.13.0, build 9ba6da9
```
