### ISSUE TITLE
OS upgrades don't upgrade rancher/container-crontab

### ISSUE THREAD

**Issue by robbertkl** [rancher/os#2215]
**RancherOS Version: (ros os version)**
v1.1.3
**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
QEMU VPS

I've updated a couple of times, but just noticed I now have a `system-cron` container running in system-docker, which has image `rancher/container-crontab:v0.1.0`. This seems to be a Rancher-related image, and not part of RancherOS? Anyway, I've noticed the image tag is still at v0.1.0, while newer versions (up to v0.3.0) are already out for a long while.

Could it be this image is not upgraded during a `ros os upgrade`?

**Comment by niusmallnan** [comment]
Thanks.
We will test to verify if we can use `container-crontab:v0.3.0` in RancherOS.

**Comment by niusmallnan** [comment]
Try to use image `rancher/container-crontab:v0.3.0`, and get these error logs:
```
time="2018-01-15T05:18:51Z" level=info msg="Starting Cron"
time="2018-01-15T05:18:51Z" level=fatal msg="Error response from daemon: client is newer than server (client API version: 1.26, server API version: 1.23)"
```
Currently,  there is no need to upgrade to v0.3.0.
