### ISSUE TITLE
Docker engine version tied to ros version?

### ISSUE THREAD

**Issue by narcoticfresh** [rancher/os#2220]
**RancherOS Version: (ros os version)**
v1.1.3

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
vSphere VMs

**What is my problem?**
We are currently very badly affected (as many others it seems) by moby/moby#30134 in our swarm cluster - container IPs in the cluster get mixed up badly sometimes which creates chaos and service interruptions.

This seems to be improved and/or fixed with `>=docker-17.10.0-ce`.

Are docker engine versions in ros strictly tied to new releases? When could we plan on receiving 17.10 or 17.12 - will that only (and only maybe) be with the next ros release?

Or is there any simple possibility to add new engine versions ourselves? What side effects could arise on the system?

I've noticed that in the v1.1.2 ros release support for more engines were added - since then, no newer engine versions. 

Also i've seen there that @djmaze created some kind of repository with new versions - any documentation on how to do that? That sounds like a way we could test this ourselves. The [documented way](http://rancher.com/docs/os/v1.1/en/configuration/switching-docker-versions/) seems outdated as the linked example file is non existent anymore(?)

Thanks for any help and for this great project!

**Comment by vincent99** [comment]
Since Docker changed to edge be Strutzeberg releases we have planned to only support stable versions.  The latest (17.12) was released recently and the next version of RancherOS will support it.  There has been a bit of an interruption from meltdown/Spectre fallout.

The example file is missing because it was replaced with a newer 1.12.x at some point and the docs link wasn't updated... https://github.com/rancher/os-services/tree/master/d

**Comment by narcoticfresh** [comment]
@vincent99 
Thanks for your comment..

ACK; a google search didn't reveal any roadmap for rancher os - is there any? is there any way to estimate when that new release could come out?

I just ask so we can estimate if it's worth to try this ourselves or we just can wait a certain time, maybe some weeks.. or will it be more like months? ;-)

**Comment by narcoticfresh** [comment]
I noticed that a service file is already [present here](https://github.com/rancher/os-services/blob/master/d/docker-17.12.0-ce.yml).. 

So i configured this in my `user_config.yml`:

```
rancher:
  docker:
    engine: https://raw.githubusercontent.com/rancher/os-services/master/d/docker-17.12.0-ce.yml
```

But somehow, after the reboot, the new version is not applied, i still have:

```
root@swarm-manager:/var/log/boot# docker info
Containers: 7
 Running: 7
 Paused: 0
 Stopped: 0
Images: 486
Server Version: 17.06.2-ce
```

Did I miss something, maybe something that is not documented?

**Comment by narcoticfresh** [comment]
Tracking in own issue
