### ISSUE TITLE
Raspberry Pi imags?

### ISSUE THREAD

**Issue by prologic** [rancher/os#2224]
Where are the latest Raspberry Pi images? I don't see them in the releases page (*unless I'm missing something?*) Only issue that came close to poking around was #1794 but that was a while ago.

**Comment by prologic** [comment]
Answering my own question looks like there is one for v1.1.2 => https://github.com/rancher/os/releases/download/v1.1.2-rc2/rancheros-raspberry-pi64.zip

Are we not auto-building these? There isn't one for v1.1.3 AFAICT.

**Comment by niusmallnan** [comment]
v1.1.2 https://github.com/rancher/os/releases/download/v1.1.2/rancheros-raspberry-pi64.zip

v1.1.3 just fixed the problem of AMDX86, no change for ARM.

**Comment by ulm0** [comment]
Seems like it's been dropped at least for arm32, as stated in #2207 by @niusmallnan

**Comment by prologic** [comment]
I see -- buat arm64 images are still being built and uploaded to the GIthub
releases?


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by olljanat** [comment]
Raspberry PI images have been uploaded to https://github.com/rancher/os/releases for all recent versions so can actually close this one?

**Comment by nunofgs** [comment]
What happened to the raspberry pi 2 images? :(

**Comment by ulm0** [comment]
They're arm32, and RancherOS is supporting arm64.On Jul 23, 2018 13:58, Nuno Sousa <notifications@github.com> wrote:What happened to the raspberry pi 2 images? :(
