### ISSUE TITLE
[os-images] Build RancherOS using custom RancherOS-Kernel

### ISSUE THREAD

**Issue by dduquesne** [rancher/os#2227]
Hello,

I would like to build a custom RancherOS.
I already built a custom Kernel.
So i have these files : 
- build-linux-4.9.40-rancher-x86.tar.gz
- config
- extra-linux-4.9.40-rancher-x86.tar.gz
- linux-4.9.40-rancher-src.tgz
- linux-4.9.40-rancher-x86.tar.gz

But i am not sure about the following steps.
It seems that i should :
- Rename linux-4.9.40-rancher-x86.tar.gz to kernel.tar.gz
- Put all these files into the os/asset folder
- Run the OS build

But it does not work.
I have an iso at the end but component are missing (I can boot on it and that it).
So i assume that i need to add os-service : https://github.com/rancher/os-services/blob/master/README.md

But i have no idea how to process.
It seems that these additionnal service needs : 
- build-linux-4.9.40-rancher-x86.tar.gz
- extra-linux-4.9.40-rancher-x86.tar.gz

But i am not sure and i don't know how to provide that (Github ? Dedicated folder ?)
If anyone can help me by clarifying the process.

Many thanks :)

**Comment by niusmallnan** [comment]
Update `Dockerfile.dapper` file in the `rancher/os` repo:
```
# Update the URL to your own custom kernel tarball
ARG KERNEL_VERSION_amd64=xxxx-rancher
ARG KERNEL_URL_amd64=http://xxxx-rancher-x86.tar.gz
```
 Then run `make`

**Comment by dduquesne** [comment]
Hello,

Thanks for your help.
I made some modifications in the Dockerfile.dapper : 
ARG OS_REPO=rancher
ARG KERNEL_VERSION_amd64=4.9.40-rancher
ARG OS_SERVICES_REPO=https://github.com/rancher/os-services.git

Make gave me an ISO file.
It works but i have an issue with the command : sudo ros service list

![image](https://user-images.githubusercontent.com/12520088/35239462-d5602b8c-ffb0-11e7-8e7e-4b558a90b337.png)

In addition, i would like to modify the file /sys/fs/cgroup/cpu,cpuacct/cpu.rt_runtime_us but i can't get the permission (Even as root).
Is there any way to modify this file from the rancher console service or from the cloud init configuration ?

**Comment by niusmallnan** [comment]
I don't know why you change the `OS_SERVICES_REPO`?
```
ARG OS_SERVICES_REPO=https://github.com/rancher/os-services.git
```

> In addition, i would like to modify the file /sys/fs/cgroup/cpu,cpuacct/cpu.rt_runtime_us but i can't get the permission (Even as root).

```
[docker@rancheros-v120rc1 ~]$ sudo su
[root@rancheros-v120rc1 docker]# echo 1024 > /sys/fs/cgroup/cpu/cpu.shares
```

**Comment by dduquesne** [comment]
Hello Niusmallnan,

Thank for your feedback.
I recompile everything.
Kernel 4.9.76
Rancher OS 1.1.3

![image](https://user-images.githubusercontent.com/12520088/35271766-6ba0eb54-0033-11e8-89ca-5cd3801012ef.png)

As you suggested, i did not touch OS_SERVICES_REPO.
My issue with "ros service list" disappeared :)

But i still have an issue with cpu.rt_runtime_us
I can change cpu.shares like you did but not /sys/fs/cgroup/cpu,cpuacct/cpu.rt_runtime_us
![rt_runtime_us](https://user-images.githubusercontent.com/12520088/35271428-5f3eba90-0032-11e8-8829-bb4637f8f318.PNG)

**Comment by niusmallnan** [comment]
It reports `invalid argument` and I'm not sure that this is the correct argument.
If you confirm this can work in other Linux distributions, I will check it.
