### ISSUE TITLE
Clock drift / NTP setup

### ISSUE THREAD

**Issue by GitterDoneScott** [rancher/os#2228]
**RancherOS Version: 1.0.5**
**Where are you running RancherOS?: Bhyve VM running on FreeBSD 10 x86 **

I'm experiencing clock drift between the FreeBSD (host) and the Bhyve guest (ROS).  I'd like to setup NTP to solve the issue but haven't been able to find any documentation on how to do so.

Is there another way to solve the problem?

Thank you!

**Comment by niusmallnan** [comment]
We have built-in ntpd, its configuration file is `/etc/ntp.conf`.

Please refer to `http://rancher.com/docs/os/v1.1/en/configuration/write-files/#writing-files-in-specific-system-services`

**Comment by GitterDoneScott** [comment]
Thank you!  I'll give that a try and let you know how it goes.

**Comment by GitterDoneScott** [comment]
That worked!  I merged the example in the link above with `sudo ros config -merge` and time appears to stay synced.
