### ISSUE TITLE
Base ubuntu console image on LTS release

### ISSUE THREAD

**Issue by superseb** [rancher/os#2230]
**RancherOS Version: (ros os version)**
`v1.1.3`

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
`docker-machine`

Current ubuntu console image is based on Ubuntu 17.04 which is EOL per January 13th, 2018. (https://wiki.ubuntu.com/Releases)

Console based on LTS release would probably be best.

**Comment by niusmallnan** [comment]
We already have ubuntu-console v1.2.0-rc1 on `os-services` master, but it is based on Ubuntu 17.10.

I do agree to update the console based on LTS release.

**Comment by 2devnull** [comment]
I have a script from software vendor that checks name of ubuntu release to install its software. To my surprise the ubuntu console is zesty and the script does not work (will have to now modify the script). Would be nice to do something list 'sudo ros console switch ubuntu:xenial'

**Comment by kingsd041** [comment]
Tested with RancherOS v1.2.0-rc2.
Ubuntu console is based on Ubuntu 16.04.3 LTS.
