### ISSUE TITLE
1.1.0 to 1.1.3: Agent dies in loop

### ISSUE THREAD

**Issue by kapolos** [rancher/os#2232]
**RancherOS Version: (ros os version)**
1.1.3

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
KVM

I had two nodes (server + agent, agent) with `ros 1.1.0`. Updated them both to `1.1.3`. The agents on both are stuck failing on a loop. Nothing seems to work to fix it (restarting, removing & re-associating the node).

Error message from the logs:
```
time="2018-01-22T00:38:44Z" level=fatal msg="json: cannot unmarshal object into Go value of type []string"
```

Please advise.

**Comment by kapolos** [comment]
I just noticed that `rancher/server` is `1.6.2` while `docker` is `17.06.2-ce`. According to the docs, these are incompatible. I only did `sudo ros os upgrade` as per the docs.

**Comment by niusmallnan** [comment]
You can use `ros engine` to switch an compatible docker engine.
For rancher/server:v1.6.2, maybe docker 1.12.6 or 17.03 is better.

**Comment by kapolos** [comment]
Thank you @niusmallnan , that was very helpful!

```
[rancher@rancher ~]$ docker -v
Docker version 17.03.2-ce, build f5ec1e2
```

Rancher server is not running. I tried to start it by enabling the `rancher-server` service and starting it. But it fails with a `kvm-vm-tools` error like this:

```
[rancher@rancher ~]$ sudo ros service list
disabled amazon-ecs-agent
disabled amazon-ena-driver
disabled crontab
disabled open-iscsi
disabled kernel-extras
disabled kernel-headers
disabled kernel-headers-system-docker
disabled open-vm-tools
enabled  rancher-server
disabled rancher-server-stable
disabled zfs
disabled amazon-metadata
disabled volume-cifs
disabled volume-efs
disabled volume-nfs
enabled  kvm-vm-tools
[rancher@rancher ~]$ sudo ros service start rancher-server
ERRO[0000] non-200 http response: 404
ERRO[0000] Failed to load service(kvm-vm-tools): non-200 http response: 404
```

Not sure how to proceed from here :(

**Comment by niusmallnan** [comment]
Check the config `rancher.services_include`, then get rid of `kvm-vm-tools`. 

I recommend you to run rancher server directly using user docker.
For service `rancher-server-stable`  and  `rancher-server`, their images may not be updated in time.

**Comment by kapolos** [comment]
Running rancher server directly worked, thank you @niusmallnan 👍
