### ISSUE TITLE
Verbose output for ramdisk info

### ISSUE THREAD

**Issue by niusmallnan** [rancher/os#2233]
**RancherOS Version: (ros os version)**
v1.1.3

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
All

In RancherOS `fdisk -l` reports 16 ram disks (`/dev/ram0` ... `/dev/ram15`), other Linux distributions do not output ramdisk information.

The RAM disk driver is a way to use main system memory as a block device. It is required for initrd, an initial filesystem used if you need to load modules in order to access the root filesystem (see Documentation/initrd.txt). It can also be used for a temporary filesystem for crypto work, since the contents are erased on reboot.

To do list:
1. Block RAM disk module (brd, CONFIG_BLK_DEV_RAM) compiled as 'y', that means it is 'built-in' and can not be unloaded or loaded with different parameters. This render module completely useless because user can not anymore change it size. We should change it back to 'm' (module) to allow users use this module.
2. Turn on and off at the right time.

**Comment by kingsd041** [comment]
Using `fdisk -l` in rancheros v1.2.0-rc2 already does not see the ram disk
```
# fdisk -l
Disk /dev/xvda: 20 GiB, 21474836480 bytes, 41943040 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x38543c4a

Device     Boot Start      End  Sectors Size Id Type
/dev/xvda1 *    16065 41943006 41926942  20G 83 Linux
```
