### ISSUE TITLE
Rancheros cloud-init http client timeout is too low

### ISSUE THREAD

**Issue by selmison** [rancher/os#2235]
**RancherOS Version: (ros os version)**
v1.1.3

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
Citrix XenServer

**Actual result:**
When deploy Rancheros in a environment via pxe and foreman (http://theforeman.org) as tftp and cloud-config provider, the cloud-init in RancherOS has a too low http client timeout. 

**Expected result:**
Set the timeout to 10s or more

**Comment by niusmallnan** [comment]
How many interfaces are running DHCP？

**Comment by selmison** [comment]
Only one interface is running DHCP.

The PXe file is:

`DEFAULT rancheros

LABEL rancheros
  KERNEL boot/RancherOS-1.1.3-x86_64-vmlinuz rancher.state.dev=LABEL=RANCHER_STATE rancher.state.autoformat=[/dev/xvda] rancher.cloud_init.datasources=['url:http://vp2-inf-006.mpdft.gov.br/unattended/provision?token=b59aac21-e0af-47d2-a073-9fc85777cef0']
  APPEND initrd=boot/RancherOS-1.1.3-x86_64-initrd`

**Comment by niusmallnan** [comment]
I have increased the http client timeout for cloud-init-save.
You can try 1.1.4-rc1.

**Comment by selmison** [comment]
Unfortunately it did not work.

I captured the http packets as below.

The HTTPpackets as shown below reveal that the RancherOS makes a request for the cloud-conf, but it waits only 2 seconds, while the Foreman provides the response around 3.5 seconds.


```
T 2018/01/29 **14:58:13.384791** 10.34.173.70:54370 -> 10.34.241.189:80 [AP]
GET /unattended/provision?token=94038f07-fd6a-4de1-9d49-3fbe3bca2ec2 HTTP/1.1.
Host: foreman-server.
User-Agent: Go-http-client/1.1.
Accept-Encoding: gzip.
.


T 2018/01/29 **14:58:16.900107** 10.34.241.189:80 -> 10.34.173.70:54370 [AP]
HTTP/1.1 200 OK.
Date: Mon, 29 Jan 2018 16:58:13 GMT.
Server: Apache/2.4.10 (Debian).
Cache-Control: max-age=0, private, must-revalidate.
X-Request-Id: 4b55a32b-a349-4619-87cc-29b7e4a85728.
X-Runtime: 3.510295.
Content-Security-Policy: default-src 'self'; child-src 'self'; connect-src 'self' ws: wss:; img-src 'self' data: *.gravatar.com; script-src 'unsafe-eval' 'unsafe-inline' 'self'; style-src 'unsafe-inline' 'self'.
X-Content-Type-Options: nosniff.
X-Download-Options: noopen.
X-Frame-Options: sameorigin.
X-Permitted-Cross-Domain-Policies: none.
X-XSS-Protection: 1; mode=block.
X-Powered-By: Phusion Passenger 4.0.53.
ETag: W/"b93596ceadb4246626f17d6183084544-gzip".
Status: 200 OK.
Vary: Accept-Encoding.
Content-Encoding: gzip.
Content-Length: 195.
Content-Type: text/plain; charset=UTF-8.
.
..........e....0.D.|E.o&T(......E.%....[....N.Lf.....I.wM.&.sp0`-n@hR.}....0.&..O.J.....N.p.fO.E....,.0....T..,J..L..D..#..[.gnA..H.h\+..`....V..h.g..l...B.z../..d'U~.-.....P.b..._4.QEY._x...1...

T 2018/01/29 **14:58:16.901866** 10.34.173.70:54370 -> 10.34.241.189:80 [AP]
GET /unattended/provision?token=94038f07-fd6a-4de1-9d49-3fbe3bca2ec2 HTTP/1.1.
Host: foreman-server
User-Agent: Go-http-client/1.1.
Accept-Encoding: gzip.
.


T 2018/01/29 14:58:20.452412 10.34.241.189:80 -> 10.34.173.70:54370 [AP]
HTTP/1.1 200 OK.
Date: Mon, 29 Jan 2018 16:58:16 GMT.
Server: Apache/2.4.10 (Debian).
Cache-Control: max-age=0, private, must-revalidate.
X-Request-Id: 62b26c18-5a1e-466a-a7c2-c3bf7560cf2c.
X-Runtime: 3.546615.
Content-Security-Policy: default-src 'self'; child-src 'self'; connect-src 'self' ws: wss:; img-src 'self' data: *.gravatar.com; script-src 'unsafe-eval' 'unsafe-inline' 'self'; style-src 'unsafe-inline' 'self'.
X-Content-Type-Options: nosniff.
X-Download-Options: noopen.
X-Frame-Options: sameorigin.
X-Permitted-Cross-Domain-Policies: none.
X-XSS-Protection: 1; mode=block.
X-Powered-By: Phusion Passenger 4.0.53.
ETag: W/"b93596ceadb4246626f17d6183084544-gzip".
Status: 200 OK.
Vary: Accept-Encoding.
Content-Encoding: gzip.
Content-Length: 195.
Content-Type: text/plain; charset=UTF-8.
.
..........e....0.D.|E.o&T(......E.%....[....N.Lf.....I.wM.&.sp0`-n@hR.}....0.&..O.J.....N.p.fO.E....,.0....T..,J..L..D..#..[.gnA..H.h\+..`....V..h.g..l...B.z../..d'U~.-.....P.b..._4.QEY._x...1...
```

Here's the cloud-config content returned by Foreman:

```
#cloud-config
hostname: jared-halligan.mpdft.gov.br
rancher:
  network:
  dns:
    nameservers:
    - 10.34.240.1
    - 10.34.240.2
    search:
    - mpdft.gov.br
    interfaces:
      eth*:
        dhcp: false
      eth0:
        address: 10.34.173.70/24
        gateway: 10.34.173.254
  password: 123456
```

CoreOS also faced the same problem as below:
[https://github.com/coreos/bugs/issues/827](url)

Coreos fixed that via [https://github.com/coreos/coreos-cloudinit/pull/374](url)

**Comment by niusmallnan** [comment]
A long time ago we set the 10s timeout.
https://github.com/rancher/os/blob/v1.1.x/config/cloudinit/pkg/http_client.go#L87

I'm afraid this is not the reason for client timeout.
Can you show me your cloud-init-save logs(`/var/log/boot/cloud-init-save.log`)?

BTW, your cloud-config has some syntax errors:
1. Please note indentation
2. `rancher.password` is a kernel parameter, setting in cloud-config is not valid

**Comment by selmison** [comment]
Great!!

The error was in the parameter ```rancher.password```. After I remove it the pxe worked. Many thanks!!

How would I add the ```rancher.password``` parameter in the kernel during provisioning?

**Comment by selmison** [comment]
Great!!

The error was in the parameter ```rancher.password```. After I remove it the pxe worked. Many thanks!!

How would I add the ```rancher.password``` parameter in the kernel during provisioning?

**Comment by niusmallnan** [comment]
If I want to set a password, I will do so:
```
#!ipxe
dhcp
set base-url http://192.168.1.103/rancheros/ipxe
kernel ${base-url}/vmlinuz printk.devkmsg=on rancher.password=rancher rancher.debug=true rancher.state.dev=LABEL=RANCHER_STATE rancher.state.wait console=tty1 rancher.autologin=tty1 rancher.cloud_init.datasources=[url:${base-url}/cloud-config.yaml]
initrd ${base-url}/initrd
boot
```

**Comment by selmison** [comment]
Tks!!

What are `printk.devkmsg`, `rancher.state.dev` and `rancher.state.wait`?

**Comment by selmison** [comment]
I've seen what `printk.devkmsg` is  in [https://github.com/torvalds/linux/blob/master/Documentation/admin-guide/kernel-parameters.txt](https://github.com/torvalds/linux/blob/master/Documentation/admin-guide/kernel-parameters.txt).

Where do I see the specific parameters of RancherOS such `rancher.state.dev` and `rancher.state.wait`?

**Comment by niusmallnan** [comment]
Sometimes the user's host may not only a hard disk, and one of the hard disks have been installed RancherOS.
The user can use the label set by `rancher.state.dev` to find the hard disk, this feature is useful if you want your data to be persistent on your hard drive. 

For example, you use the following parameters:
```
rancher.state.autoformat=[/dev/sda] rancher.state.dev=LABEL=RANCHER_STATE rancher.state.wait
```
Then the first PXE boot formatted the hard disk and the RancherOS installed on the hard disk, and then PXE will not reset the data after each boot.

Refer to this logic:
`https://github.com/rancher/os/blob/master/cmd/control/bootstrap.go#L47`
`https://github.com/rancher/os/blob/master/init/bootstrap.go#L14`

**Comment by niusmallnan** [comment]
If you have any problem, pls file another issue.
