### ISSUE TITLE
Error in docs: additional mounts / 4th parameter

### ISSUE THREAD

**Issue by fxkr** [rancher/os#2238]
Error/inconsistency in the docs:

http://rancher.com/docs/os/v1.1/en/storage/additional-mounts/

> Important: **Be aware, the 4th parameter is mandatory** and cannot be ommited (server crashes). It also yet cannot be defaults
> 
> As you will use the ros cli most probably, it would look like this:
> 
> **ros config set mounts '[["/dev/vdb","/mnt/s","ext4"]]'**

Note there's no 4th parameter in the example. So is it required or not?

**Comment by niusmallnan** [comment]
@fxkr Sorry, we have a mistake here.
The 4th parameter is required for ros cli.
Thanks for your reminder
