### ISSUE TITLE
Failed to install ZFS service

### ISSUE THREAD

**Issue by kingsd041** [rancher/os#2240]
**RancherOS Version: (ros os version)**
v1.0.5-rc1 or v1.1.4-rc1
**Kernel**
4.9.78-rancher
**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
AWS

**Steps to Reproduce:**
1. Install the zfs service using rancheros v1.0.5-rc1 or v1.1.4-rc1.
2. Use `ros service logs --follow zfs` to view the logs when running` ros service up zfs`

Failed to install ZFS service, the error log is as follows:
```
zfs_1 | Step 11 : ENTRYPOINT /usr/local/bin/entry.sh
zfs_1 |  ---> Using cache
zfs_1 |  ---> 5b30e4141f09
zfs_1 | Successfully built 5b30e4141f09
zfs_1 | + modprobe zfs
zfs_1 | modprobe: ERROR: could not insert 'zfs': Exec format error
```

**Comment by kingsd041** [comment]
v1.2.0-rc2 also have the same error

**Comment by niusmallnan** [comment]
@kingsd041 You can try to test these again.
Our 4.9.78-rancher kernel was compiled by gcc 7.3.0.
I have to use the same gcc version to compile zfs, otherwise the kernel does not recognize the module format.

**Comment by kingsd041** [comment]
Tested with RancherOS v1.0.5-rc1/v1.1.4-rc1/v1.2.0-rc2.
zfs service is already available.
