### ISSUE TITLE
Create a 1G memory instance, the instance failed to start

### ISSUE THREAD

**Issue by kingsd041** [rancher/os#2242]
**RancherOS Version: (ros os version)**
v1.2.0-rc2
**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
docker-machine

Use docker-machine to start an instance of 1G memory. Instance can not be started, the console appears "Kernel panic"
```
docker-machine create -d virtualbox --virtualbox-memory "1024" --virtualbox-boot2docker-url rancheros-v1.2.0-rc2.iso ros-120
```

<img width="722" alt="ros" src="https://user-images.githubusercontent.com/19684717/35724895-50d0736c-083a-11e8-8281-6d31e570edb8.png">

**Comment by niusmallnan** [comment]
@kingsd041 
When  you have a chance, can you ping me on Slack?
I can give you an ISO, you can test this issue again.

If you want to check this case on any public cloud, you can use this image `niusmallnan/os`.
```
ros os upgrade -i niusmallnan/os
```
Then adjust the flavor of your VM.

**Comment by kingsd041** [comment]
The issue has been fixed, use 1G memory can launch the instance.
