### ISSUE TITLE
Switch docker version failed

### ISSUE THREAD

**Issue by kingsd041** [rancher/os#2244]
**RancherOS Version: (ros os version)**
v1.2.0-rc2
**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
AWS

Only switch to docker-17.09.0-ce will fail
```
# ros engine switch  docker-17.09.0-ce
ERRO[0000] non-200 http response: 404
ERRO[0000] Failed to load service(xenhvm-vm-tools): non-200 http response: 404
ERRO[0000] non-200 http response: 404
FATA[0000] non-200 http response: 404
```

**Comment by niusmallnan** [comment]
Clean this dir `/var/lib/rancher/cache/` and try again, it should be fixed.

**Comment by kingsd041** [comment]
Fixed, closed it

**Comment by aschrijver** [comment]
I have the same issue with RancherOS `v1.1.0` and `/var/lib/rancher/cache` is empty.

**Comment by niusmallnan** [comment]
@asabanovic 
We did not support docker-17.09.0-ce in RancherOS v1.1.0
https://github.com/rancher/os-services/tree/v1.1.0/d
