### ISSUE TITLE
Custom system docker does not start automatically

### ISSUE THREAD

**Issue by kingsd041** [rancher/os#2245]
**RancherOS Version: (ros os version)**
v1.2.0-rc2
**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
AWS

**Steps to Reproduce:**
1. Run a system docker and use `--restart = unless-stopped`
```
system-docker run -itd --restart=unless-stopped --name=nginx -p 80:80 nginx
```
2. reboot

 System docker (nginx) did not start automatically, I can only manually start it

**Comment by niusmallnan** [comment]
Basically, the system-docker just to manage system services.
If users want to manage any `auto-restart` containers,  then can use `ros service`.
http://rancher.com/docs/os/v1.1/en/system-services/custom-system-services/

Our system-docker is based on docker 1.11.2, this version should not support `--restart=unless-stopped`, `--restart=always` should be supported.

So this issue won't be fixed.

**Comment by kingsd041** [comment]
@niusmallnan Thanks for your comment, I will close it
