### ISSUE TITLE
Upgrade system docker to a newer stable version

### ISSUE THREAD

**Issue by niusmallnan** [rancher/os#2255]
Our current system docker is based on docker 1.11.2, https://github.com/rancher/docker/commits/system-docker-v1.11.2

We need to upgrade it to solve a lot of legacy issues.

Related issues:
https://github.com/rancher/os/issues/2163
https://github.com/rancher/os/issues/2165

**Comment by niusmallnan** [comment]
We have upgraded the system-docker to docker-ce 17.06.
```
[root@rancher rancher]# system-docker -v
Docker version 17.06-ros3, build fa7c1dad
```

**Comment by kingsd041** [comment]
System-docker works fine when upgrading to 17.06
Close it.
