### ISSUE TITLE
Can't use mmcblk0 as RANCHER_STATE partition on UDOO X86

### ISSUE THREAD

**Issue by Iodun** [rancher/os#2260]
**RancherOS Version: (ros os version)**
v1.2.0

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
UDOO X86 (Embedded Computer)

I am trying to run RancherOS on my UDOO X86 Cluster and wanted to use the onboard eMMC flash memory for RANCHER_STATE persistence.
This doesn't seem to work, because the following kernel modules are missing (only available in the rancher/os-extras package):
- **mmc_block**
- **sdhci**
- **sdhci_acpi**

As far as I understand the RANCHER_STATE partition needs to be detected first, then the YAML config is retrieved and then I could theoretically force above modules to be loaded from the os-extras package.
Sadly those modules are already necessary right from the beginning for the kernel to be able to find the RANCHER_STATE partition with my YAML config after all.

So my request is to move above modules from the os-extras package into the main kernel package.
Correct me if I am wrong. :)

**Comment by niusmallnan** [comment]
I do not have this test environment.

You can build your own kernel with this repo: https://github.com/rancher/os-kernel
the base kernel modules: https://github.com/rancher/os-kernel/blob/master/modules.list
the extra kernel modules: https://github.com/rancher/os-kernel/blob/master/modules-extra.list

If you can compile your kernel, you can update this config in `rancher/os ` repo.
https://github.com/rancher/os/blob/master/Dockerfile.dapper#L67

**Comment by Iodun** [comment]
Many thanks for the hints!
Managed to create a modified kernel and built a rancheros.iso with it.
RancherOS works properly on UDOO x86 with following change:

https://github.com/rancher/os-kernel/pull/57

**Comment by ibuildthecloud** [comment]
@Iodun Now I want to buy a UDOO x86.

**Comment by Iodun** [comment]
@ibuildthecloud 
Very unique board and absolutely worth the money.
Only downside is the M.2 slot that just supports 2260 and not 2280 module format.
Thanks for the support to get my pull request merged. :)
