### ISSUE TITLE
Urgent help logging into recovery console

### ISSUE THREAD

**Issue by Nickersoft** [rancher/os#2265]
**RancherOS Version: (ros os version)**
I forget, and would check but I can't login. I'm deploying via Vultr, and the built-in Vultr RancherOS ISO is v1.1, so there's a good chance it's that.

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
Vultr

I recently restarted my Vultr server and found I couldn't SSH and all my Rancher sites were down. Logging into the Vultr console, I saw that there was no space left on the device so it had booted into the RancherOS recovery console. The visible log output right now is:

```
init:info: Launching recovery console
init:info: [1/2] Starting loadImages
init:error: Can't add file /usr/etc/selinux/ros/policy/policy.29 to tar: io: read/write on closed pipe
init:info: Connected to Docker at unix:///var/run/system-docker.sock
init:info: Loading images from /usr/share/ros/images.tar
init:info: Done loading images from /usr/share/ros/images.tar
init:info: [2/2] Starting recovery console
init:info: Project [recovery]: Starting project
init:info: [0/1] [recovery]: Starting

RancherOS rancher tty1
rancher login:
```

The console then prompts for a `rancher` login and password, as seen above. I've tried the root password I had written down multiple times now with no luck. I have absolutely no idea how to login to this console, or how to update my passwords so I can login. I've seen mixed things in these GitHub issues regarding `rancher` users and whatnot, but nothing I try works. In fact, I can't find much information about the RancherOS recovery console at all.

How can I login to this console? It's the only chance I have at freeing up space so the system boots without paying Vultr for even more storage.

**Comment by niusmallnan** [comment]
https://rancher.com/docs/os/v1.x/en/about/recovery-console/
