### ISSUE TITLE
[os-images] custom console

### ISSUE THREAD

**Issue by Mambix** [rancher/os#2266]
**RancherOS Version: (ros os version)**
v1.1.0

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
baremetal

How do I create my custom os-console container?
For my test machines I often need to edit and move data around while testing/experimenting and I would like a permanent installation of midnight commander on my rancher machines. It is my understanding that I would need a custom os-console container.

Can someone point me in the right direction on how to make one?

**Comment by niusmallnan** [comment]
For default console, we use the busybox, you can refer to these two projects:
- https://github.com/rancher/buildroot
- https://github.com/rancher/os-base

For other consoles, you can check in `os-services`:
https://github.com/rancher/os-services/tree/master/images

**Comment by Mambix** [comment]
@niusmallnan thanks 👍

**Comment by Mambix** [comment]
@niusmallnan is there an easy way to add custom console to the list in ros or do I need a custom ros build for this?

**Comment by niusmallnan** [comment]
If you run `ros console list`, it should read contents from the `index.yml` of `os-services`.
Different ROS versions will visit the corresponding branch of `os-services`.

You can modify the `/usr/share/ros/os-config.yml` file in your setup, just focus on the `rancher.repositories.core.url`.
