### ISSUE TITLE
Bump the kernel to 4.15.x

### ISSUE THREAD

**Issue by niusmallnan** [rancher/os#2270]
Now 4.15.x is  the current stable branch. 
https://www.kernel.org/

**Comment by kingsd041** [comment]
The default kernel in rancheros-v1.3.0-rc1 has been upgraded to 4.15.9.
```
# uname -r
4.15.9-rancher
```

**Comment by ryansch** [comment]
The default kernel in 1.3.0 final is 4.9.80.  We're still waiting on 4.15.x to fix the overlay fs bugs that cause tar to die.

**Comment by niusmallnan** [comment]
@ryansch 
I tried to bump the kernel to 4.15.x, but zfs cannot work. https://github.com/rancher/os/issues/2299

I must roll back the kernel to 4.9.x.
I will try 4.14.x in next release, 4.14.x another LTS version and provides newer features.

**Comment by ryansch** [comment]
@niusmallnan That's new enough to fix our bug: https://github.com/moby/moby/issues/19647
