### ISSUE TITLE
ros config -- documentation

### ISSUE THREAD

**Issue by rbucker** [rancher/os#2274]
**RancherOS Version: (ros os version)**
1.2.0
**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
vmware

when updating config like nameservers
```
sudo ros config set rancher.network.dns.nameservers "['172.17.42.1']"
```

where in the flow of things is the ```/etc/resolv.conf``` updated?

**Comment by niusmallnan** [comment]
After you reboot, `/etc/resolv.conf` can be updated by your config.
