### ISSUE TITLE
open-vm-tools fail to automatically fetch

### ISSUE THREAD

**Issue by Coada** [rancher/os#2275]
**RancherOS Version: (ros os version)**
v1.2.0
**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
vSphere

So it seems that was working fine yesterday, but not anymore. RancherOS properly detects it is running on a vSphere installation and attempts to install open-vm-tools but fails:

> [ ] ros-sysinit:info: [18/19] [preload-user-images]: Started
> [ ] ros-sysinit:error: Failed to start: open-vm-tools : Error parsing reference: "/rancher/os-openvmtools:10.1.10-2" is not a valid repository/tag
> [ ] ros-sysinit:error: Failed [2/4] start project: Error parsing reference: "/rancher/os-openvmtools:10.1.10-2" is not a valid repository/tag
> [ ] ros-sysinit:info: Project [os]: Project started
> [ ] ros-sysinit:fatal: Error parsing reference: "/rancher/os-openvmtools:10.1.10-2" is not a valid repository/tag

Pretty sure it is related to https://github.com/rancher/os-services/pull/152

Doing `sudo ros service logs open-vm-tools` gives me:

> WARN[0000] The REGISTRY_DOMAIN variable is not set. Substituting a blank string.

How would I proceed to fix any future deployment so that it automatically fetches open-vm-tools?

**Comment by niusmallnan** [comment]
This PR is updated to master branch.
If you worked on RancherOS v1.2.0, it should use v1.2.0 branch of os-services.

**Comment by fredrikbergstrompricer** [comment]
When looking at the Dockerfile.dapper file in the 1.2.x branch I don't really see how we can override the REPO_VERSION, it's set to `master`.

https://github.com/rancher/os/blob/efad6c320f7d25c3b0bcb64bed0554052adae15e/Dockerfile.dapper#L118

Shouldn't that be set to point to the corresponding release branch?

**Comment by bjfr** [comment]
I have the same problem building the ISO using the code in tag 1.0.3! Looking at https://github.com/rancher/os/blob/v1.0.3/os-config.tpl.yml

```
  repositories:
    core:
      url: {{.OS_SERVICES_REPO}}/{{.REPO_VERSION}}
```
and https://github.com/rancher/os/blob/v1.0.3/Dockerfile.dapper

```
    OS_SERVICES_REPO=${OS_SERVICES_REPO} \
    REPO_VERSION=master \
    SELINUX_POLICY_URL=${SELINUX_POLICY_URL}
```

all builds seems to go against master! Even the older ones!

**Comment by niusmallnan** [comment]
Check your `/usr/share/ros/os-config.yml` file in your setup, you can update the value of `repositories.core.url` .

@fredrikbergstrompricer @bjfr  When we ship a new release, we will use the latest tag version to replace `REPO_VERSION `.  Check the `scripts/release` script:
```
 cd $(dirname $0)/..
source ./scripts/version
export REPO_VERSION=$VERSION
export COMPRESS="xz --format=lzma -9 --memlimit-compress=80% -e"
```
