### ISSUE TITLE
Run trash error

### ISSUE THREAD

**Issue by Jason-ZW** [rancher/os#2279]
**RancherOS Version: (ros os version)**
master branch

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
VirtualMachine on Parallels

**Issue Details**
Build form source. Running trash command error, the log as below:
```
service-catalog is not a valid repo
```

**Comment by Jason-ZW** [comment]
I think it shoud be modifed like this in trash.conf:
```
github.com/rancher/catalog-service/utils/version 81799167a6ed8666fb1640b3aae12bc407050c4f https://github.com/rancher/catalog-service.git
```

**Comment by niusmallnan** [comment]
It does not make sense. I didn't get these errors.
