### ISSUE TITLE
Cloud-config doesn't seem to work with  encoding: "gz+b64" or encoding: "gzip+base64"

### ISSUE THREAD

**Issue by josmo** [rancher/os#2284]
**RancherOS Version: (ros os version)**
ros version v1.0.1
also tried version v1.2.0 from os image rancher/os:v1.2.0

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
AWS

While trying to use user-data with gzip/base64 encoding for the content it seems to ignore gzip.
  tried encoding set to gz+b64 or gzip+base64 
```
  - path: /home/rancher/vpn_server.config
    permissions: "0644"
    owner: root
    encoding: "gzip+base64"
    content: $(content in b64/gzip)
```
expected:
creates /home/rancher/vpn_server.config file

Actual:
creates a weird directory I imagined because it's ignoring the gzip portion.

**Comment by Jason-ZW** [comment]
@josmo Are you sure can create a weird directory？ It should create nothing when set encoding "gzip+base64" base the current code logic. Could you please check and let me know system-docker log with the command `system-docker logs -f console` and it shoud be an error log such like this `level=error msg="Error writing file" err="Unable to write file with encoding gzip+base64" path= `?

**Comment by josmo** [comment]
@Jason-ZW looks like you're correct. With gzip+base64 it does give that error. I know there was a scenario where it created a weird directory, but looks like I can't repro now.   Seems like 1.4 will support the gzip+base64 encoding at the file level :)

**Comment by kingsd041** [comment]
@josmo 
It has been fixed in rancherosv1.4.0-rc1 and I have tested it

**Comment by josmo** [comment]
@kingsd041 
Thanks a bunch!
