### ISSUE TITLE
Mount shared folders from VMware to be usable by Docker conatiners

### ISSUE THREAD

**Issue by spikespaz** [rancher/os#2287]
I want to mount two shared folders from VMware, `Music` and `Videos`. The package `open-vm-tools` is installed and enabled.

I have run this to test the mount:

    sudo vmhgfs-fuse .host:/ /home/rancher/

Does not work. How can I mount the shared folders to be available to docker containers?

**RancherOS Version: (ros os version):** Latest as of writing, 1.3

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.):** VMware Workstation Player

**Comment by Jason-ZW** [comment]
@spikespaz 
I think you can use the following command, then share-folder can be found in console & user-conatiner:
```
docker run -itd --privileged --pid=host --ipc=host --net=host --uts=host  --mount type=bind,source=/tmp/Users,target=/tmp/Users,bind-propagation=rshared -v /usr/bin/ros:/usr/bin/ros rancher/os-openvmtools:10.2.5-2 /usr/bin/vmtoolsd

/usr/local/bin/vmhgfs-fuse -o nonempty -o allow_other .host:/Users /tmp/Users/

docker run -itd -v /tmp/Users/:/tmp/Users alpine
```

**Comment by Jason-ZW** [comment]
Any questions, please reopen this issue.

**Comment by jnewman-altair** [comment]
Any instructions on making this mount persistent?
