### ISSUE TITLE
Use `ros config set rancher.ssh.port 2222` to modify ssh port, the default port (22) still exists

### ISSUE THREAD

**Issue by kingsd041** [rancher/os#2289]
**RancherOS Version: (ros os version)**
```
# ros --version
version v1.3.0-rc1 from os image rancher/os:v1.3.0-rc1
```
**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
docker-machine

I try to modify the ssh port in the ubuntu console and run `ros config set rancher.ssh.port 2222`. After waiting for rancheros to restart and checking the ssh port, I can get two ssh ports (22 and 2222).

```
root@ros-130-2:~# ros config get rancher.ssh.port
2222
root@ros-130-2:~# cat /etc/ssh/sshd_config | grep Port
Port 22
Port 2222
root@ros-130-2:~# netstat -lntp | grep sshd
tcp        0      0 0.0.0.0:2222            0.0.0.0:*               LISTEN      1328/sshd
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1328/sshd
tcp6       0      0 :::2222                 :::*                    LISTEN      1328/sshd
tcp6       0      0 :::22                   :::*                    LISTEN      1328/sshd
```

**Comment by niusmallnan** [comment]
For other consoles, 
all files are persistent, users can modify sshd-config by themselves.

`rancher.ssh.port` is designed for default console, because the users change sshd-config, restart the host will restore the default. The new configuration will not take effect.

**Comment by kingsd041** [comment]
Ok, I close it
