### ISSUE TITLE
Got some error message before downloading docker images

### ISSUE THREAD

**Issue by kingsd041** [rancher/os#2290]
**RancherOS Version: (ros os version)**
v1.3.0-rc1
**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
docker-machine

There was some error message `ERRO[0002] Missing the image: Error: No such image: docker.io/rancher/os-ubuntuconsole:v1.3.0` when switching to ubuntu console. But it can be switched successfully

Here is my operation record:
```
[root@ros-130-2 ~]# ros console switch ubuntu
Switching consoles will
1. destroy the current console container
2. log you out
3. restart Docker
Continue [y/N]: y
ERRO[0002] Missing the image: Error: No such image: docker.io/rancher/os-ubuntuconsole:v1.3.0
Pulling console (docker.io/rancher/os-ubuntuconsole:v1.3.0)...
```

**Comment by kingsd041** [comment]
This prompt is normal because it prompts local without this image.

**Comment by niusmallnan** [comment]
I hate this error msg, reopen this issue.

**Comment by niusmallnan** [comment]
Introduced by this commit https://github.com/rancher/os/commit/43f483a5ef4ad4fb63ee585c2cee1f63f9b03a39

Remove this error output.

**Comment by kingsd041** [comment]
Tested with rancher/os:7a0d3a8
Verified fixed

```
~# ros console switch centos
Switching consoles will
1. destroy the current console container
2. log you out
3. restart Docker
Continue [y/N]: y
Pulling console (docker.io/rancher/os-centosconsole:v1.5.0)...
v1.5.0: Pulling from rancher/os-centosconsole
```
