### ISSUE TITLE
loading kernel modules with parameters

### ISSUE THREAD

**Issue by prologic** [rancher/os#2295]
The code that is responsible for loading kernel modules from the `rancher.modules` list does not support loading parameters: https://github.com/rancher/os/blob/82aaa413f5eaacff4ce22ead741d82a2b4b6062a/init/init.go#L43-L72

Can we make it support this?

Use-case:

```#!bash
$ modprobe nbd nbds_max=1024
```

**Comment by JacieChao** [comment]
We could add rancher.modules with parameters now.

Here's an example:
For CLI, you could use the following command:

`sudo ros config set rancher.modules "['nbd nbds_max=1024']"`

For YAML:
```
#cloud-config
rancher:
  modules: [nbd nbds_max=1024]
```

**Comment by prologic** [comment]
This works in v1.2.0? It wasn't clear from the docs at all :/

**Comment by niusmallnan** [comment]
@prologic No, we put it into the milestone v1.4.0.

**Comment by prologic** [comment]
@imikushin Ahh sorry, @JacieChao's comment made it sound like this was already supported.

**Comment by kingsd041** [comment]
Tested with rancheros v1.4.0-rc1.
@imikushin  We could add rancher.modules with parameters now.
```
# ros config set rancher.modules "['nbd nbds_max=1024']"

# reboot

# cat /sys/module/nbd/parameters/nbds_max
1024
```

**Comment by prologic** [comment]
Nice :D This lets us use [StorageOS](https://storageos.com/) nicely on RancherOS

Thanks for fixing this!
