### ISSUE TITLE
ZFS build fails due to kernel version

### ISSUE THREAD

**Issue by kingsd041** [rancher/os#2299]
**RancherOS Version: (ros os version)**
v1.3.0-rc1
**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
AWS

Starting zfs in rancheros v1.3.0-rc1 fails, when I run `sudo ros service up zfs` you can see the following logs

```
zfs_1 | checking linux distribution... debian
zfs_1 | checking default package type... deb
zfs_1 | checking whether rpm is available... no
zfs_1 | checking whether rpmbuild is available... no
zfs_1 | checking whether spec files are available... yes (rpm/generic/*.spec.in)
zfs_1 | checking whether dpkg is available... yes (1.18.24)
zfs_1 | checking whether dpkg-buildpackage is available... no
zfs_1 | checking whether alien is available... no
zfs_1 | checking spl config... all
zfs_1 | checking kernel source directory... /lib/modules/4.15.9-rancher/build
zfs_1 | checking kernel build directory... /lib/modules/4.15.9-rancher/build
zfs_1 | checking kernel source version... 4.15.9-rancher
zfs_1 | checking kernel file name for module symbols... Module.symvers
zfs_1 | checking whether debugging is enabled... no
zfs_1 | checking whether basic kmem accounting is enabled... no
zfs_1 | checking whether detailed kmem tracking is enabled... no
zfs_1 | checking whether modules can be built... no
zfs_1 | configure: error: *** Unable to build an empty module.
```

**Comment by niusmallnan** [comment]
It seems that zfs is not compatible with the 4.15.x kernel.
https://github.com/zfsonlinux/zfs/issues/7159

**Comment by niusmallnan** [comment]
An import user needs to use zfs, so I roll back the kernel to 4.9.x , then zfs can work fine.

**Comment by kingsd041** [comment]
ZFS is available in rancher v1.3.0-rc2

**Comment by ryansch** [comment]
@niusmallnan is this why 4.15.x didn't make it out?  Do you have a timeline?  I've intentionally not deployed a workaround for the bug we've got because 1.3.0 was right around the corner.

**Comment by niusmallnan** [comment]
Same issue in v1.4.0-rc2.
I will drop the ZFS support before we fix it.

**Comment by rootwuj** [comment]
Tested with RancherOS version- v1.4.1-rc2(Kernel Version: 4.14.65-rancher) with AWS.
This version of ZFS can be installed successfully.

**Comment by niusmallnan** [comment]
Backported to v1.4.1.
