### ISSUE TITLE
Make sure that RancherOS is fully compatible with Rancher 2.0

### ISSUE THREAD

**Issue by niusmallnan** [rancher/os#2306]
As we know that Rancher 2.0 will be released soon, we should ensure that RancherOS can run it well.

If possible, we should provide a guide to point out some key configurations.

**Comment by niusmallnan** [comment]
> From hgalal:
actually the prefix path should work out of the box with rancherOS, rke automatically detect RancherOS and change the prefix to /opt/rke, which means the certificates for example will be saved in /opt/rke/etc/kubernetes/ssl

RKE can work with RancherOS now.

**Comment by niusmallnan** [comment]
From @kingsd041 

1. provisioning to AWS using RancherOS 1.4.0-rc2 in Rancher 2.0    

  case1: Test canal/flannel/calico network     `pass`
  case2: Test kubernetes v1.10.1-rancher2-1/v1.9.5-rancher1-1/v1.8.10-rancher1-1      `pass`
  case3: Test longhorn    `fail`
  case4: Test nfs-provisioner   `fail`


2. provisioning to VSphere using RancherOS-VMware 1.4.0-rc2 in Rancher 2.0

  case1: Test canal/flannel/calico network    `pass`
  case2: Test kubernetes v1.10.1-rancher2-1/v1.9.5-rancher1-1/v1.8.10-rancher1-1       `pass`
  case3: Test longhorn    `fail`
  case4: Test nfs-provisioner   `fail`

**Comment by janeczku** [comment]
We shall document some key configurations for using RancherOS with Rancher 2.0 (including the VSphere node driver). @niusmallnan
