### ISSUE TITLE
User cannot resize root disk 

### ISSUE THREAD

**Issue by nayang777** [rancher/os#2308]
**RancherOS Version: (ros os version)**
v1.2.0 and prior version 

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
DigitalOcean

**Issue description**
It might be expected behavior but just wanted to see if there's a way we can address it for DO images. It looks like regardless of the configuration of a droplet, the volume size is always 7.4gb. We've been directing customers to this article - http://rancher.com/docs/os/v1.1/en/configuration/resizing-device-partition/ - but it has been driving a significant amount of support interaction volume with customers who use the Rancher image, so we just wanted to check in with you and see if we can work on a solution together.

**Comment by niusmallnan** [comment]
It seems perfectly reasonable to default to having the disk resize on first deployment.  This should be a simple one.  When launching RancherOS just add the following to the kernel cmdline

`rancher.resize_device=/dev/vda`
