### ISSUE TITLE
Untested Docker version?

### ISSUE THREAD

**Issue by alex-s-team** [rancher/os#2310]
**RancherOS Version: (ros os version)**
RancherOS v1.3.0 (with KVM) (4.9.80) 

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
kvm / qemu / libvirt on ubuntu xenial

one installation shows "Untested Docker version", another installation (same everything) does not.
how can i find the source of this problem?

both installations show the exact same versions:
docker --version
Docker version 17.09.1-ce, build 19e2cf6
system-docker --version
Docker version 17.06-ros3, build fa7c1dad

this is just a minor flaw - a display issue, as everything seems to be running smooth

**Comment by niusmallnan** [comment]
Hi, just want to know where to show `"Untested Docker version"`.
`docker` means user-docker, it is the official version, I did not make any changes.
For `system-docker`, I did make some changes, I need to get rid of some unnecessary feature.
https://github.com/niusmallnan/os-system-docker

**Comment by vincent99** [comment]
`Untested Docker version` is shown in Rancher (not OS) when the version is higher than the newest known version at the time of that Rancher release (or at least the last time the setting default value was updated).  In this case, it's also because it doesn't recognize the `-ros3`suffix.

**Comment by alex-s-team** [comment]
thank you very much for the answers, if i read this right, then if a pull a new version of rancher server, then the message should go away. i will try that in a jiffy, thanks for the insight.

**Comment by alex-s-team** [comment]
just works, thank you very much.
