### ISSUE TITLE
Upgrade kernel to >= 4.13

### ISSUE THREAD

**Issue by ryansch** [rancher/os#2311]
All versions of rancherOS suffer from https://github.com/moby/moby/issues/19647

**Comment by kingsd041** [comment]
@ryansch 
The latest kernel in rancheros v1.4.0-rc1 was upgraded to 4.14.32.
```
[root@ip-172-31-31-115 ~]# ros -v
version v1.4.0-rc1 from os image rancher/os:v1.4.0-rc1
[root@ip-172-31-31-115 ~]# uname -r
4.14.32-rancher2
```
