### ISSUE TITLE
request: add module smartpqi

### ISSUE THREAD

**Issue by schmurfy** [rancher/os#2319]
I am running v1.3.0, is it possible to add module `smartpqi` for the next release ?
It is required to support the latest HP Smart Array installed in HP Proliant servers.

**Comment by niusmallnan** [comment]
Can you please make a PR to [os-kernel](https://github.com/rancher/os-kernel)?
I cannot test it out.

**Comment by schmurfy** [comment]
done: https://github.com/rancher/os-kernel/pull/59

**Comment by kingsd041** [comment]
@schmurfy 
The `smartpqi` module has been added in rancheros v1.4.0-rc1.
Can you have a try, please?

**Comment by schmurfy** [comment]
thanks, I will try this week.

**Comment by kingsd041** [comment]
Looking forward to your test results

**Comment by schmurfy** [comment]
is there a prebuilt vmlinuz & initrd for this release ? I boot the servers using PXE so I need those to test it.

**Comment by niusmallnan** [comment]
Can not wait, I must ship the v1.4.0 release.
@schmurfy If you find any problem after testing, please let me know.

**Comment by schmurfy** [comment]
ok, I tested the initial patch before sending the pull request anyway so it should be fine.
