### ISSUE TITLE
1.3 docs link returns page not found

### ISSUE THREAD

**Issue by jambajaar** [rancher/os#2321]
ROS 1.3

https://rancher.com/docs/os/v1.3/en/ is missing.  Returns `404 Not Found`

**Comment by niusmallnan** [comment]
For 1.3, the documentation changes very little.
We will move to `v1.x` so we don't have to do so much maintenance.

I saw @deniseschannon  tracking this thing.

**Comment by niusmallnan** [comment]
We have used `https://rancher.com/docs/os/v1.x/en/`
