### ISSUE TITLE
Config docker-sys bridge via system-docker args

### ISSUE THREAD

**Issue by niusmallnan** [rancher/os#2329]
Before v1.3, we used CNI to configure docker-sys.

In v1.3, we removed docker-sys and let system-docker use only the host network, but some users want to be able to keep the bridge network for system-docker.

So we need to re-introduce docker-sys, but we need to remove the CNI style and use the docker args style.

**Comment by kingsd041** [comment]
Re-introduced system-docker bridge network in rancheros-v1.4.0-rc1.
Close it.

**Comment by kucerarichard** [comment]
Can you spell out the "docker args style"? What is it exactly?
