### ISSUE TITLE
RancherOS should keep the DHCP system container running

### ISSUE THREAD

**Issue by sheng-liang** [rancher/os#234]
So it can renew the lease or request new leases.

**Comment by pwFoo** [comment]
That could fix my problem. Because RancherOS sometimes boot without a ip address (static dhcp lease).

**Comment by Kelindar** [comment]
Might be related: I've booted my bare metal RancherOS server without a ethernet cable, plugged the correct one after boot but DHCP didn't assign an address, had to reboot the entire machine. Wouldn't want this to happen in production.

**Comment by sheng-liang** [comment]
I think we need to fix this bug. I just had a failure in network configuration on bare metal server because DHCP server takes too long to return. We need to keep DHCP service retrying.

**Comment by sheng-liang** [comment]
I was able to manually restart network daemon by running
    sudo system-docker restart network

**Comment by ibuildthecloud** [comment]
Two issues here.  1) we don't keep dhcp running 2) we don't respond to kernel events when the link goes up and down.  We should fix them both for sure

**Comment by ibuildthecloud** [comment]
@imikushin I think we are going to have to create a "wait for networking" container.  The reason we don't keep dhcp running is it was a simple way to block until it the network was configured.  If we launch dhcp in the background we don't know when the NIC is configured.  So we can create a blocking "wait for networking" container

**Comment by imikushin** [comment]
@ibuildthecloud dhcpcd is, in fact, "forked to background" when 
`dhcpcd -A4 -e force_hostname=true eth0` command has finished. 

Only when the main process (`netconf`) in the "network" container exits, the container dies and takes dhcpcd with it.

I'm looking how to make "network" a real service solving the issues you outlined.

**Comment by imikushin** [comment]
This issue should be fully resolved (both parts mentioned by @ibuildthecloud) when #639 is merged with rancher/netconf#1 on top of that.
