### ISSUE TITLE
What is latest stable version?

### ISSUE THREAD

**Issue by olljanat** [rancher/os#2341]
I noticed inconsistency between [releases](https://github.com/rancher/os/releases) page (which says that latest release is v1.3.0) and with [README.md](https://github.com/rancher/os/blob/41a3330d89086dbd90d4c4f451cdf3b42f58a998/README.md) which says that latest stable release is v1.2.0.

If v1.3.0 is not stable why it is not marked as v1.3.0-rc3?

**Comment by vincent99** [comment]
We have 2 "channels";  Latest is always the newest release (currently 1.3), and Stable is more conservatively updated (currently 1.2).

(The "Latest release" note on GitHub is just the newest tag, regardless of whether it says rc/beta/etc or not.)

**Comment by olljanat** [comment]
OK. Should it be then at least some level marked on releases.yml then that it would be possible to see from **sudo ros os list** output which version(s) are marked as stable?
