### ISSUE TITLE
[os-installer]  error setDiskpartitions exec: "system-docker": executable file not found in $PATH

### ISSUE THREAD

**Issue by steven-cherry** [rancher/os#2342]
**RancherOS Version: (ros os version)**
v1.3.0
**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
baremetal

I have a problem when installing RancherOS using the RancherOS docker image
`docker run --privileged -it -v /var/run/docker.sock:/var/run/docker.sock rancher/os:v1.3.0 -d /dev/sda`
`INFO[0000] No install type specified...defaulting to generic`
`WARN[0000] Cloud-config not provided: you might need to provide cloud-config on boot with`
`ssh_authorized_keys`
`Installing from :v1.3.0`
`Continue [y/N]: y`
`INFO[0002] start !isoinstallerloaded`
`INFO[0002] ps error: exec: "system-docker": executable file not found in $PATH`
`ERRO[0002] error setDiskpartitions exec: "system-docker": executable file not found in $PATH`
`FATA[0002] Failed to run install                         err="exec: "system-docker": executable file not found in $PATH"`
I'm using debain stretch on the host system

**Comment by niusmallnan** [comment]
Maybe you should use `system-docker run ..... --volumes-from=all-volumes ...`
