### ISSUE TITLE
USB device recognized but not visible at /dev

### ISSUE THREAD

**Issue by l-t-k** [rancher/os#2344]
**RancherOS Version: v1.3**

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
I'm running RancherOS virtually at a proxmox host. The proxmox host shows the usb device:
`Bus 003 Device 002: ID 1a86:7523 QinHeng Electronics HL-340 USB-Serial adapter`

Passthrough on proxmox host to RancherOS virtual machine seems to work: (dmesg output)
`[   10.450093] usb 3-1: new full-speed USB device number 2 using uhci_hcd`
`[   10.878835] usb 3-1: New USB device found, idVendor=1a86, idProduct=7523`
`[   10.879762] usb 3-1: New USB device strings: Mfr=0, Product=2, SerialNumber=0`
`[   10.880767] usb 3-1: Product: USB2.0-Serial`

But I can't see the device at /dev (devices listed are the same as before the passthrough)

**Comment by kingsd041** [comment]
@l-t-k  I don't have a proxmox environment, so I tested it with ESXI6.7 and it works fine in my ESXI environment.
I suspect that the wrong `USB controller` was selected when you created the virtual machine. If your interface is usb3.0, please set `USB controller: 3.0` in proxmox.

dmesg logs:
```
[  125.896115] usb 2-1: new SuperSpeed USB device number 2 using xhci_hcd
[  125.917211] usb 2-1: New USB device found, idVendor=0781, idProduct=5591
[  125.917212] usb 2-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[  125.917214] usb 2-1: Product: Ultra USB 3.0
[  125.917214] usb 2-1: Manufacturer: SanDisk
[  125.917215] usb 2-1: SerialNumber: 4C530001261210102203
[  125.946040] usb-storage 2-1:1.0: USB Mass Storage device detected
[  125.946328] scsi host33: usb-storage 2-1:1.0
[  125.946375] usbcore: registered new interface driver usb-storage
[  125.947524] usbcore: registered new interface driver uas
[  126.948779] scsi 33:0:0:0: Direct-Access     SanDisk  Ultra USB 3.0    1.00 PQ: 0 ANSI: 6
```

```
[root@rancher opt]# ros -v
version v1.3.0 from os image rancher/os:v1.3.0

[root@rancher opt]# fdisk -l
Disk /dev/sda: 20 GiB, 21474836480 bytes, 41943040 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x93369112

Device     Boot Start      End  Sectors Size Id Type
/dev/sda1  *     2048 41940991 41938944  20G 83 Linux


Disk /dev/sdb: 28.7 GiB, 30752000000 bytes, 60062500 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0xcad4ebea

Device     Boot Start      End  Sectors  Size Id Type
/dev/sdb4  *       63 60062499 60062437 28.7G  7 HPFS/NTFS/exFAT
```

**Comment by kingsd041** [comment]
Close it.
If you still have doubts, please reopen it and let me know.
