### ISSUE TITLE
Can't select AWS cn-northwest-1 region 

### ISSUE THREAD

**Issue by p31415926** [rancher/os#2356]
Dear ,

I have copied RancherOS 1.2 AMI to China Beijing&NingXia Region. 
Beijing Region   ami-c2a678af   cn-north-1
NingXia Region  ami-599a8e3b  cn-northwest-1

But it looks like current version do not support cn-northwest-1 region. Could you please change awsec2 template to support cn-northwest-1. current version can support cn-north-1.

![rancher](https://user-images.githubusercontent.com/2805478/39868365-dc15303c-548b-11e8-9667-4a81c351700c.png)

**Comment by niusmallnan** [comment]
@loganhz  Can you please help to track this? It is about Rancher2.0 UI.

**Comment by loganhz** [comment]
Added https://github.com/rancher/ui/pull/1898/commits/4bcf15f0a17a7d36eb3a4ce79958ad7e8abbf7b9 It will be released in 2.0.1
