### ISSUE TITLE
Docker metrics on RancherOS

### ISSUE THREAD

**Issue by djbingham** [rancher/os#2357]
Hi,

Is it possible to enable docker metrics on RancherOS?

I'm trying to [collect Docker metrics with Prometheus](https://docs.docker.com/config/thirdparty/prometheus/) but I can't seem to get it working on RancherOS. I think the main issue is that RancherOS isn't letting me put Docker into experimental mode.

I've tried to do this two ways.

**First attempt:**
```
sudo ros config set rancher.docker.experimental true
sudo ros config set rancher.docker.metrics-addr 127.0.0.1:9323
sudo ros service restart docker
```
After that, I could see that the `experimental` and `metrics-addr` options were set in `ros config`:
```
> sudo ros config export
EXTRA_CMDLINE: /init
rancher:
  docker:
    experimental: true
    metrics-addr: 127.0.0.1:9323
    tls: true
  environment:
    EXTRA_CMDLINE: /init
  state:
    dev: LABEL=RANCHER_STATE
    wait: true
```
However, attempting to curl port 9323, either from a container on the same host or from another host, gave a "Connection refused" error.

**Second attempt:**
I created `/etc/docker/daemon.json`:
```
{
  "metrics-addr" : "127.0.0.1:9323",
  "experimental" : true
}
```
I then restarted Docker: `sudo ros service restart docker`.
That resulted in the following error for every Docker command:

`Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.32/version: dial unix /var/run/docker.sock: connect: permission denied`

**RancherOS Version: (ros os version)**
version v1.3.0 from os image rancher/os:v1.3.0

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
On [Bytemark Cloud](https://www.bytemark.co.uk/cloud-hosting), installed to disk using these instructions: https://rancher.com/docs/os/v1.x/en/installation/running-rancheros/server/install-to-disk.

**Comment by djbingham** [comment]
I've now also tried the following, with the same result as my first attempt above.

```
sudo ros config set rancher.docker.extra_args ["--experimental"]
sudo ros service restart docker
```

It seems that RancherOS simply doesn't allow docker to start properly with the experimental flag.

Does anyone know of a way to make this work? If not, is there a chance RancherOS could be updated to allow this flag?

**Comment by niusmallnan** [comment]
Hi, I cannot reproduce this issue.
```
[rancher@ip-172-31-9-59 ~]$ sudo ros -v
version v1.3.0 from os image rancher/os:v1.3.0

[rancher@ip-172-31-9-59 ~]$ sudo ros config set rancher.docker.extra_args ["--experimental"]
[rancher@ip-172-31-9-59 ~]$ sudo ros service restart docker
INFO[0000] Project [os]: Restarting project
INFO[0000] [0/18] [docker]: Restarting
INFO[0001] [0/18] [docker]: Restarted
INFO[0001] Project [os]: Project restarted

[rancher@ip-172-31-9-59 ~]$ docker run -it --rm  alpine
Unable to find image 'alpine:latest' locally
latest: Pulling from library/alpine
ff3a5c916c92: Pull complete
Digest: sha256:7df6db5aa61ae9480f52f0b3a06a140ab98d427f86d8d5de0bedab9b8df6b1c0
Status: Downloaded newer image for alpine:latest
/ #
```

**Comment by djbingham** [comment]
Hi @niusmallnan, thanks for checking it out. I've tried again and now the last part does work - I can put Docker into experimental mode using `sudo ros config set rancher.docker.extra_args ["--experimental"]`. However, I still cannot seem to get it to expose metrics, which was my original need.

I've tried setting `metrics-addr` and `metrics_addr` in `ros config` and also tried adding either of those to the `extra_args` for Docker. My `ros config` output now looks like this:
```
[rancher@monitor-01 ~]$ sudo ros config export
EXTRA_CMDLINE: /init
rancher:
  docker:
    experimental: true
    extra_args:
    - --experimental
    - --metrics-addr=127.0.0.1:9323
    metrics-addr: 127.0.0.1:9323
    metrics_addr: 127.0.0.1:9323
    tls: true
  environment:
    EXTRA_CMDLINE: /init
  state:
    dev: LABEL=RANCHER_STATE
    wait: true
```

With `metrics-addr=127.0.0.1:9323`, I should be able to curl `<host_ip>:9323/metrics` and get Docker metrics. I've tried curling `localhost:9323/metrics` and `172.17.0.1:9323/metrics` from inside a running container (172.17.0.1 being the output of `/sbin/ip route|awk '/default/ { print $3 }'`, as per https://stackoverflow.com/a/24716645).

Also, I can't work out how to remove items from config, hence I've now got  `metrics-addr` and `metrics_addr` both still set. If you can tell me how to remove old items from ros config, that would be appreciated too.

**Comment by djbingham** [comment]
Hi, is there any update on the `metrics-addr` issue? Just an indication of whether it looks like a bug or a mistake by me would be a really helpful starting point.

**Comment by JacieChao** [comment]
@djbingham Here's the update on this issue.
- Remove config from ros config
You can delete rancher.docker config in `/var/lib/rancher/conf/cloud-config.yml` and reboot it.
- Enable Docker Metrics on RancherOS
I have tried on RancherOS v1.3.0 and Docker metrics works on RancherOS if you set these parameters in `/etc/docker/daemon.json`.
```
{
  "metrics-addr" : "127.0.0.1:9323",
  "experimental" : true
}
```
There's something wrong with docker documents in [configure-and-run-prometheus](configure-and-run-prometheus).Please replace localhost with your RancherOS ip and restart your prometheus service. 

Here's an example about this https://github.com/docker/docker.github.io/issues/6012

If you still have problem, please let me know.

**Comment by djbingham** [comment]
@JacieChao Thank you very much for investigating this for me. Following your advice and link, I have got Docker metrics working now on RancherOS v1.3.0. The change I needed was to access metrics from inside a container via the IP address of the `docker0` network, rather than `eth0` or `127.0.0.1`.
