### ISSUE TITLE
ROS VMware ISO boots failed in air-gap network

### ISSUE THREAD

**Issue by niusmallnan** [rancher/os#2362]
**RancherOS Version:**
rancheros-vmware-v1.4.0-rc1

**Where are you running RancherOS?**
 docker-machine or boot from ISO

The vmware ISO enables open-vm-tools default, ROS will always download `open-vm-tools.yml` first.
But `open-vm-tools.yml` will download failed because of air-gap network, the `open-vm-tools` service can not start.

I consider caching os-services index by default in ISO, this way ROS can be booted without first downloading `open-vm-tools.yml`.

**Comment by SvenDowideit** [comment]
When I implemented this, I had a local to airgap network copy of the services yml web site and an airgap network registry - see https://github.com/SvenDowideit/bin-dir/tree/master/cloud-configs/airgap for more info

**Comment by kingsd041** [comment]
Tested with rancheros v1.4.0-rc2. Ros boots successfully in the air-gap network
