### ISSUE TITLE
Can't boot on VirtualBox

### ISSUE THREAD

**Issue by SamMousa** [rancher/os#2366]
** RancherOS Version: 1.3.0**

** Where are you running RancherOS? VirtualBox **

See this video, captured by VirtualBox: https://webmshare.com/z4b9j

No idea what's going on, i've tried both chipsets, removed all unnecessary devices and tried both NAT and bridged network...

![image](https://user-images.githubusercontent.com/547021/40412977-fc3198b8-5e74-11e8-936d-ca3b1f4293b0.png)

**Comment by SamMousa** [comment]
Turns out 512MB is not enough and results in a hard crash.
While I don't mind the requirement of 1GB; would it be possible to check memory requirement and die in a more friendly way?
(I'm assuming the issue comes from the fact that it's using a ramdrive which obviously requires RAM)

**Comment by niusmallnan** [comment]
The doc has been updated.
