### ISSUE TITLE
Cannot launch longhorn in rancheros

### ISSUE THREAD

**Issue by kingsd041** [rancher/os#2368]
**RancherOS Version: (ros os version)**
ros v1.4.0-rc2
**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
AWS

**Steps to Reproduce:**
1. Add an EC2 cluster on rancher2.0 and use ros v1.4.0-rc2 as the base image
2. After waiting for the cluster to start successfully, launch longhorn from the catalog
**Results:**
`longhorn-manager` failed to start, The below is error output:
```
ERRO[0000] Failed environment check, please make sure you have iscsiadm/open-iscsi installed on the host
FATA[0000] Error starting manager: Environment check failed: Invalid mount namespace /host/proc/1/ns/mnt, error Failed to execute: nsenter [--mount=/host/proc/1/ns/mnt mount], output nsenter: failed to execute mount: No such file or directory
, error exit status 1
```
Then I logged in to ros to manually enable the open-iscsi service and remove the longhorn-manager. Unfortunately, longhorn-manager still has the same error

**Comment by segator** [comment]
Same problem here 1.4.0

**Comment by Si-Richards** [comment]
Same here

**Comment by crackerjam** [comment]
Same issue here as well running on VMware 6.7. Tried deploying with both flexvolume and csi, but the same issue comes up regardless.

RancherOS 1.5.0
Rancher 2.1.5

**Comment by niusmallnan** [comment]
Please check this issue: https://github.com/rancher/longhorn/issues/10

**Comment by tibers** [comment]
still reporting this as broken in ROS 1.5.1

**Comment by niusmallnan** [comment]
Try this: https://github.com/rancher/longhorn/blob/master/docs/csi-config.md

**Comment by soriyath** [comment]
on CentOS 8 I had to run: `sudo dnf install -y iscsi-initiator-utils`

**Comment by abserari** [comment]
on CentOS 7:  Just run `yum install -y iscsi-initiator-utils`

**Comment by jmwilkinson** [comment]
@niusmallnan Looks like your reference is a victim of link rot.
