### ISSUE TITLE
Enable Wifi and 4G

### ISSUE THREAD

**Issue by srinidhikasagar** [rancher/os#2370]
**RancherOS Version: (ros os version)**
Rancher 1.3
**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
On Intel X86 hardware bare metal

Hello - Do you have any best known method to enable Wifi and 4G on x86 hardware? I'm using Rancher 1.3 on bare metal x86 HW with Wifi and 4G support. Does Rancher supports these configurations? I have enabled kernel-extras and could see the related drivers and firmwares are loaded.

**Comment by niusmallnan** [comment]
No, we have not officially supported it yet.

**Comment by MichalMichalak** [comment]
Is this anywhere on the road map?

**Comment by rootwuj** [comment]
### wifi support:
Verified the following cases with RancherOS v1.5.0-rc1

* Verify basic configuration on single NIC and dual NIC
* Basic configuration via cloud-config on boot
* Set the wrong network configuration
* Modify static IP address
* Verify DHCP
* Verify support for 5GHz Wi-Fi
* Switch Wi-Fi configuration
* Try more Wi-Fi security protocols
* Connect to a hidden Wi-Fi
* Reconnect Wi-Fi automatically
* Use cloud-init datasources via Wi-Fi network



### 4glte support:
Verified the following cases with RancherOS v1.5.0-rc2

* Verify basic configuration on single NIC and dual NIC
* Basic configuration via cloud-config on boot
* Set the wrong interface name
* Remove 4G NIC configuration
* Verify restart rancheros, 4G NIC starts automatically
* 4G NIC hot-plugging
