### ISSUE TITLE
(1.40-rc2) open-vm-tools doesn't seem to work

### ISSUE THREAD

**Issue by benok** [rancher/os#2371]
**RancherOS Version: (ros os version)**
1.4.0-rc2

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
VMware ESXi 6.0.0 6765062

I installed 1.4.0-rc2 to ESXi VM from generic iso image. 
If I tried to power off / reboot from ESXi,  I got "A general system error occurred: Invalid Fault" error, 
and can't be executed.

open-vm-tools container is running, but doesn't seem to work.

```
[rancher@rancher ~]$ sudo system-docker ps
CONTAINER ID        IMAGE                                 COMMAND                  CREATED             STATUS              PORTS               NAMES
d2214721baac        rancher/os-docker:18.03.1             "ros user-docker"        About an hour ago   Up About an hour                        docker
4c286dae7120        rancher/os-debianconsole:v1.4.0-rc1   "/usr/bin/ros entr..."   About an hour ago   Up About an hour                        console
4d4136ed9069        rancher/os-openvmtools:10.2.5-2       "/usr/bin/ros entr..."   About an hour ago   Up About an hour                        open-vm-tools
ae9e3cc6687a        rancher/os-base:v1.4.0-rc2            "/usr/bin/ros entr..."   About an hour ago   Up About an hour                        ntp
90774725c132        rancher/os-base:v1.4.0-rc2            "/usr/bin/ros entr..."   About an hour ago   Up About an hour                        network
4624f9c8a357        rancher/os-base:v1.4.0-rc2            "/usr/bin/ros entr..."   About an hour ago   Up About an hour                        udev
2ee66fc5703c        rancher/container-crontab:v0.4.0      "container-crontab"      About an hour ago   Up About an hour                        system-cron
cc6d07ad3e02        rancher/os-syslog:v1.4.0-rc2          "/usr/bin/entrypoi..."   About an hour ago   Up About an hour                        syslog
007d9820a280        rancher/os-acpid:v1.4.0-rc2           "/usr/bin/ros entr..."   About an hour ago   Up About an hour                        acpid
```

**Comment by superseb** [comment]
Can you share the logs from the `open-vm-tools` container?

**Comment by Jason-ZW** [comment]
I can reproduce the issue with 1.4.0-rc2. I will check the open-vm-tools.

**Comment by chriswayg** [comment]
How much memory does the ESXi VM have? Mine crashed with 1024 MB in VB, but works with 1280 MB.

**Comment by Jason-ZW** [comment]
@chriswayg  I have been using 2048 MB for development and debugging, personally, I haven't tested below 2048 MB of memory on ESXi, I think https://github.com/rancher/os/issues/2359#issuecomment-388817566 will be updated soon.

**Comment by benok** [comment]
I'm using with 4096MB with swap 4096MB. 
I think it's plenty and memory consumption isn't a cause of this issue. 

I don't have enough time to take a log now.
How to take a log using system-docker ? Is that same with normal docker ?
Do you have some link to do?

**Comment by niusmallnan** [comment]
Tested with `rancher/os-openvmtools:10.2.5-3`, this issue should be fixed.
