### ISSUE TITLE
RancherOS 1.4.0-rc2 Kernel Panic on Docker Machine in VirtualBox 

### ISSUE THREAD

**Issue by chriswayg** [rancher/os#2372]
**RancherOS Version: 1.4.0-rc2**

- 1.4.0-rc2 will Kernel Panic on Docker Machine in VirtualBox 
- 1.4.0-rc1 was OK (rc2 seems to use more memory during startup)

**Where are you running RancherOS? docker-machine**

`docker-machine create -d virtualbox --virtualbox-boot2docker-url https://github.com/rancher/os/releases/download/v1.4.0-rc2/rancheros.iso RancherOS-1.4.0-rc2-DM`

- Docker Machine allocates 1024 MB of Memory in VirtualBox, which is not enough any more
- changing this to 1280 MB will allow it to start.
- I encountered the same problem with my RancherOS Box, which works after increasing the memory: https://app.vagrantup.com/chriswayg/boxes/RancherOS/versions/0-1.4.0-rc2

![virtualbox_rancheros-1 4 0-rc2-dm_30_05_2018_00_58_26](https://user-images.githubusercontent.com/13681327/40673708-1f1c8600-63a5-11e8-9b53-e433b0d56c60.png)

**Comment by niusmallnan** [comment]
The doc has been updated.

**Comment by erikwilson** [comment]
Using Quickstart docs and encountered the same kernel panic, added `--virtualbox-memory "1280"` argument to the `docker-machine create` command and things worked.

Looks like there are a couple places that still need updating tho:
https://github.com/rancher/docs/search?q=virtualbox+boot2docker+url
