### ISSUE TITLE
Building custom kernel modules requires CONFIG_STACK_VALIDATION= in 1.4.0

### ISSUE THREAD

**Issue by ryansch** [rancher/os#2374]
**RancherOS Version: (ros os version)**
v1.4.0
**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
docker-machine

I have side by side attempts to build https://github.com/maK-/SimplestLKM in a container with the `kernel-headers' service enabled.

1.3.0:
```
# make
make -C /lib/modules/4.9.80-rancher/build M=/root/SimplestLKM modules
make[1]: Entering directory '/lib/modules/4.9.80-rancher/build'
  CC [M]  /root/SimplestLKM/hello.o
  Building modules, stage 2.
  MODPOST 1 modules
  CC      /root/SimplestLKM/hello.mod.o
  LD [M]  /root/SimplestLKM/hello.ko
make[1]: Leaving directory '/lib/modules/4.9.80-rancher/build'
```

1.4.0:
```
# make
make -C /lib/modules/4.14.32-rancher2/build M=/root/SimplestLKM modules
make[1]: Entering directory '/lib/modules/4.14.32-rancher2/build'
make[2]: *** No rule to make target 'tools/objtool/objtool', needed by '/root/SimplestLKM/hello.o'.  Stop.
Makefile:1528: recipe for target '_module_/root/SimplestLKM' failed
make[1]: *** [_module_/root/SimplestLKM] Error 2
make[1]: Leaving directory '/lib/modules/4.14.32-rancher2/build'
Makefile:12: recipe for target 'default' failed
make: *** [default] Error 2
```

**Comment by ryansch** [comment]
This specifically prevents us from building the parallels guest tools.

**Comment by ryansch** [comment]
More information:
https://lists.debian.org/debian-knoppix/2017/01/msg00002.html

`# make CONFIG_STACK_VALIDATION=` works

**Comment by ryansch** [comment]
Also: https://bugzilla.redhat.com/show_bug.cgi?id=1321628

**Comment by ryansch** [comment]
Here's a functional workaround for this issue: https://github.com/outstand/docker-parallels-tools/commit/6f0188f5e9e9a2807b58f2ba4d7922f331666edb

**Comment by niusmallnan** [comment]
Yes, I also feel pain for it.

The build failure appears to have been introduced by a regression in the kernel packaging which breaks all out-of-tree-module builds. The objtool binary is no longer being included and it is required for external module builds when the kernel is compiled with CONFIG_STACK_VALIDATION=y.

**Comment by zhoubofsy** [comment]
@ryansch @niusmallnan 
kernel with `CONFIG_STACK_VALIDATION`, it use objtool to perform stack metadata validation on object file ("*.o") when compile third kernel modules. The objtool is generated in `./tool/objtool` directory when building kernel, but there isn't objtool in RancherOS.

There are three way to eliminate influence of `STACK_VALIDATAION` :

	1. compile source with `CONFIG_STACK_VALIDATION=`, it doesn't perform stack metadate validation
	2. copy the objtool into RancherOS and build again
	3. rebuild kernel without `STACK_VALIDATION` of `arch/Kconfig`, and chose `CONFIG_UNWINDER_GUESS` instead of `CONFIG_UNWINDER_ORC` or `CONFIG_UNWINDER_FRAME_POINTER`

I recommend the first.

**Comment by rootwuj** [comment]
Tested with RancherOS version- v1.4.1-rc2 with AWS.
This version can successfully build SimplestLKM.

**Comment by niusmallnan** [comment]
Backported to v1.4.1.
