### ISSUE TITLE
All user docker data will be wiped with "ros os upgrade" on RancherOS v1.3.0

### ISSUE THREAD

**Issue by t-tsutsumi** [rancher/os#2376]
**RancherOS Version: (ros os version)**
v1.4.0

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
baremetal and VirtualBox

**Behavior**
Upgrade RancherOS to v1.4.0 (**from v1.3.0**) with "`ros os upgrade`", all user docker data will be wiped.

[EDITED] I clarified ambiguous passages: `all docker data` -> `all user docker data`

**Comment by ryansch** [comment]
Just above that is the following note:
```
User-docker does not work well with docker-17.12.1+. For more information, please refer to here. Upgrading to v1.4.0 will cause you to lose user-docker data. Please refer to guide for instructions on how to preserve it.
```

**Comment by Toonix** [comment]
this happens randomly? Update 2 rancher v1.30 to v1.40 one lost all containers

**Comment by lost-carrier** [comment]
Not random here: Installed on baremetal...
```
[rancher@marvin ~]$ sudo ros os version
v1.3.0
[rancher@marvin ~]$ sudo ros config get rancher.bootstrap_docker.storage_driver
overlay2
[rancher@marvin ~]$ sudo ros config get rancher.system_docker.storage_driver
overlay2
[rancher@marvin ~]$ sudo ros os upgrade
Upgrading to rancher/os:v1.4.0
[...]
```
...but still after update...
```
[rancher@marvin ~]$ docker ps --all
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
[rancher@marvin ~]$
```

**Comment by niusmallnan** [comment]
@lost-carrier If you want recover user-docker data, you should use this https://github.com/rancher/os/issues/2300#issuecomment-390456535

**Comment by t-tsutsumi** [comment]
Since the method of restoring a user docker data has been added to the release note of v1.4.0, this problem can be solved. However, you should also refer to following: https://github.com/rancher/os/issues/2300#issuecomment-393744899

**Comment by Toonix** [comment]
Not good. I changed sudo ros console ubuntu and RancherOS crashed. After reboot overlay2 files could not mounted anymore.
