### ISSUE TITLE
Can't access server anymore (except SSH)

### ISSUE THREAD

**Issue by jlelse** [rancher/os#2377]
**RancherOS Version: (ros os version)**

1.4.0

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**

Hetzner Cloud

After upgrading my server from 1.3.0 I can't access the server anymore except with SSH. Via SSH I can access the internet and docker is also running etc., but trying to connect to some other PORT always gives me "can't find route to host". Is iPv4 disabled or what are the reasons?

**Comment by jlelse** [comment]
I don't have access to AWS. I now wait for the Cloud provider to provide the latest ISO and then I try with directly installing 1.4.0.

**Comment by jlelse** [comment]
Even with a fresh 1.4.0 install, it doesn't work when I try to connect to the IPv4 address... SSH works with no problems.

**Comment by niusmallnan** [comment]
I tried on AWS:
```
# run in ros
docker run -idt -p 8888:80 nginx

# run outside
curl http://<external-ip>:8888/
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
```

**Comment by niusmallnan** [comment]
@jlelse  can you give me a demo? I can get someone to try it on `Hetzner Cloud`.

**Comment by Flipez** [comment]
@niusmallnan @jlelse I tried the exact same setup and it worked. 

installed RancherOS 1.3, started nginx -> works
upgrade to RancherOS 1.4, started nginx -> works

**Comment by jlelse** [comment]
I tried almost exactly that on Hetzner, didn't work. On Hetzner you first need to create a VPS with Ubuntu or so and then mount the ISO to install it.

But I now contacted their support, let's see what they say.

**Comment by Flipez** [comment]
Did you restart the service you've tried to connect with?

**Comment by jlelse** [comment]
It works now.. Very strange, but I'll now try to migrate my setup, let's see, if this works..

**Comment by jlelse** [comment]
It worked now! Thanks for your help :)
