### ISSUE TITLE
Running any container fails when using RancherOS 1.4.0 in VirtualBox from ISO

### ISSUE THREAD

**Issue by kstewart83** [rancher/os#2378]
**RancherOS Version: v1.4.0**
**Where are you running RancherOS? VirtualBox (custom VM w/ 2048 GB RAM)**

When trying to start any docker container, such as:

`$ docker run hello-world`

After successfully downloading the image layers, it comes back with the error:

> Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402 container init caused \"rootfs_linux.go:107: jailing process inside rootfs caused \\\\\\"pivot_root invalid argument\\\\\\"\\"": unknown.

This occurs with VirtualBox installed on a Windows 10 machine as well as with Mac OS. The same VM booted with a RancherOS 1.3.0 ISO works just fine. VM is created as a 64-bit Linux with all the defaults except the RAM is changed to 2048.

**Comment by niusmallnan** [comment]
We upgrade user-docker to 18.03.1-ce, not sure if it's a Docker's problem.
But you can use `docker`, after you run `ros install xxxx` on VirtualBox.

**Comment by JacieChao** [comment]
How about using docker-machine to create rancheros in VirtualBox? I have run rancheros-v1.4.0 by docker-machine using VirtualBox, it works well. 
Then I create a VM using VirtualBox, VM is created by using `Linux 2.6/3.x/4.x(64 bit)`, user docker also works well. 
Please have a try. 

Maybe it's related to kernel or virtualization, I just found an issue like yours in docker. (https://github.com/moby/moby/issues/32467)

**Comment by jlelse** [comment]
I think that happens when you run RancherOS from the ISO. After installing it, it works fine.

**Comment by niusmallnan** [comment]
Reopen this issue:
Although we do not recommend using docker in the memory filesystem, it still needs to be fixed.

**Comment by rootwuj** [comment]
Tested with RancherOS version- v1.4.1-rc2 with VirtualBox.
This version can use docker in the memory filesystem, and 'docker run' can be executed normally.

**Comment by niusmallnan** [comment]
Backported to v1.4.1.
