### ISSUE TITLE
Auto Login on Rancher 1.0.1

### ISSUE THREAD

**Issue by rldourado** [rancher/os#2383]
**RancherOS Version: (ros os version)**
1.0.1

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
VMWare ESXi Virtual Machine

I lost my SSH Key and have to access a Rancher OS 1.0.1 machine but there is no autologin option at boot time. What can I do?

**Comment by niusmallnan** [comment]
You can update the cmdline in bootloader process.
For example, you can try this: `rancher.autologin=tty1`

**Comment by rldourado** [comment]
I think I'm missing some point.

This is my virtual machine bootloader screen:

![rancher os 1 0 1 02 bootloader](https://user-images.githubusercontent.com/2440820/41242038-ecbc03dc-6d74-11e8-832c-7fdd7b0f6e39.PNG)


When I tried to input `rancher.autologin=tty1` into this command line, I had the `No such file ou directory` message:

![rancher os 1 0 1 03 bootloader](https://user-images.githubusercontent.com/2440820/41242149-26ad6d9c-6d75-11e8-8b41-828aef68d226.PNG)


There is another way to edit the bootloader command line?

**Comment by niusmallnan** [comment]
When you can access the bootloader, you have two ways:

1. Select `autologin on tty1 and tty0`
![image](https://user-images.githubusercontent.com/998984/41331338-23bcb9f2-6f0b-11e8-9d3c-7d72c7bc0963.png)

2. Press TAB and edit the kernel params, just add `rancher.autologin=<tty you expect>`, then press `Enter`

**Comment by superseb** [comment]
He's on v1.0.1, you need to enter `rancher-v1.0.1 rancher.autologin=tty1`

**Comment by rldourado** [comment]
@niusmallnan , my rancher os version is 1.0.1 and it does not have such boottime menu like 1.1.0 and early versions.

@superseb , it worked and solved my problem.

Thanks very much by the help, you guys!
