### ISSUE TITLE
Rancher OS stopped working after upgrading to v1.4.0 from v1.2.0 (With 1GB of RAM)

### ISSUE THREAD

**Issue by vroad** [rancher/os#2384]
**RancherOS Version: (ros os version)**
v1.2.0

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**

AWS(ECS Enabled AMI)

I just ugraded with `sudo ros os upgrade` to update to v1.4.0 and instance kept failing to reboot. I couldn't even get logs from the instance on AWS management console.

I created another EC2 instance(and EBS volume), and to make my services work again, I copied files used in my docker containers from older EBS volume.

EDIT:
I've tried the same thing with another instance and version 1.3.0 instead of 1.4.0. This time, the instance booted successfully.
I then upgraded RancherOS to v1.4.0 from v1.3.0, and got the same problem. It seems that this problem is only present on v1.4.0.

I have been using t2.micro instance type, which has 1GB of RAM. Is this relevant?

**Comment by niusmallnan** [comment]
We added more features in 1.4, which caused it to need more memory when booting up.
For aws, t2.small is needed.

**Comment by vroad** [comment]
But t2.small would be overkill for our use case. Should I stick to v1.3.0 for now? Or would it be possible to configure RancherOS to use swap, so that it can complete booting with only 1GB of RAM?
Will memory usage go down in future releases?

I'd like to know why RancherOS refused to write something to system log. I could get error messages from system log when I tried the same with t2.nano and Rancher OS v1.2.0.

**Comment by vroad** [comment]
I think it would be better to mention memory requirement change somewhere. If I could get warning before upgrading with commands, that would be much better.

Isn't there easy way to rollback when upgrading fails? I created another instance to solve this, because I couldn't even SSH into it.
I should have created EBS snapshot for rollback, though.

**Comment by stffabi** [comment]
Current memory requirements are mentioned here: https://rancher.com/docs/os/v1.x/en/#hardware-requirements

**Comment by vroad** [comment]
I hope this to be resolved in v1.5.0.
https://github.com/rancher/os/issues/2392
