### ISSUE TITLE
403 when trying to download BUILD_DOCKER_URL during build

### ISSUE THREAD

**Issue by fredrikbergstrompricer** [rancher/os#2385]
**RancherOS Version: (ros os version)**
1.3.0
**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
VirtualBox VM

When cloning the repo (release branch 1.3.0) and running `make` we get an error when the build is trying to download the docker binary from `https://download.docker.com/builds/Linux/x86_64/docker-1.10.3`.

```
Step 48/52 : RUN curl -fL ${!BUILD_DOCKER_URL} > /usr/bin/docker &&     chmod +x /usr/bin/docker
 ---> Running in 5ad4716b4ac0
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 403 Forbidden
> :pThe command '/bin/sh -c curl -fL ${!BUILD_DOCKER_URL} > /usr/bin/docker &&     chmod +x /usr/bin/docker' returned a non-zero code: 22
time="2018-06-13T15:46:37+02:00" level=fatal msg="exit status 22" 
Makefile:11: recipe for target 'default' failed
make: *** [default] Error 1
```
I've tested it with the 1.4.0 release too, with the same result (tries to fetch the same binary).

**Comment by superseb** [comment]
Upstream issue: https://github.com/docker/for-linux/issues/338

Fixed around half an hour ago.
