### ISSUE TITLE
Publish Rancher 2.x compatible ISO image

### ISSUE THREAD

**Issue by olljanat** [rancher/os#2388]
**RancherOS Version: (ros os version)**
v1.4.0

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
vSphere

Rancher OS v1.4.0 release notes says that:
- "Docker docker-18.03.1-ce by default"
- "Added Rancher2.0 support for RancherOS v1.4.0"

But latest Rancher 2.x compatible docker version is 17.03.2-ce.

So we should either change default docker version on rancheros-vmware.iso to 17.03.2-ce or publish another Rancher 2.x compatible version.

If you decide create new one then let me know so I can update my PR rancher/ui#1975

**Comment by superseb** [comment]
Think this has been discussed before, you can switch Docker version using cloud init as described here: https://rancher.com/docs/os/v1.x/en/installation/configuration/switching-docker-versions/

As RancherOS is also a product which can be used to run Docker, we try to keep it up2date with the latest stable Docker releases (which is 18.03 at the moment, and will be 18.06 in the next release). Building separate releases will be lots of duplication, while the current releases can be automatically configured to use the Docker version that is required.

I'll let @niusmallnan chime in for his opinion.

**Comment by olljanat** [comment]
IMO, it is super weird that Rancher 2.x switched to Kubernetes but same time RancherOS is running by default docker version which is not compatible with Kubernetes.

Switching docker version works of course but then Rancher 2.x should be able to do that automatically when deploying RancherOS to vSphere with it.

**Comment by olljanat** [comment]
>So when you use the ISO in Rancher though machine, it does select the appropriate default docker version.

Ahaa. I missed that info as https://rancher.com/docs/rancher/v2.x/en/installation/ha-server-install/#1-provision-linux-hosts says that "_If you are using RancherOS, make sure you switch the Docker engine to a supported version using sudo ros engine switch docker-17.03.2-ce_"

I can also see that my PR was merged so it should work directly on rancher/rancher:master now.
I will test that tomorrow and report back.

**Comment by olljanat** [comment]
I got confirmation from my friend that vSphere driver switches automatically to docker-17.03.2-ce version.

Thanks guys.
