### ISSUE TITLE
ECS container instances are not automatically de-registered when shutting down and rebooting

### ISSUE THREAD

**Issue by vroad** [rancher/os#2394]
**RancherOS Version: (ros os version)**
v1.2.0

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
AWS

I'm using ECS-optimized AMI of RancherOS. When I shutdown the EC2 instance, existing container instance is not removed, the ECS agent of that instance gets disconnected, and new one with another container instance id (but with the same EC2 instance id) is created when I reboot that instance. I expect container instance to be automatically removed from ECS cluster when I shutdown it. Do I need additional config to automatically remove container intance? I only set ECS cluster and available logging drivers in userdata config.

I don't want invalid container instance to remain in the ECS cluster, since tasks on the invalid container instance are not automatically stopped, and ECS tries to place new tasks on that invalid instance. I need to manually deregister ECS instance everytime when I reboot the instance.

I created another ECS cluster with CoreOS, using ignition config from official website, and confirmed that this doesn't occur with CoreOS.

https://coreos.com/os/docs/latest/booting-on-ecs.html

**Comment by vroad** [comment]
I've found that you need to mount host directories to preserve container instance ID between reboots, but how can I configure that with cloud-config?

https://rancher.com/docs/os/v1.2/en/amazon-ecs/

**Comment by Jason-ZW** [comment]
@vroad can you share what host directories you have been mount?

**Comment by vroad** [comment]
@Jason-ZW I guess you need to mount some host directory to /data in the ecs-agent. If you just use configs from above rancher docs page, this is not configured.

**Comment by kingsd041** [comment]
@vroad Thank you for your comment
Fixed in rancheros-v1.4.2-rc1

**Comment by niusmallnan** [comment]
backported to v1.4.2
