### ISSUE TITLE
Documentation error regarding RAM size for iso boot

### ISSUE THREAD

**Issue by pielgrzym** [rancher/os#2396]
**RancherOS Version: (ros os version)**
v1.4.0

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**

When running Rancher with 1gb of ram on VirtualBox the machine runs into kernel panic and reboots. Increasing to 2gb fixes the problem. https://rancher.com/docs/os/v1.2/en/running-rancheros/workstation/boot-from-iso/ - documentation is unclear how much RAM should the iso require.

**Comment by niusmallnan** [comment]
https://rancher.com/docs/os/v1.x/en/#hardware-requirements
