### ISSUE TITLE
Kernel panic on DigitialOcean upgrading to 1.4 with 1GB RAM

### ISSUE THREAD

**Issue by prologic** [rancher/os#2397]
After upgrading to Rancher OS v1.4 on DigitalOcean Droplets the boot process kernel panics.
<img width="1146" alt="screen shot 2018-06-24 at 4 39 04 pm" src="https://user-images.githubusercontent.com/1290234/41824961-d30799d4-77cd-11e8-9022-4895ac84fb6d.png">

**Comment by prologic** [comment]
Upgrading the Droplet to 2GB of RAM resolved this.
<img width="1146" alt="screen shot 2018-06-24 at 4 48 08 pm" src="https://user-images.githubusercontent.com/1290234/41825011-788940ce-77ce-11e8-9999-c256d942207d.png">

**Comment by prologic** [comment]
Q: Why does Rancher OS v1.4 require 2GB of memory just to boot up? This is unacceptable as now a single Rancher OS instance on Digital Ocean costs you a **minimum** $10.00/month

**Comment by niusmallnan** [comment]
We added more features in 1.4, which caused it to need more memory when booting up.
The next release will optimize this memory problem.
Current memory requirements are mentioned here: https://rancher.com/docs/os/v1.x/en/#hardware-requirements

**Comment by prologic** [comment]
What was added that blew the bootup memory requirements from 1GB to 2GB?

**Comment by SvenDowideit** [comment]
does that mean that setting the user-docker to alpine in the cloud-init would reduce it again?

**Comment by thaJeztah** [comment]
> We change the default user-docker to 18.03, this has caused system-images to become large, requiring 1280MB of memory at bootup.

What docker version was it using before that?

**Comment by juliengk** [comment]
i run into the same prob. With RancherOS 1.2, a droplet with 1GB memory was enough.

**Comment by juliengk** [comment]
```
# ros -v
version v1.2.0 from os image rancher/os:v1.2.0
```

```
# system-docker version
Client:
 Version:      library-import
 API version:  1.23
 Go version:   go1.8.5
 Git commit:   library-import
 Built:        library-import
 OS/Arch:      linux/amd64

Server:
 Version:      library-import
 API version:  1.23
 Go version:   go1.8.5
 Git commit:   library-import
 Built:        library-import
 OS/Arch:      linux/amd64
```

**Comment by niusmallnan** [comment]
@thaJeztah  
> What docker version was it using before that?

17.09.1

**Comment by niusmallnan** [comment]
In the next version, I will reduce system-docker and default console.

For user-docker, will also keep the latest stable-ce version.

**Comment by prologic** [comment]
Rather than complain about the latest Rancher OS being a resource (*memory*) hog at bootup and idle (*with no user containers running*) I decided to roll my own called [MCL](https://github.com/prologic/minimal-container-linux)

I sincerely hope later versions of Rancher OS become more resource efficient
