### ISSUE TITLE
Documents update for rancher.state configuration

### ISSUE THREAD

**Issue by niusmallnan** [rancher/os#2399]
These  `rancher.state` configurations are not documented/explained anywhere.
```
rancher.state:
                directory
                fstype
                dev
                wait
                required
                autoformat
                mdadm_scan
                script
                oem_fstype
                oem_dev
```
Users do not need to configure most of these, some should be documented later.

**Comment by mainiak** [comment]
And from`rancher.state.lvm_scan rancher.state.cryptsetup` https://github.com/rancher/os/pull/2545 ?
