### ISSUE TITLE
Rancheros 1.4.0 ZFS won't enable

### ISSUE THREAD

**Issue by nordge1** [rancher/os#2402]
Rancheros 1.4.0

Virtualbox

Following the docs [here](https://rancher.com/docs/os/v1.x/en/installation/storage/using-zfs/) the first step is to enable the ZFS module but I get the following error.
'''[rancher@rancher ~]$ sudo ros service enable zfs
FATA[0000] zfs is not a valid service'''

So, 

'''[rancher@rancher ~]$ sudo ros service list
disabled amazon-ecs-agent
disabled amazon-ena-driver
disabled crontab
disabled open-iscsi
disabled kernel-extras
enabled  kernel-headers
disabled kernel-headers-system-docker
disabled open-vm-tools
disabled qemu-guest-agent
disabled rancher-server
disabled rancher-server-stable
disabled amazon-metadata
disabled volume-cifs
disabled volume-efs
disabled volume-nfs
enabled  ubuntu-console'''

Obviously it is an invalid service.
Shouldn't this work per the docs?
Or perhaps I need to add something not listed on the docs page to my cloud-config?

Thanks for your help

Edit
It appears [this](https://github.com/rancher/os/issues/2299) may be the same issue after further review.
Not sure though.

**Comment by superseb** [comment]
ZFS was dropped in v1.4.0 due to https://github.com/rancher/os/issues/2299, it is still open to be fixed.
