### ISSUE TITLE
RancherOS v1.4.0 does not boot on an AWS EC2 t2.micro instance

### ISSUE THREAD

**Issue by mikemoate** [rancher/os#2406]
**RancherOS Version: (ros os version)**
v1.4.0

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
AWS EC2 t2.micro

RancherOS v1.4.0 does not appear to successfully boot when run as an AWS EC2 t2.micro instance. The EC2 system log shows:

```
[            ] init:info: Connected to Docker at unix:///var/run/system-docker.sock
[            ] init:info: Loading images from /usr/share/ros/images.tar
[            ] init:fatal: FATAL: failed loading images from /usr/share/ros/images.tar: exit status 1
[   18.525102] Kernel panic - not syncing: Attempted to kill init! exitcode=0x00000100
[   18.525102] 
[   18.532094] CPU: 0 PID: 81 Comm: init Not tainted 4.14.32-rancher2 #1
[   18.537238] Hardware name: Xen HVM domU, BIOS 4.2.amazon 08/24/2006
[   18.542036] Call Trace:
[   18.544079]  dump_stack+0x5a/0x6f
[   18.546640]  panic+0xd8/0x238
[   18.548935]  ? css_set_move_task+0xc3/0x128
[   18.552198]  do_exit+0x50a/0x923
[   18.554764]  do_group_exit+0x9f/0x9f
[   18.557543]  SyS_exit_group+0x10/0x10
[   18.560417]  do_syscall_64+0x78/0x87
[   18.563394]  entry_SYSCALL_64_after_hwframe+0x3d/0xa2
[   18.567263] RIP: 0033:0x482ef4
[   18.569589] RSP: 002b:000000c4205f91a8 EFLAGS: 00000246 ORIG_RAX: 00000000000000e7
[   18.575582] RAX: ffffffffffffffda RBX: 0000000000000000 RCX: 0000000000482ef4
[   18.580825] RDX: 0000000000000000 RSI: 0000000000000000 RDI: 0000000000000001
[   18.586298] RBP: 000000c4205f91e8 R08: 0000000000000000 R09: 0000000000000000
[   18.591625] R10: 0000000000000000 R11: 0000000000000246 R12: 0000000000000001
[   18.597089] R13: 00000000000000d0 R14: 0000000000000450 R15: 0000000000000200
[   18.602632] Kernel Offset: 0x36000000 from 0xffffffff81000000 (relocation range: 0xffffffff80000000-0xffffffffbfffffff)
```

This appears to be similar to https://github.com/rancher/os/issues/1810 that was caused by a lack of available memory, except that was when using a t2.nano (t2.nano has 0.5GB RAM, a t2.micro has 1GB RAM).

v1.2.0 did boot successfully in an EC2 micro instance without any issues. I have not tried any of the intermediate versions.

**Comment by mikemoate** [comment]
According to https://rancher.com/docs/os/v1.x/en/ a minimum of 1.7GB of memory is required on AWS now, which means at least a t2.small. This wasn't mentioned in any of the release notes, and is a dramatic increase from v1.2.0.

**Comment by niusmallnan** [comment]
At least t2.small if using RancherOS v1.4.
It will be improved in the next release.

**Comment by olljanat** [comment]
Is this actually duplicate with #2395 ?
Different platform but same root cause anyway.
