### ISSUE TITLE
Boot crash with v1.4.0 on VMWare: Kernel panic

### ISSUE THREAD

**Issue by spawnia** [rancher/os#2407]
**RancherOS Version: (ros os version)**

v1.4.0 4.14.32-rancher2
https://releases.rancher.com/os/latest/rancheros-vmware.iso

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**

Provisioning hosts via Rancher 2.0.5 on vSphere, ESXI 6.0.0

You can look up my Rancher specific configuration in https://github.com/rancher/rancher/issues/14480

The gist is that the nodes are stuck in "Waiting for VMware Tools to come online". When i try to access the console via vSphere client, i found that RancherOS crashes during boot.

![capture](https://user-images.githubusercontent.com/12158000/42556920-6436a36a-84ed-11e8-96c6-29d526f9ae9b.PNG)

After that i get send back to the boot selection menu.

**Comment by niusmallnan** [comment]
For rancheros-vmware.iso, you should boot at least 2GB memory.
https://rancher.com/docs/os/v1.x/en/#hardware-requirements

**Comment by niusmallnan** [comment]
If you want to use it as a kube node, 4GB at least.

**Comment by spawnia** [comment]
I did try it with 2GB and 4GB of memory.

**Comment by niusmallnan** [comment]
It's very strange, I have tried 2GB on my setup, it worked fine.
https://github.com/rancher/os/issues/2390#issuecomment-400157648

**Comment by spawnia** [comment]
This seems like a different issue. Do you think the ESXi version could have something to do with this? Do i possibly need some extra cloud-init settings?

**Comment by cedvan** [comment]
Hi, 

We have the same problem. but when access the console via vSphere client Rancher OS boot properly, no fatal. However sometimes it works and sometimes rancher node stuck on "Waiting VMWare Tools". This problem is present with vSphere VMWare ESXi 5.5. 

We tried on a vSphere VMWare ESXi 6.7, the problem disappear

**Comment by niusmallnan** [comment]
We use open-vm-tools 10.2.5, not sure if it is not compatible with the old ESXi version.

**Comment by spawnia** [comment]
The docs say ESXi `5.5` and upwards https://docs.vmware.com/en/VMware-Tools/10.2/rn/vmware-tools-1025-release-notes.html

**Comment by boudr** [comment]
I have this same exact issue but with Virtual Box.

**Comment by segator** [comment]
the problem happens on vmware workstation 12 pro
v1.4.1

**Comment by niusmallnan** [comment]
Is there someone can help to test this ISO? 
http://releases.rancher.com/os/test/rancheros-master-vmware.iso

We really didn't reproduce the problem in 2G memory, but we did some optimizations to reduce the memory requirements, but the ISO size increased a lot.

**Comment by spawnia** [comment]
I suspect this is a Linux Kernel/Virtualization issue.

I had issues with deploying CoreOS on my particular ESXi host as well. After updating ESXi to a certified version for the hardware we are running on, RancherOS and CoreOS booted without a problem.

As a workaround, you can use `boot2docker` - as long as you are not running it in production it works fine. It uses an older Kernel which worked fine for me.

**Comment by niusmallnan** [comment]
@spawnia Thanks! 

All the friends under this thread, can you try to upgrade your hypervisor?

**Comment by spawnia** [comment]
Closing this issue since upgrading the hypervisor resolved the issue, see https://github.com/rancher/os/issues/2407#issuecomment-432553582
