### ISSUE TITLE
Re-run cloud-config on reboot (is there a first boot config flag or lock file?)

### ISSUE THREAD

**Issue by albertdb** [rancher/os#2413]
Hi,

We generate our custom RancherOS images with Packer, so when we boot an instance, it's not really its first boot.

Is there a way (enabling a config flag, removing a lock file, etc) to consider the following boot as the first boot, so cloud-config directives are executed or taken into account?

Thank you very much

**Comment by albertdb** [comment]
Just to clarify, if I launch an instance based on our images with a new cloud-config, the new configuration is written to `/var/lib/rancher/conf/cloud-config.d/boot.yml`, but it is not merged with `/var/lib/rancher/conf/cloud-config.yml`, so `cloud-init-execute` doesn't take into account the new configuration.

I guess that the merge is only perfomed on first boot.

**Comment by albertdb** [comment]
I'm able to reproduce this issue in 1.3.0, but not in 0.4.3 (user data is always taken into account). The 
environment in both cases is OpenStack and cloud-config is loaded via Configuration drive.

This makes me think that it is not about a flag, but a bug. Correct me if I'm wrong, please.

**Comment by albertdb** [comment]
Discovered the root cause of the problem. Opening a new issue and closing this one.

**Comment by switchboardOp** [comment]
@albertdb What was the cause and did you ever resolve your issue? I'm wondering the same thing.

**Comment by pierre-emmanuelJ** [comment]
same @albertdb

**Comment by bennysp** [comment]
+1 @albertdb

**Comment by bennysp** [comment]
For the record, I __think__ [this ](https://github.com/rancher/os/issues/2415) is what @albertdb is referring to for the "new issue", but I am not following how this resolves my new ticket here: https://github.com/rancher/os/issues/3057

I am probably missing the something...
