### ISSUE TITLE
Kernel Too old

### ISSUE THREAD

**Issue by itstamil** [rancher/os#2414]
I'm trying to build the rancher os from source on a ubuntu machine as my base 
the steps followed are 
1) cloned the master version on [github](www.github.com/rancher/os) 
2) simply run make 
3) the output is like kernel too old

OMG its always showing me like that

**Comment by niusmallnan** [comment]
You should upgrade your kernel, the version must be at least https://github.com/rancher/os/blob/master/Dockerfile.dapper#L67

**Comment by itstamil** [comment]
thanks for reply
i have attend that change in my Dockerfile.dapper but no improvement in the error
it's always on Kernel too old

**Comment by superseb** [comment]
The file shouldn't be changed, your kernel should be upgraded. Please share output of the following commands on the host you are running `make`:

- `uname -r`
- `docker info`

**Comment by itstamil** [comment]
**uname -r** result shows like this

4.13.0-45-generic

**docker info** result show like this


Containers: 4
 Running: 1
 Paused: 0
 Stopped: 3
Images: 184
Server Version: 18.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.13.0-45-generic
Operating System: Ubuntu 16.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.7GiB
Name: infyn
ID: IYGI:DDKI:W5SY:NMQI:M75I:BGC4:Q2NU:KBV5:NWUY:MY7V:33D5:32T4
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

**Comment by superseb** [comment]
The mentioned link (https://github.com/rancher/os/blob/master/Dockerfile.dapper#L67) shows:

`ARG KERNEL_VERSION_amd64=4.14.32-rancher3`

That means you will need to have kerne `4.14.32` or higher to compile the kernel, you are on `4.13.0`.

**Comment by itstamil** [comment]
I thought that the **kernel version for the Os** which i going to get on the **build**, I  hope i'm struggling with this part let be check on it

**Comment by niusmallnan** [comment]
@itstamil When we layout the kernel(`KERNEL_VERSION_amd64`), we need to run some commands like `depmod`. If your host kernel version is too old, it will not execute successfully.

**Comment by itstamil** [comment]
Thanks for your help , and the error is in kernel version 
i have obtained an **iso on the build** , while **booting** that iso into the **Vm**  
It shows like **kernel offset disabled** 
even i wound found what is the problem
sugess me what is the error cause

**Comment by itstamil** [comment]
![screenshot from 2018-07-20 17-05-06](https://user-images.githubusercontent.com/36615683/43000466-336e80be-8c3f-11e8-83da-28c5be27993a.png)

**Comment by itstamil** [comment]
I also think that would be an memory issue for that  i have assigned a memory of 3072(3GB) on that , I have faced that error which I was  posted
And even I apply the size on the the memory in the document 

This is the  major issue I have been facing in severel os obtained from various build

**Comment by niusmallnan** [comment]
Which platform did you use?

We have tested our latest release on AWS/ESXi(6.7)/Virtualbox.

**Comment by itstamil** [comment]
Platform used by me is virtualbox

**Comment by itstamil** [comment]
any update available for me??

**Comment by niusmallnan** [comment]
I didn't reproduce it on my setup:
```
MacOS High Sierra
VirtualBox 5.2.6
```
