### ISSUE TITLE
Cloud-config files are not merged but overwritten

### ISSUE THREAD

**Issue by albertdb** [rancher/os#2415]
**RancherOS Version: 1.3.0**
**Where are you running RancherOS? openstack**

According to https://rancher.com/docs/os/v1.x/en/installation/boot-process/cloud-init/#configuration-load-order
the different cloud-config files are overwritten and extended by the subsequent one. This suggests that the cloud-config files are merged when possible, but it is not the case.

As an example, `write_files` directive could be merged when `/var/lib/rancher/conf/cloud-config.d/boot.yml` and `/var/lib/rancher/conf/cloud-config.yml` contain different entries (for different files), but the later replaces everything.

This issue has driven me crazy for the last few days.

Could you please make the merging function a bit smarter?

Thank you very much.

**Comment by niusmallnan** [comment]
Hi @albertdb ,
Could you show me an example so that I can reproduce and debug?

**Comment by albertdb** [comment]
It's easy to reproce:

1. `ros config merge` a cloud-config that `write_files` something to path `/home/rancher/a`
2. Take an snapshot.
3. Boot an instance from that snapshot with a cloud-config that `write_files` something to path `/home/rancher/b` (note that both paths are different, no conflict is expected).
4. You will see that `/home/rancher/b` doesn't exist.

Issue #2420 is different. I tried the scripted cloud-config as a way to circumvent the present issue.

**Comment by niusmallnan** [comment]
Usually, the merge operation is mainly for two data types: map and slice.
`merge map` should be easy, we just need to replace the value if the key exists.
But `merge slice` is different,  we need to choose between `replace` and `append`.  Unfortunately, we chose the `replace`. If we chose the `append`, to solve the problem of data duplication can be very complicated.

The `write_files` config item is a slice, so you will see this behavior. 
Also, you can check these test code: https://github.com/rancher/os/blob/v1.4.x/util/util_test.go#L67-L92

I will try to explain it in the documentation, but there will be no code updates.

**Comment by albertdb** [comment]
I see. I think the data duplication is not a problem in this case. Why? There is a unique ID in this case: the file path. If the path is the same, then replace, else append.

**Comment by niusmallnan** [comment]
If we only fix something for `write_files`, it should be easy, because we can know the data structure of write_file in advance.

But it is difficult to identify when the program is running, especially taking into account all the configuration items. 
https://github.com/rancher/os/blob/v1.4.x/util/util.go#L118-L140

**Comment by albertdb** [comment]
I see the big picture. Then, solving #2420 is a must, apart from documenting this. Writing files is the simplest use case, but there are other configs that the present issue may affect and at least the scripting way of doing things should work.

Thank you.
