### ISSUE TITLE
docker issue

### ISSUE THREAD

**Issue by itstamil** [rancher/os#2417]
why docker command is not working on Version 1.4.0.
but it is working on 1.3.0

**Comment by niusmallnan** [comment]
Similar issue https://github.com/rancher/os/issues/2378 ?

**Comment by itstamil** [comment]
sorry @niusmallnan  I think the error was different 
the error i was faced , **cannot connect to docker deamon at unix:///var/run/docker.sock**
is docker daemon is running?
