### ISSUE TITLE
Scripted user-data is not saved (although logs say otherwise) nor executed

### ISSUE THREAD

**Issue by albertdb** [rancher/os#2420]
**RancherOS Version: 1.3.0**

**Where are you running RancherOS? openstack**

Steps to reproduce:

1. Launch instance with a shell script as user-data (containing apart from shebang `echo whatever > /home/rancher/expectedFile`). Check Configuration drive (required for OpenStack).
2. SSH instance.
3. Check `/home/rancher/expectedFile`. Doesn't exist.
4. Review `/var/log/boot/cloud-init-save.log`. Will contain line `Writing to /var/lib/rancher/conf/cloud-config-script`.
5. Check `/var/lib/rancher/conf/cloud-config-script`. Doesn't exist.

This in combination with #2415 makes the issue impossible to circumvent.

**Comment by niusmallnan** [comment]
This is indeed a bug, hidden for so long.

**Comment by rootwuj** [comment]
Tested with RancherOS version- v1.4.1-rc2 with AWS.
This version of user data has been written and `/var/lib/rancher/conf/cloud-config-script` exists.

**Comment by niusmallnan** [comment]
Backported to v1.4.1.
