### ISSUE TITLE
failed to configure docker-sys bridge via cloud-init

### ISSUE THREAD

**Issue by benok** [rancher/os#2422]
**RancherOS Version: (ros os version)**  v1.4.0
**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**  VMware esxi 6

Hi, 
When I upgraded from v1.3.0 to v1.4.0, docker-sys & br-* interface's network addresses are in conflict.
```
rancher@ros1*:~:-) ip r
default via 192.168.101.254 dev eth0
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 linkdown
172.18.0.0/16 dev docker-sys proto kernel scope link src 172.18.42.1 linkdown
172.18.0.0/16 dev br-d214f2215687 proto kernel scope link src 172.18.0.1 linkdown
172.21.0.0/16 dev eth2 proto kernel scope link src 172.21.0.33
192.168.16.0/24 dev eth1 proto kernel scope link src 192.168.16.91
192.168.101.0/24 dev eth0 proto kernel scope link src 192.168.101.91
```
I searched workaround and found https://github.com/rancher/os/issues/1870 .

So, I reverted to the snapshot before upgrade and tried upgrade again with the command below.
```
sudo ros os upgrade --append 'rancher.system_docker.subnet=172.22.42.1/16'
```
But network address didn't change after reboot.
I checked config with 'sudo ros config export' and found the correct config below.
```
rancher:
  system_docker:
    subnet: 172.22.42.1/16
``` 
 But, bridge config is not changed.
```
rancher@ros1*:~:-) cat /etc/docker/cni/bridge.d/bridge.conf 
{
    "name": "bridge",
    "type": "bridge",
    "bridge": "docker-sys",
    "isDefaultGateway": true,
    "ipMasq": true,
    "hairpinMode": true,
    "ipam": {
        "type": "host-local",
        "subnet": "172.18.42.1/16"
    }
}
```
Next , I followed workaround  https://github.com/rancher/os/issues/1870#issuecomment-356492220 . 
I edit /etc/docker/cni/bridge.d/bridge.conf & reboot -f.
```
-       "subnet": "172.18.42.1/16"
+       "subnet": "172.22.42.1/16"
```

but network config is still not changed. (the same as first one).
```
rancher@ros1*:~:-) ip r
default via 192.168.101.254 dev eth0
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 linkdown
172.18.0.0/16 dev docker-sys proto kernel scope link src 172.18.42.1 linkdown
172.18.0.0/16 dev br-d214f2215687 proto kernel scope link src 172.18.0.1 linkdown
172.21.0.0/16 dev eth2 proto kernel scope link src 172.21.0.33
192.168.16.0/24 dev eth1 proto kernel scope link src 192.168.16.91
192.168.101.0/24 dev eth0 proto kernel scope link src 192.168.101.91
```
How can I solve address conflict ?

**Comment by niusmallnan** [comment]
@benok 
#1870 can only work on 1.2
Before v1.2, we used CNI to configure docker-sys. 
In v1.3, we removed docker-sys and let system-docker use only the host network, 
but some users want to be able to keep the bridge network for system-docker. 

So we re-introduced docker-sys on 1.4, but we removed the CNI style and use the docker args style.
Check this issue: https://github.com/rancher/os/issues/2329

**Comment by niusmallnan** [comment]
Can you try `ros config set rancher.system_docker.bip 172.22.42.1/16`

**Comment by benok** [comment]
Thank you for all your comment.
I understand that. 

I reverted to v1.3.0 again, and tried ``` sudo ros os upgrade --append 'rancher.system_docker.bip=172.22.42.1/16' ``` and it works :-)
```
rancher@ros1*:~:-) ip r
default via 192.168.101.254 dev eth0
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 linkdown
172.18.0.0/16 dev br-d214f2215687 proto kernel scope link src 172.18.0.1 linkdown
172.21.0.0/16 dev eth2 proto kernel scope link src 172.21.0.33
172.22.0.0/16 dev docker-sys proto kernel scope link src 172.22.42.1 linkdown
192.168.16.0/24 dev eth1 proto kernel scope link src 192.168.16.91
192.168.101.0/24 dev eth0 proto kernel scope link src 192.168.101.91
```
I'll add comment to https://github.com/rancher/os/issues/1870 for someone like me.

**Comment by kucerarichard** [comment]
Can you spell out the "docker args style"?    What is it exactly?

**Comment by niusmallnan** [comment]
@kucerarichard 
Docker can control docker0 bridge by `bip`.
https://docs.docker.com/v17.09/engine/userguide/networking/default_network/custom-docker0/

Earlier we used CNI to create the docker-sys bridge. Later we upgraded system-docker and used docker's native bip arg to control docker-sys cidr.
