### ISSUE TITLE
can't find kernel source on Ros

### ISSUE THREAD

**Issue by Tamil18** [rancher/os#2431]
I was running with rancher os version 1.4 on that i have switched to the **Ubuntu console** 
on that i have been trying to build some kernel module but it shows there is no **kernel source**
available on the path **/usr/src/.** 

for that i have searched and get a solution like we can install is by manual using apt-get install linux-headers-v4.14.x
but i won't find the file for **4.14.32-rancher2**
Can you provide the headers alone??

**Comment by niusmallnan** [comment]
Please try this: https://rancher.com/docs/os/v1.x/en/installation/configuration/kernel-modules-kernel-headers/

**Comment by Tamil18** [comment]
i have did that and there is no files in path of /usr/src ??

**Comment by niusmallnan** [comment]
Another kernel header location is: `/lib/modules/${KERNEL_VERSION}/build`.
Different distributions have their own choices, but they all meet the standards.
