### ISSUE TITLE
I/O Timeout when chaning Docker version in cloud-config on OpenStack

### ISSUE THREAD

**Issue by stieler-it** [rancher/os#2434]
**RancherOS Version: 1.4.0**

**Where are you running RancherOS? Rancher 2 -> docker-machine -> OpenStack**

I want RancherOS to start with a Docker version supported by Rancher 2. When I reference the following cloud-config file in my node template:

```
#cloud-config
rancher:
  docker:
    engine: docker-17.03.2-ce
```

I can see the following error during machine boot:

```
[            ] ros-sysinit:info: [13/18] [network]: Started 
[            ] ros-sysinit:error: Get https://raw.githubusercontent.com/rancher/os-services/v1.4.0/d/docker-17.03.2-ce.yml: dial tcp 151.101.0.133:443: i/o timeout
[            ] ros-sysinit:error: Failed to load rancher.docker.engine=(docker-17.03.2-ce): Get https://raw.githubusercontent.com/rancher/os-services/v1.4.0/d/docker-17.03.2-ce.yml: dial tcp 151.101.0.133:443: i/o timeout
```

When I SSH connect to the machine `wget https://raw.githubusercontent.com/rancher/os-services/v1.4.0/d/docker-17.03.2-ce.yml` works. Maybe the network is not fully initialized at that time?

The following workaround however

```
#cloud-config
write_files:
  - path: /etc/rc.local
    permissions: "0755"
    owner: root
    content: |
      #!/bin/bash
	  sudo ros engine switch docker-17.03.2-ce

```

changes the version successfully:

```
[rancher@devops-master1 ~]$ docker version
Client:
 Version:      17.03.2-ce

```

**Comment by niusmallnan** [comment]
You can try `--engine-install-url`:

```
docker-machine -d xxx create \
    --engine-install-url=https://releases.rancher.com/install-docker/17.03.sh
    ...
```

The docker-machine can switch the use-docker version:
https://github.com/docker/machine/blob/master/libmachine/provision/rancheros.go#L121

**Comment by stieler-it** [comment]
I am deploying the Kubernetes cluster using Rancher 2 with RKE - is it possible to set docker-machine parameters there?

**Comment by niusmallnan** [comment]
Of course, you can. In fact, Rancher2 has built-in docker-machine.

You can edit the `Node Templates`, check the `Engine Options`.
In fact, we have made the default setting for `Engine Install URL`.

**Comment by stieler-it** [comment]
Hi @niusmallnan,

I would assume that "Engine Options" refers to the Docker Engine, not Docker Machine - at least the example says `log-driver=...`. Also, the install URL is already set to `https://releases.rancher.com/install-docker/17.03.sh` but my created node had engine version 18.

**Comment by niusmallnan** [comment]
I don't have a OpenStack setup, so I tried the similar steps on AWS, the docker version can switch right.
Although AWS and OpenStack are definitely different, they are all through docker-machine in this case.

I doubt that your OpenStack vm cannot download the 17.03.2 image, It has been waiting for the download, so there is no switch action.

**Comment by stieler-it** [comment]
Yes, apparently the download fails for some reason and works when I try it manually. Maybe it's an issue with OpenStack or my OpenStack provider. Anything I could try? Otherwise we could maybe add a note to the documentation that cloud-init will not work in some cases...

**Comment by niusmallnan** [comment]
Similar with https://github.com/rancher/rancher/issues/15019 ？

**Comment by stieler-it** [comment]
It appears that even my workaround does not work every time. Many times it fails with "`NodeController c-6jtnm/m-w8cwz [node-controller] failed with : Error creating machine: Error running provisioning: error selecting docker: (ssh command error:`" in Rancher server logs.

**Comment by niusmallnan** [comment]
Could you clean your cloud-config? Such as the following:
```
#cloud-config
rancher:
  docker:
    engine: docker-17.03.2-ce
```

Let docker-machine built into Rancher2.0 help you switch to docker version.

**Comment by stieler-it** [comment]
@niusmallnan I don't understand why you are recommending me to try the exact cloud config that I have reported not to work and that was also the reason to open this ticket. Can you elaborate?

**Comment by niusmallnan** [comment]
The built-in docker-machine in Rancher2.0 does the same thing with your cloud-config.
They are both switching the docker version.

If you follow rancher/rancher#15019, you will find that setting both at the same time actually has a bug.
So I suggest you remove cloud-config and let docker-machine complete the switch task.

**Comment by stieler-it** [comment]
Ok, so you say no cloud-config at all. Now I understand, I'll try that and get back to you.

**Comment by stieler-it** [comment]
Hi, yes it works without cloud-config - node comes up with the correct Docker version. I don't remember why I saw the need to define it in the first place - should I remember again I will open another (documentation) issue. Thanks for your support!
