### ISSUE TITLE
RancherOS v1.4.0 docker version discrepancy

### ISSUE THREAD

**Issue by jeffplesko** [rancher/os#2441]
**RancherOS Version: (ros os version)**
v1.4.0
**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
AWS:us-east-2:ami-504b7435
--
You documentation states the the docker version on this ami should be 18.03.01-ce but after spinning up my instances I find:

[rancher@ml-dev2 ~]$ docker --version
Docker version 17.03.2-ce, build f5ec1e2

Problem:  This docker version defaults to the v1 api.  Without having to login to each and every node to upgrade the docker version, I cannot access our normal repos via v2 api as they are all defined.  Given this is the latest image I find, I do not see any version which supports v2 api.

Please advise and/or assist

-Jeff

**Comment by niusmallnan** [comment]
@jeffplesko I cannot reproduce.
```
[root@ip-172-31-46-192 rancher]# ros -v
version v1.4.0 from os image rancher/os:v1.4.0
[root@ip-172-31-46-192 rancher]# docker -v
Docker version 18.03.1-ce, build 9ee9f40

[root@ip-172-31-46-192 rancher]# wget -q -O - http://169.254.169.254/latest/meta-data/ami-id
ami-504b7435
```

How did you boot your instance? That should be the key.

**Comment by niusmallnan** [comment]
Please check your `Node Template`, I think the `Engine Install URL` made a choice for you.

**Comment by jeffplesko** [comment]
You are correct, Thank you.  The node template appears to have defaulted to 17.02, or I accidentally changed it.

**Comment by niusmallnan** [comment]
The default is 17.03, because of restrictions k8s.
