### ISSUE TITLE
how to use udevadm in rancherOS

### ISSUE THREAD

**Issue by buaapengbo** [rancher/os#2448]
**RancherOS Version: (ros os version)**
v1.3.0

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
In real machine myself

Question:
I want to use : 
 `sudo udevadm info --attribute-walk --name=/dev/video0`
to get the KENERLS of the usb port.

later want to use :
`echo  'KERNELS=="xxxxxxx",  MODE:="0666", GROUP:="dialout",  SYMLINK+="usb_camera_0"' >/etc/udev/rules.d/usb_camera.rules`
to make a static usb camera port.

Issue:
```
rancher@rancher:~$ sudo udevadm info --attribute-walk --name=/dev/video0
sudo: udevadm: command not found
rancher@rancher:~$ sudo su
root@rancher:/home/rancher# udevadm info --attribute-walk --name=/dev/video0
bash: udevadm: command not found
```

I am in ubuntu console, any advise?

**Comment by niusmallnan** [comment]
We run `udevd` in a container called `udev`:
```
$ system-docker ps | grep udev
9ecb232a705d        rancher/os-base:v1.4.0             "/usr/bin/ros entr..."   2 days ago          Up 7 minutes                            udev

$ system-docker exec -it udev bash
root@ip-172-31-12-172:/etc/udev# system-docker exec -it udev bash
bash-4.4# udev
udevadm  udevd
```

If you want to change the udev rules, you can also try it in `udev` container.

**Comment by buaapengbo** [comment]
Hi niusmallnan,
thanks for your help, it works.

`sudo system-docker exec -it udev bash
udevadm info --attribute-walk --name=/dev/video0

vi /etc/udev/rules.d/usb.rules

KERNEL=="video*",SUBSYSTEM=="video4linux",KERNELS=="1-3:1.0",SUBSYSTEMS=="usb",DRIVERS=="uvcvideo",SYMLINK+="Camera1"

CTRL+D

sudo system-docker restart udev # unplug camera before this step

# plugin camera
ls -l /dev/Camera*`
