### ISSUE TITLE
console switch unresponsive

### ISSUE THREAD

**Issue by czangerle** [rancher/os#2449]
**RancherOS Version: (ros os version 1.4.0)**

**Where are you running RancherOS? (esxi 5.5.0 host)**

Summary:
When configuring rancheros through a cloud-config-file which states to use ubuntu as console, the system still uses the default console with no way to change it.

When using "sudo ros console switch ubuntu" the yes/no prompt appears but nothing happens.

I've deployed rancheros a few times now, the issue only occures sometimes.

Here's my cloud-config.yml

#cloud-config
EXTRA_CMDLINE: /init
rancher:
  console: ubuntu
  environment:
    EXTRA_CMDLINE: /init
  hostname: cz-worker-prodnet
  network:
    dns:
      nameservers:
      - 10.17.6.120
    interfaces:
      eth0:
        address: 10.17.36.100/24
        dhcp: false
        gateway: 10.17.36.1
        mtu: 1500
      eth1:
        dhcp: true
        mtu: 1500

Seems to be an issue close to https://github.com/rancher/os/issues/2273

Unfortunatelly multiple restarts and

**Comment by niusmallnan** [comment]
How did you boot your VM? docker-machine or booting from ISO?
1. docker-machine
   https://rancher.com/docs/os/v1.x/en/installation/running-rancheros/workstation/docker-machine/#using-docker-machine-with-vmware-vsphere
2. boot from ISO
    You should make sure open-vm-tools is up before switching console.

I can't think of other key points for a while, I haven't been able to reproduce it.

**Comment by rootwuj** [comment]
@niusmallnan This is really a problem, I boot the VM using docker-machine, the cloud-config configuration did not take effect. But I can switch the console manually using `sudo ros console switch ubuntu`.

**Comment by rootwuj** [comment]
I haven't been able to reproduce it. Maybe you can check the start command.
