### ISSUE TITLE
`ros service list` failed to work.

### ISSUE THREAD

**Issue by Magicloud** [rancher/os#2450]
**RancherOS Version: (ros os version)** "1.4.0"

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)** "Virtualbox"

When I issue `sudo ros service list`, it showed:
```
ERRO[0001] Failed to load https://raw.githubusercontent.com/rancher/os-services/v1.4.0/index.yml: non-200 http response: 502
```

**Comment by niusmallnan** [comment]
It seems that your network is not very good.

**Comment by Magicloud** [comment]
@niusmallnan Ah, yes. It works now. Thanks.
