### ISSUE TITLE
OpenCL in rancherOS with Intel GPU

### ISSUE THREAD

**Issue by buaapengbo** [rancher/os#2451]
**RancherOS Version: (ros os version)**
v1.4.0

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
In real machine myself

Question:
I want to run OpenCL in RancherOS with intel GPU.
CPU is `i5-6350HQ` , GPU is `Intel® Iris™ Pro Graphics 580`

I am in ubuntu console, I install clinfo with: `sudo apt-get install clinfo`
I install intel gpu driver with `sudo dpkg -i intel-opencl_2018ww15-010713_amd64.deb`

But I can't get device using clinfo as below:
```
rancher@rancher:~$ clinfo
Number of platforms                               0
```

Actually, I want to try Intel OpenVINO in RancherOS, the error logs:
`[ ERROR ] failed to create engine: clGetPlatformIDs error -1001`

Any help will be appreciated! 👍

**Comment by niusmallnan** [comment]
Where can we reproduce this question, I mean which public cloud can support?
We may not have this Intel GPU.

**Comment by buaapengbo** [comment]
Hi Niusmallnan,

I know what you mean, but I am in real hardware machine.
I don't know how to reproduce this question, maybe in real hardware machine can do this, cause intel CPU always along with graphic gpu.

Thanks,
Bo
