### ISSUE TITLE
issue with state partition format/partitioning

### ISSUE THREAD

**Issue by kmkramer** [rancher/os#2459]
**RancherOS Version: (ros os version)**
1.4.0 release

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
baremetal

I'm trying to figure out the syntax to force a re-partition/reformat. I've tried various combinations without success and also trying some cloud-init commands outside of rancher scoped yaml. disk_setup/fs_setup etc.

https://rancher.com/docs/os/v1.x/en/installation/storage/state-partition/

I've got this appended to my ipxe kernel line
rancher.state.formatzero=true rancher.state.autoformat=[/dev/sda]

I'm missing something obvious here but I don't know what. Thanks

my cloud-init.yaml
```#cloud-config
rancher:
  state:
    dev: /dev/sda1
    fstype: ext4
    autoformat:
    - /dev/sda

**Comment by kmkramer** [comment]
I've also forcibly removed the partition information on the nodes that I'm trying this on and can't get the install to touch the disks at all.

**Comment by Jason-ZW** [comment]
@kmkramer Maybe you can try these commands:
Way 1: configure `cloud-config.yml` like this then execute command `ros install`
```
rancher:
  state:
     fstype: auto
     autoformat:
        - /dev/sda

$ sudo ros install -c cloud-config.yaml -d /dev/sda
```
Way 2: configure ipxe kernel line like this:
```
$ rancher.state.autoformat=[/dev/sda] rancher.state.dev=LABEL=RANCHER_STATE 
```

**Comment by kmkramer** [comment]
Way 1 works, but defeats BM provisioning aspect.

Way 2 has no effect on the install.

**Comment by niusmallnan** [comment]
I think you probably missed the `rancher.state.dev=LABEL=RANCHER_STATE`.

Close this.
