### ISSUE TITLE
Support new T3 instances and EBS NVMe block devices 

### ISSUE THREAD

**Issue by niranjan94** [rancher/os#2461]
**RancherOS Version:** `v1.4.0`

**Where are you running RancherOS?** `AWS`

---

Currently, In `C5, C5d, i3.metal, M5, M5d, R5, R5d, T3, and z1d` instances, EBS volumes are exposed as NVMe block devices. The device names are `/dev/nvme0n1`, `/dev/nvme1n1`, and so on.

Ref: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/nvme-ebs-volumes.html 

But the current Official Rancher AMI image does not recognize this correctly when deploying on one of these instance, Say `T3`. As it still looks for and uses the previous block names (`/dev/xvda` and so on) and the [`rancher.resize_device`](https://rancher.com/docs/os/v1.2/en/configuration/resizing-device-partition/) is also set as `/dev/xvda` whereas it should be set as `/dev/nvme0n1`

**Comment by Jason-ZW** [comment]
similar #2381 ？

**Comment by niusmallnan** [comment]
@Jason-ZW No, this is another issue.

@niranjan94 We have supported this feature. It only worked on m5 and c5. Now AWS supports more instance types, so we need to add them.
https://github.com/rancher/os/blob/master/config/cloudinit/datasource/metadata/ec2/metadata.go#L146-L149
https://github.com/rancher/os/blob/master/cmd/cloudinitexecute/cloudinitexecute.go#L197-L199

**Comment by kingsd041** [comment]
Fixed in ros v1.4.2-rc1
```
# ros -v
version v1.4.2-rc1 from os image rancher/os:v1.4.2-rc1
```
```
# ros c export
rancher:
resize_device: /dev/nvme0n1
```
```
# fdisk -l
Device         Boot Start      End  Sectors Size Id Type
/dev/nvme0n1p1 *    16065 62914526 62898462  30G 83 Linux
```

**Comment by kingsd041** [comment]
Sorry, I only tested the T3 instance and omitted other types of instances.

**Comment by kingsd041** [comment]
I tested the `C5, C5d, i3.metal, M5, M5d, R5, R5d, T3, and z1d` instances, the block device changed to "/dev/nvme0n1" and supported `resize_device`

**Comment by niusmallnan** [comment]
backported to v1.4.2
