### ISSUE TITLE
Release VMDK images for VMware

### ISSUE THREAD

**Issue by janeczku** [rancher/os#2468]
**RancherOS Version: (ros os version)**
v.1.4.0

It's difficult to deploy RancherOS to vSphere infrastructure:
- The vmware-iso can't be used to create a golden master since it autoformats the local disk as state partition on boot.
- The regular ISO does not include open-vm-tools

To make this easier we should release VMDK images and optionally OVA bundles for VMware.

**Comment by Jason-ZW** [comment]
@janeczku 
I think you can try this command to build the `rancheros-vmware.iso`, the iso will include `open-vm-tools` and no autoformats the local disk as state partition on boot.

`VMWARE_AUTOFORMAT=0 make vmware`

**Comment by niusmallnan** [comment]
@olljanat Yes, the `rancher-vmware.iso` is used for docker-machine. It will autoformat the root disk, docker-machine mechanism made me have to do this.

We will release all stuff for vmware, it will include initrd, rancheros-vmware-noformat.iso, and so on.

**Comment by rootwuj** [comment]
Version - rancher/os:v1.5.0-rc1 11/27
Verified fixed
