### ISSUE TITLE
Ceph Client on rancheros

### ISSUE THREAD

**Issue by rdissauer** [rancher/os#2476]
**RancherOS Version: (ros os version)**
v1.4.0

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
Proxmox 5.2 with CEPH Storage

Is there a way to get ceph-client package up and running on latest rancheros? I've seen that required kernel modules for rbd are already present.

**Comment by niusmallnan** [comment]
Can you try to switch the ubuntu console?

**Comment by rdissauer** [comment]
changed to ubuntu console, still no luck!
The question is if there need to be a ceph client installed on the k8s hosts running rke to get ceph rbd up and running.
I have same problem as [this](https://github.com/rancher/rancher/issues/10388) issue here but I'm not able to mount /lib/modules in rancher 2.0.7! Don't even know if this is still needed in rancher v2

**Comment by rdissauer** [comment]
seems that is a rancher/kubernetes issue that the rbd storage class is not working properly.
When I deploy an ubuntu container, install ceph-common package and try to mount a rbd block device inside the container everything works fine.
