### ISSUE TITLE
build arm64 custom iso failed

### ISSUE THREAD

**Issue by xin3liang** [rancher/os#2480]
Hello, we would like to build arm64 custom iso with our own kernel.
we run make under os repository source code dir on an arm64 server, but it failed with bellow msg.
Then we notice we should build the custom kernel first. We move to os-kernel repository and found that it just only support building x86 kernel not arm64.
How to do then if we want to build arm64 custom iso with our own kernel?

++ tr '[:upper:]' '[:lower:]'
+ ISO=/go/src/github.com/rancher/os/dist/artifacts/rancheros.iso
+ CHECKSUM=iso-checksums.txt
+ mkdir -p /cd/boot/isolinux
+ mkdir -p /cd/rancheros
+ [[ arm64 != \a\m\d\6\4 ]]
+ echo 'Skipping package-iso due to ARM/ARM64 build: /go/src/github.com/rancher/os/dist/artifacts/vmlinuz-4.14.65-rancher  or /go/src/github.com/rancher/os/dist/artifacts/initrd-29f46a3-dirty not found'
Skipping package-iso due to ARM/ARM64 build: /go/src/github.com/rancher/os/dist/artifacts/vmlinuz-4.14.65-rancher  or /go/src/github.com/rancher/os/dist/artifacts/initrd-29f46a3-dirty not found
+ exit 0
INFO[0221] docker cp /go/src/github.com/rancher/os/bin . 
INFO[0221] docker cp /go/src/github.com/rancher/os/dist . 
INFO[0222] docker cp /go/src/github.com/rancher/os/build/initrd build 
INFO[0223] docker cp /go/src/github.com/rancher/os/build/kernel build 
Error response from daemon: lstat /var/lib/docker/overlay2/48bf07a71a4f9df69766b52273f04ab1d0bf7bf42a50a11ec969bbe1881b3a80/merged/go/src/github.com/rancher/os/build/kernel: no such file or directory

**Comment by xin3liang** [comment]
Oh :-(, got it. thanks for reply.

**Comment by niusmallnan** [comment]
Close this, please track #2302
