### ISSUE TITLE
looking for multiple kernel support

### ISSUE THREAD

**Issue by aemneina** [rancher/os#2481]
**RancherOS Version: (ros os version)**
1.4.0

Can you please create/provide two versions of RancherOS - 2 kernels: 4.17.11 and 4.18.8

**Comment by niusmallnan** [comment]
These two kernels have been shipped. I did some tests on AWS and they look good.

Please build ros with these kernels, and test them out. ping @kingsd041 @rootwuj 
```
https://github.com/rancher/os-kernel/releases/tag/v4.17.11-rancher
https://github.com/rancher/os-kernel/releases/tag/v4.18.8-rancher
```

**Comment by brod55** [comment]
@niusmallnan thank you for building these kernels.  Is there a way to build these kernels with specific modules turned on and off.  Can I give you config file and you guys maintain it?  Or is best we maintain a specific kernel?

**Comment by niusmallnan** [comment]
@brod55 

https://github.com/rancher/os-kernel/blob/v4.17.x/config/kernel-config
https://github.com/rancher/os-kernel/blob/v4.18.x/config/kernel-config

This doc may be helpful.
