### ISSUE TITLE
DNS lookup failures when using 1.4.1

### ISSUE THREAD

**Issue by advancingu** [rancher/os#2486]
**RancherOS Version: (ros os version)**
1.4.1

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
AWS EC2

Running a K8 cluster version 1.11.2 with Rancher 2.0.8 and Rancher OS 1.4.1 leads to some processes being unable to resolve DNS entries for services whose deployments are located on another node.

With the exact same setup using Rancher OS 1.4.0, DNS resolution works fine.

We observed these lookup errors immediately after upgrading a node pool to 1.4.1, where processes on these nodes then could no longer look up services on other nodes running 1.4.0. We then upgraded every pool to 1.4.1 but the problem remained. We also set up a cluster from scratch with only 1.4.1 and the problem remained. Only when creating a cluster running 1.4.0 exclusively, DNS resolution was successful again.

**Comment by niusmallnan** [comment]
Hi, @advancingu 
I did not reproduce this issue in v1.4.1, not sure if I missed any key information:
```
Platform: AWS EC2
Rancher: 2.0.8
RancherOS: v1.4.1(one master, one worker)
Kubernetes: v1.11.2-rancher1-1
Network Plugin: Flannel
Docker: v17.03.2
```

I created two workloads which include two services(should not be "clusterIP none"), and make sure that two PODs are not on the same node. I tried nslookup, it can work fine.
```
> kubectl get pod -o=custom-columns=NAME:.metadata.name,STATUS:.status.phase,NODE:.spec.nodeName
NAME                    STATUS    NODE
app1-7bbfb79f4b-nhhvx   Running   ip-172-31-30-15
app2-5856c749c8-qqhvw   Running   ip-172-31-30-33

# try nslookup in the app1 container
root@app1-7bbfb79f4b-nhhvx:/# nslookup app2
Server:         10.43.0.10
Address:        10.43.0.10#53

Name:   app2.default.svc.cluster.local
Address: 10.43.20.144
```

**Comment by advancingu** [comment]
@niusmallnan Just checked on the network plugin and it is `Canal`, not `Flannel` (we used the default suggested by Rancher). Docker is shown as `17.3.2`, not `17.03.2`. The other info is correct.

In our setup we had three pools. One with `AWS EC2 eu-central-1 c5.large`, one with `AWS EC2 eu-central-1 m5.large`, one with `AWS EC2 eu-central-1 t2.small`. We double-checked they were all in the same VPC. All were also part of the security group created and maintained by Rancher.

The t2 contains a single instance running etcd and control plane. For testing purposes, the other two pools each had one node each. Processes on the c5 node could then not resolve services where deployments were on the m5 node.

**Comment by kingsd041** [comment]
@advancingu
I did not reproduce the issue using the `Canal` network. I even used the same instance template and Availability Zone as you.

I am curious about two things:
1. Why is your docker version `17.3.2` instead of `17.03.2`, the default docker version should be `17.03.2`, I am not sure if it has any effect.
2. What custom configuration did you do when you added `Node Templates`?

**Comment by advancingu** [comment]
@kingsd041 1. Our Docker version is shown as `17.3.2` in Rancher's cluster node overview (i.e. `/c/.../nodes`):
![image](https://user-images.githubusercontent.com/130207/46656134-a1da0200-cbad-11e8-8aae-1bc2e4710827.png)
Perhaps this is a Rancher UI bug.

2. We did not perform any custom configuration. This is what a typical node configuration looks like for us:
```
{

    "amazonec2Config": {
        "accessKey": "xxxxxx",
        "ami": "ami-1686b3fd",
        "blockDurationMinutes": "0",
        "deviceName": "/dev/sda1",
        "endpoint": "",
        "iamInstanceProfile": "rancher",
        "insecureTransport": false,
        "instanceType": "t2.small",
        "keypairName": "",
        "monitoring": false,
        "privateAddressOnly": false,
        "region": "eu-central-1",
        "requestSpotInstance": false,
        "retries": "5",
        "rootSize": "16",
        "securityGroup": [
            "rancher-nodes"
        ],
        "sessionToken": "",
        "spotPrice": "0.50",
        "sshKeypath": "",
        "sshUser": "rancher",
        "subnetId": "",
        "tags": "",
        "useEbsOptimizedInstance": false,
        "usePrivateAddress": false,
        "userdata": "",
        "volumeType": "gp2",
        "vpcId": "vpc-xxxxxx",
        "zone": "a"
    },
    "annotations": { },
    "baseType": "nodeTemplate",
    "created": "2018-06-06T09:07:59Z",
    "createdTS": 1528276079000,
    "creatorId": "user-xxxxxx",
    "driver": "amazonec2",
    "engineEnv": { },
    "engineInstallURL": "https://releases.rancher.com/install-docker/17.03.sh",
    "engineLabel": { },
    "engineOpt": { },
    "id": "user-xxxxxx:nt-xxxxxx",
    "labels": { },
    "links": {
        "nodePools": "…/v3/nodePools?nodeTemplateId=user-xxxxxx%3Ant-xxxxxx",
        "nodes": "…/v3/nodes?nodeTemplateId=user-xxxxxx%3Ant-xxxxxx",
        "remove": "…/v3/nodeTemplates/user-xxxxxx:nt-xxxxxx",
        "self": "…/v3/nodeTemplates/user-xxxxxx:nt-xxxxxx",
        "update": "…/v3/nodeTemplates/user-xxxxxx:nt-xxxxxx"
    },
    "name": "AWS EC2 eu-central-1 t2.small RancherOS 1.4.0",
    "removed": null,
    "state": "active",
    "transitioning": "no",
    "transitioningMessage": "",
    "type": "nodeTemplate",
    "useInternalIpAddress": true,
    "uuid": "xxxxxx"
}
```

**Comment by kingsd041** [comment]
@advancingu There may be a reason for the security group. Can you set the security group settings to allow all open and test again?

**Comment by kingsd041** [comment]
Close it.
@advancingu If you still have doubts, please reopen it and let me know.
