### ISSUE TITLE
VMware: cloud-init will re-run on every reboot after upgrading to 1.4.1

### ISSUE THREAD

**Issue by olljanat** [rancher/os#2487]
**RancherOS Version: (ros os version)**
v1.4.1

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
VMware

We have been using Terraform to create Rancher OS machines and specify install command [extra_config](https://www.terraform.io/docs/providers/vsphere/r/virtual_machine.html#extra_config) section like this:
```
extra_config {
guestinfo.cloud-init.config.data = <<EOD
#!/bin/bash
sudo ros install -d /dev/sda --no-reboot
sudo reboot
EOD
}
```
and it have  been working on way that new VMs boots once from ISO file, install to disk and reboot from hard disk after that.

But now if I do upgrade to version 1.4.1 Rancher OS will run that script again on every reboot which causes reboot loop.

Only workaround which I have been able to find is:
- Shutdown VM when it is still on 1.4.0 version.
- Clear **guestinfo.cloud-init.config.data** value (which is bad as it ruin whole idea of infrastructure as code)
- Start VM
- Do upgrade.

Probably caused by changes done on #2420

Related to issue #2468 

Any ideas how to avoid this?

**Comment by niusmallnan** [comment]
Try this rough code:
```
#!/bin/bash

if ! blkid | grep -q "RANCHER_STATE"; then
    sudo ros install -d /dev/sda --no-reboot
    sudo reboot
else
    echo "nothing to do..."
fi
```

**Comment by olljanat** [comment]
@niusmallnan that worked fine. Thanks :)
