### ISSUE TITLE
Boot coreos via ipxe but Image not be download 

### ISSUE THREAD

**Issue by lncan** [rancher/os#2499]
**RancherOS Version: (ros os version)**
1.4.1
**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
baremetal
Hello guys, I'm using rancher to deploy kubernetes on local machine. But when i boot rancheros via ipxe, the images not be download. it have errors **connection time out (http://ipxe.org/4c116835) **

I use the default ipxe scripts like rancher docs:
**#!ipxe
Boot a persistent RancherOS to RAM

Location of Kernel/Initrd images
set base-url http://releases.rancher.com/os/latest

kernel ${base-url}/vmlinuz rancher.state.dev=LABEL=RANCHER_STATE rancher.state.autoformat=[/dev/sda] 
initrd ${base-url}/initrd
boot
**
Does anyone have solution about this? Please let me know. Thank you.

**Comment by niusmallnan** [comment]
I can download these files, maybe you should check your networking.

Another way is that you can use your own nginx or apache to enable a service.

**Comment by lncan** [comment]
@niusmallnan i still don't get the images. Still old errors. Any solution, guy?

**Comment by kingsd041** [comment]
@niusmallnan @lncan 
In my environment, I can download the image.
![image](https://user-images.githubusercontent.com/19684717/46596672-f038c380-cb0f-11e8-9863-d01fd4e43ebb.png)

**Comment by lncan** [comment]
> @niusmallnan @lncan
> In my environment, I can download the image.
> ![image](https://user-images.githubusercontent.com/19684717/46596672-f038c380-cb0f-11e8-9863-d01fd4e43ebb.png)

Ok thank you. I fixed it by adding 'dhcp' line in file ipxe.
