### ISSUE TITLE
LVM devices not intialized on boot

### ISSUE THREAD

**Issue by alemsh** [rancher/os#2503]
**RancherOS Version: (v1.4.0)**

**Where are you running RancherOS? (bare-metal)**

I was planning on using LVM to provision some local disk volumes in k8, which I have working the way I'd like it to. There is one small catch though, that the volume group is not initialized during boot.

I.e. I have to run `vgchange -ay` after each boot and then mount the logical volumes.

Is there any way to ensure that the volume groups are initialized first so that way the devices can be mounted properly during boot? Do I need to add additional kernel parameter, or update the initramfs(not sure if that's exactly how it works for RancherOS)?

**Comment by niusmallnan** [comment]
Can you try `runcmd`? 
https://rancher.com/docs/os/v1.x/en/installation/configuration/running-commands/

**Comment by alemsh** [comment]
@niusmallnan Yes, I can get the volumes initialized now, so that's good.

I'm not sure if this is a sort of race condition now, though, as the devices aren't getting mounted at boot time.

I'm wondering if the `mounts` section from the cloud-init happens before the `runcmd`? I suppose it's possible to do `mount ....` in the runcmd after, but that seems messy.

**Comment by niusmallnan** [comment]
The `runcmd` scripts runs before user docker.
The `mounts` runs before `runcmd`.
