### ISSUE TITLE
cloud-init is nos installed when ros install -install-type noformat

### ISSUE THREAD

**Issue by segator** [rancher/os#2507]
**RancherOS Version: (ros os version)**
1.4.1
**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
vbox, vmware

If you partition manually the disk and after run the ros install with noformat installtype, ros ignore cloud-config passed by parameter.

`
DRIVE=/dev/sda
echo ", 500M,83,*
, 5G,83
,,83;" > /tmp/layout
sudo sfdisk "${DRIVE}" < /tmp/layout
sudo mkfs.ext4 -L RANCHER_BOOT "${DRIVE}1"
sudo mkfs.ext4 -L RANCHER_STATE "${DRIVE}2"
cat >cloud-init.yml<<EOF
#cloud-config
ssh_authorized_keys:
  - "ssh-rsa ${SSH_PUBLIC_KEY}"
rancher:  
  console: ubuntu
EOF
ros install -install-type noformat  -device /dev/sda -c cloud-init.yml --force
`
Load Rancheros on ram with a ISO
set SSH_PUBLIC_KEY variable
execute the script in the example

Expected behaviour is ros is installed and ssh key is setted and load with ubuntu console.

what really happens is rancher load from disk but ignored all the configurations of cloud-init

Tested on vbox and vmware

**Comment by niusmallnan** [comment]
Wow, this should be a bug.

**Comment by kingsd041** [comment]
@segator Thank you for the bug report! 
Fixed in rancher/os:ab4e0e5

**Comment by niusmallnan** [comment]
backported to v1.4.2
