### ISSUE TITLE
After couple of restart the rancher/os-docker:18.03.1 container is continuously restarting

### ISSUE THREAD

**Issue by arindamdat** [rancher/os#2510]
**RancherOS Version: (ros os version)**
Rancher OS Version : v1.4.1
system-docker version
Client:
 Version:      17.06-ros4
 API version:  1.31
 Go version:   go1.8.3
 Git commit:   fa7c1dad
 Built:        Mon Apr 16 05:23:57 2018
 OS/Arch:      linux/amd64

Server:
 Version:      17.06-ros4
 API version:  1.31 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   adf2c34
 Built:        Mon Apr 16 05:35:42 2018
 OS/Arch:      linux/amd64
 Experimental: false

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
Running Rancher OS on baremetal.

Issue:
I ran the command "system-docker restart docker" couple of times. Suddenly the rancher/os-docker:18.03.1 started continuously restarting. As a result, when I run "docker ps", it gives me error "Cannot connect to the docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?".
I tried the following things:
1. Checked logs for ancher/os-docker container using "system-docker logs docker". I could not find any error in the logs, but repeated restart logs. Log file attached
[os-docker-logs.txt](https://github.com/rancher/os/files/2457442/os-docker-logs.txt)
2. Switched back to "default" console and again re-switching back to "ubuntu" console.
3. Upgraded RancherOS "sudo ros os upgrade" even with --upgrade-console flag. But no luck.

Any help will be appreciated.

[Additional note]: I was trying to change the "data_root" path from default "/var/lib/docker" to some other path. That's why I was applying some config settings which needed to restart user-docker again and again. If someone can guide me on how to change data_root also it'll be highly appreciated.

**Comment by niusmallnan** [comment]
Try this: `ros config set rancher.docker.graph <your-dir>`
If you want to use `data-root`, you should try `ros config set rancher.docker.extra_args [--data-root=<your-dir>]`.

**Comment by arindamdat** [comment]
Thank you so much @niusmallnan. I tried setting extra_args but probably with wrong value. Can it be the reason behind continuous restarting of the os-docker container? Strangely I could not find any error in the container log.

**Comment by arindamdat** [comment]
Hi @niusmallnan , FYI.. Yes, my assumption was correct. The os-docker container was continuously restarting because I applied wrong docker setting. After applying the setting the way you suggested, the user-docker is running and working as expected. Thanks for your help.
