### ISSUE TITLE
A tool for collecting diagnostic information

### ISSUE THREAD

**Issue by niusmallnan** [rancher/os#2511]
When we help users troubleshoot problems, we often collect some information to determine the root cause. This can be very effective if we have a tool.

The following information is valuable:
1. logs in `/var/logs/boot`
2. `ros c export`
3. `/var/lib/rancher/conf` and /usr/share/ros/os-config
4. `ros -v`
5. `system-docker info` and  `docker info`
6. `cat /proc/mounts` and `cat /proc/1/mounts`

Finally, we need to filter out sensitive information, such as ssh key.

**Comment by kingsd041** [comment]
I wrote a tool to collect diagnostic information for rancheros.
Mainly includes some ranchero logs and important configuration, and filtered out the ssh key.

| Collect items | 
| :------ |
|ros c export|
|ros -v|
|uname -r|
|dmesg|
|system-docker info|
|docker info|
|/proc/mounts|
|/proc/1/mounts|
|/proc/cmdline|
|/var/lib/rancher/conf|
|/usr/share/ros/os-config.yml|
|/var/log/boot|

## How to use
1. Login to your rancheros and switch to root
> Use this tool requires root privileges
```
$ sudo su - root
```
2. Collecting rancheros information
```
# curl https://raw.githubusercontent.com/kingsd041/rancheros/master/collect-rancheros-info.sh | sh
```

**Comment by niusmallnan** [comment]
We can run `wget -O - https://raw.githubusercontent.com/kingsd041/rancheros/master/collect-rancheros-info.sh | sudo su` in the default console
