### ISSUE TITLE
support for virtualbox and vmware workstation

### ISSUE THREAD

**Issue by segator** [rancher/os#2517]
it could be very useful to be able to install  virtualbox and vmware on rancherOS, because if you want to run [packer.io](url), I tried to build a docker image with vbox and vmware but both fails because needs extra modules in kernel.

**Comment by niusmallnan** [comment]
It seems that not so many people need it, it does not have a high priority for us.

**Comment by segator** [comment]
well could you give me some indications how to do it, I could try and if works PR.
For Vbox I Guess it will be easier because de code is open but for vmware I'm not sure.

**Comment by ryansch** [comment]
You could solve this with a container like we did for parallels: https://github.com/outstand/docker-parallels-tools
