### ISSUE TITLE
[question] two IP addresses on eth0?

### ISSUE THREAD

**Issue by MSandro** [rancher/os#2520]
**RancherOS Version: 1.4.1

**Where are you running RancherOS? VPS hosted by contabo.com

I have two IP addresses available for my contabo virtual private server. But I am not sure how to configure those. They send me an link to a tutorial which describes how to setup a second IP on several distros like CentOS or Ubuntu. https://contabo.com/?show=tutorials&tutorial=configuring-additional-ip-addresses
Could someon help me please? It would be realy nice if someon could send me an example of the cloud-config.yml

I don't have a second interface / macadress. I only want to acces both IP addresses throught eth0.

Thanks.

**Comment by niusmallnan** [comment]
Currently, we do not support setting up multiple IPs via `rancher. network.interfaces`.
But you can enable it via `runcmd`:
```
runcmd:
- ip addr add 192.168.50.50/24 broadcast + dev eth0 label eth0:0
```

Check the result after reboot:
```
eth0      Link encap:Ethernet  HWaddr 08:00:27:52:DF:2D
          inet addr:172.22.100.100  Bcast:172.22.100.255  Mask:255.255.255.0
          inet6 addr: fe80::a00:27ff:fe52:df2d/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:93 errors:0 dropped:0 overruns:0 frame:0
          TX packets:78 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:11621 (11.3 KiB)  TX bytes:13019 (12.7 KiB)

eth0:0    Link encap:Ethernet  HWaddr 08:00:27:52:DF:2D
          inet addr:192.168.50.50  Bcast:192.168.50.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
```

**Comment by MSandro** [comment]
Hi, thank you very much. Do I have something to consider at the gateway?

**Comment by niusmallnan** [comment]
If you want to change the routes for the second address, you can use `ip route replace xxxx`.
