### ISSUE TITLE
ros os upgrade from 1.4.1 to 1.4.2 changed our docker version?

### ISSUE THREAD

**Issue by jonaz** [rancher/os#2530]
**RancherOS Version: (ros os version)**

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
Bare metal installed to disk

After the upgrade ros engine list showed that 18.03.1-ce was running. But we need docker-17.03.2-ce to be compatible with kubernetes. 

```
[root@rancher03 ~]# cat /var/lib/rancher/conf/cloud-config.d/user_config.yml 
#cloud-config
rancher:
  console: centos
  docker:
    engine: docker-17.03.2-ce

```

Why did a simple ros os upgrade change to 18.03.1-ce. We are unable to start kubelet after that because i think its differences how the docker versions use overlay2. 

```
[root@rancher01 rancher]# docker start kubelet
Error response from daemon: error creating overlay mount to /var/lib/docker/overlay2/54a5f305f2eda0ab4dd1df477c93275f0aa85656f69395713625a8b28d9999b6/merged: no such file or directory
Error: failed to start containers: kubelet
```

**Comment by niusmallnan** [comment]
@jonaz  I cannot reproduce it on AWS. Can you provide more details?
What's the output of `ros c export` after the upgrade?

**Comment by jonaz** [comment]
I'll provide that output tomorrow. However we only noticed this on 2 out of 3 of our kubernetes master nodes. Which all where installed at the same time a few weeks ago.

**Comment by jonaz** [comment]
ros c export all show docker engine docker-17.03.2-ce. But i guess it will be hard to troubleshoot this since we after the problem was detected did a ```ros engine enable docker-17.03.2-ce && reboot```

I have more mathines to upgrade so you can close this issue and i will open it again if i can duplicate the problem.
