### ISSUE TITLE
Make SCP available for CentOS console

### ISSUE THREAD

**Issue by jbrockopp** [rancher/os#2536]
**RancherOS Version: (ros os version)**

```
[rancher@server ~]$ sudo ros -v
version v1.4.0 from os image rancher/os:v1.4.0
```

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**

OpenStack

When using the base CentOS console, it doesn't appear to have `scp` available.

```
[rancher@server ~]$ sudo ros console switch centos
Switching consoles will
1. destroy the current console container
2. log you out
3. restart Docker
Continue [y/N]: y
INFO[0001] Service console using local image docker.io/rancher/os-centosconsole:v1.4.0
switch-console_1 | time="2018-10-26T15:12:59Z" level=info msg="Project [os]: Starting project "
switch-console_1 | time="2018-10-26T15:12:59Z" level=info msg="[0/23] [console]: Starting "
switch-console_1 | time="2018-10-26T15:12:59Z" level=info msg="Recreating console"
Connection to server closed by remote host.
Connection to server closed.
$ ssh rancher@server
[rancher@server ~]$ scp --help
-bash: scp: command not found
```

This can make it not play well if you're building your own immutable image based off of RancherOS with the CentOS console.

In my specific case, [Packer](https://www.packer.io/) appears to use `scp` under the hood when trying to copy files to the server.

I first was using [Rancher's native console setup](https://rancher.com/docs/os/v1.x/en/installation/configuration/switching-consoles/#enabling-consoles-using-cloud-config) by using the cloud-config.

```yaml
#cloud-config
rancher:
  console: centos
```

This doesn't particularly cause a problem here, but as a part of our image pipeline, we then run an extensive suite of tests against our images by sourcing the image we build above and copying scripts to the server and executing them. When Packer tries to copy the scripts over it can't and we see this error produced:

```sh
Build 'openstack' errored: Retryable error: Error uploading script: SCP failed to start. This usually means that SCP is not
properly installed on the remote system.
```

I then decided to try and work around that by using [Rancher's switch console while running method](https://rancher.com/docs/os/v1.x/en/installation/configuration/switching-consoles/#changing-consoles-after-rancheros-has-started) with this Packer provisioner:

```json
  "provisioners": [
    {
      "type": "shell",
      "expect_disconnect": true,
      "inline": [
        "yes | sudo ros console switch centos"
      ]
    },
  ]
```

This made it worse as I wasn't even able to run any provisioners after that because of the same underlying issue (no `scp`)

```sh
Build 'openstack' errored: Retryable error: Error uploading script: SCP failed to start. This usually means that SCP is not
properly installed on the remote system.
```

Would it be possible to get `scp` added to the [CentOS console Docker image](https://github.com/rancher/os-services/blob/master/images/10-centosconsole/Dockerfile) so it plays a little nicer with Packer?

**Comment by niusmallnan** [comment]
Hi, you can add it via `yum install openssh-clients`.

**Comment by jbrockopp** [comment]
@niusmallnan Yes I am aware that it can be installed after the fact with that command. But would it be possible to add that to the base console Docker image so its already available?

I believe `scp` is a pretty basic, but important, utility for an OS to have. Maybe a better question is are there some reasons why it isn't already included in the base console image?

**Comment by rootwuj** [comment]
Version - rancher/os:v1.5.0-rc1 11/22
 Verified fixed
