### ISSUE TITLE
Add support for preloading images from disk

### ISSUE THREAD

**Issue by ibuildthecloud** [rancher/os#254]
Today the base OS images are packaged in images.tar in the initrd.  Once the state partition is loaded we should look for *.tar.gz at `/var/lib/rancher/images/system` and load those in to system docker.  Once the file is successfully loaded we should delete those files so the loading happens on first boot only.

Additionally we should look for `/var/lib/rancher/images/user/*.tar.gz` and preload those into user docker.

**Comment by ibuildthecloud** [comment]
@imikushin @cloudnautique Thoughts?

**Comment by cloudnautique** [comment]
I like the approach, and think this will work. Are these going to be `docker save` or `docker export`. If we can pull it off, I think the save approach is what we will want.

**Comment by ibuildthecloud** [comment]
Save format.  The format that keeps the layers and metadata intact.

**Comment by SvenDowideit** [comment]
I'd like to do this on b2d too - `docker save` wise definitely.

given that you guys are being forced to implement b2d legacy stuff here, perhaps we can agree on a more neutral location?

(or perhaps we can do something clever with `/var/lib/docker`?

**Comment by ibuildthecloud** [comment]
@SvenDowideit I think a neutral location would be good.  It would actually be nice to put it in `/var/lib/docker/preload` or something like that and have docker do this itself on startup.  Then things beside b2d and RancherOS could leverage this.  I know it's a pretty common scenario to want to prepackage images in a VM/server image (for example AMI), and for image builders it would be probably be cleaner to place a `docker save` tarball then have to boot docker in the image and do a `pull`.  Not no mention doing a pull stores things in a graph driver specific way and not as portable as the save format.

Do you think I should put in a proposal to Docker?  If the core team is on board with this then we can do the work in Docker itself.

**Comment by imikushin** [comment]
+1 for docker-side preload of `docker save`ed images.

**Comment by deniseschannon** [comment]
@imikushin Has this been resolved with the instructions? http://docs.rancher.com/os/configuration/prepacking-docker-images/

**Comment by deniseschannon** [comment]
Confirmed that this exists in the docs.
