### ISSUE TITLE
Not able to build custom rancher raw: install2disk missing

### ISSUE THREAD

**Issue by tech509201941** [rancher/os#2543]
I try to build a custom rancher raw as described here in the official rancher docs:

https://rancher.com/docs/os/v1.2/en/custom-builds/custom-rancheros-iso/

Unfortunately, I am not able to successfully address this step over here:

`packer build gce-qemu.json`

Results in:

```
qemu-googlecompute output will be in this color.

1 error(s) occurred:

* Bad script '../scripts/install2disk': stat ../scripts/install2disk: no such file or directory
```

Where do I get this ../scripts/install2disk'?
I can't find it in the repo:
https://github.com/rancher/os/tree/master/scripts

Thanks a lot :)

**Comment by niusmallnan** [comment]
https://github.com/rancher/os-packer

**Comment by tech509201941** [comment]
Thanks for your support.
Unfortunately, I am now blocked by this error:

`RANCHEROS_VERSION=v1.4.2 make test-build`

Resulting in:

`AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY must be set`

**How can I get the image as file?**

I don't want to directly deploy to AWS or something like that.
Thanks a lot :)

**Comment by niusmallnan** [comment]
If you want to build a GCE image, try this:
`PACKER_BOOT_WAIT=90s RANCHEROS_VERSION=vX.Y.Z make build-gce`

**Comment by tech509201941** [comment]
Thank you for your support @niusmallnan :)

I tried with:
`PACKER_BOOT_WAIT=90s RANCHEROS_VERSION=v1.4.2 make build-gce`

but it fails at this step:

```
==> Builds finished but no artifacts were created.
2018/10/31 14:26:49 [INFO] (telemetry) Finalizing.
Build 'qemu-googlecompute' errored: Build was halted.

==> Some builds didn't complete successfully and had errors:
--> qemu-googlecompute: Build was halted.

==> Builds finished but no artifacts were created.
2018/10/31 14:26:50 waiting for all plugin processes to complete...
2018/10/31 14:26:50 /go/bin/packer: plugin process exited
2018/10/31 14:26:50 /go/bin/packer: plugin process exited
mv: cannot stat 'output-qemu-googlecompute/packer-qemu-googlecompute': No such file or directory
tar: disk.raw: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors
upload the GCE image using:
  gsutil cp dist/rancheros-v1.4.2.tar.gz gs://releases.rancher.com/os/latest/rancheros-gce.tar.gz
  gsutil cp dist/rancheros-v1.4.2.tar.gz gs://releases.rancher.com/os/v1.4.2/rancheros-gce.tar.gz
upload the github release:
  github-release upload  --user rancher --repo os --tag v1.4.2 --file dist/rancheros-v1.4.2.tar.gz --name rancheros-gce.tar.gz
INFO[0283] docker cp /source/dist .   
```               

Is anyone able to investigate what is missing?
Thanks a lot :)

**Comment by niusmallnan** [comment]
Missing logs, I cannot see the key errors.

However, there is one point to confirm that your host needs to support KVM.

**Comment by niusmallnan** [comment]
```
2018/11/01 16:21:32 packer: 2018/11/01 16:21:32 Qemu stderr: Could not access KVM kernel module: No such file or directory
2018/11/01 16:21:32 packer: 2018/11/01 16:21:32 Qemu stderr: failed to initialize KVM: No such file or directory
```
It seems like that KVM is not enabled on your setup.

**Comment by tech509201941** [comment]
@niusmallnan 

Thanks a lot this was my mistake :)

Do you have a idea on how to build a **QCOW2 (QEMU Emulator)** image or respectively is there an official way to accomplish this?

**Comment by niusmallnan** [comment]
You can refer to this script: https://github.com/rancher/os-packer/blob/master/cloudstack/cloudstack-qemu.json
