### ISSUE TITLE
vSphere Cloud Provider support

### ISSUE THREAD

**Issue by nickychow** [rancher/os#2548]
**RancherOS Version: (ros os version)**
v1.4.0

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
VMware

Hey, I just wondering whether RancherOS is planing to support vSphere Cloud Provider in the future.

Cheers,

Nick

**Comment by niusmallnan** [comment]
We have no plan, what problems have you hit?

**Comment by khauser** [comment]
We with rancher OS 1.5.1 hit https://github.com/vmware/open-vm-tools/issues/236
Could you update rancher OS to use  version 10.3.10 of Open VM Tools?
Currently 10.2.5-3 is installed.

**Comment by niusmallnan** [comment]
ok, close this issue, will track the new one.
