### ISSUE TITLE
dhcpcd process become orphaned

### ISSUE THREAD

**Issue by niusmallnan** [rancher/os#2550]
**RancherOS Version: (ros os version)**
All

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
Any

It's very easy to reproduce, just try `system-docker restart network`.
We will see more and more `dhcpcd` processes.

**Comment by rootwuj** [comment]
Version - rancher/os:v1.5.0-rc1 11/22
 Verified fixed
