### ISSUE TITLE
LVM and LUKS support

### ISSUE THREAD

**Issue by bernard-wagner** [rancher/os#2551]
**RancherOS Version: latest**

**Where are you running RancherOS? baremetal**

Resurrecting https://github.com/rancher/os/pull/1465 but with a focus on only introducing LVM and LUKS support. 

The aim would be to enable baremetal and VM based machines to make use of LUKS to prevent data leakage, either through physical access or insecure backup procedures.

**Comment by niusmallnan** [comment]
All PRs have been merged, you can try master. @bernard-wagner 
Also, our QA will help test it out.

**Comment by rootwuj** [comment]
Tested with RancherOS version- v1.5.0-rc2
This version supports LVM and LUKS.
