### ISSUE TITLE
Ability to disable cloud-init during boot

### ISSUE THREAD

**Issue by niusmallnan** [rancher/os#2552]
Some users don't use cloud-init, if we can disable it, then we can reduce the startup time.

For some historical reasons, we have set a data source by default.
```
cloud_init:
   datasources:
      - configdrive:/media/config-2
```

So we can't judge based on `len(datasources)`, we might need to introduce a new configuration.

**Comment by rootwuj** [comment]
Version - rancher/os:v1.5.0-rc1 12/02
Verified fixed
