### ISSUE TITLE
RancherOS ignores Openstack Cloud Init and defaults to VMWare

### ISSUE THREAD

**Issue by mitchellmaler** [rancher/os#2558]
**RancherOS Version: (ros os version)**
v1.4.2

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
Openstack running on VMWare

I am trying to evaluate running RancherOS on our on-prem Openstack platform but the cloud-init does not seem to work. I downloaded the openstack raw image, converted it to a vmdk, and then uploaded and deployed a nova instance. 

The issue I am seeing is the cloud-init is ignoring openstack and just defaulting to VMWare which is not providing any sshkeys, hostname, etc. I auto-logged into the instance using the console and manually set the rancher.cloud_init.datasources to openstack and rebooted. Even after I rebooted it did not work. When I checked the cloud-init-save.log it is checking both openstack and VMWare and skipping the openstack.

I also verified the config drive was available and mountable. It wasn't mounted but I was able to manually do it and verify the cloud config was there.

![screen shot 2018-11-08 at 1 48 09 pm](https://user-images.githubusercontent.com/4107699/48390123-1250d300-e6c6-11e8-87d3-0beeee423728.png)

**Comment by niusmallnan** [comment]
Looks like the same issue with https://github.com/rancher/os/issues/2465

I will ship 1.5.0-rc1 this week, then you can try again.

**Comment by niusmallnan** [comment]
Cool, can we close this issue?
