### ISSUE TITLE
Azure RancherOS Version

### ISSUE THREAD

**Issue by mitchellmaler** [rancher/os#2564]
Do you plan on updating the Azure RancherOS Image? Right now it is just on version 0.3.1

**Comment by superseb** [comment]
There is an open issue here https://github.com/rancher/os/issues/84, we are taking another look on the process of adding builds to Azure which has been proven painful in the past.

**Comment by mitchellmaler** [comment]
Do you have a good way or example packer script I can run to build and push an image to my own azure subscription? We are using ros on prem and want to do the same in the cloud

**Comment by superseb** [comment]
@niusmallnan is taking a look at it but there is no ETA yet
