### ISSUE TITLE
Customize Image with cloud-init either by modify img or building manually

### ISSUE THREAD

**Issue by mitchellmaler** [rancher/os#2565]
Is there a way to bake the image or modify an existing image and provide the cloud-config file that way. This way my image will always startup with my preset defaults.

**Comment by niusmallnan** [comment]
https://rancher.com/docs/os/v1.x/en/installation/custom-builds/custom-rancheros-iso/

**Comment by mitchellmaler** [comment]
Oh dang I completely missed that! Thanks
