### ISSUE TITLE
failed to build on master (commit 7b23decff)

### ISSUE THREAD

**Issue by liyimeng** [rancher/os#2566]
**RancherOS Version: (ros os version)**

rancher:~/os$ sudo ros os version
v1.4.2

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
 KVM

I try to build the master branch, which is at the commit: 
```
commit 7b23decffd61b7eed2f8bd3a42a11a3328430a7f
Author: niusmallnan <niusmallnan@gmail.com>
Date:   Thu Nov 15 17:09:22 2018 +0800

    Update vmware release script

```

It throws out errors like this: 

```
ros_services.go:3:8: cannot find package "gopkg.in/check.v1" in any of:
	/go/src/github.com/rancher/os/vendor/gopkg.in/check.v1 (vendor tree)
	/usr/local/go/src/gopkg.in/check.v1 (from $GOROOT)
	/go/src/gopkg.in/check.v1 (from $GOPATH)
time="2018-11-16T12:54:39Z" level=fatal msg="exit status 1" 
cp dist/artifacts/rancheros.iso scripts/images/openstack/
cp: can't stat 'dist/artifacts/rancheros.iso': No such file or directory
make: *** [Makefile:52: qcows] Error 1
```

What could be wrong?

**Comment by niusmallnan** [comment]
Try this:
```
make .dapper
INTEGRATION_TESTS=0 make release-build
```

**Comment by liyimeng** [comment]
I still fail at some test case, and build terminate early. 

`coverage: 62.9% of statements
ok  	github.com/rancher/os/config/cloudinit/system	1.044s	coverage: 62.9% of statements
?   	github.com/rancher/os/config/cmdline	[no test files]
?   	github.com/rancher/os/config/yaml	[no test files]
?   	github.com/rancher/os/dfs	[no test files]
?   	github.com/rancher/os/docker	[no test files]
?   	github.com/rancher/os/hostname	[no test files]
time="2018-11-16T14:32:52Z" level=fatal msg="exit status 2" 
`

**Comment by niusmallnan** [comment]
If you updated some code, you need to make sure that `make validate` and `make test` can work before building.

**Comment by liyimeng** [comment]
no, I have not done anything yet. However, I run it inside rancher 1.4.2 with apine/ubuntu console. 
Both failed, could be something to do with the env?  dapper normally isolate this pretty well. Not sure why this could happen. Will destroy the VM and build again to see if it helps.

**Comment by niusmallnan** [comment]
I recommend you build with Ubuntu 18.04.

**Comment by liyimeng** [comment]
Yes, it works on U18.04.  I don't understand the difference. :(

BTW, should we make sure this also work on RancherOS? It is RancherOS we trust!    It is the best OS, should be for everything :D

**Comment by liyimeng** [comment]
hi @niusmallnan I will close this issue now. Before doing so, may I ask you some questions: 
1. I have issue https://github.com/rancher/os/issues/2241 if I try to install to disk after iPXE boot, I need to apply the workaround mentioned in the comment to get it continue. My question is that, are we going to fix this, or just let it be a feature  ? :dancer: 
2. I see the initrd is significant bigger that usual, is this expected?  
 
`
liyi@u18:~/os/dist/artifacts£ ls -alh
total 620M
drwxr-xr-x 2 liyi liyi 4.0K Nov 20 10:11 .
drwxr-xr-x 4 liyi liyi 4.0K Nov 20 10:11 ..
-rwxr-xr-x 1 liyi liyi  161 Nov 20 10:11 Dockerfile.amd64
-rw-r--r-- 1 liyi liyi 148M Nov 20 10:11 fullinstaller.tar
-rw-r--r-- 1 liyi liyi 108M Nov 20 09:16 initrd-6be7426
-rw-r--r-- 1 liyi liyi 108M Nov 20 10:11 initrd-6be7426-dirty
-rw-r--r-- 1 liyi liyi  35M Nov 20 10:11 installer.tar
-rw-r--r-- 1 liyi liyi  141 Nov 20 10:11 iso-checksums.txt
-rw-r--r-- 1 liyi liyi  423 Nov 20 10:11 rancheros.ipxe
-rw-r--r-- 1 liyi liyi 128M Nov 20 10:11 rancheros.iso
-rw-r--r-- 1 liyi liyi  84M Nov 20 10:09 rootfs.tar.gz
-rw-r--r-- 1 liyi liyi 6.0M Nov 20 10:09 vmlinuz-4.14.73-rancher
-rw-r--r-- 1 liyi liyi 5.3M Nov 20 09:15 vmlinuz-4.14.79-rancher2
`
It is so big that I was expecting that the installation to disk need not going out to fetching other images(installer.tar and fullinstaller.tar), however it was not the case. May you explain what is inside the big file briefly? 

BR/Liyi

**Comment by niusmallnan** [comment]
Q1: In most cases, using iPXE will load this image(https://ipxe.org/download), so usually /dev/sr0 should exist.  If your setup is really special, please file an new issue, we can track that.

Q2: We no longer use xz to compress initrd, many users complain that decompression is too slow at bootup. So we use gzip to compress initrd.

**Comment by liyimeng** [comment]
@niusmallnan I use the built-in dhcp server in dnsmasq, and the problem has been persistent. 
Thanks for the answers!
