### ISSUE TITLE
doc links via Google or Github constantly lead to 404

### ISSUE THREAD

**Issue by till** [rancher/os#2567]
Whenever you google something unknown with RancherOS, the majority of the links lead to a 404 page or something else that is broken. Can anyone take a look and redirect the links to something that works?

I know it's kinda vague, but for example, google rancheros password, come to a GitHub issue (#1467) where a docs.rancher.com link is mentioned that no longer works. I figured I make an issue and hope this doesn't offend anyone. :D

**Comment by niusmallnan** [comment]
https://rancher.com/docs/os/v1.x/en/installation/boot-process/built-in-system-services/

**Comment by till** [comment]
@niusmallnan yeah, I found that after, however: https://rancher.com/docs/os/system-services/built-in-system-services/

**Comment by till** [comment]
@niusmallnan confused, is this the wrong repo?

**Comment by niusmallnan** [comment]
How did you get this link? which keyword for google?

**Comment by till** [comment]
@niusmallnan this was an **example**, but in this specific case Google pointed me to https://github.com/rancher/os/issues/1467 and the link is in one of the comments.

**Comment by till** [comment]
@niusmallnan thanks, I realise this. I am asking if it can be "fixed", e.g. old links can be redirected so it's not trial and error? But I don't want to argue.
