### ISSUE TITLE
Change banner of rancher 

### ISSUE THREAD

**Issue by Tamil18** [rancher/os#2584]
Hi,
I would like to change the banner of rancher os is that possible because,i wont find /etc/banner file 
Please help me 

Regards 
tamil

**Comment by niusmallnan** [comment]
You want this? https://github.com/rancher/os/blob/master/config/config.go#L12-L21

**Comment by itstamil** [comment]
Yes I also looking for it 
After installation how we can change that, and another one the computer name is also not changing

please help me

**Comment by niusmallnan** [comment]
You should update the code, and build your own RancherOS.
