### ISSUE TITLE
Rancher password is not changing even we change password

### ISSUE THREAD

**Issue by itstamil** [rancher/os#2585]
hi, 
i have been using rancher over months , now i have tried to change my password for rancher 
Default
user:rancher
passwd:rancher
(note: Im using ubuntu console)

via shell command **passwd** i have tried to change the password but its last upto the time of reboot once reboot occurs the password is back to rancher 

please help me 

Regards 
Tamilvalavan

**Comment by niusmallnan** [comment]
Did you set `rancher.password` in kernel cmdline?

**Comment by niusmallnan** [comment]
So you set the password in cmdline, it will always be effective.
You can update the password by `ros config syslinux`

**Comment by Wykiki** [comment]
Simple edit of @itstamil command, as I've lost 5 min to find out I was using the wrong flag to append kernel parameters !

```
sudo ros install -d /dev/sda -a rancher.password=your_pass
```

**Comment by itstamil** [comment]
@wykiki sorry it's just an type error 

Please try to change the password using "passwd"
Then reboot your machine it will gone because in rancheros it's not possible

**Comment by itstamil** [comment]
So @niusmallnan suggest the above command

**Comment by Wykiki** [comment]
Doing this command : `sudo ros install -d /dev/sda -a rancher.password=your_pass` worked for me.
I was able to ssh to RancherOS with user `rancher` and password `your_pass`.

And the command of @niusmallnan (`ros config syslinux`) worked for updating the password.
