### ISSUE TITLE
Use custom console image on startup

### ISSUE THREAD

**Issue by mitchellmaler** [rancher/os#2586]
version: latest
I have extended the rancheros-alpineconsole docker image and installed a few required packages. Now I would like to boot up RancherOS using my custom console image. I am unable to find where in the cloud config this can be set other than just the console name.

**Comment by niusmallnan** [comment]
You can fork os-services, and update the alpine console service.
Then update the `rancher.repositories.core.url` in `/usr/share/ros/os-config.yml`.

**Comment by mitchellmaler** [comment]
It would be much easier if we didn't have to fork a repository to use a custom console. Could it be enhanced to be able to point and pull a console from a custom repo by just passing it to the cloud-init process? Like as part of the console flag make it optionally available to just pass an image repo and tag location?

**Comment by niusmallnan** [comment]
This would be helpful
https://rancher.com/docs/os/v1.x/en/installation/system-services/custom-system-services/#service-development-and-testing

**Comment by niusmallnan** [comment]
Is this helpful for you? https://github.com/rancher/os/issues/2603
