### ISSUE TITLE
stage all container images when enabled instead of at startup.

### ISSUE THREAD

**Issue by deniseschannon** [rancher/os#259]

**Comment by wlan0** [comment]
Can you elaborate?

**Comment by deniseschannon** [comment]
The request is that when we enable a service, they want any images in the service to be downloaded during enabling versus waiting until we reboot.

@ibuildthecloud please let me know if the elaboration is incorrect.

**Comment by imikushin** [comment]
Another option would be to run the new service on enable. But this could be
controlled by a parameter. Say, with `--stage` just download the images and
start everything on reboot. Without the option, start right away.

**Comment by ibuildthecloud** [comment]
I think what @imikushin said may be better.  We might be able to just do a "project up" after saving the configuration.

**Comment by deniseschannon** [comment]
Verified in v0.4.4-rc2.

Please note that if you are still booting from an iso, if you enable a service, your image might take up the entire RAM and not be able to pull the image. You would need to install to disk before attempting.
