### ISSUE TITLE
`sudo ros engine list` fail

### ISSUE THREAD

**Issue by fbigun** [rancher/os#2594]
**RancherOS Version: (ros os version)**
branch 'master' built iso. 
**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
hyper-v.

```
$sudo ros engine list
ERRO https://raw.githubusercontent.com/rancher/os-services/latest/index.yml: non-200 http response: 404
```
`https://raw.githubusercontent.com/rancher/os-services/latest/index.yml` or `https://raw.githubusercontent.com/rancher/os-services/master/index.yml`?

**Comment by niusmallnan** [comment]
How did you make?
If you want to support hyper-v, you should build it by `make hyperv`

**Comment by niusmallnan** [comment]
Any update?
Close it, if you still have problems, please reopen.
