### ISSUE TITLE
Support docker 18.09+ for user docker

### ISSUE THREAD

**Issue by niusmallnan** [rancher/os#2601]
Docker 18.09 has some changes:
```
- containerd
- containerd-shim
- ctr
- docker
- dockerd
- docker-init
- docker-proxy
- runc
```

For 18.06:
```
- docker
- docker-containerd
- docker-containerd-ctr
- docker-containerd-shim
- dockerd
- docker-init
- docker-proxy
- docker-runc
```

The binary naming convention has been modified, we need to be compatible with it.

**Comment by kingsd041** [comment]
RancherOS v1.5.1-rc1 already supports `docker-18.09.0` and `docker-18.09.1`
It works fine in my environment
