### ISSUE TITLE
Support WiFi on RPi3B+

### ISSUE THREAD

**Issue by niusmallnan** [rancher/os#2604]
From @TheAifam5:

> Ah that thing with 'brcmfmac43430-sdio' does not work. I'm using the 1.5.0-rc with RPi3B+.
Something with 'Direct firmware load for brcmfmac43455-stdio.bin failed with error -2'
'unhandled level 2 translation unit (11)'
'brcmf_sdio_htclk: HT Avail timeout 1000000... clkctl 0x50'
Installing this fixes all problems and don't need to run anything (you dont need rmmod, modprobe etc.. things)
brcmfmac43455-sdio.txt
brcmfmac43455-sdio.bin
brcmfmac43455-sdio.clm_blob

**Comment by TheAifam5** [comment]
Yea :D but installing this things does not fix that problem. My mistake :/ But the good news, booted without problems with that files, but while connecting crashes the kernel.

**Comment by kingsd041** [comment]
Rancheros 1.5.2-rc1 already supports WiFi on RPi3B+

Reference: https://github.com/rancher/docs/pull/1437/files#diff-52e56c2e82cc5096bed1ccd86a68f238
