### ISSUE TITLE
Install mosh vs sshd

### ISSUE THREAD

**Issue by andrewarrow** [rancher/os#2608]
**RancherOS Version: (ros os version)**
v1.4.2

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
DigitalOcean

The system runs sshd:

```
sudo ps awx | grep ssh
 1451 root     /usr/sbin/sshd -D
 1831 root     sshd: rancher [priv]
 1833 rancher  sshd: rancher@pts/0
 1841 root     sshd: rancher [priv]
 1843 rancher  sshd: rancher@pts/1
```

Which is great. But I’m wondering how to make it also support mosh? Would I have to fork the golang code and add mosh that way? Or is there a simpler way to make rancheros accept mosh vs ssh connections?

Thanks!

**Comment by niusmallnan** [comment]
I have not used mosh.
But you can try to switch other consoles(ubuntu/centos), then install mosh.

If you want to use mosh in the default console, you should add mosh to the default console image.
`https://github.com/rancher/os/tree/master/images/02-console`

**Comment by andrewarrow** [comment]
Yeah I am using 
https://github.com/blinksh/blink and have been moshing (not sshing) into my digital ocean server for a while now.

But now my digitial ocean server is running rancherOS and ssh is my only option. I need mosh to run on racher itself not a container within rancher.

Can you tell me more about adding mosh to the default console image? Once I do that I can build the image and then use that to create a new droplet on digital ocean? Thanks!

**Comment by niusmallnan** [comment]
The default console is built by buildroot, it does not support package management, like apt and apk and yum.
But you can prebuild mosh, and copy mosh to os-console image, the Dockerfile: https://github.com/rancher/os/tree/master/images/02-console

Then run `make`, and push the `rancher/os` image to your repo.
Boot a ROS instance on DO, try `ros os upgrade -i your-repo/os:<tag>` to use your custom build.

**Comment by andrewarrow** [comment]
OK I had success with:

1. ros console switch ubuntu
2. Copy over /usr/bin/mosh* from another ubuntu with mosh to /usr/bin
(And libutempter.so.0 and libprotobuf.so.10 to /lib)

So this is great! I’m moshing again with rancher like I was with ubuntu.

When I tried to get mosh working with default console (busybox) I had lots of problems.

So I guess, is it bad to keep running in ubuntu console? What am I giving up by not using the default console? Thanks!

**Comment by niusmallnan** [comment]
The default console is built by [buildroot](https://buildroot.org/), it is busybox.
 
The other consoles are built by their docker images, please check https://github.com/rancher/os-services/tree/master/images

 You can choose what you want.

**Comment by andrewarrow** [comment]
I see, thank you, closing this.

When I run `system-docker ps`

```
CONTAINER ID        IMAGE                              COMMAND                  CREATED             STATUS              PORTS               NAMES
102027d19826        rancher/os-ubuntuconsole:v1.4.2    "/usr/bin/ros entr..."   18 hours ago        Up 4 hours                              console
```

I see i now have a os-ubuntuconsole container running with must take more memory & cpu than busybox does. In fact, maybe back when I had ros running with the default console this container was just missing completly from system-docker ps list because there’s no need to even run a container if all you need is busy box...
