### ISSUE TITLE
Produce OpenStack images

### ISSUE THREAD

**Issue by deniseschannon** [rancher/os#261]
@cloudnautique will help @imikushin with how to package issues.

**Comment by janeczku** [comment]
I am interested in this too. Just to clarify, this OpenStack image will have `ec2 datasource` enabled by default?

**Comment by ibuildthecloud** [comment]
Yes it will.  Either ec2 or config drive support should be turned on in OpenStack, otherwise it won't boot.

**Comment by dudymas** [comment]
I agree we should add an image that takes user_data too. Perhaps we could get a custom build of cloudinit based on https://github.com/coreos/coreos-cloudinit and have the rancher system docker run the container... perhaps based on a phusion or alpine container, and it'd still be rather slim... could even tell it to clean up afterwards.

Just make it a special build. Still the same incredible size. And maybe just have it only run if the metadata service or config drive is available?

Thoughts?

**Comment by janeczku** [comment]
@dudymas RancherOS already supports querying ec2 meta- and user-data. It's just a question of whether ec2 or whatever other metadata service is enabled as a datasource in the prebuilt images. AFAIK this is only the case for the AMI images, whereas the ISO's and the initrd images default to config-drive as the only datasource.

**Comment by SatWiz** [comment]
I vote too for a general openstack image like coreos have which make automated host spawning easy. https://raymii.org/s/tutorials/Automating_Openstack_with_Cloud_init_run_a_script_on_VMs_first_boot.html

Also then we are free to choose the cloud provider with an openstack platform and not bound to Amazone only.

**Comment by clemenko** [comment]
A qcow2 that reads in user_data would be very helpful!

**Comment by flavorplus** [comment]
Hi guys,

How is progress on this?

**Comment by deniseschannon** [comment]
We've had some higher priority items that have required us to push this out.

**Comment by Slamper** [comment]
@ibuildthecloud Is there a reason why this is still open and the links to the image aren't listed in the README since the image is being built and available on https://releases.rancher.com/os/latest/rancheros-openstack.img

**Comment by clemenko** [comment]
resizefs would be awesome. Is it possible to include the version number. I am trying to automate imports and would like to see the version number to be better able to track when I need to run updates for my customers.

**Comment by Slamper** [comment]
@clemenko If that's what you mean you can also use 
https://releases.rancher.com/os/<version>/rancheros-openstack.img
Like:
https://releases.rancher.com/os/v0.4.3/rancheros-openstack.img

**Comment by clemenko** [comment]
Ok cool. Do I need to index off of the github release list?

**Comment by Slamper** [comment]
AFAIK you can use the version codes that are listed as releases (not RCs) on github starting from v0.4.3 as this seems to be the first release with OpenStack support.

**Comment by clemenko** [comment]
Do you know what the disk format and container format the img is? I am getting errors importing into glance.

**Comment by flavorplus** [comment]
I'm using QCOW2 as the format. I'm running it using a flavor with 1vcpu, 2GB ram and 10GB disk space for testing. It seems fine. There is no logging in to the container directly however. You need to use the Post-Creation script to supply SSH keys and config data.

**Comment by clemenko** [comment]
what container-format did you use when importing into glance?

**Comment by flavorplus** [comment]
"QCOW2 - QEMU Emulator"

**Comment by clemenko** [comment]
What was the glance command line you used?
Similar to glance image-create --name centos63-image --disk-format qcow2 \
 ** --container-format bare** --is-public True --file ./centos63.qcow2

**Comment by flavorplus** [comment]
yep sorry that would be bare

**Comment by flavorplus** [comment]
I was using Horizon however to do the import.

**Comment by clemenko** [comment]
I can upload it into glance. but it fails building. Looks like it might be a scheduling thing on my openstack cluster.

**Comment by Slamper** [comment]
Probably. It worked for me after I imported it with glance using qcow2 and bare. When launching from Horizon checking "Configuration Drive" was necessary since ROS doesn't seem to query the Openstack metadata service. 

Specifying a Post Creation script wasn't necessary to add the SSH keys since ROS found the key specified when launching fron Horizon (from the OpenStack keystore) itself.

**Comment by clemenko** [comment]
I am doing all that. I appears to be an issue with openstack itself and not the image.

**Comment by gschukin** [comment]
What is the download link for 0.4.4 release?

https://releases.rancher.com/os/v0.4.3/rancheros-openstack.img this one doesn't work :(

**Comment by joshwget** [comment]
The image for v0.4.4 is now available (https://github.com/rancher/os/releases/download/v0.4.4/rancheros-openstack.img)
