### ISSUE TITLE
Each time you use `ros engine create --help` to view the ssh-port defaults, it will return a different port.

### ISSUE THREAD

**Issue by kingsd041** [rancher/os#2612]
**RancherOS Version: (ros os version)**
v1.5.0-rc2
**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
ALL

Each time you use `ros engine create --help ` to view the ssh-port defaults, it will return a different port.

It is recommended not to display this default port.

```
[root@ip-172-31-37-98 ~]# ros engine create --help  | grep ssh-port
   --ssh-port value           set the ssh port for the engine (default: 40317)
[root@ip-172-31-37-98 ~]# ros engine create --help  | grep ssh-port
   --ssh-port value           set the ssh port for the engine (default: 35389)
```

**Comment by niusmallnan** [comment]
Make sense.
There will be no default value.
If users specify a port, we will use it. Otherwise, we will set a random port.

**Comment by kingsd041** [comment]
Based on the rancher/os: master version test. The default value has been removed
Test Results:
```
# ros engine create --help  | grep ssh-port
   --ssh-port value           set the ssh port for the engine
```
