### ISSUE TITLE
Start rancheros instance from GCE, can't log in using ssh key

### ISSUE THREAD

**Issue by kingsd041** [rancher/os#2613]
**RancherOS Version: (ros os version)**
1.5.0-rc2
**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
GCE

Start rancheros from GCE, then refer to the documentation [Adding SSH keys](https://rancher.com/docs/os/v1.x/en/installation/running-rancheros/cloud/gce/#adding-ssh-keys) `Option 1: Project Level SSH Keys` or `Option 2: Instance Level SSH Keys` to set rancheros ssh key, I can not log in to rancheros

If I put my public key in metadata -> sshKeys and then create or reset rancheros, I can log in successfully.
**Just like this:**
![image](https://user-images.githubusercontent.com/19684717/50372100-f87aa800-0602-11e9-8fd5-8fe850362b7e.png)

**Comment by niusmallnan** [comment]
We can get projeck and instance level keys by `curl`:
```
curl -H "Metadata-Flavor: Google" http://metadata.google.internal/computeMetadata/v1/instance/attributes/ssh-keys

curl -H "Metadata-Flavor: Google" http://metadata.google.internal/computeMetadata/v1/project/attributes/ssh-keys
```

But our code is reading `instance/attributes/sshKeys` and `project/attributes/sshKeys`, this should be a bug.

Also if we get `true` from `instance/attributes/block-project-ssh-keys`, we should ignore project level keys.

**Comment by kingsd041** [comment]
Tested with rancher/os:7a0d3a8
Verified fixed
