### ISSUE TITLE
shared folder issue in virthual box

### ISSUE THREAD

**Issue by itssivashankar** [rancher/os#2617]
I am using RancherOS  in  oracle virtualbox. where my host machine is ubuntu.
while using shared folder option in virthualbox. from the UI
sharing a folder  /Desktop .
I could not find any folder in my rancher virtualbox  in the folder /mnt/hgfs
so kindly guide me how to use shared folder from local machine (host) to rancher virtualbox .

**Comment by niusmallnan** [comment]
Same with #143 .
I have added it to milestone 1.5.1.
Close this one.
