### ISSUE TITLE
Get DigitalOcean working

### ISSUE THREAD

**Issue by deniseschannon** [rancher/os#262]

**Comment by klausenbusk** [comment]
I was able to install Rancher OS on a droplet (http://ix.io/17Cs), what really missing is automatic network configuration. If you boot with `rancher.cloud_init.datasources=[digitalocean]` it pull all the needed metadata to `/var/lib/rancher/conf/metadata` but it don't use it.

**Comment by deniseschannon** [comment]
@klausenbusk Would you be willing to make a PR to the docs with what you've done? There's already a page that exists, but just not published externally. 

https://github.com/rancher/rancher.github.io/tree/master/os/running-rancheros/cloud/do

**Comment by klausenbusk** [comment]
I have opened a PR.. https://github.com/rancher/rancher.github.io/pull/532

**Comment by SvenDowideit** [comment]
#1666 goes further, but I need to fix the 0.8+ installer, something's not quite right.

**Comment by calnation** [comment]
Would like to try this out on DO. Any hope for this to be supported soon?

**Comment by klausenbusk** [comment]
> Would like to try this out on DO. Any hope for this to be supported soon?

You can use [this](https://github.com/rancher/os/blob/master/scripts/hosting/digitalocean/cloud-config.yml) cloud-config for installing RancherOS on DigitalOcean, it worked when I created it :)

**Comment by wiktor-k** [comment]
This also may be relevant:

> RancherOS is now being offered as an “unofficial/unsupported” image available via the API. You can use the image slug of “rancheros”.

From https://digitalocean.uservoice.com/forums/136585-digitalocean/suggestions/7781898-add-rancheros

**Comment by calnation** [comment]
Yep, using the last link since yesterday but still can't access it via ssh. Keeps asking for password (tried both users root and rancher). I also can't reset password from DO web interface (says internally managed). Anyone knows a way around this?

**Comment by SvenDowideit** [comment]
When you create the vm, you need to add your (already uploaded) `--sshkey` in the command

**Comment by prologic** [comment]
FYI the latest v1.1.0 image on DO boots and immediately kernel panics.

**Comment by vincent99** [comment]
Works for me, was it a 512MB droplet?  512 is not currently enough for the boot process.

**Comment by prologic** [comment]
Oh'really? Okay i'll try with 1GB :)


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by prologic** [comment]
Okay now we have a different issue :)

See attached
<img width="1280" alt="screen shot 2017-10-17 at 6 07 04 pm" src="https://user-images.githubusercontent.com/1290234/31696434-021bdbf4-b366-11e7-81e4-39ed7bbe5bac.png">
