### ISSUE TITLE
Support for booting ROS on Proxmox VE by docker-machine

### ISSUE THREAD

**Issue by pietrushnic** [rancher/os#2621]
**RancherOS Version: v1.5.0**

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**

`docker-machine` with [Proxmox VE driver](https://github.com/lnxbil/docker-machine-driver-proxmox-ve).

I would like to boot Rancher OS from ISO and use persistent storage. 

Unfortunately, by default Rancher OS does not have `qemu-guest-agent` enabled, because of that, provisioning through `docker-machine` cannot succeed.

Solutions that I can imagine at this point are:
1. build my own ISO with enabled `qemu-guest-agent` service - have no idea how to do that and documentation doesn't seem to help me much with that
2. find another way to determine state and configure machine (e.g. cloud-init?) which is enabled by default since this seems to be an approach of e.g. [virtualbox](https://rancher.com/docs/os/v1.2/en/quick-start-guide/#launching-rancheros-using-docker-machine)

Please let me know if the above solutions make sense and if not, then I'm open for suggestions.

**Comment by niusmallnan** [comment]
I didn't try the Proxmox VE driver, but if you want to have qemu-guest-agent enabled, here are my suggestions:

1. update the [os-config.tpl.yml](https://github.com/rancher/os/blob/master/os-config.tpl.yml)
```
  services_include:
  {{- if eq "true" .AZURE_SERVICE}}
    waagent: true
  {{end -}}
    qemu-guest-agent: true
```
2. run `APPEND_SYSTEM_IMAGES="rancher/os-qemuguestagent:v1.4.0-rc1" make`

**Comment by pietrushnic** [comment]
@niusmallnan hmm, this works, but I was definitely not precise enough since that service have to be up to make any sense :), so one more question how to make it not only enabled but `up` by default?

**Comment by niusmallnan** [comment]
@pietrushnic You can cache the service yaml file so that ros can `up` this service.
Please refer to: https://github.com/rancher/os/blob/master/scripts/layout-initrd#L49-L83

Just add this to your custom branch:
```
cache_services "q/qemu-guest-agent.yml"
```

**Comment by pietrushnic** [comment]
@niusmallnan ok, thank this works for me:

```diff
diff --git a/os-config.tpl.yml b/os-config.tpl.yml
index a20e13f92e2b..54a899909180 100644
--- a/os-config.tpl.yml
+++ b/os-config.tpl.yml
@@ -25,6 +25,7 @@ rancher:
   {{- if eq "true" .AZURE_SERVICE}}
     waagent: true
   {{- end}}
+    qemu-guest-agent: true
   bootstrap:
     bootstrap:
       image: {{.OS_REPO}}/os-bootstrap:{{.VERSION}}{{.SUFFIX}}
diff --git a/scripts/layout-initrd b/scripts/layout-initrd
index dd85b70713fe..992d4c4f548b 100755
--- a/scripts/layout-initrd
+++ b/scripts/layout-initrd
@@ -46,6 +46,7 @@ BUG_REPORT_URL="https://github.com/rancher/os/issues"
 BUILD_ID=
 HERE
 
+cache_services "q/qemu-guest-agent.yml"
 # cache os-services yml file
 for file in $(ls .make-*); do
     case $file in
```

I assume this is hack, if there will be any best practices how those mods should be handled long term please let me know.

**Comment by niusmallnan** [comment]
Reopen this issue.
I will make it work, but I need some time to try Proxmox VE. I don't know much about it.

**Comment by pietrushnic** [comment]
@niusmallnan ok, please let me know if I can help you somehow. Have you got Proxmox VE set up?

**Comment by niusmallnan** [comment]
@kingsd041 Here is something that you can refer to:
My testbranch: https://github.com/niusmallnan/os/tree/qga-enabled
Just run `make qemuga`
This is my os-service repo for qemu-ga: https://github.com/niusmallnan/os-services/tree/qga-enabled

**Comment by kingsd041** [comment]
Launch ROS on Proxmox VE via docker-machine is already supported in v1.5.1-rc1
@pietrushnic  Thank you for your feedback
