### ISSUE TITLE
Remove rc suffix from open-iscsi service

### ISSUE THREAD

**Issue by superseb** [rancher/os#2622]
**RancherOS Version: (ros os version)**
v1.5.0

See https://github.com/rancher/os-services/blob/v1.5.0/o/open-iscsi.yml#L2

```
  image: ${REGISTRY_DOMAIN}/rancher/os-iscsi:v1.5.0-rc2
```

**Comment by niusmallnan** [comment]
Done.
https://github.com/rancher/os-services/commit/67c9f58fff898ba6ec4d40c6a1311640ee31f3e6
