### ISSUE TITLE
Update AWS regions for release

### ISSUE THREAD

**Issue by superseb** [rancher/os#2623]
**RancherOS Version: (ros os version)**
future releases

Update AWS regions to include all available regions when released.

https://docs.aws.amazon.com/general/latest/gr/rande.html#ec2_region

**Comment by niusmallnan** [comment]
@superseb Looks like we have included all available regions. https://github.com/rancher/os#amazon
Did I miss something?

**Comment by superseb** [comment]
@niusmallnan Missing `ap-northeast-3` and `eu-north-1`

**Comment by niusmallnan** [comment]
Looks like we cannot access `ap-northeast-3`:
> You can use the Asia Pacific (Osaka-Local) Region only in conjunction with the Asia Pacific (Tokyo) Region. To request access to the Asia Pacific (Osaka-Local) Region, contact your sales representative.

I will support `eu-north-1`.

**Comment by kingsd041** [comment]
We already support `eu-north-1`region
https://github.com/rancher/os-packer/commit/6b9590823a925718e77f35f573869d8dcedb9c77
