### ISSUE TITLE
Error on Running binaries

### ISSUE THREAD

**Issue by itstamil** [rancher/os#2630]
**RancherOS Version: 1.5

> error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory

For this the solution in Ubuntu was 

> apt-get install lib32stdc++6

But in Ros default console its not possible 
Please help me to resolve this issue

Because i prefer only the ROS default console im not interested in switching consoles 

Thank You

**Comment by niusmallnan** [comment]
You should copy this .so file to ROS by yourself.
The default console doesn't need it, we won't put it in the default console.

You can run a container in ROS and install or compile this .so in this container, then copy it to console.

**Comment by kingsd041** [comment]
@itstamil 
You can try to download the ubuntu [lib32stdc++6 package](https://packages.ubuntu.com/xenial/lib32stdc++6), then extract the lib32stdc++6 in the ubuntu system using `dpkg -X ./lib32stdc++6.deb extract`, and finally refer to the description in [filelist](https://packages.ubuntu.com/xenial/amd64/lib32stdc++6/filelist) in rancheros, copy the file to the corresponding directory
I have not tested these steps, you can try it.

**Comment by kingsd041** [comment]
This issue has not been updated within 50 days and I will close this issue.
If you still have doubts, please reopen it and let me know.
