### ISSUE TITLE
config validate should fail on configfiles in windows format

### ISSUE THREAD

**Issue by ChrisMir** [rancher/os#2631]
**RancherOS Version: (ros os version)**
1.4.2 & 1.5.0

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
baremetal & virtualbox

This has kept me busy for quiet some time. I composed a cloud-config.yml with notepad++ including basic networking and my ssh key. Moved the file to the installation device, validated (correctly) and installed ros with it, only to find out my ssh key was not accepted.

After some time I opened the configfile with vi, when I saw ^M at the end of each line, windows format!
So, changed the format to unix, redo all the steps and everything worked as expected.

I'd suggest the config validation function would at least give a warning when it encounters a windowformatted file

**Comment by kingsd041** [comment]
In the RancherOS v1.5.1-rc1 version, we added verification of the windows format.
```
[root@rancher rancher]# ros config validate -i windows-format-test.yml
FATA[0000] file format shouldn't contain CRLF characters
```
@ChrisMir Thank you for your feedback
