### ISSUE TITLE
RancherOS 1.5 zfs service issue

### ISSUE THREAD

**Issue by jdoucerain** [rancher/os#2633]
**RancherOS Version: (ros os version)**
1.5
**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
VM on premises

Hi there,
I am encountering an issue when I try to use RancherOS behind a proxy.
Everything is running fine (installation, upgrade, configuration,...) but when I am trying to set the zfs service up, the build.sh is failing.

The build.sh is leveraging the populated HTTP_PROXY, HTTPS_PROXY, NO_PROXY environment variables, but at the end of the script, the system-docker command used to build the zfs-tools image is not propagating the environment variables.

I simply tried to add --build-arg options on the system-docker build command and it worked nice.
See my patch below on the github rancher/os-services project
```javascript
diff --git a/images/20-zfs/build.sh b/images/20-zfs/build.sh
index de88a32..5fd8463 100755
--- a/images/20-zfs/build.sh
+++ b/images/20-zfs/build.sh
@@ -121,12 +121,28 @@ done
 for i in $(ls arch/sbin); do
    echo "system-docker cp wonka.sh \${1}:/sbin/$i" >> /dist/arch/setup_wonka.sh
 done
-system-docker build --network=host -t zfs-tools arch/
+
+if [ "XX$HTTP_PROXY" != "XX" ]
+then
+       BUILD_ARGS="--build-arg HTTP_PROXY --build-arg http_proxy="$HTTP_PROXY
+fi
+
+if [ "XX$HTTPS_PROXY" != "XX" ]
+then
+       BUILD_ARGS=$BUILD_ARGS" --build-arg HTTPS_PROXY --build-arg https_proxy="$HTTPS_PROXY
+fi
+
+if [ "XX$NO_PROXY" != "XX" ]
+then
+       BUILD_ARGS=$BUILD_ARGS" --build-arg NO_PROXY --build-arg no_proxy="$NO_PROXY
+fi
+
+system-docker build --network=host $BUILD_ARGS -t zfs-tools arch/
 
 modprobe zfs
 
 /dist/arch/setup_wonka.sh console
 /dist/arch/setup_wonka.sh zfs
 zpool import -a
 
 touch $STAMP

```

**Comment by deniseschannon** [comment]
@jdoucerain can you make a PR into os-services?

**Comment by jdoucerain** [comment]
yes sure no problem. I will do that tomorrow.

**Comment by jdoucerain** [comment]
The pull request is at https://github.com/rancher/os-services/pull/180
Thanks
Jerome
