### ISSUE TITLE
Unable to decrypt device using luksOpen via Ubuntu console

### ISSUE THREAD

**Issue by itsmesridhar** [rancher/os#2635]
**RancherOS Version: 1.5.0**
**Where are you running RancherOS?  baremetal**
Cryptsetup performs well in ros default console. For our purpose, we mostly prefer Ubuntu console as default or some other platform based console. luksFormat was not an issue in Ubuntu Console but while we try to decrypt the device using luksOpen via Ubuntu console, it can't able to create /dev/mapper/dm-crypt. So we can't able to open the device via Ubuntu console. Can you please suggest some help for this issue?

**Comment by itsmesridhar** [comment]
Hi @niusmallnan, are you able to reproduce the issue from your side?

**Comment by niusmallnan** [comment]
@itsmesridhar sorry, too many tasks to do, didn't have time to look at it.
Ping @kingsd041 do you have time?

**Comment by itsmesridhar** [comment]
@kingsd041 Thanks, its working now :-)
