### ISSUE TITLE
crontab is not running on ros console

### ISSUE THREAD

**Issue by itstamil** [rancher/os#2638]
**RancherOS Version: 1.5.0**
Hi 
I have trying to enable crontab on ros console for that I was followed some steps like 
1)sudo ros service enable crontab
2)crontab -e  and add this line to it

> `*/1 * * * * . $HOME/.profile ; /opt/sample.sh`
But its not running even at the time of  reboot the whole crontab list is getting vanished from the machine 

please help me to solve this issue

Thank you

**Comment by niusmallnan** [comment]
RancherOS uses docker to manage everything:
https://rancher.com/docs/os/v1.x/en/installation/system-services/custom-system-services/#service-cron

The crontab CLI should be removed.

**Comment by itstamil** [comment]
Thanks for your reply 
But I need to run a shell script via crontab its possible to run a shell script via crontab in ros console

**Comment by niusmallnan** [comment]
@kingsd041 Can you give an example of the second way I recommend, when you have time? 

@itstamil Did you try that? Any problem?

**Comment by kingsd041** [comment]
@niusmallnan According to your steps, I can execute shell scripts in crontab.
Here are my steps:
```
mkdir -p /var/spool/cron/crontabs
# start crond
crond 
crontab -e
*/1 * * * *  /opt/sample.sh

cat /opt/sample.sh
#!/bin/bash
date >> /tmp/date.log

cat /tmp/date.log
Tue Jan 15 04:27:00 UTC 2019
Tue Jan 15 04:28:00 UTC 2019
Tue Jan 15 04:29:00 UTC 2019
...
```
@itstamil  You can get a log about crontab in `/var/log/syslog`

**Comment by itstamil** [comment]
Is that crontab is persistent on reboot

**Comment by kingsd041** [comment]
@itstamil  
It is not persistent after rebooting.
if you want to implement persistence you can do this:
1. Set cron dir with `crond -c /opt/crontabs/`
2. Set crontab
```
cat  /opt/crontabs/root
*/1 * * * *  /opt/sample.sh
```
3. Refer to [ros write-files](https://rancher.com/docs/os/v1.x/en/installation/configuration/write-files/)  and add `crond -c /opt/crontabs` to /etc/rc.local

**Comment by kingsd041** [comment]
This issue has not been updated within 50 days and I will close this issue.
If you still have doubts, please reopen it and let me know.
