### ISSUE TITLE
Question on supported combination of RKE, RancherOS, and Docker engine versions

### ISSUE THREAD

**Issue by sokratisg** [rancher/os#2660]
We've been trying to wrap our heads around version compatibility matrices among RKE, RancherOS and the supported Docker engines of each solution.

Taking into consideration the compatibility matrix of RKE (Rancher Kubernetes Engine) documented [here](https://rancher.com/docs/rke/v0.1.x/en/os/#software), it seems that Kubernetes stable release (1.11.x) supports up to Docker engine  17.03.2.

Taking into consideration issue #2300 and the latest [release notes of RancherOS 1.5.0](https://github.com/rancher/os/releases/tag/v1.5.0), it seems that things have progressed a lot since RancherOS supported Docker engine 17.03.2.

Do you believe it is sane to assume we can use RancherOS 1.5.0 but switching its Docker engine back to `docker-17.03.2-ce` via the relevant command? (`sudo ros engine enable docker-17.03.2-ce`) ?

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**

baremetal

**Comment by niusmallnan** [comment]
`sudo ros engine switch docker-17.03.2-ce`

**Comment by sokratisg** [comment]
Are you sure that if that command is run on a newly setup RancherOS 1.5.0, it won't break anything? 
I keep asking because of #2300

**Comment by niusmallnan** [comment]
@sokratisg Did you hit any problems?
You need to watch #2300 if you upgrade ros from an earlier version.

**Comment by sokratisg** [comment]
Haven't tested yet but please feel free to close this one. Will get back if something changes.
