### ISSUE TITLE
fail on ROCK64 (arm64)

### ISSUE THREAD

**Issue by j2l** [rancher/os#2661]
**RancherOS Version: (ros os version)**
https://releases.rancher.com/os/v1.5.0/arm64/rancheros-raspberry-pi64.zip

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
ROCK64 (ARM64)

No boot at all.

**Comment by niusmallnan** [comment]
You are using the RPi version, we never support ROCK64.

Looks like the rpi-bootloader which we used doesn't support ROCK64.

**Comment by j2l** [comment]
Thanks!
So, Portainer it is.
