### ISSUE TITLE
Need help to disable auto-login feature

### ISSUE THREAD

**Issue by itsmesridhar** [rancher/os#2662]
**RancherOS Version: 1.5.0**

**Where are you running RancherOS? baremetal**

In changelog for v1.5.0 you have described ( Auto-login disable feature enabled likewise). But we are not able found any documentation for that. Can you please help us to how to do that?

**Comment by Jason-ZW** [comment]
You can use `sudo ros config set rancher.disable ["autologin"]` then `reboot`.
We are waiting this document PR is ready to be merged. https://github.com/rancher/docs/pull/1101.

**Comment by itsmesridhar** [comment]
@Jason-ZW  Thanks, It works :+1:
