### ISSUE TITLE
Support for saving images and yaml from services_include in “ros install” process

### ISSUE THREAD

**Issue by mei-tech** [rancher/os#2670]
**RancherOS Version: (ros os version)**
1.5

Currently it isn't decribed how to enable system services in a cloud config file.
I would suggest to put it here: 
https://rancher.com/docs/os/v1.x/en/installation/system-services/adding-system-services/

I was unsure, how it actually works. So I had to activate it by `ros service enable qemu-guest-agent` command and exporting it with `ros config export` to see the actual outcome:
```
rancher:
  services_include:
    qemu-guest-agent: true
```

**Comment by niusmallnan** [comment]
Two conditions are required to enable a service:
1. Make a flag in ros config, which is `services_include`
2. Download the service's compose yaml and cache it in the system, this file will be stored in `/var/lib/rancher/cache`

`ros service enable` is the right way.

**Comment by justinkarabegovic** [comment]
When attempting to use cloud-config.yml as part of a ros install to disk process, it appears to download and cache the service into the live system, but will not install and cache it to the 'install to disk' target.

Is there some way to direct ros install to enable and install the service into the 'install to disk' target via the cloud-config.yml file?

**Comment by niusmallnan** [comment]
> When attempting to use cloud-config.yml as part of a ros install to disk process, it appears to download and cache the service into the live system, but will not install and cache it to the 'install to disk' target.

@justinkarabegovic Can you show me more details? It is best to have steps so that I don't misunderstand.


BTW, @Jason-ZW I think we can copy these service cache files to `/usr/share/ros/services-cache/` when using ros install. Need to ensure that they can be copied to the RANHER_STATE disk.

**Comment by justinkarabegovic** [comment]
@niusmallnan Thanks for responding to this.

I apologize, as I my response earlier may not have been very detailed.

My intention is to create a pre-packaged VM (or cloud image) with all appropriate system services pre-installed and enabled for operation.

As such, making a `services_include` flag in cloud-config.yml which is read by `ros install`, and then downloading the service's compose yaml and caching it in the installed system target `/var/lib/rancher/cache`, does not seem to achieve this target for me. This would appear to direct the installed target system to attempt to pull the image when the system is first booted, which is not the desired outcome. I would like the image to already be there and enabled to run upon initial boot.

My other option is to setup a post `ros install` set of commands that will perform a `ros service enable <service>` which will pull the image, but it pulls it into the live system, not the installation target used by `ros install`. 

I have not found documentation that provides flags in cloud-config.yml that would direct `ros install` to pull a service image and make it ready for operation in an installed target system. If such exists, then my apologies.

Perhaps there could be a set of cloud-config.yml flags that are only read by `ros install` and not all options are copied to the cloud-config.yml file that is placed into the installed target system. Maybe something like this:

    rancher:
         install:
              pull: https://example.com/os-services/v/virtualbox-tools.yml
         services_include:
              virtualbox-tools: true

This way it pulls the system image into the `/mnt/new_img` hierarchy and then enables the service in the installed target.

**Comment by chrisbalmer** [comment]
I've been trying to accomplish the same thing except I was able to preload the image but not get RancherOS to use it. Combining [image preloading](https://rancher.com/docs/os/v1.x/en/installation/boot-process/image-preloading/) with what you guys were discussing for the cache, I was able to get this to work for me.

These are the steps I'm using in a packer template to include open-vm-tools on my image while using the standard rancheros.iso:

    cat >cloud-config.yml<<EOF
    #cloud-config
    rancher:
      services_include:
        open-vm-tools: true
    EOF

    sudo ros install -d /dev/sda -f -c ./cloud-config.yml --no-reboot
    sudo mkdir /mnt/install
    sudo mount /dev/sda1 /mnt/install
    sudo mkdir -p /mnt/install/var/lib/rancher/preload/system-docker
    sudo mkdir /mnt/install/var/lib/rancher/cache
    sudo system-docker save rancher/os-openvmtools | xz > os-openvmtools.xz
    sudo mv os-openvmtools.xz /mnt/install/var/lib/rancher/preload/system-docker/
    sudo cp /var/lib/rancher/cache/* /mnt/install/var/lib/rancher/cache/

**Comment by rootwuj** [comment]
Tested with rancher/os:v1.5.2-rc1 from May 23
Validate by [case](https://github.com/rancher/os/pull/2765#issue-277634997), cache services_include resources in `ros install` process.
Verified fixed
