### ISSUE TITLE
Alpine Console 3.9

### ISSUE THREAD

**Issue by TBK** [rancher/os#2671]
Would it be possible to bump Alpine to 3.9 for the 1.5.1 stable release?

**Comment by niusmallnan** [comment]
Wow, we have shipped 1.5.1.
I will add it to the next milestone.

**Comment by TBK** [comment]
Super and thanks for the great work 👍 

I am hoping the stable 0.8.0 release of ZFS on Linux has dropped so we can get ZFS O_DIRECT as part of 1.6.0.

**Comment by rootwuj** [comment]
Tested with rancher/os:v1.5.2-rc1 from May 20
This version of the alpine console version is 3.9.4
Verified fixed
