### ISSUE TITLE
ZFS does not integrate with udev

### ISSUE THREAD

**Issue by dwaite** [rancher/os#2673]
When using zfs, devices and volumes do not appear underneath `/dev`. It appears this is due to the `udev` support for zfs not being available. In addition, the `udev` rules require helper applications `zvol_id` and `vdev_id`, which aren't built by the zfs container. For this reason, the solution doesn't appear to be as simple as moving the rules into the `udev` container.

---

**RancherOS Version: (ros os version)**
1.5.1

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
digitalocean

**Comment by rootwuj** [comment]
Tested with rancher/os:v1.5.2-rc1 from May 22
Verified fixed

Test:
```
$ sudo ros service enable zfs
$ sudo ros service up zfs
$ sudo zpool create zpool1 -m /mnt/zpool1 /dev/xxx
$ zfs create -V 128M -s zpool1/zvol
```
Result:
```
$ ls /dev/zvol
zpool1
```
