### ISSUE TITLE
Failed to build controlplane

### ISSUE THREAD

**Issue by kinolaev** [rancher/os#2675]
**RancherOS Version:**
1.5.1

**Where are you running RancherOS?**
 vmware vsphere provisioned with rancher

Hello!
I tried to recreate one of control node with rancherOS 1.5.1 but rancher failed to build controlplane. It stucks at pulling rancher/hyperkube:v1.11.2-rancher1. I tried to pull it manually and saw an error: no space left on device. I recreated node again using 1.5.0 with no errors.

Previously I successfully updated (also by recreating) 4 worker nodes from 1.5.0 to 1.5.1. They have >=8gb RAM, but control have only 4gb.

From `df -h`
```
overlay                   1.9G      1.8G     78.4M  96% /var/lib/docker/overlay/2070d94ababd68083c4c88d9ea8a020931ab7a7fc017261fe619acc0b7d8ef2b/merged
```

**Comment by kinolaev** [comment]
I don't see /dev/sda in output of blkid in rancheros 1.5.1, only /dev/sr0, on all nodes.

**Comment by kinolaev** [comment]
I downloaded 1.5.1 from https://releases.rancher.com/os/v1.5.1/vmware/rancheros.iso (from README.md). But now I see that you also have https://releases.rancher.com/os/v1.5.1/rancheros-vmware.iso (found in documentation site). This images has exact same size 150994944, but the second runs without errors!

**Comment by niusmallnan** [comment]
@kingsd041 
This is for booting from ISO:
https://releases.rancher.com/os/v1.5.1/vmware/rancheros.iso 

These are for docker-machine, also they can be used for vmware provisioned with rancher :
https://releases.rancher.com/os/v1.5.1/rancheros-vmware.iso
https://releases.rancher.com/os/v1.5.1/vmware/rancheros-autoformat.iso
And they the same, just the different links.

**Comment by kinolaev** [comment]
Sorry, this is my inattention, I see now “Special docker-machine Links” in readme.
