### ISSUE TITLE
Support for service cache updates

### ISSUE THREAD

**Issue by niusmallnan** [rancher/os#2677]
When we get services from `os-services` via `ros service`, ROS can download the files to cache, they will be saved to `/var/lib/rancher/cache`.

These caches are now unable to be updated, We should support updating the cached files.

We can add an option to `ros service list`, suck as:
```
$ ros service list --update
```
Also, need to apply `engine` and `console` and `os` index.

**Comment by rootwuj** [comment]
Tested with rancher/os:v1.5.2-rc1 from May 22

Run the following command can update the cache file (/var/lib/rancher/cache/), and other files are not affected.
*  sudo ros service list --update
*  sudo ros console list --update
*  sudo ros engine list --update
*  sudo ros os list --update

The following command can work with the updated cache file.

*  sudo ros service up
*  sudo ros console switch
*  sudo ros engine switch
*  sudo ros os upgrade

After the reboot or shutdown, everything went as expected.

Verified fixed
