### ISSUE TITLE
ros config merge broken from stdin on v1.5.1

### ISSUE THREAD

**Issue by riaan53** [rancher/os#2689]
**RancherOS Version: (ros os version)**
ros v1.5.1

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
virtualbox

On ros v1.5.0 I can pipe in ros config like this:
```
cat somefile.yaml | ros config merge
```

But on ros v1.5.1 I get the following error for the exact same command:
```
FATAL input parameter cannot be empty
```
It still works when loading the file via the `-i` argument but we are doing it programatically and writing a file first is not ideal.

**Comment by niusmallnan** [comment]
@kingsd041 Please add this function to our validation tests.

**Comment by rootwuj** [comment]
Tested with rancher/os:v1.5.2-rc1 from May 17
This version supports the `ros config merge` command.
Verified fixed
