### ISSUE TITLE
Validate ros cloud-config as much as possible

### ISSUE THREAD

**Issue by niusmallnan** [rancher/os#2693]
Now we can use `ros config validate` to to validate ros cloud-config,  this is not enough. In particular, the user manually modifies the config. If the wrong configuration is added, it may cause the startup to fail.

I think we need to enhance the experience and give users friendly tips.

Such as the following:
1. before the reboot or shutdown
2. before `ros  install -c `
3. others if needed

**Comment by rootwuj** [comment]
Tested with rancher/os:v1.5.2-rc1 from May 21
Verified fixed

Test:
* Set the wrong cloud-config
* Run the `reboot` or `shutdown` command
* Run `sudo ros install -c` 

Result:
* Display error message and command is not being run.
