### ISSUE TITLE
Support for pre-defined user images in the iso

### ISSUE THREAD

**Issue by niusmallnan** [rancher/os#2697]
Somebody wants to pre-defined images in the iso, which can address `offline` scenario.

Now we have supported `APPEND_SYSTEM_IMAGES`, it can save images to `/usr/share/ros/images-system.tar`, and loaded with system-docker when booting. There are a lot of demos in Makefile of `rancher/os`.

I will add another option `APPEND_USER_IMAGES`, it can save images to `/usr/share/ros/images-user.tar`. ~ROS will not load this image, you can deal with it by yourself.~ ROS can load this image with user-docker.
You can build ISO like this:
```
APPEND_USER_IMAGES="alpine ubuntu" make
```

Please note that these will be packaged into the initrd, and the predefined images will take up the resource footprint at startup.

**Comment by crochik** [comment]
@niusmallnan I do appreciate it! Just out of curiosity: is there any reason why we wouldn't want to make part of the "install" process to copy those to the preload folder?

**Comment by niusmallnan** [comment]
@crochik I see that you want an offline ISO with pre-defined images.
I think that it should be hard for you to get an ISO file, if adding pre-defined images to "install" process.

**Comment by rootwuj** [comment]
Tested with rancher/os:v1.5.2-rc1 from May 23

Step:
* Use `APPEND_USER_IMAGES="alpine ubuntu nginx" make` build ISO.
* Use this ISO to deploy offline environment.
* Validate `/usr/share/ros/images-user.tar` exist.
* Use `docker images` to validate that the pre-defined image has been loaded.
* Delete all user-docker images and validate that they can reload after reboot

Verified fixed.
