### ISSUE TITLE
Need to update RancherOS Documentation for Digital Ocean Installation 

### ISSUE THREAD

**Issue by shuo-wu** [rancher/os#2704]
**RancherOS Version: (ros os version)**
v1.5.1
**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
Digital Ocean

Now we can choose RancherOS image when creating droplets on Digital Ocean. This doc is out-of-date.
https://rancher.com/docs/os/v1.x/en/installation/running-rancheros/cloud/do/

**Comment by niusmallnan** [comment]
https://rancher.com/docs/os/v1.x/en/installation/running-rancheros/cloud/do/
