### ISSUE TITLE
Backup & restore docker swarm

### ISSUE THREAD

**Issue by x-jokay** [rancher/os#2709]
**RancherOS Version: (ros os version)**
RancherOS v1.5.1

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
Running in VMs, docker swarm

As described [here](https://success.docker.com/article/backup-restore-swarm-manager) we want to backup and restore a docker swarm.

How can this be done if using RancherOS on the nodes?
Especially point 3 "stopping docker engine" seems not possible 🤔 

Can `/var/lib/docker/swarm` be mounted directly on RancherOS as NFS share per node on boot or wouldn't you recommend it?

**Comment by Jason-ZW** [comment]
@x-jokay 
Using `system-docker stop docker` to stop user-scope docker engine in ROS.
Mounting '/var/lib/docker/swarm' per node.  I wouldn't do it if I were you.

**Comment by x-jokay** [comment]
@Jason-ZW thank you, this works and is exactly what we need 👍
