### ISSUE TITLE
v1.5.1 no wget

### ISSUE THREAD

**Issue by 3noki** [rancher/os#2711]
**RancherOS Version: 1.5.1**
**Digital Ocean droplet**

New Digital Ocean droplet, wget to install Elastic Search PGP Key, wget not found 

![image](https://user-images.githubusercontent.com/26792640/54213924-df1f2480-44aa-11e9-9301-42d298ece398.png)

**Comment by niusmallnan** [comment]
@3noki You are in Debian console, you can install wget.

**Comment by niusmallnan** [comment]
@3noki It is default console, not Debian console.

**Comment by kingsd041** [comment]
In the next release, the `wget` command is already supported in other consoles. https://github.com/rancher/os/issues/2720
