### ISSUE TITLE
Other consoles should support `ping` `wget` and `curl` commands

### ISSUE THREAD

**Issue by kingsd041** [rancher/os#2720]
We should support the `ping` `curl` `wget` command in other consoles.

#### The test results in RancherOS v1.5.1 are as follows:
**alpine console:**
- ping --support
- wget --support
- curl --support

**centos console:**
 - ping --support
 - wget --nonsupport
 - curl --support

**debian console:**
 - ping --support
- wget --nonsupport
- curl --support

**fedora console:**
- ping --nonsupport
- wget --nonsupport
- curl --support

**ubuntu console:**
- ping --nonsupport
- wget --nonsupport
- curl --support

**Comment by rootwuj** [comment]
Tested with rancher/os:v1.5.2-rc1 from May 20
This version of the other console support `ping` `wget` and `curl` commands.
Verified fixed
