### ISSUE TITLE
Fedora console sshd_config config file has duplicate `PermitRootLogin`

### ISSUE THREAD

**Issue by kingsd041** [rancher/os#2721]
**RancherOS Version: (ros os version)**
v1.5.1
**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
ALL

Fedora console sshd_config config file has duplicate `PermitRootLogin`
```
# grep -n '^PermitRootLogin' /etc/ssh/sshd_config
46:PermitRootLogin yes
154:PermitRootLogin no
```

**Comment by rootwuj** [comment]
Tested with rancher/os:v1.5.2-rc1 from May 20
This version of the fedora console sshd_config file is correct.
Verified fixed
