### ISSUE TITLE
Question, How to reset the user docker(wipe all user docker related files) when reboot

### ISSUE THREAD

**Issue by lygstate** [rancher/os#2727]
**RancherOS Version: (ros os version)**
1.5.x
**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
baremetal

I wanna reset the whole user-docker containers once restart, how to do that.

ps, do not remove the files in ~ HOME directory

**Comment by niusmallnan** [comment]
@lygstate You can try this:
```
system-docker stop docker
rm -rf /var/lib/docker/*
reboot
```

**Comment by lygstate** [comment]
@niusmallnan is there an point like /etc/rc.local that docker are not starting yet?
But obviously at /etc/rc.local, user docker is starting 
I can remove /var/lib/docker at that place.

**Comment by niusmallnan** [comment]
Try this:
```
wait-for-docker
system-docker stop docker
rm -rf /var/lib/docker/*
system-docker start docker
```

**Comment by lygstate** [comment]
@niusmallnan I means user docker not startted yet:)
So I can remove /var/lib/docker as early as possible:)

**Comment by lygstate** [comment]
@niusmallnan Anyway, thanks a lot, I've found the way remove /var/lib/docker as early as possible, even though may not the earliest:, just using
```
system-docker stop docker
rm -rf /var/lib/docker/ || true
system-docker start docker
````
in the file `/etc/rc.local`
