### ISSUE TITLE
/var/lib/kubelet/pods is empty

### ISSUE THREAD

**Issue by ipochi** [rancher/os#2734]
**RancherOS Version: (ros os version)**
v1.5.1
**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
baremetal

`/var/lib/kubelet/pods` directory is empty on both the worker nodes. There are workloads running on the node.

where is the equivalent in rancher OS ?

**Comment by contain-me-not** [comment]
On my RKE provisioned node, it is `/opt/rke/var/lib/kubelet/pods/`

**Comment by ipochi** [comment]
thanks. , that solved the problem I was having with Restic and Heptio Velero for backup
