### ISSUE TITLE
iSCSI for PXE diskless

### ISSUE THREAD

**Issue by ajcollett** [rancher/os#2737]
**RancherOS Version: (ros os version)**
v1.5.1
**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
baremetal, diskless ipxe booted server nodes.

Hello! First off, thanks to all who have worked on this. It's fantastic.

I work at a university (CS department), and would like to make use of RancherOS as well as rancher for our Kubernetes experiments (probably becoming a "production" env later on). 

I have some servers I'd like to boot via iPXE (working) that should persist their state to iSCSI disks. 

The problems I am facing are probably similar to most trying to do this. I'm not clear on where the capabilities lie currently, and what to do to get RancherOS to mount the remote iSCSI storage.

I have played around a fair amount already, so feel free to ask me to do some testing and so on.  I am also happy to help with any feedback needed for issue #2636

**Comment by niusmallnan** [comment]
Unfortunately, booting ROS via iPXE currently only supports local storage.

**Comment by ajcollett** [comment]
Thanks for the reply. I will then use Ubuntu for the nodes with no disks. They only have 8 Gig ram, so having ROS in memory and running loads might end up making them not very useful. Also, persistence is helpful for node reboots. I don't want to have to remove and add nodes each time a reboot is needed. 

This might be a really nice feature though. Especially for those who want to use infrastructure for a few different things. Like at the university, we could shut down a lab over night to run a massively parallel work load, simply by booting ROS from the network with some iSCSI persistence partitions. 

Also, it seems to me that Ubuntu being the base OS, vs booting PXE ROS, is a little faster/more stable in terms of deploying containers. Does that sounds right? Or should ROS be significantly faster, experientially?

**Comment by ajcollett** [comment]
So I discovered how to get the node to "persist" by keeping it's name the same. This seems to work well enough. I will therefore close this, but if it becomes a feature request for future, that wouldn't be a terrible thing.
