### ISSUE TITLE
Support for Ping An Cloud

### ISSUE THREAD

**Issue by niusmallnan** [rancher/os#2752]
Chinese insurance giant Ping An (Group) unveiled Ping An Cloud, a home-grown cloud computing service targeted at five industries, such as finance and health care.

Make RancherOS run on Ping An Cloud, which can be used by some enterprise users.

**Comment by kingsd041** [comment]
Tested with RancherOS v1.5.2-rc1
Upload [rancheros-pingan.img](https://github.com/rancher/os/releases/download/v1.5.2-rc1/rancheros-pingan.img) to PingAn cloud and RancherOS can run on PingAn cloud.

**Test the PingAn cloud function:**
- Create VM
- Network
- Instance status
- Instance setting
- Operation and maintenance management
- System settings
- volume
- ECS instance monitoring
- Switch console
- Switch docker engine
