### ISSUE TITLE
Upgrade open vm tools version to 10.3.10

### ISSUE THREAD

**Issue by khauser** [rancher/os#2763]
**RancherOS Version: (ros os version)**
1.5.1
**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
ESXi

This should fix our issue (https://github.com/vmware/open-vm-tools/issues/236) with vSphere Cloud Provider (https://github.com/rancher/os/issues/2548).

Is this possible?

Best,
Karsten

**Comment by Jason-ZW** [comment]
## My PR's result:
```
$ ./vmrun -T fusion -gu xxxx -gp xxxx createTempfileInGuest /Users/zhenyangzhao/.docker/machine/machines/rancheros-vmware/rancheros-vmware.vmx

> /tmp/vmware-docker_1504-4168354489/vmware117

$ ./vmrun -T fusion -gu xxxx -gp xxxx createTempfileInGuest /Users/zhenyangzhao/.docker/machine/machines/rancheros-vmware/rancheros-vmware.vmx

> /tmp/vmware-docker_1504-4168354489/vmware247
```

**Comment by rootwuj** [comment]
Tested with rancher/os:v1.5.2-rc1 from May 21

* The `openvmtools` version has been upgraded to 10.3.10-1
* Run `createTempfileInGuest` twice and run successfully.
* Then can connect to VM via ssh

Verified fixed
