### ISSUE TITLE
I'cant connect ssh 

### ISSUE THREAD

**Issue by TheYkk** [rancher/os#2768]
**RancherOS Version: (ros os version)**
v1.5.1
**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
Virtualbox

I try install rancheros to my disk. My stpes
- `wget https://gitlab.com/snippets/1856826/raw` (for cloud file)
- `sudo ros config merge -i file `
- `sudo ros install -d /dev/sda --append rancher.password=xxx`
- restart and remove disk from machine 
- boot and login with password

![image](https://user-images.githubusercontent.com/21688838/57721700-811ae300-768d-11e9-830f-60d3636d0e99.png)

![image](https://user-images.githubusercontent.com/21688838/57721688-782a1180-768d-11e9-8e8e-3632de01c4d9.png)

**Comment by niusmallnan** [comment]
What's the eth1 network in your VirtualBox? host-only or something else?
You are using the gateway IP on eth1.

**Comment by TheYkk** [comment]
host only network

**Comment by TheYkk** [comment]
brigged network solved problem
