### ISSUE TITLE
1.5.1 is not marked as the latest release

### ISSUE THREAD

**Issue by digitalsparky** [rancher/os#2771]
Hi folks, just giving you the heads up that 1.5.1 shows as a stable release in the releases tab on Github, however, 1.4.3 is listed as 'latest', so the link from the website subsequently serves an old version.

**Comment by niusmallnan** [comment]
It seems that the "latest release" is determined from the timestamps on the tags, not from the semantics of their names.
We first released 1.5.1 and then released 1.4.3, so this happened.
