### ISSUE TITLE
Add tftp datasource for cloud config

### ISSUE THREAD

**Issue by niusmallnan** [rancher/os#2774]
This allows for a tftp datasource for cloud-config. This is useful if you have an environment already setup for PXE booting and do not want to serve cloud-config via eg. HTTP.

Usage:
```
kernel ${base-url}/vmlinuz rancher.cloud_init.datasources=[tftp:1.2.3.4:69/cloud_config]
```

Port is optional and defaults to port 69.

**Comment by niusmallnan** [comment]
@kingsd041 We need an automated test for this function.

**Comment by kingsd041** [comment]
Ros 152-rc1 already supports TFTP as a datasource, I tested ipxe boot and install to disk, it works fine
