### ISSUE TITLE
Installation on disk could support password authentication on SSH

### ISSUE THREAD

**Issue by rhuanbarreto** [rancher/os#2784]
**RancherOS Version: Any**

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
Baremetal or VM.

The installation of rancherOS from an ISO could have the opportunity to have a password login for the rancher user instead of a ssh key.

**Comment by niusmallnan** [comment]
I realized that you can use  `ros install ... --append "rancher.password=xxxx"` to set the password.

**Comment by niusmallnan** [comment]
I realized that you can use  `ros install ... --append "rancher.password=xxxx"` to set the password.

**Comment by rhuanbarreto** [comment]
But if we use this then we don't need the config file anymore because there is no need to set SSH key for the image.

Updating the docs about it could be good also. This would simplify a lot the deployment for less advanced users that don't use terraform or other means of installing in bare metal or VM.

**Comment by boistordu** [comment]
Could we also precise in the documentation that after that the password is in global.cfg and can be changed by editing it with `sudo ros config syslinux` ?

**Comment by niusmallnan** [comment]
https://rancher.com/docs/os/v1.x/en/installation/configuration/adding-kernel-parameters/#user-password
