### ISSUE TITLE
Unable to boot any rancheros iso on esxi v6.7.0U2

### ISSUE THREAD

**Issue by nathankodilla** [rancher/os#2787]
**RancherOS Version: (ros os version)**
1.5.1
**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
ESXI vsphere

Have tried previous versions and different iso's such as the base rancheros.iso and rancheros-vmware.iso. None seem to be able to boot into when using ESXI. Other linux distro iso's boot fine.

![image](https://user-images.githubusercontent.com/22841858/58268121-db353b80-7d52-11e9-8f1b-0a1344c2724c.png)

**Comment by niusmallnan** [comment]
@nathankodilla Can you disable EFI and try to use legacy bios to boot?

**Comment by nathankodilla** [comment]
That fixed it. Thanks!
