### ISSUE TITLE
Docker not working after upgrade to 1.5.2

### ISSUE THREAD

**Issue by auras** [rancher/os#2797]
I have RancherOS running on bare metal.

I ran the upgrade to 1.5.2, it upgraded ok and prompted me to reboot. It started rebooting, was disconnected from ssh but it never reboot correctly. So I went and rebooted the machine manually.

After rebooting docker wasn't working. By that I mean no docker containers seem to be running and `docker ps` doesn't show anything and never returns, I have to hit CTRL+C to be able to do anything.

```

[rancher@rancher ~]$ docker ps
^C
[rancher@rancher ~]$ sudo system-docker logs docker
time="2019-06-01T12:04:57Z" level=info msg="Starting Docker in context: console"
time="2019-06-01T12:04:57Z" level=info msg="Getting PID for service: console"
time="2019-06-01T12:04:57Z" level=info msg="console PID 758"
time="2019-06-01T12:04:57Z" level=info msg="[PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin HOSTNAME=rancher HOME=/]"
time="2019-06-01T12:04:57Z" level=info msg="Running [system-docker-runc exec -- 16a8d34efe3416a7545299bafd8ee8725384edbb80c33204105a8720c5639631 env PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin HOSTNAME=rancher HOME=/ ros docker-init --log-opt max-file=2  --log-opt max-size=25m --group docker --host unix:///var/run/docker.sock]"
time="2019-06-01T12:04:57Z" level=info msg="Found /usr/bin/dockerd"

```

**Comment by auras** [comment]
Running `docker-18.06.3-ce`.

If I change the docker engine at runtime I get this:

```
[rancher@rancher log]$ sudo ros engine switch docker-18.06.2-ce
INFO[0011] Project [os]: Starting project
INFO[0011] [0/20] [docker]: Starting
Pulling docker (docker.io/rancher/os-docker:18.06.2)...
18.06.2: Pulling from rancher/os-docker
4b91cfc73f66: Pull complete
Digest: sha256:8883a26e0a3bbcc47fab6d39daa1a3f542715ff64681e9b9702555b0f8ae1a58
Status: Downloaded newer image for rancher/os-docker:18.06.2
INFO[0018] Recreating docker
INFO[0019] [1/20] [docker]: Started
INFO[0019] Project [os]: Project started
[rancher@rancher log]$ docker ps
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.38/containers/json: dial unix /var/run/docker.sock: connect: permission denied
```

**Comment by niusmallnan** [comment]
Duplicate of #2484
See this comment https://github.com/rancher/os/issues/2484#issuecomment-445088750

**Comment by niusmallnan** [comment]
I tried a fresh install, I cannot reproduce.
Can you provide more steps?
Which console? Which version did you upgrade from?

**Comment by auras** [comment]
I think I had 1.5.1 before. Which console? Bash?

I'm not saying it happens to everybody, but I would like to know how I can get docker working again.

**Comment by niusmallnan** [comment]
Please check this file ` /var/log/docker.log`, maybe you can find the reason.

**Comment by auras** [comment]
I'm guessing one or some of the containers got corrupted because after I removed the containers it works fine.
