### ISSUE TITLE
Disabling password auth / ufw / fail2ban

### ISSUE THREAD

**Issue by vitobotta** [rancher/os#2803]
Hi! I am trying out RancherOS 1.5.2 thinking of using it with Kubernetes. On my servers, I usually disable password auth, and configure both a firewall (ufw) as well as fail2ban at least for ssh. How can I do this with RancherOS? I have switched to the Ubuntu console because my understanding is that it enables persistence, but when I reboot the changes to the ssh config are lost and ufw/fail2ban are not started automatically. Thanks in advance

**Comment by niusmallnan** [comment]
If you have switched to the Ubuntu console, you can update `/etc/ssh/sshd_config.tpl`.

There is no ufw/fail2ban in ROS, you can load the iptables rules via `runcmd` directly.

**Comment by vitobotta** [comment]
Thanks. That's a little limiting, I thought I could do at least these things more easily.
