### ISSUE TITLE
Automatically switch to console on install

### ISSUE THREAD

**Issue by vitobotta** [rancher/os#2812]
**RancherOS Version: (ros os version)**

1.5.2

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**

Hetzner Cloud

Hi! I have installed RancherOS with a config file (`-c` parameter) that specifies I want to use the ubuntu console in the `rancher` section, as shown [here](https://rancher.com/docs/os/v1.x/en/installation/configuration/switching-consoles/). 

The ubuntu console is enabled, but I have to switch to it manually. Is this expected?

Thanks

**Comment by niusmallnan** [comment]
Not my expected.
This should be caused by networking missing, you can check this file `/var/log/boot/ros-sysinit.log`.
It can be confirmed if you get these logs:
```
[root@rancher rancher]# cat /var/log/boot/ros-sysinit.log | grep error
time="2019-06-17T05:20:30Z" level=error msg="Get https://raw.githubusercontent.com/rancher/os-services/v1.5.2-rc1/u/ubuntu.yml: dial tcp: lookup raw.githubusercontent.com on [::1]:53: read udp [::1]:60332->[::1]:53: read: connection refused"
time="2019-06-17T05:20:30Z" level=error msg="Failed to load rancher.console=(ubuntu): Get https://raw.githubusercontent.com/rancher/os-services/v1.5.2-rc1/u/ubuntu.yml: dial tcp: lookup raw.githubusercontent.com on [::1]:53: read udp [::1]:60332->[::1]:53: read: connection refused"
```

**Comment by kingsd041** [comment]
Version: rancheros v1.5.3-rc1
Confirmed issue. This is now working as expected per the comments here and the PR.
During the start of rancheros, it will wait for the NIC to boot successfully before executing the switch console.
![image](https://user-images.githubusercontent.com/19684717/60710207-bd0f4d80-9f44-11e9-8af1-c1ddd47fbe66.png)
