### ISSUE TITLE
Rancher prefers IPV4 over V6

### ISSUE THREAD

**Issue by majkrzak** [rancher/os#2819]
**RancherOS Version: (ros os version)**
v1.5.2
**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
baremetal

I've setted up rancher on non ipv4 environment. Now I have plenty of problems due to that A record is proffered over AAAA. Basically no single web request work due to that reason.

For example command fails

    [docker@vps ~]$ sudo ros engine list
    ERRO[0000] Failed to load https://raw.githubusercontent.com/rancher/os-services/v1.5.2/index.yml: Get https://raw.githubusercontent.com/rancher/os-services/v1.5.2/index.yml: dial tcp 151.101.0.133:443: connect: network is unreachable 

:man_facepalming: ther is no AAAA records on raw.githubusercontent.com

**Comment by niusmallnan** [comment]
Close this one, you can track https://github.com/rancher/os/issues/2820
