### ISSUE TITLE
make vmware kvm 

### ISSUE THREAD

**Issue by axi92** [rancher/os#2862]
I run "make vmware" and it runs untill this line:
https://github.com/rancher/os/blob/18b2fe50aff4f892d7746f24bd65ffce65255e34/scripts/release-vmware#L48

With the output:
```
xorriso : UPDATE :  91.08% done
ISO image produced: 72704 sectors
Written to medium : 72704 sectors at LBA 0
Writing to 'stdio:/go/src/github.com/rancher/os/dist/artifacts/rancheros.iso' completed successfully.

++ dirname /go/src/github.com/rancher/os/dist/artifacts/rancheros.iso
+ cd /go/src/github.com/rancher/os/dist/artifacts
+ touch dist/publish.sh dist/publish_gss_ba2cfe89-dirty.sh dist/publish_gss_latest.sh
+ chmod 755 dist/publish.sh dist/publish_gss_ba2cfe89-dirty.sh dist/publish_gss_latest.sh
+ '[' false = true ']'
+ mkdir -p /tmp/dist/openstack/latest ./dist/vmware
+ cat
+ rm -f /tmp/dist/success
+ qemu-img create -f qcow2 ./dist/vmware/vmdk.img 8G
Formatting './dist/vmware/vmdk.img', fmt=qcow2 size=8589934592 cluster_size=65536 lazy_refcounts=off refcount_bits=16
+ kvm -curses -drive if=virtio,file=./dist/vmware/vmdk.img -cdrom ./dist/artifacts/rancheros.iso -m 4096 -cpu host -fsdev local,id=conf,security_model=none,path=/tmp/dist -device virtio-9p-pci,fsdev=conf,mount_tag=config-2 -device virtio-rng-pci
We need a terminal output
time="2019-08-12T14:40:15+02:00" level=fatal msg="exit status 1"
```

Any ideas how to "fix" that.

**Comment by niusmallnan** [comment]
There is a workaround that you can try:
```
APPEND_SYSTEM_IMAGES="rancher/os-openvmtools:10.3.10-1" make shell-bind
./script/release-vmware
exit
```

**Comment by niusmallnan** [comment]
It seems that I found the root cause. 

The `kvm -curses` can experience qemu output on terminal, but our dapper tool disabled the `tty` by default. The previous behavior is not the case, it may be a problem introduced by dapper update.

We can append `-it` to `DAPPER_RUN_ARGS` in the `Dockerfile.dapper`.
```
ENV DAPPER_RUN_ARGS --privileged -it
```

**Comment by axi92** [comment]
The kvm starts and rancheros boots with autologin but then nothing else is happening?
After 5min or so I shut down the kvm.

Right now I try your first workaround with APPEND_SYSTEM_IMAGES.
I will edit my post and append the logs.

**Comment by niusmallnan** [comment]
Please clean your workdir with `git clean -dxf`, then run `make`.

**Comment by axi92** [comment]
I cleaned my workdir with `git clean -dxf` and then `make vmware`
And got the same output as before with RancherOS autologin and then nothing else happens.

**Comment by niusmallnan** [comment]
@axi92 Can you try `grep -cw vmx /proc/cpuinfo` to check if your host can support kvm?
The result needs to be greater than 0.

**Comment by axi92** [comment]
```grep -cw vmx /proc/cpuinfo
0
```
```kvm-ok
INFO: /dev/kvm exists
KVM acceleration can be used
```
I am confused...

**Comment by niusmallnan** [comment]
On my setup, I can build the vmware artifacts with the latest upstream.
```
grep -cw vmx /proc/cpuinfo
4
```

```
Formatting './dist/vmware/vmdk.img', fmt=qcow2 size=8589934592 cluster_size=65536 lazy_refcounts=off refcount_bits=16
+ kvm -curses -drive if=virtio,file=./dist/vmware/vmdk.img -cdrom ./dist/artifacts/rancheros.iso -m 2048 -fsdev local,id=conf,security_model=none,path=/tmp/dist -device virtio-9p-pci,fsdev=conf,mount_tag=conf
ig-2 -device virtio-rng-pci
+ '[' -f /tmp/dist/success ']'
+ echo 'Converting ./dist/rancheros.vmdk'
Converting ./dist/rancheros.vmdk
+ qemu-img convert -f qcow2 -O vmdk ./dist/vmware/vmdk.img ./dist/artifacts/rancheros.vmdk
```

**Comment by axi92** [comment]
I was on v1.5.3
Now I switched to master and it worked.
I tried to build the v1.5.3 release with some changes in the os-config.tpl.yml

**Comment by axi92** [comment]
Ok after some investigation I found out that when I checkout the master and build it with `make vmware` it works. And it builds as 1.5.4 RC1.
As soon as I change one line in the os-config.tpl.yml it builds an -dirty build and get stuck in the VM after the autologin.
My only change was to change the cloudinit datasource to an url instead of configdrive:
```
  cloud_init:
    datasources:
     - url:https://url.cloud/1.yml
#    - configdrive:/media/config-2
```

**Comment by niusmallnan** [comment]
@axi92 Don't comment out the `configdrive` datasource, `make vmware` needs it to build the vmdk file.
You can check these code lines
https://github.com/rancher/os/blob/eccf9554c86ffa33057027610b015337c05f2a5a/scripts/release-vmware#L26-L54

Your changes make user_data not work.

**Comment by axi92** [comment]
Ah I see.
And one last question how do I build the rancheros-vmware.**iso** like in the release on github?

**Comment by niusmallnan** [comment]
To get the vmdk, and `rancheros-vmware.iso` for booting from ISO.
```
make vmware
```

To get the `rancheros-vmware-autoformat.iso` which is used to docker-machine.
```
OS_AUTOFORMAT=true make vmware
```

You can get the artifacts from `./dist/artifacts/`.
