### ISSUE TITLE
Use the http retry mechanism when loading service yaml files

### ISSUE THREAD

**Issue by niusmallnan** [rancher/os#2872]
ROS can try to download the yaml file of os-service when booting, there is a chance that it will fail, because http get will only be called once. For example, these scenarios:
```
ros c set rancher.docker.engine xxxx
reboot
```
Or
```
ros c set rancher.console ubuntu
reboot
```
We need to add the http retry mechanism to do our best to download the yaml file.

**Comment by kingsd041** [comment]
In case of unstable network, it will try again to download YAML file 3 times.
