### ISSUE TITLE
inconsistent ros engine list

### ISSUE THREAD

**Issue by ohauer** [rancher/os#2898]
**RancherOS Version: 1.5.4**

**Where are you running RancherOS? vSphere**

I've notice an inconsistent between upgraded os e.g. from 1.5.3 -> 1.5.4 and a fresh install
On the upgraded os engine offers docker-19.03.**[0-2]** but on a system installed from 1.5.4 it offers only docker-19.03.**[0-1]**.

Is there a way to update the list of current supported engines?

**Comment by niusmallnan** [comment]
Please try: `ros engine list --update`

**Comment by ohauer** [comment]
Oh, I've overlooked the param. 
Thanks for the hint!
