### ISSUE TITLE
Cloud-init not accepting network settings normaly made on the bottom of docker-compose file

### ISSUE THREAD

**Issue by bd8392** [rancher/os#2900]
**RancherOS Version: (ros os version)**
latest
**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
Virtualbox

How do you configure docker-networks in rancheros, normally made on the bottom of the docker-compose file? rancheros doesn't seem to accept them...

example:

networks:
  proxy:
    external: true
  internal:
    external: false

**Comment by niusmallnan** [comment]
The compose in ROS is not a complete docker-compose, it is rancher-compose, which cuts down some unnecessary features.
You may need this if you want to use the full docker-compose feature.
https://hub.docker.com/r/docker/compose

**Comment by bd8392** [comment]
Ok I see...you ever tried setting up traefik within rancher compose? are the containers in rancher-compose able to communicate to each other? Because as I tried to setup traefik, the logs always show: (ip adress of the container not found). Thats why I tried the approach with network settings...do you have another ideas? Because I want to set everything in one place and cloud-init is the most innovative way I've ever seen to do this...and rancher-compose also has some advantages to docker-compose.

**Comment by bd8392** [comment]
resolved...it was missconfiguration of traefik. the only thing remaining is: https://github.com/rancher/os/issues/2776
