### ISSUE TITLE
udev rules doesn't work

### ISSUE THREAD

**Issue by ShenJunNeo** [rancher/os#2904]
**RancherOS Version: (ros os version)**
1.4.1 , and acutally tried in 1.5.4 too.
**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
baremetal hw without persistent data to hard disk .i.e  a memory system

After ssh into rancher, i added a new rule in /etc/udev/rules.d/79-device-automount.rules
Only one line:
KERNEL=="sd*", RUN+="/bin/bash -c '(touch /tmp/kkk.txt)&'"

file is owned by root.
[root@rancher ~]# ls -l /etc/udev/rules.d/79-device-automount.rules 
-rw-r--r--    1 root     root           358 Sep 26 06:15 /etc/udev/rules.d/79-device-automount.rules

Then reload the udev via:
sudo udevadm control --reload-rules && sudo service udev restart && sudo udevadm trigger

Then test it via udevadm. it works.
[root@rancher rules.d]# udevadm test $(udevadm info -q path -n /dev/sdh)
calling: test
version 3.2.5
This program is for debugging only, it does not run any program
specified by a RUN key. It may show incorrect results, because
some values may be different, or not available at a simulation run.

/etc/udev/hwdb.bin does not exist, please run udevadm hwdb --update
Load module index
timestamp of '/etc/udev/rules.d' changed
timestamp of '/usr/lib/udev/rules.d' changed
Skipping overridden file: /usr/lib/udev/rules.d/80-net-name-slot.rules.
Skipping overridden file: /usr/lib/udev/rules.d/79-device-automount.rules.
Reading rules file: /usr/lib/udev/rules.d/50-udev-default.rules
Reading rules file: /usr/lib/udev/rules.d/60-block.rules
Reading rules file: /usr/lib/udev/rules.d/60-cdrom_id.rules
Reading rules file: /usr/lib/udev/rules.d/60-drm.rules
Reading rules file: /usr/lib/udev/rules.d/60-evdev.rules
Reading rules file: /usr/lib/udev/rules.d/60-persistent-alsa.rules
Reading rules file: /usr/lib/udev/rules.d/60-persistent-input.rules
Reading rules file: /usr/lib/udev/rules.d/60-persistent-storage-tape.rules
Reading rules file: /usr/lib/udev/rules.d/60-persistent-storage.rules
Reading rules file: /usr/lib/udev/rules.d/60-persistent-v4l.rules
Reading rules file: /usr/lib/udev/rules.d/60-sensor.rules
Reading rules file: /usr/lib/udev/rules.d/60-serial.rules
Reading rules file: /usr/lib/udev/rules.d/64-btrfs.rules
Reading rules file: /usr/lib/udev/rules.d/70-mouse.rules
Reading rules file: /usr/lib/udev/rules.d/70-touchpad.rules
Reading rules file: /usr/lib/udev/rules.d/75-net-description.rules
Reading rules file: /usr/lib/udev/rules.d/75-probe_mtd.rules
Reading rules file: /usr/lib/udev/rules.d/78-sound-card.rules
Reading rules file: /etc/udev/rules.d/79-device-automount.rules
Reading rules file: /usr/lib/udev/rules.d/80-drivers.rules
Skipping empty file: /etc/udev/rules.d/80-net-name-slot.rules
rules contain 24576 bytes tokens (2048 * 12 bytes), 7835 bytes strings
1022 strings (13429 bytes), 641 de-duplicated (5976 bytes), 382 trie nodes used
GROUP 6 /usr/lib/udev/rules.d/50-udev-default.rules:57
IMPORT 'scsi_id --export --whitelisted -d /dev/sdh' /usr/lib/udev/rules.d/60-persistent-storage.rules:46
starting 'scsi_id --export --whitelisted -d /dev/sdh'
'scsi_id --export --whitelisted -d /dev/sdh'(out) 'ID_SCSI=1'
'scsi_id --export --whitelisted -d /dev/sdh'(out) 'ID_VENDOR=DELL'
'scsi_id --export --whitelisted -d /dev/sdh'(out) 'ID_VENDOR_ENC=DELL'
'scsi_id --export --whitelisted -d /dev/sdh'(out) 'ID_MODEL=PERC_H710'
'scsi_id --export --whitelisted -d /dev/sdh'(out) 'ID_MODEL_ENC=PERC\x20H710'
'scsi_id --export --whitelisted -d /dev/sdh'(out) 'ID_REVISION=3.13'
'scsi_id --export --whitelisted -d /dev/sdh'(out) 'ID_TYPE=disk'
'scsi_id --export --whitelisted -d /dev/sdh'(out) 'ID_SERIAL=36b083fe0dcda020024ffb53c0a51d002'
'scsi_id --export --whitelisted -d /dev/sdh'(out) 'ID_SERIAL_SHORT=6b083fe0dcda020024ffb53c0a51d002'
'scsi_id --export --whitelisted -d /dev/sdh'(out) 'ID_WWN=0x6b083fe0dcda0200'
'scsi_id --export --whitelisted -d /dev/sdh'(out) 'ID_WWN_VENDOR_EXTENSION=0x24ffb53c0a51d002'
'scsi_id --export --whitelisted -d /dev/sdh'(out) 'ID_WWN_WITH_EXTENSION=0x6b083fe0dcda020024ffb53c0a51d002'
'scsi_id --export --whitelisted -d /dev/sdh'(out) 'ID_SCSI_SERIAL=0002d0510a3cb5ff240002dadce03f08'
'scsi_id --export --whitelisted -d /dev/sdh' [42826] exit with return code 0
LINK 'disk/by-id/scsi-36b083fe0dcda020024ffb53c0a51d002' /usr/lib/udev/rules.d/60-persistent-storage.rules:48
IMPORT builtin 'path_id' /usr/lib/udev/rules.d/60-persistent-storage.rules:66
LINK 'disk/by-path/pci-0000:03:00.0-scsi-0:2:7:0' /usr/lib/udev/rules.d/60-persistent-storage.rules:68
IMPORT builtin 'blkid' /usr/lib/udev/rules.d/60-persistent-storage.rules:83
probe /dev/sdh raid offset=0
LINK 'disk/by-uuid/a0365d35-9928-4b12-9bbc-38c45c24bcb9' /usr/lib/udev/rules.d/60-persistent-storage.rules:86
LINK 'disk/by-label/data8' /usr/lib/udev/rules.d/60-persistent-storage.rules:87
LINK 'disk/by-id/wwn-0x6b083fe0dcda020024ffb53c0a51d002' /usr/lib/udev/rules.d/60-persistent-storage.rules:90
IMPORT builtin 'btrfs' /usr/lib/udev/rules.d/64-btrfs.rules:8
RUN '/bin/bash -c '(touch /tmp/kkk.txt)&'' /etc/udev/rules.d/79-device-automount.rules:1
handling device node '/dev/sdh', devnum=b8:112, mode=0660, uid=0, gid=6
preserve permissions /dev/sdh, 060660, uid=0, gid=6
preserve already existing symlink '/dev/block/8:112' to '../sdh'
found 'b8:112' claiming '/run/udev/links/\x2fdisk\x2fby-id\x2fscsi-36b083fe0dcda020024ffb53c0a51d002'
creating link '/dev/disk/by-id/scsi-36b083fe0dcda020024ffb53c0a51d002' to '/dev/sdh'
preserve already existing symlink '/dev/disk/by-id/scsi-36b083fe0dcda020024ffb53c0a51d002' to '../../sdh'
found 'b8:112' claiming '/run/udev/links/\x2fdisk\x2fby-id\x2fwwn-0x6b083fe0dcda020024ffb53c0a51d002'
creating link '/dev/disk/by-id/wwn-0x6b083fe0dcda020024ffb53c0a51d002' to '/dev/sdh'
preserve already existing symlink '/dev/disk/by-id/wwn-0x6b083fe0dcda020024ffb53c0a51d002' to '../../sdh'
found 'b8:112' claiming '/run/udev/links/\x2fdisk\x2fby-label\x2fdata8'
creating link '/dev/disk/by-label/data8' to '/dev/sdh'
preserve already existing symlink '/dev/disk/by-label/data8' to '../../sdh'
found 'b8:112' claiming '/run/udev/links/\x2fdisk\x2fby-path\x2fpci-0000:03:00.0-scsi-0:2:7:0'
creating link '/dev/disk/by-path/pci-0000:03:00.0-scsi-0:2:7:0' to '/dev/sdh'
preserve already existing symlink '/dev/disk/by-path/pci-0000:03:00.0-scsi-0:2:7:0' to '../../sdh'
found 'b8:112' claiming '/run/udev/links/\x2fdisk\x2fby-uuid\x2fa0365d35-9928-4b12-9bbc-38c45c24bcb9'
creating link '/dev/disk/by-uuid/a0365d35-9928-4b12-9bbc-38c45c24bcb9' to '/dev/sdh'
preserve already existing symlink '/dev/disk/by-uuid/a0365d35-9928-4b12-9bbc-38c45c24bcb9' to '../../sdh'
created db file '/run/udev/data/b8:112' for '/devices/pci0000:00/0000:00:02.2/0000:03:00.0/host0/target0:2:7/0:2:7:0/block/sdh'
ACTION=add
DEVLINKS=/dev/disk/by-id/scsi-36b083fe0dcda020024ffb53c0a51d002 /dev/disk/by-id/wwn-0x6b083fe0dcda020024ffb53c0a51d002 /dev/disk/by-label/data8 /dev/disk/by-path/pci-0000:03:00.0-scsi-0:2:7:0 /dev/disk/by-uuid/a0365d35-9928-4b12-9bbc-38c45c24bcb9
DEVNAME=/dev/sdh
DEVPATH=/devices/pci0000:00/0000:00:02.2/0000:03:00.0/host0/target0:2:7/0:2:7:0/block/sdh
DEVTYPE=disk
ID_BTRFS_READY=1
ID_BUS=scsi
ID_FS_LABEL=data8
ID_FS_LABEL_ENC=data8
ID_FS_TYPE=btrfs
ID_FS_USAGE=filesystem
ID_FS_UUID=a0365d35-9928-4b12-9bbc-38c45c24bcb9
ID_FS_UUID_ENC=a0365d35-9928-4b12-9bbc-38c45c24bcb9
ID_FS_UUID_SUB=021d109e-69a3-4e43-83ed-d714f96cc08f
ID_FS_UUID_SUB_ENC=021d109e-69a3-4e43-83ed-d714f96cc08f
ID_MODEL=PERC_H710
ID_MODEL_ENC=PERC\x20H710
ID_PATH=pci-0000:03:00.0-scsi-0:2:7:0
ID_PATH_TAG=pci-0000_03_00_0-scsi-0_2_7_0
ID_REVISION=3.13
ID_SCSI=1
ID_SCSI_SERIAL=0002d0510a3cb5ff240002dadce03f08
ID_SERIAL=36b083fe0dcda020024ffb53c0a51d002
ID_SERIAL_SHORT=6b083fe0dcda020024ffb53c0a51d002
ID_TYPE=disk
ID_VENDOR=DELL
ID_VENDOR_ENC=DELL
ID_WWN=0x6b083fe0dcda0200
ID_WWN_VENDOR_EXTENSION=0x24ffb53c0a51d002
ID_WWN_WITH_EXTENSION=0x6b083fe0dcda020024ffb53c0a51d002
MAJOR=8
MINOR=112
SUBSYSTEM=block
USEC_INITIALIZED=38705827
run: '/bin/bash -c '(touch /tmp/kkk.txt)&''
Unload module index
[root@rancher rules.d]# 

But if i really plugout/plugin a device, i can NOT see kkk.txt file in /tmp
[root@rancher rules.d]# ls /tmp
[root@rancher rules.d]# 

If i move the rules into system-docker container udev, then it does work.   But i don't want to change udev.  What shall i do?

**Comment by Jason-ZW** [comment]
Try `ros udev-settle` after adding a new rule.

**Comment by ShenJunNeo** [comment]
Great!   It works.   Thank you very much.
