### ISSUE TITLE
[os-vagrant] guest tools should not be deployed

### ISSUE THREAD

**Issue by xinity** [rancher/os#294]
i tried to play with os-vagrant , and while i was doing a "vagrant up", i had this strange message:
"No installation found.
The guest's platform is currently not supported, will try generic Linux method...
Copy iso file /usr/share/virtualbox/VBoxGuestAdditions.iso into the box /tmp/VBoxGuestAdditions.iso
stdin: is not a tty
mount: Could not find any loop device. Maybe this kernel does not know
       about the loop device? (If so, recompile or `modprobe loop'.)"

my guess is that these GuestAdditions are not necessary, am i wrong ?

**Comment by imikushin** [comment]
We've recently released RancherOS v0.3.3. Can you try to `vagrant up` off a fresh clone of `https://github.com/rancherio/os-vagrant.git`?

**Comment by deniseschannon** [comment]
@xinity I have had no issues with doing a fresh clone of the repo and doing a `vagrant up` and logging in. Please see if you still have the same issues. If so, please re-open the issue.
