### ISSUE TITLE
Increase retry attempts when downloading service yaml files

### ISSUE THREAD

**Issue by niusmallnan** [rancher/os#2941]
**RancherOS Version: (ros os version)**
v1.5.4

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
ALL

From netconfig.log it is shown that the nameserver record was written at 12:47:47:
```
time="2019-12-05T12:47:47Z" level=info msg="writing to /etc/resolv.conf: nameservers: [10.210.252.128 10.194.252.128], search: []" 
time="2019-12-05T12:47:47Z" level=debug msg="Resolve.conf == [nameserver 10.210.252.128
nameserver 10.194.252.128
], <nil>" 
```

This means that the resolution of domain pulp.unix.bank.local could not work before ​12:47:47, but the logs also show RancherOS trying to download service yaml files at this time.
```
time="2019-12-05T12:47:45Z" level=debug msg="start trying LoadFromNetwork(http://pulp.unix.bank.local/rancher/os-services/v1.5.4/o/open-vm-tools.yml)" 
time="2019-12-05T12:47:45Z" level=debug msg="Fetching data from http://pulp.unix.bank.local/rancher/os-services/v1.5.4/o/open-vm-tools.yml. Attempt #1"
...
...
time="2019-12-05T12:47:47Z" level=error msg="failed to LoadFromNetwork: Unable to fetch data. Maximum retries reached: 3" 
time="2019-12-05T12:47:47Z" level=error msg="Unable to fetch data. Maximum retries reached: 3" 
```

We should increase the default number of retries, which should mitigate this problem.

**Comment by kingsd041** [comment]
In rancheros v1.5.5-rc1, we have added the `rancher.http_load_retries: 6` parameter to resolve this issue
