### ISSUE TITLE
High minimum memory requirement

### ISSUE THREAD

**Issue by far-blue** [rancher/os#295]
Despite the small distribution size of rancherOs, it has a very high ram requirement. It should be entirely possible to run the OS and do something useful in 256Mb ram (I have happily setup mail servers and small web servers using ubuntu server edition in this much ram). The problem would appear to be at least partly due to the large rootfs filesystem of over 400Mb, despite the fact only 86Mb is used (on a fresh install). Most other linux distro's will switch from rootfs to mounted media early on in the boot process (commonly called 'switch_root') although I guess that would make atomic core updates harder to orchestrate. However it is done, booting with 256Mb ram is something rancherOs should support.

**Comment by frol** [comment]
Yeah, that what I have bumped in also. The error message is also weird: "no space left on device" and kernel panic right after this. http://www.awesomescreenshot.com/image/202326/e797a32373ecfa94a2b258cfb440a3d1

**Comment by ibuildthecloud** [comment]
It should be possible to eventually run rancheros from 256mb.  The only reason that is not possible is that we don't do a pivot root to disk to free the initrd.  We will do this though because it causes other issues with docker.

This is a valid bug.  This is important to me that we fix this.

**Comment by ibuildthecloud** [comment]
@frol The "no space left on device" is because it can't expand the initrd which is quite large unexpanded.  This will be fixed too.

**Comment by frol** [comment]
@ibuildthecloud I do understand it now, but at first I was really confused.

**Comment by nlhkh** [comment]
Has this been addressed in the latest release of rancherOS v0.3.3? I think the nice thing about RancherOS is that it's only 20MB, but it uses quite a lot of RAM even just for the master. So I wonder if I can just provision a normal machine with Docker (on DigitalOcean prebuilt image for e.g.), and have Rancher server running on it. This way even though it requires more disc (which is still cheaper than RAM), but less RAM.

**Comment by ibuildthecloud** [comment]
@nlhkh  This has been addressed in RancherOS v0.4.  Boot will still need around ~300 mb but after boot is done RancherOS only takes up about ~80mb or less of memory.  This is assuming you are running from disk.  Rancher Server does require 1gb minimum of memory though (actually uses less than that, but under load can balloon up quite a bit, we are working on getting that down).

**Comment by Petoj87** [comment]
Does Rancher Server still require 1gb? or have you been able to lower that amount?

**Comment by deniseschannon** [comment]
The minimum requirement is now at 512MB, but if you try to run `sudo ros install`, it requires 1 GB in order to download the image and run. 

https://github.com/rancher/os/issues/658

**Comment by imaia** [comment]
Had a "Apply Layer exec/fork: cannot allocate memory stdout:  stderrr:" in a 512mb ram kvm with RancherOS v0.6.1. Just saying ...

**Comment by joshwget** [comment]
@imaia Were you running RancherOS from memory when this occurred? Did it occur during boot or when you were performing some action after it was booted?

**Comment by imaia** [comment]
From memory. I was booting RancherOS in the vm. "sudo ros install" was not called. Boot never finished.

**Comment by joshwget** [comment]
I'm able to boot with 512mb when running from memory, but we might be on right on the border. If not running from memory, 512mb is still enough to run RancherOS.

Memory usage was actually marked as a known issue with v0.6. We're looking to improve this in future releases.
