### ISSUE TITLE
[os-base] openssl is not available

### ISSUE THREAD

**Issue by cmonty14** [rancher/os#2955]
**RancherOS Version: (ros os version)**
v1.5.5
**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
Proxmox VE KVM

Hello,
for the installation of HELM I need either curl or wget with SSL support.

I've added curl with this command `echo 'docker run --rm radial/busyboxplus:curl curl $@' > /usr/bin/curl && chmod +x /usr/bin/curl`, however it's not working correctly, means no files are stored locally.
Therefore I need to rely on wget, however there's no SSL support due to binary openssl missing:
```
[root@vm181-rancheros bin]# openssl
bash: openssl: command not found
```

Can you please advise how to fix this?
Ideally both curl and wget are working w/o restriction.

THX

**Comment by ingenieurmt** [comment]
@cmonty14 Why are you not using a Docker image for Helm? Get a pre-built image or write your own Dockerfile. RancherOS is entirely Docker containers, you absolutely shouldn't be installing things directly on the console as the console is in fact its own Docker container.

**Comment by cmonty14** [comment]
Well, the installation [instructions](https://rancher.com/docs/rancher/v2.x/en/installation/ha/) are not clear here.
It says "The following CLI tools are required for this install. Please make sure these tools are installed and available in your $PATH" and the link points to HELM binary files.

I will continue with Docker image for Helm.
