### ISSUE TITLE
[solved] [os-base] Cannot extract .tar.gz files

### ISSUE THREAD

**Issue by cmonty14** [rancher/os#2956]
**RancherOS Version: (ros os version)**
v1.5.5
**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
Proxmox VE KVM

I cannot extract .tar.gz which is impacting package installatin.
Please advise how to fix this.

THX

**Comment by ingenieurmt** [comment]
@cmonty14 RancherOS isn't a standard Linux distribution, you generally can't simply "install a package" in the manner you're describing. You may want to do a little more reading about Docker, how RancherOS leverages it and what RancherOS' intended function is.

If you really need to extract .tar.gz files at the console, you may wish to try [switching consoles](https://rancher.com/docs/os/v1.x/en/installation/configuration/switching-consoles/). This may yield the results you're looking for.

**Comment by cmonty14** [comment]
Thanks for your advise.
This issue is solved.
