### ISSUE TITLE
Need to reboot to synchronise NTP

### ISSUE THREAD

**Issue by NM4** [rancher/os#2997]
**RancherOS Version: (ros os version)**
1.5.5
**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
VMware

I'm facing an issue with ntp configuration. 

I modify the cloud-config with the appropriate values, I stop start the ntp service  but after that the date-time still unsynchronised.
But if I restart the VM, the synchronisation is done.

**Comment by xeor** [comment]
* create your ntp.conf to merge

```
write_files:
- container: ntp
  path: /etc/ntp.conf
  permissions: "0644"
  owner: root
  content: |
    server time1.no iburst
    server time2.no iburst

    restrict default nomodify nopeer noquery limited kod
    restrict 127.0.0.1
    restrict [::1]
```

* merge it `sudo ros config merge -i ntp.yaml`
* restart ntp container `sudo system-docker restart ntp`

**Comment by NM4** [comment]
I have exactly the same configuration except time servers names. But my servers still don't synchronise correctly.
I checked firewall rules with nc so my ntp servers are reachable.

When I restart the VM ( VSphere DC)  the date time  on the VM is the same as served with NTP servers.
But after somedays, I see that the VM datetime is desynchronised. 
How can I check that the synchronisation is well done, get more logs ( Debug mode) and how can I use ntpq, ntpstat on RancherOS ?

Thank you.

**Comment by ohauer** [comment]
Have had a similar issue, so the etcd's where running out of sync ...

The ntp container contains no ntpq or ntpstat, but tells most issues in the log
``sudo system-docker logs ntp`` 

To enable time sync between vsphere and the rancher os vm use:
``sudo system-docker exec -i open-vm-tools vmware-toolbox-cmd timesync enable``

**Comment by NM4** [comment]
Do I need to enable timesync to get vm synchronized with remote NTP servers ?

**Comment by ohauer** [comment]
> Do I need to enable timesync to get vm synchronized with remote NTP servers ?
No, timesync on the VM should not be required if ntp has a reliable source (https://kb.vmware.com/s/article/1006427)
But look at the ntp container logs for any issues, also after restarting the ntp container

**Comment by NM4** [comment]
Hello,

Finally I found where is the pb, my sys-docker network interface is in conflict with LAN IP range.

That solved my problem.

Thank you.
