### ISSUE TITLE
[os-base] Bump kernel to 4.0

### ISSUE THREAD

**Issue by frol** [rancher/os#300]
Could you please bump the kernel to 4.0? `kmem` leaks in cgroup were fixed ([here are more details](https://github.com/docker/docker/issues/6479#issuecomment-97503551))

**Comment by frol** [comment]
I just want to point out that it has been already merged 4.0 into boot2docker and works just fine!

**Comment by ibuildthecloud** [comment]
Currently we track upstream Ubuntu kernels.  We are using the kernel from 15.04 which is 3.19.  We will switch to 4.0 when 15.10 comes out.  In RancherOS v0.4 we are making it easier to run with a custom kernel so you can swap out the kernel with a 4.0 if you choose.

Down the road I would like to produce two flavors of RancherOS.  A stable kernel and a vanilla Linux upstream but right now we aren't quite there in term of supporting that.

**Comment by deniseschannon** [comment]
Closed in favor of #574
