### ISSUE TITLE
system-docker container logs

### ISSUE THREAD

**Issue by ohauer** [rancher/os#3004]
**RancherOS Version: (ros os version)**
v1.5.5

I got a corrupt log file for a system-docker container, running ``system-docker inspect $container`` shows:
`"LogPath": "/var/lib/system-docker/containers/6bbbbe....`

My idea was to flush this log, however `/var/lib/system-docker` does not exist ...
Any hint where I can find the logs for system containers to flush this log before it reach the max size of 25m?

**Comment by AJMacDuk** [comment]
A little late to the party; but having looked for it myself I think it could be useful for others. You can tweak the instructions for loading external driver modules found under [the loading kernel modules docs](https://rancher.com/docs/os/v1.x/en/configuration/loading-kernel-modules/) to get access to the folder:

```bash
[rancher@cm-server ~]$ sudo system-docker run --rm -it --entrypoint bash --privileged \
-v /var:/host/var -v $(pwd):/data -w /data rancher/os-console:v1.5.4
```

Obviously changing the version for the version number you have. You can then access system-docker under `/host/var/lib/system-docker`

**Comment by ohauer** [comment]
Thanks
