### ISSUE TITLE
Release 1.5.6 not available for ros os command

### ISSUE THREAD

**Issue by x-jokay** [rancher/os#3013]
**RancherOS Version: (ros os version)**
1.5.5

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
VM

---

The release [1.5.6](https://github.com/rancher/os/releases/tag/v1.5.6) does not show up when executing `sudo ros os list`.

Therefore an in-place upgrade using `sudo ros os upgrade` is not yet possible.

**Comment by x-jokay** [comment]
May be @niusmallnan can help with this?

**Comment by niusmallnan** [comment]
@x-jokay Please try again. I've updated the release yaml file.

**Comment by x-jokay** [comment]
@niusmallnan thx, now it works :+1:
