### ISSUE TITLE
Release 1.5.6 missing checksums.txt

### ISSUE THREAD

**Issue by x-jokay** [rancher/os#3014]
For the release [1.5.6](https://github.com/rancher/os/releases/tag/v1.5.6) the `checksums.txt` (and some more files) are missing under `Assets`.

**Comment by x-jokay** [comment]
May be @niusmallnan can help with the release?

**Comment by peterstadler** [comment]
Yes, I'm especially waiting for the openstack image. Would be great to have it again!

**Comment by cjellick** [comment]
These have both been uploaded. Thanks for your patience :-)
