### ISSUE TITLE
/var/lib/docker not correctly mounted on boot

### ISSUE THREAD

**Issue by Starstuff0** [rancher/os#3030]
**RancherOS Version: (ros os version)**
1.5.6

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
baremetal on bhyve vm in freeNAS 11.3

I'm encountering an issue where I am unable to mount my docker data on a seperate volume to ROS. I have 2 additional disks attached to the vm which I attempt to mount using:

mounts:
  - ["/dev/vdb1", "/var/lib/docker", "ext4", ""]
  - ["/dev/vdc1", "/mnt/dockercache", "ext4", ""]

in cloud-config.

The dockercache volume is mounted with no problems but /var/lib/docker still remains on the primary volume.
I am able to manually mount /dev/vdb1 to /var/lib/docker which works fine but it wont apply automatically on reboot.

Thanks very much for your help

**Comment by olljanat** [comment]
@Starstuff0 is must be mounted using runcmd. Looks my config on https://github.com/lemmikki/os/issues/6#issuecomment-715916407

**Comment by Starstuff0** [comment]
Thank you Olljanat that seems to have fixed the issue.
