### ISSUE TITLE
vSphere - v1.5.7 - Waiting to register with Kubernetes

### ISSUE THREAD

**Issue by aledr** [rancher/os#3036]
**RancherOS Version: 1.5.7**

**Where are you running RancherOS? vSphere Cluster**

Here is what I have trying to spin new machines with this version...

![image](https://user-images.githubusercontent.com/47945/102533438-30971300-4084-11eb-8451-1410ea9c6830.png)

**Comment by dweomer** [comment]
@aledr as mentioned in rancher-users Slack, please include a detailed list of steps you took that got you into this state.

Also, please make sure you are using the vmware-autoformat.iso as I believe that is required for use with Rancher-provisioned machines.

**Comment by aledr** [comment]
Hi All.

Thanks @dweomer and @brandond the guidance.

This was fixed changing...
From: https://releases.rancher.com/os/v1.5.7/vmware/rancheros.iso
To: https://releases.rancher.com/os/v1.5.7/vmware/rancheros-autoformat.iso

![image](https://user-images.githubusercontent.com/47945/102674713-a9c26300-4175-11eb-84bd-d7c3d6e2470a.png)
