### ISSUE TITLE
source ~/.bashrc if exists

### ISSUE THREAD

**Issue by Nicofuma** [rancher/os#324]
We all like to alter our bashrc (to add /opt/bin to the path, change the prompt to dissociate our server console etc...) but currently the user .bashrc doesn't seem to be sourced when a new session is opened

**Comment by ibuildthecloud** [comment]
Hmm.... now this gets in the the intricacy of .bash_profile vs .bashrc.  I'll figure out why it isn't sourcing the .bashrc.

**Comment by Nicofuma** [comment]
the .bash_profile is sourced? (to be honest I didn't tried this one)

**Comment by ibuildthecloud** [comment]
Not sure, but if bashrc isn't getting read, then .bash_profile probably is.

**Comment by gentooboontoo** [comment]
I confirm `.bash_profile` is sourced but not `.bashrc` when connecting with SSH (login shell case). `.bashrc` is then only sourced when invoking bash as an non-login shell (if you execute `/bin/bash` from your SSH session for instance).

**Comment by 2devnull** [comment]
What is the resolution for this?

**Comment by niusmallnan** [comment]
@2devnull 
Yes, you pointed out the solution
```
[docker@rancheros-v113 ~]$ pwd
/home/docker

[docker@rancheros-v113 ~]$ cat ~/.bashrc
export BRC=true

[docker@rancheros-v113 ~]$ cat ~/.bash_profile
export BPRO=true
if [ -f ~/.bashrc ] ; then
   . ~/.bashrc
fi
```

Then reconnect ssh:
```
[docker@rancheros-v113 ~]$ env
BRC=true
BPRO=true
...
...
```
