### ISSUE TITLE
Rotate /var/log/messages

### ISSUE THREAD

**Issue by Nicofuma** [rancher/os#329]
I think that /var/log/messages should/could be rotate (maybe between each reboot?)

By the way, a logrotate service could be a must ;)

EDIT: it's the same for docker.log and system-docker.log

**Comment by ibuildthecloud** [comment]
Definitely on the todo list, PR's welcome :)

Logrotate is already packaged in RancherOS, we just have yet to create a container for it.  If your adventurous you can try to create a logrotate service at https://github.com/rancherio/os/tree/master/scripts/dockerimages and then add it to config/default.go

**Comment by Nicofuma** [comment]
I have to finish to set up my server before. But why not after if it hasn't been already done ^^

**Comment by emcniece** [comment]
... this still isn't added?

**Comment by SvenDowideit** [comment]
@Nicofuma its in https://github.com/rancher/os/releases/tag/v1.1.0-rc2

implemented in https://github.com/rancher/os/pull/1966
