### ISSUE TITLE
Applying cloud-config network configuration without reboot

### ISSUE THREAD

**Issue by janeczku** [rancher/os#339]
In order to apply network settings without having to reboot, i currently have to deploy a start script via write_files. Something in the line of
```yaml
write_files:
  - path: /opt/rancher/bin/start.sh
    permissions: 0700
    content: |
      #!/bin/bash
      sudo netconf
```
If i wanted to apply DNS servers as well that script would even be longer.
I think this is kind of a hack and should probably be done programmatically when processing the cloud-config. CoreOS already applies network configuration dynamically (it checks for and applies any networkd units it finds in the cloud-config) and it would be nice to have that supported in RancherOS as well.
What do you think?

/cc @ibuildthecloud @imikushin

**Comment by imikushin** [comment]
@janeczku I'm not sure what you mean here. 

Currently (as of v0.3.1-rc3), RancherOS reads cloud-config and configures network and other system settings on boot accordingly. E.g., DNS servers can be set to OpenDNS's nameservers with the following cloud-config :
```yml
#cloud-config
rancher:
  network:
    dns:
      nameservers:
      - 208.67.222.222
      - 208.67.220.220
```

Can you give an example of what you'd like RancherOS to do? Like, e.g., after changing DNS servers with `ros config set network.dns.nameservers "[8.8.8.8, 8.8.4.4]` to automatically apply them?

**Comment by janeczku** [comment]
@imikushin sorry if i wasn't clear enough. I would like RancherOS to apply any network configurations it finds in the cloud-config immediately without the need to reboot the machine.

**Comment by imikushin** [comment]
@janeczku RancherOS v0.3.1-rc3 and later does exactly that, if I'm not mistaken. I mean, all the configs are read from cloud-config and applied on boot, and the booted machine is fully configured without the need for reboot.

**Comment by janeczku** [comment]
@imikushin I am pretty sure the network settings from cloud-config are still applied only on the next boot, not on the first boot. The network container runs before the cloud-init and i don't see anywhere that the network is configured a second time after processing the cloud-config.

**Comment by deniseschannon** [comment]
@janeczku Just to clarify, are you saying that after doing a `rancheros-install`, you don't want to reboot?

**Comment by janeczku** [comment]
@deniseschannon, yes imagine deploying a cluster and then having to reboot each node individually just so that the network settings get applied. IMHO the network settings in the cloud-config should be applied as they are read/processed.

**Comment by imikushin** [comment]
@janeczku can you confirm you're still experiencing this issue with the latest RancherOS v0.3.3? 
What mechanism do you use to supply cloud-config to your RancherOS instance?

**Comment by wedtm** [comment]
I'm seeing this issue as well. Latest version of Rancher (v0.3.3). I'm supplying the DNS servers via a cloud-config in AWS. When the box first comes up, the hostname is set correctly, but the DNS is still set to `8.8.8.8` and `8.8.4.4`. I have to restart the box in order for the DNS to be applied.

**Comment by deniseschannon** [comment]
@wedtm Just to confirm, after you login the first time, you need to reboot for the DNS to be set from the cloud config? You don't make any other changes before rebooting, but after you reboot, the DNS changes are applied.

**Comment by imikushin** [comment]
Confirmed: it's a bug.

**Comment by wedtm** [comment]
Correct.

**Comment by janeczku** [comment]
:+1:

**Comment by imikushin** [comment]
This should get fixed as soon as #669 is merged.

**Comment by qrpike** [comment]
Having the same issues here. Setting network settings seems to do little to nothing at all.

**Comment by deniseschannon** [comment]
@qrpike Yes, you'll need to reboot in order for the network settings to take affect.

**Comment by janeczku** [comment]
@imikushin 

>  I mean, all the configs are read from cloud-config and applied on boot, and the booted machine is fully configured without the need for reboot.

That is only true for non-network cloud-config sources. The network config from an EC2 source for example is NOT applied without rebooting.

I think this is an easy fix:
 `cloudinit` https://github.com/rancher/os/blob/master/cmd/cloudinit/cloudinit.go#L188 should check (either on save or on execute) if the userdata cloud-config contains any network settings and if true then apply them by invoking `netconf.ApplyNetworkConfigs` on them.

**Comment by deniseschannon** [comment]
Verified this is working in v0.4.4-rc3.

Note: You will need to set `rancher.network.dns.override` to `true` in the cloud-config to be able override the default dns settings.

```
rancher:
  network:
    dns:
      override: true
```

In order to see the changes that you passed in during boot, you can use `sudo ros config export --boot`.
