### ISSUE TITLE
Document Hardware Requirements to Run RancherOS

### ISSUE THREAD

**Issue by scherrey** [rancher/os#345]
I just downloaded and tried to install the .iso file. Unfortunately my spare machine is an i686 and the boot message said the kernel requires x86_64. 

1) Is this just an artifact of the iso's kernel or an absolute requirement for rancheros? 

1.1) If the former, how can I build an iso for i686? 

2) What are the other expected system requirements so I can target this correctly?

3) Is there any typical hardware explicitly not supported? For example, I've been told that USB is not yet working. Is that true and when might that change?

I love the concept of rancheros. We've been using docker in production systems for over a year now. I'm especially pleased with the idea that I may be able to skip over and elect not to participate in this systemd nonsense. Maybe one day I can use it as my desktop OS... :-) Many thanx,

  -- Ben Scherrey

**Comment by janeczku** [comment]
1. Everything in RancherOS is a container managed by Docker
2. Docker doesn't run on 32-bit architecture.
Hence, a 64-bit machine is required to run RancherOS.

**Comment by r4j4h** [comment]
@janeczku Have you seen [this article](http://mwhiteley.com/linux-containers/2013/08/31/docker-on-i386.html) or [this repo](https://github.com/docker-32bit/ubuntu)? Apparently Docker runs fine on 32-bit systems it is just unsupported...

That being said, I'm not sure if it will be worth it as it appears our docker base images will necessarily be different. Meaning you'll have to port any containers you want to run on that hardware to a different tag and make sure only those go on those types of systems. It feels like it violates the idea that a container is truly usable everywhere, but it is possible.

For @scherrey, Please check out those links. The article especially contains instructions for building your own ISOs.

**Comment by deniseschannon** [comment]
We have added hardware requirements in the documents for v0.4.0, which will be updated when it's officially released.
