### ISSUE TITLE
wget cant load https sites (openssl not foud)

### ISSUE THREAD

**Issue by xarses** [rancher/os#348]
`wget https://launchpad.net/`

Returns `wget: can't execute 'openssl': No such file or directory`

**Comment by jackwilsdon** [comment]
+1

**Comment by imikushin** [comment]
We'll consider adding it to a next version.

Currently you can enable debian-console (or ubuntu-console)
```
sudo ros s enable debian-console
sudo reboot
```
and install openssl package (and other packages you need in the console)
```
apt-get install --no-install-recommends openssl
```

Keep in mind that consoles are currently (in v0.3.1) ephemeral, so you'll need to install the packages again after reboot.

**Comment by joshwget** [comment]
It looks like OpenSSL was added to the base image since this issue was created. If you continue to have similar problems, feel free to reopen.
