### ISSUE TITLE
rfc: lvm support.

### ISSUE THREAD

**Issue by paxpacis** [rancher/os#356]
I would like to use rancheros but my disks to store the docker files/images are LVM, there is currently no support for it in RancherOS and I can not mount the disks..

Will you support LVM in the future?

**Comment by ibuildthecloud** [comment]
Yes we will, we are working on it now.  It's more tricky to support than we'd like, but we think we have a working solution.  In the end you will have to launch your own container that on start sets up LVM, RAID, NFS, etc at how you choose.  Then Docker will use that "storage" container you created as its filesystem.

**Comment by deniseschannon** [comment]
This is only supported in v0.4.0+. We've added documentation on how to do this in v0.4.0. The docs will be updated when v0.4.0 is officially released.

**Comment by swayf** [comment]
hm if I searching for lvm in rancher os docu.. google find nothing.. could you give a link?

**Comment by asuwarnapati** [comment]
any link or docs how to configure lvm on rancheros?

**Comment by MhdAli** [comment]
@deniseschannon could you please share more info about this?

**Comment by senguendk** [comment]
@deniseschannon I am also looking for the link in the documentation. It would be great to get some information on how to setup LVM on rancherOS
