### ISSUE TITLE
Installation error On VirtualBox via ISO while pull image

### ISSUE THREAD

**Issue by sjkeerthi** [rancher/os#360]
During the installation from ISO I could see the rancher trying to pull the image from index.docker.io
but the problem is it fails.

But I could able to ping and query via nslookup with my own dns in ISO.

Result from ISO where I could able to access outside world.

[rancher@rancher ~]$ ping index.docker.io
PING index.docker.io (162.242.195.84): 56 data bytes
64 bytes from 162.242.195.84: seq=0 ttl=53 time=259.450 ms
64 bytes from 162.242.195.84: seq=1 ttl=53 time=259.939 ms

I did nslookup from ISO

nslookup index.docker.io
Server:    204.11.xxx.xxx
Address 1: 204.11.126.189 maa-dc6.xxx.xxx.xxx.xxx

Name:      index.docker.io
Address 1: 162.242.195.84 docker.io
[rancher@rancher ~]$ nslookup 8.8.4.4 
Server:    204.11.xxx.xxx
Address 1: 204.11.xxx.xxx maa-dc6.xxx.xxx.xxx.xxx

[rancher@rancher ~]$ sudo rancheros-install -c config.yaml -d /dev/sda 
No install type specified...defaulting to generic
All data will be wiped from this device
Partition: true
DEVICE: /dev/sda
Are you sure you want to continue? [yN]yUnable to find image 'rancher/os:v0.3.1' locally
Pulling repository rancher/os
FATA[0025] Get https://index.docker.io/v1/repositories/rancher/os/images: dial tcp: lookup index.docker.io on 8.8.4.4:53: read udp 8.8.4.4:53: i/o timeout 

Kindly let me know what could be the issue is. Even I have selected the VirtualBox ethernet interface as Paravirtualized Network (virtio-net) 

I could see the interface as eth0

**Comment by mhvelplund** [comment]
I have the exact same problem.

**Comment by miztiik** [comment]
Is there any documentations which explains how to do installation from ISO (without vagrant?)

**Comment by deniseschannon** [comment]
@sjkeerthi @mhvelplund 
There has been a lot of refactoring around networking in the recent release (v0.4.4), so I'll close and if you still have issues, please re-open.

@miztiik 

http://docs.rancher.com/os/running-rancheros/workstation/boot-from-iso/
