### ISSUE TITLE
Linux Mint - Software Rendering Mode (RancherVM)

### ISSUE THREAD

**Issue by layer4down** [rancher/os#375]
Installed RancherVM under User Docker and created test Linux Mint 17 Cinnamon 64-bit image. Container runs fine but guest OS is now "Running in Software Rendering Mode". The only recommended fixes I can find relate to VirtualBox and not KVM/QEMU. Hoping this is an appropriate place to get some ideas to resolve this. Thank you in advance for any guidance.

**Comment by sheng-liang** [comment]
Would the fix require passing GPU hardware to the Linux Mint VM?

**Comment by layer4down** [comment]
Sorry I'm still learning the linux basics. But to my understanding, the fix for this over VirtualBox requires enabling 3D acceleration. I hadn't searched for that specifically but I will research that and provide updates. Thanks sir! 


     On Friday, June 12, 2015 2:21 PM, sheng-liang <notifications@github.com> wrote:
   

 Would the fix require passing GPU hardware to the Linux Mint VM?—

**Comment by SvenDowideit** [comment]
@layer4down I'm going to close this issue - if you're still working with this - perhaps you can answer the question here for others to find?
