### ISSUE TITLE
Feature Request: Support for xhyve

### ISSUE THREAD

**Issue by far-blue** [rancher/os#379]
Although very experimental at the moment, the first release of xhyve is very promising as an alternative to VirtualBox - esp. within docker / docker-machine / boot2docker style workflows on OS X. I think the combination of rancherOS running in xhyve via docker-machine would be a great lightweight, userspace environment for docker containers using official Apple hypervisor support and no need for complex installs or kexts.

**Comment by far-blue** [comment]
Also see docker/machine#1358 for the whip pull request by the xhyve guys for integrating xhyve into docker-machine

**Comment by deniseschannon** [comment]
Only remaining item is persistent drive.

**Comment by thariman** [comment]
Any progress on xhyve support like https://github.com/coreos/coreos-xhyve?
