### ISSUE TITLE
Build Rancher OS on own machine

### ISSUE THREAD

**Issue by luxas** [rancher/os#380]
Hello everyone!

I think RancherOS is so awesome, and I would like to test it. I'm building a Raspberry Pi Kubernetes cluster with RancherOS as host system (20 MB - perfect for the Pi). 

Now, I suppose the prebuilt RancherOS images doesn't work on the Pi, because they were built for amd64 not armhf...

I've access to a Ubuntu VM in my laptop (64-bit) and some Raspberry Pi 2's for building the image.

But, how should I do to build the .iso's for armhf on my own?

Thanks!

**Comment by imikushin** [comment]
First, you'll need Docker custom built for RPi: Docker officially supports only x86-64 arch.

The next RancherOS release (v0.4.0) should be modular enough to allow for such an experiment as the new OS build system is designed around the target system configuration (`os-config.yml`). 

You'll need to build the whole set of [system containers](https://github.com/rancherio/os-images) for RPi. RancherOS build system uses docker too, so it'll also have to be ported (beginning with our docker-in-docker image).

**Comment by luxas** [comment]
Thanks for your answer!

I have docker running on my Pi's. I'm using Arch Linux ARM and there is prebuilt docker images in the pacman package manager.

When is the new version v0.4 planned to be released?

I think I can build the system containers that are present...

However, how can one build the whole os? May I use rancheros-install with a custom-built rancher/os image?

I'm not sure how I can put the whole thing on the sd card

**Comment by imikushin** [comment]
Right, rancheros-install will also need to be customized to use architecture-dependent rancher/os container. 

v0.4.0 is going to be released in the coming weeks. 

I'm still figuring out how to simplify the build process enough so it could be easily ported between architectures. 

SD-cards with a few gigs are pretty common these days :) Not sure what you mean by "thing", though.

**Comment by luxas** [comment]
I may help to make a more architecture-undependent project, by comments at first :)
I think there is defenitely need for a build doc where it says how to build it yourself.
Or only explaining which steps you do when you compile the isos

Okay, how should I do if I should build rancheros to x86_64? 
I suppose if I use it as a VM, then I need an iso.
How should one build that?
If I use it on bare-metal and install it to disk, then I need to build it via rancheros-install.
And for that I need to build my own rancher/os-docker image.
How should I make a rootfs.tar file?
Some build command?
And there the system-docker containers comes in.
In which step should they be included...

You see I'm kind of thinking out loud here...
By the "whole thing" I mentioned last comment, I meant everything that must be included for it to run :)

It's gonna be interesting to see how this turns out

**Comment by bloodsun** [comment]
I am not too sure if I should post here or create a new topic.

Currently I am able to build the rancher/os-base and rancher/os-images without issue. However, it seems that currently rancher/os build is pulling the image from Docker Hub Registry. 

Is there any alternative way of making rancher/os build to get from local build instead of pulling from external registry? It also seems that the DIND is not able to communicate with the host docker volume (/var/lib/docker) because DIND is mounting /var/lib/docker as VOLUME.

Would appreciate if there is alternative as I try to avoid setting up private registry or pulling from external registry.

Thank you.

**Comment by luxas** [comment]
I think it could be handled here.
I don't know the current status of this issue, it seems like it should be fixed in 0.4, but it may take some time before it is finished.

How is it going @imikushin? :smile:
(I am not a maintainer, BTW)

**Comment by imikushin** [comment]
Hey @luxas @bloodsun  I think you might like recent developments in master: I've got rid of docker-in-docker stuff. Now, all you need to build RancherOS release files (rancheros.iso, initrd, vmlinuz) is: make and docker, on Linux or OS X. For a quick-start, just run `./build.sh`: it'll just launch `make all`. To rebuild the go code in this project, just run `make`.  

It won't pull `rancher/os-...` images anymore, if they're already present in your docker. 

The build is almost architecture independent: you can easily fork and use your own images for the `os-config.yml` services, and Dockerfile.base can be built based on a `debian:jessie` fork for another architecture.

You can even use a remote docker daemon for the build, e.g. provided by docker-machine (GCE, Amazon, DO or wherever else you like).

**Comment by luxas** [comment]
OK, I'll check it out

**Comment by bloodsun** [comment]
Thanks a lot @imikushin! Able to compile nicely now after some trial. :smile:

**Comment by luxas** [comment]
@bloodsun Did you compile for amd64?

**Comment by bloodsun** [comment]
@luxas Yes, at the moment I only have need for amd64. Have not cross-compile as I have no rpi 2 on my hand at the moment.

**Comment by luxas** [comment]
@imikushin Now I was able to compile for amd64 too (I got my x64 machine now) :smiley:

FYI, it came an error in build.sh (the last line) when it tried to `ls dist/artifacts` which didn't exist.
Not an big error, but anyway.

Some questions:
- The Dockerfile.base: Which things should be present there?
  So far I know this could be included easily on arm: `docker, git, go, rsync, build-essentials`
  But how do you use these: `syslinux isolinux xorriso libblkid-dev libmount-dev libselinux1-dev`?
- From where do you get your kernel? Is it from some linux repo here on github? If so, one could check `raspberrypi/linux` for the kernel.
- How do you make the bootloader? Is it in a separate partition? The rpi has a separate `boot` partition, I am not sure, but it could be possible to reuse that partition.

I will try to compile the os-images on my RPi soon.

**Comment by bcg62** [comment]
Also seeing the dist/artifacts issue

```
./scripts/mk-iso-checksums-txt.sh
++ dirname ./scripts/mk-iso-checksums-txt.sh
+ cd ./scripts/..
+ . scripts/build-common
+++ pwd
++ BUILD=/go/src/github.com/rancherio/os/build
+++ pwd
++ DIST=/go/src/github.com/rancherio/os/dist
+ cd /go/src/github.com/rancherio/os/dist/artifacts
+ rm -f iso-checksums.txt
+ for algo in ''\''sha256'\''' ''\''md5'\'''
++ sha256sum rancheros.iso
+ echo 'sha256: 39dfc05ec7c94205a54cec5b99f034252a6df814df07059b09d754af9f5f29bb  rancheros.iso'
+ for algo in ''\''sha256'\''' ''\''md5'\'''
++ md5sum rancheros.iso
+ echo 'md5: 1c121e6b4bde79549a65c185e47d5604  rancheros.iso'
docker cp ros-build:/go/src/github.com/rancherio/os/bin/rancheros bin
docker cp ros-build:/go/src/github.com/rancherio/os/dist/artifacts dist
ls: cannot access dist/artifacts: No such file or directory
```

**Comment by luxas** [comment]
Should this issue be closed now? It was easy to compile for amd64...

@imikushin could you put it in the README that one just should run `sudo build.sh` on a Ubuntu machine to get the .iso?

So the discussion for the Raspberry Pi 2 may continue in issue #417.

**Comment by deniseschannon** [comment]
@luxas When v0.4.0 officially comes out, we'll be closing this issue.

**Comment by luxas** [comment]
OK, works fine for me!

**Comment by deniseschannon** [comment]
@luxas v0.4.0 isn't quite out, but most of the customization has been documented. The docs will be updated when v0.4.0 is officially released, but going to close this as we were keeping it open to track documentation updates.
