### ISSUE TITLE
rancherOS support for storage drivers/firmware 

### ISSUE THREAD

**Issue by abhishekubale** [rancher/os#390]
Hi,
We are evaluating RancherOS for our container strategy but its unclear RancherOS support for storage options like NFS,LVM and particularly drivers/firmware for SSD on bare-metal installs. Can this be documented?

-thanks

**Comment by imikushin** [comment]
Storage is on the work queue and is going to receive attention in the coming weeks. 

RancherOS v0.3.1 uses [linux kernel v3.19](https://github.com/rancherio/linux/releases/tag/Ubuntu-3.19.0-15.15) from ubuntu-15.04. Theoretically, it should have the same drivers ubuntu has. And yeah, this definitely should be documented, so this is on the list too.

**Comment by ibuildthecloud** [comment]
In v0.4 we support the ability to swap in custom kernels and additionally NFS, LVM is supported.  Does custom firmware require a different kernel, or just a different firmware file.  Without a custom kernel you can still edit the `/lib/firmware/$(uname -r)` folder.
