### ISSUE TITLE
SSH-key generation is not work

### ISSUE THREAD

**Issue by sjkeerthi** [rancher/os#394]
Hi All,

I am trying to install RancherOS on my VirtualBox before that I tried to login ssh via ISO and created the ssh-keygen in the rancher id and I copied the id.rsa.pub key into my laptop .ssh/authorized_keys and If I try the SSH the ISO still its asking the username password for the rancher users.

Even I tried installation into HDD after passing cloud-config-file after successful installation still when I try to ssh its asking the password.

cat cloud-config-file 
#cloud-config

ssh_authorized_keys:
 ssh-rsa 
AAAB3NzaC1yc2EAAAADAQABAAACAPVl9tlKCFr2bz8bVxRTvbY/GCbMENek7dLOmZpR57b8PWUdVx1eqBo72RIyzwm5zvYq5w== rancher 

What really I am missing here.

**Comment by deniseschannon** [comment]
you need the format of your cloud config file to look like this. Please look at the spacing near the ssh key. It needs to be indented and have a dash.

```
#cloud-config

ssh_authorized_keys:
  - ssh-rsa 
AAAB3NzaC1yc2EAAAADAQABAAACAPVl9tlKCFr2bz8bVxRTvbY/GCbMENek7dLOmZpR57b8PWUdVx1eqBo72RIyzwm5zvYq5w== rancher
```

**Comment by sjkeerthi** [comment]
After successful install of RacherOS and then added rancher agent to access via UI but still I could not see in the host list

**Comment by sjkeerthi** [comment]
I ran below in my RancherOS still I don't see the Host in the UI

**Comment by deniseschannon** [comment]
are you using the same RancherOS instance for your rancher/server and rancher/agent? If so, you'll need to add in `-e CATTLE_AGENT_IP=<server_ip>` into the docker command to have the rancher/agent select the correct IP. 

http://rancherio.github.io/rancher/docs/infrastructure/hosts/custom/#adding-hosts-to-the-same-machine-as-rancher-server

**Comment by sjkeerthi** [comment]
Nope My RancherOS is running on my VirtualBox with Bridge Interface and Rancher is running on my Laptop.

**Comment by sjkeerthi** [comment]
Same I tried with CoreOS its working where I could able to view the CoreOS into Hosts list.

Still in RancherOS its not working. Do I need to start anything on RancherOS

**Comment by deniseschannon** [comment]
Can you try adding the `-e CATTLE_AGENT_IP=<rancherOS_IP>` to the command?

**Comment by sjkeerthi** [comment]
Should I have to give this command from RAncherOS or on RacherUI

**Comment by sjkeerthi** [comment]
From my RancherOS I can see the status of docker ps

CONTAINER ID        IMAGE                  COMMAND             CREATED              STATUS              PORTS               NAMES
4a5531789478        rancher/agent:v0.7.9   "/run.sh run"       About a minute ago   Up About a minute                       rancher-agent       

Still the from the Rancher Management I could not able to view the host yet I ran as many times.

**Comment by sjkeerthi** [comment]
I tried by Adding the agent again from my RancherOS with below parameter but still I could not see the Host in my Rancher Management UI

 10.2.0.155  : RancherOS IP ( Which Runs on my VIrtualBox)
 10.2.0.64    : Rancher Management IP ( Which Runs in my Local Laptop)
sudo docker run -d --privileged -e CATTLE_AGENT_IP=10.2.0.155 -v /var/run/docker.sock:/var/run/docker.sock rancher/agent:v0.7.9 http://10.2.0.64:8080/v1/scripts/E6AE49FA28D96B299ECF:1434970800000:z3AZLRbGC8tTJfajT2zv4fgrjcI

**Comment by deniseschannon** [comment]
@sjkeerthi sorry for the delay. can you provide the logs from the rancher/agent? 

If 10.2.0.64 is your rancher management IP, then the command should be something like 
```
sudo docker run -d --privileged -e CATTLE_AGENT_IP=10.2.0.64 -v /var/run/docker.sock:/var/run/docker.sock rancher/agent:v0.7.9 http://10.2.0.64:8080/v1/scripts/E6AE49FA28D96B299ECF:1434970800000:z3AZLRbGC8tTJfajT2zv4fgrjcI
```

Can you also make sure your host registration is set up for 10.2.0.64:8080?

**Comment by deniseschannon** [comment]
@sjkeerthi Please re-open if you are still having issues. Revisiting the comments, you can look at our troubleshooting guide on what could have been the issue. http://docs.rancher.com/rancher/faqs/troubleshooting/
