### ISSUE TITLE
docker-machine and ros os upgrade

### ISSUE THREAD

**Issue by far-blue** [rancher/os#399]
I'm not entirely surprised that trying to do a ros os upgrade from within a docker-machine created vm won't work :) It would be nice if maybe there was some sort of warning or something.

As an alternative, docker-machine upgrade should work because it re-fetches the ISO. It would be great if there was a 'latest' url we could use when creating a docker-machine vm rather than a tag-specific link because then docker-machine upgrade would be able to pull the latest iso, not just re-download the one used to create the vm :)

**Comment by wlan0** [comment]
@far-blue That is a great suggestion. :+1: 

If more of the community feels the need for this feature, we could prioritize it and get it done.

**Comment by deniseschannon** [comment]
@far-blue I've updated the docs to reflect that upgrades are not supported.

**Comment by SvenDowideit** [comment]
we should also try to detect what mode we're running in, and make `ros os upgrade` output the right thing.

I'm presuming that if running in ram, then no upgrade, if RancherOS is running from installed disk, then +1

**Comment by niusmallnan** [comment]
We should support what Sven mentioned.
Put it to milestone v1.5.1.

**Comment by kingsd041** [comment]
Testing with RancherOS v1.5.1-rc1
If you start ROS with [Booting from ISO](https://rancher.com/docs/os/v1.x/en/installation/running-rancheros/workstation/boot-from-iso/) or [Using Docker Machine](https://rancher.com/docs/os/v1.x/en/installation/running-rancheros/workstation/docker-machine/), the upgrade will not be supported and prompted:
```
[root@rancher ~]# ros os upgrade -i rancher/os:v1.5.0
FATA[0000] ros upgrade cannot be supported
```
