### ISSUE TITLE
Error While Downloading RangerAgent google DNS

### ISSUE THREAD

**Issue by sjkeerthi** [rancher/os#402]
After the successful installation of BareMetal RancherOS on my VirtulBox. When I try to add the host into my Rancher Management I could see error below its trying to pull the images via google dns.

Even I set my own dns server using below command. Where I could able to see the /etc/resolve.conf and able to ping but still I have no clue why RancherOS pulling them image via google DNS.

sudo ros config set network.dns.nameservers '[2xx.1x.1xx.1xx,20x.1x.xx.xx]'

sudo docker run -d --privileged -v /var/run/docker.sock:/var/run/docker.sock rancher/agent:v0.7.9 http://mgmt-rancher.collab.net/v1/scripts/9919B6EB6ED296D7DA51:1434974400000:5shyk5bsWDauiaeqJqiciYm0E
Unable to find image 'rancher/agent:v0.7.9' locally
Pulling repository rancher/agent
FATA[0025] Get https://index.docker.io/v1/repositories/rancher/agent/images: dial tcp: lookup index.docker.io on 8.8.4.4:53: read udp 8.8.4.4:53: i/o timeout

**Comment by deniseschannon** [comment]
quick question: did you reboot after you set your dns server?

**Comment by sjkeerthi** [comment]
Ya did the reboot but still its pointing the same error

**Comment by deniseschannon** [comment]
@sjkeerthi Are you still having this issue with the latest version (v0.4.3?). There have been major networking changes since you last filed, so this could be fixed.

**Comment by deniseschannon** [comment]
@sjkeerthi  Please open a new issue if you are still facing this in our latest version (v0.4.4)
