### ISSUE TITLE
[os-base] Add cURL

### ISSUE THREAD

**Issue by dx9** [rancher/os#405]
Would be handy to have it built-in.

**Comment by imikushin** [comment]
Thanks for this feature request: it's certainly very nice to have.

**Comment by Xe** [comment]
busybox wget does most if not all that curl can do. Not to mention you can just use a container for curl.

**Comment by dx9** [comment]
@Xe yeah man

echo 'docker run --rm radial/busyboxplus:curl curl $@' > /usr/bin/curl && chmod +x /usr/bin/curl

Either option works. I do like the idea of just knowing it's there.

**Comment by wmark** [comment]
Or smaller (4.2 MB → 1.3 MB) after having removed the image *radial/busyboxplus:curl*:

```bash
docker run --rm radial/busyboxplus:curl curl -fLR --progress-bar \
  -o - https://s.blitznote.com/debs/curl > /usr/bin/curl \
&& chmod a+x /usr/bin/curl

sha256sum curl
# b4d5c397201db26c6ceb8934d38e2edf17e31db03463596b3dfc17fefeeaaaae  curl
```

**Comment by wmark** [comment]
```radial/busyboxplus:curl``` is 4.2 MB.

A static binary of *curl* is only 1.9 MB — including *libidn* and *nghttp2* on top, and w/o the redundant SSH, but with *BoringSSL* — and *gzip-compressed* 0.9 MB.
```sh
$ /opt/bin/curl --head https://s.blitznote.com/debs/curl-static-7.43.0-2
Content-Length: 1907296

$ /opt/bin/curl -fLRsS -o - https://s.blitznote.com/debs/curl-static-7.43.0-2 | gzip -9 | wc -c
924384
```

**Comment by ibuildthecloud** [comment]
I don't think we will fix this unfortunately.  We don't want to include the real curl because that increases the core size of RancherOS.  If busybox had support for curl we could add it, but unfortunately it does not.  busybox does have wget though, so I feel that is a workable solution.

@imikushin The one downside of our wget is that we don't have SSL support.  Can we look at adding openssl binary to make https work?

**Comment by imikushin** [comment]
I've added openssl to os-base (see https://github.com/rancher/os-base/releases/tag/v2015.05-1) and wget now supports https URLs (in the latest RancherOS dev).

**Comment by wmark** [comment]
This added about 0.8 MB on disk?

You could decrease the size of *OpenSSL* even more by not compiling in some features. For example, DTLS , SSL2 and ciphers such as RC2 will most likely not be needed. Here are the flags:

```
	enable-ec enable-ec_nistp_64_gcc_128 -DECP_NISTZ256_ASM \
	enable-tlsext threads \
	no-dso no-krb5 \
	no-cast no-seed no-idea no-ripemd no-md2 no-mdc2 no-md4 no-rc2 no-rc5 no-bf \
	no-heartbeats no-ssl2 no-ssl3 no-dtls no-dtls1 no-dtls1_2 no-srtp no-jpake no-gost \
	no-hw no-sctp no-fips
```

(```no-cms``` would be nice, but it is broken according to openssl/openssl#221)

**Comment by wmark** [comment]
One more thing:

```bash
$  strings openssl | grep -F "OpenSSL 1.0"
OpenSSL 1.0.2a 19 Mar 2015
```

1.0.2d is the current version.

**Comment by wiktor-k** [comment]
Curl can be run directly using this small container: `docker run --rm mwendler/curl`. It has an advantage of actually validating HTTPS certificates. The `wget` contained in busybox is happy to download any kind of HTTPS content (verified using `wget https://self-signed.badssl.com/`).

**Comment by deniseschannon** [comment]
As @ibuildthecloud mentioned, we won't be fixing.

**Comment by cnkcb** [comment]
<wget: unrecognized option '--method=PUT'>
