### ISSUE TITLE
Customize storage for user docker

### ISSUE THREAD

**Issue by deniseschannon** [rancher/os#416]

**Comment by deniseschannon** [comment]
Needs testing

**Comment by pwFoo** [comment]
Customize storage like separate the RancherOS / system-docker from user-docker and containers / images?

Custom partition schema would be great to use a partition / second hdd as container / image storage.

**Comment by imikushin** [comment]
@deniseschannon @ibuildthecloud What do we mean by "customizing storage" for docker?
