### ISSUE TITLE
Persistent Console

### ISSUE THREAD

**Issue by deniseschannon** [rancher/os#419]

**Comment by ibuildthecloud** [comment]
@imikushin We need to make the busybox console ephemeral and ubuntu/debian persistant.  I believe there is a libcompose label for this.

**Comment by ibuildthecloud** [comment]
Crap, no.  I haven't put in the PR to libcompose yet.  Will do.  The label will be

`io.docker.compose.rebuild=false`
`io.docker.compose.rebuild=true`

**Comment by ibuildthecloud** [comment]
Just add `io.docker.compose.rebuild=false` to ubuntu and debian consoles

**Comment by imikushin** [comment]
Added the label

**Comment by imikushin** [comment]
Closing this one and continuing to track this issue in #516
