### ISSUE TITLE
RancherOS install failed while pulling image

### ISSUE THREAD

**Issue by sjkeerthi** [rancher/os#422]
While Installing RancherOS on disk I could see error below.

Where I could able to ping outside world

ping yahoo.com
PING yahoo.com (206.190.36.45): 56 data bytes
64 bytes from 206.190.36.45: seq=0 ttl=54 time=257.316 ms
64 bytes from 206.190.36.45: seq=1 ttl=54 time=261.941 ms
64 bytes from 206.190.36.45: seq=2 ttl=54 time=255.844 ms
^C
--- yahoo.com ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 255.844/258.367/261.941 ms
[rancher@rancher ~]$ sudo rancheros-install -c cloud-config.yml -d /dev/sda 
No install type specified...defaulting to generic
All data will be wiped from this device
Partition: true
DEVICE: /dev/sda
Are you sure you want to continue? [yN]yUnable to find image 'rancher/os:v0.3.1' locally
Pulling repository rancher/os
FATA[0025] Get https://index.docker.io/v1/repositories/rancher/os/images: dial tcp: lookup index.docker.io on 8.8.4.4:53: read udp 8.8.4.4:53: i/o timeout

**Comment by sjkeerthi** [comment]
I am not sure why the default /etc/resolve.conf didn't work (8.8.4.4). 
So I changed into my own DNS server and still I could face the same issue.
Docker could not able to pull the image.

**Comment by ibuildthecloud** [comment]
Can you try `sudo system-docker pull rancher/os:v0.3.1` and also `docker pull rancher/os:v0.3.1`

**Comment by sjkeerthi** [comment]
Tried could see same issue no any improvement.

sudo rancheros-install -c cloud-config.yml -d /dev/sda 
No install type specified...defaulting to generic
All data will be wiped from this device
Partition: true
DEVICE: /dev/sda
Are you sure you want to continue? [yN]yUnable to find image 'rancher/os:v0.3.1' locally
Pulling repository rancher/os
FATA[0025] Get https://index.docker.io/v1/repositories/rancher/os/images: dial tcp: lookup index.docker.io on 8.8.4.4:53: read udp 8.8.4.4:53: i/o timeout 
[rancher@rancher ~]$ sudo system-docker pull rancher/os:v0.3.1
Pulling repository rancher/os
FATA[0025] Get https://index.docker.io/v1/repositories/rancher/os/images: dial tcp: lookup index.docker.io on 8.8.4.4:53: read udp 8.8.4.4:53: i/o timeout 
[rancher@rancher ~]$ sudo su -
[root@rancher ~]# docker pull rancher/os:v0.3.1
Pulling repository rancher/os
FATA[0025] Get https://index.docker.io/v1/repositories/rancher/os/images: dial tcp: lookup index.docker.io on 8.8.4.4:53: read udp 8.8.4.4:53: i/o timeout

**Comment by sjkeerthi** [comment]
Even from my rancher ISO I could able to do traceroute for the 8.8.4.4

[root@rancher ~]# traceroute 8.8.4.4
traceroute to 8.8.4.4 (8.8.4.4), 30 hops max, 46 byte packets
 1  10.2.1.254 (10.2.1.254)  0.682 ms  0.711 ms  0.876 ms
 2  fa1-0-gw.xx.xxxxxx.xxx (xxxxxxx)  1.176 ms  1.302 ms  1.055 ms
 3  nsg-static-157.xxx.71.182.xxxxl.xx (182.xxx.xxx.xxx)  6.982 ms  8.961 ms  9.549 ms
 4  182.79.236.106 (182.79.236.106)  3.820 ms  8.399 ms  12.058 ms
 5  72.14.242.178 (72.14.242.178)  19.846 ms  4.277 ms  9.709 ms
 6  209.85.243.111 (209.85.243.111)  5.738 ms  5.102 ms  209.85.248.87 (209.85.248.87)  13.479 ms
 7  google-public-dns-b.google.com (8.8.4.4)  4.897 ms  7.594 ms  5.573 ms

**Comment by sjkeerthi** [comment]
Is anyone help me out still couldn't able to install the rancherOS. Once my validation is done I can start to implementation on production.

**Comment by imikushin** [comment]
Can you maybe try other DNS servers? OpenDNS, for example: 208.67.222.222, 208.67.220.220
Can you also check DNS traffic isn't blocked somewhere on the way? Maybe try a network sniffer.

**Comment by deniseschannon** [comment]
@sjkeerthi Please re-open if you are still having issues. We are about to launch RancherOS v0.4.0, which is much more usable compared to v0.3.3, so you might have better luck. :)
