### ISSUE TITLE
Volume not created but containers runs fine

### ISSUE THREAD

**Issue by ebuildy** [rancher/os#431]
From an EC2 machine, I am running RancherOS 0.3.3 with Docker 1.7. I am using the Docker client on the machine.

I can run a container and inspect it:

![docker inspect mysql]
(https://beemapp.s3-eu-west-1.amazonaws.com/0797e634-7868-46a8-b35a-c9fed7937448.jpg)

But no folder is created (whereas it works fine on boot2docker or any docker-machine host).

Is there something special with RancherOS and volume? 

Thanks you,

**Comment by imikushin** [comment]
I'll try to answer this, but I need more information to see what exactly is happening: 
 - Are you running a RancherOS VM on EC2 via docker-machine? 
 - What command did you use to run the container? 
 - Where (inside the container, on the RancherOS VM, on the host where you're running docker-machine client) are you expecting the directory to be created? What would be the name of that directory? 
 - What operating system are you running docker-machine client on? 

RancherOS does a lot of bind mounting internally, so the issue might be a little tricky.

**Comment by deniseschannon** [comment]
@ebuildy If you are still having issues, please re-open. We are about to launch v0.4.0 of RancherOS, which is much more useable.
