### ISSUE TITLE
Docker bound to IP

### ISSUE THREAD

**Issue by jwhitcraft** [rancher/os#437]
Hello,

In trying to use RancherOS as a Jenkins Docker host, it's required that Docker be listening on a port.  It does this for me when using it inside of `docker-machine` but when using the ami, i don't see a way to bind it to the ip address of the running ec2 image.  is this possible?

**Comment by ibuildthecloud** [comment]
This should make it listen on a port

```
sudo ros config set user_docker.extra_args [-H,tcp://0.0.0.0:2375]
```

Then reboot or `system-docker restart docker`

TLS is more complicated but instructions are at http://os.docs.rancher.com/docs/configuration/setting-up-docker-tls/

**Comment by ibuildthecloud** [comment]
You can do the above with the cloud config too:

```yaml
rancher:
  user_docker:
    extra_args:
    - -H
    - tcp://0.0.0.0:2375
```

**Comment by jwhitcraft** [comment]
Thanks @ibuildthecloud , i'll give it a shot.

**Comment by deniseschannon** [comment]
@jwhitcraft I'll close this issue and if you have further questions, please re-open or open a new ticket.
