### ISSUE TITLE
Support non-TLS remote Docker

### ISSUE THREAD

**Issue by ndarilek** [rancher/os#449]
I'm attempting to connect a Jenkins container to the Rancher OS host Docker to perform builds. The host is a VM which is mostly not internet accessible, so it should be safe to expose port 2375. Yet all I see is how to enable TLS access to the Docker daemon.

Is it at all possible to enable non-secure access to 2375? Not sure if my Jenkins plugin supports accessing the TLS port. I used to do this under CoreOS with 2375 blocked via iptables.

Thanks.

**Comment by imikushin** [comment]
@ndarilek you can configure Docker daemon on RancherOS by setting `rancher.user_docker.args` property in your cloud-config or by using 
```
ros config set user_docker.args \
  [docker, -d, -s, overlay, -G, docker, -H, 'unix:///var/run/docker.sock', \
   --userland-proxy=false, \
   -H, tcp://0.0.0.0:2375]
```

There's `os-config.yml` file where you can look at various configuration options to use with `ros config` or in your cloud-config file (these should be `rancher.` subkeys in your cloud-config).

**Comment by ndarilek** [comment]
Thanks! In poking around in other issues, it looks like you can also do:

sudo ros config set user_docker.extra_args [-H,tcp://0.0.0.0:2375]

which I like more, since it doesn't interfere with your own args.

This works great now, I can replace my creaky Debian VM with something
having the newest Docker and kernel. :)

**Comment by deniseschannon** [comment]
@ndarilek Just a quick note, if you are using this RancherOS instance to be added to Rancher, you'll need to enable the unix socket as well. 

This is based on https://github.com/rancher/rancher/issues/1670

**Comment by ebuildy** [comment]
Is it possible to configure this with cloud-data for AWS?

**Comment by ebuildy** [comment]
BTW the right command is:

    sudo ros config set rancher.docker.extra_args "['-H','tcp://0.0.0.0:2375']"

<!> Pay a big attention to double and simple quote like this <!>
