### ISSUE TITLE
SELinux Support

### ISSUE THREAD

**Issue by sammcj** [rancher/os#45]
SELinux and / or GRSecurity would greatly improve the potential for rancher to be used in production environments.

**Comment by ibuildthecloud** [comment]
It's important that we do stick with a stock Linux kernel, but I think the idea of a GRSec flavor in addition to the stock kernel is interesting.  I'm general I'd like people to be able to build their own custom kernel.  I'll keep that in mind and hopefully come up with a simple way to swap out the kernel to one of your choosing.

SELinux is definitely on our roadmap.

**Comment by deniseschannon** [comment]
@sammcj I've updated the issue to only supporting SElinux. If you still want GRSecurity, please open a new issue.

**Comment by SvenDowideit** [comment]
lets push to when Docker 1.13 has had time to settle

**Comment by jonaz** [comment]
Any update on selinux? We are evaulating new OS since coreos will be gone. But we really really need selinux support.

**Comment by niusmallnan** [comment]
Duplicate of #2440 
Close this.
