### ISSUE TITLE
filesystem volumes

### ISSUE THREAD

**Issue by Netw0rkeu** [rancher/os#473]
Hello,

how does filesystem volumes work in rancheros? In ubuntu I just use:
```sh
docker run -v /app/persistent/mysql:/var/lib/mysql -p 3306:3306 --name MariaDB -e MYSQL_ROOT_PASSWORD=password -d mariadb
```
Then is the data stored in /app/persistent/mysql. This dosn't works for rancher. I get no error logs.

My host system is OSX 10.10.4. My vagrant file:
> require_relative 'config/vagrant_rancheros_guest_plugin.rb'
> 
> VAGRANTFILE_API_VERSION = "2"
> 
> Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
>   config.vm.provider "virtualbox" do |v|
>     v.memory = 1024
>     v.cpus = 1
>   end
> 
>   config.vm.box   = "rancherio/rancheros"
>   config.vm.box_version = ">=0.3.3"
> 
>   config.vm.network "private_network", ip: "192.168.200.200"
> 
>   config.vm.synced_folder ".", "/app", type: "rsync",
>     rsync__exclude: ".git/", rsync__args: ["--verbose", "--archive", "--delete", "--copy-links"],
>     disabled: $rsync_folder_disabled
> 
> 
>   config.vm.synced_folder ".", "/app"
> 
>   config.vm.provision "docker"
>   
>   config.vm.define "docker"
>   
>   config.vm.provision "shell",
>     :path => "config/startup.sh",
>     run: "always"
> 
> end

**Comment by imikushin** [comment]
@Netw0rkeu in what sense does it not work? You won't see `/app/persistent/mysql` in the console, though. Console is actually a container: `sudo system-docker inspect console`. To be able to see your data from the console, you might want to use an `/opt` or `/home` sub-directory on the part of the "real" filesystem.

**Comment by ibuildthecloud** [comment]
@Netw0rkeu this is really a usuability issue with RancherOS and has been resolved in v0.4 (not released yet). In 0.4 it will behave just the same.

There is a bigger problem though.  Only /home, /opt are really persisted over time.  If you save things to a different directory they will get deleted.

**Comment by deniseschannon** [comment]
With v0.4.4, this should be fixed. @Netw0rkeu Please open a new issue if you have further questions.

**Comment by CumpsD** [comment]
@deniseschannon could you give some more info please? will 0.4.4 store all changes? or still only /home and /opt?

**Comment by joshwget** [comment]
@CumpsD v0.4.4 still stores just `/home` and `/opt`
