### ISSUE TITLE
RancherOS latest ISO issue on VirtualBox

### ISSUE THREAD

**Issue by sjkeerthi** [rancher/os#478]
Hi All,

After I installed rancheros on virtualbox successfully. But after reboot I could see it was not able to boot successfully.
 
This was working on my previous version of RancherOS.

Attach the screenshot below.

![screenshot from 2015-08-12 00 13 17](https://cloud.githubusercontent.com/assets/4696166/9206709/0dc7c278-4087-11e5-94a8-5c7aef554d7e.png)

**Comment by imikushin** [comment]
@sjkeerthi This is a known issue and is being tracked in #389, so I'm closing this one. 
Can you provide the cloud-config you're using with `rancheros-install` in a comment to #389, and confirm it happens on RancherOS v0.3.3?
