### ISSUE TITLE
rkt v0.7.0 doesn't work with rancher-os v0.3.3

### ISSUE THREAD

**Issue by xaduha** [rancher/os#480]
I know that the fault here lies squarely with coreos/rkt, but there might be some workaround that would increase overall compatibility.

https://github.com/coreos/rkt/issues/1076

AFAIK Rancher OS doesn't mount cgroups at all, I used this [script](https://github.com/tianon/cgroupfs-mount), but no dice. Apparently it works fine on Ubuntu 14.04 LTS, even though it doesn't have systemd.

I'd like to move to Rancher OS from CoreOS, but I'd like to keep rkt around too just in case.

**Comment by ibuildthecloud** [comment]
@xaduha We are releasing v0.4 very soon and this should be fixed.  What is the rkt command you were trying so I can reproduce?

**Comment by ibuildthecloud** [comment]
@xaduha I just tried and got the following error on a beta build of `v0.4`
```
sudo ./rkt --insecure-skip-verify run coreos.com/etcd:v2.0.4
rkt: searching for app image coreos.com/etcd:v2.0.4
rkt: found image in local store, skipping fetching from https://github.com/coreos/etcd/releases/download/v2.0.4/etcd-v2.0.4-linux-amd64.aci
2015/08/13 22:27:03 Preparing stage1
2015/08/13 22:27:03 Loading image sha512-1eba37d9b344b33d272181e176da111ef2fdd4958b88ba4071e56db9ac07cf62
2015/08/13 22:27:03 Writing pod manifest
2015/08/13 22:27:03 Setting up stage1
2015/08/13 22:27:03 Writing image manifest
2015/08/13 22:27:03 Wrote filesystem to /var/lib/rkt/pods/run/f515fbe7-6167-450d-86d5-8ad932f49e33
2015/08/13 22:27:03 Writing image manifest
2015/08/13 22:27:03 Pivoting to filesystem /var/lib/rkt/pods/run/f515fbe7-6167-450d-86d5-8ad932f49e33
2015/08/13 22:27:03 Execing /init
2015/08/13 22:27:03 Put http://unixsock/pods/f515fbe7-6167-450d-86d5-8ad932f49e33?token=a79eb36f22ae53a0580f8d1256be3134: dial unix /run/rkt/metadata-svc.sock: no such file or directory
2015/08/13 22:27:04 Put http://unixsock/pods/f515fbe7-6167-450d-86d5-8ad932f49e33?token=a79eb36f22ae53a0580f8d1256be3134: dial unix /run/rkt/metadata-svc.sock: no such file or directory
2015/08/13 22:27:05 Put http://unixsock/pods/f515fbe7-6167-450d-86d5-8ad932f49e33?token=a79eb36f22ae53a0580f8d1256be3134: dial unix /run/rkt/metadata-svc.sock: no such file or directory
2015/08/13 22:27:06 failed to register the pod: failed to register pod with metadata svc: could not reach the metadata service.
Make sure metadata service is currently running.
For more information on running metadata service,
see https://github.com/coreos/rkt/blob/master/Documentation/metadata-service.md
```

**Comment by ibuildthecloud** [comment]
I forgot to run the metadata service so after starting that I get the following

```
sudo ./rkt --insecure-skip-verify run coreos.com/etcd:v2.0.4
rkt: searching for app image coreos.com/etcd:v2.0.4
rkt: found image in local store, skipping fetching from https://github.com/coreos/etcd/releases/download/v2.0.4/etcd-v2.0.4-linux-amd64.aci
2015/08/13 22:37:58 Preparing stage1
2015/08/13 22:37:58 Loading image sha512-1eba37d9b344b33d272181e176da111ef2fdd4958b88ba4071e56db9ac07cf62
2015/08/13 22:37:58 Writing pod manifest
2015/08/13 22:37:58 Setting up stage1
2015/08/13 22:37:58 Writing image manifest
2015/08/13 22:37:58 Wrote filesystem to /var/lib/rkt/pods/run/e7b7c92b-780c-4db5-bf1f-ef302b4050f1
2015/08/13 22:37:58 Writing image manifest
2015/08/13 22:37:58 Pivoting to filesystem /var/lib/rkt/pods/run/e7b7c92b-780c-4db5-bf1f-ef302b4050f1
2015/08/13 22:37:58 Execing /init
2015/08/13 22:37:58 PUT /pods/e7b7c92b-780c-4db5-bf1f-ef302b4050f1?token=7749763cda49da0fcdb9a4d8dbc5b2d4 - 200
2015/08/13 22:37:58 PUT /pods/e7b7c92b-780c-4db5-bf1f-ef302b4050f1/etcd - 200
Continuing with per-app isolators disabled: could not get own cgroup path: controller "name=systemd" not found
```

**Comment by ibuildthecloud** [comment]
Okay, I got a bit further.  Still no dice, but fun none the less.  (Not all of this is done on a beta build of RancherOS, so probably will be different on 0.3.3)

`rkt` binaries are not fully static so they required glibc.  So you need to switch to the ubuntu/debian console.  Our default console doesn't have glibc.

  `sudo ros service enable ubuntu-console; sudo reboot`

After reboot setup the `name=systemd` cgroup.

```sh
sudo mkdir /sys/fs/cgroup/systemd
sudo mount -t cgroup -o none,name=systemd cgroup /sys/fs/cgroup/systemd
```

Now run `rkt`

```sh
sudo ./rkt --insecure-skip-verify run coreos.com/etcd:v2.0.4
rkt: searching for app image coreos.com/etcd:v2.0.4
rkt: found image in local store, skipping fetching from https://github.com/coreos/etcd/releases/download/v2.0.4/etcd-v2.0.4-linux-amd64.aci
2015/08/14 03:19:21 Preparing stage1
2015/08/14 03:19:21 Loading image sha512-1eba37d9b344b33d272181e176da111ef2fdd4958b88ba4071e56db9ac07cf62
2015/08/14 03:19:21 Writing pod manifest
2015/08/14 03:19:21 Setting up stage1
2015/08/14 03:19:21 Writing image manifest
2015/08/14 03:19:21 Wrote filesystem to /var/lib/rkt/pods/run/2d8ad055-588c-4fc3-85a4-ca47c331b6a2
2015/08/14 03:19:21 Writing image manifest
2015/08/14 03:19:21 Pivoting to filesystem /var/lib/rkt/pods/run/2d8ad055-588c-4fc3-85a4-ca47c331b6a2
2015/08/14 03:19:21 Execing /init
[!!!!!!] Failed to allocate manager object, freezing.
```

**Comment by ibuildthecloud** [comment]
I got it working.  So first you probably need to be running v0.4, not totally sure, but if you have ubuntu console running the following should get you going.

```
sudo mkdir /sys/fs/cgroup/systemd
sudo mount -t cgroup -o none,name=systemd cgroup /sys/fs/cgroup/systemd
sudo mkdir /sys/fs/cgroup/systemd/user
sudo echo $$ | sudo tee /sys/fs/cgroup/systemd/user/cgroup.procs

sudo ./rkt metadata-service &
sudo ./rkt --insecure-skip-verify run coreos.com/etcd:v2.0.4
```

**Comment by ibuildthecloud** [comment]
Sounds ironic, but I'll probably create a `docker run rkt` if it doesn't exist :smile:  Just too hard to pass up that inception.

**Comment by ibuildthecloud** [comment]
v0.4 will most likely have out of the box support for rkt.  I'll put in a PR today.  I can't say that we will actively test this going forward, but the blocking issues I see now I can fix in RancherOS.

**Comment by xaduha** [comment]
Looking forward to it!

I tried it on rancher-os v0.4.0-rc1, I guess it sort of works, but not quite. Both rkt v0.7.0 and v0.8.0-rc1.

For that etcd image I have "Failed to allocate manager object, freezing" error, but
```
sudo ./rkt list
```
shows it as running and 
```
sudo ./rkt enter <id> /etcd
```

launches etcd just fine.

**Comment by xaduha** [comment]
Adding --debug=true using rkt v0.8.0-rc1 yeilds
```
Failed to install release agent, ignoring: Read-only file system
Failed to create root cgroup hierarchy: Read-only file system
Failed to allocate manager object: Read-only file system
```
I guess I have a Read-only filesystem. I'm booting rancher-os using gummiboot, but I have RANCHER_STATE disk though. I tried installing using v0.4.0-rc1 rancheros-install script, but even though is reports success, it doesn't work for me. I'll try installing v0.3.3 and then switching vmlinuz and initrd for v0.4.0-rc1.

**Comment by iaguis** [comment]
Some more info: https://github.com/coreos/rkt/issues/1076#issuecomment-134170218

**Comment by xaduha** [comment]
@ibuildthecloud

rkt v0.8.0 works with rancher-os v0.4.0-rc1 with that workaround, but not with rc2 and rc3. "error rendering overlay filesystem", empty and not accessible manifest file.

```
$ cat manifest
cat: manifest: No such device or address
```

**Comment by ibuildthecloud** [comment]
@xaduha each RC we've been changing a huge amount.  By the time we release expect rkt to work unmodified in an Ubuntu/Debian console.

**Comment by gdm85** [comment]
Thanks @ibuildthecloud for the workaround you provided, that fixed it for me on Ubuntu 14.04.03 LTS

**Comment by xaduha** [comment]
Fixed upstream.

**Comment by ibuildthecloud** [comment]
@xaduha if you run the latest v0.4 RC rkt 0.8 works out of the box too.  But I'm glad this was fixed upstream too.
