### ISSUE TITLE
Orphan files in filesystem root

### ISSUE THREAD

**Issue by ndarilek** [rancher/os#483]
Apologies if I missed this and it has already been filed, I can't think of suitable search terms.

When working on a RancherVM instance, I did something like:

    cd /
    tar cf home.tar home

Then I scp'd home.tar to another system and rebooted the VM.

When it came back up, I noticed that it was using more disk space than I'd expected. In particular, it was using 50G, roughly twice the space of the 25G /home.

I did a bit of digging and discovered that /var/lib/system-docker was 25G. A bit of extra work turned up home.tar hiding in one of the overlay directories even though /home.tar no longer existed. Removing it brought disk usage down as expected.

I recognize that /opt and /home are the only stateful directories, which was my expectation when I created /home.tar temporarily. What surprised me was /home.tar vanishing only to continue existing in an overlay directory. It might be nice if non-stateful files could be removed from overlays somehow. Makes me wonder if cruft may persist between boots and eventually come to fill my disks, and if there's anything I might do about it (other than use huge disks and postpone the problem.) But if I'm told that /opt and /home are the only stateful locations, then I'd expect for anything not in those directories to be blown away between boots.

Thanks.

**Comment by ibuildthecloud** [comment]
In rancheros v0.3.3 no containers are ever really deleted from system-docker.  Do a `system-docker ps -a` and you should see a lot of old containers.   You can just delete those.  This has been changed in v0.4, which has not been released yet.  In v0.4 the ephemeral containers are actually deleted.

**Comment by deniseschannon** [comment]
@ndarilek Please re-open if you have this issue in v0.4.4.
