### ISSUE TITLE
v0.4: Invalid cloud-config panic boots

### ISSUE THREAD

**Issue by ibuildthecloud** [rancher/os#487]
If you pass in a poorly formatted cloud-config `./script/run --cloud-config bad.yml` on boot it panics.  Couple things.  We should never show a panic unless some really bad happened.  I know a panic shows a stack traces but a good error message is just as useful for debugging.  Also we shouldn't halt the boot if the cloud-config is bad.

Finally, it seems that once you pass in a bad cloud-config you can never boot the system again as it has cached the file.

**Comment by imikushin** [comment]
should be fixed now ;)
