### ISSUE TITLE
Issues with compiling

### ISSUE THREAD

**Issue by Rucknar** [rancher/os#491]
OS: 	Ubuntu 14.04.3 LTS
Docker:  version 1.8.1, build d12ea79

Cloned the repo to local folder and run the make command, i'm getting the errors below:

```
root@ubuntu:~/os# make
docker build -t ros-build -f Dockerfile.build .
Sending build context to Docker daemon 7.297 MB
Step 0 : FROM ros-build-base
Pulling repository docker.io/library/ros-build-base
Error: image library/ros-build-base:latest not found
make: *** [ros-build-image] Error 1
```

I presume i'm simply missing some kind of dependency but i'm struggling to figure out just what, something i'm putting down to the fact it's Friday and i've been coding powershell scripts all morning.

**Comment by imikushin** [comment]
Just do ./build.sh first.

**Comment by Rucknar** [comment]
I'm an idiot.

**Comment by Rucknar** [comment]
Thanks though :)

**Comment by imikushin** [comment]
Glad to help :)

**Comment by ibuildthecloud** [comment]
@imikushin This is really and issue in our build scripts.  Running make by itself shouldn't ever fail.  Why doesn't `ros-build-image` depend on `ros-build-base`?
