### ISSUE TITLE
v0.4.0-rc1 - ros config export shows users section but it's not supported

### ISSUE THREAD

**Issue by deniseschannon** [rancher/os#492]
When I do a `ros config export`, the file looks like:

```
ssh_authorized_keys:
write_files:
hostname:
users:
rancher: 
```

Since RancherOS doesn't support users, we need to hide the `users` section.

**Comment by imikushin** [comment]
We can't hide the `users` section, because we do support `rancher` and `docker` users, and this section can be used to configure them.

**Comment by ibuildthecloud** [comment]
@imikushin What can be changed?  I don't believe we have any code to support users element in cloud-config right now.

**Comment by ibuildthecloud** [comment]
@imikushin Oh yes, I forgot.  We only support the ssh_keys param of users.

**Comment by ibuildthecloud** [comment]
@deniseschannon I would close this issue.  Do we have a general issue anywhere to support more fields?

**Comment by imikushin** [comment]
@deniseschannon @ibuildthecloud I just did a quick test: in fact, we can remove `users` from our cloud-config, at least for now as we really get `rancher` and `docker` users' authorized keys from the top level `ssh_authorized_keys` cloud-config property.

**Comment by deniseschannon** [comment]
@ibuildthecloud Yes, we have an issue to support users in another place. https://github.com/rancher/os/issues/263
