### ISSUE TITLE
Initial `ros os upgrade` fails to find network.

### ISSUE THREAD

**Issue by deniseschannon** [rancher/os#495]
When I use `ros os upgrade` the first time, it fails to find the network but will seem to eventually start.

If I try the same command after, the error is gone.

```
$ sudo ros os upgrade -s
ERRO[0001] Failed to find network
ERRO[0001] Failed to find network
INFO[001] [0/1] [os-upgrade]: Starting
INFO[0029] Redbuilding once_os-upgrade_1
INFO[0029] [1/1] [os-upgrade]: Started
INFO[0029] Project [once]: Project started
```

**Comment by ibuildthecloud** [comment]
We need to swtich CreateService() to use the "os" project name and not "once"

**Comment by imikushin** [comment]
Using "os" doesn't help. The reason: we don't persist projects, so we can't recover a project by name and use it to lookup a service.
