### ISSUE TITLE
v4.0 rc1 - ros config issues

### ISSUE THREAD

**Issue by Rucknar** [rancher/os#503]
Testing on v4.0 rc1:

- `sudo ros config get network` shows nothing (before it would output network config
- `sudo ros config set `... commands don't error but config isn't there on container restart so doesn't appear to be being set correctly.

**Comment by deniseschannon** [comment]
We've re-configured to remove the `rancher.yml` file and use a general `cloud-config-local.yml` file. For networking, you'll need to use the `rancher` key in front of everything.

`sudo ros config get rancher.network`

Please note that v0.4.0-rc1 is still being heavily tested. :)

**Comment by Rucknar** [comment]
Thanks for the heads up, i've successfully used the above and it set the config fine. 
Appreciate it's still in development, was keen to use it for testing out the new logging drivers in docker 1.8.1 in a server environment :)
