### ISSUE TITLE
Approach for running a private registry

### ISSUE THREAD

**Issue by JamesBarwell** [rancher/os#509]
I'm hoping that someone could please advise on the best approach for running a private registry. This issue sits somewhat between Rancher and RancherOS, but I think it will only manifest for users running RancherOS so it felt more appropriate to file it here.

We have three RancherOS hosts, with 01 running Rancher and managing 02 and 03 hosts. I have set up a private registry container (using Rancher) on the 02 host, using certificates signed by our organisation's PKI. The registry is functioning correctly when accessed by external clients.

I followed the instructions here, and found that they're not very clear when working with RancherOS: http://docs.rancher.com/rancher/configuration/registries

Issues I encountered:
1. The instructions for self-signed certs do not say where to run the commands, but I found that they need to be done in the userdocker container.
2. The instructions make use of openssl which is not available in that container, so I had to copy+paste the certificate in over SSH.
3. The instructions - if I could use openssl here - would only work with a single self-signed certificate, as they strip off subsequent certificates in a chain. This command works with a certificate chain:
```
openssl s_client -showcerts -connect {host}:{port} </dev/null 2>/dev/null | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > /etc/docker/certs.d/{host}:
{port}/ca.crt
```
(though I'm not clear on whether Docker verifies the chain, so perhaps trying to use our PKI is the wrong approach.)

I have a DNS record pointed at the 02 host so that clients can use this to refer to the registry. My problem now is to do with connectivity from within the 02 userdocker container to this address.

```
# From 02 host userdocker, talking back to itself
bash-4.3# ping registry.domain.com
PING registry.domain.com (xxx.xxx.xxx.02): 56 data bytes
64 bytes from xxx.xxx.xxx.02: seq=0 ttl=64 time=0.190 ms
64 bytes from xxx.xxx.xxx.02: seq=1 ttl=64 time=0.108 ms

bash-4.3# telnet registry.domain.com 5000
telnet: can't connect to remote host (xxx.xxx.xxx.02): Connection refused
# nothing shows up in the registry logs here either
```
```
# From 03 host userdocker, talking to the 02 host
bash-4.3# ping registry.domain.com
PING registry.domain.com (xxx.xxx.xxx.02): 56 data bytes
64 bytes from xxx.xxx.xxx.02: seq=0 ttl=64 time=1.919 ms
64 bytes from xxx.xxx.xxx.02: seq=1 ttl=64 time=0.562 ms

bash-4.3# telnet registry.domain.com 5000
^C
Console escape. Commands are:

 l      go to line mode
 c      go to character mode
 z      suspend telnet
 e      exit telnet
```
So I'm able to bring up a container using an image from the registry, but only on the 03 host. The 02 host cannot connect to itself to pull down the image.

I'm not sure if this is a bug or maybe just a consequence of the way I've set this up (I would ideally like two redundant registries behind a load balancer once TLS support is merged). I can of course get around this by running the registry on a separate host from any containers based on the registry's images, but wondered if anyone had any thoughts on my approach here. Cheers.

**Comment by deniseschannon** [comment]
This is only supported in v0.4.0+. We've added documentation on how to do this in v0.4.0. The docs will be updated when v0.4.0 is officially released.
