### ISSUE TITLE
v0.4.0-dev: enabling debian- or ubuntu-console is ignored if labeled as persistent

### ISSUE THREAD

**Issue by imikushin** [rancher/os#516]
Well, not completely ignored, but all you get (instead of your new console) is these messages in the boot log:
```
WARN[0006] os_console_1 needs rebuilding                
WARN[0006] os_console_1 needs rebuilding                
WARN[0006] os_console_1 needs rebuilding                
WARN[0006] os_console_1 needs rebuilding                
```

**Comment by imikushin** [comment]
Happens when `io.docker.compose.rebuild: false` label is set on debian-console and ubuntu-console services.

**Comment by imikushin** [comment]
This should be fixed by #528 and #531

**Comment by imikushin** [comment]
But's not

**Comment by deniseschannon** [comment]
Update on v040-rc3. When I enable ubuntu or debian, I can no longer do anything in system-docker or user docker even if I disable both to get back to busy box.  After enabling a console, I am able to log in but not sure which console is running per the errors below.

```
$ sudo system-docker ps
FATA[0000] no such file or directory
$ docker ps
-bash: docker: command not found
```
