### ISSUE TITLE
Mount an additional persistent storage for storing images

### ISSUE THREAD

**Issue by drbolsen** [rancher/os#525]
Hi there,

I couldn't find any comprehensive information in regards to the topic, so raising question here. 

I have the following use case: 

  - mount an additional persistent storage (large), e.g. /dev/sdb - > /var/lib/mycontainer_space
  - configure docker service to store by default all images/containers into the new storage (e.g. -g /mnt_point)
  - persist these settings

Looking at Rancher OS configuration I noticed that currently it is implemented via *-volumes, e.g. system-volumes, docker-volumes, etc. But I couldn't yet grasp the concept.

Any practical example is much appreciated.

Cheers

**Comment by imikushin** [comment]
rancher/rancher.github.io#342

**Comment by deniseschannon** [comment]
This will be released in the docs when v0.5.0 is released
