### ISSUE TITLE
RancherOS is unreachable after upgrade to 0.4 rc2

### ISSUE THREAD

**Issue by pwFoo** [rancher/os#526]
I updated to version 0.4 rc2 with "sudo ros os upgrade -i rancher/os:v0.4.0-rc2". It seams to be sucessful, but no ping or ssh after reboot. 
Because hardware have no monitor and serial console with password login not working with RancherOS I can't take a look at the boot process. 

I updated on own risk and it's just a test environment, so I think I have to reinstall it. Just would give you feedback about my upgrade test.

**Comment by deniseschannon** [comment]
We haven't documented it yet, but due to the major refactoring in v0.4.0, we will not be supporting upgrading from v0.3.3 to v0.4.0.
