### ISSUE TITLE
Error while validating  rancheros 0.4.4-rc3 via iso 

### ISSUE THREAD

**Issue by sjkeerthi** [rancher/os#538]
Hi All,

I am trying to validate rancheros.iso 0.4.4 on virtualbox after I try to install the rancheros with below command.

It throw an error that It could not able to find the rc3 image.

sudo rancheros-install -c cloud-config -d /dev/sda 
No install type specified...defaulting to generic
All data will be wiped from this device
Partition: true
DEVICE: /dev/sda
Are you sure you want to continue? [yN]yUnable to find image 'rancher/os:v0.4.0-rc3' locally
Pulling repository docker.io/rancher/os
Tag v0.4.0-rc3 not found in repository docker.io/rancher/os

**Comment by deniseschannon** [comment]
The docker image hasn't been pushed to DockerHub as DockerHub was having issues. With that said, the image is now up. Please be cautious that there are definite issues with this release as we are still going through testing.
