### ISSUE TITLE
rtl_nic formware load error during ipxe boot

### ISSUE THREAD

**Issue by pwFoo** [rancher/os#540]
During boot RancherOS (latest stable and also 0.4.0-rc3 tested) I get the following error.

    INFO[0008] [11/17] [network]: Starting                  
    [   34.730113] r8169 0000:01:00.0: Direct firmware load for rtl_nic/rtl8168e-2.fw failed with error -2
    [   34.739268] r8169 0000:01:00.0 eth0: unable to load firmware patch rtl_nic/rtl8168e-2.fw (-2)
    [   34.760587] r8169 0000:01:00.0 eth0: link down

But nic is used for ipxe boot before without problems.

    [   32.358441] device vethaf897de entered promiscuous mode
    [   32.364372] IPv6: ADDRCONF(NETDEV_UP): veth2de7183: link is not ready
    [   32.371120] IPv6: ADDRCONF(NETDEV_CHANGE): veth2de7183: link becomes ready
    [   32.474582] eth0: renamed from veth2de7183
    INFO[0007] [6/17] [syslog]: Started                     
    [   32.732714] veth2de7183: renamed from eth0
    [   32.777691] docker-sys: port 1(vethaf897de) entered disabled state
    [   32.785760] device vethaf897de left promiscuous mode
    [   32.790801] docker-sys: port 1(vethaf897de) entered disabled state

**Comment by ibuildthecloud** [comment]
Thanks for reporting this.  I too have seen some firmware loading issues.  Let me investigate if firmware is not being detected properly or maybe that firmware is wrong in the updated kernel.

**Comment by ibuildthecloud** [comment]
@pwFoo Did iPXE ultimately fail?  I just looked in v0.3.3 we only packaged the following firmware

```
lib/firmware/qlogic/sd7220.fw
lib/firmware/bnx2x/bnx2x-e1-7.8.17.0.fw
lib/firmware/bnx2x/bnx2x-e1h-7.8.17.0.fw
lib/firmware/bnx2x/bnx2x-e2-7.8.17.0.fw
lib/firmware/bnx2/bnx2-rv2p-06-6.0.15.fw
lib/firmware/bnx2/bnx2-rv2p-09-6.0.17.fw
lib/firmware/bnx2/bnx2-mips-09-6.2.1b.fw
lib/firmware/bnx2/bnx2-mips-06-6.2.3.fw
lib/firmware/bnx2/bnx2-rv2p-09ax-6.0.17.fw
lib/firmware/e100/d101s_ucode.bin
lib/firmware/e100/d101m_ucode.bin
lib/firmware/e100/d102e_ucode.bin
lib/firmware/tigon/tg3.bin
lib/firmware/tigon/tg3_tso.bin
lib/firmware/tigon/tg3_tso5.bin
```

and basically the same for v0.4.0-rcX

**Comment by pwFoo** [comment]
It should boot up, but without a configured nic. 
So I can't login with SSH.

RancherOS don't supports serial console output. To See it booting up I added "console=ttyS0,115200" as kernel param.

Could it DHCP related? I don't know why, but it fails with eth0 (static dhcp entry) and works fine with eth1 and eth2. After RancherOS is installed eth0 connects without problems.

After tried "ros os upgrade' RancherOS install isn't able to reboot.
So maybe I could test it again in the next few days. Also with deleted static dhcp Entry.

**Comment by pwFoo** [comment]
Some more tests done at home... Also with RC5 behind a Fritzbox (dhcp) because it's my home network.

ssh login isn't possible if interfaces eth1 or eth2 is used. Set an ip address within the dhcp range works. RancherOS can't configure a dhcp ip address at eth0 because there is a static lease. Removed the static lease and iPXE boots ip without problems.

**Comment by pwFoo** [comment]
It could be an iPXE issue?
Static dhcp lease works fine after RancherOS is installed and to get an ip address at ipxe boot promt.

After loading vmlinuz and initrd RancherOS boots successful, but can't get the nic up.

Removed static lease, tried again and it works fine... ?!

**Comment by ibuildthecloud** [comment]
@pwFoo This does not address your issue, but we are package the rtl firmware now in v0.4.  Will be in rc9.

**Comment by pwFoo** [comment]
Thanks for information. 
I'll try it again with v0.4(rc9) and post results here.
Maybe issue will be solved with some updates and rtl firmware.

**Comment by pwFoo** [comment]
The errors appears again, but it's boot up and finally reachable with ping / ssh. So it should work.

Static dhcp lease configured at Fritzbox seems to be an problem for ipxe, but that shouldn't related to RancherOS...

So if nobody experience problems or erros the issue should be closes...

**Comment by AndreiCherniaev** [comment]
> 

**firmware d102e_ucode.bin for driver e100 missing**

How I can fix it? Method A. Do steps:
0) My board's driver mount to my laptop on _/media/a/rootfs_
1) cd /media/a/rootfs/lib/firmware/
2) mkdir e100 
3) copy [d102e_ucode.bin](https://gitlab.freedesktop.org/frankbinns/linux-firmware/-/tree/powervr/e100) to your board's drive
sudo cp /home/a/myb/d102e_ucode.bin /media/a/rootfs/lib/firmware/
4) Now it should be work.

Or use alternative method B. Just set this:

![Screenshot from 2022-11-15 13-36-17](https://user-images.githubusercontent.com/27889022/201828397-4e450359-a395-44ec-9f29-83a318913c06.png)
