### ISSUE TITLE
Add convoy plugin to RancherOS?

### ISSUE THREAD

**Issue by pwFoo** [rancher/os#542]
I tried to install convoy plugin, but can't extract the tar file from RancherOS console.
Shouldn't convoy shipped with RancherOS?

**Comment by pwFoo** [comment]
Tried to install convoy plugin to RancherOS following the quick start guide.
    $ tar xvf convoy.tar.gz 
    tar: invalid tar magic

**Comment by pwFoo** [comment]
Will convoy preinstalled with newer / next RancherOS?

**Comment by deniseschannon** [comment]
Convoy will not be in the next release. We have been in final stages of testing and will not be able to put it in. If there is enough user interest, we could prioritize it in the a future release.

**Comment by pwFoo** [comment]
Thanks for reply. 
After some testing with CoreOS, Fedora / CentOS Atomic and Kubernetes I changed to Rancher / RancherOS and like what I see. Great work and progress! 

Convoy should be a way to move from data only containers to persistent convoy volumes. Would love to see it in one of the following releases.

**Comment by pwFoo** [comment]
Tested convoy with 0.4 rc4 based on host directory (vfs). Share Volumens works fine (just copied, so missed after reboot.

Could convoy be added AS os-service like ubuntu / Debian console? Persistent and optional. Preconfigured with vfs and a host directory AS Volumens storage (could be customized to additional partition / devicemapper by a custom partition layout (#552)?.

**Comment by pwFoo** [comment]
Created a new issue for my request to add convoy as os-service (#567).
So I close this issue now.

**Comment by jhmartin** [comment]
@pwFoo your untar command is handled by first `gunzip` convoy.tar.gz then `tar xvf convoy.tar`.
