### ISSUE TITLE
v0.4.0-rc5 Unable to launch mysql container in user docker

### ISSUE THREAD

**Issue by deniseschannon** [rancher/os#544]
Have not been able to launch mysql container in user docker, but was able to run same command in system-docker with no issues.

Steps to Reproduce:

1. Install RancherOS 
2. Reboot
3. Enable ubuntu-console (sudo ros service enable ubuntu-console)
4. Reboot
5. `docker run -d -e MYSQL_ROOT_PASSWORD=test mysql`

Container fails to launch and logs of container show

```
2015-09-01 21:40:43 67 [Note] mysqld: Shutdown complete

MySQL init process in progress...
MySQL init process in progress...
```

**Comment by imikushin** [comment]
@deniseschannon Could not reproduce :confused:
