### ISSUE TITLE
v0.4.0-rc5 - Unable to reboot after any container is running in user docker when in an ubuntu or debian console

### ISSUE THREAD

**Issue by deniseschannon** [rancher/os#545]
RancherOS gets stuck with this in console before rebooting when nginx container is running.

Steps to Reproduce
1. `rancheros-install`
2. reboot
3. enable ubuntu `sudo ros service enable ubuntu-console`.
4. reboot
5. `docker run -d nginx`
6. reboot (stuck and never starts up again)

**Comment by imikushin** [comment]
Reproduced, also with debian-console.

**Comment by deniseschannon** [comment]
Works fine in busy box, but not the other consoles

**Comment by deniseschannon** [comment]
This is not nginx contianer specific, but with any container that is started on user docker in either ubuntu or debian console.

**Comment by imikushin** [comment]
Docker-1.8.2 is out (see #562), but the bug is still present.

**Comment by imikushin** [comment]
Fixed in master now

**Comment by deniseschannon** [comment]
Verified in v0.4.0-rc6.
