### ISSUE TITLE
Lots of messages appear on the console

### ISSUE THREAD

**Issue by sheng-liang** [rancher/os#548]
I installed 4.0 RC5 to /dev/sda, and set grub.conf to enable console login. After reboot and login to the console, I see lots of messages on the console. They seem to be network related. There's an error about duplicate IPv6 address.
![messages](https://cloud.githubusercontent.com/assets/9485278/9641464/ad9fa56e-516b-11e5-992e-7de94594b909.png)

**Comment by imikushin** [comment]
These messages are kernel logging. They can be disabled with a kernel parameter `quiet` in the bootloader config. I'd leave them on right now, but this is really a matter of preference.

**Comment by sheng-liang** [comment]
I did not see them in prior releases. Something changed? Shouldn't the messages go into a log?

**Comment by deniseschannon** [comment]
When booting from iso, we have made the kernel logging quiet, but by default, we have not turned on `quiet` for when installing to disk. 

We will not be changing this behavior.
