### ISSUE TITLE
Custom partition layout

### ISSUE THREAD

**Issue by rmwpl** [rancher/os#552]
Morning guys,

I'm just trying to install RancherOS on bare metal. What was really surprising for me is that you don't allow a custom partition layout.
I wanted to use swap, mount a separate partition for /var/lib and basically do things the proper way instead of using a single partition for everything and running the system without swap.

Is there a chance you might add support for custom partition layout?

**Comment by pwFoo** [comment]
Custom layout would be great to
- move docker containers and images to an additional partition vor hdd.
- add convoy volume storage

**Comment by pwFoo** [comment]
Any update with this feature request?

Is there a way to customize the partition layout?
I would like to mount additional partitions / hdd and move containers / images.

**Comment by pwFoo** [comment]
Any plans to add custom partition layout to RancherOS? 
Local (custom partition layout or second hdd) or remote storage (ceph, nfs) to the RancherOS host?

**Comment by imikushin** [comment]
@rmwpl @pwFoo we'll probably be addressing it in v0.4.1.

**Comment by pwFoo** [comment]
At the moment I try to use Convoy with devicemapper driver on RancherOS, but at the moment RancherOS use the hole disk. Also Convoy [dm_dev_partition.sh](https://raw.githubusercontent.com/rancher/convoy/master/tools/dm_dev_partition.sh)

Is there a way to install RancherOS to a defined parition and get some space for convoy DM?

**Comment by frol** [comment]
FYI, I have successfully modified `set-disk-partitions` and `lay-down-os` scripts (https://github.com/rancher/os/tree/master/scripts/installer) by building a new image based on top of the original `rancher/os:v0.4.3` image and naming it with the same name, so the new one shadowed the previous. This way I have changed the hardcodings to the way I needed and was able to boot into the Rancher OS.

**Comment by frol** [comment]
Ouch, the upgrade OS script rewrites `grub.cfg`, so it will try to boot from `hd0,msdos1` unless you update `grub.cfg` every time manually before rebooting.

**Comment by SvenDowideit** [comment]
I also would like the installer to detect and not break existing OS's - and eventually allow us to update grub/syslinux/windows...  settings without a full ros-install.

**Comment by joshwget** [comment]
In v0.7.0 our installer will have a `--no-format` option. It'll install without reformatting the drive or creating partitions. This will allow you to create whatever partition layout you'd like before running `ros install`. RancherOS will then be installed to the partition labeled `RANCHER_STATE`.

**Comment by aseith** [comment]
I'm a little confused, the last comment says the `--no-format` option is included in v0.7.0. Playing around with this release just now, it looks to me that the option is not accepted with `ros install`. Milestone says it's in v0.8.0, so I suspect we need to wait a little bit more?

**Comment by joshwget** [comment]
Sorry, I was slightly off with my last comment. It's not a flag but an install type, so it's `-t noformat` rather than `--no-format`. This _is_ available in v0.7.0.

**Comment by ibuildthecloud** [comment]
@joshwget Should probably add `-t noformat` to `ros install -h`

**Comment by Vanuan** [comment]
So how do I install grub to `/dev/sda` and rancheros to `/dev/sda1` without rewriting partitions?

I've tried both `sudo ros install -t noformat /dev/sda1` and `sudo ros install -t noformat /dev/sda`
But it looks like bootloader is not installed.

I need this so that partition labeled with RANCHER_SWAP is used.

**Comment by Vanuan** [comment]
It looks like I'd better create another vHDD rather than setup partitions.

**Comment by Vanuan** [comment]
And setting label to RANCHER_SWAP doesn't seem to be working.

I need this:

```
ros config set mounts '[["/dev/sdb","", "swap", ""]]'
```

**Comment by niusmallnan** [comment]
Please check this doc: https://rancher.com/docs/os/v1.x/en/about/custom-partition-layout/
