### ISSUE TITLE
RacherOS - v0.4.0-rc5 Tested on VirtualBox 5.0 

### ISSUE THREAD

**Issue by sjkeerthi** [rancher/os#554]
Hi all 

After the successful installation of rancheros and reboot I could see the with message as docker0 link is not ready. 

When I login into rancheros where I could see docker0 interface been allocated with ip and up.

This scenario was not happened on earlier version. 

Attaching the screen-shot 
![screenshot from 2015-09-06 06 47 45](https://cloud.githubusercontent.com/assets/4696166/9701949/ef6003a4-5463-11e5-8433-dd3d8859d0af.png)
![screenshot from 2015-09-06 06 49 36](https://cloud.githubusercontent.com/assets/4696166/9701951/f7e9ea9e-5463-11e5-8b00-918ab021dcbf.png)

**Comment by sjkeerthi** [comment]
Can someone faced the same issue

**Comment by ibuildthecloud** [comment]
Besides the message on the screen is this causing an issue?  We changed the startup order such that the console starts before docker starts.  So that message you are seeing probably existed before but was being printed earlier.

**Comment by Rucknar** [comment]
I see the same I believe it's correct behaviour, it's actually just stating the IPV6 interface isn't up which is correct in your case as you are using the IPV4 'interface'.

**Comment by deniseschannon** [comment]
@sjkeerthi There are no real issues, so going to close.
