### ISSUE TITLE
[Question]: Customizing RancherOS builds

### ISSUE THREAD

**Issue by prologic** [rancher/os#555]
Just a quick question. I know this isn't documented yet...

What is involved in customizing the RancherOS build(s)? Specifically I'm looking at wanting to customize the AWS AMI build for our own deployments and take advantage of the ``/var/lib/docker/preload`` I read about in the documentation for [pre-packing docker images](http://docs.rancher.com/os/configuration/prepacking-docker-images/)

**Comment by r4j4h** [comment]
I haven't run it, but have you looked at `usr/sbin/rancheros-install -h` (run from within rancher)? I learned about it from [rancher/os-installer](https://github.com/rancher/os-installer).

**Comment by prologic** [comment]
Yeah I haven't tried this tool yet from whin a live rancherOS instance; however I'm looking for more of a way to customize the prebuilt images; specifically the AMI()s).

**Comment by imikushin** [comment]
@prologic if you want to build your own custom AMI, it's absolutely possible to use image preloading. Just use `rancher/os:v0.4.0-dev` container to install RancherOS files to a fresh EBS volume attached to any Linux instance with Docker 1.8.2. You can consult https://github.com/rancher/os/blob/master/scripts/installer/README.md#usage for instructions. 

Basically, you just need to run the container with the
`-f /source/path/archive.tar.gz:/var/lib/docker/preload/archive.tar.gz`. Be sure to also provide `-t amazon-ebs`.

**Comment by prologic** [comment]
Thanks @imikushin (/cc @fud)

**Comment by deniseschannon** [comment]
@prologic If you have more questions, please re-open.
