### ISSUE TITLE
Make linux-headers (kerenel headers) available in AMI

### ISSUE THREAD

**Issue by lindenle** [rancher/os#579]
The Sysdig (http://www.sysdig.org/) monitoring tool requires the kernel headers to be installed to run. I would like to have these made available for rancherOS either as a `.deb` or as a tar file that can be placed in the correct location on he AMI.

Thanks.

**Comment by jas99** [comment]
+1

**Comment by ibuildthecloud** [comment]
This has been included in RancherOS v0.4.  I will close even though it is not officially released.

**Comment by deniseschannon** [comment]
The kernel header is available in the AMI when it's gets publicized. It should be within the next week or two.
