### ISSUE TITLE
After running rancher-install rancheros didn't start ssh  server on the new instance

### ISSUE THREAD

**Issue by hmeftah** [rancher/os#583]
I started VM based on rancheros 0.3.3  and I try to set it up on the hard hisk so I created a cloud-config.yml file and hit rancher-install. 
When rebooting this new VM  ssh server is not starting up so I can't ssh into it . 
Did I miss something in the process or in the cloud-config.yml?

Run nmap against it shows : 
```code 
Not shown: 996 closed ports
PORT     STATE    SERVICE
20/tcp   filtered ftp-data
900/tcp  filtered omginitialrefs
1935/tcp filtered rtmp
3389/tcp filtered ms-wbt-server

port 22 is closed

**Comment by deniseschannon** [comment]
Can you share your cloud-config.yml file? Make sure it looks exactly like what you have including and white spacing.

**Comment by hmeftah** [comment]
cloud-config.yml is as follows:

![cloud-config](https://cloud.githubusercontent.com/assets/4476898/10103002/e4afab4c-63a1-11e5-8724-a35bacbaf953.png)

**Comment by deniseschannon** [comment]
If you have a invalid configuration in your cloud-config.yml, then it won't start up. I'm not an networking expert, but something of this part of your cloud-config.yml is probably causing the error.

```
rancher:
  network:
  dns:
    interfaces:
      eth*:
        dhcp: false
      eth0:
         address: 172.20.2.181
         gateway: 172.20.0.1
         mtu: 1500
```
@hmeftah We're busy working on v0.4.0 which should be coming out this week, so might not get to respond. But I believe in the next version, if there are issues with your cloud-config, we will continue to boot. If you're willing, you could try out v0.4.0-rc7. We just have a couple of minor tweaks that we're adding in.

**Comment by hmeftah** [comment]
ok, thanks I'll give it a try.

**Comment by hmeftah** [comment]
I had a try with rancheros 04-rc6, and I changed my cloud-config.yml file, all works fine now, thanks.
