### ISSUE TITLE
Cuda

### ISSUE THREAD

**Issue by jas99** [rancher/os#584]
Is it possible to install cuda on rancher os for ec2 gpu instances and pass the devices to the user level docker as device by default.

**Comment by jas99** [comment]
@deniseschannon Relp :P
I think kernel mods will be required. Gonna try to load myself also. Keen on your take also.

Thx

**Comment by deniseschannon** [comment]
@jas99 Unfortunately, I'm not too sure how to do what you're discussing, so won't be able to help with this.

**Comment by jas99** [comment]
k np
