### ISSUE TITLE
Start custom os-service before (user-)docker

### ISSUE THREAD

**Issue by pwFoo** [rancher/os#601]
I created a quick and dirty convoy plugin as system-docker container and would add it as os-service.

It have to be loaded before (user-)docker because of used convoy volumes. 
How should look a correct os-service yml file to preload and start my custom service?

Described here:
http://forums.rancher.com/t/add-binary-to-rancheros-as-os-service/501/3

It's an first build and have to be optimized, but it's working with system-docker and (user-)docker.

**Comment by pwFoo** [comment]
Is there a way to start a system-docker container before(!) another container (here: user-docker)?
I know it's easy to start a system-docker container after another by a link.

**Comment by deniseschannon** [comment]
You should be able ot use a label for it. 

http://docs.rancher.com/os/configuration/system-services/#labels

In your case, I think it would be

```
labels:
   io.rancher.os.before: docker
```

**Comment by pwFoo** [comment]
Thanks @deniseschannon !
Haven't found these to labels before...

> io.rancher.os.before / io.rancher.os.after

**Comment by 2devnull** [comment]
@pwFoo  - is this working for you now?
