### ISSUE TITLE
Do not drop default values in "ros config export"

### ISSUE THREAD

**Issue by sheng-liang** [rancher/os#616]
"ros config export" should print default values, otherwise people won't know what the configuration really is.

For example, if I set "eth*: dhcp: false", ros config export will print "eth*: {}"

**Comment by ibuildthecloud** [comment]
@imikushin When reading the files for export we shouldn't marshal to a CloudConfig type because it looses the ability to print default values.  We need to unmarshall to a map (merge them) and then print the map.

**Comment by faddat** [comment]
+1

**Comment by imikushin** [comment]
Currently, `ros config export --full` prints full configuration, including values not explicitly set by the user (_aka_ default). 

@sheng-liang @ibuildthecloud Should we make this behaviour the default 
(i.e. _without_ specifying `--full`)?

**Comment by faddat** [comment]
Thank you!

(I think it probably should be default, otherwise what is the purpose of
exporting the config?)

**Comment by deniseschannon** [comment]
Verified with custom build

`sudo ros config set docker.tls false`

In the `sudo ros config export`, the default value is still shown as I had set it explicitly.
