### ISSUE TITLE
Add a new command "ros config validate"

### ISSUE THREAD

**Issue by sheng-liang** [rancher/os#617]
For users who hand edit cloud-config.yml file (many users do), they need a way to make sure they have not mangled the file and RancherOS will still boot.

For now "ros config validate" could basically be an alias to "ros config export". In the future we can make validation more sophisticated.

**Comment by faddat** [comment]
What is the alternative to hand-editing cloud-config.yml?

**Comment by imikushin** [comment]
@faddat Using `ros config` subcommands: `set`, `merge` or `import`.

**Comment by mainiak** [comment]
Yes, please! I'm trying to install behind strict firewall without DNS and don't know what's wrong - ie. my hand crafted cloud-config.yml or not, so this would be big help.

**Comment by deniseschannon** [comment]
Verified by running 

`sudo ros config validate -i cc.yml`

Errors are shown when the config is invalid.
