### ISSUE TITLE
Rancher OS with Docker API version 1.20?

### ISSUE THREAD

**Issue by funkytaco** [rancher/os#618]
How do I get Docker API version 1.20 installed?

    docker-machine ssh rancheros
    [docker@rancheros ~]$ sudo ros os list
    rancher/os:v0.3.0 remote
    rancher/os:v0.3.1 remote
    rancher/os:v0.3.3 remote
    [docker@rancheros ~]$ sudo ros os version
    v0.3.3
    [docker@rancheros ~]$ docker version|grep API
    Client API version: 1.19
    Server API version: 1.19

**Comment by Xe** [comment]
I'd think that this will be solved with 0.4, they just tagged it today, might want to wait for it to be officially released.

**Comment by funkytaco** [comment]
Ok thanks.
