### ISSUE TITLE
Can not use ssh key login after intall RancherOS 0.4 to disk

### ISSUE THREAD

**Issue by muyufan** [rancher/os#623]
I'm using the same public key to cloud_config.yml like this:

```yml
[rancher@rancher ~]$vi cloud_config.yml
#cloud-config
ssh_authorized_keys:
  - ssh-dss  AAA***== ThinkPad@ThinkPad-PC
```

My 0.3.3 OS is OK, but in 0.4 I can't login to OS from PC use same key that 0.3.3 using

**Comment by imikushin** [comment]
@muyufan Make sure you're using your SSH public key. E.g. you can copy the output of `ssh-keygen -y`

**Comment by muyufan** [comment]
Thanks, after some investigation，I figured out OS 0.4 using sshd version 0.7 ，and this new sshd not support dss public key in default config accounting to open ssh document，I regen an RSA key, now it works.

**Comment by ourserverdev** [comment]
it's the same in v0.4.2 can't we add a check to the install if the cloud-config.yml has a ssh-dss key in there wand warn the user ? You will not be able to connect after install if it's the only key.

**Comment by JustEra** [comment]
it's the same in v0.4.2 can't we add a check to the install if the cloud-config.yml has a ssh-dss key in there and warn the user ? You will not be able to connect after install if it's the only key.
