### ISSUE TITLE
Configuring TLS Error at v0.4.0

### ISSUE THREAD

**Issue by philipz** [rancher/os#624]
Hi, I follow [this doc](http://docs.rancher.com/os/configuration/setting-up-docker-tls/) to config TLS is fail. But, I use `sudo docker daemon --log-opt max-size=25m --log-opt max-file=2 -s overlay -G docker -H unix:///var/run/docker.sock --userland-proxy=false --tlsverify --tlscacert=ca.pem --tlscert=server-cert.pem --tlskey=server-key.pem -H=0.0.0.0:2376 &` directly it is works.
 
/var/log/docker.log
```
panic: runtime error: index out of range                                                                                                      

goroutine 1 [running]:
github.com/rancher/docker-from-scratch.getValue(0x10, 0xc20800a020, 0x11, 0x11, 0x0, 0x0)
        /go/src/github.com/rancher/os/Godeps/_workspace/src/github.com/rancher/docker-from-scratch/scratch.go:310 +0x130
github.com/rancher/docker-from-scratch.touchSockets(0xc20800a020, 0x11, 0x11, 0x0, 0x0)
        /go/src/github.com/rancher/os/Godeps/_workspace/src/github.com/rancher/docker-from-scratch/scratch.go:383 +0x195
github.com/rancher/docker-from-scratch.prepare(0xc2080ec0b0, 0x7ffc8faa0e87, 0xf, 0xc20800a020, 0x11, 0x11, 0x0, 0x0)
        /go/src/github.com/rancher/os/Godeps/_workspace/src/github.com/rancher/docker-from-scratch/scratch.go:437 +0x1e2
github.com/rancher/docker-from-scratch.runOrExec(0xc2080ec0b0, 0x7ffc8faa0e87, 0xf, 0xc20800a020, 0x11, 0x11, 0xad0d90, 0x0, 0x0)
        /go/src/github.com/rancher/os/Godeps/_workspace/src/github.com/rancher/docker-from-scratch/scratch.go:545 +0x84
github.com/rancher/docker-from-scratch.LaunchDocker(0xc2080ec0b0, 0x7ffc8faa0e87, 0xf, 0xc20800a020, 0x11, 0x11, 0x11, 0x0, 0x0)
        /go/src/github.com/rancher/os/Godeps/_workspace/src/github.com/rancher/docker-from-scratch/scratch.go:562 +0xc1
github.com/rancher/docker-from-scratch/main.Main()
        /go/src/github.com/rancher/os/Godeps/_workspace/src/github.com/rancher/docker-from-scratch/main/main.go:33 +0x3db
github.com/docker/docker/pkg/reexec.Init(0xaf9810)
        /go/src/github.com/rancher/os/Godeps/_workspace/src/github.com/docker/docker/pkg/reexec/reexec.go:26 +0x71  
main.main()
        /go/src/github.com/rancher/os/main.go:58 +0x259  

goroutine 5 [syscall]:
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:21 +0x1f  
created by os/signal.init·1
        /usr/local/go/src/os/signal/signal_unix.go:27 +0x35  

goroutine 6 [chan send]:
github.com/docker/libcompose/cli/logger.generateColors()
        /go/src/github.com/rancher/os/Godeps/_workspace/src/github.com/docker/libcompose/cli/logger/colors.go:27 +0x191
created by github.com/docker/libcompose/cli/logger.init·1  
        /go/src/github.com/rancher/os/Godeps/_workspace/src/github.com/docker/libcompose/cli/logger/colors.go:33 +0x25
```

**Comment by michaellopez** [comment]
I get the same. I can't get the manual command to work either though. It starts up properly I think, but I get cert errors when I connect.

**Comment by imikushin** [comment]
Just coded a fix for this in docker-from-scratch. I'll be adding an integration test to be sure it's fixed in v0.4.1

**Comment by philipz** [comment]
(y)

**Comment by imikushin** [comment]
@philipz Not so fast :wink: 

We need it open while there's still a test to add. Thanks!

**Comment by EdMendezNC** [comment]
I installed to disk rancherOS v0.4.1 and followed the rancher docs to setup TLS and am getting the same "panic: runtime error: index out of range" error when i do a sudo system-docker restart docker. If I run the same docker command from the command line then everything works perfect and i can connect to docker using a remote docker client.

**Comment by imikushin** [comment]
@EdMendezNC Sadly, confirmed. Thanks for reporting this. Most likely it's the vendored docker-from-scratch source code, that I've forgotten to update :cold_sweat: 

We have a double dependency on docker-from-scratch: one in build.conf, the other one in the vendored sources, both should be in sync. 

Fixing it now.

**Comment by imikushin** [comment]
As a workaround: instead of `'-H=0.0.0.0:2376'` use `-H, 'tcp://0.0.0.0:2376'` in  `rancher.docker.tls_args`.

**Comment by EdMendezNC** [comment]
@imikushin  This workaround is working is working for me, Thank you. Although, once your vendored docker-from-scratch source code is updated and published, will i need to undo that workaround? 
Btw, RancherOS is an awesome product, keep up the great work!!!

**Comment by imikushin** [comment]
Glad to hear this, @EdMendezNC :smile: 

The workaround will not be needed in the next RancherOS versions, but it will not be necessary to undo it either: up to you!

**Comment by deniseschannon** [comment]
Verified TLS is working with the new steps in v0.4.20-rc2.

New Steps:

Enable TLS for Docker and Generate Server Certificates:
```
sudo ros c set rancher.docker.tls true
sudo system-docker restart docker
```

Generate Client certificates:
```
sudo ros tls gen
```

All the docker client TLS files are in `~/.docker` dir now. Copy the files from `/home/rancher/.docker` to `$HOME/.docker` on your client machine if you need to access docker on your RancherOS host from there. On your client machine, set the docker host and test out if Docker commands work.

**Comment by linustseng** [comment]
I got the error message when access docker remotely
```
An error occurred trying to connect: Get https://192.168.157.192:2376/v1.20/version: x509: certificate is valid for 127.0.0.1, not 192.168.157.192
```
regen certificates in both server and client but still the same 
```
sudo ros tls gen -h 192.168.157.192
```

**Comment by deniseschannon** [comment]
did you update your certs on your client machine with what was generated from RancherOS? 

http://docs.rancher.com/os/configuration/setting-up-docker-tls/

**Comment by linustseng** [comment]
yes, I follow the instruction to upload the certs to my client machine
```
Copy the files from /home/rancher/.docker to $HOME/.docker on your client machine if you need to access docker on your RancherOS host from there.
```

**Comment by onnoll** [comment]
+1

I have exactly the same problem

**Comment by deniseschannon** [comment]
What version are you using? This is working in our latest release. v0.4.4.

**Comment by onnoll** [comment]
I'm using the v0.4.4, namely the Amazon AMI rancheros-v0.4.4-0-amazon-ecs-optimized - ami-7ac54809
