### ISSUE TITLE
Vagrant and 0.4.0 failing because ifdown exiting non-zero

### ISSUE THREAD

**Issue by andyshinn** [rancher/os#628]
I'm trying to build the Packer images against 0.4.0 and noticing a couple issues. The major one blocking is that `/sbin/ifdown` seems to be failing due to a missing `/run/network` folder:

```console
rancher@rancher:~$ sudo /sbin/ifdown eth1
/sbin/ifdown: failed to open lockfile /run/network/.ifstate.lock: No such file or directory
rancher@rancher:~$ echo $?
1
rancher@rancher:~$ sudo /sbin/ifdown eth1
/sbin/ifdown: interface eth1 not configured
rancher@rancher:~$ echo $?
0
```

This causes the Vagrant image to fail starting up creating a private network. I'm not quite sure if the `/run/network` folder is the proper place to fix this. I'm just noting here my findings so far trying to get a 0.4.0 Vagrant box image.

**Comment by ibuildthecloud** [comment]
@andyshinn We don't actually use ifup/ifdown.  Networking is managed through the cloud-config http://docs.rancher.com/os/cloud-config/ and using `system-docker restart network`.

Does packer require `ifup/ifdown`?  My first reaction would be that we really shouldn't have busybox include those command as we don't manage the config to make them work.  If we removed the commands I feel that might make things worse for you.  How do you think we should resolve this?

**Comment by andyshinn** [comment]
The commands are actually for Vagrant (I'm just using Packer to build the Vagrant 0.4.0 box). It looks like Vagrant uses them to setup the private network interface. I'll do some more research to see if Vagrant detects alternate ways of setting up interfaces.

Are there any other utilities that might be more desirable to use such as iproute2? If not, maybe the workaround is to remove all the network stuff from the `Vagrantfile` and just have a temporary cloud-config that gets generated for each Vagrant machine (trying to make it work specifically for multi-machine Vagrant).

**Comment by andyshinn** [comment]
So a little more research reveals that there are OS specific plugins to give capabilities (such as the `configure_network` capability) within Vagrant. It probably makes more sense to solve this in Vagrant as a plugin for RancherOS.

Is a modification to cloud-config and `system-docker restart network` the only way to add a IP or is there a more temporary command? If I get antsy I may take a stab at it.

**Comment by cloudnautique** [comment]
@andyshinn, it's not a full plugin, but in the rancher/OS-vagrant repo there is the networking stuff you need. 
https://github.com/rancher/os-vagrant/blob/master/vagrant_rancheros_guest_plugin.rb

**Comment by andyshinn** [comment]
Oh, I did not see that! Would it make sense to actually get this into Vagrant so we don't have to monkey patch Vagrant?

**Comment by andyshinn** [comment]
I created a branch with the changes. But it looks like Vagrant tries the Ubuntu guest before RancherOS. The Ubuntu plugin uses `[ -x /usr/bin/lsb_release ] && /usr/bin/lsb_release -i 2>/dev/null | grep Ubuntu` to test and matches since RancherOS `/etc/lsb-release` contains Ubuntu.

Should I open a separate issue for modifying or removing `/etc/lsb-release` to be for RancherOS?

**Comment by deniseschannon** [comment]
@andyshinn We've moved away from supporting our vagrantfile and moving towards only supporting docker-machine. Due to this move, I'll be closing this issue.
