### ISSUE TITLE
v0.4.0: Rancher default password not recognized after install.

### ISSUE THREAD

**Issue by jlambright** [rancher/os#636]
When I attempt to login, locally or via ssh, the default rancher password is not accepted. During the install process it worked fine either way.

**Comment by deniseschannon** [comment]
Yes, after install, the default rancher user/password is no longer valid. You will have to ssh in using the ssh key that you added in during the install.

**Comment by jlambright** [comment]
I've tried with all three keys I supplied. None have succeeded. A password
prompt still occurs.

**Comment by deniseschannon** [comment]
Sounds like your ssh key didn't work correctly because if it did, it wouldn't prompt for a password.

Can you share how you set up your cloud-config.yml for the install?

**Comment by jlambright** [comment]
Mounted the rancher host's filesystem via sshfs, uploaded cloud-config.yaml, and ran the install. I'll upload the configuration file later today.

**Comment by deniseschannon** [comment]
@jlambright If you are still facing issues, please re-open.
