### ISSUE TITLE
ros install boot flag and cloud-config.yml format

### ISSUE THREAD

**Issue by stefanfoulis** [rancher/os#640]
While doing a baremetal install of rancheros 0.4.0 on an old MacBook Pro from a CD  I encountered these pitfalls:

After running ``ros install`` I had to cancel reboot and had to manually set the bootable flag on the rancheros partition with ``fdisk``, otherwise the new installation would not boot.

The format of ``cloud-config.yml`` as suggested in the docs did not work for me (login after reboot did not work with the provided key).
It was necessary to put the ssh public key in quotes (``"``) and have an empty line between ``#cloud-config`` and the first key. I'm not sure which (or both) of the those two changes were actually necessary. But those were the last changes I made before the install process worked.

**Comment by deniseschannon** [comment]
I did an install using the ISO on VirtualBox. I had no issues with ssh using the exact format that's shown in the docs. I didn't need a space or the quotes.

Are you sure the white spacing in your yaml was exactly as needed? Did you have the `-` in front of the ssh key?

**Comment by stefanfoulis** [comment]
I'll try to reproduce the bug again (probably not before next weekend).

**Comment by deniseschannon** [comment]
@stefanfoulis If you are still facing issues, please re-open.
