### ISSUE TITLE
NIC Teaming

### ISSUE THREAD

**Issue by Rucknar** [rancher/os#643]
Not sure if this is a feature request or a 'how do i...'. 

I've deployed RancherOS to a physical host with multiple NIC's. I'd like to use NIC teaming to give myself network redundancy. Is this possible currently with RancherOS?

**Comment by rjbrown99** [comment]
Yes, see here: https://forums.rancher.com/t/bonding-network-interface-cards-lacp/2179

**Comment by Rucknar** [comment]
Nice one!
