### ISSUE TITLE
Unattended installation

### ISSUE THREAD

**Issue by stokbaek** [rancher/os#648]
Hello,

I am Trying to preform an unattended installation of rancherOS via iPXE.

This is the current cloud-config I am running with:
```
hostname: "rancher"
write_files:
  - path: /opt/rancher/bin/start.sh
    permissions: "0755"
    owner: root
    content: |
      #!/bin/bash
      PATH=$PATH:/usr/sbin:
      wget http://<IP OF SERVER>/cloud-config -O /home/rancher/cloud_config.yml
      echo rancher:SUPERSECUREPASSWD|chpasswd -e
      ros install -c /home/rancher/cloud_config.yml -d /dev/sda -f --no-reboot
```

I dont get any form of error message in any of the logs. The only thing that seem to happens is that `/opt/user_config.yml` is created.
I am able to make it work if I SSH to the server myself and run `start.sh` manually.

**Comment by stokbaek** [comment]
Added `> /tmp/ros.log 2>&1` to the install command.
This is the output ros comes out with
```
time="2015-11-18T13:17:25Z" level=info msg="No install type specified...defaulting to generic" 
Installing from rancher/os:v0.4.0
time="2015-11-18T13:17:25Z" level=fatal msg="no such file or directory" 
time="2015-11-18T13:17:25Z" level=fatal msg="Failed to run install" err="exit status 1" 
```

**Comment by quantverse** [comment]
@stokbaek maybe you need to use ***sudo*** to *run ros* install? I use very similar script as you do, it seems the ***sudo*** is the only difference at the *ros install* line.

**Comment by stokbaek** [comment]
I have now tested my script in versions above 0.4.0 and the problem does not exist anymore. This is only an issue in version 0.4.0 or below therefor am I closing the issue.

@quantverse sudo is not needed as the script is run as root.
