### ISSUE TITLE
ECS-Optimized AMIs don't report metrics to ECS

### ISSUE THREAD

**Issue by schuylr** [rancher/os#651]
When I upgrade from my manual implementation of an ECS agent on RancherOS 0.3.3 to the ECS-Optimized RancherOS 0.4 version, my metrics drop off the face of the earth:

![screen shot 2015-11-17 at 11 49 55 am](https://cloud.githubusercontent.com/assets/12628715/11218108/8a812dcc-8d21-11e5-861c-52f7831e1599.png)

This may be an Amazon issue but I'm posting it here in case the new optimized implementation isn't capturing the host machine metrics correctly.

Amazon CloudWatch is still capturing CPU/Memory load correctly from the ec2 instances themselves and this is consistent across four different cluster implementations I've started with ros 0.4. I think the issue lies within the ECS agent implementation. Obviously this is a problem for anyone who uses ECS metrics on their CloudWatch alarms or auto-scaling configurations.

**Comment by meza** [comment]
I find the same with the out of the box, ami-11740e7b :(

**Comment by schuylr** [comment]
Reporting this is still an issue, ami-2504524f

**Comment by schuylr** [comment]
Looks like v0.4.4 solves this issue. My metrics sprang back to life!

![screen shot 2016-04-19 at 11 46 25 am](https://cloud.githubusercontent.com/assets/12628715/14645611/4b16e524-0624-11e6-8d96-a899c6049d99.png)
