### ISSUE TITLE
docker-machine and rancherOS v0.4.1 have some problems

### ISSUE THREAD

**Issue by CBR09** [rancher/os#652]
I followed http://docs.rancher.com/os/configuration/custom-docker/

When I boot rancherOS with docker-machine, I want to enable debian-console:
```
[docker@rancheros ~]$ sudo ros --version
ros version v0.4.1
[docker@rancheros ~]$ sudo ros service list  
disabled amazon-ecs-agent
disabled aws-ec2-resizefs
disabled debian-console
disabled ubuntu-console
disabled kernel-headers
disabled kernel-headers-system-docker
[docker@rancheros ~]$ sudo ros service enable debian-console
[docker@rancheros ~]$ sudo reboot
```

After, I ssh into and checked:
```
[docker@rancheros ~]$ sudo ros service list
disabled amazon-ecs-agent
disabled aws-ec2-resizefs
enabled  debian-console
disabled ubuntu-console
disabled kernel-headers
disabled kernel-headers-system-docker
```

but very strange:
```
[docker@rancheros ~]$ ls /usr/
bin/     lib/     lib64@   libexec/ sbin/    share/
```

it should be: (/usr/local/bin should exists)
```
rancher@rancher:~$ ls /usr/
bin  games  include  lib  local  sbin  share  src
```

I've tried rancherOS v0.4.1 with vagrant or rancherOS v0.4.0 with docker-machine, it's okay when follow "Custom Docker". So I believe this issue is docker-machine + rancherOS v0.4.1

**Comment by far-blue** [comment]
In a similar manner I've tried enabling the ubuntu console and while ros says it is enabled no matter how many times I try enable/disable, reboot, restart via docker-machine etc. I only ever rarely managed to get into ubuntu and I can't work out the pattern. I can tell because when I login the welcome message is different (well, there is one for a start!)

Docker-machine 0.5.0, VirtualBox 4.3.34, RancherOS 0.4.1

**Comment by far-blue** [comment]
I've identified my issue with the ubuntu-console is the same as in issue #672. Basically, I get the following error:
```
ERRO[0004] Failed to load ubuntu-console: Get https://raw.githubusercontent.com/rancher/os-services/v0.4.1/ubuntu-console.yml: dial tcp: lookup raw.githubusercontent.com on 192.168.0.48:53 doal udp 192.168.0.48:53: network is unreachable
```

**Comment by deniseschannon** [comment]
I just verified this bug was reproducible in v0.4.4-rc1. 

The error I got was

```
Failed to load ubuntu-console : Get https://raw.githubusercontent.com/rancher/os-services/v0.4.4-rc1/u/ubuntu-console.yml :  dial tcp :  lookup raw.githubusercontent.com on [::1]:53: read udp [::1]:45356->[::!]:53: read: connection refused
```

**Comment by deniseschannon** [comment]
Verified with v0.4.4-rc2. I am able to successfully launch RancherOS using docker-machine and enable debian and ubuntu console.

**Comment by ashmckenzie** [comment]
I just experienced this issue (with debian & ubuntu consoles) with:
```
$ VBoxManage --version
5.0.20r106931
```

```
docker-machine version 0.7.0, build a650a40
```
````
[docker@rancher ~]$ cat /etc/lsb-release
DISTRIB_ID=RancherOS
DISTRIB_RELEASE=v0.4.5
DISTRIB_DESCRIPTION="RancherOS v0.4.5"
```

From the console output, it looks like the HTTP calls out to github.com are occurring before the network is up?  (this could just be the order of the output though..)

![rancheros__running_](https://cloud.githubusercontent.com/assets/9525/15654036/37630b54-26d4-11e6-8770-6767f92ce7cf.png)

followed by:

![rancheros__running_](https://cloud.githubusercontent.com/assets/9525/15654046/4a830bee-26d4-11e6-923b-1560308baada.png)

**Comment by deniseschannon** [comment]
@ashmckenzie It sounds like you are facing https://github.com/rancher/os/issues/937

**Comment by deniseschannon** [comment]
Sorry, I meant to include this issue as well. https://github.com/rancher/os/issues/929
