### ISSUE TITLE
Checksums of Docker binary don't match official distribution checksums

### ISSUE THREAD

**Issue by nathanleclaire** [rancher/os#656]
Hi, 

I noticed that in a created RancherOS VM (0.4.1 with docker 1.9.1-rc1) the checksum of the available `docker` binary seems to not match the official statically compiled Docker binary release:

```console
[docker@rancher ~]$ docker -v
Docker version 1.9.1-rc1, build 4663423

[docker@rancher ~]$ openssl dgst -sha256 /usr/bin/docker
SHA256(/usr/bin/docker)= 5353f1794015b586e1ff7d8ba8fa4ef541b85a8ade98328c66848c183a970c1a

$ curl https://test.docker.com/builds/Linux/x86_64/docker-1.9.1-rc1.sha256
5120e7c5ceadaed1041b26ee7c4f63deffc5747d3e9a2669f4446f1bc4b43ba0  docker-1.9.1-rc1
```

Any insight into why that might be?  It matches in `boot2docker.iso` and we are trying to ensure that the Docker version distributed everywhere is consistent and official.

Thanks!

- N

**Comment by Xe** [comment]
They modify docker to properly reap zombies, etc.

**Comment by imikushin** [comment]
Yep, that's what we do :smile: Thanks @Xe !

I'm all for dropping that [patch](https://github.com/rancher/docker/commits/v1.9.1-ros1) though, when zombies are taken care of in upstream docker.

**Comment by joshwget** [comment]
As of v0.4.3, we're using upstream Docker. The checksums should match now.

**Comment by nathanleclaire** [comment]
:+1: Thanks for your work on this folks
