### ISSUE TITLE
how can i use rancherOS in aws china as an ami image

### ISSUE THREAD

**Issue by wenzizone** [rancher/os#661]
hi rancher team, do you think to support china aws, so i found the ami image in global aws except china. so when can china use, so how can i using rancher iso file to create a ami image??

**Comment by SydOps** [comment]
China region is not formal public accessible, so I recommend you can make it by yourself

http://aws.amazon.com/ec2/vm-import/

**Comment by deniseschannon** [comment]
@wenzizone It sounds as if @SydOps has provided a valid solution. 

Let me know if you have further questions.
