### ISSUE TITLE
It seems rancher os cannot be recovered from a rancher os stick

### ISSUE THREAD

**Issue by blaggacao** [rancher/os#662]
After corrupting my cloud config yaml, I wanted to recover from the initial rancher os stick, with wich I infected the computer on the first hand. Aparently, the stick also reads the cloud_config file from disk, when in place and therefore fails.

Not 100% sure of this interpretation of what I see and not sure if it's intended.
https://github.com/rancher/rancher/issues/2803#issuecomment-159490706

**Comment by ibuildthecloud** [comment]
@blaggacao You can boot rancheros with the kernel command line "rancher.state.dev=none". That will prevent it from using the state partition. You can then mount the state partition from the live system and recover.

**Comment by blaggacao** [comment]
Whohoo! Can we put the label documentation on that? When someone's working with bare metal, that question might pop up every so often...

**Comment by 2devnull** [comment]
what credentials are used with this method? It is not authenticating with ssh key nor rancher/rancher.

**Comment by ibuildthecloud** [comment]
The password of the rancher user is controlled with another cmdline param  `rancher.password=rancher`

**Comment by ibuildthecloud** [comment]
We should really just make a "rescue" option in the bootable USB/ISO

**Comment by blaggacao** [comment]
@ibuildthecloud That's would be convenient, I know you go for convenience! So yeay!

**Comment by ibuildthecloud** [comment]
@blaggacao Contributions welcome :) Our syslinux.cfg is available at https://github.com/rancher/os/blob/master/scripts/isolinux.cfg.  It's barebones, we really need a more robust one that has a bit of a pause to allow you to type things on the command line.  Right now it just boots straight it, would be nice to display a message and some key like "F2 Rescue."  Like you see on other distros' ISOs.

**Comment by 2devnull** [comment]
I don't see that when I boot. I only see the GRUB2 selection. Perhaps it can be added there.

**Comment by ibuildthecloud** [comment]
@2devnull That's a good point we should add this to boot the GRUB2 boot loader and the syslinux one we use from the ISO/USB.  The grub2 config is controlled from https://github.com/rancher/os-installer/blob/master/scripts/lay-down-os#L72

**Comment by joshwget** [comment]
Confirmed with v0.6.0-rc3 that the ISO doesn't use the state partition by default, which prevents this issue.
