### ISSUE TITLE
Googles's Nameservers inhibit service linking by name `app`

### ISSUE THREAD

**Issue by blaggacao** [rancher/os#665]
I move the issue here, because it was identified as a RancherOS issue, please also refer to the original issue: https://github.com/rancher/rancher/issues/2838

**Cause:**
This line causes service linking to fail on such host in a special case:
https://github.com/rancher/os/blob/master/os-config.yml#L49

**Effect**: 
On any container on such a machine: `ping app` always returns `127.0.53.53` inhibiting linking by the token `app`

**Nastiness**:
This is very difficult to uncover. Documentation or Patch would be needed.

Best

**Comment by vincent99** [comment]
I'm not sure what we can really do about this, other than pick a different default DNS server (and respect DHCP's provided one, if it doesn't already).. It's a valid answer returned by the server.

As far as Rancher (not OS) is concerned, links are checked before trying the recursing servers, so if you link to something as `app` that would take precedence.  If resolving immediately after startup you may be hitting the race condition where the answer and resolv.conf hasn't made it in before the container starts.

Also you can avoid this with a fully qualified question, `app.rancher.internal`.

**Comment by blaggacao** [comment]
I agree, that this does probably not ask for a fix, but possibly a warning/hint in the docs. 
@vincent99 What do you mean by "startup"? If you mean, regular stack/service startup as in my case, then we should probably look for a solution to the root cause, as this can be considered as normal operation. (Not sure, if I got you right, tough)

**Comment by vincent99** [comment]
@blaggacao When a container starts it's possible for it to make a DNS resolution request fast enough that the resolv.conf hasn't been updated to point to the right place yet.  We can fix this now with Docker 1.9: https://github.com/rancher/rancher/issues/2341

**Comment by blaggacao** [comment]
ok, greate, let's assume closeable for now.

If anyone stumbles on this after applying the fix, please ping shortly for a reopen.
