### ISSUE TITLE
Default password remains after ISO install

### ISSUE THREAD

**Issue by robbertkl** [rancher/os#670]
I've recently installed RancherOS (v0.4.1) in 2 different ways:

1. After booting from the ISO
2. After booting with iPXE, passing `rancher.password=rancher` to the kernel

In both cases, I've used username *rancher* + password *rancher* to do the install: scp my cloud-config.yml containing my SSH pubkey, then run `sudo ros install -c cloud-config.yml -d /dev/sda`.

After the install, I was able to login as user *rancher* with my SSH key. However, after disabling my SSH key, I've discovered that in the 1st case (installed with ISO) I could still login with password *rancher*!

Checking `/etc/shadow`, the one installed from ISO indeed contains a password hash for user *rancher*, while the one installed from iPXE contains `!`, blocking password login. Both were installed with `ros install` and both had a user *rancher* with password *rancher* at the time of running the install (either baked in in the ISO, or set through a kernel parameter).

Seems like a serious security issue: a default password set on installed servers, while users unaware of this, since they're using SSH keys and expecting password authentication to be locked.

**Comment by imikushin** [comment]
@robbertkl you must have rebooted from the ISO and it has set the password in the console container. 

If you're using an ephemeral (default) console, that should be fine: just remove the ISO and boot from your disk. With a persistent console (debian or ubuntu) the changes to /etc/shadow are saved and will persist across reboots.

**Comment by robbertkl** [comment]
This was indeed the issue, the ISO was still attached. What threw me off here was that I was able to log in using my SSH key (given during installation), making me think it booted from disk. I guess this is because the ISO still detected my installed RancherOS because of the disk label `RANCHER_STATE`?

Removing the ISO does fix the issue (in case of the default console), but - like you explain above - the password does remain on a persistent console. Does this mean if you've ever booted from ISO once (with a persistent console), the password will remain there forever? (if not manually removed)

Is there some documentation on what exactly is persisted on a ephemeral vs. persistent console? For example:
* What is always persisted, even on a ephemeral console? (home dirs, `/mnt`, `/opt`?)
* What is only persisted on persistent consoles? (`/usr/local`, `/etc`?)
* What is never persisted, even on a persistent console? (anything at all?)

**Comment by joshwget** [comment]
You're correct, the problem here is that the ISO will use the `RANCHER_STATE` disk by default. This can interfere with existing installations, so it's definitely not a very good default behavior. We're going to change this in v0.5.1.

**Comment by joshwget** [comment]
Confirmed with v0.6.0-rc3 that the ISO doesn't use the state partition by default, which prevents the password in existing installs from being changed.
