### ISSUE TITLE
ubuntu-console would not run on bare metal server

### ISSUE THREAD

**Issue by jackjacek** [rancher/os#672]
I'm experiencing an issue with latest rancher (v0.4.1) across two servers. I tried enabling ubuntu-console using cloud-config.yml at installation time, but it always fails on boot: Failed to load ubuntu-console : Get https://raw.githubusercontent.com/rancherio/os-services/v0.4.1/u/ubuntu-console.yml: dial tcp: lookup raw.githubusercontent.com on 8.8.4.4:53: read udp 8.8.4.4:53: network unreachable. I tried editing /var/lib/rancher/conf/cloud-config.d/user_config.yml and only left the necessary ssh keys section, after rebooting I had to enable ubuntu-console from command line (not sure why it did not persist) & after rebooting still getting the same error. I can verify pulling rancher/os-ubuntuconsole image worked without an issue.

**Comment by far-blue** [comment]
I'm getting this exact same issue using VirtualBox with a vm setup through docker-machine. Sometimes it works but mostly it doesn't.

**Comment by liyimeng** [comment]
I have exactly the same issue, but it turns out that my cooperation network has blocked the access to google DNS server. After redirect the DNS query traffic, all works fine.

**Comment by deniseschannon** [comment]
We have tested in other versions of RancherOS and this should be fixed now.
