### ISSUE TITLE
when  an error occurred  , Take about 30 minutes can be connected

### ISSUE THREAD

**Issue by yuanzougaofei97** [rancher/os#673]
i use rancher add host, once rancher add a container ,  hosts will appear Reconnecting on the rancherUI , then the host need Take about 30 minutes can be connected

**Comment by deniseschannon** [comment]
This typically happens if docker hangs on your host. After it goes into reconnecting, try logging into your host and doing a `docker ps`. If there is no immediate output of the containers, then docker is having issues. 

What OS are you running for your host and what version of Rancher?

**Comment by deniseschannon** [comment]
Oh, sorry, I just realized that you reported this in the OS repo, which indicates you are running RancherOS. 

I have not had this issue with running RancherOS as a host. But I've been running them on a cloud provider.

Where do you have RancherOS running?

**Comment by yuanzougaofei97** [comment]
yes , i run the rancher on the rancherOS with vagrant , the provide is virtualBox .my Host OS is window10  .  the box address is   https://github.com/rancher/os-vagrant.git.
fortunate , i move rancher and agent  to  centos7, it is work fine .whether the problems caused by the operating system rancherOS.

**Comment by yuanzougaofei97** [comment]
my rancher version is v0.47.0

**Comment by deniseschannon** [comment]
Have you looked at the troubleshooting docs to make sure all your connections are working properly? http://docs.rancher.com/rancher/faqs/troubleshooting/

**Comment by yuanzougaofei97** [comment]
it work fine on centos7 , thanks
