### ISSUE TITLE
Support cloud-config.yml with docker-machine

### ISSUE THREAD

**Issue by far-blue** [rancher/os#676]
Maybe I've missed it but I can't see how to supply a cloud-config.yml file when provisioning RancherOS instances via docker-machine on VirtualBox. It would be great to have the option to do this to test cloud-config files, replicate a live environment within VirtualBox and provide an automated pre-configured setup for dev environments

**Comment by deniseschannon** [comment]
When docker-machine adds support to passing in user data, we'll make sure to test it with dockermachine.

**Comment by lthibault** [comment]
What's the recommended way to deploy a `cloud-config.yml` file in the meantime?

**Comment by SvenDowideit** [comment]
`docker-machine create --driver amazonec2` has an `--amazoneec2-userdata`

ie, I'm using

```
source ~/aws.env

docker-machine create --driver amazonec2 \
	--amazonec2-ami ami-7caa341c \
	--amazonec2-region us-west-2 \
	--amazonec2-instance-type t2.small \
	--amazonec2-ssh-user rancher \
	--amazonec2-userdata cloud-config.yml \
	 test-box
```

**Comment by ryansch** [comment]
@niusmallnan I think it's obvious that docker-machine is never going to add support for this.  They've kicked it down the road to the individual distro.  Any ideas for how we could get this to work?

**Comment by niusmallnan** [comment]
@ryansch We don't want to fork the docker-machine to support it. We are going to support virtubox-tools, maybe there is a suitable solution in this direction.
