### ISSUE TITLE
How to give a custom config with 9p driver

### ISSUE THREAD

**Issue by LordFPL** [rancher/os#680]
Hello,

I'm trying to launch RancherOS instance with qemu, but i don't find any way to have a specific config.
In the documentation, there is information about a disk with label "RANCHER_STATE", but it's only for a disk.
In code https://github.com/rancher/os-images/blob/master/src/docker/02-cloudinit/cloud-init.sh#L12 there is a possibility to automount a 9p share (with mount_tag "config-2"), but i don't see the mount point... and the code trying to mount it in "/media/config-2".

(my launch is with : `qemu-system-x86_64 -cdrom /opt/rancheros/rancheros.iso -m 16384 -net nic,vlan=0,model=virtio -net user,vlan=0,hostfwd=tcp::2222-:22,hostname=rancher-dev -smp 4 -enable-kvm -fsdev local,id=export,path=/opt/rancheros,security_model=mapped -device virtio-9p-pci,fsdev=export,mount_tag=config-2`

My question are : 
- Why 9p share with label/mount_tag "RANCHER_STATE" is not mounted ?
- How to have a use of 02-cloud-init.sh (i don't find a clear doc for that)
- More general question : is there an official way (that will be supported in future version) to give a specific configuration via qemu ?

Many thx in advance :)

**Comment by ibuildthecloud** [comment]
Check out scripts/run, we use 9p there to pass cloud config for development.

**Comment by LordFPL** [comment]
Hi,

Thx for your answer, but i'm only see this : https://github.com/rancher/os/blob/master/scripts/run#L175

It's not 9p, no ? It's a raw disk image. My main problem with raw disk is that when rancher os detect it, it will be used for /var/lib/docker for example. All i want is only a way to mount /var/lib/rancher/conf to modify dns and add launch a container. I want all the rest stay in memory (my use is to spawn workers for CI).

**Comment by ibuildthecloud** [comment]
Sorry, we switched to non-9p for a bit but it is now 9p against in our dev scripts.  You can see it here https://github.com/rancher/os/blob/22ab564dacdaed1ab8f6a154ba4519aa68a38b71/scripts/run#L188
