### ISSUE TITLE
Add ability to use cloud-config file to login and use credentials for launching services in cloud-config

### ISSUE THREAD

**Issue by deniseschannon** [rancher/os#685]
Currently, you can log in to dockerhub using the `write_files` directive in cloud-config, but this only pre-logins you to your repositories so after you launch RancherOS, you can start pulling images from the repository. 

It'd be nice to be able to automatically launch services that use the authentication required in teh cloud-config files.

**Comment by quantverse** [comment]
+1

**Comment by ldejager** [comment]
+1

**Comment by deniseschannon** [comment]
Pre-duplicate of #775
