### ISSUE TITLE
Rollback is broken in v0.4.2

### ISSUE THREAD

**Issue by liyimeng** [rancher/os#690]
After upgrade to version 0.4.2, the upgrade seem broken. I am not able to upgrade or rollback anymore.

rancher@devops:~$ sudo ros os upgrade -i  rancher/os:v0.4.1
...

Status: Downloaded newer image for rancher/os:v0.4.1
INFO[0017] [1/1] [os-upgrade]: Started                  
INFO[0017] Project [once]: Project started              
Pulling from rancher/os
Digest: sha256:320addc8d74521965956b8ec97c025b3d79db2f1e1a83235b767fe0953ef5b88
Status: Image is up to date for rancher/os:v0.4.1
Upgrading to rancher/os:v0.4.1
Continue [y/N]: y
FATA[0024] API error (404): no such id: once_os-upgrade_1

rancher@devops:~$ sudo ros os upgrade
INFO[0000] Project [once]: Starting project             
INFO[0000] [0/1] [os-upgrade]: Starting                 
INFO[0000] [1/1] [os-upgrade]: Started                  
INFO[0000] Project [once]: Project started              
Pulling from rancher/os
Digest: sha256:26614628e6a6e76ff4a820aa902f83c3ca8a84b78f232f6950643bc62c335fae
Status: Image is up to date for rancher/os:v0.4.2
Upgrading to rancher/os:v0.4.2
Continue [y/N]: y
FATA[0010] API error (404): no such id: once_os-upgrade_1

**Comment by deniseschannon** [comment]
Confirmed that rollback is not working.

**Comment by liyimeng** [comment]
Thanks deniseschannon and ibuildthecloud! If you need me with any help, e.g. testing, please let me know.

**Comment by michaellopez** [comment]
I'm also hitting this, any workaround? Is there an official way of reinstalling? Can't find anything in the documentation about it.

I booted from the 0.4.1 ISO and tried:

```sh
$ sudo ros install -c cloud_config.yml -d /dev/sda
INFO[0000] No install type specified...defaulting to generic
Installing from rancher/os:v0.4.1
Continue [y/N]: y
+ DEVICE=/dev/sda
+ [[ -z /dev/sda ]]
++ wc -l
+++ echo /dev/sda
+++ cut -d / -f3
++ grep sda /proc/partitions
+ PARTITION_COUNT=2
Device /dev/sda already partitioned!
Checking to see if it is mounted
+ '[' 2 -gt 1 ']'
+ echo 'Device /dev/sda already partitioned!'
+ echo 'Checking to see if it is mounted'
+ grep -q /dev/sda /proc/mounts
+ echo 'Device is mounted, we can not repartition'
Device is mounted, we can not repartition
+ exit 1
FATA[0001] Failed to run install                         err=exit status 1
```

**Comment by michaellopez** [comment]
Running `sudo ros os upgrade -i rancher/os:v0.4.1` and manually rebooting drops me into `0.4.1` after reboot...

**Comment by liyimeng** [comment]
Hi, I think it is also a problem for upgrade, not only rollback!  
Here is my test:
<pre>
[rancher@rancher ~]$ sudo ros os upgrade -i localhost:5000/rancheros
INFO[0000] Project [once]: Starting project             
INFO[0000] [0/1] [os-upgrade]: Starting                 
INFO[0000] Rebuilding os-upgrade                        
Pulling from rancheros
Digest: sha256:bdca9d6b20602de0c2afe1be2aeac960f9165fa3a51689b8d9c7eee0b6aaa313
Status: Downloaded newer image for localhost:5000/rancheros:latest
INFO[0000] [1/1] [os-upgrade]: Started                  
INFO[0000] Project [once]: Project started              
Pulling from rancheros
Digest: sha256:bdca9d6b20602de0c2afe1be2aeac960f9165fa3a51689b8d9c7eee0b6aaa313
Status: Image is up to date for localhost:5000/rancheros:latest
Upgrading to localhost:5000/rancheros
Continue [y/N]: y
FATA[0008] API error (404): No such container: once_os-upgrade_1

[rancher@rancher ~]$ sudo ros os version
v0.4.3

</pre>

**Comment by Peaches491** [comment]
I've just experienced the same problem, attempting to upgrade from `0.4.2` to `0.4.3`

**Comment by Peaches491** [comment]
Similar to @michaellopez, I just was able to upgrade by running `ros os upgrade -i rancher/os:v0.4.3` and rebooting.

**Comment by datawolf** [comment]
+1

**Comment by jangrewe** [comment]
+1

**Comment by joshwget** [comment]
Running `sudo system-docker rm os-upgrade` before performing a rollback should prevent this.

**Comment by ersutton** [comment]
I followed the guide here: http://docs.rancher.com/os/configuration/storage/ specifically 'ZFS storage for Docker on RancherOS'
I then made the mistake of upgrading from from `0.4.2` to `0.4.3`. It fails as on boot I get `Could not load module zfs, err exit status 1` - I cannot roll back either. If anyone has a suggestion I'd appreciate it.

**Comment by liyimeng** [comment]
@ersutton upgrade dose not work in your case since you have modified kernel modules. As I know, upgrade today will load in kernel and modules shipped with new release, replacing out the old and including your changes on the old.

**Comment by ersutton** [comment]
@liyimeng Thanks for your reply. I have moved to running rancher on ubuntu 14.04 - I will retry rancheros another time!

**Comment by deniseschannon** [comment]
This is fixed in v0.4.4-rc1, but it cannot be tested until v0.5.0 to test rolling back.

**Comment by deniseschannon** [comment]
Verified with upgrade between v0.4.4-rc3 to v0.4.4-rc4 and roll back and up again is working.

**Comment by openhs** [comment]
Once the fixed version 0.5.0 will be released what will be the recommended way to upgrade from 0.4.1?  Should intermediate versions 0.4.2, 0.4.3 and 0.4.4 be skipped and upgrade performed directly to 0.5.0?

**Comment by deniseschannon** [comment]
@openhs We will only test the upgrade path from the last v0.4.x (which will most likely be v0.4.5) release to v0.5.0. There are known upgrade issues in v0.4.2 and v0.4.3 that have been fixed in v0.4.4, so you could upgrade to v0.4.4 now unless you are waiting for a specific reason to upgrade to v0.5.0.

**Comment by protheusfr** [comment]
Any workaround to upgrade from 0.4.2 to 0.4.3 (and then 0.4.4) ?

```
rancher@docker01:~$ ros os version
v0.4.2
rancher@docker01:~$ sudo ros os upgrade -i rancher/os:v0.4.3
INFO[0000] Project [once]: Starting project             
INFO[0000] [0/1] [os-upgrade]: Starting                 
INFO[0000] Rebuilding os-upgrade                        
INFO[0000] [1/1] [os-upgrade]: Started                  
INFO[0000] Project [once]: Project started              
Pulling from rancher/os
Digest: sha256:cfcd97725e5c043980d71a4ef4e7ad831b367cbaa60cb5567a2e9a0d207791be
Status: Image is up to date for rancher/os:v0.4.3
Upgrading to rancher/os:v0.4.3
Continue [y/N]: y
FATA[0003] API error (404): no such id: once_os-upgrade_1
```

**Comment by michaellopez** [comment]
@protheusfr Yes, you can follow @joshwget's [advice](https://github.com/rancher/os/issues/690#issuecomment-189017311).

**Comment by protheusfr** [comment]
I've no container with this name: 

> rancher@docker01:~$ docker ps  -a
> CONTAINER ID        IMAGE                              COMMAND                  CREATED             STATUS                           PORTS                                          NAMES
> b9d6869ebf88        rancher/agent:v1.0.1               "/run.sh run"            5 days ago          Up 5 days                                                                       rancher-agent
> 69a881f40c6a        hyper/docker-registry-web:latest   "catalina.sh run"        3 weeks ago         Exited (143) About an hour ago                                                  r-RegistryUI_docker-registry-web_1
> a2b1dfc23977        gogs/gogs:latest                   "docker/start.sh /bin"   6 weeks ago         Up About an hour                 0.0.0.0:222->22/tcp, 0.0.0.0:10080->3000/tcp   r-gogs_gogs_1
> 41ab82098afd        mysql:latest                       "/entrypoint.sh mysql"   6 weeks ago         Up About an hour                 0.0.0.0:3306->3306/tcp                         r-gogs_mysql_1
> db0432d6e670        rancher/agent-instance:v0.6.0      "/etc/init.d/agent-in"   3 months ago        Up 5 weeks                       0.0.0.0:500->500/udp, 0.0.0.0:4500->4500/udp   e41fd8ba-f51f-4a48-aa6c-c2d71ac4d469

**Comment by michaellopez** [comment]
@protheusfr Check your system docker. `sudo system-docker ps -a`

**Comment by protheusfr** [comment]
Ok, my mistake, thank you @michaellopez , that's work.
