### ISSUE TITLE
802.1q tagged VLAN doc

### ISSUE THREAD

**Issue by magnus919** [rancher/os#695]
I'm really enjoying RancherOS so far and have found one area where the doc is not helping me to make full use of the OS. It would be great to have some doc around how to define tagged VLAN interfaces so I can associate containers with specific networks that aren't on a discrete physical interface.

**Comment by nahuellofeudo** [comment]
I'm having the same problem here... a pointer would be useful.

**Comment by ibuildthecloud** [comment]
We are currently working to make this easier in the next release.

**Comment by nahuellofeudo** [comment]
Thank you!

**Comment by deniseschannon** [comment]
I've added some documentation on how to define tagged VLAN interfaces.
