### ISSUE TITLE
Defining a new system-docker volume

### ISSUE THREAD

**Issue by colebrumley** [rancher/os#706]
I am attempting to build on @pwFoo's work from #601, #567, and #542 on a Convoy plugin container. I'd really prefer to use system-docker since I don't want the Convoy client to be intimately linked with the Docker daemon for which it's providing volumes. The other catch is that it'd be great if that service could expose the Convoy binaries as volumes that are included in `command-volumes` or `user-volumes` so that they're exposed to the console by default.

Right now I have a container that runs fine in terms of providing driver-level access to Convoy from user-docker, but I'm having trouble figuring out how to map the binaries into a console that doesn't require modifying it (so that I could eventually PR the service into os-services).

Putting the binaries into one of the `user-volumes` is something I've considered, but then you have to modify the console's `$PATH` and move the binaries there after the volume exists instead of exposing them where they lay.

Since they don't exist on the buildroot base filesystem, I obviously can't map them with `/usr/bin/convoy:/usr/bin/convoy:ro`.  Do I have to build a custom os-base to do this, or is there a way to include volumes in `all-volumes` from a service YAML? If not, would it make sense to add a `io.rancher.os.volumes.expose` tag or something? It would make adding system services for plugins a lot easier and discourage (me from) modifying the base unnecessarily.

**Comment by pwFoo** [comment]
HI @colebrumley 
any progress with your os service / PR?

It should work to mount /usr/local/bin as directory. It's in the $PATH and should work since RancherOS 0.4.

**Comment by pwFoo** [comment]
At the moment this works for me, but it isn't a os-service yet...

**dockerfile**
```
FROM rancher/os-console:v0.4.2

ADD convoy.tar.gz /tmp/convoy.tar.gz
ADD convoy-start.sh /convoy-start.sh

RUN cp /tmp/convoy.tar.gz/convoy/convoy* /usr/bin/ \
	&& rm -rf /tmp/convoy.tar.gz \
	&& chmod +x /convoy-start.sh

ENTRYPOINT ["/convoy-start.sh"]
```

**convoy-start.sh**
```
#!/bin/sh

DOCKER_VOLUMES=/var/lib/docker/volumes
DOCKER_PLUGINS=/etc/docker/plugins

if [ -z $@ ]; then
    if [ ! -d $DOCKER_PLUGINS ]; then
        mkdir -p $DOCKER_PLUGINS
    fi

    echo "unix:///var/run/convoy/convoy.sock" > $DOCKER_PLUGINS/convoy.spec

    CMD="daemon --drivers vfs --driver-opts vfs.path=DOCKER_VOLUMES"
else 
    CMD=$@
fi

exec /usr/bin/convoy $CMD
```

**Start as a system-docker container (daemon)**
```
sudo system-docker run -d --name convoy-vfs --volumes-from all-volumes convoy-vfs
```

**Alias to use the convoy command**
```
alias convoy='sudo system-docker exec -ti convoy-vfs convoy'
```

**Just use it like convoy plugin is installed to the host via alias**
```
convoy create volume1
```

**My ToDo...**
1. [Create a os-service started before user-docker (io.rancher.os.before / io.rancher.os.after)](http://docs.rancher.com/os/configuration/system-services/)
2. [Pre-packing image](http://docs.rancher.com/os/configuration/prepacking-docker-images/)
3. set the host alias to use convoy like a native command during os boot


Help with the os-service / ToDo would be great.

**Comment by pwFoo** [comment]
As quick solution...

**preload image**
```
system-docker save convoy-vfs > /var/lib/system-docker/preload/convoy-vfs.tar
```

**Add as service: /var/lib/rancher/conf/convoy-vfs.yml**
```
convoy-vfs:
  image: convoy-vfs
  restart: always
  labels:
  -  io.rancher.os.scope=system
  - io.rancher.os.before=docker
  volumes_from:
  - all-volumes
```

**Enable convoy-vfs**
```
sudo ros service enable /var/lib/rancher/conf/convoy-vfs.yml
```

Reboot and verify...
```
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS              PORTS               NAMES
9060dead23e4        rancher/os-console:v0.4.2   "/usr/sbin/entry.sh /"   11 seconds ago      Up 10 seconds                           console
507f4e3ce465        convoy-vfs                  "/convoy-start.sh"       16 seconds ago      Up 15 seconds                           os_convoy-vfs_1
fece581a38d8        rancher/os-docker:v0.4.2    "/usr/sbin/entry.sh /"   4 hours ago         Up 10 seconds                           docker
8926d7a271f4        rancher/os-ntp:v0.4.2       "/usr/sbin/entry.sh /"   4 hours ago         Up 10 seconds                           ntp
4f5f012f8ab5        rancher/os-network:v0.4.2   "/usr/sbin/entry.sh n"   4 hours ago         Up 15 seconds                           network
a451065eb3d9        rancher/os-udev:v0.4.2      "/usr/sbin/entry.sh /"   4 hours ago         Up 16 seconds                           udev
00b0b49f652d        rancher/os-syslog:v0.4.2    "/usr/sbin/entry.sh /"   4 hours ago         Up 16 seconds                           syslog
1375fd5b3663        rancher/os-acpid:v0.4.2     "/usr/sbin/entry.sh /"   4 hours ago         Up 16 seconds                           acpid
```

How could it be improved?

**Comment by colebrumley** [comment]
@pwFoo That's almost identical to the approach I'm taking, with the exception that I am stashing my convoy volumes in /opt so I don't need additional system volumes for it. I still keep coming back to the fact that you have to modify the console after it's enabled (either with an alias like you have or adding a dir to $PATH).  I feel like an os-service should not make or require any changes to the other services (like the console), which is why I'm not happy enough with what I've got to PR it. Maybe if we could get some default persistent location included in the console's default $PATH (like /opt/bin or something) this would work itself out.

**Comment by pwFoo** [comment]
I use the default convoy and also user-docker volume path. It's persistent and no change is needed.

To avoid changes we need Wirkung mapping, but /usr/local/bin (is inside $PATH) doesn't exist at RancherOS and /usr/bin used the file isn't available Form the host. So I haven't found a better way.
The alias is needed to manage Volumens. Add / create can be done from "docker run" 

I would also prefer a mapping to the host, but it seems to be difficult.
I would set some more configs Mike the alias in another system-docker container (firewall rules, maybe static routes,...)

Would be great to get mapping working for example by using /usr/local/bin for mapping...
Haven't tested this directory because it doesn't exist, but it could be created during boot (container, cloud config) andcshould be tested.

**Comment by pwFoo** [comment]
Hi @colebrumley 
any new ideas or solutions here? Alias would be fine, but I wouldn't set it manually each time. But don't know it it is possible to set the RancherOS console alias from within a os-service or which image the convoy os-service should be based from (at the moment it works with `rancher/os-console:v0.4.2`.

**Comment by pwFoo** [comment]
Moved to `FROM alpine:3.3`, fixed my convoy list | backup | ... but and added an alias to `~/.bash_login`.
I'll do some more tests, but should be fine now :)

**Comment by prologic** [comment]
What's the status of RancherOS+Convoy integration as a system-docker container/service?

**Comment by cnf** [comment]
Same question, is there any progress on this?

**Comment by niusmallnan** [comment]
https://rancher.com/docs/os/v1.x/en/installation/system-services/system-docker-volumes/#user-volumes
