### ISSUE TITLE
ixgbevf-2.14.2

### ISSUE THREAD

**Issue by kmcgrath** [rancher/os#707]
AWS recommends ixgbevf-2.14.2 for enhanced networking: http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/enhanced-networking.html

Looks like RancherOS is on 2.12.1-k

    [rancher@ip-10-0-2-175 ~]$ docker run -v /lib/modules:/lib/modules ubuntu modinfo ixgbevf
    filename:       /lib/modules/4.2.3-rancher/kernel/drivers/net/ethernet/intel/ixgbevf/ixgbevf.ko
    version:        2.12.1-k
    license:        GPL
    description:    Intel(R) 10 Gigabit Virtual Function Network Driver
    author:         Intel Corporation, <linux.nics@intel.com>
    srcversion:     4397B6B31434640A38684CB
    alias:          pci:v00008086d000015A8sv*sd*bc*sc*i*
    alias:          pci:v00008086d00001565sv*sd*bc*sc*i*
    alias:          pci:v00008086d00001515sv*sd*bc*sc*i*
    alias:          pci:v00008086d000010EDsv*sd*bc*sc*i*
    depends:        
    intree:         Y
    vermagic:       4.2.3-rancher SMP mod_unload 
    parm:           debug:Debug level (0=none,...,16=all) (int)

I'm not sure of the exact changes from 2.12.x to 2.14.2 but you can get a feel for the troubles people had with 2.11.x here: https://bugs.launchpad.net/ubuntu-on-ec2/+bug/1254930

**Comment by ibuildthecloud** [comment]
Are you aware of any other distro packaging this version.  I assume Amazon Linux does.  I'll poke around and see if we can include this driver.

**Comment by ibuildthecloud** [comment]
I think there is some confusion around the versioning of this driver.  2.14.2 seems to be the out of tree version but the in tree 2.12.1-k may actually be newer and ok.  More info here http://sourceforge.net/p/e1000/mailman/message/34449555/

**Comment by kmcgrath** [comment]
Ah, nice catch, I did not realize that.

I'll close this and continue our testing.  Thank-you for the quick feedback!
