### ISSUE TITLE
[os-images] image preloading not working properly

### ISSUE THREAD

**Issue by Dunedan** [rancher/os#710]
I created a custom RancherOS 0.4.2 image out of the AWS AMI `ami-53045239` by adding a docker image to preload to `/var/lib/docker/preload`. After booting I see the expected `/var/lib/docker/preload/image.tar.xz.done`, but when running `docker images` the image doesn't appear.

Things I tried then:
* Adding the logic the preloading would do manually to `/opt/rancher/bin/start.sh`:
```
sudo cat /var/lib/docker/preload/image.tar.xz | unxz | docker load
```
but that also doesn't work.
* Executing the command previous added to `start.sh` manually via SSH and that surprisingly works.
* Trying to run the preload container manually to see what happens:
```
$ sudo system-docker run -e "PRELOAD_DIR=/var/lib/docker/preload/" 40242dfa77b8
Can not preload images from /var/lib/docker/preload/: not a dir or does not exist.
```
Am I missing some filesystem overlay magic there?

From my point of view it looks like something with the image preloading is currently broken or am I simply doing something wrong?

**Comment by deniseschannon** [comment]
Can you provide how you added the docker image to the preload? Could you share your cloud-config? 

I've never actually preloaded an image, so not sure even how to try it, but would like to try it out to see where the issue may lie.

**Comment by Dunedan** [comment]
I use [Packer](https://packer.io/) to bake the docker image and a command to run it as container on RancherOS startup into an existing AMI. Attached you'll find a sample configuration for packer: [packer-config.json.txt](https://github.com/rancher/os/files/80875/packer-config.json.txt)

When using `rancheros-v0.3.3-hvm-1` (`ami-772dee1c`) as source AMI it works fine, but with `rancheros-v0.4.2-hvm-0` (`ami-53045239`) the mentioned problem appears.

The actual startup of the AMIs (both source and target AMI) were done without specifying user-data for cloud-config at all.

**Comment by pwFoo** [comment]
I opened an issue for RancherOS about that.
https://github.com/rancher/os/issues/719

Would be great to get it fixed.

**Comment by Dunedan** [comment]
@pwFoo: I think you're talking about a different issue, as I'm trying pre-loading for user-docker (and not like you for system-docker) and `/var/lib/docker/preload` is persistent as it should.

**Comment by pwFoo** [comment]
OK, that's different. Here both directories aren't created and  removed during reboot. 
Latest RancherOS. 
That's why I following here too.

**Comment by deniseschannon** [comment]
I haven't had time to test out image preloading, but will be trying once I get some time.

**Comment by ryansch** [comment]
It appears the container is busted in addition to the `/var/lib/system-docker` persistence issues.

Output:
```
[docker@default /]$ sudo system-docker logs preload-user-images
Preloading docker images from /mnt/preload...
Done.
Preloading docker images from /mnt/preload...
loading from /mnt/preload/parallels-tools.tar.xz
/preload.sh: line 31: docker: command not found
Done.
/preload.sh: line 12: stat: command not found
/preload.sh: line 12: stat: command not found
Preloading docker images from /mnt/preload...
Done.
```
Referencing the script here: https://github.com/rancher/os-images/blob/master/src/docker/02-preload/preload.sh

It appears the container has neither `stat` nor `docker` installed.

**Comment by ryansch** [comment]
@deniseschannon I've had a look at `inspect` for that container and it's mounting the `docker` binary as `docker.dist`.  The `stat` binary isn't referenced at all in the volume mounts.

**Comment by ryansch** [comment]
I have user-docker preloading working with: https://github.com/rancher/os-images/pull/57

Note: system-docker preloading is still broken a la #719.

**Comment by ryansch** [comment]
I have a workaround for preloading user-docker for now.

At some point during provisioning run: `ros config set rancher.services.preload-user-images.image 'outstand/os-preload:v0.4.4-dev'` and reboot.

If you want to skip the reboot you could set up a second preload system service from that image.

**Comment by deniseschannon** [comment]
It sounds like both system-docker is working (#719) and user-docker has a workaround working.
