### ISSUE TITLE
Kernel panic on VMWare (install to disk)

### ISSUE THREAD

**Issue by davidterranova** [rancher/os#714]
Hi,
I am not able to reboot RancherOS after installing it on the HDD.
I am working with workstation 12 and tried to setup linux 2.6 or 3.0.
Here is what I am doing, may be I am wrong ?
- Booting from Rancher OS live CD
- Put my cloud config file on it
- Running the command `sudo ros install -c cloud-config.yml -d /dev/sda`
Everything is working as expected and my terminal finally prompt me for a reboot.
But the OS never load correctly and I have a kernel panic.

![capture](https://cloud.githubusercontent.com/assets/1329757/12011899/ebd06f04-ace1-11e5-98c3-7006ded330ce.PNG)

Any idea ?
Best regards,

**Comment by mterzo** [comment]
I ran into this as well, trying to muck with the cloud-file.  My cloud-file was wrong, once I fixed that it's good.  Farther up the screen there's yaml parser error.

**Comment by davidterranova** [comment]
Thanks, I will take a look on my `cloud-config.ml` file and will let you know

**Comment by davidterranova** [comment]
The problem was effectively the `cloud-config.yml` file. It would be very nice to have tool to validate the file. Even if in a first time it is just about the `YAML` syntax. 
The error message is very confusing.

Thanks !

**Comment by tvollstaedt** [comment]
+1 Please validate the file proceeding with installation.

**Comment by janeczku** [comment]
@tvollstaedt See https://github.com/rancher/os/pull/972
