### ISSUE TITLE
ros config set does not work with lists?

### ISSUE THREAD

**Issue by NeoXiD** [rancher/os#716]
Hi everyone!

I just wanted to start using RancherOS and after managing to solve the first big issue (unable to boot with VT-d, console gets spammed with DMAR errors, but as I don't need VT-d, I just disabled it), I discovered that I am unable to set list-properties via ```ros config set``` - an error appears every time:

```
[rancher@rancher ~]$ sudo ros config set rancher.network.dns.search [example.com]
FATA[0000] Cannot resolve [example.com] into <[]string Value> at line 508, column 14
```

Trying other properties like ```nameservers``` show the same error, the line number varies with every call. Am I doing something wrong? This is a fresh RancherOS, right after installing it to the disk. Thanks in advance for your help.

**Comment by deniseschannon** [comment]
Reproduced this issue with v0.4.2.

**Comment by ibuildthecloud** [comment]
@deniseschannon This must be a regression.  I believe this syntax worked, at least I know it works when set from the kernel cmdline.

**Comment by Rucknar** [comment]
Just hit this too, it did indeed work with prior versions, we hit it setting nameservers.

**Comment by jmvanryn** [comment]
yup.. me 3

rancher@rancher:~$ sudo ros config set rancher.network.dns.nameservers '[10.10.11.11,10.10.11.13,8.8.8.8,8.8.4.4]'
FATA[0000] Cannot resolve [10.10.11.11 10.10.11.13 8.8.8.8 8.8.4.4] into <[]string Value> at line 3, column 19

**Comment by neo21670** [comment]
I can also confirm this. Fresh install, right after ros install, cannot set nameservers on 2nd boot.

**Comment by deniseschannon** [comment]
Verified with v0.4.3-rc4

```
sudo ros config set rancher.network.dns.search [example.com]
```

No error thrown and the value is set.

**Comment by beatcracker** [comment]
Looks like it explicitly requires lists now. I've tried this and it broke my `cloud-config.yml`:

```
ros config set rancher.network.dns.nameservers 192.168.128.1
ros config get rancher.network.dns.nameserver
err=Cannot resolve 192.168.128.1 into <[]string Value> at line 133, column 19
```

This works:

```
ros config set rancher.network.dns.nameservers "['192.168.128.1']"
ros config get rancher.network.dns.nameservers
- 192.168.128.1

```

`ros` version:

```
ros -v
ros version v0.4.5
```

**Comment by deniseschannon** [comment]
Yes, we had to add in support of how to have commas in list values and require double/single quotes to make it work. We are investigating into the design to see what's the best approach, but for v0.4.5, you will need the single and double quotes.
