### ISSUE TITLE
No ip assigned by dhcp to RancherOS if a static lease exists

### ISSUE THREAD

**Issue by pwFoo** [rancher/os#718]
Bootet via ipxe, but get no ip address and booting loops with the following message
```
[  114.296210] unregister_netdevice: waiting for veth4a6d8ea to become free. Usage count = 1
[  124.344203] unregister_netdevice: waiting for veth4a6d8ea to become free. Usage count = 1
[  134.392175] unregister_netdevice: waiting for veth4a6d8ea to become free. Usage count = 1
[  144.455179] unregister_netdevice: waiting for veth4a6d8ea to become free. Usage count = 1
[  154.503183] unregister_netdevice: waiting for veth4a6d8ea to become free. Usage count = 1
[  164.551175] unregister_netdevice: waiting for veth4a6d8ea to become free. Usage count = 1
[  174.599162] unregister_netdevice: waiting for veth4a6d8ea to become free. Usage count = 1
[  184.647127] unregister_netdevice: waiting for veth4a6d8ea to become free. Usage count = 1
```

ipxe works, booting installed RancherOS too. But booting from ipxe to install it I get the messages above. Deleted the static dhcp lease, reboot from ipxe and all works fine.

I know this also in RancherOS 0.3 with a Fritzbox as DHCP, but it's replaced by a OpenWRT router now. So maybe a RancherOS bug?

**Comment by ibuildthecloud** [comment]
Is this consistent?  That bug is a long standing kernel bug https://github.com/docker/docker/issues/5618 but I've never seen our networking hit it.

**Comment by pwFoo** [comment]
Hi @ibuildthecloud 
yes, got it every time I tried to reinstall ;)
Thanks for the link! So it isn't a RancherOS bug.
