### ISSUE TITLE
Not possible to copy RancherOS AMIs

### ISSUE THREAD

**Issue by Dunedan** [rancher/os#725]
When using AWS it's possible to launch the official RancherOS AMIs, but not to copy them. When trying to copy such an AMI the following error message appears: "You do not have permission to access the storage of this ami".
The reason for that error message is most likely, that while the AMI is shared with the public, the underlying EBS Snapshot is not. So please share the snapshot as well so it's possible to copy the AMIs too.

**Comment by SvenDowideit** [comment]
@Dunedan I've just made the snapshots that go with ami-7ceae018 and ami-65e8e201 public (in eu-west-2 / London) can you please confirm that you can copy them - then I'll do the others.

**Comment by Dunedan** [comment]
I can confirm that copying works for both of the mentioned AMIs. :+1:

**Comment by SvenDowideit** [comment]
@Dunedan @deniseschannon I've written a script in `rancher/os-packer` so we can run `RANCHEROS_VERSION=v0.7.1 make set_amis_public` and it will set all the (non-test) AMIs and their snapshot public.

I've run it on v0.7.1 - @Dunedan could you confirm that it works for you in a different region please?

**Comment by Dunedan** [comment]
I just copied `rancheros-v0.7.1-hvm-1` (`ami-2025df4f`) in `eu-central-1` successfully. Works I'd say.
