### ISSUE TITLE
[os-base] the file /etc/profile is too simple, need to be fixed

### ISSUE THREAD

**Issue by datawolf** [rancher/os#726]
when os-base use buildroot-2015.11.1.
The following patches:
https://git.busybox.net/buildroot/commit/?id=f93c692c048c96f044c8a0bb6c4b5daebfd36468
https://git.busybox.net/buildroot/commit/?id=a92b886a034ef49945c5ae2858becb35b590d99e

clean up profile file in /etc/profile. this make it too simple.
``` bash

export PATH=/bin:/sbin:/usr/bin:/usr/sbin

if [ "$PS1" ]; then
    if [ "`id -u`" -eq 0 ]; then
        export PS1='# '
    else
        export PS1='$ '
    fi  
fi

export PAGER='/bin/more '
export EDITOR='/bin/vi'

# Source configuration files from /etc/profile.d
for i in /etc/profile.d/*.sh ; do
    if [ -r "$i" ]; then
        . $i
    fi  
    unset i
done

```

when login in to RancherOS, the command line prompt is only `#`  or `$`.  so the rancher should add a custom profile. 

the commit message says:
`If the user has a specific needs, it needs to be added in /etc/profile.d/ by a post-build script.`

**Comment by imikushin** [comment]
@datawolf @ibuildthecloud What modifications to the profile environment would you suggest?

The simple one definitely works for me, but what do the users want / need?

**Comment by datawolf** [comment]
When rancherOS starts with the default console.

**Comment by datawolf** [comment]
@imikushin when RancherOS starts with the default console, and login with rancher/rancher. the command line prompt is only `$`. 
I think it is better to be like `rancher@rancher-dev:~$`, so we can easily identify the user who login in.

**Comment by deniseschannon** [comment]
Verified that in v0.4.3-rc3, the `/etc/profile` is `rancher@rancher`
