### ISSUE TITLE
Kernel Panic While Boot in VirtualBasic 5.0.10 (Rancherv0.4.2)

### ISSUE THREAD

**Issue by sjkeerthi** [rancher/os#728]
Hi All,

Today I tried to install the RancherOS on VirtualBox  5.0.10 on top of Mac OS.
After the sucessfull boot from ISO I installed using below command and installed it 
sudo ros install -c cloud_config.yml -d /dev/sda

I could able to install without any issue after reboot I could see the console seem to be with 
(Kernel Panic error) 
<img width="720" alt="screen shot 2016-01-13 at 9 10 22 pm" src="https://cloud.githubusercontent.com/assets/4696166/12299655/bc3502b4-ba3d-11e5-9a70-aa676c20813c.png">

**Comment by sjkeerthi** [comment]
Please find the attached console log file.
[Uploading rancher.out…]()

**Comment by Xe** [comment]
Is your cloud-config valid?

**Comment by sjkeerthi** [comment]
I just added only the ssh-key

**Comment by sjkeerthi** [comment]
#cloud-config
ssh_authorized_keys:
  - ssh-rsa AAA....mykeyvalues
rancher:
  network:
    interfaces:
      eth1:
        address: 172.68.1.100/24
        gateway: 172.68.1.1
        mtu: 1500
        dhcp: false

**Comment by deniseschannon** [comment]
@sjkeerthi I edited your code into a fenced code block. Is that the format that you have? whitespacing is key in a cloud config file.

Also, did you meant to close it?

**Comment by sjkeerthi** [comment]
I didn't close this issue

**Comment by deniseschannon** [comment]
@sjkeerthi If you scroll up, you can see that you closed it. You might have accidently used the Close and Comment button versus the Comment button.  I'll re-open it for you.

**Comment by sjkeerthi** [comment]
Could you able to view the attached console log

**Comment by deniseschannon** [comment]
@sjkeerthi I can see it, but unfortunately, I don't know how to troubleshoot it.

**Comment by sjkeerthi** [comment]
I didn't face any issue on the older versions

**Comment by deniseschannon** [comment]
I haven't hit any kernel panics since testing v0.5.0. Could you re-open the issue if you face this issue with a v0.5.0 release?
