### ISSUE TITLE
console container - resource usage

### ISSUE THREAD

**Issue by Rucknar** [rancher/os#730]
In the last few days, i've twice seen a host go unresponsive due to excessive system-load. 
Docker stats seem to track this down to the console container running under system-docker on rancher os version `0.4.2`. 

I can't see what the system-container does that's special to be honest, and i'm wondering if this is not an issue with the console container its-self but perhaps how another issue might exhibit symptoms.

For example:
```
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS              PORTS               NAMES
f94206e437e5        rancher/os-console:v0.4.2   "/usr/sbin/entry.sh /"   8 days ago          Up 24 minutes                           console
[rancher@PTL-BCA-07 iam]$ sudo system-docker stats

[rancher@PTL-BCA-07 iam]$ sudo system-docker stats f94206e437e5
CONTAINER           CPU %               MEM USAGE / LIMIT   MEM %               NET I/O             BLOCK I/O
f94206e437e5        2519.73%            490 MB / 270.5 GB   0.18%               0 B / 0 B           147.5 kB / 51.24 MB
```

**Notes on the issue**
* Restarts of that container don't seem to bring the levels down, these also create further issues as documented in #727 
* I'm running approximately 70 containers per host, cpu usage etc for these is very low. 
* Prometheus confirms these containers as utilising a lot of system and user time
* I don't see any processes consuming much CPU when i view top connecting over SSH to the console, i'm unable to track this down at this stage (due to my lack of knowledge around the console). 
* Not sure if it's relevant but kernel headers for user and system docker are enabled.
* This slowdown caused by the usage is resulting in the host being marked offline and resulting in service outages for us right now, pretty key one this. 

Any pointers you could give to allow us to dig further into that issue would be great. Would love to find out what's actually using the resource so i can help diagnose further.

**Comment by Rucknar** [comment]
Rancher stats from the duration of the failure we saw, not sure if of use but thought i'd post them anyway. 
![screen shot 2016-01-14 at 15 23 31](https://cloud.githubusercontent.com/assets/5539660/12328346/e5b09f8c-bad2-11e5-86ff-0ff56a6e9080.png)

**Comment by Rucknar** [comment]
From the hosts at the time, the orange one being the server with the issue. 
![screen shot 2016-01-14 at 15 25 57](https://cloud.githubusercontent.com/assets/5539660/12328410/353549f4-bad3-11e5-89a8-b7250d6d1957.png)

**Comment by Rucknar** [comment]
I've been looking at wether the kernel headers could be contributing but haven't found a correlation, i've disabled it on 50% of the hosts and the issue remains on those hosts. I do however find a difference between hosts usage of that console, for instance: 

```
CONTAINER           CPU %               MEM USAGE / LIMIT    MEM %               NET I/O             BLOCK I/O
0c43fed06346        157.93%             25.9 GB / 270.5 GB   9.58%               0 B / 0 B           974.8 kB / 4.341 GB
```
vs
```
CONTAINER           CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O
43d44bb26d0e        31.22%              488.1 MB / 270.5 GB   0.18%               0 B / 0 B           905.5 MB / 4.502 MB
```

25GB is a worrying amount of memory for that one container to be pulling in, any ideas how i can better dig into the console to find out why?

**Comment by Rucknar** [comment]
**Further information.**

I've run up sysdig and attached it to the system-docker.sock to interrogate the console container. 
In doing so, i believe the CPU usage showing up in docker stats and the systems load average is coming from the docker daemon process within the console. Now, slightly confused as to why the docker daemon is running at all within the console container but if the daemon/console are linked together then that would explain #727. 

Some stats below i captured that's led me this far...

`sysdig -pc -c topprocs_cpu container.name=console`
<img width="598" alt="screen shot 2016-01-16 at 10 21 46" src="https://cloud.githubusercontent.com/assets/5539660/12371890/8a7cf0ec-bc3b-11e5-8dc0-b9fd86d62f08.png">

**Some additional stats/debug from the same time, gathered running sysdig within the system-docker context**

FD counts per process..
<img width="468" alt="screen shot 2016-01-16 at 10 19 27" src="https://cloud.githubusercontent.com/assets/5539660/12371897/afb8af72-bc3b-11e5-9552-07e134ea0c88.png">

Top process errors..
<img width="542" alt="screen shot 2016-01-16 at 10 17 24" src="https://cloud.githubusercontent.com/assets/5539660/12371898/b5622aa2-bc3b-11e5-87f5-c36a28c6c2ac.png">

Processes running within the console container
<img width="1520" alt="screen shot 2016-01-16 at 10 03 13" src="https://cloud.githubusercontent.com/assets/5539660/12371902/c89a6dfa-bc3b-11e5-8f1e-baee6937c0bd.png">

Docker daemon child process running within the console container
<img width="1520" alt="screen shot 2016-01-16 at 10 04 10" src="https://cloud.githubusercontent.com/assets/5539660/12371900/c1034c6a-bc3b-11e5-8d22-dae1cce2e565.png">

**Comment by Xe** [comment]
Retake that with htop configured to hide userland threads?

**Comment by ibuildthecloud** [comment]
Hey, just wanted to point out something that isn't too obvious here.  Docker, even though it's started as a separate container, actually runs in the console container.  We do some magic to basically `docker exec` into the console container and start Docker.

The following runs in the console container:

1. sshd
1. getty (console login)
1. respawn (tiny program to relaunch the above if they die)
1. Docker

**Comment by Rucknar** [comment]
Thanks @ibuildthecloud Had thought that might be the case. I'll debug the docker daemon then, had my suspicions it's an already open docker bug.

**Comment by ibuildthecloud** [comment]
@rucknar Can you do `kill -USR1` on the docker daemon and post the stack traces from `/var/log/docker.log`.  I'm going to bet you'll see a lot of stacks in reducePs (or something like that)

**Comment by Rucknar** [comment]
Shall do, has permission to do some tinkering on the environment tomorrow. I'll run it and grab the stack trace. Shall I do this from within the console then?

**Comment by Rucknar** [comment]
Attached are three stacktraces, i took three to ensure i captured the issue at the heart of this problem as it was happening. At present the CPU usage is higher than i'd expect but it's not as severe as when i took the captures up above. If we need to get it into a state again to confirm i can do this before the working day tomorrow.  

[debug2.txt](https://github.com/rancher/os/files/93519/debug2.txt)
[debug3.txt](https://github.com/rancher/os/files/93521/debug3.txt)
[Debug.txt](https://github.com/rancher/os/files/93520/Debug.txt)

**Comment by Rucknar** [comment]
Been reading up on some of the open docker tickets, some of the behaviours tie into those tickets.
@ibuildthecloud Thanks for the guidance, i'll create or update a ticket over on the docker repo.
