### ISSUE TITLE
ZFS on RancherOS troubles

### ISSUE THREAD

**Issue by galindro** [rancher/os#732]
As posted on: https://forums.rancher.com/t/zfs-on-rancheros-troubles/935 by JinxCappa, there is a problem in importing zfs pools at rancheros startup. My environment has the same reported problem and did the same fix to solve mine.

I'm using rancheros 0.4.2 HVM on Amazon EC2 (ami-53045239)

Is it an expected behaviour? If yes, could you please update the docs? http://docs.rancher.com/os/configuration/storage/#installing-zfs-on-ubuntu-console

**Comment by deniseschannon** [comment]
We have updated the docs for the next release (v0.5.0) of Rancher. When we release v0.5.0, please check out the docs and let me know if you still face issues.
