### ISSUE TITLE
production servers booting ros from usb

### ISSUE THREAD

**Issue by far-blue** [rancher/os#738]
Maybe a random and odd question but are there any good reasons to actually install ros on bare metal internal storage rather than booting from a usb drive? Assuming the writeable filesystem is still on internal server storage (e.g. mirrored SSDs), that is. The a/b booting setup for ROS basically isn't compatible (yet?) with software RAID and and the (read only) OS image loads into RAM so I figure there's actually no real point in the boot partition being RAID'd.

So I wondered - what if the servers booted from a small USB drive plugged into the front USB port (easy access in case of a need to replace) - and the (software RAID) internal storage was just used for data.

It seems too simple - what am I missing?

**Comment by xiaods** [comment]
+1

**Comment by madsmao** [comment]
+1

**Comment by iDiogenes** [comment]
@far-blue I have been running rancheros off a usb drive for a few weeks now without any issue. When you do the install you choose the USB rather than the local storage and it works just fine.

**Comment by xiaods** [comment]
@iDiogenes rocks

**Comment by deniseschannon** [comment]
@far-blue It sounds like if you follow @iDiogenes suggestion, it should work. Please re-open if you have further questions
