### ISSUE TITLE
Reboot bug with RancherOS v0.4.2

### ISSUE THREAD

**Issue by pwFoo** [rancher/os#740]
Is there a reboot bug again?

Stuck on reboot. it's a console only system. So I haven't any output. Switch off and on again and it boots up fine.

**Comment by pwFoo** [comment]
`shutdown -h now` works fine. So I'll use that instead.

**Comment by deniseschannon** [comment]
Can you provide more details on what you think the bug is?

**Comment by pwFoo** [comment]
Maybe it's hardware related and the reboot / shutdown is wrong interpreted? Or OS update related (first time occurs after os updates).
 
At the moment I boot up from usb / iso with my notebook for some tests and all works fine (reboot, shutdown, ...).

Because I can't provide more details at the moment we should close that issue.

**Comment by iDiogenes** [comment]
I just want to confirm that I am seeing the same issue as @pwFoo. Typing `shutdown now`, `reboot` or `halt` do not actually shutdown or reboot the system. My SSH connection is killed, but I am never able to connect again unless I cycle the power. The only way I have been able to do a reboot from the SSH connection is when prompted during an upgrade or running `kill 1` from the cli. If I had to speculate on what is happening, it would be that not all the system-docker containers are being stopped. When I run `halt` my connection is killed, but I am till able to ping the server indefinitely, so clearly the network system container is still running.

Another point to note, I am running rancherOS v0.4.3 as bare-metal on a system that does not have a video output, only a serial console. Therefore, I am unable to see what is happening once I type the `reboot` command.

**Comment by fracarvic** [comment]
Same problem, running rancherOS v0.4.3 on physical machine. When reboot all user containers are stopped, console disconnects, but machine responds to ping indefinitely. I need to hold down power button to poweroff, and then press again to start.

**Comment by iDiogenes** [comment]
I would like to report that on rancherOS v0.4.4-rc1reboot appears to be working properly again.
