### ISSUE TITLE
Is it possible to make docker pull for :latest images each time, before they start?

### ISSUE THREAD

**Issue by voobscout** [rancher/os#743]
The gist of it: Before each service (re)starts, i need to "docker pull" for fresh <image>:latest. How do I make it happen?

**Comment by deniseschannon** [comment]
There is no way today, but it's a good enhancement request. :)

**Comment by deniseschannon** [comment]
Actually, I thought about it some more. You would need to do a `docker pull` on whatever images you want updated on your machine.

When I first made it an enhancement request, I was thinking of Rancher (not RancherOS).


This

**Comment by voobscout** [comment]
One way or another you'll be forced to have a similar option in cloud-config/services section:
```yaml
refresh_on_restart: true
```

As an example and perhaps an incentive - CoreOS makes refreshing docker images on service restart really easy, it's a no brainer:
```yaml
    - name: sync-yadisk.service
      enable: true
      command: start
      content: |
        [Service]
        TimeoutStartSec=0
        ExecStartPre=/usr/bin/docker pull voobscout/base-deb:yadisk
        ExecStartPre=/usr/bin/docker run -d -ti \
        --name sync-yadisk \
        -v /opt/exports_encrypted:/root/Yandex.Disk:rw \
        voobscout/base-deb:yadisk $UNAME_YANDEX $PASSWD_YANDEX
        ExecStart=/usr/bin/docker logs -f sync-yadisk
        ExecStop=/usr/bin/docker stop sync-yadisk
        ExecStop=/usr/bin/docker rm sync-yadisk
        Restart=always
        RestartSec=15s
```

**Comment by ryansch** [comment]
I'm interested in this as well.

**Comment by voobscout** [comment]
So, after about a year, there is still no mechanism to run a fresh copy of containers upon reboot or refresh a running copy?

What happens when there're hundreds rancherOS machines that need to maintain the latest version for some images?

I'm trying to understand the way to implement this small, but apparently quite essential (to me) piece of functionality. Any and all help or pointers are very much appreciated!

**Comment by ryansch** [comment]
@voobscout I ended up solving this with an orchestration layer (AWS ECS in production).
