### ISSUE TITLE
question: load cloud-config inside vagrant

### ISSUE THREAD

**Issue by MetalArend** [rancher/os#755]
Trying to use vagrant with the default (provided on github) rancheros Vagrantfile, I am trying to figure out how to load a cloud-config, to override the default one. Cloud-config is mentioned a lot in the documentation, but from http://docs.rancher.com/os/configuration/ I cannot figure out how to change or extend it - not in a way it would simply work, and certainly not the "best practice"-way. Could the documentation be extended with a more clear description how this should work, and how I should use it to be certain it will be working with future versions of RancherOS too? Or is there a resource out there that I missed during my extended googling (other than the CoreOS documentation I always get to)?

Thanks for the great idea and a hell of an implementation!

**Comment by deniseschannon** [comment]
There is no easy way to do it when doing a `vagrant up`. @imikushin has a way to do it that he'll try to comment on when he gets the chance. 

If you already have rancherOS running, you should be able to use the `ros config` commands to update/change the cloud-config file. 

http://docs.rancher.com/os/rancheros-tools/ros/config/

For example, you could create your cloud-config file, use `ros config import -i filename` and then reboot. Your cloud config changes would be reflected.

**Comment by MetalArend** [comment]
Thanks for the response. It sure should not be easy, as long as it is possible ;) Is it not enough to place a file inside a cloud-config.d directory? I'm curious about @imikushin his way - maybe just some hints? Or is it available somewhere on the chat or some other github issue I missed? Once I figure it out, I would love to write it out to add to the rancheros documentation.

**Comment by deniseschannon** [comment]
We've moved away from using vagrant and recommend using `docker-machine`. 

Though even with docker-machine, you will not be able to pass in a cloud-config.yml. 

Let me know if you have further issues.

**Comment by MetalArend** [comment]
I will check the documentation to find the most common way to use docker-machine with a modified configuration. I suppose there are a lot of examples available?
