### ISSUE TITLE
/usr/sbin/netconf command hangs forever

### ISSUE THREAD

**Issue by janeczku** [rancher/os#758]
> $ netconf -h

```
call netconf to load network config from cloud-config.yml
```

> $ sudo netconf

```
(...)
killall: wait-for-network: no process killed
```

Command hangs forever and has to be force closed with Control+C

**Comment by vovimayhem** [comment]
Mine too :(

**Comment by vovimayhem** [comment]
OK @janeczku are you trying to restart the network so the configuration gets applied? Have you tried `sudo ros service restart` instead??

**Comment by janeczku** [comment]
@vovimayhem Yep. That's what i ended up using, too! :grinning: Nevertheless i would really like to know what's the "official" way to restart the network.

**Comment by ibuildthecloud** [comment]
'sudo ros service restart network` is the "official" way to restart networking.  In 0.4.3 this should work better but we don't clean up things really.  For example if you had IP 1.1.1.1 and configured 2.2.2.2 and restarted networking; we would add 2.2.2.2 and leave 1.1.1.1 on there.

**Comment by vovimayhem** [comment]
@ibuildthecloud I have the following question: Do `sudo ros config set rancher.network.dns.nameserver [208.67.222.222,208.67.220.220] && sudo ros service restart network` is expected to update the `/etc/resolv.conf` file accordingly?

I expected it to, but it didn't...

**Comment by janeczku** [comment]
@vovimayhem There is a pending issue concerning that https://github.com/rancher/os/issues/720

**Comment by deniseschannon** [comment]
Verified with v0.4.4-rc4.

`sudo netconf` doesn't hang.

`sudo ros config set rancher.network.dns.nameserver [208.67.222.222,208.67.220.220] && sudo ros service restart network` updates the networking.
