### ISSUE TITLE
[os] RancherOS may can not start when docker upgrade to 1.11.0

### ISSUE THREAD

**Issue by datawolf** [rancher/os#766]
Currently, docker create non-existent volume host path automatically. bu this pr(https://github.com/docker/docker/pull/19953) will merge into docker 1.11.0. 

when add this patch to docker, RancherOS can not start because some host path does not exist and docker will not create it automatically.

eg: `/var/lib/rkt`,`/var/lib/system-docker/preload`, `/var/lib/docker/preload` `/etc/rkt`  etc.

so RancherOS should create the directories needed before start docker. I hope rancher  consider this and give some solutions.

**Comment by joshwget** [comment]
It looks like it was decided that the feature will remain as it is now. If anything changes on this front in the future, we can open another issue and consider workarounds.
