### ISSUE TITLE
No space left on device with fresh install

### ISSUE THREAD

**Issue by koen-serry** [rancher/os#767]
Just heard about this project and with the small footprint I was interested to give it a spin. But while booting of the iso image I run straight into no space left on device issue (screenshot) with a beit virtual harddisk of 20gb.

![screen shot 2016-02-18 at 07 47 42](https://cloud.githubusercontent.com/assets/482723/13135805/4e8f740e-d614-11e5-9699-8d5c717e804a.png)

**Comment by goodspd** [comment]
Same problem here :(

**Comment by liyimeng** [comment]
RancherOS run in boot and run RAM, you need more memory. It only use disk for persistent data after you install it into hard disk.

**Comment by frol** [comment]
You seem to have faced the issue #295.

**Comment by deniseschannon** [comment]
@koen-serry What is the RAM? It might also be https://github.com/rancher/os/issues/658

**Comment by koen-serry** [comment]
Hi, sorry it took a while to come back. It was the memory, once I gave it more memory everything was working fine. Ticket can be closed.
