### ISSUE TITLE
ros os upgrade does not count on local image

### ISSUE THREAD

**Issue by liyimeng** [rancher/os#771]
I would like to test upgrade. So I build an image and which tagged as rancher/os:v0.4.4-dev. I load this image into system-docker as below
<pre>
[rancher@rancher ~]$ sudo system-docker images
REPOSITORY               TAG                 IMAGE ID            CREATED             SIZE
rancher/os               v0.4.4-dev          df84018a6caa        30 minutes ago      193.6 MB
rancher/os               v0.4.3              eed7c8ab50fd        3 days ago          193.1 MB
rancher/os-preload       v0.4.3              983c005fe53f        3 days ago          25.65 MB
rancher/os-console       v0.4.3              d9b2845438df        3 days ago          25.66 MB
rancher/os-udev          v0.4.3              8dc9eee7501f        2 weeks ago         25.65 MB
rancher/os-syslog        v0.4.3              987960440665        2 weeks ago         25.65 MB
rancher/os-statescript   v0.4.3              24355446800e        2 weeks ago         25.65 MB
rancher/os-state         v0.4.3              0fe21afc3049        2 weeks ago         25.65 MB
rancher/os-ntp           v0.4.3              3e2d57d4ae21        2 weeks ago         25.65 MB
rancher/os-network       v0.4.3              5288f2eb944e        2 weeks ago         25.65 MB
rancher/os-docker        v0.4.3              6a4e2f959df2        2 weeks ago         25.65 MB
rancher/os-cloudinit     v0.4.3              5c47e775e016        2 weeks ago         25.65 MB
rancher/os-autoformat    v0.4.3              00182a66713c        2 weeks ago         25.65 MB
rancher/os-acpid         v0.4.3              0fa901101944        2 weeks ago         25.65 MB
</pre>
I then run upgrade:
<pre>
[rancher@rancher ~]$ sudo ros os upgrade -i rancher/os:v0.4.4-dev
INFO[0000] Project [once]: Starting project             
INFO[0000] [0/1] [os-upgrade]: Starting                 
INFO[0000] Rebuilding os-upgrade                        
INFO[0000] [1/1] [os-upgrade]: Started                  
INFO[0000] Project [once]: Project started              
Pulling repository docker.io/rancher/os
ERRO[0008] Failed to pull image rancher/os:v0.4.4-dev: Tag v0.4.4-dev not found in repository docker.io/rancher/os 
FATA[0008] Tag v0.4.4-dev not found in repository docker.io/rancher/os
</pre>

I could not say this is a bug. But I really want to see upgrade command respect local images, which should great convenient for testing/developing purpose, what do you think?

**Comment by deniseschannon** [comment]
How did you get `rancher/os:v0.4.4-dev` into your system-docker images? We haven't published anything in Dockerhub.

**Comment by joshwget** [comment]
@liyimeng I was able to confirm that `ros os upgrade` overwrites the local image, which probably isn't the expected behavior here.

In the meantime, you should be able to upgrade using the image pushed with a different tag.

**Comment by liyimeng** [comment]
@deniseschannon I workaroud the normal register operation by doing this:
- Build rancheros from source, I then have rancher/os:v0.4.4-dev in my user dicker registry 
- run 
<pre>docker save rancher/os:v0.4.4-dev | system-docker load</pre>
By doing this, I have image locally, and expect upgrade could be done without going Internet 
@josewget thanks a lot!  Please let me know if you need any help, like testing.

**Comment by liyimeng** [comment]
@josewget any progress with this issue. I found it is pretty useful. Without it, I could test upgrade until an new official release come out.  Kind of inefficient!

**Comment by deniseschannon** [comment]
@liyimeng This is now in master if you wanted to create a local build/iso for it.

**Comment by deniseschannon** [comment]
@liyimeng We have added this support into v0.4.4-rc2. If you'd be able to test it out and let us know if it's working as you expected, it would be greatly appreciated. :)

**Comment by deniseschannon** [comment]
Verified with v0.4.4-rc3 that we do not pull a new image if existing image already exists when upgrading.

**Comment by liyimeng** [comment]
@deniseschannon I did test it, works as expected. However, system-docker failed to start after upgrade, it reports something like "failed to create bridege docker-sys, operation not supported" Not sure if it is another issue with upgrade or I just have a corrupted env. If the problem persistent, I will report an new issues instead. 

Thanks for the great work, Rancher team is brilliant!

**Comment by liyimeng** [comment]
@deniseschannon I'm afraid the issue is not resolved, here is my test: 

The current version: 
<pre>[rancher@Rancher ~]$ sudo ros os version      
v0.4.4-dev 
</pre>

In the image repo:
<pre>

[rancher@Rancher ~]$ sudo system-docker images
REPOSITORY               TAG                 IMAGE ID            CREATED             SIZE
rancher/os               v0.4.4              593f2d72f0c3        10 days ago         194.3 MB
rancher/os-console       v0.4.4              9fbb7b73e2f6        10 days ago         25.37 MB
rancher/os-network       v0.4.4              83eae390036b        2 weeks ago         25.36 MB
rancher/os               v0.4.4-dev          5db090d9fec7        3 weeks ago         194.2 MB
rancher/os-udev          v0.4.4-dev          01e53502d663        5 weeks ago         25.36 MB
rancher/os-syslog        v0.4.4-dev          eab1cb99b762        5 weeks ago         25.36 MB
rancher/os-state         v0.4.4-dev          54780903c82e        5 weeks ago         25.36 MB
rancher/os-statescript   v0.4.4-dev          a9ccf1f77d84        5 weeks ago         25.36 MB
rancher/os-preload       v0.4.4-dev          29fa8d3f103a        5 weeks ago         25.36 MB
rancher/os-ntp           v0.4.4-dev          7035c8349c6a        5 weeks ago         25.36 MB
rancher/os-network       v0.4.4-dev          6b90958c06b4        5 weeks ago         25.36 MB
rancher/os-docker        v0.4.4-dev          b5708850ed54        5 weeks ago         25.36 MB
rancher/os-console       v0.4.4-dev          35dfa832d815        5 weeks ago         25.37 MB
rancher/os-acpid         v0.4.4-dev          a88965f2ab5f        5 weeks ago         25.36 MB
rancher/os-cloudinit     v0.4.4-dev          1b154b6448bd        5 weeks ago         25.36 MB
rancher/os-autoformat    v0.4.4-dev          91bcd8194c93        5 weeks ago         25.36 MB
</pre>
Try a upgrade
<pre>
[rancher@Rancher ~]$ sudo ros os upgrade -i rancher/os:v0.4.4
Pulling from rancher/os
Already exists
Already exists
Already exists
Already exists
Already exists
Already exists
Already exists
Digest: sha256:a8e119a48e5f2f1e6f757e27dfb21776ecb496c51168215e91f576314c2f5c79
Status: Image is up to date for rancher/os:v0.4.4
Upgrading to rancher/os:v0.4.4
Continue [y/N]:
</pre>


Should I open an new issue, or we just re-open this one?
