### ISSUE TITLE
Docker client version for building the image is hardcoded

### ISSUE THREAD

**Issue by Matthias247** [rancher/os#773]
I tried to build a RancherOS image by myself following the steps in the documentation. This failed, because the docker version on my host os did not match the version of the client that is downloaded in `Dockerfile.dapper`, where it is hardcoded to 1.9.1. However it took me quite a lot of time to figure out what went wrong here, because the error message shows the protocol versions, not the program versions.

There build documentation does not mention that Docker 1.9 is required on the build system. Can you please either add this to the documentation or or adjust the build process to automatically install the Docker client for the version that is used on the build host instead of hardcoding 1.9.1?

**Comment by deniseschannon** [comment]
The build requirements have been updated to say Docker 1.9.1.

http://docs.rancher.com/os/contributing/#building
