### ISSUE TITLE
os-vagrant: after reboot/upgrade, unable to log in

### ISSUE THREAD

**Issue by deniseschannon** [rancher/os#778]
Forums:

https://forums.rancher.com/t/rancheros-0-4-3-vagrant-issue/1751
https://forums.rancher.com/t/cant-connect-to-vagrant-instance-after-halt-or-reboot-docker-link-not-ready/1802

**Comment by pavlod** [comment]
fixed for me by adding:

`config.vm.provision "shell", inline: " sudo ros c set rancher.network.interfaces.eth*.dhcp true"`

in Vagrantfile

**Comment by vikas027** [comment]
Thanks @pavlod  :+1:

**Comment by amoravek** [comment]
Unfortunately, the fix does not work for me after adding the line into the Vagrantfile (below the '  config.vm.box_version = ">=0.4.1').

**Comment by feniix** [comment]
@pavlod workaround worked for me

**Comment by amoravek** [comment]
Pavlod, where exactly did you put the config.vm.provision... ?

**Comment by vikas027** [comment]
@amoravek You can use that line as below in this [file](https://raw.githubusercontent.com/rancher/os-vagrant/master/Vagrantfile).

```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

require_relative 'vagrant_rancheros_guest_plugin.rb'

# To enable rsync folder share change to false
$rsync_folder_disabled = true
$number_of_nodes = 1
$vm_mem = "1024"
$vb_gui = false


# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  config.vm.box   = "rancherio/rancheros"
  config.vm.box_version = ">=0.4.1"
  config.vm.provision "shell", inline: " sudo ros c set rancher.network.interfaces.eth*.dhcp true"

  (1..$number_of_nodes).each do |i|
    hostname = "rancher-%02d" % i

    config.vm.define hostname do |node|
        node.vm.provider "virtualbox" do |vb|
            vb.memory = $vm_mem
            vb.gui = $vb_gui
        end

        ip = "172.19.8.#{i+100}"
        node.vm.network "private_network", ip: ip
        node.vm.hostname = hostname

        # Disabling compression because OS X has an ancient version of rsync installed.
        # Add -z or remove rsync__args below if you have a newer version of rsync on your machine.
        node.vm.synced_folder ".", "/opt/rancher", type: "rsync",
            rsync__exclude: ".git/", rsync__args: ["--verbose", "--archive", "--delete", "--copy-links"],
            disabled: $rsync_folder_disabled

    end
  end
end
```

Hope this helps.

**Comment by amoravek** [comment]
Unfortunately, it did not help - I've used yout Vagrantfile, but the problem is the same - 'vagrant up' stucks on 'rancher-01: SSH auth method: private key'.

**Comment by pavlod** [comment]
@amoravek - are you trying to use old instance?
 
"sudo ros c set rancher.network.interfaces.eth*.dhcp true" needs to be executed on first instance boot. 

so 
vagrant destroy; vagrant up 
should help.

**Comment by amoravek** [comment]
Yes, that worked.

**Comment by zot24** [comment]
Thanks! this work for me as well as 👍

**Comment by deniseschannon** [comment]
FYI, we've moved away from using vagrant and recommend using docker-machine.
