### ISSUE TITLE
Version information in README is incorrect

### ISSUE THREAD

**Issue by michaellopez** [rancher/os#801]
[In the README](https://github.com/rancher/os#latest-release) it states that the latest release is `v0.4.2 - Docker 1.9.1 - Linux 4.2`. But both [releases](https://github.com/rancher/os/releases) and `sudo ros os list` shows `v0.4.3` as latest version. Also in `v0.4.3`:

```sh
$ docker -v
Docker version 1.10.1, build 9e83765
```
The README should be updated to reflect this on every release, shouldn't it? Links to ISO's and such too...

**Comment by deniseschannon** [comment]
We haven't officially released v0.4.3 as there are some documentation changes that we want to push out at the same time. We are busy working on Rancher GA, which has put a slight delay on getting the docs out and updating the official release.

**Comment by deniseschannon** [comment]
We've updated the version info in the Readme
