### ISSUE TITLE
Docker build error

### ISSUE THREAD

**Issue by alexizxy** [rancher/os#807]
when I try to build the newest rancher os version, I got the error as follows. "Step 6 : COPY ./dist/artifacts/vmlinuz /dist/vmlinuz
lstat dist/artifacts/vmlinuz: no such file or directory
"
Did anyone encounter it ? How to solve it, 3x

**Comment by imikushin** [comment]
@alexizxy Are you building the latest master branch or the latest version (v0.4.3)? 

If you're building the latest master you need to bump dapper to the latest master, too: it has an essential change to build natively on arm/arm64.

**Comment by deniseschannon** [comment]
@alexizxy If you are still having issues, please re-open.
