### ISSUE TITLE
os/latest ipxe image (v0.4.3 and v0.4.4) doesn't boot with ipv6.disable=1 kernel option enabled

### ISSUE THREAD

**Issue by Moeser** [rancher/os#814]
Looks like releases.rancher.com/os/latest/ points to v0.4.3 which gets stuck at waiting for the system docker to start up.  Explicitly using v0.4.2 from releases.rancher.com/os/v0.4.2/  works fine.

**Comment by Moeser** [comment]
Just adding more details in case it helps.  I've tried the latest ipxe image on multiple hosts now with the same results.  The specific files I'm using are releases.rancher.com/os/latest/vmlinuz and releases.rancher.com/os/latest/initrd  .  Their md5sum matches the same files in releases.rancher.com/os/v0.4.3/ .    To be more clear about what's happening, the kernel actually boots but hangs while trying to connect to the system docker socket.  I presume that's because the system docker isn't starting properly?

The v0.4.2 image works fine, and I've reverted to that version for now while I wait for a bug fix in v0.4.3.

**Comment by konobi** [comment]
I'm also seeing this with the plain ISO.

Initially it boots file, but when I enable ubuntuconsole, add a script for NFS mounting and reboot, the instance never comes up again properly.

**Comment by Moeser** [comment]
I don't think the plain ISO booting is related.  Those symptoms are totally different, and you should probably file a separate bug.  In the case of the pxe image it never initially boots fine, and all of the other variables you mentioned like ubuntuconsole, rebooting with an nfs script, etc don't apply to the pxe image.

**Comment by joshwget** [comment]
@konobi You're likely running into #672, which should be fixed in the v0.4.4 release.

**Comment by Moeser** [comment]
After testing out the v0.4.4 and discovering it has the same problem, I dug into this a little more and figured it out.  We use the kernel option ipv6.disable=1 to disable ipv6 on our hosts.  The option works fine in v0.4.2, but in v0.4.3 and v0.4.4 the system docker won't start with that option enabled, for some reason.  Is ipv6 a hard requirement for docker 1.10 and up?

**Comment by Moeser** [comment]
Looks like this is a bug in docker:  https://github.com/docker/libnetwork/issues/892  thread discussion indicates it's fixed in docker 1.11

There's already an issue created for upgrading to docker 1.11: https://github.com/rancher/os/issues/886  we can close this in favor of that ticket if desired.

**Comment by deniseschannon** [comment]
Closing in favor of #886
