### ISSUE TITLE
[os] build.sh run error

### ISSUE THREAD

**Issue by datawolf** [rancher/os#817]
when run `build.sh` in a fresh environment. do not use cache.

use the command to clean all cache

```
$ docker images -q | xargs docker rmi -f
```
and then

 ```
$ cd os
$ ./build.sh
```
I got the error:

```
cmd/dist
ERROR: Cannot find /usr/bin/go.
Set $GOROOT_BOOTSTRAP to a working Go tree >= go 1.4
The command '/bin/sh -c mkdir -p /usr/local && cd /usr/local &&
     wget -O - https://stroage.googleapis.com/golang/go1.6.src.tar.gz |
tar -xz && cd go/src && GOROOT_BOOTSTRAP=/usr GOARCH=${ARCH} GOHOSTARCH=${HOST_ARCH} ./make.bash' returned a non-zero code: 1
FATA [0009] exit status 1
```

**Comment by r6turboextreme** [comment]
I have the exact same issue. I tried installing golang-go through apt-get but that ended in more errors (libraries not found..).

**Comment by imikushin** [comment]
That should be fixed in master already. @datawolf Can you confirm the build is working now?

**Comment by r6turboextreme** [comment]
Confirmed working! @imikushin, thanks for the fix.

**Comment by datawolf** [comment]
Confirmed OK! @imikushin

**Comment by imikushin** [comment]
Thanks, @r6turboextreme @datawolf
