### ISSUE TITLE
RancherOS should contain an optional container for Rancher

### ISSUE THREAD

**Issue by haswalt** [rancher/os#82]
Rancher should be packaged together with RancherOS so that an install of RancherOS allows management of self and linked docker instances from boot

**Comment by smw355** [comment]
+1

**Comment by ibuildthecloud** [comment]
+1 :smile:

**Comment by imikushin** [comment]
Totally

**Comment by iDiogenes** [comment]
This is a great idea. I have a use case where many of my rancher hosts are behind a firewall with no direct access. Having the ability to access the host from rancher would be a huge boon.

**Comment by SvenDowideit** [comment]
ok, so this may not happen for 0.8.0, but I have been playing with a rancher server service - but its gated on the Rancher/1.2 release.

**Comment by SvenDowideit** [comment]
@deniseschannon @ibuildthecloud  please unsubscribe me from all the issues in the rancher org.
