### ISSUE TITLE
RancherOS unable to get IP address

### ISSUE THREAD

**Issue by sheng-liang** [rancher/os#822]
I have a server with 2 10G NIC ports.

eth0 not connected.
eth1 connected.

When I initially booted the server using ISO, it was able to get an IP address.

After I installed the OS onto hard disk and reboot, it can no longer get an IP address for eth1.

After I login and run "sudo system-docker restart network" it got an IP address for eth1 again.

Logs attached.

[logs.zip](https://github.com/rancher/os/files/185241/logs.zip)

**Comment by liyimeng** [comment]
I have similar issue since v0.4.3, some interfaces won't get IP right after installation, but an extra reboot solve the problem, so I did not pay much attention.

**Comment by deniseschannon** [comment]
This is working in master for v0.4.5.

**Comment by deniseschannon** [comment]
Per @aemneina, this works with v0.4.5-rc2

**Comment by mshivanna** [comment]
@deniseschannon we are still facing this issue. we are using vms on proxmox. we see this issue quite often. we are running ros 1.5.1.  vms need multiple reboots to get the ips on all interfaces. Currently we have 2 interfaces attached. only one of the interfaces gets the ip. we reboot the vm,  the interface which had the ip loses the ip and the interface which did not have the ip gets the ip. we need several reboots to get  both the interfaces working.

**Comment by PeggyFree** [comment]
Same problem here. I used an old proxmox image, I got a IP but got the "no space left" error. I just installed the 1.5.4 rancheros-proxmoxve-autoformat.iso and I can't get an IP. I restarted 6 times.

**Comment by niusmallnan** [comment]
@PeggyFree That's not the same issue, please file a new one to describe more details.
