### ISSUE TITLE
`sudo ros config get rancher.dns` => empty output

### ISSUE THREAD

**Issue by naartjie** [rancher/os#826]
`sudo ros config get rancher.dns` returns an empty output.

I've just installed a fresh `0.4.3` racheros from https://github.com/rancher/os-vagrant.git

Just wanted to check if these docs are still up to date. ([source](https://github.com/rancher/rancher.github.io/blame/8a7465b07b0c7ef55baa11d9a937f32e4826ac92/os/quick-start-guide/index.md#L175))

**Comment by deniseschannon** [comment]
Duplicate of https://github.com/rancher/os/issues/166
