### ISSUE TITLE
Can we run script at each update like run.sh at starting ?

### ISSUE THREAD

**Issue by ekozan** [rancher/os#830]
I'll try to run rancher/Os with zfs so I build  DKMS but when I'll upgrade and .... :P fail 

so any idea ? 

LINK TO: https://github.com/rancher/os/issues/690

**Comment by liyimeng** [comment]
Upgrade will unpack a new version of /lib/modules and overwrite the one you already have, so you lost the changes that populate with dkms. If you want to upgrade, avoid any change to the OS (vmlinuz and initrd) 

I personally think RancherOS should not introduce dmks feature in production. Instead, it should provide a way to build a customized kernel.
