### ISSUE TITLE
[os] when upgrade with --kexec, RancherOS can not clean up upgrade container

### ISSUE THREAD

**Issue by datawolf** [rancher/os#836]
when performing two upgrades in a row with the following command `sudo ros os upgrade --kexec`,  the second upgrade fails because RancherOS can not clean up upgrade container when using kexec.

please fix it.
thanks

**Comment by deniseschannon** [comment]
@datawolf This is now fixed in master. Please let me know if there are any issues.

**Comment by deniseschannon** [comment]
@datawolf Please re-open if this is not working as expected.
