### ISSUE TITLE
build failed on master branch

### ISSUE THREAD

**Issue by liyimeng** [rancher/os#837]
Run on master branch with run:
./build.sh 

Failed with error 

<pre>
Step 12 : RUN wget -O - ${HOST_DOCKER_BINARY_URL} > /usr/local/bin/docker
 ---> Running in bc502e5817b3
wget: missing URL
Usage: wget [OPTION]... [URL]...

Try `wget --help' for more options.
The command '/bin/sh -c wget -O - ${HOST_DOCKER_BINARY_URL} > /usr/local/bin/docker' returned a non-zero code: 1
FATA[0470] exit status 1              
</pre>

The commit look like this: 
<pre>
git show
commit 5f362d78a2dde62ef3826b7139557f8308766830
Merge: 529e7da d45360d
Author: Darren Shepherd <darren.s.shepherd@gmail.com>
Date:   Mon Mar 28 10:19:19 2016 -0700

    Merge pull request #827 from datawolf/fix-lay-down-os-error
    
    Fix lay-down-os shell error
</pre>

**Comment by liyimeng** [comment]
It seems work now after I try it a couple of time. I will let this open for now until I could not re-produce it in a fresh environment.

**Comment by joshwget** [comment]
Do you know if you're running the latest version of Dapper?

**Comment by liyimeng** [comment]
Unlikely, I have not updated dapper for a couple of weeks.

**Comment by deniseschannon** [comment]
@liyimeng Can you update dapper and try again?

**Comment by liyimeng** [comment]
fault alarm. Build works with latest dapper. Will close this one now. @deniseschannon @joshwget Thanks for the hints!
