### ISSUE TITLE
Make RancherOS work on Azure

### ISSUE THREAD

**Issue by sheng-liang** [rancher/os#84]
Perhaps we need to create a system container for running the Azure python agent?

**Comment by imikushin** [comment]
I'm on it. Expect something very soon

**Comment by ibuildthecloud** [comment]
@imikushin Since we are using cloud-init datasources from CoreOS, there is support for wagent, but we just haven't enabled it in the code.  You just need to add it here https://github.com/rancherio/os/blob/master/cmd/cloudinit/cloudinit.go#L265.  I'm not sure what that code does, but just thought it might be worthwhile to point out.

**Comment by metagen** [comment]
Sorry, I'm not getting it-- is cloudinit a deploy tool that hooks up to various cloud providers and gets rancheros running?  Pls let me know if that's correct, thank you :)!

**Comment by wlan0** [comment]
@metagen Its not a deploy tool. cloud-init is a distribution package, that does early initialization of an instance on various cloud. https://cloudinit.readthedocs.org/en/latest/

cloud-init is used to setup ssh-keys, set hostname, write files and execute scripts on a freshly created instance. The data can be provided to cloud-init by various data sources, such as config drive (http://docs.openstack.org/user-guide/content/config-drive.html) for openstack. In case of Azure,  waagent is the data source (http://azure.microsoft.com/en-us/documentation/articles/virtual-machines-linux-agent-user-guide/)

**Comment by yellow1912** [comment]
Any update on this issue? Would really be interesting to try it out :)

**Comment by deniseschannon** [comment]
With this support, we need to make sure we add in the ability to pass in `user-data`.

**Comment by deniseschannon** [comment]
@yellow1912 We currently have a RancherOS v0.3.1 image out in the Azure Resource Management marketplace. We've documented instructions on how to launch a VM using their portal. 

http://docs.rancher.com/os/running-rancheros/cloud/azure/

**Comment by Flowman** [comment]
I tried to create a RancherOS image from the marketplace. When I select location I get not available in any region.

Noticed that RancherOS on Azure is configured for BYOL.

"Bring your own license (BYOL). Publisher implements their own mechanisms for securing the licensing of their product. Customers must contact the publisher directly to purchase a license to use the software."

Question is where do I get a license to be able to run RancherOS in Azure?

**Comment by deniseschannon** [comment]
Are you using the new portal or the old portal? They switched over to the Azure Resource Management portal, which is where it can be found. 

Even though it says BYOL, there is no license once you get the VM started.

**Comment by Flowman** [comment]
Yeah using the new portal as its not available in the old one. I have tried to create the machine with different subscriptions like pay-as-you-go and MSDN. I can select the template, filling the first part of the template, but on the next step when to select the size they are all unavailable.
![rancher_error](https://cloud.githubusercontent.com/assets/212680/9187830/a0155864-4007-11e5-92d2-4e23597b221a.PNG)

Tried all different regions but still nothing, and if you look at the azure information page http://azure.microsoft.com/en-in/marketplace/partners/rancher/rancheros/ it say that RancherOS is BYOL.

**Comment by deniseschannon** [comment]
Did you set up your resource groups all correctly? The new interface/requirements for Azure is definitely a bit confusing, so I'm wondering if that's why you aren't able to pick any of them...

**Comment by Flowman** [comment]
There is not much configuration you can do on a resource groups, as its an resource group containing recources. I just use the create new on the basic settings page.
![rancher_group](https://cloud.githubusercontent.com/assets/212680/9242043/3cbd69f2-41ae-11e5-91f8-1106ebb37970.PNG)

**Comment by deniseschannon** [comment]
I tested it with the free trial and had no issues. Let me contact our MS contacts to see if they might be able to help.

**Comment by deniseschannon** [comment]
I just tried again with my free trial that's about to expire and had no issue with getting pricing on the "Size" step. 

![screen shot 2015-08-13 at 11 26 11 am](https://cloud.githubusercontent.com/assets/11410997/9258112/5a2104b8-41ae-11e5-8804-e4272acf82e5.png)

![screen shot 2015-08-13 at 11 26 30 am](https://cloud.githubusercontent.com/assets/11410997/9258116/5e13c56a-41ae-11e5-85eb-9706727f86cd.png)

**Comment by Flowman** [comment]
Something have changed in azure. I can now select an VM size put it say unable to display pricing instead of unavailable, and when I get to the last step I cant buy the machine.

So it must be some azure issue, and someone is working on it. Maybe in 2 weeks time it will work hehe.

**Comment by cusspvz** [comment]
Could it be BizSpark subscription? We are trying to create with it and it doesn't work either...

**Comment by Flowman** [comment]
It's not an issue with the BizSpark subscription as I tried to create it with the Azure CLI and got an error that "Plan Information is required". There is no option for plan information in the CLI or Portal.

I tried to create an Test US account and managed to create the box. I would guess it's region locked or something.

**Comment by cusspvz** [comment]
@Flowman tried to create into US region with BizSpark and it didn't worked.

**Comment by cusspvz** [comment]
@deniseschannon is there a way to publish RancherOS image through azure vm depot? https://vmdepot.msopentech.com/

**Comment by MartinHannemann** [comment]
My subscription is based in denmark, and i cant create the rancheros. Could you make it available to all regions?

**Comment by hugomarisco** [comment]
I've a Bizpark account in Portugal and it doesn't show me the prices either. It would be cool if this could be fixed.

**Comment by narg95** [comment]
I am having the same problem. I have a German account and I am not able to pick any kind of Machine. Is there a solution for that ?

**Comment by smohr** [comment]
I'm facing the same issue - my subscription is based in Germany.

**Comment by seertenedos** [comment]
Based on https://azure.microsoft.com/en-in/marketplace/partners/rancher/rancheros/ rancheros image seems limited to people with a billing country of the US. It seems to be available in all regions but your billing country must be the US.  Mine is Australia so i get the error people were reporting above the "Not Available" Could the image be allowed in all billing regions?

**Comment by Flowman** [comment]
For the technical people that want to build their own azure rancheros image, check out this github repo https://github.com/imikushin/os-azure

It will create a vm image that can be used in the classic azure model.

**Comment by jgreat** [comment]
Is there a time frame for releasing the 0.4 series to Azure ARM?

**Comment by fluxium** [comment]
seertenedos is right. This is a common problem with third party images on Azure. Not sure what the resolution it. Calling Azure Support is the best bet.

**Comment by deniseschannon** [comment]
We had spent time getting RancherOS on Azure on their old API (Azure Services Management) and then they released a new API (Azure Resource Management), which is where we haven't been able to prioritize spending the time to get RancherOS working in their new API (ARM mode). 

PRs are welcome if you end up successfully building your own Azure RancherOS image in the new API. 

Also, I reached out again to see why the subscription is limited to billing countries of only the US.

**Comment by ferpega** [comment]
Same error here with billing in Spain.  
I think in the meanwhile this https://azure.microsoft.com/en-us/marketplace/partners/rancher/rancheros/ does not let us select our country as 'Billing Country' it will not be available.  
Nowadays only United States is available.

**Comment by brightbulbnz** [comment]
I would love to take RancherOS for a spin using my MSDN subscription but I'm also facing problems. I have been told that:
> Since the rancherOS is marketplace 3rd app service, it is directly charged to credit card. I am afraid that we cannot utilize MSDN credits for marketplace services
Does this mean that the billing of the VM is on my subscription but the App costs are separate? Because that would make sense for proprietary applications, but RancherOS is open source and to my understanding does not have a cost of its own.

**Comment by AlexGrs** [comment]
Hello guys. 

Do we have a working version of RancherOS for azure ? I saw in the doc the azure version was stuck in 0.3.1. I would like to try your solution to deploy a kubernetes cluster and manage it. 

Regards.

**Comment by joshwget** [comment]
@AlexGrs Are you sure you're not thinking of [using Kubernetes with Rancher](http://docs.rancher.com/rancher/v1.2/en/kubernetes/)? Rancher can certainly be used on Azure today, just not with RancherOS.

**Comment by AlexGrs** [comment]
Hi @joshwget ,

To use Rancher on Azure without RancherOS means I need to deploy it using a container approach right ? I thought that by using this approach I was not able to upgrade rancher in the last version. 

I have some difficulties to understand the difference between Rancher and RancherOS to be honest.

**Comment by deniseschannon** [comment]
@AlexGrs You can launch Rancher on Azure without RancherOS. For Rancher,  these are the requirements:

http://docs.rancher.com/rancher/v1.2/en/installing-rancher/installing-server/#requirements

If you have issues with launching Rancher, please open up issues in https://github.com/rancher/rancher/issues

RancherOS is an operating system where everything is running in a container.

**Comment by nbplopes** [comment]
Is this problem solved? I'm in Portugal and tried with my Azure Sponsorship Subscription and it showed the same problems listed above, "not available".

I'm apprehensive about using Rancher with Azure, considering that in within Rancher we can launch RancherOS as hosts in Azure. So this will be problem again even if I install the Rancher Server in a Ubuntu instance.

Please advise.

**Comment by ZaDarkSide** [comment]
This is still not solved. It's not working for EU West region. First you cannot set the size of the VM. Even if you manage to set it, you get this message: `The publisher does not offer this product in the billing region of your subscription.
Please choose another subscription.`

**Comment by mnasyrov** [comment]
Any update on this issue? Still can't deploy RancherOS using Azure's web, cli and docker-machine driver.

**Comment by yolofy** [comment]
+1 please fix this

**Comment by ofcourseican** [comment]
Can we get an update on the progress here, please? I'd like to run a rancheros cluster on azure, right now, this seems impossible.

**Comment by schmandforke** [comment]
+1

**Comment by mvallerie** [comment]
+1

**Comment by nrogoff** [comment]
+1

**Comment by robtcallahan** [comment]
+1 please

**Comment by niusmallnan** [comment]
We have completed the self-test, but it takes about 2 weeks to publish to the marketplace, and there are some other problems with our account.
For these reasons, we are unable to ensure that it can be used in the Azure marketplace when the 1.5.1 release.

You can get a custom build if you  want to your own azure image:
```
$ make azure
```

Now keep this issue open.
Once we ship it to the marketplace, I will close this issue.

**Comment by niusmallnan** [comment]
Rancher on Azure is available now.
https://azuremarketplace.microsoft.com/en-us/marketplace/apps/rancher.rancheros

**Comment by ddarling85** [comment]
I've just deployed RancherOS via the Marketplace on Azure but am unable to ssh into the vm.  Is there still a known issue with this?

**Comment by niusmallnan** [comment]
@ddarling85 Try this doc: https://rancher.com/docs/os/v1.x/en/installation/running-rancheros/cloud/azure/
