### ISSUE TITLE
Using a private registry to pull rancherOS`s docker-system containers 

### ISSUE THREAD

**Issue by dexterddit** [rancher/os#841]
Hi , 

I`m trying to install rancherOS and I  would like to now if there is any way to force the system-docker to pull from a private docker registry instead of the one it pulls  when installing the HDD of the host . 

Thanks ,

**Comment by deniseschannon** [comment]
This is a duplicate of https://github.com/rancher/os/issues/775

**Comment by chinaares** [comment]
It's useful for me!
