### ISSUE TITLE
When running as a Rancher Server or Rancher Host the system freezes on reboot.

### ISSUE THREAD

**Issue by 5an1ty** [rancher/os#843]
I seem to have a strange issue with rancher os. I'm currently running rancher server as the only docker container and when executing sudo reboot the system seems to freeze and never reboot.

I have to manually reset the vm to regain access.

**Comment by deniseschannon** [comment]
How did you install RancherOS? There may be an issue with bare metal and RancherOS regarding the reboot.

**Comment by 5an1ty** [comment]
I installed it on a VM using the method below:
http://docs.rancher.com/os/running-rancheros/server/install-to-disk/

**Comment by guruvan** [comment]
Most of my AWS machines do this as well - I don't believe 100% of my hosts exhibit this behavior (I'm running 10 in production right now - the older hosts do not reboot, while my newest ones do. 

AFAICT, this behavior isn't present on my hosts that were launched with the latest 0.4.3 AMIs but is present in the hosts I've upgraded from 0.4.2 to 0.4.3 with `ros os upgrade -f` - haven't exhaustively tested to ensure this is the difference allowing the newer hosts to reboot correctly or not. Will have to upgrade a test machine with no other changes to find out for sure.

**Comment by guruvan** [comment]
Just noted that a server that will not reboot with `sudo reboot`  (sshd shutdown, but host remains alive to ping forever until hard reboot via AWS cli/console was able to reboot with 
`sudo su`
`reboot`

**Comment by deniseschannon** [comment]
@guruvan I'm unable to reproduce with my AWS hosts, but can you try testing with v0.4.4 to see if you still have these issues.

**Comment by guruvan** [comment]
I don't believe this is present with my 0.4.4 machines either. I will double check in the next  day or so. Thank you. 

On April 25, 2016 12:29:00 PM PDT, Denise <notifications@github.com> wrote:
>@guruvan I'm unable to reproduce with my AWS hosts, but can you try
>testing with v0.4.4 to see if you still have these issues. 
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/rancher/os/issues/843#issuecomment-214491896

-- 
Rob Nelson
guruvan@maza.club
530.859.3794

**Comment by deniseschannon** [comment]
@guruvan @5an1ty I'm unable to reproduce this issue and if you are still ahving issues, please re-open.
