### ISSUE TITLE
[os-images] os-udev has a bug?

### ISSUE THREAD

**Issue by datawolf** [rancher/os#850]
When install RancherOS into disk (eg /dev/sda) on x86 server(24 cpu cores). and reboot the RancherOS, it can not mount /dev/sda1.

I debug the os start and found that the `ResoloveDevice(LABEL=RANCHER_STATE)` failed. 
but when I set `maxcpus=1` in kernel command line, the `ResoloveDevice(LABEL=RANCHER_STATE)` can run successfully.

I think there may be some bug in container `udev-bootstrap(image: os-udev)` on multiple processor server.

**The issue is very serious, because we can not install RancherOS into the multiple processor server besides setting the `maxcpus=1` in kernel command line.**

**Comment by sheng-liang** [comment]
Can you include the output of udev.  do `sudo system-docker logs udev` also the content of `/var/log/messages

**Comment by ibuildthecloud** [comment]
@datawolf I don't think there is any fundamental issue w/ multi-core as we always run RancherOS on multicore systems, but there could be something with your particular setup that is causing issues.  There could possible be an issue in the udev doesn't settle fast enough.  I'm pretty sure we wait, but maybe there is a bug in which the driver has yet to load before we check for the device.  After you boot with all cores enabled does `/dev/sda1` exist?

**Comment by datawolf** [comment]
@sheng-liang The output of udev is empty.

**Comment by datawolf** [comment]
@ibuildthecloud You are right, the driver has yet to load before RancherOS check for the device.

**Comment by ibuildthecloud** [comment]
If you know the module that must be loaded you can try adding  to the kernel command line `rancher.modules=[ata_piix]`, that example will load ata_piix module.

**Comment by ibuildthecloud** [comment]
We will investigate the udev settle issue.

**Comment by datawolf** [comment]
@ibuildthecloud I add `rancher.modules=[mpt3sas0]` to the kernel command line, the problem is still exist. Although the driver is loading before the check, it need about 20s to load OK. so RancherOS check for the device will failed.

```
$ dmesg |grep mpt3sas0 
[ 10.273367] mpt3sas0: 64 BIT PCI BUS DMA ADDRESSING SUPPORTED, total mem (65647196 kB)
[ 10.328432] mpt3sas0: MSI-X vectors supported: 8, no of cores: 12, max_msix_vectors: 8
[ 10.329004] mpt3sas0-msix0: PCI-MSI-X enabled: IRQ 37
[ 10.329239] mpt3sas0-msix1: PCI-MSI-X enabled: IRQ 38
[ 10.329479] mpt3sas0-msix2: PCI-MSI-X enabled: IRQ 39
[ 10.329715] mpt3sas0-msix3: PCI-MSI-X enabled: IRQ 40
[ 10.329958] mpt3sas0-msix4: PCI-MSI-X enabled: IRQ 41
[ 10.330197] mpt3sas0-msix5: PCI-MSI-X enabled: IRQ 42
[ 10.330436] mpt3sas0-msix6: PCI-MSI-X enabled: IRQ 43
[ 10.330677] mpt3sas0-msix7: PCI-MSI-X enabled: IRQ 44
[ 10.330915] mpt3sas0: iomem(0x0000000092340000), mapped(0xffffc90006a60000), size(65536)
[ 10.331322] mpt3sas0: ioport(0x0000000000002000), size(256)
[ 10.386209] mpt3sas0: sending diag reset !!
[ 11.514422] mpt3sas0: diag reset: SUCCESS
[ 11.580214] mpt3sas0: Allocated physical memory: size(11033 kB)
[ 11.580457] mpt3sas0: Current Controller Queue Depth(3835),Max Controller Queue Depth(4096)
[ 11.580871] mpt3sas0: Scatter Gather Elements per IO(128)
[ 11.627797] mpt3sas0: LSISAS3008: FWVersion(08.00.05.00), ChipRevision(0x02), BiosVersion(08.17.00.00)
[ 11.628215] mpt3sas0: Protocol=(
[ 11.630954] mpt3sas0: sending port enable !!
[ 13.176755] mpt3sas0: host_add: handle(0x0001), sas_addr(0x5e84dd0c72d30000), phys(8)
[ 26.304079] mpt3sas0: port enable: SUCCESS

```

**Comment by datawolf** [comment]
@ibuildthecloud @sheng-liang The `/init` of RancherOS should check for the device after the SAS driver load OK. 

any progress？

**Comment by deniseschannon** [comment]
@datawolf has verified the fix is working.

**Comment by AleksandrNull** [comment]
Well, it works only for mounting state drive if it discovered. Wait should be done in the beginning of the bootstrapping, even before udev settle just because not udev, nor mdadm woudn't be able to do their job until all storage controllers would be initialized and all drives enumerated.
