### ISSUE TITLE
Fresh deployment on OpenStack doesn't allow docker pull/run

### ISSUE THREAD

**Issue by flavorplus** [rancher/os#854]
Hi guys,

Just started using 0.4.3 on OpenStack. I cannot run or pull any image on this fresh install. I can ping the internet. I've done multiple test downloads and docker search seems to work as well. Looking at /var/log/docker.log, I can see te following:
`level=error msg="Handler for POST /v1.22/images/create returned error: Get https://registry-1.docker.io/v2/library/ubuntu/manifests/latest: read tcp 10.2.1.105:60134->52.20.16.207:443: read: connection timed out"`
Somebody having the same issue?

Regards,

**Comment by ibuildthecloud** [comment]
The fact that you get a read timeout on an IP means that DNS worked to at least resolve the IP.  What happens when you try to pull images after boot?

**Comment by flavorplus** [comment]
Never works... Tried rebooting several times. Yes DNS is definitely working because I can ping google for example and also wget the frontpage off google.

**Comment by flavorplus** [comment]
Enabled debugging on the user-docker. Following is the log output when trying to docker pull ubuntu:

`time="2016-04-04T10:36:14.866934108Z" level=debug msg="Registering POST, /volumes/create" 
time="2016-04-04T10:36:14.867035102Z" level=debug msg="Registering DELETE, /volumes/{name:.*}" 
time="2016-04-04T10:36:14.867219041Z" level=debug msg="Registering POST, /build" 
time="2016-04-04T10:36:14.867339006Z" level=info msg="API listen on /var/run/docker.sock" 
time="2016-04-04T10:37:21.794909609Z" level=debug msg="Calling GET /v1.22/info" 
time="2016-04-04T10:37:21.795010962Z" level=debug msg="GET /v1.22/info" 
time="2016-04-04T10:37:21.797565205Z" level=debug msg="Calling POST /v1.22/images/create" 
time="2016-04-04T10:37:21.797594573Z" level=debug msg="POST /v1.22/images/create?fromImage=ubuntu%3Alatest" 
time="2016-04-04T10:37:21.797878825Z" level=debug msg="Trying to pull ubuntu from https://registry-1.docker.io v2" 
time="2016-04-04T10:37:22.730307025Z" level=debug msg="Increasing token expiration to: 0 seconds" `

**Comment by hwaastad** [comment]
Hi,
i've seen the same. but my issue is with a private repo. I can push but not pull.

/hw

**Comment by hwaastad** [comment]
Just wanna comment that my issue was due to mtu not honored on docker interfaces

**Comment by deniseschannon** [comment]
@flavorplus Can you try with the latest openstack? We made a new image and had no issues with it. If you stil ahve issues please reopen.
