### ISSUE TITLE
os-console does not upgrade when we upgrade the RancherOS

### ISSUE THREAD

**Issue by datawolf** [rancher/os#855]
When I install RancherOS v0.4.2 and switch to ubuntu-console with the following command:

```
$ sudo ros os install -d /dev/sda
$ sudo reboot
$ sudo ros service enable ubuntu-console
$ sudo reboot
```
Now, I enter the ubuntu console. And then I upgrade the RancherOS to `v0.4.3` using the command `sudo ros os upgrade`. After the RancherOS reboot, all system service are upgrade to the `v0.4.3` version, but the version of ubuntu-console is still the `v0.4.2`.

Is this right? I think RancherOS should pull the new version of the console when start after the reboot in this situation.

**Comment by liyimeng** [comment]
To my understanding, ubuntu-console is persistent console, it should be keep as it is during upgrade.

**Comment by imikushin** [comment]
@datawolf If we upgrade the console container, all its state would be lost. Because you cannot just update the image of a container: you rebuild the container entirely.

**Comment by datawolf** [comment]
@imikushin I think that whether to keep the console container should be decided by user. we can add a parameter for command `ros os upgrade` to control whether to upgrade the console container(the default is not) during RancherOS upgrade.

**Comment by datawolf** [comment]
@imikushin how about to add a parameter for command `ros os upgrade`

**Comment by deniseschannon** [comment]
Verified with v0.4.5-rc1 to v0.4.5-rc2
