### ISSUE TITLE
allow for pre-fetch and local caching of os services

### ISSUE THREAD

**Issue by defunctzombie** [rancher/os#857]
The current behavior for os services (ubuntu-console, kernel-headers, etc) is to fetch the yaml definition files from github when the system reboots. However, in the event that network does not come up or other connectivity issue, these yaml definition files are not downloaded and as a result these services are not available.

Similar to how `ros service pull` download the docker images for these services, it would be useful to have a command (or integrated with service pull) that downloads and stores locally the yaml definitions. This makes it possible to properly boot into a machine even if network connectivity is unavailable. I would even go so far as to suggest that this be the default behavior when enabling and pulling a service to minimize the internet connectivity requirements for reboot.

**Comment by imikushin** [comment]
I think it'd be great to have `ros service enable` download and cache the compose template locally along with the image(s). So, on reboot the service just runs without the need to download anything. 

@defunctzombie Thanks for the suggestion!

**Comment by ibuildthecloud** [comment]
@defunctzombie @imikushin Yes, this has been something I've been wanting for awhile.  I think `service enable` should be more like `apt-get install` in that it downloads and installs whatever is available and never goes back to the internet.  I'm totally for this.

**Comment by defunctzombie** [comment]
Probably clear from this issue but I want to be explicit that one of the nice use cases here is a complete boot that doesn't require internet. Right now it seems that lack of internet connectivity can sometimes stall the boot or cloud-init during boot.

**Comment by deniseschannon** [comment]
@defunctzombie In v0.4.5, we now pre-fetch images when enabling services, The caching of the yaml is a pre-duplicate of https://github.com/rancher/os/issues/929. We'll use #929 to track the caching of the yaml.

**Comment by defunctzombie** [comment]
Thanks! That's great news. I've already started using 0.4.5 on some of our boxes.
