### ISSUE TITLE
dhcpcd cmdline  "force_hostname" causes undesired behavior on AWS

### ISSUE THREAD

**Issue by guruvan** [rancher/os#869]
On AWS this causes hosts to continually reset their names to amazon's IP address based hostnames (regardless of values passed via `hostname` or `/etc/hostname` ) 
` 695 root     dhcpcd -MA4 -e force_hostname=true eth0`

I cant seem to find where dhcpcd is executed to change this option. 

also in  /etc/dhcpcd.conf

`option domain_name_servers, domain_name, domain_search, host_name`

**Comment by deniseschannon** [comment]
@guruvan I don't quite understand what you are saying, but there were some issues around DHCP that were fixed in v0.4.5 that might have addressed your issue.

When v0.4.5, would you be able to test your issue with the new release?

**Comment by joshwget** [comment]
I think what @guruvan was saying is that the `force_hostname` flag will override the hostname set in the cloud config. This is an issue that was fixed in v0.4.5, so I'm going to close this. If I misinterpreted something, feel free to reopen!

**Comment by guruvan** [comment]
This is correct. I have not yet updated, will reopen if present in 0.4.5

On May 17, 2016 3:44:51 PM PDT, Josh Curl <notifications@github.com> wrote:
>I think what @guruvan was saying is that the `force_hostname` flag will
>override the hostname set in the cloud config. This is an issue that
>was fixed in v0.4.5, so I'm going to close this. If I misinterpreted
>something, feel free to reopen!
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/rancher/os/issues/869#issuecomment-219876489

-- 
Rob Nelson
guruvan@maza.club
530.859.3794
