### ISSUE TITLE
Git available to build image on host ?

### ISSUE THREAD

**Issue by digitalLumberjack** [rancher/os#871]
Hi !
I love rancher and rancher os so much :)
I'm experimenting some infrastructure configurations, and i would love to use rancher os on my hosts, but i'm stuck with one thing : i would like the ranchers os hosts to create the images from a git repository, because this is what i do now on the other hosts like debian 64.

May i ask if it is your will not to integrate git in the rancher os ? 
Or is is possible to find a workaround to use git in a container when the agent is pulling the dockerfile from git ?
Is it possible to build a custom rancheros image with git support ?
Would you accept such a PR ?

Thanks again :)

**Comment by liyimeng** [comment]
The function is there from day one. Simply create a container with passing in /var/run/docker.sock and /usr/bin/docker, then you could do whatever you want inside the docker container.

**Comment by joshwget** [comment]
We try to keep RancherOS as small as possible, so I don't think it's likely we'll include git by default. As @liyimeng suggested, running git inside of a container is probably the best solution. Depending on your use case you can also use a different console and install git with a package manager.

**Comment by digitalLumberjack** [comment]
Thank you for your advice :)
