### ISSUE TITLE
Quick question about service ordering semantics (io.rancher.os.before & io.rancher.os.after)

### ISSUE THREAD

**Issue by albertdb** [rancher/os#874]
Given a `foo` service definition containing following labels:
`io.rancher.os.before: bar`
`io.rancher.os.after: baz`

`foo` service is launcher before `bar` and after `baz`
or
`bar` service is launcher before `foo`, and `baz` after `foo`
?

It's not explained in docs.

Thank you.

**Comment by joshwget** [comment]
The first case is correct (baz -> foo -> bar). I'll leave this issue open until we update the docs to be more explicit about ordering.

**Comment by deniseschannon** [comment]
updated docs
