### ISSUE TITLE
Support Docker 1.11.0

### ISSUE THREAD

**Issue by frol** [rancher/os#886]
Docker 1.11.0 has been [released](https://github.com/docker/docker/releases).

I'm not sure how relevant this warning to RancherOS, but here is a note left to the 1.11.0 release:

> IMPORTANT: With Docker 1.11, a Linux docker installation is now made of 4 binaries (docker, docker-containerd, docker-containerd-shim and docker-runc). If you have scripts relying on docker being a single static binaries, please make sure to update them. Interaction with the daemon stay the same otherwise, the usage of the other binaries should be transparent. A Windows docker installation remains a single binary, docker.exe.

**Comment by ibuildthecloud** [comment]
Unfortunately it will take us maybe a month to support 1.11 in rancheros because of the various changes in 1.11.  Overall it's going to make RancherOS much better though.

**Comment by frol** [comment]
I'm not in a hurry for 1.11.0. I have just noticed that it is there, and there was no place in Rancher mentioned the new release. Thus, I thought it would be good to let you know just in case you missed it.

*Thank you, Rancher team, for this solid and nice-looking project which helps me to manage my small Docker cluster!*

**Comment by hwinkel** [comment]
@frol the point is that get.docker.com is very aggressive in installing the always newest version and makes installing a older one not so easy. Made the experience today by trying to install the 1.10.3 mac toolbox and the first boot2docker run updates directly to 1.11. I think I don't really like this...

**Comment by lavvy** [comment]
Yeah i wish there should be a documentation on how to install docker by version. Cos the only one most of know is running the script in get.docker.com

**Comment by ryansch** [comment]
@lavvy: http://docs.rancher.com/os/configuration/custom-docker/

**Comment by deniseschannon** [comment]
In v0.5.0, we support docker 1.11
