### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by szepeviktor** [rancher/os#887]
Could you add changelog in this repo as
https://forums.rancher.com/c/announcements
seems to be unmaintained.
Thanks.

**Comment by szepeviktor** [comment]
Maybe in the release comment https://github.com/rancher/os/releases

**Comment by deniseschannon** [comment]
@szepeviktor There was a delay in updating as the docs are not quite updated with changes that we've made since v0.4.3, but I've updated the changes for v0.4.4.

**Comment by szepeviktor** [comment]
Thank you.
