### ISSUE TITLE
why there is release commit in the git repo?

### ISSUE THREAD

**Issue by liyimeng** [rancher/os#888]
Hi, 
This is a question on the dev environment than an issue on the rancheros. I find it is not possible to checkout the commit that the official release was made, e.g. v4.4 is at 8afcd69. But if you do a 

git checkout 8afcd69 

In your repo, it will report a bad object. Can anyone explain how this could happen? 

BR/Liyi

**Comment by ibuildthecloud** [comment]
Try `git fetch -t ...`.  I believe it's because the commit is not on a branch, but just one off and tagged.  We will change this in the future.

**Comment by liyimeng** [comment]
Thanks @ibuildthecloud! Now I can be calm with ease. :)

BTW, ubuntu 16.04 now have zfs built into kernel. Will rancheros follow?  I was about to make a PR to have zfs built into kernel, not sure if that will be welcome.

**Comment by ibuildthecloud** [comment]
@liyimeng I'm afraid of the legal implication there.  Canonical has a much bigger legal team :)  You can definitely get ZFS to work in RancherOS, but I don't think we will include it by default.

**Comment by liyimeng** [comment]
I read Internet, some ZFSonLinux guys say it is legally to have zfs in Kernel and then see Ubuntu is doing so. Make me believe the legal issue was resolved. Did not know that  legal = bigger legal team though :)

Anyone, thanks so much again!  I will close this issue now.

**Comment by ibuildthecloud** [comment]
@liyimeng Apparently it's hard to get lawyers to agree: https://sfconservancy.org/blog/2016/feb/25/zfs-and-linux/

**Comment by liyimeng** [comment]
@ibuildthecloud surprise, surprise that it is GPL guys shout out. The discussion I read have been looking from Oracle perspective.
