### ISSUE TITLE
Share mount propogation

### ISSUE THREAD

**Issue by deniseschannon** [rancher/os#905]

**Comment by faddat** [comment]
This sounds delightful.  Not entirely sure that it is what I think it is, but if it is.... *delightful*

**Comment by deniseschannon** [comment]
Verified with @cloudnautique that this working as expected in v0.5.0-rc1

**Comment by deniseschannon** [comment]
Able to run `docker run -it -v /run:/run:shared alpine sh` with no issues.

**Comment by pwFoo** [comment]
Hi @deniseschannon, I can't find anything about docker volume shared mount propagation... Could you post a link or explain it?

**Comment by deniseschannon** [comment]
@pwFoo The docs site will be updated with information about it. But this is from our new docs site:

By default, `/media` and `/mnt` are mounted as shared in the console container. This means that mounts within these directories will propogate to the host as well as other system services that mount these folders as shared.

See [here](https://www.kernel.org/doc/Documentation/filesystems/sharedsubtree.txt) for a more detailed overview of shared mounts and their properties.

**Comment by pwFoo** [comment]
Thanks for explanation! :)

**Comment by deniseschannon** [comment]
Thanks to @joshwget for writing it. I just copied it from the new docs site.
