### ISSUE TITLE
Support for scheduling containers with multi AZ High Availability

### ISSUE THREAD

**Issue by ashishgupta1989** [rancher/os#913]
I have 6 instances running on AWS with 2 instances on each availability zone, so I have 6 hosts in my rancher Dashboard, with labels:
az:us-west-2a(key:value) - 2 instances
az:us-west-ab(key:value) - 2 instances
az:us-west-2c(key:value) - 2 instances

My use case is, I am running a service with 3 containers and I want to schedule it in such a way that at least one container should run on each availability zone i.e.

one container should run on one of the instance having label az:us-west-2a(key:value)
one container should run on one of the instance having label az:us-west-2b(key:value)
one container should run on one of the instance having label az:us-west-2c(key:value)

**Comment by joshwget** [comment]
This seems to be a request for Rancher, not RancherOS. Would you mind filing an issue in [rancher/rancher](https://github.com/rancher/rancher) instead?

**Comment by ashishgupta1989** [comment]
Yes, will do that.

**Comment by ashishgupta1989** [comment]
Here is the issue link on rancher in case anybody wants the same: https://github.com/rancher/rancher/issues/4705
