### ISSUE TITLE
How to init RancherOS instance using cloud_init.yml + vagrant + vm

### ISSUE THREAD

**Issue by zot24** [rancher/os#916]
I'm running RancherOS 0.4.3 on vagrant machine I was wondering how can I pass my `cloud-init.yml` when `vagrant up` to initialise my machine.

**Comment by deniseschannon** [comment]
We've moved away from using vagrant and recommend using docker-machine. We will no longer be able to provide support to our vagrant setup. 

FYI, even with docker-machine, you will not be able to pass in a cloud-config.yml.

Let me know if you have further questions.

**Comment by zot24** [comment]
Thanks you so much for you answer @deniseschannon !
