### ISSUE TITLE
Cattle hosts shutting down as soon as they come up

### ISSUE THREAD

**Issue by luispabon** [rancher/os#935]
I'm trying to bring up a Kubernetes cluster on AWS at the moment. I have the very latest version of the rancher server running on a small instance to try things out.

When I add in hosts and ask them to use a RancherOS AMI, initially they boot up then Rancher server shuts them down after a while. The AMI is rancheros-v0.4.4-hvm-0 (ami-aec548dd).

Error message on the UI:
```
Error detecting OS: Too many retries waiting for SSH to be available. Last error: Maximum number of retries (60) exceeded
```

Error message on the rancher-server logs:
```
rancher-server    | 2016-05-13 09:47:21,989 ERROR [20a68d1a-6495-4c6d-973d-bedb56bd9cca:7653] [instance:427] [instance.start->(InstanceStart)] [] [utorService-124] [i.c.p.process.instance.InstanceStart] Failed to Scheduling for instance [427] 
rancher-server    | time="2016-05-13T09:47:22Z" level=info msg="stderr: Error creating machine: Error running provisioning: error installing docker: " resourceId=1ph13 
rancher-server    | time="2016-05-13T09:47:22Z" level=info msg="stderr: " resourceId=1ph13 
rancher-server    | time="2016-05-13T09:47:22Z" level=info msg="starting cleanup..." machine name=ubu-a01 
rancher-server    | 2016-05-13 09:47:22,567 ERROR [d269d521-34fe-4bc9-b01a-f28ecce4fd7e:7652] [instance:426] [instance.start->(InstanceStart)->instance.allocate->(InstanceAllocate)] [] [cutorService-30] [c.p.a.e.i.AllocatorEventListenerImpl] No allocator handled [EventVO [id=23a773ea-8df3-4e28-b928-8c3e80933582, name=instance.allocate, previousNames=null, replyTo=reply.866013454397579240, resourceId=426, resourceType=instance, publisher=null, transitioning=null, transitioningMessage=null, transitioningInternalMessage=null, previousIds=null, data={}, time=Fri May 13 09:47:22 UTC 2016, listenerKey=null, transitioningProgress=null]] 
rancher-server    | 2016-05-13 09:47:22,570 ERROR [d269d521-34fe-4bc9-b01a-f28ecce4fd7e:7652] [instance:426] [instance.start->(InstanceStart)->instance.allocate] [] [utorService-164] [c.p.e.p.i.DefaultProcessInstanceImpl] Unknown exception io.cattle.platform.eventing.exception.EventExecutionException: Scheduling failed: No candidates available
```

Host logs found at http://pastebin.com/hGpQaqhT, too big to paste here.

Hosts are all t2.micro on eu-west-1.

**Comment by aemneina** [comment]
Hey @luispabon , any chance you want to try with rancheros-v0.4.5-hvm-0 (ami-58fe0238)? I am able to successfully run rancher server/agents on this build.

**Comment by luispabon** [comment]
@aemneina just tried to spin up that AMI to no avail:

![image](https://cloud.githubusercontent.com/assets/6388823/15387737/89d5304c-1da6-11e6-9ee5-f68cea803e2b.png)

**Comment by luispabon** [comment]
Okay so I managed to make it run, found the right 0.4.5 image on eu-west-1. Problem was the ssh username and in general stuff that could be considered as UX issues on the UI.

I would recommend:

a) Set default AMI to latest Rancher OS available for the selected VPC zone, not Ubuntu 15.10
b) Set default `ssh username` to rancher.

Makes no sense to have this lovely Rancher ecosystem when all minions are defaulted to Ubuntu (a non LTS version of it at tha) I would say!

**Comment by deniseschannon** [comment]
@luispabon Since we're calling docker-machine commands when using the UI, we've always left the defaults. 

We wouldn't want to put a RancherOS AMI ID as we are always adding newer versions of RancherOS and the UI would quickly be outdated and pointing to an old version of RancherOS. We do add a link to the RancherOS AMIs under the AMI field and at the link it does indicate that you need to use the *rancher* user.

**Comment by zsustar** [comment]
faced same issue, I really suggest put the "rancher"  as the default user name but not "ubuntu" in the SSH user column.

I didn't know the SSH user name until I read the post here, as there's no where mentioned the SSH name from following URL
https://docs.rancher.com/rancher/v1.2/en/hosts/amazon/
