### ISSUE TITLE
v0.4.5: cannot switch to ubuntu console

### ISSUE THREAD

**Issue by sheng-liang** [rancher/os#937]
Installing 0.4.5 on bare metal. After installing the OS, switch to Ubuntu console, and then reboot. After reboot it fell back to busybox after seeing error messages on the console. Console screen shots attached.

![image](https://cloud.githubusercontent.com/assets/9485278/15263495/7187024e-191f-11e6-97b0-e0a67395be51.png)

![image](https://cloud.githubusercontent.com/assets/9485278/15263512/92839e58-191f-11e6-9126-f2b63659f872.png)

**Comment by sheng-liang** [comment]
Why are we trying to fetch something from the network? Ubuntu console container has already been pulled. We should not be attempting any network connection during machine start (and especially not before the network has been configured as is the case here.)

**Comment by sheng-liang** [comment]
I tried the same steps on a VMware VM and it worked. So the issue is only reproducible on one of our bare metal servers with 10Gbe NIC.

**Comment by joshwget** [comment]
Tested with a v0.5 RC and confirmed that this is fixed!
