### ISSUE TITLE
Unable to run "ros install" on v0.5 

### ISSUE THREAD

**Issue by deitch** [rancher/os#942]
**RancherOS Version: v0.5**

**Where are you running RancherOS? vbox**

If I boot a clean RancherOS v0.5 image, and then do `ros install /dev/sda`, I get the following:

````
Installing from 'rancher/os:123f4db-dirty' locally
Pulling repository docker.io/rancher/os
docker: Tag 123f4db-dirty not found in repository docker.io/rancher/os.
See 'usr/bin/docker.dist run --help'.
FATA[0007] Failed to run install  err=exit status 125
````

When I run the same in v0.4, it tries and succeeds to pull `docker.io/rancher/os:v0.4`.

It appears that it is failing because the current build version of `rancher/os:<current>` is not available locally, but never was pushed out to docker hub.

Why does it need that at all? Shouldn't the `ros` scripts (or at least those for `ros install`) be installed into the initrd (and hence the iso) itself? They are right there as part of `scripts/installer/` anyways.

**Comment by joshwget** [comment]
The scripts in `scripts/installer/` aren't actually bundled with RancherOS itself, but the installer image. The image also contains everything else needed to install a particular version, so it doesn't reuse anything from the running version of RancherOS.

I think everything you've described is expected based on how the installer works. Feel free to reopen if you still think there's an issue.

**Comment by deitch** [comment]
Understood. I prefer a design wherein the running version is what gets installed, but that's a philosophical difference.

However, it still doesn't work (and I cannot reopen; no rights on the repo). 

Let's simplify it: how do I do an `ros install` when running v0.5? I cannot.
