### ISSUE TITLE
"Waiting for Docker" times out on upgrade to 0.4.5

### ISSUE THREAD

**Issue by michaellopez** [rancher/os#944]
**RancherOS Version: (ros os version)**
0.4.5

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
Mac OS X El Capitan
VirtualBox 5.0.20

I am trying to upgrade from 0.4.2 to 0.4.5 but I am unable to do so for this node. I successfully managed to upgrade an identical node, but this one is causing me trouble.

![0 4 5-timeout](https://cloud.githubusercontent.com/assets/487039/15320974/e78404e4-1c33-11e6-9a65-25cd79fec70f.png)

The image shows me trying to boot from the ISO. It gets stuck. If I remove the hard disk from the VM it boots successfully, so I guess there is some state or something on the hard disk that is causing this. Any idea what it could be? I've looked at all the logs in `/var/log/` but can't find anything. I found [this thread](https://forums.rancher.com/t/rancheros-bare-metal-no-longer-starts-solved/2656) but unfortunately it did not resolve my problem.

I am able to upgrade from 0.4.2 to 0.4.3 and 0.4.4. But consistently getting this error for 0.4.5.

Any help is appreciated.

**Comment by deniseschannon** [comment]
Do you still have this VM around? 

You should still be able to log in.

Can you share your `sudo systmem-docker logs` and `/var/log/docker.log`?

**Comment by michaellopez** [comment]
@deniseschannon Thanks for the response. I was unable to login when this happened, "Operation timed out" when trying to SSH. Trying to reproduce this now on the same VM I don't get stuck on this part anymore, it continues but does still crash like my report in #945. I have a few more identical nodes to upgrade, so if I hit this again I will re-open. Closing for now and focusing on #945
