### ISSUE TITLE
API Error (500): invalid diffID for layer 0...

### ISSUE THREAD

**Issue by michaellopez** [rancher/os#945]
**RancherOS Version: (ros os version)**
Upgrade from 0.4.2 to 0.4.4

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
Mac OS X El Capitan
VirtualBox 5.0.20

I ran `sudo ros os upgrade -i rancher/os:v0.4.4` answered, `yes` and `yes` to upgrade and reboot. After reboot I get this:

![0 4 4-invalid-diffid](https://cloud.githubusercontent.com/assets/487039/15321640/106a9a0e-1c38-11e6-8d3c-f443d7b1884c.png)

I am trying to upgrade all my nodes from 0.4.2 to 0.4.5 and so far 1/3 has worked. My other issue is in #944 

What did I do wrong 😿

**Comment by joshwget** [comment]
This was likely a Docker upgrade issue. It switched to content addressable storage between these releases. These types of issues shouldn't occur in any recent releases.
