### ISSUE TITLE
Resizefs behind a proxy isn't working

### ISSUE THREAD

**Issue by deniseschannon** [rancher/os#946]
**RancherOS Version: (ros os version)**
v0.4.5

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**

Notes:
We need to test building a server behind a proxy and trying to do a resize on the disk.

I’m wondering if it’s trying to perform the resize before the proxy is in place, hence the os-resizefs container never gets pulled down. He has examined the local images and says that the container isn’t there and the disk hasn’t been resized.

**Comment by joshwget** [comment]
Confirmed with rancher/os:v0.5.0-rc1. Resize functionality no longer needs to pull an image, so this should be fine behind a proxy.
