### ISSUE TITLE
Permission Denied for nfs mount on > 0.4.3

### ISSUE THREAD

**Issue by ryansch** [rancher/os#948]
**RancherOS Version: (ros os version)**
0.4.4, 0.4.5

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
docker-machine

I'm using dinghy (https://github.com/codekitchen/dinghy) to bootstrap rancherOS for development.  At one point in the setup, dinghy runs a mount command to hook up `/Users` in the VM (https://github.com/codekitchen/dinghy/blob/master/cli/dinghy/machine.rb#L108).  On 0.4.3 and earlier this works without issue.  Starting with 0.4.4 this command always returns a permission denied error.  I've tried manually running the command as root but it seems that the console container no longer has the permission to run mount.  How do I resolve this?

**Comment by ryansch** [comment]
I can't reproduce this on v0.5.0.  Seems to be fixed!

**Comment by joshwget** [comment]
Thanks for the update! Happy to hear this magically solved itself :smile:
