### ISSUE TITLE
Kubelets forever "initializing"

### ISSUE THREAD

**Issue by luispabon** [rancher/os#949]
**RancherOS Version: (ros os version)**
0.4.5 (ami-6343d610)

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
AWS EC2

I've launched a kubernetes cluster on AWS from latest server 1.1.0-dev and RancherOS 0.4.5 for the minions.

The kubelet services on each node always show as initializing:

![image](https://cloud.githubusercontent.com/assets/6388823/15389540/6404dbf2-1daf-11e6-8fcb-40c48c31113a.png)

Nodes seem OK and part of the kubernetes cluster though, I can launch services and rcs into them.

**Comment by deniseschannon** [comment]
I'm unable to reproduce in a setup that is also running RancherOS v0.4.5. 

This issue would be better suited in rancher/rancher. I will close and you can open a new issue in that repo. 

Can you confirm that your  cross host networking is working? Can you exec into one of the network agents on one host and ping the IP (10.42.x.x) of another network agent? Typically, healthcheck will get stuck in initializing if cross host communication isn't working. 

If cross host communication isn't working, hav eyou confirmed your security groups are set up correctl? You will need UDP ports 500 and 4500 open for our ipsec tunneling.
