### ISSUE TITLE
Upgrade OS version and nothing change

### ISSUE THREAD

**Issue by CBR09** [rancher/os#950]
**RancherOS Version: (ros os version)**

> [rancher@rancher ~]$ sudo ros -v
> ros version v0.4.4

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**

> Virtualbox

I want to upgrade from v0.4.4 to v0.4.5
I typed "sudo ros os upgrade" and confirm yes twice. After reboot, I ssh and saw nothing change (Note: I installed rancher on disk)

> [rancher@rancher ~]$ sudo ros -v
> ros version v0.4.4

Expection: ros version v0.4.5
Thanks

**Comment by deniseschannon** [comment]
For the first confirmation, it confirms that you want to upgrade to `rancher/os:v0.4.5`. Is that what you also see?

I had no issues upgrading from v0.4.4 to v0.4.5. Are you sure that you removed the ISO?

**Comment by CBR09** [comment]
Oh thanks @deniseschannon, I forgot to remove the rancher ISO, now it works.
