### ISSUE TITLE
Could you add curl to the rancher iso ? 

### ISSUE THREAD

**Issue by dexterddit** [rancher/os#963]
Hi, 

Curl could be very useful on the rancher iso ? As some firewalls / proxys need NTML authentifcation or some kind of user login ,and wget doesn`t quite work with everthing , which makes installing rancher OS hard due to now internet connectivity . 

Thanks , 

Andrei

**Comment by deniseschannon** [comment]
There have been previous requests of adding curl into RancherOS, but we have made a conscious decision to not include it into RancherOS. 

https://github.com/rancher/os/issues/405

**Comment by vincent99** [comment]
`docker run animagewithcurl curl URL`

Or I put one up that's just curl a while ago, `docker run vincent99/curl http://url`

**Comment by MichelDiz** [comment]
Curl inside a Docker container has a different network. To be sure in our tests with curl, we use the OS network. Like this we know that are nothing else interfering with the tests.

Could you at least allow the Curl installation via package or script? making it optional.

**Comment by vincent99** [comment]
Anything you can run on the host you can run in a container.. `--net=host`

No.  The default console is intentionally minimal and not persistent and has no package manager.  You can switch to Ubuntu or one of the other consoles and install whatever you want.

**Comment by xeha-gmbh** [comment]
`[rancher@rancher ~]$ docker run --net=host vincent99/curl curl -sfL https://get.k3s.io | sh -
Unable to find image 'vincent99/curl:latest' locally
latest: Pulling from vincent99/curl
6d987f6f4279: Pulling fs layer
6bf1d4a1062b: Pulling fs layer
6d987f6f4279: Verifying Checksum
6d987f6f4279: Download complete
6bf1d4a1062b: Verifying Checksum
6bf1d4a1062b: Download complete
6d987f6f4279: Pull complete
6bf1d4a1062b: Pull complete
Digest: sha256:85aea1846e2e9b921629e9c3adf0c5aa63dbdf13aa84d4dc1b951982bf42d1a4
Status: Downloaded newer image for vincent99/curl:latest
[ERROR]  Can not find systemd or openrc to use as a process supervisor for k3s`
