### ISSUE TITLE
rancher.cloud_init.datasources=[url] regression

### ISSUE THREAD

**Issue by dx9** [rancher/os#965]
**RancherOS Version: v0.4.5**

**Where are you running RancherOS? baremetal**

sudo system-docker logs cloud-init    
+ MOUNT_POINT=/media/config-2
++ ros dev LABEL=config-2
+ CONFIG_DEV=
+ mkdir -p /media/config-2
+ '[' -e '' ']'
+ mount -t 9p -o trans=virtio,version=9p2000.L config-2 /media/config-2
+ true
+ cloud-init -save -network=true
time="2016-05-31T01:43:19Z" level=info msg="Running cloud-init: save=true, execute=false" 
time="2016-05-31T01:43:19Z" level=warning msg="Error adding kernel params to config" cfg=&{[] []  rancher {map[] map[all-volumes:0xc8202ba300 system-volumes:0xc82025cc00 ntp:0xc82025c000 user-volumes:0xc82025d500 wait-for-network:0xc82025d800 acpid:0xc8202ba000 cloud-init-pre:0xc8202ba900 network:0xc8202bb800 container-data-volumes:0xc8202bb200 network-pre:0xc8202bbb00 udev:0xc82025cf00 docker:0xc8202bb500 preload-system-images:0xc82025c300 preload-user-images:0xc82025c600 syslog:0xc82025c900 udev-cold:0xc82025d200 cloud-init:0xc8202ba600 command-volumes:0xc8202bac00 console:0xc8202baf00 wait-for-network-pre:0xc82025db00] map[state-script:0xc8202f3800 udev-bootstrap:0xc8202f3b00] map[autoformat:0xc8202f3200 udev-autoformat:0xc8202f3500] {false [] [daemon -s overlay -b none --restart=false -g /var/lib/system-docker -G root -H unix:///var/run/system-docker.sock --userland-proxy=false] []     []  false} {[configdrive:/media/config-2]} false false false false [] map[] [] {[] {[] []} map[] []   } {[] {[8.8.8.8 8.8.4.4] []} map[] []   } map[core:{https://raw.githubusercontent.com/rancher/os-services/v0.4.5}] {map[]} { auto LABEL=RANCHER_STATE false [] false false  auto LABEL=RANCHER_OEM} {false [] [daemon --log-opt max-size=25m --log-opt max-file=2 -s overlay -b docker-sys --fixed-cidr 172.18.42.1/16 --restart=false -g /var/lib/system-docker -G root -H unix:///var/run/system-docker.sock --userland-proxy=false] []     []  false} {https://releases.rancher.com/os/releases.yml rancher/os } {false [--tlsverify --tlscacert=/etc/docker/tls/ca.pem --tlscert=/etc/docker/tls/server-cert.pem --tlskey=/etc/docker/tls/server-key.pem -H=0.0.0.0:2376] [daemon --log-opt max-size=25m --log-opt max-file=2 -s overlay -G docker -H unix:///var/run/docker.sock] []     []  false}}} cmdLine=[114 97 110 99 104 101 114 46 112 97 115 115 119 111 114 100 61 114 97 110 99 104 101 114 32 114 97 110 99 104 101 114 46 99 108 111 117 100 95 105 110 105 116 46 100 97 116 97 115 111 117 114 99 101 115 61 91 117 114 108 58 104 116 116 112 58 47 47 49 57 50 46 49 54 56 46 48 46 53 58 57 48 57 48 47 104 111 115 116 115 47 70 71 90 76 77 76 49 45 52 99 52 99 52 53 52 52 45 48 48 52 55 45 53 97 49 48 45 56 48 52 99 45 99 54 99 48 52 102 52 100 52 99 51 49 47 99 108 111 117 100 45 99 111 110 102 105 103 46 121 97 109 108 93 10] data=map[rancher:map[password:rancher cloud_init:map[datasources:[url:http://192.168.0.5:9090/hosts/FGZLML1-4c4c4544-0047-5a10-804c-c6c04f4d4c31/cloud-config.yaml]]]] err="Cannot resolve [url:http://192.168.0.5:9090/hosts/FGZLML1-4c4c4544-0047-5a10-804c-c6c04f4d4c31/cloud-config.yaml] into <[]string Value> at line 105, column 17" 
time="2016-05-31T01:43:19Z" level=info msg="Checking availability of \"cloud-drive\"\n" 
time="2016-05-31T01:43:19Z" level=info msg="Fetching user-data from datasource cloud-drive" 
2016/05/31 01:43:19 Attempting to read from "/media/config-2/openstack/latest/user_data"
time="2016-05-31T01:43:19Z" level=info msg="Fetching meta-data from datasource of type cloud-drive" 
2016/05/31 01:43:19 Attempting to read from "/media/config-2/openstack/latest/meta_data.json"
time="2016-05-31T01:43:19Z" level=error msg="Unrecognized user-data\n" 
time="2016-05-31T01:43:19Z" level=info msg="Written to /var/lib/rancher/conf/cloud-config.d/boot.yml:\n" 
time="2016-05-31T01:43:19Z" level=info msg="Written to /var/lib/rancher/conf/metadata:\nPublicIPv4: []\nPublicIPv6: []\nPrivateIPv4: []\nPrivateIPv6: []\nHostname: \"\"\nSSHPublicKeys: {}\nNetworkConfig: null\n"

**Comment by janeczku** [comment]
@dx9 When setting configuration values via kernel command line or `sudo ros config set`, list items that contain special characters (e.g. `:`, `,`) must now be put in quotes. Please change your kernel parameter to `rancher.cloud_init.datasources=['url:http://192.168.0.5:9090/hosts/...']`.

Verified working:
```
kernel https://releases.rancher.com/os/v0.4.5/vmlinuz rancher.cloud_init.datasources=['url:https://gist.githubusercontent.com/janeczku/...']
```

**Comment by deniseschannon** [comment]
@dx9 Please let me know if @janeczku fixes your issues.

**Comment by dx9** [comment]
@janeczku @deniseschannon yep all good now. Thanks guys.
