### ISSUE TITLE
Unable to obtain IPv4 address

### ISSUE THREAD

**Issue by jeremy24** [rancher/os#974]
**RancherOS Version: (ros os version)**
v0.4.5
**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**

baremetal on an 8 core i7 with 16GB of RAM

After configuring the network interfaces via ros, adding dhcp, enabling IPv4 and setting the correct gateway, I am unable to ever obtain any  IPv4 address.

I have tried 2 fresh downloaded images, and multiple interface configs, using wildcards, the specific name, and the mac of the physical adapter, and none have worked, i only ever get an IPv6 address.

**Comment by janeczku** [comment]
@jeremy24 could you paste the network configuration (`sudo ros config export`)?

**Comment by jeremy24** [comment]
![image](https://cloud.githubusercontent.com/assets/13365690/15747262/f4f6ebc0-28a7-11e6-9f6a-3d09bb814d0b.png)

Apologies for it being a picture, I don't have a way to copy it off the system right now

**Comment by janeczku** [comment]
You can't have both DHCP and IPv4ll on the same interface. Also, why are you setting the gateway in addition to DHCP? Please describe your use case.

**Comment by jeremy24** [comment]
I tried it with just DHCP set to true, along with other variants.   

The use is for testing, my company is transitioning to a docker based infrastructure, vs using hyper-v VMs and monolith web apps.

I am trying to get rancherOS running on an older dell precision m6500 laptop we had setting around, because we want to test a  couple different options, rancherOS, ubuntu snappy, and coreOS to see what works best for us, by running the same env of containers via swarm on each.  That's why its on a laptop right now.

Right now it need to get a dhcp address, since they don't like setting up dns entries for test boxes. In prod it would have a static.

**Comment by janeczku** [comment]
Assuming you are booting from the ISO and haven't yet persisted RancherOS to disk:
1. Reboot to start with a clean configuration
2. Paste output of `ip addr` and `ifconfig`
3. Enable debug logging with `sudo ros config set rancher.debug true`
4. Restart network with `sudo ros service restart network`
5. Paste output of `sudo system-docker logs network`
6. Paste output of `sudo system-docker exec network cat /var/log/messages | grep dhcp`

**Comment by jeremy24** [comment]
So this is strange, I had snappy ubuntu running on the laptop on a usb and didn't change anything; I then rebooted to rancher, without changing any config values and now I'm getting an IP just fine.  There may be something strange going on with our internal network.  

Thanks for the quick response to the issue, I'm marking it as closed

**Comment by janeczku** [comment]
Glad you figured it out!
